### ISSUE TITLE
Eclipse Help issue producing toc file

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1078]
Converted from [SourceForge issue 1819660](http://sourceforge.net/support/tracker.php?aid=1819660), submitted by easirois

When building for Eclipse, this map works fine (called overview.ditamap):

    <map title="something">
      <topicref format="ditamap" href="DITA-articles.ditamap"/>
    </map>

However, if I import that into an Eclipse map, it does not work:

    <plugin id="com.example.doc">
      <pluginmeta>
        <providerName>IBM</providerName>
        <plugininfo>
          <pluginname>My Component system</pluginname>
          <vrmlist><vrm version="1.0"/><vrm version="2.0"/></vrmlist>
        </plugininfo>
      </pluginmeta>
      <tocref href="overview.ditamap"/>
    </plugin>

In that case, the generated file overview.xml is no longer correct. It looks like the override for plugin maps will incorrectly modify processing for the normal map as well.

The issue occurs when we have the following use case:
eclipsemap --> map --> map -->topics

The processing produces the following toc file:

    <?xml version="1.0" encoding="utf-8"?>
    <?NLS  TYPE="org.eclipse.help.toc"?>
    <toc label="Test toc" topic="DITA-articles.ditamap">
       <topic label="DITA-articles.ditamap" href="DITA-articles.ditamap"/>
    </toc>

It should instead produce something like this:

    <?xml version="1.0" encoding="utf-8"?>
    <?NLS  TYPE="org.eclipse.help.toc"?>
    <toc label="Test toc" topic="DITA-rm.html">  
       <topic label="Introduction to the Darwin Information Typing Architecture" href="DITA-rm.html">
          <topic label="Specializing topic types in DITA" href="DITA-dsf.html"/>
          <topic label="Specializing domains in DITA" href="DITA-domains.html"/>
          <topic label="How to define a formal information architecture with DITA map domains" href="DITA-mapdomains.html"/>
       </topic>
    </toc>

**Comment by robander** [comment]
I think that this is resolved now - at least, when I do a `pluginmap -> mapA -> mapB -> content` organization, the generated `mapA.xml` file has the topics (it does not have a reference to the ditamap). I get new errors from the code that overrides linking for eclipsehelp output, but that seems entirely separate (and may already have an issue open elsewhere. I think we can mark this one obsolete.
