### ISSUE TITLE
Inconsistent PIs for linktext generated from navtitle

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1094]
Converted from [SourceForge issue 2903326](http://sourceforge.net/support/tracker.php?aid=2903326), submitted by stokecn

DITA-OT1.5 m23

I am using `<topicgroup toc="no">` and child topicrefs to simulate keydefs.

In my keydef (topicrefs) file, I have:

```
<topicgroup toc="no">
<topicref keys="WWW_SF"  navtitle="navtitle text"  href="http://sourceforge.net" scope="external"/>
</topicgroup>
```

The keydefs (topicrefs) are imported into the project ditamap via mapref.  In my project ditamap I have this:

```
<reltable>
<relrow>
<relcell>
<topicref id="mapSFLink" keyref="WWW_SF"/>
</relcell>
<relcell>
<topicref href="testTopic.dita"/>
</relcell>
</relrow>
</reltable>
```

And in testTopic.dita, to test xref output, I have:

```
<xref id="aickeyWWWTrademark" keyref="WWW_SF"/>
```

When I build this project, the navtitle text is used as the link text for both xref and topic/link output. However, the PI assigned to the text derived from the navtitle is different for each type of link. The following is taken from stage1.xml using PDF2, but it's also true forthe  htmlhelp temp files.

When I build, I get the following for the xref:

```
<xref class="- topic/xref " href="http://sourceforge.net" id="testTopicWWWSFID" keyref="WWW_SF" scope="external" xtrc="xref:1"  xtrf="C:\DITA-OT1.5m23-112209\assembledContent\20091124134154622\miniTestAliases.dita">
Note the PI--><?ditaot usertext?>navtitle text</xref>
```

And I get the following for the reltable link:

```
<link class="- topic/link " href="http://sourceforge.net" mapclass="- map/topicref " role="friend" scope="external" xtrc="topicref:6" xtrf="C:\DITA-OT1.5m23-112209\assembledContent\20091124134154622\miniTestBookmap.ditamap">
<?ditaot usertext?>
<linktext class="- topic/linktext ">
Note the PI--><?ditaot gentext?>navtitle text</linktext>
</link>
```

**Comment by robander** [comment]
Marking as obsolete. After 6 years of seeing this bumped from release to release, I'm not anticipating activity on it and not seeing a straightforward way to change the behavior.
