### ISSUE TITLE
Generate title page during bookmap->XHTML build

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1126]
Converted from [SourceForge issue 1841976](http://sourceforge.net/support/tracker.php?aid=1841976), submitted by dhjohnso2000

When I generate XHTML output for the taskbook example sample using OT 1.4.1, the title page is NULL. A title page is produced for PDF.

**Comment by mucher1** [comment]
I'm sorry, but why was this marked obsolete? This feature is still absent in the current version of the OT. A page with (say) title and subtitle would be very useful, the XSLT being relatively easy to customize.

**Comment by jelovirt** [comment]
The HTML5 output generates an index page and that's the default implementation. If a separate cover page file is needed, that can be implemented as an extension plugin.

**Comment by mucher1** [comment]
Thanks for the explanation. I'm relatively new to this, and making customizations to an existing XSLT file seemed a lot less intimidating than messing with the ANT build files, so I guess I was hoping for a small miracle.
