### ISSUE TITLE
Figure/table numbering mismatch in topicpull vs dita2html

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1131]
Converted from [SourceForge issue 1985926](http://sourceforge.net/support/tracker.php?aid=1985926), submitted by debbiep-sf

The topicpull preprocess stage puts link text into an empty xref-to-a-figure such as "Figure 1".

The main dita2xhtml stage creates captions on figures such as "Figure 1".

The code for these two stages is independent and could diverge, especially since the topicpull code is more specialization-aware than the dita2xhtml code.

This code should be factored out and called from both places so that cross-references and captions agree on the figure number.

All of the above applies to table numbering too.

(I'm particularly worried about builds to PDF and other merged output, because the numbering of cross-references will be per-topic, and the numbering of captions will be consecutive across the map.)

**Comment by robander** [comment]
Closing this as inactive - nobody on the development team is currently expecting to implement. It can be reopened if an interested party wishes to work on it.
