### ISSUE TITLE
Support generating text only reference in reltable

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1132]
Converted from [SourceForge issue 1989420](http://sourceforge.net/support/tracker.php?aid=1989420), submitted by amberink

Requirement: be able to use relationship table for all references, including text only references to other deliverables.

Enhancement: support processing `<topicref>` with no href specified and generate text in <linktext> element.

Example DITA markup:

``` xml
<topicref>
  <topicmeta>
    <linktext>For more information about twinkies, see "All about Twinkies".</linktext>
  </topicmeta>
</topicref>
```

in a relationship table.

```
Output: For more information about twinkies, see "All about Twinkies".
```

**Comment by robander** [comment]
For some reason decided to take a look at this one and found 3 different issues all with a simple test case:

- Original issue of course is still there: a `linktext`-only entry in the reltable doesn't get added to the topic
- If a text-only link appears inside of a topic, the `linktext` element is dropped by the `topicpull` step: `<link><linktext>something</linktext></link>` is converted to `<link></link>` (after error message `DOTX028E` that it is missing href/keyref)
- If such an empty link is coded in a topic (or created by that `topicpull` bug), FOP crashes with the following message:
```
      [fop] [ERROR] Anttask - Error rendering fo file: C:\DITA-OT\TEST\
1132textReltable\temp\topic.fo <net.sf.saxon.trans.XPathException: org.apache.fop.f
o.ValidationException: Missing attribute on fo:basic-link: Either external-desti
nation or internal-destination must be specified. (See position 3:405)>net.sf.sa
xon.trans.XPathException: org.apache.fop.fo.ValidationException: Missing attribu
te on fo:basic-link: Either external-destination or internal-destination must be
 specified. (See position 3:405)
```
[1132.zip](https://github.com/dita-ot/dita-ot/files/2117570/1132.zip)
