### ISSUE TITLE
Improve title numbering in PDF2

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1162]
Converted from [SourceForge issue 3486511](http://sourceforge.net/support/tracker.php?aid=3486511), submitted by @jelovirt

PDF2 title number generation should be improved and combined. Currently actual title gets the number from "insertChapterFirstpageStaticContent", number in TOC gets generated by "toc-prefix-text", and bookmarks have no numbering. The code should be combined to make it easier to maintain and extend.

Also, the topicref lookup should be simplified, because merging code now handles duplicate topics and map-id key should always return a single topicref.

**Comment by ColinMaudry** [comment]
I haven't seen any facility in DITA OT 2.0 to add title numbering in PDF2. Did I miss something?

Since I need it, I would contribute the result back here.

Thanks.

**Comment by jelovirt** [comment]
The output is not enabled by default. IIRC just modified the code to make numbering easier. Have you checked the output from http://dita-generator-hrd.appspot.com/pdf-plugin/ with numbering enabled. It does not support section numbering, because it's generally seen as a bad idea.

**Comment by ColinMaudry** [comment]
Thanks, I could snatch the getTitle template that takes care of numbering. And my client wants their section numbered, so I'll manage something. Thanks!
