### ISSUE TITLE
DITAVAL flagging graphics copied to wrong place

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1176]
Converted from [SourceForge issue 3399241](http://sourceforge.net/support/tracker.php?aid=3399241), submitted by @drmacro

GIven a DITAVAL file that references flagging graphics like so:

``` xml
<prop action="flag"
      att="audience"
      val="beginner"
      color="green">
     <startflag imageref="icons/beginner-icon-01.gif">
       <alt-text> Beginner form: </alt-text>
     </startflag>
</prop>
```

If I use this for a map that has topics outside its descendants, the graphics files are copied to the wrong place (one directory above the directory containing the generated FO files) and are thus not resolved in the generated FO.

If I use the same map but located above all its dependencies, then the graphics are in the right location and appear in the resulting FO.

The setting for `generate.outer.copy` appears to have no effect (get same behavior with a value of "1" or '2".

The flagging does work for both maps using the XHTML transform, so it appears to be a problem specific to the PDF transform.

**Comment by robander** [comment]
Just set up a test to see if this still exists in 2.2.4. I'm not sure if the original does but something very similar now exists. Using the old sample files:

- I added a paragraph with `audience="beginner"` into `tasks/garagetaskoverview.xml`. 
- Processed with a version of the DITAVAL above (flag image `icons/flag.jpg`)
- In the temp directory, the new flagging preprocess adjusted the path when placing flag info into the topic, resulting in `imageref="../icons/yukface.jpg"`)
- But when topicmerge combined everything, moving the task from a sub-directory into the map directory, the path was not adjusted a second time, making it incorrect in the merged file
