### ISSUE TITLE
PDF2: Add region-start and region-end in layout-masters.xsl.

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1184]
Converted from [SourceForge issue 3495400](http://sourceforge.net/support/tracker.php?aid=3495400), submitted by @jannylund

I suggest adding region-start and region-end to layout-masters.xsl. They are useful both for when you actually need content in them, and when you want them to have precedence so region-before / region-after gets the same width as region-body.

**Comment by robander** [comment]
Closing this as inactive - nobody on the development team is currently expecting to implement. It can be reopened if an interested party wishes to work on it.
