### ISSUE TITLE
Index generation should be independent of transtype.

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1187]
Converted from [SourceForge issue 3516642](http://sourceforge.net/support/tracker.php?aid=3516642), submitted by @jannylund

DITA-OT contains several different features for generating indexes. (One within PDF2, one used for Eclipsehelp, etc). As index generation and sorting is a rather complex thing, it should be splitted out to not be depending on transtype. The index generation could happen as early as possible and generate an XML file (similar to Eclipsehelp's index.xml?) that can later be processed to match the wanted output.

This would allow users that publish the same content to several platforms to have synchronized indexes in all output formats as well as reduce the code overlap of having several tools to solve the same problem.

**Comment by robander** [comment]
Closing this as inactive - nobody on the development team is currently expecting to implement. It can be reopened if an interested party wishes to work on it.
