### ISSUE TITLE
Localization should be independent of transtype.

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1188]
Converted from [SourceForge issue 3516644](http://sourceforge.net/support/tracker.php?aid=3516644), submitted by @jannylund

Localization should be configured in one place. Currently PDF2 uses an "insertVariable" functionality and XHTML uses the "getString" functionality. This would require splitting out the variable functionality so it would not be part of an output type.

A first step against a better solution would be to make the variable files in an generic format and generate the transtype specific localizations using integrator.xml  (or maybe on the fly?).

**Comment by macksol** [comment]
I am really confused at where we are with this enhancement, any clarification would be helpful.

1/ In the documentation doc/dev_ref/plugin-addgeneratedtext.html - it refers to using "getString" but "getString" is deprecated in favour of "getVariable".
I presume this just means that the documentation needs updated?

2/ the org.dita.pdf2 plugin uses "insertVariable" but this is also deprecated and using standard code produces lots of these deprecated messages in the log.
I presume over time the pdf plugin will be rewritten to use "getVariable" and until then we live with the log messages?

3/ the org.dita.pdf2 plugin (and my heavily customised version of it) used to support string customizations by having the base strings in the cfg/common/vars sub folder with the client specific version in the  customization sub folder. The old code used to check in the cusomtization file first and if it could not find that content then it would look in the base file.
Is this no longer supported?
