### ISSUE TITLE
Add parameter to clean output before publishing

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1199]
Converted from [SourceForge issue 3500331](http://sourceforge.net/support/tracker.php?aid=3500331), submitted by @raducoravu

In the DITA Open Toolkit bundled with Oxygen XML Editor we have a small customization which adds a "clean.output" parameter (which is disabled by default). This parameter cleans the output directory before each publishing and it useful to remove garbage from the output directory, topic files which may no longer be linked in the DITA Map for example.

I think that the DITA OT might benefit of having such a parameter added by default:
http://tech.groups.yahoo.com/group/dita-users/message/26248

**Comment by raducoravu** [comment]
@jelovirt Could this be re-opened? It looks like a maybe useful thing to have in the DITA OT default distribution.

**Comment by jelovirt** [comment]
Which transtype would benefit from this? Or what's the use case?

**Comment by raducoravu** [comment]
XHTML output for example, if you never clean the output at publish time, you will end up with lots of junk (old HTML topics for example) in the output folder.

**Comment by jelovirt** [comment]
I still think this is out of scope for DITA-OT and adds functionality to core code that should be taken care of by the embedding tool.

**Comment by raducoravu** [comment]
Ok

**Comment by jelovirt** [comment]
@robander I'd like to get your vote on this too. I think we should try to keep as much out of the core that can be trivially implemented outside DITA-OT; if we add this now, we can't take it out anymore.

**Comment by infotexture** [comment]
With the `clean.temp` parameter, we do have a precedent for similar functionality in the core code, so something like `clean.output` would not seem entirely unreasonable.

IIRC, the use case Radu describes has affected OT distribution builds in the past, where obsolete topics were occasionally shipped in the `doc` folder. 

Recent versions prevent this via the `cleanDistTemp` Gradle task, but a toolkit parameter would be useful in environments where custom build files may not be an option.

**Comment by xephon2** [comment]
Hope that Gradle will once get vendored in the OT. Would probably simplify things like this.

**Comment by jelovirt** [comment]
I don't see `clean.temp` as a totally convincing precedent.

`clean.temp=no` disables the deletion of the generated temporary directory and can be used for debugging purposes; this is the only way to retain the temporary directory and you cannot control this outside DITA-OT.

`clean.output=yes` would delete the contents of the output directory before the transtype is ran; this can be done outside DITA-OT trivially.

This can already be implemented by a plugin that contributes to the extension point `depend.preprocess.pre´ and adds a target there to delete the contents of the output directory if a custom `clean.output` property is set to true.

**Comment by jelovirt** [comment]
If we add this (my :-1: still applies), I'd prefer to stick convenience functionality like this to a separate plugin. We may already have some convenience functionality that could be moved there.
