### ISSUE TITLE
Parameter for customizing the name of output file

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1200]
Converted from [SourceForge issue 3514841](http://sourceforge.net/support/tracker.php?aid=3514841), submitted by @raducoravu

Some transformation types generate a single output file like PDF, CHM, ODF.
It would be nice if there would be a documented parameter which could be set in order for the user to control the name of the generated output file.

As an usecase, from one DITA Map you can obtain multiple PDF outputs depending on the profiling conditions. If you want to use a single output directory the PDF files would just overwrite each other after each transformation finishes.

A longer discussion related to PDF output can be found here:
http://www.oxygenxml.com/forum/topic6787.html

**Comment by robander** [comment]
@jelovirt With this parameter working for so long now, in our docs, and declared in the PDF `plugin.xml` file ... any intention of creating a new `args.` parameter at this point? If not, we can probably just mark this one closed...

**Comment by jelovirt** [comment]
We currently have

* EclipseHelp: `args.eclipsehelp.jar.name` that includes file extension
* HTMLHelp: `dita.map.filename.root`
* JavaHelp: `args.javahelp.jar.name` that includes file extension, generated from `dita.map.filename.root`
* PDF: `outputFile` that includes file extension, generated from `outputFile.base`

**Comment by jelovirt** [comment]
Added `args.output.base` property to control the name of the output file. The value of the property is the base file name of the output file, without file extension. The file extension is defined by the transtype.
