### ISSUE TITLE
Running dita from command line fails

### ISSUE THREAD

**Issue by mkarg** [dita-ot/dita-ot#1205]
This bug report was forwarded from SourceForge (http://sourceforge.net/tracker/?func=detail&aid=3521017&group_id=132728&atid=725074) by @mkarg.

The following page describes how to start DITA from command line:
 
http://dita-ot.sourceforge.net/1.5.4/readme/DITA-javacmd.html
 
In fact, this is NOT working, as the attached simplistic sample proofs. In the ZIP file, there are two very simple build.xml files for ANT. While "build-OK.xml" works well by calling ant, which in turn calls DITA-OT, the file "build-FAIL.xml" fails -- which does nothing else than the steps described by the above link into the documention:
 
[DITA-OT] java.io.FileNotFoundException: integrator.properties (The system cannot find this file)
 [DITA-OT] java.lang.NullPointerException
 
As it seems, either the documentation is missing something (like: startcmd is needed before running this) or there is a bug in the Java Launcher of DITA.

**Comment by jelovirt** [comment]
Closing as inactive
