### ISSUE TITLE
Loosing chunk attribute when map references a map

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1210]
Converted from [SourceForge issue 3165348](http://sourceforge.net/support/tracker.php?aid=3165348), submitted by @easirois

When a child map has the chunk attribute on the map element, the resulting generated map in the temp directory no longer has the chuck attribute.  At issue for the chunk attribute is that  the processing creates one single map representation of  the hierarchy represented  by the root map.  The only surfaces itself when the @chunk is listed on `<map>` because there's only one map in the output.

In the examples below the value of the chunk attribute is  chunk="to-content by-document"

Example 1

```
map 
   --  map@chunk      -->  one HTML
```

Example 2

```
map 
   --  map@chunk      -->  one HTML (one root topicref)
   --  map@chunk      -->  one HTML (one root topicref)
   --  map@chunk      -->  one HTML (two root topicref)
   --  topicref              -->  multiple HTML
          topicref                         
```

As long as there's a 'root' topicref in the submap the issue is fairly straight forward, where things get more complicated is when one needs to represent the a hierarchy in the resultant map when to create one or two single HTML file base on the @chunk on `<map>` when `<map>` is striped out of the output.

Here is a sample of the arrogate map from the processing, where should the chunk attribute appear to get the expected HTML output?  How do we handle the content from map 3 where the expected output is a single HTML doc, but there are multiple root topicref elements.  If we where simply processing map3, then this scenario is not an issue, but when we put another map and  is a sibling of other maps, the problem is a bit more complicated. 

```
map
  -- topicref  <!-- map1 one HTML-->
       -- topicref
       -- topicref
 -- topicref  <!-- map2  one HTML -->
       -- topicref
       -- topicref
 -- topicref  <!-- map3 -->
 -- topicref  <!-- map3 -->
--  topicref  <!-- map1  multiple HTML -->           
      topicref    
```

**Comment by raducoravu** [comment]
One of our users had the same expectation, that the attributes @chunk or @collection-type set on a submap should have been taken into account.

**Comment by raducoravu** [comment]
Eliot Kimber's analysis on this:

            The 1.3 spec says, under 2.4.5.1 Using the @chunk attribute:
            
            "A default by-xxx policy for an entire map may be established by setting
            the @chunk  attribute on the <map>  element, which will apply to any
            <topicref>  that does not specify its own by-xxx policy."
            
            It doesn't qualify root or submaps, so I think it would be reasonable to
            expect @chunk on a submap to set the default topic selection policy.
            
            Later in the same topic, under the discussion for "to-content", it says:
            
            "When specified on the <map> element, this indicates that the contents of
            all topics referenced by the map are to be rendered as a single document."
            
            I can't find any other language related to chunking and the handling of
            maps in the 1.3 spec.
            
            That suggests that the behavior you're seeing is a bug.
            
            The way I would expect submaps to be handled is that each submap gets
            replaced by a topicgroup element that reflects all the attributes of the
            map that are relevant to topicrefs (which is pretty much all of them).
            This would result in a single-document map with the @chunk values
            preserved such that normal topicref chunk processing would then apply. The
            only addition would be the setting of default values for the
            splitting/combining policy, which is not inherent in topicgroup (the spec
            is clear that only @chunk on map sets defaults for descendant topicrefs).
            
            The one rub here is setting the default topic split/combine policy
            (by-document or by-topic). Specifying @chunk on map sets the default for
            all descendant topicrefs but it shouldn¹t, by itself then trigger chunking
            for topicrefs that don't specify @chunk explicitly (that would make no
            sense). But the spec is clear that chunk on topicref elements does not
            cascade to descendants, so replacing a referenced map with a topicrgroup
            with @chunk would not, by itself serve to set the default, so processors
            would need some private way to capture any default set by submaps and then
            take that into account when doing chunk processing.
            
            In practice I would avoid specifying @chunk on maps, especially on maps
            that are intended as submaps. I think better practice is to ensure that
            every map has exactly one root normal-role topicref, which then provides
            an unambiguous place to put chunking rules and also happens to avoid this
            particular issue.

**Comment by gvinodkumar515** [comment]
I am using chunk="content" in topichead tag like below to generate merged topic html file using DITA OT Plugin org.dita4publishers.html2 plugin then **its generating Chunk363995000.html output**

My ditamap file

    <map>
    <title>Directory</title>
    <topichead chunk="to-content">
    <topicmeta class="- map/topicmeta "><navtitle>Details</navtitle></topicmeta>
    <topicref class="- map/topicref " href="dita1.xml"/>
    	<topicref class="- map/topicref " href="dita2.xml"/>
    	<topicref class="- map/topicref " href="dita3.xml"/></topichead>
    </map>

If used chunk="to-content" in root element its **not generating merged topic html** file using DITA OT Plugin org.dita4publishers.html2 plugin

    <map chunk="to-content">
    <title>Directory</title>
    <topicref class="- map/topicref " href="dita1.xml"/>
    	<topicref class="- map/topicref " href="dita2.xml"/>
    	<topicref class="- map/topicref " href="dita3.xml"/>
    </map>



For this i have to do any xsl changes or plugin code problem?

Or I have to do any changes to this template?

    <xsl:template match="/*[df:class(., 'map/map')]">
        
        <xsl:apply-templates select="." mode="report-parameters"/>
    
        <xsl:variable name="uniqueTopicRefs" as="element()*" select="df:getUniqueTopicrefs(.)"/>
        
        <xsl:variable name="chunkRootTopicrefs" as="element()*"
          select="//*[df:class(.,'map/topicref')][@processing-role = 'normal']"
        />
        
        <xsl:message> + [INFO] Collecting data for index generation, enumeration, etc....</xsl:message>
        
        <xsl:variable name="collected-data" as="element()">
          <xsl:call-template name="mapdriven:collect-data"/>      
        </xsl:variable>
        
        <xsl:if test="$debugBoolean">
          <xsl:message> + [DEBUG] chunkRootTopicrefs=
    <xsl:sequence select="$chunkRootTopicrefs"/>      
           </xsl:message>
        </xsl:if>
        <xsl:variable name="graphicMap" as="element()">
          <xsl:apply-templates select="." mode="generate-graphic-map">
          </xsl:apply-templates>
        </xsl:variable>
        <xsl:result-document href="{relpath:newFile($outdir, 'graphicMap.xml')}" format="graphic-map">
          <xsl:sequence select="$graphicMap"/>
        </xsl:result-document>    
        
        <xsl:if test="true() or $debugBoolean">
          <xsl:message> + [DEBUG] Writing file <xsl:sequence select="relpath:newFile($outdir, 'collected-data.xml')"/>...</xsl:message>
          <xsl:result-document href="{relpath:newFile($outdir, 'collected-data.xml')}"
            format="indented-xml"
            >
            <xsl:sequence select="$collected-data"/>
          </xsl:result-document>
        </xsl:if>
        
        
        <xsl:apply-templates select="." mode="generate-root-pages">
          <xsl:with-param name="uniqueTopicRefs" as="element()*" select="$uniqueTopicRefs" tunnel="yes"/>
          <xsl:with-param name="collected-data" as="element()" select="$collected-data" tunnel="yes"/>
        </xsl:apply-templates>
        <xsl:apply-templates select="." mode="generate-content">
          <xsl:with-param name="collected-data" as="element()" select="$collected-data" tunnel="yes"/>
          <xsl:with-param name="uniqueTopicRefs" as="element()*" select="$uniqueTopicRefs" tunnel="yes"/>      
        </xsl:apply-templates>
        <xsl:apply-templates select="." mode="generate-index">
          <xsl:with-param name="collected-data" as="element()" select="$collected-data" tunnel="yes"/>
        </xsl:apply-templates>
        <xsl:apply-templates select="." mode="generate-glossary">
          <xsl:with-param name="collected-data" as="element()" select="$collected-data" tunnel="yes"/>
        </xsl:apply-templates>
        
        <xsl:message> + [DEBUG] generate-graphic-copy-ant-script:  Applying templates to <xsl:value-of select="name(.)"/>...</xsl:message>
        <xsl:apply-templates select="." mode="generate-graphic-copy-ant-script">
          <xsl:with-param name="graphicMap" as="node()*" tunnel="yes" select="$graphicMap"/>
        </xsl:apply-templates>
        <xsl:message> + [DEBUG] generate-graphic-copy-ant-script: Templates applied.</xsl:message>
      </xsl:template>

Please give any guidelines or suggestions to overcome this issue.

Thanks in Advance.
