### ISSUE TITLE
anchorref reverses order of topics & drops anchor topicrefs

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1215]
Converted from [SourceForge issue 3428884](http://sourceforge.net/support/tracker.php?aid=3428884), submitted by xymarkd

Given map 1:

``` xml
<map>
<title>Map 1</title>
<anchorref href="map2.ditamap#ankh">
<topicref href="topic1.xml"/>
<topicref href="topic2.xml"/>
</anchorref>
<mapref href="map2.ditamap"/>
<topicref href="topic3.xml"/>
</map>
```

And map 2:

``` xml
<map>
<title>Map 2</title>
<anchor id="ankh"/>
</map>
```

When I run my plug-in that does (1) dita-preprocess and (2) an antcall to my step that runs the pipeline task, module TopicMerge, I get essentially this in the merged file:

``` xml
<dita-merge>
<map>
<topicref href="topic3"/>
</map>
<topic id="topic3"/>
<topic id="topic2"/>
<topic id="topic1"/>
</dita-merge>
```

I would have expected the <map> to have all three topicrefs, in the order encountered in the original map sequence. If that were so, I wouldn't care about the order of the topics.

This is with DITA 1.5.3.

**Comment by robander** [comment]
The PDF process basically has no support for `<anchorref>` at this point - when I use the sample map, I get this error:
```
   [mapref] file:/C:/DITA-OT/dita-ot-2.3/reproduce/1215map1.ditamap:6:41: [DOTX0
68W][WARN]: A topicref element that references a map contains child topicref ele
ments. Child topicref elements are ignored.
```

I'm not really expecting `<anchor>` to be supported in PDF, as it's really an element designed entirely around run-time resolution in Eclipse. I guess that, based on the specification, the mapref stage should probably be updated to (presumably) leave `<anchorref>` alone, although this element too is not one that makes a lot of sense in PDF. I wonder if the element is headed towards a deprecated status for 2.0, as with the `<topicsetref>` element that was defined at the same time.

[1215.zip](https://github.com/dita-ot/dita-ot/files/285311/1215.zip)

**Comment by jelovirt** [comment]
Closing as rejected and lack of activity
