### ISSUE TITLE
Incorrect fo:index-range generation

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1224]
Converted from [SourceForge issue 3464901](http://sourceforge.net/support/tracker.php?aid=3464901), submitted by tmakita

I found a fatal stylesheet bug in generating PDF output.

My command-line is as follows:

```
set d=samples\index-data\
ant -l %d%en-out\sample_en.log -Dargs.input=%d%sample_en.ditamap -Dtranstype=pdf2 -Dclean.temp=no -Doutput.dir=%d%en-out -Ddita.temp.dir=%d%en-temp -Dpdf.formatter=xep
```

Please see attached .log file and .fo file. You can find following problems.
1. `<fo:index-range-begin id="NOTE_TITLE_RANGE_d55e3178a1280" index-key="NOTE_TITLE_RANGE"/>` is generated twice.
2. The fo:index-range-begin that corresponds to `<fo:index-range-end ref-id="NOTE_SHORTDESC_RANGE_d55e3190a1280"/>` is not generated.

I uploaded the test data to the following URL http://w01.tp1.jp/~a190498571/data/sample_en_testdata_20111224.zip

**Comment by robander** [comment]
I'm trying to reproduce old issues with the latest code - for this one, the sample data link does not work ("You don't have permission to access /~a190498571/data/sample_en_testdata_20111224.zip on this server.")

I'm not quite sure how to validate whether this issue still exists.

**Comment by raducoravu** [comment]
Sample files no longer accessible for tests.
