### ISSUE TITLE
TM output

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1245]
Converted from [SourceForge issue 3311121](http://sourceforge.net/support/tracker.php?aid=3311121), submitted by julio_vazquez

Currently, the `<TM>` element marks all occurrences of a trademark in the output. The element should work similar to the HTML output in that the first occurrence is the only one marked. It makes sense to make this a configurable option in case there is a requirement for all occurrences to be marked.

**Comment by robander** [comment]
@jelovirt Guessing you haven't looked at this in a while. I was thinking of implementing for 3.0 but now wondering if you have a preference as to whether this sort of option belongs in the base code. Current processing is set up to mark every `<tm>` element; I've never had this processing requirement, having only needed the first-in-PDF behavior requested above. I'm assuming others need this as well if it was requested from outside IBM, but guessing some people also expect the current behavior.

**Comment by jelovirt** [comment]
It's fair feature request. I'd implement this by adding a mode that returns `xsl:boolean` to signal whether trademark symbol is output or not. This makes it easy to write code that e.g. always outputs tm in frontmatter, and first occurrence per chapter. I've used that approach with some other element before, but can't remember which transtype it was.

**Comment by jelovirt** [comment]
XHTML seems to have something like that, but it doesn't use a mode, only `xsl:choose`. Mode is more extensible.

**Comment by robander** [comment]
Agreed. Any preference on naming for an external parameter to control this? Or were you thinking just the function, and using it requires extension?

**Comment by jelovirt** [comment]
I'd prefer _not_ to add a parameter for this, because we don't want parameter per feature.

**Comment by robander** [comment]
OK - will just work on the function. Thanks.

**Comment by robander** [comment]
Think that #2404 covers any likely changes to come from this - code is now optimized with a mode template that can configure when/if to mark trademarks.
