### ISSUE TITLE
Enable specifying MathML file as image/@href

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1247]
Converted from [SourceForge issue 3392915](http://sourceforge.net/support/tracker.php?aid=3392915), submitted by tmakita

As far as I know it is not so easy to introduce MathML graphics into DITA because it needs the DTD (or XML schema) “specialization”.
  http://tech.groups.yahoo.com/group/dita-users/message/11402
One of my customer (and there seems many needs) do needs MathML in PDF output as soon as possible. Could you consider the convenient way to introduce MathML?
My suggestion is very simple. Currently DITA-OT treats XML file described in the <image> for parsing.

[Example]

```
<fig>
  <title>Equation by MathML </title>
  <image href=”image/math1.xml”/>
</fig>
```

This authoring results the following log:

> gen-list-without-flagging:
>  [pipeline] Using Xerces grammar pool for DTD and schema caching.
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'math' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mtable' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mtr' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mtd' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'msub' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mi' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mn' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mo' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'msub' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mi' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mn' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mo' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'msub' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mi' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mn' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mo' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ030I][INFO] No 'class' attribute for 'mn' element was found.  Please add class attribute definition in the related dtd file. 
>  [pipeline] [DOTJ021W][WARN] File 'topics-en\image\math1.xml' was excluded from the 'dita.list' file since it is invalid and all its content has been filtered out by the ditaval file. Please check the file 'topics-en\image\math1.xml' and the ditaval file to see if this is the intended result.

However from the beginning DITA-OT should not parse the image file even if the file extension is “.xml”. If DITA-OT assumes this MathML XML file as graphic file, everything will succeed because PDF converter now supports MathML as external graphic. In conclusion my suggestion are:
1. Abandon the parsing for the XML file written in the image/@href.
2. Copy the XML file specified in the image/@href attribute to the output folder.

**Comment by lagivan** [comment]
It does not work as I'd expect. I get an issue "The file format is not supported. No ImagePreloader found" when I try to reference MathML image like this:

    <fig>
	    <image href="1178425_1.xml"/>
    </fig>

This is the error:

      [fop] SEVERE: Image not available. URI: file:/C:/Temp/test/data/PMPB15XP/1178425_1.xml. Reason: org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for file:/C:/Temp/test/data/PMPB15XP/1178425_1.xml (See position 597:-1)
      [fop] org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for file:/C:/Temp/test/data/PMPB15XP/1178425_1.xml

**Comment by jelovirt** [comment]
@lagivan this is related to #1623. This issue is not about actually supporting MathML, only that references to MathML with `<image>` should not cause the MathML to be parsed.
