### ISSUE TITLE
FO plugin: Support for multilingual documents

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1250]
Converted from [SourceForge issue 3483183](http://sourceforge.net/support/tracker.php?aid=3483183), submitted by snoyberg

Currently, it is not possible to provide separate font mappings for the same character based on its language. This is most relevant to CJK. The issue is that the charset for a character is determined by looking in the relevant i18n file. However, "relevant" is determined by the language of the entire document, not the current element.

I recommend we change the Java processing to look up in the appropriate i18n file of the most recent xml:lang attribute.

**Comment by radu-pisoi** [comment]
One of our customers have a similar situation. He asked how to configure the PDF transformation for a multi-language topic. 
He wanted to specify a certain font depending on the paragraph language.
