### ISSUE TITLE
Support bookmap metadata in FO plug-in

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1254]
Converted from [SourceForge issue 3508689](http://sourceforge.net/support/tracker.php?aid=3508689), submitted by cnahr

DITA 1.5.4 ships with DITA 1.2 schemas whose bookmap uses the bookmeta element to specify metadata (author, publisher, copyright...).

However, the FO plug-in still only supports the obsolete bkinfo element to specify bookmap metadata.  bookmeta is tolerated but generates no output except for the author tag.  All other metadata tags are ignored, in my (limited) testing.

The FO XSLs should be updated to change all bkinfo transformations into the equivalent bookmeta transformations.

**Comment by robander** [comment]
Related: pull request #1722
