### ISSUE TITLE
"Official" DITA-OT Plugin for Maven

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1259]
Converted from [SourceForge issue 3519836](http://sourceforge.net/support/tracker.php?aid=3519836), submitted by @mkarg

Maven is very popular these days, and it would be really helpful to have DITA-OT integrated into Maven by an "offical" plugin. Someone wrote a plugin http://mojo.codehaus.org/dita-maven-plugin/ but this is not implemented very smart and it's rather hard to get it working. It would be very smart if the DITA-OT team could provide an "official" plugin for Maven, or at least could help making the existing plugin work better with *latest* DITA-OT 1.5.4! Please support Maven!

**Comment by robander** [comment]
Closing this as inactive - nobody on the development team is currently expecting to implement. It can be reopened if an interested party wishes to work on it.

**Comment by sanderson-sfdc** [comment]
@robander - I'd like to take a stab at part of this request.  We're working with the dita-ot-gradle project, and we want to modify it to depend on specific versions of the OT.

What I'd like to do is simply push the result of the dist task to jcentral or maven central.  That's the first step. 

I've already got working code and can publish it locally.  I see in the dist.gradle file there is already an account set up for maven central.   I'd like to create a pull request based on that authentication information - is that okay?

**Comment by jelovirt** [comment]
My preference is that we don't try to distribute the whole package in Maven, because it cannot be used directly from a JAR.

**Comment by sanderson-sfdc** [comment]
@jelovirt, I'm not talking about a jar file, I'm talking about the dist zip.   

Let me give you my use case to see if it makes sense.

I do automated builds with Jenkins pipeline.  My builds, and dependency management, are controlled by gradle, 

In my build.gradle I add a dependency on a DITA-OT build (say, 3.0.3) for my production builds and different dependency (say, 3.1) for my test builds.  Using a gradle plugin, the appropriate DITA OT dist zip file can be downloaded from the maven repository and can be used to run builds.

This allows me to do builds on systems without having to set up the DITA OT into a particular state.

We're already doing this locally, but it could be useful for the community, too.

**Comment by jelovirt** [comment]
@sanderson-sfdc yes, I know your original request is not for a JAR file that contains whole OT code that can be run from within the JAR file, via the classpath. My point is that if you want to use Maven for non-JAR type of packages, what would be the benefit over just downloading the packages from some non-Maven repository URL?

**Comment by sanderson-sfdc** [comment]
The advantage is that I can use gradle to handle the dependency, rather than crafting a task to do the same dependency analysis that it does.

**Comment by sanderson-sfdc** [comment]
Say, for example, I'm on a system that doesn't have network access to github, but I do have a local artifact repository that mirrors Maven central.  I can still get the OT using gradle to do my builds.

**Comment by lionelmoi** [comment]
Why don't you use an Artifactory database? That's what I do for DITA-OT and for my own plugins.

**Comment by rahulraykor** [comment]
Can somebody please provide the maven project for DITA OT? I also want to help to take it further in any manner I can.
