### ISSUE TITLE
Add parameters for custom frameset file

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1264]
Converted from [SourceForge issue 3520986](http://sourceforge.net/support/tracker.php?aid=3520986), submitted by @infotexture

Currently, `args.css` allows the user to specify a custom CSS file for HTML transforms, and `args.copycss`, `args.csspath` and `args.cssroot` determine whether and how this file is copied to output.

Similar parameters should be available to handle a custom frameset file.

**Comment by infotexture** [comment]
As the original submitter, I concede this issue is less relevant now that OT provides HTML5 output and the use of framesets is generally declining.

As far as I'm concerned, it would be fine to close this as `inactive` and/or `obsolete`.
