### ISSUE TITLE
<image> not shown in <shortdescs> of nested topics

### ISSUE THREAD

**Issue by dwalther** [dita-ot/dita-ot#1279]
I am not really sure if this bug is relevant for dita-ot at all or if it is caused by XEP? Sorry for my ignorance. Anyway, I'll give it a try: 
 
When building PDFs with 1.5.3 and XEP, there is the following error: If a topic is a 1st level child topic referenced in a map, I can include `<image>` elements in the `<shortdesc>`. But if a topic is a 2nd level child topic referenced in a map, I can't and get the following error: 

> [java] EXCEPTION: Failed to create image file:/TEXT/pagelightning.png of type null
(error message repeated for 2 other files)
Clean temp directory...
Processing ended.

> BUILD SUCCESSFUL
Number of Fatals : 0
Number of Errors : 0
Number of Warnings : 0

> Total time: 1 minute 17 seconds
...
The process finished with exit code: 0" 

The HTML output builds correctly. 

Here is an snippet from a map which illustrates the behavior:

```xml
 <map ...>
 <topicref href="topic_intro.dita" type="topic" collection-type="family">
 <topicref href="t_add-something.dita" type="task"/>
 </topicref>
```

Images in shortdescs work for "topic_intro.dita" but not for "t_add-something.dita".

A member of the yahoo dita users group stated that:

> You're correct that the processing of the child topics are causing the issue and it may have to do with how the shortdesc should be processed, which is as content within a link in the parent topic.

The complete thread can be found [here](http://tech.dir.groups.yahoo.com/group/dita-users/message/25321).

There was some discussion in the dita users group if <images> should be usable in <shordesc> elements at all because images should not be used in shortdescs. However, according to my knowledge of the DITA spec it is not forbidden and should be rendered as such? http://docs.oasis-open.org/dita/v1.2/os/spec/langref/image.html#image

Would it be possible to make the rendering of images possible in 2nd/3rd/... level shortdesc topics. Thanks for any comments, KR Diana

**Comment by eerohele** [comment]
[Fixtures](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1279).

I can reproduce this with 1.5.4 and 1.6.3 but not with 1.7, 1.8, or 2.0.
