### ISSUE TITLE
Processing hang with bad reference outside of map dir

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1292]
Steps to reproduce:

1. Add this to samples\hierarchy.ditamap:

```xml
<topicref href="..\test.xml"/>
```

2. Copy DITA-OT\samples\tasks\changingtheoil.xml to DITA-OT\test.xml

3. Build to XHTML (tested here with the command line tool)

The build generates several warnings / errors about being outside of the map directory, then hangs during gen-list with this as the final message:

  >  [gen-list] Processing C:\concepts\oil.xml

That file does not exist. 

I consider this bad input data (for a couple of reasons) - but we shouldn't be going into a loop and hanging. I don't see any need to make this output "work", especially given the missing files, but the build should either fail at this point or continue with all of the reported errors.

**Comment by jelovirt** [comment]
Closing as obsolete.
