### ISSUE TITLE
Conref push stage issues error "null"

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1293]
I've added the following markup to garagetaskoverview.xml:

```xml
<ul>
    <li>Start the list</li>
    <li id="target">target</li>
    <li>continue the list</li>
    <li conref="#taskconcept/target" conaction="pushbefore">push content</li>
    <li conaction="mark"></li>
</ul>
```

This markup is incorrect (the conref attribute should be on the last list item). The code is supposed to generate an error, but I get this on the command prompt output:

>  [conref-push] null

The following markup is also incorrect, but is silently ignored:
```xml
    <li conaction="mark"></li>
    <li conref="#taskconcept/target" conaction="pushbefore">push content</li>
```

The code has support for some "pushbefore" condition that will generate message DOTJ044W, but I'm not sure what the condition is (found this while trying to clarify that message and user response).

The correct markup works as expected, which is:
```xml
    <li conaction="pushbefore">push content</li>
    <li conref="#taskconcept/target" conaction="mark"></li>
```

**Comment by jelovirt** [comment]
Added `DOTJ068E` for invalid conref push syntax

```xml
<li conaction="mark"></li>
<li conref="#taskconcept/target" conaction="pushbefore">push content</li>
```
