### ISSUE TITLE
Remove missing navtitle message for resource-only topicrefs

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1296]
As of 1.5.6M5, keydefs to graphics that do not specify navtitle give a warning that there is no navtitle.

I think this behavior is incorrect. For resource-only topicrefs, there's no general need for a navtitle because the topicref, by itself, is never used in navigation. In many, if not most, cases, keydefs for graphics are only used from <image> elements and thus navtitle is not relevant.

Toolkit should not produce the missing navtitle message for resource-only topicrefs. It is probably appropriate to issue it for normal-role topicrefs to graphics.

**Comment by raducoravu** [comment]
:+1: These extra error messages also annoy me

**Comment by jelovirt** [comment]
Unable to reproduce.
