### ISSUE TITLE
Not all attributes defined on a DITA Composite are copied in the preprocessing stage

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1298]
The callback `org.dita.dost.reader.MergeTopicParser.startElement(String, String, String, Attributes)` by default copies all attributes defined on the element in the string buffer. But for a `<dita>` element it makes a fast return and does not copy the attributes defined on the <dita> element to the string buffer.

Why is this a problem?
1. The attributes xtrf and xtrc are not passed further.
2. The `<dita>` element (at least the one which is XML Schema based) could have extra proxy-namespace declarations which are not copied and the XML would become namespace not-wellformed.

By the way, maybe in the entire dost.jar StringBuffer could be replaced with StringBuilder which is faster.

**Comment by robander** [comment]
Also related to #1077 - the fast return means that the `<dita>` root element is dropped, which makes it impossible to determine the original document boundaries in a merged file.

**Comment by robander** [comment]
This should have been marked closed in 2.5 (it was noted in the release notes along with the #2698 pull request).
