### ISSUE TITLE
Using @copy-to breaks preprocess + PDF rendering when using @chunk="select-topic to-content"

### ISSUE THREAD

**Issue by blefort** [dita-ot/dita-ot#1305]
No output at all for the merged content

Scenario: http://tiny.cc/dvp9fw

This will not render
```XML
<topicref href="Concept-A.dita" chunk="select-topic to-content" copy-to="cab.dita">
    <topicref href="Concept-B.dita"/>
</topicref>
```
But this will
```XML
<topicref href="Concept-A.dita" chunk="select-topic to-content">
   <topicref href="Concept-B.dita"/>
</topicref>
```
It works with the xhtml transtype

**Comment by robander** [comment]
I'm no longer able to reproduce this with a version of the map above and the latest 2.3 development code. I've got a map with a parent and child topicref, the `chunk` attribute shown above on the parent, and `copy-to` on the parent. XHTML works (I get both topics, with the parent renamed). PDF works (all content appears in the PDF). I suspect this has been resolved at some point over the last couple of years. [1305.zip](https://github.com/dita-ot/dita-ot/files/285277/1305.zip)
