### ISSUE TITLE
An easier way to send customization parameters to stylesheets

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1361]
See this [thread](http://tech.groups.yahoo.com/group/dita-users/message/26982) for an use-case.

When making customizations to the DITA OT XSLT stylesheets some developers feel the need to take in the stylesheets different choices (or do use different values) depending on custom parameters which they set to the ANT process.

Unfortunately setting a new system property to the ANT process is not enough, they also need to modify the build files and pass that new parameter to the XSLT stylesheets. Then the XSLT stylesheets need to be modified in order to add a new `xsl:param` which will receive the value from the build process.

I think this approach could be simplified. For example in XSLT the method `system-property(string)` can be used to obtain the value of a system property. Unfortunately the `<xslt>` task does not seem to pass by default system properties from the ANT process to the stylesheets.

But the ANT `<xslt>` task seem to be able to receive a [`<syspropertyset>`](http://ant.apache.org/manual/Types/propertyset.html) which could specify that all command line parameters could be passed as system properties to the transformer.

I have not tried this but the end result would mean that the user would pass an additional param to ANT and the param would be read in the stylesheets using `system-property(string)`.

Maybe this would also mean that future parameters which are used for XSLT customization would not need to be specified in the ANT build files and defined as xsl:param in the stylesheets.

**Comment by eerohele** [comment]
The approach Radu suggested would have the benefit of making it easy to use any number of Ant properties in DITA-OT stylesheets, without having to add a `<param>` element for each one as described in *[Passing parameters to existing XSLT steps](http://www.dita-ot.org/2.0/dev_ref/plugin-xsltparams.html)*.

For example, let's say I have a Java property file with an arbitrary number of parameters I want to pass to the stylesheets of my PDF plugin:

```
foo = bar
baz = quux
. . .
```

With the current implementation, to use `foo` and `baz` in my stylesheets, I would need to know the name of each property and add a corresponding `<param>` element for each of them in `insertParameters.xml`:

```xml
<dummy>
  <param name="foo" expression="${foo}" if="foo"/>
  <param name="baz" expression="${baz}" if="baz"/>
  . . .
</dummy>
```

It would be nice to avoid having to do that. However, setting system properties has [the parallel-processing problem @jelovirt mentioned in #1859](https://github.com/dita-ot/dita-ot/issues/1859#issuecomment-75734840).

I guess the only solution I can think of is to make it possible to do something like `<paramref prefix="foo"/>` in `insertParameters.xml`, which would retrieve all Ant properties with the prefix `foo`and generate an XSLT parameter for each one — kinda like Ant's `<propertyref>`. Haven't looked into how big of an effort that'd be, yet, though.
