### ISSUE TITLE
Retain conref and keyref information after preprocessing

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1381]
Add namespaced attributes to retain conref and keyref source information. This will allow advanced users to create e.g. review PDFs which show the source of each block.

The feature should be controlled by dynamic configuration; by default the feature should be disabled.

**Comment by ToshihikoMakita** [comment]
I **DO** agree Jarno's opinion. When DITA users uses conref/conkeyref more frequently, they needs the original source information for reviewing process. I've requested this capability from user and modified to retain them by modifying DitaWriter.java in DITA-OT 1.7.5. If this capability is implemented, it is strongly appreciated. Are there any possibilities to implement this?

**Comment by robander** [comment]
We already retain `@keyref` today in the temp file (it's still there after the attribute is resolved). We do not retain `@conref` or `@conkeyref`.
