### ISSUE TITLE
The ANT build should fail by default if the XSL-FO processor cannot create the PDF file

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1414]
By default the ANT process finishes with success even if the creation of the PDF by the XSL-FO process failed. This is bad, the user might have the impression that the PDF was updated and in fact it was not.

There are three cases:

1) Apache FOP is used. Unfortunately the Apache FOP ANT task never fails, it just reports errors in the console, see:

https://issues.apache.org/bugzilla/show_bug.cgi?id=54219

so this should either be patched in the DITA OT or wait for a fix on the Apache FOP side.

2) RenderX XEP is used. The build file has a parameter "xep.failOnError" but by default it is set to "false". In my opinion the default should be changed to "true".

3) Antenna House is called by using <exec>. In my opinion it should also set a failonerror="true" on the task or at least have a parameter for this like the XEP task.

**Comment by raducoravu** [comment]
Found a problem when generating PDF using XEP:

DITA-OT3.x\plugins\org.dita.pdf2.xep\build_xep.xml:183: You must nest a condition into <condition>

so this line:

      <condition property="xep.failOnError" value="true">

should probably be replaced with:

    <condition property="xep.failOnError" value="true">
      <not><isset property="xep.failOnError"/></not>
    </condition>

**Comment by jelovirt** [comment]
We can just use
