### ISSUE TITLE
xref via keyref to external HTML page doesn't work

### ISSUE THREAD

**Issue by blefort** [dita-ot/dita-ot#1439]
Hi,

There was a similar issue reported in the past, but the case is a bit different  https://github.com/dita-ot/dita-ot/issues/1174.

DITA-OT version tested (direct from download): 1.6.3, 1.7.1  both have the issue.

In my understanding, either navtitle element or linktext are not honored in the map resolution (Not sure I use the right vocabulary - sorry - I mean when the map is built in the preprocess stage), when a keyref reference an external html page.
The link text is honored in a context of a topic resolution.
## Code

Here is a map using linktext and navtitle

``` xml
<map>
    <title>Keydef on exernal content</title>
    <keydef keys="ncbi" 
                 href="http://www.ncbi.nlm.nih.gov/" 
                 scope="external" 
                 format="html">
        <topicmeta>
            <navtitle>NCBI web site</navtitle>
            <linktext>NCBI web site</linktext>     
        </topicmeta>
    </keydef>
    <topicref href="concept.dita" type="concept"/>
    <topicref keyref="ncbi"/>
</map>
```

After preprocess, the @href value seems to replace the element navtitle and link text

``` xml
<!-- (...) -->
<topicref class="- map/topicref " 
              format="html" 
              href="http://www.ncbi.nlm.nih.gov/"
              keyref="ncbi" 
              scope="external"
              xtrc="topicref:2;12:30" 
              xtrf="/Users/blefort/DITA-OT1.7.1/bugs/DITA-OT/keyref-html/main.ditamap">
        <topicmeta class="- map/topicmeta ">
            <navtitle class="- topic/navtitle ">http://www.ncbi.nlm.nih.gov/</navtitle>
            <?ditaot gentext?>
            <linktext class="- map/linktext ">http://www.ncbi.nlm.nih.gov/</linktext>
        </topicmeta>
    </topicref>
```
## Result

In the navigation, we will see http://www.ncbi.nlm.nih.gov/
In the concept: NCBI web site
## Samples

https://dl.dropbox.com/u/14980268/issues/keyref-html.zip

```
```

**Comment by infotexture** [comment]
Ran into a variant of this while building the DITA-OT docs from the 2.3.1 tag, so it looks like the issue still exists in recent versions.

With a key defined in a map as:

```xml
<keydef keys="participate" href="http://www.dita-ot.org/participate" 
        scope="external" format="html" locktitle="yes">
  <topicmeta>
    <navtitle>Participate</navtitle>
  </topicmeta>
</keydef>
```

and referenced in another map via:

```xml
<topicref keyref="participate"/>
```

the `@href` value is used as link text instead of the `<navtitle>`.

If the same content is placed directly in the referencing map as a `<topicref>` without the `@keyref`, the `<navtitle>` is honored:

```xml
<topicref keys="participate" href="http://www.dita-ot.org/participate" 
          scope="external" format="html" locktitle="yes">
  <topicmeta>
    <navtitle>Participate</navtitle>
  </topicmeta>
</topicref>
```

**Comment by drmacro** [comment]
What is the expected HTML or PDF rendition result of having a navigation topicref to an external HTML Web page?

It makes sense to have a key like this for use from xrefs but I would not expect that kind of resource to be referenced directly from a navigation topicref.

**Comment by robander** [comment]
We had that in the DITA-OT documentation TOC for the first several years - it worked from the TocJS and HTML Help versions, but I don't see any reasonable way to include the info for PDF (apart from, maybe, a link if there is some `@collection-type` setting that creates it). In those early days, from either TocJS or HTML Help, clicking on that link in the TOC resulted in a new browser window with the target URL.

**Comment by infotexture** [comment]
Reproduced with 3.0.2, still present: 

* neither `<linktext>` nor `<navtitle>` from the key definition are honored  
  (the `@href` value is still used as link text)
* also unaffected by the `<navtitle>` changes in #2897
