### ISSUE TITLE
Incorrect processing of subject scheme maps

### ISSUE THREAD

**Issue by keberlein** [dita-ot/dita-ot#1482]
## General description

DITA-OT 1.7 does not handle subject scheme maps properly in regard to validating the attribute values against the specified subject schemes. While the simplest test yields the expected warning messages when the content contains attribute values not specified in the subject scheme, it requires that the subjectScheme map be referenced with type="subjectScheme" specified.  (The DITA 1.2 spec  does not suggest this behavior; if it is a DITA-OT requirement, we need to document it.) 

More realistic test cases using schemeref elements simply fail, however, regardless of whether type="subjectScheme" is specified.

The DITA maps and topic are located at https://gist.github.com/keberlein/5237276 .
## Test content

The following subject definitions and enumeration:

```
<subjectdef keys="operating-systems">
    <subjectdef keys="linux">
        <subjectdef keys="redhat"/>
        <subjectdef keys="suse"/>
    </subjectdef>
    <subjectdef keys="unix"/>
    <subjectdef keys="windows">
        <subjectdef keys="windows7"/>
        <subjectdef keys="windows8"/>
    </subjectdef>
</subjectdef>
```

One DITA topic with following values for the platform attribute: ubuntu, mandriva, solaris
## Test 1

**Test-1.ditamap** contains the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>Example of a map referencing a subject scheme</title>
  <mapref href="baseScheme-with-enumeration.ditamap" type="subjectScheme"/>
  <topicref href="t-creating-controlled-values.dita"/>
```

</map>

**The expected results are generated --  warning messages**

```
[filter] [DOTJ049W][WARN] The attribute value platform="mandriva" on element "step" does not comply with the specified subject scheme. According to the subject scheme map, the following values are valid for the platform attribute: redhat,windows8,windows7,windows,suse,linux,unix,operating-systems
 …
 [filter] [DOTJ049W][WARN] The attribute value platform="solaris" on element "step" does not comply with the specified subject scheme. According to the subject scheme map, the following values are valid for the platform attribute: redhat,windows8,windows7,windows,suse,linux,unix,operating-systems
```

Unfortunately, the DITA-OT is incorrectly building the list of valid labels; it should NOT include operating-systems, according to the examples and guidance provided in the DITA 1.2 spec. See the examples in http://docs.oasis-open.org/dita/v1.2/os/spec/langref/subjectScheme.html#subjectScheme , as well as http://docs.oasis-open.org/dita/v1.2/os/spec/langref/enumerationdef.html#enumerationdef
## Test 2

I removed type=’’subjectScheme” from the <mapref> element Test-2.ditamap. **As a result, no warning messages are generated.**
## Test 3

Here the master map references a subjectScheme map which in turn references another subjectScheme map. This is standard use case that is outlined in the DITA 1.2 spec.

**Test-3.ditamap** contains the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>Example of a map referencing a subject scheme</title>
  <mapref href="extensionScheme.ditamap" type="subjectScheme"/>
  <topicref href="t-creating-controlled-values.dita"/>
```

   </map>

**extensionScheme.ditamap** contains the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE subjectScheme PUBLIC "-//OASIS//DTD DITA Subject Scheme Map//EN" "subjectScheme.dtd">
<subjectScheme>
  <schemeref href="baseScheme.ditamap"/>
  <enumerationdef>
      <attributedef name="platform"/>
      <subjectdef keyref="operating-systems"/>
  </enumerationdef>
</subjectScheme>
```

**Results:** No warning messages.
## Test 4

I modified the <schemeref> element in the extension scheme to see if it also needed type=”subjectScheme” to be specified.

**extensionScheme2.ditamap** contains the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE subjectScheme PUBLIC "-//OASIS//DTD DITA Subject Scheme Map//EN" "subjectScheme.dtd">
<subjectScheme>
  <schemeref href="baseScheme.ditamap" type="subjectScheme"/>
  <enumerationdef>
      <attributedef name="platform"/>
      <subjectdef keyref="operating-systems"/>
  </enumerationdef>
</subjectScheme>
```

**Results:** No warning messages.

**Comment by jelovirt** [comment]
Case 1 fixed. Cases 2/4 and 3 could be handled in separate issues to be able to close this one.
