### ISSUE TITLE
Output created using Copy-to gets incorrect CSS path

### ISSUE THREAD

**Issue by jockyb** [dita-ot/dita-ot#1510]
How to reproduce:
Generate HTML that has a user specified CSS (using args.copycss and args.css) for a map which reuses topics in multiple locations and use copy-to to create a copy of the topic in the output (eg. copy-to="copy.xml").

Error:
The resulting html will have an incorrect CSS path (href="../41.1368801227378/out/style.css") that includes the PATH2PROJ variable that is added by the OT to the copy-to topics (<?path2project ..\41.1368801227378\out\?>)

**Comment by eerohele** [comment]
I tested this on Windows with the files supplied by @jockyb.

On 1.7.5:

```html
 <link rel="stylesheet" type="text/css" href="../../../../../../dita-ot/src/main/out/commonltr.css"/>
```

On 2.0:

```html
<link rel="stylesheet" type="text/css" href="commonltr.css" />
```

The path is also correct when defining a custom CSS file with `args.css`, so I believe this one is fixed by #1563 as @robander suggested and can be closed.
