### ISSUE TITLE
ANT parameter to specify path to additional catalog file

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1515]
For now the DITA OT only looks in the "catalog-dita.xml" for catalog mappings.

It would be interesting to add a new parameter which specifies the path to an additional custom user defined catalog file.
In this way the user could use the specialization DTDs from an external location without making them into a plugin.
For example in Oxygen XML Editor the bundled DITA OT is located in the installation directory which may not have access rights for regular users.

**Comment by stokecn** [comment]
@jelovirt on Dec. 19, 2014: but do the pipeline tasks support URI resolution or even the plugin: URI mechanism? 

Our existing 1.5.2 implementation uses URIs within stylesheets for stylesheet imports. Some tasks that have been migrated to pipeline tasks in 2.3 (i.e. maplink) no longer resolve URI-based imports within stylesheets inserted in maplink.xsl via dita.xsl.maplink.
