### ISSUE TITLE
Variables like "Body even footer" and "Body odd footer" are not properly used

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1516]
In configuration files like: `DITA-OT\plugins\org.dita.pdf2\cfg\common\vars\en.xml` you have variables like:

``` xml
<!-- The footer that appears on odd-numbered pages. -->
<variable id="Body odd footer"/>

<!-- The footer that appears on even-numbered pages. -->
<variable id="Body even footer"/>
```

If I set different values to each one, only the value from the odd pages will be used in all pages (odd or even) of the PDF output.

The XSL `DITA-OT/plugins/org.dita.pdf2/xsl/fo/static-content.xsl` contains a template called "insertBodyStaticContents" which does things like:

``` xml
<xsl:call-template name="insertBodyOddFooter"/>
  <xsl:if test="$mirror-page-margins">
    <xsl:call-template name="insertBodyEvenFooter"/>
  </xsl:if>
```

Do I have a misunderstanding in the way the parameters should be used? I'm expecting that on the PDF pages which are ODD numbered the "Body odd footer" to be used and on the pages which are EVEN numbered the "Body even footer" to be used.

**Comment by Phil-Champ** [comment]
This may sound obvious (the information is on the oXygen forum), but by default only the odd headers and footers are enabled. The "mirror-page-margins" variable is set in DITA-OT/plugins/org.dita.pdf2/cfg/fo/attrs/basic-settings.xsl:

    <xsl:variable name="mirror-page-margins" select="false()"/>

Once "mirror-page-margins" is set to "true", the EVEN content appears in the PDF output.

**Comment by raducoravu** [comment]
You are probably right, somehow when I added the bug I did not know that. I'm not sure if we should try to make this requirement more explicit somehow.

**Comment by raducoravu** [comment]
This is not an issue.
