### ISSUE TITLE
start-indent in attribute-sets body__toplevel and body__secondLevel being ignored in conbody and refbody

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#1517]
I found what appears to be the problem. Consider this excerpt from commons.xsl (line 1095):

```
    <xsl:when test="$level = 1">
        <fo:block xsl:use-attribute-sets="body__toplevel conbody">
            <xsl:call-template name="commonattributes"/>
            <xsl:apply-templates/>
        </fo:block>
    </xsl:when>
```

The order of the attribute-sets is backwards (it should be xsl:use-attribute-sets="conbody body__toplevel"). As it is, the default value for start-indent--obtained from attribute-set conbody--overwrites the value specified in attribute-set body__toplevel. This means that attribute-set body__toplevel becomes useless for conbody because it only contains attribute start-indent. A parallel problem also occurs with attribute sets body__secondLevel and conbody (it should be xsl:use-attribute-sets="conbody body__secondLevel").

A similar precedence error also occurs with refbody in reference-elements.xsl.

Fall through code for body is working correctly.

**Comment by robander** [comment]
I think that this might be working as designed. Using DITA's inheritance model, it's explicitly the goal that if you set something for conbody, that should overwrite anything set for body. 

The odd / likely unexpected side effect is that if you override anything for body, the core settings for conbody still win. 

A different question might be - do we really need to have that override for conbody, or the one for refbody? They seem to do nothing apart from adding the possibility of separate attribute sets for these. Seems like that might be better handled in a different way. Oddly, the taskbody code doesn't reuse body attributes at all, or do anything different based on nesting, it only ever uses attribute set "taskbody".
