### ISSUE TITLE
"tm" is not interpreted in link text in "index.html" using xhtml transtype

### ISSUE THREAD

**Issue by lmazuel** [dita-ot/dita-ot#1521]
Hi,

I have a "topicref" in a map to a topic where the "topic/title" contains a "tm" node.

Then, the "tm" is correctly translated in ® in the "topic.html", but in the "index.html" from the map it is not.
I have kept the "tempdir" of the transformation, to see the dita generated by the pre-processing step. I have this in my map file:

``` xml
  <topicref class="- map/topicref " format="dita" [...]>
    <topicmeta class="- map/topicmeta ">
      <navtitle class="- topic/navtitle ">My title with
        <ph class="- topic/ph ">
          <ph class="- topic/ph ">
            <tm class="- topic/tm " tmtype="reg">Word</tm>
          </ph>
        which use a register
        </ph>
      </navtitle>
      <?ditaot gentext?>
      <linktext class="- map/linktext ">My title with Word which use a register</linktext>
```

The "linktext" generated the the dita-ot pre-processing (it was not present in my data) do not include the trademark. I suppose the "linktext" is used by the HTML XSLs to produce the link text in the "index.html".

I don't see anything in the dita spec which do not authorized to insert this utf-8 character (maybe I'm wrong?). I think it is possible to use the same rules than in the HTML XSL:

``` xml
        <xsl:choose>  <!-- ignore @tmtype=service or anything else -->
          <xsl:when test="@tmtype='tm'">&#x2122;</xsl:when>
          <xsl:when test="@tmtype='reg'"><sup>&#xAE;</sup></xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
```

I use DITA-ot 1.7.1

**Comment by infotexture** [comment]
For related issues with trademark processing, see #2065 & #2293.
