### ISSUE TITLE
Create dynamic filters that use subject scheme maps in XHTML output

### ISSUE THREAD

**Issue by johngtait** [dita-ot/dita-ot#1527]
XHTML output produces static web pages. To produce web pages for different audiences (in the broadest sense), it's possible to filter content using DITAVAL files.

For example, it's possible to specialize a new profiling attribute, populate a list of its possible values from a subject scheme map, and filter on chosen values using DITAVAL files.

We can make these filters as complex as we want but ultimately we need to create static XHTML pages for each desired combination.

As a feature request, can I suggest adding a (Javascript-enabled?) transform that adds a drop down menu to a web page, and allows the content to be filtered dynamically using values obtained from subject scheme maps.

This would allow a single output to be created that would satisfy all possible readers.

**Comment by raducoravu** [comment]
This issue seems quite related to this issue which has already been fixed:
https://github.com/dita-ot/dita-ot/issues/1739

Of course you would need to contribute your own Javascript to show/hide sections in the XHTML output.
