### ISSUE TITLE
Unable to find key definition for defined key

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1534]
This was reported by one of our customers and we tried to minimize the sample.

Try to publish to an XHTML-based output the following DITA Map:

http://www.oxygenxml.com/userFiles/TA_Help_ditamap.zip

The publishing reports that a certain key (which is actually defined) cannot be found:

>[DOTJ047I] Unable to find key definition for keyref="kusing_debugger", href may be used as fallback if it exists.

Relevant console messages:
              
>keyref:
[keyref] Reading C:\Users\radu_coravu\Desktop\LASS\TA_Help_reduced\temp\xhtml\TA_Integration_ditamap.ditamap
[keyref] Reading C:\Users\radu_coravu\Desktop\LASS\TA_Help_reduced\temp\xhtml\TA_Test_execution_ditamap.ditamap
[keyref] [Fatal Error] :2:11: The element type "topicref" must be terminated by the matching end-tag "</topicref>".
[keyref] Failed to parse key definition: The element type "topicref" must be terminated by the matching end-tag "</topicref>".
[keyref] null
[keyref] Processing C:\Users\radu_coravu\Desktop\LASS\TA_Help_reduced\temp\xhtml\test.dita
[keyref] C:\Users\radu_coravu\Desktop\LASS\TA_Help_reduced\test.dita:6:46: [DOTJ047I][INFO] Unable to find key definition for keyref="kusing_debugger", href may be used as fallback if it exists.

I will try to keep the ZIP with the samples on our web site for a couple of days.

DITA-OT 1.7

**Comment by robander** [comment]
Closing as obsolete - I've tested with Radu's 2013 samples in DITA-OT 2.2.4, and the key is resolved properly. This must have been fixed with other key updates in either 1.8, 2.0, 2.1, or 2.2.
