### ISSUE TITLE
Remove completely from the DITA OT distribution the plugin for generating Eclipse Content

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1542]
It seems to be something without much usability for anybody:

http://dita-ot.github.io/1.8/readme/dita2eclipsecontent.html

which was used only by the particular person/organization which added it at that time.

**Comment by robander** [comment]
Probably should remove this in 3.0, which is the currently assigned target.

I know people have used this to create a form of "normalized DITA" but I think there are better solutions for that now. I do think we should ask @infotexture to document those solutions as an alternative when we remove this.

**Comment by infotexture** [comment]
Perhaps we should consider bundling the [org.dita.normalize](https://github.com/dita-ot/org.dita.normalize) plug-in instead.

The information contained in the ReadMe there was derived from the description of the DITA to Eclipse Content plug-in.

**Comment by robander** [comment]
I like that idea - I've had a lot of people ask me about how to get this sort of output, I used to direct them to eclipsecontent with a vague explanation of the history, but org.dita.normalize does it better.

**Comment by infotexture** [comment]
The plugin was moved to a separate repo in a45a72e, so it looks like this can be closed.
