### ISSUE TITLE
Inconsistencies between plugins when flagging the root element of a topic

### ISSUE THREAD

**Issue by nigelwhitaker** [dita-ot/dita-ot#1545]
Flagging the root element of a topic does work in for example the html plugin.  But it doesn't work in pdf2.  

There's a comment in the code (plugins/org.dita.pdf2/xsl/fo/flagging-preprocess.xsl) which suggests that flagging shouldn't work:

   
   <xsl:template match="*[contains(@class, ' topic/topic ')]" 

But I suspect this comment predates the 1.7 flagging updates.

I would like to make flagging work on the topic root element for pdf2 and have worked out how to fix the code.

Also discussed here:  http://tech.groups.yahoo.com/group/dita-users/message/31152

Nigel

**Comment by raducoravu** [comment]
:+1: One of our users is also trying to flag an entire topic/task in the PDF and it does not work. DITA OT 2.3.2.

**Comment by raducoravu** [comment]
This is somehow also related to:
https://github.com/dita-ot/dita-ot/issues/1913
which would consider that setting the flagging condition directly on the topicref could also work in the PDF.
