### ISSUE TITLE
Duplicate ID in merged DITA to XSL-FO code

### ISSUE THREAD

**Issue by mkaatman** [dita-ot/dita-ot#1553]
Gist here:
https://gist.github.com/mkaatman/6370956

Check out the duplicate IDs on these lines: 
https://gist.github.com/mkaatman/6370956#file-topic-fo-L464
https://gist.github.com/mkaatman/6370956#file-topic-fo-L473

I haven't noticed any adverse effects from this issue. AHF formatter throws warnings but they don't seem consistent.

Tested in 1.7.5 and 1.8.0.

**Comment by robander** [comment]
This was fixed in 3.1 with #2985.
