### ISSUE TITLE
Can't provide alternative navtitle with topicsetref

### ISSUE THREAD

**Issue by ghost** [dita-ot/dita-ot#1580]
At least for HTML outputs, both `@navtitle`, navtitle (element), and linktext (element) are ignored for a topicsetref. There are use cases for providing alternative navigation titles, and nothing in the spec prohibits this.

**Comment by robander** [comment]
The DITA 1.3 specification includes this comment, in large part thanks to Jarno raising the question:
> As with other cases where the attribute `format="ditamap"` is specified or used as a default, the use of topic references nested inside of `<topicsetref>` is undefined.

There is no defined way to handle nested `<topicref>` elements in this situation - the general expectation is that the reference itself is replaced by the target, meaning that any nested elements tend to be informational (or erroneous).

I'm going to close this one as inactive - there has not been any activity in 2+ years, and updates in the DITA 1.3 spec clarify that there is really no defined behavior or purpose for nested topics. I expect the same is true for a navigation title.
