### ISSUE TITLE
Change bars from DITAVAL crash FOP

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1581]
Breaking this off from issue #1175 

When using changebar in a DITAVAL for revisions, the PDF code creates ```<fo:change-bar-begin>``` and ```<fo:change-bar-end>``` in the current context of the document. This means that for nearly every case, those elements become children of ```<fo:block>``` or ```<fo:inline>```. This doesn't meet the letter of the XSL-FO spec, which only allows change bars as a child of ```<fo:flow>```. When FOP encounters the change bars in these locations, it crashes.

We should update the build so that when using FOP, we skip generating those change bar elements, allowing the build to finish. AH currently ignores the elements, so we may as well leave them in, in case support comes along later. I'm not sure about XEP, but I think the original testing with this code used XEP so I'm guessing it either supports or ignores the markup.

**Comment by robander** [comment]
I'm no longer able to reproduce this in 2.2. It may have been fixed with the updates in 2.2 to use the flagging preprocess, or may have been fixed earlier. Either way, using the gist that failed in an older version, I get a PDF with no errors from FOP.

**Comment by shudson310** [comment]
I am getting this error in 2.3.2.
