### ISSUE TITLE
xref in <shortdesc> won't allways work

### ISSUE THREAD

**Issue by jkri** [dita-ot/dita-ot#1599]
When using an xref in a shortdesc 1.8 complains when the map and associated concepts are in a subdirectory. Moving them into a single directory will work.

-- documentation.ditamap --
````
<?xml version="1.0"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "../../map.dtd">
<map title="Bug" id="com.service2media.m2active.trunk">
  <topicref href="concepts_chapter.dita">
    <mapref href="refdoc/concepts.ditamap"/>
  </topicref>
</map>
```
-- refdoc/concepts.ditamap --
```
<?xml version="1.0"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "../../map.dtd">
<map title="concepts">
  <topicref href="concept_a.dita"/>
  <topicref href="concept_b.dita"/>
</map>
````
-- refdoc/concept_a.dita --
````
<?xml version="1.0"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "../../concept.dtd">
<concept id="concept_A" xml:lang="en-us">
  <title>A</title>
  <shortdesc>
    <ph><xref href="concept_b.dita">B</xref></ph>
  </shortdesc>
  <conbody>
    <section>
    <ph><xref href="concept_b.dita">B</xref></ph>
    </section>
  </conbody>
</concept>
````
-- refdoc/concept_B.dita --
````
<?xml version="1.0"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "../../concept.dtd">
<concept id="concept_B" xml:lang="en-us">
  <title>B</title>
  <shortdesc> </shortdesc>
</concept>
````

**Comment by drmacro** [comment]
I'm hitting this bug too.

In the resolved map the xrefs in the shortdesc are copied into the topicref without rewriting the @href values to reflect the relative location of the target topic. If the map and topics happen to be in the same directory then the href can be resolved, otherwise it cannot be resolved.

It looks like there's code in topicpullImpl that intends to handle this case but doesn't actually.

**Comment by raducoravu** [comment]
:+1: for us, we hit the same problem trying to resolve abbreviated forms in topic titles when building the TOC.

**Comment by jelovirt** [comment]
A customer got hit by this.
