### ISSUE TITLE
Indirect reference to keys erases one file, causes failures

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1600]
Encountered an issue similar to this with a much larger sample, encountered this specific issue while trying to debug the original with a clean set of samples. 

In my original case, the product defines a large set of plugins. Each set defines content in one set of maps, and creates a related map to define keys for topics in that plug-in.

All plug-ins pull in a common map from a peer directory, which in turn pulls in every key map. The result: every plug-in pulls in the common key map with a single topicref, which in turn pulls in key definitions from every plug-in; everybody can then use the common keys. No files are generated from outside the plug-in, but keys are retrieved.

When I construct a similar sample with the hierarchy samples, using 1.8.2, I get a java crash during the dit2xhtml stage. In this case all of my content and all of my keys are inside of samples/ but I go out and back in to define the keys. Checking the temp directory shows that tasks/washingthecar.xml is empty (zero length file), even though it is defined the same as other files. The only way this runs is if I set generate.copy.outer=3, which adjusts the output directory, even though no files are generated outside of that directory.

To reproduce, add this line to samples/hierarchy.ditamap:
```xml
<topicref href="../peer/allkeys.ditamap" format="ditamap"/>
```

Create this file peer/allkeys.ditamap:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN"
 "../dtd/technicalContent/dtd/map.dtd">
<map>
  <topicref href="../samples/samplekeys.ditamap" format="ditamap"/>
</map>
```

And create samples/samplekeys.ditamap:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN"
 "../dtd/technicalContent/dtd/map.dtd">
<map title="keys">
  <topicref href="tasks/garagetaskoverview.xml" type="concept" keys="overview"
    processing-role="resource-only"/>
  <topicref href="concepts/lawnmower.xml" type="concept" keys="lawnmower"
    processing-role="resource-only"/>
</map>
```

I get the failure with this command:
C:\DITA-OT1.8.M2>ant -f build.xml -Dargs.input=samples/hierarchy.ditamap -Dtranstype=xhtml -Dclean.temp=no 

I get a "clean" build with this:
C:\DITA-OT1.8.M2>ant -f build.xml -Dargs.input=samples/hierarchy.ditamap -Dtranstype=xhtml -Dclean.temp=no -Douter.control=quiet -Dgenerate.copy.outer=3

The clean build adjusts the output directory, which isn't actually needed, but is more of a minor annoyance than anything (I am not surprised by that when using -Dgenerate.copy.outer=3).

**Comment by jelovirt** [comment]
I get no errors with the latest code, closing as obsolete.
