### ISSUE TITLE
Two levels of map ref causes good key ref to fail

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1605]
This may be the same as issue 1600 or maybe not. 

Given a map that includes a map that then includes another map with a keydef, an xref to that keydef that is proven correct by Oxygen fails to resolve in the OT.

Test data set and OT log are available here:

http://github.com/drmacro/dita-13-spec/tree/master/temp

**Comment by eerohele** [comment]
Fixed by #1962.

**Comment by jelovirt** [comment]
@eerohele,could you also add 2.2 milestone as thus fix kinda goes to it.
