### ISSUE TITLE
chunk="to-content" and keyrefs to topics merged into parent topic don't work together

### ISSUE THREAD

**Issue by sorin-ristache** [dita-ot/dita-ot#1617]
The xref/@keyref links are not resolved when the target of the keyref is a topic that was merged into the parent due to the chunk="to-content" attribute added to the parent topicref of the target of the keyref. In the attached example (see https://gist.github.com/sorin-ristache/8052958) the link:

```
<xref keyref="link">target</xref>
```

remains unresolved in all DITA-OT transformations: PDF, XHTML, Windows Help, etc. The transformation is finished and the final output is created, but the link does not work. A transformation error related with the keyref link is like:

```
[topicpull] [DOTX031E][ERROR]: The file file:/D:/support/DITA/DITA-OT-bug-reports/temp/xhtml/subdir/link-target.dita is not available to resolve link information.  The location of this problem was at (File = D:\support\DITA\DITA-OT-bug-reports\subdir\link-source.dita, Element = xref:1;6:40)
```

Example files are at: https://gist.github.com/sorin-ristache/8052958

**Comment by mikeewins** [comment]
I've been implementing a solution based on 2.0.1 of the OT.

I have a map where the same image topic is referenced twice but with different keys.

An xref to the first instance keyref incorrectly resolves to the 2nd instance because the 1st instance is a child of a parent topic with a chunk="to-content" attribute.

If the chunk="to-content" is removed, the xref keyref correctly resolves to the first instance.

This behaviour appears to be related to the thread in this ticket.

Are there any plans to resolve the resolutiion of keyrefs to chunked child topics?

**Comment by radu-pisoi** [comment]
We have another user with a similar problem.

In this case, the link points to a topic that is merged into the content of the parent topic.

DITA Map:
```
<map title="Eclipse content aggregated by a map">
    <topicref href="tasks/garagetaskoverview.dita" type="concept" chunk="to-content">
        <topicref href="tasks/changingtheoil.dita" type="task"/>
    </topicref>    
</map>
```

Link in 'tasks/garagetaskoverview.dita':
```
<lines>here: <xref href="changingtheoil.dita"/></lines>
```

When publishing to XHTML we get the next error:
```
topicpull:
[topicpull] Transforming into D:\workspace\eXml\samples\dita\garage\temp\xhtml
[topicpull] Loading stylesheet C:\Users\radu_pisoi\Program Files\Oxygen XML Editor 17.1\frameworks\dita\DITA-OT2.x\xsl\preprocess\topicpull.xsl
[topicpull] Processing D:\workspace\eXml\samples\dita\garage\temp\xhtml\tasks\garagetaskoverview.dita
[topicpull] Recoverable error on line 581 of topicpullImpl.xsl:
[topicpull]   FODC0002: I/O error reported by XML parser processing
[topicpull]   file:/D:/workspace/eXml/samples/dita/garage/temp/xhtml/garagetaskoverview.dita:
[topicpull]   D:\workspace\eXml\samples\dita\garage\temp\xhtml\garagetaskoverview.dita (The system
[topicpull]   cannot find the file specified)
[topicpull] file:/D:/workspace/eXml/samples/dita/garage/tasks/garagetaskoverview.dita:13:50: [DOTX031E][ERROR]: The file file:/D:/workspace/eXml/samples/dita/garage/temp/xhtml/garagetaskoverview.dita is not available to resolve link information. 
```

**Comment by raducoravu** [comment]
:+1: from one of our users:

    I have a parent topic with chunk=”to-content”. In some of the child topic, I use xref to refer to figure or figures used in the topic.
     But when I run the transformation, I get an error that the dita file containing the image is not available to resolve link information.

**Comment by raducoravu** [comment]
:+1: One more report on DITA Users List:
https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/40503

Maybe we should change in topic title the word "keyrefs " with "links " as it happens for both keyrefs and hrefs.

**Comment by haolekatalon** [comment]
Hi I'm experiencing the same problem with chunk="to-content". If one topic is chunked with its parent, all xrefs to that topic is invalid. This happens with transformation scenarios like markdown, html5. However, it works fine with webhelp.
