### ISSUE TITLE
Include JEuclid -core and -fop jars in built-in FOP distribution

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1623]
DITA 1.3 includes built-in integration of MathML and I've implemented a simple plugin to emit MathML as fo:instream-foreign-object content. Using FOP 1.1 and the JEuclid core and fop jars, FOP can render the MathML.

It would be most convenient if the built-in FOP distribution for the org.dita.pdf2 transform included the jars necessary to do MathML rendering.

**Comment by robander** [comment]
Just ran in to this with our math usage. With JEuclid copied into the FOP directory, DITA 1.3 math elements render well; without it, they do not.

As delivered, our shipped FOP does not come with JEuclid, and there's no easy way to add it to the FOP-specific classpath:
```
<taskdef name="fop" classname="org.apache.fop.tools.anttasks.Fop" classpathref="dost.class.path">
      <classpath>
        <fileset dir="${fop.home}">
          <include name="lib/*.jar"/>
          <include name="build/fop.jar"/>
        </fileset>
      </classpath>
    </taskdef>
```

It looks like right now (unless / until DITA-OT bundles JEuclid), our options re:

- Copy it into the FOP dir -- need to remember to copy with each upgrade
- Update that classpath ref (with every upgrade) to add a reference to the JAR
- Pre-define fop.home to our own copy of FOP that includes JEuclid in the lib directory
- Define our own version of the full `transform.fo2pdf.fop` task and add the library there

Any other options?

**Comment by jelovirt** [comment]
The whole classpath in taskdef is the Wrong Way to handle the classpath. The correct way is to add it to global classpath with plugin configuration. The only reason that classpath configuration is still in Ant is historical and will be removed in 3.0.

**Comment by robander** [comment]
@drmacro also mentioned adding to global path in Slack. I completely missed the fact that it has `@classpathref` already, thus pulled in `dost.class.path`, thought it was just defining its own. User error, brought on by debugging through an IM chat window...

**Comment by raducoravu** [comment]
The latest Batik 1.10 libraries bundled with DITA OT 3.x are no longer compatible with Apache JEuclid (JEuclid implements some kind of API method from the DOM events package which has changed). The Apache JEuclid code needs to be slightly modified and then the "jeuclid-core.jar" rebuilt to remove this incompatibility problem.
The last release of JEuclid was in 2010 so it's kind of abandoned.
So if at some point we will want to include JEuclid we will probably need to fork it to the DITA OT organization.

**Comment by hcw70** [comment]
There seems to be ongoing development for JEuclid under https://github.com/rototor/jeuclid .
pls investigate if MathML can be fixed using that fork.
