### ISSUE TITLE
Complex map with outer paths and key refs produces no HTML for keyreffed topics

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1625]
Given a systems of maps that uses key refs from maps to point to topics and where the root map is not above all the sub maps and topics, the XHTML transform produces no HTML files for those topics referenced by key ref. Topics that are referenced directly are processed normally. The same map produces good PDF output.

Will provide test case and results separately.

This is the OT 1.8.M2 but I get the same behavior with 1.6.3.

**Comment by robertnthomas** [comment]
For XHTML, I have a similar case that exhibits a failure like @drmacro described. 

Consider this scenario:
terms.ditamap contains two keys bindings to glossary topics
some_topic.dita has a term keyref that points to one of the two keys declared in terms.ditamap
subdir/some_other_topic.dita has a term keyref that points to the other key declared in terms.ditamap
outer.ditamap contains topicrefs to each of the above, with the topicref to terms.ditamap having processsing-role="resource-only"
All files are in the same directory except for some_other_topic.dita which is located in a subdirectory named subdir

HTML gets generated for the term keyreffed from some_topic.dita, but no HTML gets generated for the term keyreffed from subdir/some_other_topic.dita. This is true regardless of how generate.copy.outer is set. Setting the processing-role to "normal" on the topicref to terms.ditamap results in both target HTML topics being generated. I have a .zip of the scenario if you would like it.
