### ISSUE TITLE
"Fix'" for multiple index targets in org.dita.dost.writer.HTMLIndexWriter.outputIndexTerm()

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#1628]
In the current code, whenever an index term has multiple targets, the outputIndexTerm() method outputs the term without a link because a single link cannot be created without arbitrarily picking one of the targets as the destination.

In a customization that I am doing, I solved this problem by using a small graphic as a clickable link (chicklet.gif)![chicklet](https://f.cloud.github.com/assets/3413005/1986230/165aec3a-844a-11e3-9036-2da4921983bb.gif)
for each target.

Existing code:

``` java
if(targetNum > 1) {
            serializer.writeCharacters(term.getTermFullName());
        } else {
            final IndexTermTarget target = targets.get(0);
            serializer.writeStartElement("a");
            serializer.writeAttribute("href", target.getTargetURI());
            serializer.writeCharacters(term.getTermFullName());
            serializer.writeEndElement(); // a
        }
```

Revised code:

``` java
        //Write the term name
        serializer.writeCharacters(term.getTermFullName());
        //Output a linked in-line graphic for each target
        for (IndexTermTarget target : targets) {
            serializer.writeStartElement("a");
            serializer.writeAttribute("href", target.getTargetURI());
            serializer.writeStartElement("img");
            serializer.writeAttribute("alt", "link");
            serializer.writeAttribute("src", "chicklet.gif");
            serializer.writeAttribute("border", "0");
            serializer.writeAttribute("hspace", "5");
            serializer.writeEndElement(); // img
            serializer.writeEndElement(); // a
        }
```

**Comment by robander** [comment]
Marking this as inactive. As far as I can tell this appears to be a stylistic choice, and I'm not clear at this point which output files would be affected by the change. The specific choice of a graphic seems best left to a customization - I think the most we could / should do in core code is making the index output easier to customize.
