### ISSUE TITLE
DOT 1.74: args.rellinks does not generate related links correctly for subjectScheme topics: html plugin

### ISSUE THREAD

**Issue by mikeewins** [dita-ot/dita-ot#1629]
Where a subjectScheme item links to a topic AND has a parent and children subjectScheme items, the related links are not generating correctly and not correctly controlled by the three values of args.rellinks.

In the following image:
![capture](https://f.cloud.github.com/assets/6482658/1987024/ad8fcb1c-8453-11e3-9ecb-632b70e30828.JPG)

The 'What is Shelf Review?' topic has a parent and children. It has related links entitled 'Parent Topic' but they are both Parent and Child topics.

No value of arg.rellinks will turn off these auto-generated links whilst allowing user created ones to be included.

**Comment by robander** [comment]
Marking this as closed - no sample was provided to reproduce the issue, and it has been marked inactive since October 2014. If a sample is provided we can take another look.
