### ISSUE TITLE
Inconsistent link text in keyref links to elements with <title>

### ISSUE THREAD

**Issue by eerohele** [dita-ot/dita-ot#1646]
**[Gist](https://gist.github.com/eerohele/9099773)**.

Tested on the current `develop` branch.

Given:

```
<xref keyref="keysValue/elementId"/>
```

And:

```
<topicref keys="keysValue" ... >
```

Which has:

```
<section id="elementId">
  <title>Hello, world</title>
  ...
</section>
```

The link text for `<xref>` is determined like this:

| topicref | link text |
| --- | --- |
| `@navtitle` | `@navtitle` value |
| `<navtitle>`, no `@navtitle` | `<section>` title |
| no `<navtitle>`, no `@navtitle` | `<section>` title |

Furthermore, it seems that DITA-OT never uses the value of `<navtitle>` as the link text -- only `@navtitle` (see the fourth link in `topic4.dita` in the Gist).

Should the navtitle really ever be used as the link text if the keyref points to an element with a `<title>` child? It seems counterintuitive to me.

**Comment by robander** [comment]
Adding "bug" tag as this looks incorrect - but also adding needs-reproduction, as it was opened 2+ years ago and I'd like to verify if it exists in 2.x.
