### ISSUE TITLE
Support DITA 1.3 scoped keys

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1648]
Support key scopes in DITA 1.3.

**Comment by jelovirt** [comment]
Initial code in #1979

**Comment by raducoravu** [comment]
I tested a little bit the support, I'm attaching a simple DITA Map project along with some observations:

http://www.oxygenxml.com/forum/files/keyScopes.zip

I published the DITA Map which has the content like:

      <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 1.3 Map//EN" "map.dtd">
      <map>
       <title>DITA Topic Map</title>
       <topicref href="potatoes.dita" keyscope="potatoes">
        <topicref href="common.dita" keys="vegetable">
         <topicmeta>
          <keywords>
           <keyword>Potatoes</keyword>
          </keywords>
         </topicmeta>
        </topicref>
       </topicref>
       <topicref href="carrots.dita" keyscope="carrots">
        <topicref href="common.dita" keys="vegetable">
         <topicmeta>
          <keywords>
           <keyword>Carrots </keyword>
          </keywords>
         </topicmeta>
        </topicref>
       </topicref>
      </map>

1) I got this message reported by the DITA OT, I'm not sure why:

      [DOTJ045I] The key "vegetable" is defined more than once in the same map file. The reference href="common.dita" is ignored.

2) The first resulting "common.html" correctly expands the key but it has a link on the "Potatoes" text although in the DITA topic I used:

      <ph keyref="...."

and not:

    <xref keyref="vegetable"

3) The second resulting common-2.html (the one in the second key scope) has the same problem with a link instead of plain text. And why does it have "-2" as a suffix? Shouldn't it have "-1"?

4) If in the DITA Map I define the keys directly on the topicrefs which have the keyscope, the output will not expand the keyref properly anymore:

     <map>
      <title>DITA Topic Map</title>
      <topicref href="potatoes.dita" keyscope="potatoes" keys="vegetable">
       <topicmeta>
        <keywords>
         <keyword>Potatoes</keyword>
        </keywords>
       </topicmeta>
       <topicref href="common.dita" keys="vegetable">
       </topicref>
      </topicref>
      <topicref href="carrots.dita" keyscope="carrots" keys="vegetable">
       <topicmeta>
        <keywords>
         <keyword>Carrots </keyword>
        </keywords>
       </topicmeta>
       <topicref href="common.dita"/>
      </topicref>
     </map>

**Comment by raducoravu** [comment]
Related to problem (2), I read more the specs:

http://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/processing_key_references.html

and it's correct that the ph with keyref becomes a link, because the key was specified directly on a topicref which had an href.

**Comment by raducoravu** [comment]
5) Another problem, if in the same sample DITA Map I add a new topic outside of any scope with the content:

        <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
        <topic id="vegetables_list">
          <title>Vegetables List</title>
          <body>
            <p><ph keyref="potatoes.vegetable"/> and <ph keyref="carrots.vegetable"/> can be peeled like:
            <ul>
              <li><xref keyref="potatoes.vegetable"/></li>
              <li><xref keyref="carrots.vegetable"/></li>
            </ul>
            </p>
          </body>
        </topic>

the link text is properly computed but all links point to "common.html" although the carrots link should point to the "common-2.html" which explains carrots peeling.

**Comment by jelovirt** [comment]
1) This comes from old key processing code, it'll be removed at some point.

**Comment by jelovirt** [comment]
3) The duplicate counters started from 2, changed it to start from 1 in #2aa6867

**Comment by jelovirt** [comment]
[5](https://github.com/dita-ot/dita-ot/issues/1648#issuecomment-131009713) reproduced

**Comment by jelovirt** [comment]
[4](https://github.com/dita-ot/dita-ot/issues/1648#issuecomment-131005720) reproduced.

**Comment by jelovirt** [comment]
Root cause for [5](https://github.com/dita-ot/dita-ot/issues/1648#issuecomment-131009713) is that in key module keys are resolved first, per scope. Then, how duplicated files are renamed is processed during key resolution. The code should be refactored so that the order of processing is something like:
1.  read key scopes
2.  determine how duplicates are renamed
3.  resolve keys in topic/maps
Step 2 doesn't exists yet as a separate step.

**Comment by jelovirt** [comment]
Closing as the initial implementation has been in `develop` for a while now. Rest of the implementation should be handled as bug issues.
