### ISSUE TITLE
Support DITA 1.3 link syntax

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1649]
Add support for DITA 1.3 same topic fragment identifier `topic#./element`.

**Comment by raducoravu** [comment]
Conref's don't seem to work for me, I'm using DITA OT 2.1.
So if in a topic I have a paragraph:

     <p id="pidi">This is a para</p>

I can make a conref to it like:

     <p conref="#./pidi"/>

but the XHTML and PDF outputs do not seem to show the paragraph.

**Comment by jelovirt** [comment]
That's because the same topic fragment rewrite is done after conref. We need to move it before conref processing.
