### ISSUE TITLE
DITA-OT does not rewrite xrefs to topic elements correctly during preprocessing when chunk = "to-content" is specified

### ISSUE THREAD

**Issue by rieztra** [dita-ot/dita-ot#1655]
When chunk = "to-content" is specified, DITA-OT creates a ditabase document during preprocessing that contains all of the topics that are being chunked.  If the topics' IDs contain any duplicates, then unique IDs are generated to make all of the topic IDs unique in the ditabase document.  However, xrefs to topic elements don't properly get rewritten.  I am enclosing a sample .ditamap containing three topics that demonstrates the problem.

In the sample, the topics intro.dita, topic1.dita, and topic2.dita all contain id = "topicid" on the topic.  This is valid since the ID is unique within each topic.

The chunk.ditamap contains chunk = "to-content" on intro.dita telling the DITA-OT that we want intro.dita, topic1.dita, and topic2.dita output as a single file.  During preprocessing, the DITA-OT will create intro.dita as a single ditabase document containing the contents of the three topics.  Since taken together there would be duplicate IDs, the DITA-OT writes unique IDs for the contents of topic1.dita and topic2.dita in the ditabase document.

The problem is the xrefs in topic1.dita and topic2.dita are not rewritten to contain the new, unique IDs.

Reproducible using DITA-OT1.7.5 and DITA-OT1.8.4.

https://drive.google.com/file/d/0ByZs7YV5C0j0QWV3TVppSGRZXzQ/edit?usp=sharing

**Comment by tyrin** [comment]
We also have run into this bug and am wondering if it's been fixed in DITA-OT 2.0

**Comment by raducoravu** [comment]
Tested publishing to HTML5 with DITA OT 3.x, problem can still be reproduced. Attaching also a zip with the samples as the original samples are on Google Drive. 
[chunk-internal-links.zip](https://github.com/dita-ot/dita-ot/files/2675196/chunk-internal-links.zip)
