### ISSUE TITLE
Add more @class attributes on spans and divs created by XSLT for XHTML output

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1669]
The XSLT stylesheets for XHTML output create in some places artificial `<span>` or `<div>` elements. For example in this XSL "DITA-OT/plugins/org.dita.xhtml/xsl/xslhtml/rel-links.xsl" there are places like:

``` xml
<div><xsl:call-template name="makelink"/></div>
```

Ideally all these extra generated spans and divs created in the XHTML XSLT code should have a `@class` attribute set to them so that they can be styled using CSS.

**Comment by robander** [comment]
Thinking about this one - I tend to agree, I like having the extra classes available to do something with as needed. That said, I've had (one or two) people complain that HTML5 output should be clean / simple / not cluttered, and have asked me to remove extra classes that were not explicitly needed. 

Of course, those same people wouldn't like extra `<div>` or `<span>` elements that do not serve a clear purpose anyway. Those of us familiar with the mapping from DITA can often relate those elements to the original source, but if you only care about the HTML markup, it tends to look more cluttered than needed. That's probably not something we can easily solve, so it's likely not worth worrying about here.

**Comment by infotexture** [comment]
See #2239 for related changes to HTML5 table markup _(released w/ v2.3)_.

Perhaps that same approach could be applied elsewhere in HTML5 output to provide [BEM](https://en.bem.info/methodology/)-style CSS classes. 

IIRC, the clutter issue can be addressed with the `args.xhtml.classattr` parameter that specifies whether to include the DITA class ancestry in the generated CSS classes, so those who prefer clean markup can have that, while still supporting use cases that require more granular class information.
