### ISSUE TITLE
Image without an @href attribute generates error in XSLT stylesheet for PDF transformation (DOT 1.8)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1675]
If in the DITA content I have something like:

``` xml
<image id="image_b4j_s4w_zn"/>
```

and I transform to PDF I get an error in the XSLT:

> D:\projects\eXml\frameworks\dita\DITA-OT\plugins\org.dita.pdf2\build.xml:324: Fatal error during transformation using D:\projects\eXml\frameworks\dita\DITA-OT\plugins\org.dita.pdf2\xsl\fo\topic2fo_shell_fop.xsl: An empty sequence is not allowed as the first argument of opentopic-func:isAbsolute(); SystemID: file:/D:/projects/eXml/frameworks/dita/DITA-OT/plugins/org.dita.pdf2/xsl/fo/commons.xsl; Line#: 1902; Column#: -1

Maybe we could give a more precise message in this case.

**Comment by annette-b** [comment]
Hello, I've installed DITA OT 1.8.5 with Oxygen 16.1 and it seems that the issue is still here. 
Imho, it is not a problem to get an error, the only problem I have is that the message is not clear and we don't know where the href is missing (which image or at least which topic).

**Comment by raducoravu** [comment]
The DITA OT 1.8 which comes with Oxygen 16.1 should have this fix included.
For example I tried to publish to PDF a topic which had an image reference like:

    <image scale="50"/>

and I did not receive the original error reported in this bug report.
So could you post the error you are receiving?

To find all images with missing @href with Oxygen you should open the main DITA Map in the DITA Maps manager view, right click the map root, choose "Find Replace in Files", search for the string       

   <image

and use the "Restrict to XPath" field to restrict the search to the XPath: 

     //image[not(@href)]

**Comment by annette-b** [comment]
I've inserted an image with just the ID (automatically added by Oxygen) and I got the following error message:

BUILD FAILED
C:\Program Files\Oxygen XML Editor 16.1\Oxygen XML Editor 16\frameworks\dita\DITA-OT\build.xml:53: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 16.1\Oxygen XML Editor 16\frameworks\dita\DITA-OT\plugins\org.dita.pdf2\build.xml:151: The following error occurred while executing this line:
C:\Program Files\Oxygen XML Editor 16.1\Oxygen XML Editor 16\frameworks\dita\DITA-OT\plugins\org.dita.pdf2\build.xml:324: Fatal error during transformation using C:\Program Files\Oxygen XML Editor 16.1\Oxygen XML Editor 16\frameworks\dita\DITA-OT\plugins\org.dita.pdf2\xsl\fo\topic2fo_shell_xep.xsl: An empty sequence is not allowed as the first argument of opentopic-func:isAbsolute(); SystemID: file:/C:/DITA_customization/com.fresenius.custpdf/cfg/fo/xsl/commons.xsl; Line#: 1932; Column#: -1

I'm using XEP engine, which may fail on error where FOP wouldn't? 
Btw, thanks for the tip to find images without href, it's exactly what I needed.

**Comment by raducoravu** [comment]
Annette,

The problem seems to be reported in a custom XSLT which you have created as part of a PDF customization plugin:

   com.fresenius.custpdf/cfg/fo/xsl/commons.xsl

So you can modify your custom XSL to report a better message for the issue.

**Comment by annette-b** [comment]
Shame on me, you're right. I updated commons.xsl in my plugin with the one from the DITA OT 1.8.5 and it works well now. Sorry ...
