### ISSUE TITLE
Lists not handled correctly in DITA RTF transform

### ISSUE THREAD

**Issue by sorin-ristache** [dita-ot/dita-ot#1681]
The list item markers for both ordered lists (the number 1, or 2, or 3, etc that precedes the text of the list item) and unordered lists (the bullet that precedes the text of the list item) are not outputted in the RTF output. The text in the list items appears in the output like a simple paragraph.

**Comment by robander** [comment]
Can still reproduce with 2.2.4, but not optimistic about a fix, as there is very little maintenance of RTF.
