### ISSUE TITLE
generate-page-sequence-master only has odd-page first-page conditional master reference

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1688]
in generate-page-sequence-master there is this conditional page sequence template:

```
      <fo:conditional-page-master-reference master-reference="{$master-reference}-first"
                                            odd-or-even="odd"
                                            page-position="first"/>
```

Note the odd-or-even="odd". This appears to be consistent from 1.6.3 to current dev branch.

This causes the problem that if you set the initial page number to an even value then there is no first-page conditional master reference that will match.

I see two possible solutions:
1. Remove the odd-or-even. I think this is appropriate but I'm not 100% sure there's not some reason to have this particular set of conditions.
2. Add a corresponding even-page version of the conditional reference.

Which fix is appropriate?

Cheers,

Eliot

**Comment by robander** [comment]
@drmacro I know page sequences have changed over time, as discussed in some recent issues - do you know if this is still an issue in 2.x?

**Comment by drmacro** [comment]
The problem is still in 2.2.4.

**Comment by drmacro** [comment]
I think the best solution is to have a new even-page version of the condition.
