### ISSUE TITLE
NullPointerException when we have absolute references to DITA resources

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1696]
Let's say I have a DITA Map with an absolute reference to a topic:

     <topicref href="file:/D:/projects/eXml/samples/dita/flowers/topics/introduction.dita" id="t1" keys="KEY1"/>

when it gets published to XHTML or PDF a NullPointerException is thrown in the DITA OT code:

          DITA-OT\plugins\org.dita.base\build_preprocess.xml:34: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'D:\projects\eXml\samples\dita\flowers\flowers.ditamap'. The XML parser reported the following error: : null

The internal NPE is this one:

            [gen-list] java.lang.NullPointerException
             [gen-list] 	at org.dita.dost.util.FileUtils.isDITATopicFile(FileUtils.java:232)
             [gen-list] 	at org.dita.dost.reader.GenListModuleReader.parseAttribute(GenListModuleReader.java:1344)
             [gen-list] 	at org.dita.dost.reader.GenListModuleReader.startElement(GenListModuleReader.java:952)
             [gen-list] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
             [gen-list] 	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
             [gen-list] 	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.emptyElement(RelaxNGDefaultsComponent.java:635)
             [gen-list] 	at org.apache.xerces.impl.dtd.XMLDTDValidatorXerces.emptyElement(XMLDTDValidatorXerces.java:852)
             [gen-list] 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:260)
             [gen-list] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1655)
             [gen-list] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:325)
             [gen-list] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
             [gen-list] 	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:150)
             [gen-list] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
             [gen-list] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
             [gen-list] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
             [gen-list] 	at org.dita.dost.reader.GenListModuleReader.parse(GenListModuleReader.java:617)
             [gen-list] 	at org.dita.dost.module.GenMapAndTopicListModule.processFile(GenMapAndTopicListModule.java:429)
             [gen-list] 	at org.dita.dost.module.GenMapAndTopicListModule.processWaitList(GenMapAndTopicListModule.java:389)
             [gen-list] 	at org.dita.dost.module.GenMapAndTopicListModule.execute(GenMapAndTopicListModule.java:279)
             [gen-list] 	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:64)
             [gen-list] 	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:140)
             [gen-list] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
             [gen-list] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
             [gen-list] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
             [gen-list] 	at java.lang.reflect.Method.invoke(Unknown Source)
             [gen-list] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
             [gen-list] 	at org.apache.tools.ant.Task.perform(Task.java:348)
             [gen-list] 	at org.apache.tools.ant.Target.execute(Target.java:435)
             [gen-list] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
             [gen-list] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
             [gen-list] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
             [gen-list] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
             [gen-list] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
             [gen-list] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
             [gen-list] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
             [gen-list] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
             [gen-list] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
             [gen-list] 	at java.lang.reflect.Method.invoke(Unknown Source)
             [gen-list] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
             [gen-list] 	at org.apache.tools.ant.Task.perform(Task.java:348)
             [gen-list] 	at org.apache.tools.ant.Target.execute(Target.java:435)
             [gen-list] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
             [gen-list] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
             [gen-list] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
             [gen-list] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
             [gen-list] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
             [gen-list] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
             [gen-list] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
             [gen-list] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
             [gen-list] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

I don't think this situation should break the processing.
The code in "GenListModuleReader" seems to try to treat absolute URL references in some silly way:

        if (attrValue.startsWith("file:/") && attrValue.indexOf("file://") == -1) {
            attrValue = attrValue.substring("file:/".length());
            // Unix like OS
            if (UNIX_SEPARATOR.equals(File.separator)) {
                attrValue = UNIX_SEPARATOR + attrValue;
            }
        } else if (attrValue.startsWith("file:") && !attrValue.startsWith("file:/")) {
            attrValue = attrValue.substring("file:".length());
        }

and then it has an "if" clause where it forgets to update the "filename" variable:

        if (target.isAbsolute() && !ATTRIBUTE_NAME_DATA.equals(attrName)) {
            attrValue = FileUtils.getRelativePath(rootFilePath.getAbsolutePath(), attrValue);
            // for object tag bug:3052156
        }

**Comment by jelovirt** [comment]
Closing as obsolete.
