### ISSUE TITLE
Use "resourceid" value to generate anchor in the PDF

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1708]
If a DITA topic uses the resourceid element:

http://docs.oasis-open.org/dita/v1.2/os/spec/langref/resourceid.html#resourceid

in its prolog:

```
  <prolog>
    <resourceid id="sqlid00375" appname="dbaccess"/>
  </prolog>
```

at least when creating PDF with Apache FOP we could use the fox:destination extension:

http://xmlgraphics.apache.org/fop/0.95/extensions.html

to add an anchor in the PDF. In this way, you could have some contextual help linking to various parts of a PDF document using these anchors.

**Comment by robander** [comment]
There is a lot of theoretical discussion in this thread that I think got away from the original request -- automatically create anchors in PDF based on `<resourceid>` values.

There are couple of open design questions there if it is going to be implemented -- what to do with duplicates? All resource IDs or based off of some key (like `appname="pdf"`)? Is there any validation?

Starting with 3.1 I've added the ability to easily insert custom anchors in a plugin, with #2984 and the `customTopicAnchor` mode that's called for every topic. I'm using that now in our customizations -- when the original topic ID is unique across topics in the map, I insert an anchor, and using that to link within a book.

Of course it's not automatic, but means the function requested here could now be done in a pretty straightforward plugin, with answers to the questions above handled per local rules.
