### ISSUE TITLE
The "path2project-uri" is not output in chunked topics [DITA OT 1.8]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1711]
Let's say my DITA Map references a topic like:

```
       <chapter chunk="to-content" href="path/topic.dita" type="concept" collection-type="sequence"/>
```

In the temporary files folder the "topic.dita" will contain only this PI:

```
      <?path2project ..\?>
```

when it should also contain:

```
      <?path2project-uri ../?>
```

This is because the "org.dita.dost.writer.ChunkTopicParser" class only outputs the older path2project PI.

As side effect, paths to common CSSs for the XHTML outputs will be invalidly computed.

**Comment by martinpaterson** [comment]
Workaround (from referenced bug report in oxygenxml/userguide): use "select-branch to-content by-content" instead of just "to-content".
