### ISSUE TITLE
PDF2 and HTML Table Processing Handle bad @colnum values differently

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1715]
In the case where a table has incorrect @colnum values for colspecs, in particular, where the values are not in ascending order starting at 1, neither the HTML renderer nor the PDF2 renderer report the error (see https://www.oasis-open.org/specs/a502.htm under the description of tgroup [search on "colnum"]).

In the case where there are span specifications that reference the column *names*, the PDF2 renderer correctly (I think) fails to render the table, because the column order is not correct (that is, if I'm reading the code correctly, it takes the @colnum value as the actual column position, which in this case results in column 3 being before column 1 per the @colnum values).

The HTML table renderer renders the spanning "correctly" (that is, as if the @colnum attributes were not present) even though it shouldn't.

In both cases the @colnum values are incorrect per the CALS table spec (as I'm reading it) and both should report the error even if their behavior is different.

As far as I can tell @colnum is pretty much pointless, so it's certainly reasonable to simply ignore it for all table rendering purposes, which would suggest making the PDF2 table handling match the HTML handling so that the table is rendered as the author intended rather than failing because the colnum values are incorrect. As far as I can tell, @colnum is completely pointless since the only correct values should simply reflect the ordinal number of columns based on the source order of the colspecs, so ignoring it completely seems like the most appropriate behavior.

I can provide a sample table that demonstrates the problem.

**Comment by robander** [comment]
This is related to #2212 where discussion questions the existence of our table normalization code, and also questions how much validation we should do against the CALS spec (there are a lot of ways to intentionally create invalid tables, I doubt we will ever check for all of them). 

I'm going to mark this one closed, and add a comment to 2212 highlighting that this is yet another example of bad CALS markup that throws off our table processing.
