### ISSUE TITLE
Using glossref in the DITA Map does not produce by default content for abbreviated-form

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1721]
Let's say in the DITA Map I have a glossref:

``` xml
<glossref href="test.dita" keys="abskey"/>
```

to a glossentry and then in another topic I have an abbreviated form referencing to it:

``` xml
<abbreviated-form keyref="abskey"/>
```

When producing PDF by default the abbreviated form will not be shown at all in the PDF.
In order to make this work, you would need to set "print="yes"" on the glossref but this would mean that the glossentry will also be added as content in the PDF (although not in the TOC), thing which may not be desired by users.

So I think the behavior should be:

If the glossref is with print="no" (the default value) the abbreviated form should be expanded properly and the PDF content should not contain the glossentry inside.

If the glossref is with print="yes", the abbreviated form should also be expanded properly and have a link on it pointing to the glossary content in the PDF.

**Comment by DJBHollis** [comment]
[Re: [dita-users] glossref problem in PDF transform - solution in the authored DITA or in the DITA OT?](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/39959)

[Term works, but abbreviated-form doesn't + doc on abbrevlist](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/41356)

@drmacro comment mentions "... "filtering aware" preprocessing is something we're discussing for DITA 1.3 processing implementation."

Does this mean that this issue can now be fixed?

**Comment by xephon2** [comment]
@DJBHollis, there is another issue that is related to this topic: #2173

**Comment by DJBHollis** [comment]
I appreciate the comments that filtering is early on in the processing.

However, it is quite possible to set up a 'collection topic' that provides element level content for reuse. This uses <keydef> and '@conkeyref.

**Comment by DJBHollis** [comment]
Another thread on DITA-Users:

[Any way to use but omit the inclusion of the actual glossary definitions in a PDF?](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/44403)
