### ISSUE TITLE
Too many files generated in XHTML output folder when using conref situation

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1734]
Let's say I have a DITA Map:

```
 <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
 <map>
  <title>DITA Topic Map</title>
  <topicref href="a.dita"/>
 </map>
```

and 3 topics. 

a.dita:

```
  <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
  <topic id="topic_zlx_4gd_hp">
    <title>ABC</title>
    <body>
      <p>ADITA </p>
      <p conref="b.dita#topic_gwk_qgd_hp/p_k5d_tgd_hp"/>
    </body>
  </topic>
```

b.dita:

```
    <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
    <topic id="topic_gwk_qgd_hp">
      <title>B</title>
      <body>
        <p id="p_k5d_tgd_hp">BDITA</p>
        <p><xref href="c.dita"></xref></p>
      </body>
    </topic>
```

c.dita:

```
  <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
  <topic id="topic_snj_chd_hp">
    <title>CCC</title>
    <body>
      <p>CDITA</p>
    </body>
  </topic>
```

When publishing to XHTML, only the "a.html" should be present in the output folder. Right now in the output folder we also have the "c.html" which is referenced from a part of "b.dita" which should have been ignored by the processing.

**Comment by raducoravu** [comment]
👍 Another one of our users encountered this problem.

**Comment by eerohele** [comment]
[Test files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1734).

Probably also relevant for #2077.

`GenListModuleReader.java` goes through all elements in the input files. It sees `<topicref href="topic3.dita" processing-role="resource-only"/>` and marks `topic3.dita` as resource-only.

Later, it sees `<xref href="topic3.dita"/>`. The code doesn't check whether `topic3.dita` has already been marked as resource-only and assigns it the (implicit) normal processing role, overriding the previously set role.

So, a possible fix might be to check whether a topic (uniquely identified by its absolute URI) has already been assigned a processing role previously:

```diff
diff --git a/src/main/java/org/dita/dost/reader/GenListModuleReader.java b/src/main/java/org/dita/dost/reader/GenListModuleReader.java
index dc4b46c..6faaa99 100644
--- a/src/main/java/org/dita/dost/reader/GenListModuleReader.java
+++ b/src/main/java/org/dita/dost/reader/GenListModuleReader.java
@@ -385,10 +385,14 @@ public final class GenListModuleReader extends AbstractXMLFilter {
         final URI href = toURI(atts.getValue(ATTRIBUTE_NAME_HREF));
         final String scope = atts.getValue(ATTRIBUTE_NAME_SCOPE);
         if (href != null && !ATTR_SCOPE_VALUE_EXTERNAL.equals(scope)) {
+            URI topic = stripFragment(currentDir.resolve(href));
+
             if (ATTR_PROCESSING_ROLE_VALUE_RESOURCE_ONLY.equals(processingRole)) {
-                resourceOnlySet.add(stripFragment(currentDir.resolve(href)));
+                resourceOnlySet.add(topic);
             } else {
-                normalProcessingRoleSet.add(stripFragment(currentDir.resolve(href)));
+                if (!resourceOnlySet.contains(topic)) {
+                    normalProcessingRoleSet.add(topic);
+                }
             }
         }
 ```

I wonder whether there's some scenario where it would be possible to first mark a topic as resource-only and later change the processing role back to normal, though? I don't think so, but I could be wrong.

@raducoravu: Are you able to check whether that fix works for you?

**Comment by eerohele** [comment]
>I wonder whether there's some scenario where it would be possible to first mark a topic as resource-only and later change the processing role back to normal, though? I don't think so, but I could be wrong.

Actually, #2493 has just such a scenario, so scratch that fix.

**Comment by eerohele** [comment]
I guess one option would be to only allow topicref elements to override a previously set processing role? As in:

```diff
diff --git a/src/main/java/org/dita/dost/reader/GenListModuleReader.java b/src/main/java/org/dita/dost/reader/GenListModuleReader.java
index dc4b46c..ee7a937 100644
--- a/src/main/java/org/dita/dost/reader/GenListModuleReader.java
+++ b/src/main/java/org/dita/dost/reader/GenListModuleReader.java
@@ -382,18 +382,22 @@ public final class GenListModuleReader extends AbstractXMLFilter {
         }
         processRoleStack.push(processingRole);
 
+        final String classValue = atts.getValue(ATTRIBUTE_NAME_CLASS);
+
         final URI href = toURI(atts.getValue(ATTRIBUTE_NAME_HREF));
         final String scope = atts.getValue(ATTRIBUTE_NAME_SCOPE);
         if (href != null && !ATTR_SCOPE_VALUE_EXTERNAL.equals(scope)) {
+            URI topic = stripFragment(currentDir.resolve(href));
+
             if (ATTR_PROCESSING_ROLE_VALUE_RESOURCE_ONLY.equals(processingRole)) {
-                resourceOnlySet.add(stripFragment(currentDir.resolve(href)));
+                resourceOnlySet.add(topic);
             } else {
-                normalProcessingRoleSet.add(stripFragment(currentDir.resolve(href)));
+                if (!resourceOnlySet.contains(topic) || MAP_TOPICREF.matches(classValue)) {
+                    normalProcessingRoleSet.add(topic);
+                }
             }
         }
 
-        final String classValue = atts.getValue(ATTRIBUTE_NAME_CLASS);
-
         if (foreignLevel > 0) {
             foreignLevel++;
             return;
```

**Comment by robander** [comment]
Attaching @raducoravu 's original test case above; the pull request that just linked here fixes the issue when `onlytopic.in.map` is true, and gives better (but still not 100%) results when `onlytopic.in.map` is false or unspecified.
[1734.zip](https://github.com/dita-ot/dita-ot/files/1015223/1734.zip)

**Comment by drmacro** [comment]
I would consider onlytopic.in.map=false to be a "you're on your own in this case" situation and therefore anything the OT does is appropriate, because you shouldn't be doing this in the first place.

IMHO having a direct URI reference to a topic *at any time* is user error, but to a topic that is not also included as a normal-role resource via the map is definitely a user error.

Now that DITA provides a mechanism for cross-deliverable links the practical requirement for direct URI references to not-in-map topics should go away, provided the OT implements some useful behavior, even if it's to do what it's always done and blindly generate a link to the target topic.

**Comment by robander** [comment]
> I would consider `onlytopic.in.map=false` to be a "you're on your own in this case" situation and therefore anything the OT does is appropriate, because you shouldn't be doing this in the first place.

I ... well, yes. I've never understood that default, but it was there from before toolkit 1.0 (in the beta days), and `onlytopic.in.map` was added as a way to get around it. Maybe in 3.0 we should consider flipping this default?

> IMHO having a direct URI reference to a topic at any time is user error, ...

Having one? Definitely disagree, if only because I don't consider it user-error to have unmodified years-old topics. ;-) 

> ... but to a topic that is not also included as a normal-role resource via the map is definitely a user error.

I'm on the same page here - in line with my views on the `onlytopic.in.map` default, I consider that if you want content generated, it should be in the map, with a normal role.

Thanks for the feedback.

**Comment by robander** [comment]
I think #2694 takes this fix as far as it can without switching to a map-first process. At least with that, in the 2.5 release, you will get the correct output from Radu's original sample when using `onlytopic.in.map=true`.

**Comment by robander** [comment]
Marking closed - using `onlytopic.in.map=true` will now give the correct results, and results with `onlytopic.in.map` are limited by the current DITA-OT preprocess design.
