### ISSUE TITLE
Processing seems to parse as resource key name ending with ".xml" [DOT 1.8.5]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1736]
Let's say in my DITA Map I have a topicref like:

```
 <topicref href="topics/introduction.dita" keys="process.xml"/>
```

The DITA OT processing shows an error message like:

```
[DOTX008E] File 'D:\projects\eXml\samples\dita\flowers\processing.xml' does not exist or cannot be loaded.
```

as if it attempted to parse the name of the key.

**Comment by robander** [comment]
It's been 2.5 years since the comment that this can be closed if nobody comes forward with a fix -- given that time, and given that there is no real chance of shipping 1.8.6 at this point, I'm going to mark this one closed.
