### ISSUE TITLE
Support DITA 1.3 base element topic/div

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1737]
topic/div is the only new base element type in DITA 1.3. To support it we simply need the trivial fallback handling in each output type, e.g., div -> div in HTML, div -> fo:wrapper in FO (or produces no direct output, just applying templates to its children).

This support cannot be implemented as a standalone plugin because this template must be imported before any non-base XSLT modules so that it doesn't inadvertently override templates for specializations of div (e.g., all the learning2 interactions).

I'm happy to take on the task. 

I'd like to do this in 1.7 and 1.8 as well so that plugin implementors don't have to worry about getting a fallback for topic/div.

**Comment by robander** [comment]
Marking this closed - as discussed periodically at our contributor calls, we do not anticipate any updates for the 1.x releases, particularly functional updates that mix in DITA 1.3 function that is only supported / advertised in the 2.x releases. For situations with a hard requirement on both DITA 1.3 markup and DITA-OT 1.8.5 or earlier, the best approach is the simple plugin one Eliot mentioned above.
