### ISSUE TITLE
Single-step tasks numbers the step

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#175]
Converted from [SourceForge issue 1647267](http://sourceforge.net/support/tracker.php?aid=1647267), submitted by paul_cpwr

If a task topic contains a <steps> element with only one child <step>, the FO plug-in still numbers the step. This is in conflict with the handling in the HTML-based outputs where single-step tasks are formatted without a number on the single step.

**Comment by dan-caprioara** [comment]
It is impossible to differentiate between a single step from a "steps" or "steps-unordered" element, because the generated HTML misses the class attribute on the section element:
&lt;section>
      &lt;div class="li step p">
                &lt;span class="ph cmd">This is a command&lt;/span>
      &lt;/div>
&lt;/section>

**Comment by raducoravu** [comment]
@dan-caprioara maybe you can add a separate issue for this.
