### ISSUE TITLE
Provide way in plugin.xml to specify the list of public parameters added for each transtype

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1757]
Let's say you develop a plugin for the DITA OT which contributes a new transtype.
In addition to the common parameters your plugin also accepts a set of custom parameters which can be set by the end user to customize the output generation.
Right now the user needs to look in the plugin's documentation in order to see which parameters are accepted by the plugin, what description, values and default values they have.

If there would be some kind of metadata in the plugin.xml which would advertize for each transtype a list of parameters (with name, type, possible values and description) then an automated script or a GUI interface could automatically discover and show to the end user the set of parameters which could be configured for that particular transtype.

**Comment by robander** [comment]
Coming back online again, no additional comments about the latest schema suggestion.

In the past I've used a (somewhat hacked together) item in the plugin.xml file to indicate ownership of the plugin. If we're using the plugin.xml file to generate docs, it would be really nice to make that a more formal / more encouraged item in plugin.xml. That way the generated docs for any add-on transform could clearly state the owner/maintainer of that plug-in. This would be particularly useful as we try and come up with ways to direct people to more plug-ins.

That said, if the mechanism for finding / installing plugins also gives you the owner, and we can pick that up for the generated docs, then we may not need to encourage additional info in plugin.xml.

**Comment by raducoravu** [comment]
I started manually creating such metadata information for each parameter in the DITA OT 1.8 bundled with Oxygen in order to start using this metadata in Oxygen as the default way of specifying parameters. But there are probably more parameters in DITA OT 2.0 so they would need to be updated.
So I could try to issue pull requests on each plugin.xml from the DITA OT project with the metadata I've added so far.
Jarno, do you want to generate this information automatically from the specs? One problem with automatic generation would be that you might not be able to automatically generate the set of allowed values and to mark the proper value as a default value.
