### ISSUE TITLE
keyref used in a topic that has been defined by @copy-to does not get resolved

### ISSUE THREAD

**Issue by jomjohn** [dita-ot/dita-ot#1758]
During preprocessing where filenames of topics and maps that contain a keyref are added to keyref.list the copied topics do not seem to be processed.

This results in a topic where the keyref is not resolved correctly.

I am currently using DITA-OT 1.6 and I have also confirmed the same results by testing 1.8.

**Comment by raducoravu** [comment]
I also could reproduce the issue with DITA OT 1.8 but could not reproduce this with DITA-OT 2.0.
So this probably can be closed.
