### ISSUE TITLE
Processing external/remote DITA resources (http://)

### ISSUE THREAD

**Issue by ColinMaudry** [dita-ot/dita-ot#1762]
Hello,
In #501, @jelovirt (or smalldog) states that file:/// and scope="external" resources are not copied to the temp directory, thus not processed. Even if they are DITA resources (`format="dita"` or `@href` ends with ".dita")?
If so, why is there such limitation?
This would be a shame because that would prevent the referencing of resources available on another server and resources generated dynamically by a Web service, which is common practice in enterprise environments.
I've tried with a map with a topicref to a static DITA topic stored on a remote server (http://), and indeed, it was skipped. I used the DITA OT bundled in Oxygen 16.1.
Thanks for shining a light on this matter.

**Comment by lagivan** [comment]
@jelovirt As far as I see, you've already committed the code changes to support absolute URIs. Are they fully supported now? I'm testing with 2.0 and getting errors.

This is my topic reference in the ditamap:

    <topicref id="package_information" href="http://localhost:8080/exist/apps/ssg/topics/package_information.dita?irdi=0060-414673376---SPC_1_1~Z1-ACH404~001&amp;type=package" format="dita"/>

And here are the errors:

```
  [mappull] C:\Users\lagivan\Downloads\ssg\test\data\package.ditamap:2:192: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'http://localhost:8080/exist/apps/ssg/topics/package_information.dita?irdi=0060-414673376---SPC_1_1~Z1-ACH404~001&amp;type=package'.
  [mappull] C:\Users\lagivan\Downloads\ssg\test\data\package.ditamap:2:192: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'http://localhost:8080/exist/apps/ssg/topics/package_information.dita?irdi=0060-414673376---SPC_1_1~Z1-ACH404~001&amp;type=package'.
    [chunk] c:\Temp\dita\temp\http:\localhost:8080\exist\apps\ssg\topics\package_information.dita?irdi=0060-414673376---SPC_1_1~Z1-ACH404~001&type=package (The filename, directory name, or volume label syntax is incorrect)
    [chunk] c:\Temp\dita\temp\http:\localhost:8080\exist\apps\ssg\topics\package_information.dita?irdi=0060-414673376---SPC_1_1~Z1-ACH404~001&type=package (The filename, directory name, or volume label syntax is incorrect)
     [xslt] C:\Users\lagivan\Downloads\ssg\test\data\package.ditamap:2:192: [PDFX005F][FATAL]: Topic reference (href : #null) not found. Reference may be incorrect. Please correct your ditamap or bookmap file.
Error: The following error occurred while executing this line:
c:\Programs\DITA-OT\plugins\org.dita.pdf2\build.xml:335: net.sf.saxon.instruct.TerminationException: Processing terminated by xsl:message at line 75 in output-message.xsl
```

P.S. 
1. format="dita" does not seem to affect anything, the result is the same when format is not specified
2. Simpler URIs without any query string parameters give the same errors.

**Comment by lagivan** [comment]
After I've removed chunk="to-content" from the map element, the errors have changed to my surprise:

```
  [mappull] <the same error as above>
  [mappull] <the same error as above>
[topic-merge] [DOTX008E][ERROR] File 'http://localhost:8080/exist/apps/ssg/topics/package_information.dita?irdi=0060-414673376---SPC_1_1~Z1-ACH404~001&type=package' does not exist or cannot be loaded.
      [fop] <non-relevant messages>
      [fop] [ERROR] Anttask - Error rendering fo file: c:\Temp\dita\temp\topic.fo <org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 2:-1)
```

Apparently the FOP error happens because the topic file cannot be loaded.

**Comment by jelovirt** [comment]
The 2.0 code base only supports absolute *file* URIs. We don't support e.g. HTTP or custom URI schemes yet.

**Comment by raducoravu** [comment]
Thread reporting similar problems on the DITA Users List (images located in folder outside of folder where DITA Map is located):

https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/36968

**Comment by nakohdo** [comment]
AFAICS, of the two limitations Radu mentioned above, only the local files issue has been discussed here. What about the other problem, references outside the current map folder? Is that solved in 2.x?

**Comment by raducoravu** [comment]
References outside of the map folder do not yet work with DITA OT 2.x. Oxygen has workarounds when running the DITA OT from inside it but we have customers who generate output from the command line and complain about this limitation.

**Comment by lief-erickson** [comment]
Given my current file architecture, this issue is currently preventing me from moving to OT 2.x.

I know from the OT's perspective the solution is to change my file architecture. I'd rather not have to do that. Given that a solution is available from within oXygen, what's preventing the same solution from being available in a standalone OT or from the command line?

**Comment by raducoravu** [comment]
The way in which I workaround around this in Oxygen does not fit the way in which a similar DITA OT solution should work. A similar DITA OT solution would probably need to perform certain fix-ups in the pre-processing stage. @jelovirt I wonder if the current pre-processing extension points would work for this. Topics referenced in folders outside the DITA Map would need to be copied to some special folder in the temp folder and the @href's, conref's to them corrected accordingly. It would need to be a step very early on...

**Comment by jelovirt** [comment]
Could you describe your case and how `generate.copy.outer=3` doesn't help you here?

**Comment by lief-erickson** [comment]
@jelovirt It's specifically related to coderef, and perhaps that is outside of what is meant in the title as a "DITA resource." I get the following errors:
<property name="generate.copy.outer" value="3" /> produces two errors: 
[DOTJ051E][ERROR] Unable to load target for coderef 
[DOTJ013E][ERROR] Failed to parse the referenced file 

I wrote up a description of the issue on dita-users.
https://groups.yahoo.com/neo/groups/dita-users/conversations/topics/38312

**Comment by jelovirt** [comment]
Can't reproduce with 2.2. However, there seems to be a bug in image processing.

--

**Comment by raducoravu** [comment]
Had another end user report a similar problem with coderef to a remote placed HTML file:

https://www.oxygenxml.com/forum/viewtopic.php?f=1&t=18282&p=50857#p50857
