### ISSUE TITLE
xmfo - single quote interpreted as copyright symbol on Sans fonts

### ISSUE THREAD

**Issue by dan411** [dita-ot/dita-ot#1766]
When generating pdfs from xmfo, if the source material includes 'single quotes', those single quotes appear in the output as copyright symbols (c). 

For instance 'phrase' would appear as (c)phrase(c).

This only happens when the document font-family is set to a Sans font. When a Serif font is used, there is no issue. The screen below shows what happens when single quotes are placed around brackets.

![screenshot115](https://cloud.githubusercontent.com/assets/5614947/4864179/55c826a0-611a-11e4-89e9-2557f8c577fa.png)

**Comment by robander** [comment]
Closing this - there was no response to Jarno's questions from October 2014, and I'm guessing if this was a problem in the core DITA-OT code, it would have come up regularly in other issues.
