### ISSUE TITLE
Upgrade Ant to latest 1.9 version in OT 1.8.6

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1767]
Is it possible to upgrade the version of Ant in the 1.8.6 OT? 1.8.5 ships with Ant 1.8.4 but 1.9.4 is the current version.

Starting with 1.9.1 there is a new option on the Zip target, zip64Mode, on which the EPUB transform depends in order to produce EPUBs that pass epubcheck. As far as I can tell there is no way to produce correct EPUB zips using Ant before 1.9.1.

I'm assuming that the OT-specific Ant code in 2.0 is based on the latest Ant source, so the required Zip support should be there.

**Comment by jelovirt** [comment]
Closing as obsolete.
