### ISSUE TITLE
1.3: Support new step-troubleshooting element

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1770]
Proposal 13086

**Comment by robander** [comment]
This element is supported today by fallthrough processing, the same as all other `itemgroup` specializations inside of a task step:
* `<info>`
* `<stepxmp>`
* `<tutorialinfo>`
* `<stepresult>`

None of those get special processing such as generated text, so I think the current fall-through behavior is probably appropriate and in line with the other elements. Does that sound right?

**Comment by drmacro** [comment]
Probably sufficient. For my own purposes within a specialized "tutorial task" I added formatting to distinguish the troubleshooting info in the step but that was not of general utility.

The implication of the markup design is that it would be visually distinguished in some way but I'm not sure there's an appropriate general solution.

**Comment by robander** [comment]
Ok - will mark this closed as sufficient for default task output.
