### ISSUE TITLE
1.3: Support UX-specific features for resourceid, ux-window

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1772]
Proposals 13060, 13061  and 13008

Not sure if anything needs to be done, but there are opportunities to use resourceID to drive result filename generation and there may be things that can be emitted in HTML5 reflecting ux-window details to enable reflecting ux-window details in interactive delivery.

**Comment by robander** [comment]
@drmacro can you think of any specific outcomes that should come from this, using default processing? I'm not thinking of "Something cool that one person might try to do" ... more, is there anything that default processing can make use of in the currently supported output formats. I'm pretty confident there is nothing to do for the `<resourceid>` changes, somewhat less confident for `<ux-window>`.

**Comment by drmacro** [comment]
I can't think of anything. I would expect anything for the UX markup to be specific to the help delivery system. 

The only thing that comes to mind  of a generic nature might be to include the values from the ux-window markup as metadata values in the HTML head but again that would need to then be used by a given help system so probably better to just let the help system do what it needs via normal extension. If some implementation consensus appears it can always be pushed into the base code.

**Comment by robander** [comment]
I was thinking the same - these elements are really there to allow other applications to use the DITA content more effectively, meaning that any useful processing is specific to those other applications.

Marking this one closed.
