### ISSUE TITLE
1.3: Support release management domain

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1773]
Proposal 13102

There is no required output defined in the spec but some obvious implementation options include:

- Generating list-of-changes topics at the appropriate level (e.g., for the whole publication, per chapter, etc.)

- Generate a spreadsheet reflecting all the changes

Ideal implementation would include ability to filter changes by associated release, date completed, etc.

**Comment by robander** [comment]
I think this is covered by a couple of recent issues / pull requests: 
* Pull request [Add pdf2 release management domain element processing #2248](https://github.com/dita-ot/dita-ot/pull/2248)
* Issue [Implement release management domain processing for org.dita.html5 #2286](https://github.com/dita-ot/dita-ot/issues/2286)

@drmacro OK if I close this as a duplicate and keep the others open to track it?

**Comment by drmacro** [comment]
Yes, that's fine.
