### ISSUE TITLE
1.3: Support Learning Domains

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1775]
I have implemented the learning 1 and learning2 domains for HTML and FO output, producing reasonable static renderings of interactions.

I need to do a bit more testing and then will contribute this code.

**Comment by robander** [comment]
Marking this as closed.

We don't currently ship any special formatting support for the learning and training modules from OASIS. I think there's a decent argument to be made for shipping some support, but if so, they should be added as a pull request (I don't think this extra 4-year-old issue adds anything).
