### ISSUE TITLE
1.3: Support @orient attribute on table

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1777]
Proposal 13078

**Comment by juliovaz** [comment]
Is there a target date for implementation?

**Comment by robander** [comment]
This is not actively being worked on, so there is not a target date for implementation. I took a (very brief) look at it a few weeks ago when evaluating the backlog but did not have time to do anything for 2.3.

**Comment by juliovaz** [comment]
Thanks for the update. Pulling together a presentation and want to make sure I speak the truth.

**Comment by juliovaz** [comment]
Not sure why this is closed. The attribute doesn't do anything in PDF or HTML (not that you should need it for HTML).

**Comment by jelovirt** [comment]
Do you mean the support in PDF is broken and it doesn't work?

**Comment by juliovaz** [comment]
I tried on 2.2.4 and don't get land value to do anything

**Comment by jelovirt** [comment]
Please look at this issue at Github site. The issue metadata on the right sidebar says "Milestone 2.3". That means this feature will be released in DITA-OT version 2.3 and is not available in earlier versions.

**Comment by juliovaz** [comment]
Ah. I see. Thanks.
