### ISSUE TITLE
1.3: Support rotate on entry element

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1778]
Proposal 13078

**Comment by kirkilj** [comment]
It's hard to believe that this has been an issue for 4 years and no one has upvoted it. Allow me to be the first. We're committed to FOP for the time being at least. We're looking at creating a plugin for this and have seen a couple of XSL-FO snippets that appear to do this...

•	[snippet 1](http://apache-fop.1065347.n5.nabble.com/rotating-text-in-table-cell-td4932.html )
•	[snippet 2](https://www.oxygenxml.com/archives/xsl-list/201306/msg00050.html )

Are either of these on the mark?
