### ISSUE TITLE
1.3: Support draft-comment in more places

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1780]
Proposal 13027

Draft comment can now occur in locations where a simple direct rendering of the draft comment would probably be inappropriate (e.g., within titles).

Need to refine rendering of draft comments in HTML and FO output so the presentation is as appropriate as possible.

**Comment by robander** [comment]
There is no guarantee that all places where `<draft-comment>` was legal in 1.2 work well, but here is the list of elements that allow `<draft-comment>` in 1.2 (base topic, technical content composite topic) and 1.3 (base topic, technical content composite topic):

- 1.2 base topic: `<shortdesc>`, `<p>`, `<note>`, `<lq>`, `<sli>`, `<li>`, `<itemgroup>`, `<dd>`, `<pre>`, `<lines>`, `<ph>`, `<stentry>`, `<entry>`, `<abstract>`, `<body>`, `<bodydiv>`, `<section>`, `<sectiondiv>`, `<example>`
- 1.2 composite topic: `<shortdesc>`, `<p>`, `<note>`, `<lq>`, `<sli>`, `<li>`, `<itemgroup>`, `<dd>`, `<pre>`, `<lines>`, `<ph>`, `<stentry>`, `<entry>`, `<abstract>`, `<body>`, `<bodydiv>`, `<section>`, `<sectiondiv>`, `<example>`, `<conbody>`, `<prereq>`, `<context>`, `<steps-informal>`, `<stepsection>`, `<cmd>`, `<info>`, `<tutorialinfo>`, `<stepxmp>`, `<choice>`, `<choptionhd>`, `<chdeschd>`, `<choption>`, `<chdesc>`, `<stepresult>`, `<result>`, `<postreq>`, `<refsyn>`, `<proptypehd>`, `<propvaluehd>`, `<propdeschd>`, `<proptype>`, `<propvalue>`, `<glossdef>`, `<glossUsage>`, `<glossScopeNote>`, `<screen>`, `<codeblock>`, `<pd>`
- 1.3 base topic (new 1.3 locations in italic): `<abstract>`, *`<alt>`, `<b>`*, `<body>`, `<bodydiv>`, *`<cite>`, `<data>`*, `<dd>`, *`<ddhd>`, `<desc>`, `<div>`, `<dt>`, `<dthd>`,* `<entry>`, `<example>`, *`<figgroup>`, `<fn>`, `<i>`*, `<itemgroup>`, *`<keyword>`*, `<li>`, *`<line-through>`*, `<lines>`, *`<linkinfo>`*, `<lq>`, *`<navtitle>`*, `<note>`, *`<overline>`*, `<p>`, `<ph>`, *`<pre>`, `<q>`*, `<section>`, `<sectiondiv>`, `<shortdesc>`, `<sli>`, `<stentry>`, *`<sub>`, `<sup>`, `<term>`, `<title>`, `<tt>`, `<u>`, `<xref>`*
- 1.3 composite topic: Everything in base topic, plus: `<change-request-id>`, `<change-request-system>`, `<change-revisionid>`, `<change-summary>`, `<codeblock>`, `<codeph>`, `<equation-block>`, `<equation-inline>`, `<fragref>`, `<markupname>`, `<numcharref>`, `<parameterentity>`, `<pd>`, `<pt>`, `<screen>`, `<textentity>`, `<xmlatt>`, `<xmlelement>`, `<xmlnsname>`, `<xmlpi>`, `<cause>`, `<chdesc>`, `<chdeschd>`, `<choice>`, `<choption>`, `<choptionhd>`, `<cmd>`, `<conbody>`, `<condition>`, `<context>`, `<glossProperty>`, `<glossScopeNote>`, `<glossUsage>`, `<glossdef>`, `<glossterm>`, `<info>`, `<postreq>`, `<prereq>`, `<propdesc>`, `<propdeschd>`, `<proptype>`, `<proptypehd>`, `<propvalue>`, `<propvaluehd>`, `<refsyn>`, `<responsibleParty>`, `<result>`, `<stepresult>`, `<steps-informal>`, `<stepsection>`, `<steptroubleshooting>`, `<stepxmp>`, `<tasktroubleshooting>`, `<tutorialinfo>`

**Comment by robander** [comment]
Thinking at this point we should close this issue.

I'm guessing of the places `draft-comment` were allowed even going back to 1.0 don't result in great PDF content, because you can try to shove draft blocks into contexts that expect only inline or even expect no rendering a all. None of those have been encountered (or at least reported) at this point, so doesn't seem like the best use of resources to try and make good output in every DITA 1.3 context. Seems like we could handle specific cases as they come up, rather than adding complex markup to handle rendering draft blocks as part of inline/metadata elements.

**Comment by robander** [comment]
Marking this one closed - the markup is fully supported, different transform types will handle it (or not) in different ways. If there is a critical need for better draft output in an inline context that doesn't work now we can address it at that time -- as far as pre-emptive testing of unusual markup, I can think of a lot of other combinations that would be more important than this one.
