### ISSUE TITLE
1.3: Support ph element within index terms

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1782]
Proposal 13092

**Comment by jelovirt** [comment]
Since `keyword` and other elements were already allowed in DITA 1.2, are any changes actually needed to support `ph`? cc @robander

**Comment by robander** [comment]
I think "support" will be transform specific, given that index support varies by format. Pretty sure the main incentive for this was to have styling, such as `<b>` or `<sup>`, carry through to the index (without affecting sort order). Main test target then would be PDF.

**Comment by robander** [comment]
As @keberlein pointed out in Slack - main styling concerns leading to this change are `<sub>` and `<sup>`

**Comment by jelovirt** [comment]
Need to check if current processing retains `keyword` formatting. If it's retained currently, then e.g. `sub` should already go through correctly; if current processing ignores `keyword`, then this is a completely new functional feature.

**Comment by jelovirt** [comment]
Tested `develop` code and e.g. `<sup>` and `<sub>` work in index output. Closing as implemented.
