### ISSUE TITLE
1.3: Handle xref within shortdesc

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1786]
Proposal 13117

I think this mostly means not letting link markup survive in contexts where it would be inappropriate, e.g., in tooltips, in related links, etc.

**Comment by raducoravu** [comment]
This issue seems related to:
https://github.com/dita-ot/dita-ot/issues/1599

**Comment by robander** [comment]
See #2758 for a related issue where this isn't supported (even though that markup uses keys, so was valid before DITA 1.3)
