### ISSUE TITLE
1.3: Support sort-as in contexts outside indexes

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1787]
Proposal 13010

I think this implies:
1. General code for constructing the effective sort phrase 
2. Provide provide extension points to make it easy to implement sorting of things likely to be sorted, e.g., definition lists, sequences of topics, table rows (if it's not too hard).

I don't think it's necessary to rework the code to make everything potentially sortable--that would be nuts.

**Comment by robander** [comment]
Initially this made sense to me but now I'm less sure.

Provided the existence of a sort mechanism, it absolutely makes sense to use this element and/or have something set up to allow for the sort key. For example, if the base toolkit code allowed for sorting of `<dl>` based on a term, it should allow for the existence of `<sort-as>` to override the sort key.

The toolkit does not actually support any sorting outside of indexes. Whether it should is open for debate - I think this falls into the sort of category of a behavior that is fine / good / wonderful in an extension, but might not make sense in the default process. Adding the sort to a default process would also require some mechanism to trigger the sort. Using the `<dl>` example:

- I don't think the presence of `<sort-as>` in one list should result in automatic sorting of all lists (this would probably be very surprising).
- I'd question whether it should even result in automatic sorting of the list that contains it. Using that as a way to trigger sorting implies that if you want your `<dl>` sorted, you must add a `<sort-as>` element to one of the entries, even if in the common case your sort key will be the term itself. That feels wrong.
- If sorting isn't triggered by a `<sort-as>` element, then it means the toolkit must have a general mechanism for sorting - either by element type (command line parameter that lists elements to be sorted?) or by individual element (sort anything that uses `outputclass="sort"`?).

Some mechanism to specify what to sort is clearly a prerequisite for supporting `<sort-as>`. My gut feeling right now is that the prerequisite itself is outside of scope for default processing.

**Comment by robander** [comment]
Looking at some of these old DITA 1.3 items and I think this one should be closed - as I commented 2 years ago I think different elements will have different conditions that make the general sort mechanism difficult, and designing that mechanism is probably not a good idea absent real-world use cases to guide that design.
