### ISSUE TITLE
Manifest parameters not working or complete

### ISSUE THREAD

**Issue by tyrin** [dita-ot/dita-ot#1793]
I have a version of my localized help working using the following manually created manifest:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Demandware Infocenter
Bundle-SymbolicName: com.demandware.doc.help; singleton="true"
Bundle-Version: 1.0.0
Bundle-Vendor: Demandware Incorporated
Bundle-Localization: plugin
```

I'm trying to get the OT to produce this using the command line arguments. I'm supplying the following arguments:

``` xml
    <property name="args.eclipsehelp.language" value="zh" />
    <property name="args.eclipsehelp.country" value="CN" />
    <property name="args.eclipse.provider" value="Demandware" />
    <property name="args.eclipse.version" value="1.0" />
    <property name="args.eclipse.symbolic.name" value="com.demandware.doc${doc_output}; singleton=true" />
```
- Note: the first two properties are still documented incorrectly on source forge as using "eclipse" instead of "eclipsehelp". Assuming there might be a similar bug, I tried the properties with both strings.

What I'm getting is:

```
Bundle-Version: 0.0.0
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Localization: plugin
Bundle-Name: %name
Bundle-Vendor: %providerName
Eclipse-LazyStart: true
Bundle-SymbolicName: com.demandware.dochelp; singleton=true; singleton:=true
```

So it looks like the provider parameter isn't working. Also, there doesn't seem to be a way to specify a Bundle-Name (I'm using the DITA-OT on a Mac, if that makes a difference.)

**Comment by robander** [comment]
Thinking this should be closed for 3.0 -- the eclipse map specialization will likely be moved to an external plugin and no longer bundled with DITA-OT, as it is not actually an OASIS standard document type, instead reflecting just one of IBM's specializations (still in fairly wide use in IBM, but regardless, it should probably not be part of the off-the-shelf DITA-OT download). CC: @easirois for awareness, if you haven't been part of that discussion elsewhere.

**Comment by easirois** [comment]
No, I have not followed the discussion somewhere else. I think the singleton reference in the symbolic name parameter is not helping the issue.  Having the %value in the manifest should inhibit it from being loaded. They are there in case those value are translated. 

We used that code for years internally without an issue. That said, it could be that newer versions of Eclipse are stricter with the manifest file then they were in the 3.x version.  If it's still an issue, I would need more info about the version of eclipse being used to display the content.

**Comment by tavery** [comment]
This issue should not be marked as obsolete. I was not using the eclipsemap specialization, just plain dita and attempting to localize the output. The build arguments worked for the properties files, but not for the manifest - that was the bug. 
If you are considering removing any support for eclipse as an output, I'd wonder what you think will replace it as a full-fledged help system generated from the DITA-OT. The tocjs plugin is a antiquated, since it still uses an iframe, and nothing else is appropriate for help systems, since the other targets don't include search or a TOC.

**Comment by robander** [comment]
My mistake - I did not actually realize that we generated the Manifest when not using the Eclipse Plug-in map. Eric's last comments from 2014 gave me the impression this was related to the specialization.

The Eclipse help format itself is _not_ currently being considered for removal - only the related specialized map, which could then be added back in manually as a plugin.

**Comment by easirois** [comment]
Looking at the original sample, the symboliname parameter should not have the singleton=true value in the Ant paramter, that part is added to the manifest file when the manifest is created.

This:
 <property name="args.eclipse.symbolic.name" value="com.demandware.doc${doc_output}; singleton=true" />

Should be:
 <property name="args.eclipse.symbolic.name" value="com.demandware.doc${doc_output}" />

That said, something is not working with the Eclipsehelp output when you have build parms in 2.3.1.  Looking into that a bit more.
