### ISSUE TITLE
DITA-OT 2.0: preprocessing step adds to many files to resourceonly.list

### ISSUE THREAD

**Issue by maer2712** [dita-ot/dita-ot#1798]
In DITA-OT 2.0, a preprocessing step adds files to resourceonly.list that aren't resource-only. In .job.xml these files have the attribute resource-only="true". These topics simply disappear in the output, without any warnings. The CHM compiler complains about missing files but FOP doesn't. I didn't have this problem in DITA-OT 1.8.

Update: DITA-OT 2.0.M3 and 2.0.M4 have this problem, too. In M1 and M2, I ran into other problems and couldn't continue.

Update: This seems to affect topic files that are not referenced by other topic files. When I add one of the missing topic files to the related-links element of an other topic file, the DITA-OT doesn't treat it any more as resource-only. The DITA-OT seems to assume that "isolated" topic files (only mentioned in a ditamap but not in other topic files) are resource-only.

**Comment by robander** [comment]
It looks like this is the resolved in the latest `develop` code - not sure when it was last tested so it may also be fixed in an earlier release. (I found it while searching for issues that might overlap #2694, it works with that pull request but also works with latest `develop` code).

**Comment by robander** [comment]
Tested in 2.4.6 and this is working there too. So, I'm not sure when this was fixed, but the fix is already available. Marking closed.
