### ISSUE TITLE
abbreviated-form and term keyref links are not resolved when chunk="to-content" [DOT 1.8 and 2.0]]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1816]
Let's say I have a DITA Map like:

        <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/map.dtd">
        <map title="Growing Flowers">
          <topicref href="topics/introduction.dita"/>
          <topicref href="glossary/glossary_overview.dita" chunk="to-content">
            <topicref href="glossary/ot.dita" keys="opentoolkit"/>
          </topicref>
        </map>

with "introduction.dita" having the content:

            <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/topic.dtd">
            <topic id="introduction">
                <title>Introduction</title>
                <body>
                    <p>Look out for <term keyref="opentoolkit"/> and for <abbreviated-form keyref="opentoolkit"/> but not for <xref keyref="opentoolkit"/>.</p>
                </body>
            </topic>

and "glossary_overview.dita" having the content:

      <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
      <topic id="topic_dfl_sn4_3q">
        <title>TEST</title>
        <body>
          <p></p>
        </body>
      </topic>

and "ot.dita" having the content:

      <!DOCTYPE glossentry PUBLIC "-//OASIS//DTD DITA Glossary//EN" "glossary.dtd">
      <glossentry id="wmd">
        <glossterm>Weapons of Mass
            Destruction</glossterm>
        <glossBody>
          <glossSurfaceForm>Weapons of Mass
            Destruction (WMD)</glossSurfaceForm>
          <glossAlt>
            <glossAcronym>WMD</glossAcronym>
          </glossAlt>
        </glossBody>
      </glossentry>

Publishing the DITA Map to XHTML, both the abbreviated-form and term keyrefs are not properly solved. The xref with the same keyref is properly solved.

The console output contains:

        [xslt] C:\Users\radu_coravu\Desktop\DOT2.0 final\DITA-OT2.0\plugins\org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl:1372: Error! I/O error reported by XML parser processing file:/C:/Users/radu_coravu/Desktop/tomjohnson/flowers/temp/xhtml/oxygen_dita_temp/topics/../glossary/ot.dita: C:\Users\radu_coravu\Desktop\tomjohnson\flowers\temp\xhtml\oxygen_dita_temp\topics\..\glossary\ot.dita (The system cannot find the file specified) Cause: java.io.FileNotFoundException: C:\Users\radu_coravu\Desktop\tomjohnson\flowers\temp\xhtml\oxygen_dita_temp\topics\..\glossary\ot.dita (The system cannot find the file specified)
     [xslt] C:\Users\radu_coravu\Desktop\DOT2.0 final\DITA-OT2.0\plugins\org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl:4136: Error! Document has been marked not available: file:/C:/Users/radu_coravu/Desktop/tomjohnson/flowers/temp/xhtml/oxygen_dita_temp/topics/../glossary/ot.dita

**Comment by eerohele** [comment]
[Fixtures](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1816).

Bumped into the same issue.

36f3ce3ec9f952251358a2e76850fc1580a1cea7 fixes the bug, but the FIXME comment in [`TopicRefWriter.java#118`](https://github.com/dita-ot/dita-ot/blob/914a5d3a9648a8d9bc4df58a9a616ef9c0df2c3b/src/main/java/org/dita/dost/writer/TopicRefWriter.java#L118) suggests that the intention has been to refactor this in a larger way.

@jelovirt: Do you want the PR nonetheless or do you want to tackle `TopicRefWriter.java` yourself?
