### ISSUE TITLE
Trying to generate pdf from ditamap using the command line mentioned below gives the following error

### ISSUE THREAD

**Issue by pkk2014** [dita-ot/dita-ot#1822]
Ant Command Line:

ant -logfile "C:\Sample Ditaval Files\build-Untitled24.xml\buildlog-pdf2.txt" -buildfile "%FMHOME%\fminit\ditafm\DITA-OT\build.xml" -Ddita.dir="%FMHOME%\fminit\ditafm\DITA-OT" -Dargs.input="C:\Sample Ditaval Files\Untitled24.xml" -Dbasedir="C:\Sample Ditaval Files" -Doutput.dir="build-Untitled24.xml\pdf2" -Dtranstype="pdf2"  

> Error :
> 
> transform.fo2pdf.fop:
      [fop] [ERROR] Error while rendering page 1
      [fop] java.lang.NullPointerException: Parameter alpha must not be null
      [fop] 	at org.apache.fop.pdf.AlphaRasterImage.<init>(AlphaRasterImage.java:57)
      [fop] 	at org.apache.fop.pdf.AlphaRasterImage.<init>(AlphaRasterImage.java:71)
      [fop] 	at org.apache.fop.render.pdf.ImageRenderedAdapter.setup(ImageRenderedAdapter.java:127)
      [fop] 	at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:816)
      [fop] 	at org.apache.fop.render.pdf.AbstractPDFImageHandler.handleImage(AbstractPDFImageHandler.java:46)
      [fop] 	at org.apache.fop.render.pdf.PDFImageHandlerRenderedImage.handleImage(PDFImageHandlerRenderedImage.java:32)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:228)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:184)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingImageHandler(AbstractIFPainter.java:149)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingURI(AbstractIFPainter.java:271)
      [fop] 	at org.apache.fop.render.pdf.PDFPainter.drawImage(PDFPainter.java:150)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.drawImage(IFRenderer.java:1272)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderImage(IFRenderer.java:1259)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineViewport(AbstractRenderer.java:816)
      [fop] 	at org.apache.fop.render.AbstractPathOrientedRenderer.renderInlineViewport(AbstractPathOrientedRenderer.java:785)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineViewport(IFRenderer.java:866)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:678)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:913)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineParent(AbstractRenderer.java:781)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineParent(IFRenderer.java:930)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:672)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:913)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:643)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:561)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:598)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:980)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:546)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:598)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:980)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:546)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:598)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:980)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:546)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:451)
      [fop] 	at org.apache.fop.render.AbstractPathOrientedRenderer.renderFlow(AbstractPathOrientedRenderer.java:738)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:428)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:352)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:299)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderRegionViewport(IFRenderer.java:748)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:273)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:238)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderPage(IFRenderer.java:597)
      [fop] 	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:123)
      [fop] 	at org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager.finishPage(AbstractPageSequenceLayoutManager.java:312)
      [fop] 	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:191)
      [fop] 	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:115)
      [fop] 	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
      [fop] 	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:128)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:347)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:181)
      [fop] 	at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:391)
      [fop] 	at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:213)
      [fop] 	at net.sf.saxon.event.ReceivingContentHandler.endElement(ReceivingContentHandler.java:443)
      [fop] 	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
      [fop] 	at org.apache.xerces.xinclude.XIncludeHandler.endElement(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
      [fop] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
      [fop] 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
      [fop] 	at net.sf.saxon.event.Sender.send(Sender.java:193)
      [fop] 	at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:30)
      [fop] 	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:300)
      [fop] 	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:130)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:653)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:676)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:534)
      [fop] 	at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:366)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
      [fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
      [fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
      [fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
      [fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
      [fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
      [fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
      [fop] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
      [fop] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
      [fop] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
      [fop] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
      [fop] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
      [fop] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
      [fop] [ERROR] Anttask - Error rendering fo file: C:\Sample Ditaval Files\temp\temp20141211152202082\topic.fo <org.apache.fop.apps.FOPException: Parameter alpha must not be null
      [fop] java.lang.NullPointerException: Parameter alpha must not be null>org.apache.fop.apps.FOPException: Parameter alpha must not be null
      [fop] java.lang.NullPointerException: Parameter alpha must not be null
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:657)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:676)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:534)
      [fop] 	at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:366)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
      [fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
      [fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
      [fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
      [fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
      [fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
      [fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:435)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
      [fop] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
      [fop] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
      [fop] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
      [fop] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
      [fop] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
      [fop] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
      [fop] Caused by: org.apache.fop.apps.FOPException: Parameter alpha must not be null
      [fop] java.lang.NullPointerException: Parameter alpha must not be null
      [fop] 	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:303)
      [fop] 	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:130)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:653)
      [fop] 	... 45 more
      [fop] Caused by: java.lang.NullPointerException: Parameter alpha must not be null
      [fop] 	at org.apache.fop.pdf.AlphaRasterImage.<init>(AlphaRasterImage.java:57)
      [fop] 	at org.apache.fop.pdf.AlphaRasterImage.<init>(AlphaRasterImage.java:71)
      [fop] 	at org.apache.fop.render.pdf.ImageRenderedAdapter.setup(ImageRenderedAdapter.java:127)
      [fop] 	at org.apache.fop.pdf.PDFDocument.addImage(PDFDocument.java:816)
      [fop] 	at org.apache.fop.render.pdf.AbstractPDFImageHandler.handleImage(AbstractPDFImageHandler.java:46)
      [fop] 	at org.apache.fop.render.pdf.PDFImageHandlerRenderedImage.handleImage(PDFImageHandlerRenderedImage.java:32)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:228)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:184)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingImageHandler(AbstractIFPainter.java:149)
      [fop] 	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingURI(AbstractIFPainter.java:271)
      [fop] 	at org.apache.fop.render.pdf.PDFPainter.drawImage(PDFPainter.java:150)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.drawImage(IFRenderer.java:1272)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderImage(IFRenderer.java:1259)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineViewport(AbstractRenderer.java:816)
      [fop] 	at org.apache.fop.render.AbstractPathOrientedRenderer.renderInlineViewport(AbstractPathOrientedRenderer.java:785)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineViewport(IFRenderer.java:866)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:678)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:913)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineParent(AbstractRenderer.java:781)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineParent(IFRenderer.java:930)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:672)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:913)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:643)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:561)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:598)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:980)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:546)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:598)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:980)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:546)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:598)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:980)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:546)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:451)
      [fop] 	at org.apache.fop.render.AbstractPathOrientedRenderer.renderFlow(AbstractPathOrientedRenderer.java:738)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:428)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:352)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:299)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderRegionViewport(IFRenderer.java:748)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:273)
      [fop] 	at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:238)
      [fop] 	at org.apache.fop.render.intermediate.IFRenderer.renderPage(IFRenderer.java:597)
      [fop] 	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:123)
      [fop] 	at org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager.finishPage(AbstractPageSequenceLayoutManager.java:312)
      [fop] 	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:191)
      [fop] 	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:115)
      [fop] 	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
      [fop] 	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:128)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:347)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:181)
      [fop] 	at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:391)
      [fop] 	at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:213)
      [fop] 	at net.sf.saxon.event.ReceivingContentHandler.endElement(ReceivingContentHandler.java:443)
      [fop] 	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
      [fop] 	at org.apache.xerces.xinclude.XIncludeHandler.endElement(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
      [fop] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
      [fop] 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
      [fop] 	at net.sf.saxon.event.Sender.send(Sender.java:193)
      [fop] 	at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:30)
      [fop] 	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:300)
      [fop] 	... 47 more
      [fop] 
      [fop] C:\Sample Ditaval Files\temp\temp20141211152202082\topic.fo -> C:\Sample Ditaval Files\build-Untitled24.xml\pdf2\Untitled24.xml.pdf

**Comment by robander** [comment]
Based on Radu's comment from 2014 - I think this issue is external to DITA-OT, and can be closed in our backlog.
