### ISSUE TITLE
Abbreviated-form in topic title not handled consistently [DOT 1.8 and 2.0]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1828]
Let's say I use an abbreviated-form in a DITA topic title:

```
<title>This is my product:<abbreviated-form keyref="ABBS"/></title>
```

When generating XHTML output the table of contents will not contain the proper expanded title. Also links to the topic (both in XHTML-based and PDF outputs) does not contain the proper expanded title.

I tested with both DITA OT 1.8 and 2.0

**Comment by raducoravu** [comment]
+1

One more of our users reported this problem to us.

**Comment by simonbate** [comment]
I was able to fix the problem with abbreviated-form in titles that are used in links by adding an override to the mappull preprocess phase. If I encounter abbreviated-form in the title, I use the href to resolve the text.

**Comment by raducoravu** [comment]
We also tried to fix this for our WebHelp output which creates its only TOC. Our approach was to import the main XSLT which deals with obtaining XHTML output from a DITA topic and call its processing for every title in the TOC (because a title can have lots of other inline elements in it).

**Comment by raducoravu** [comment]
One of us tested an abbreviated-form in a topic title with DITA OT 2.1.2 and it seems not to be working anymore for the XHTML outputs (either in the HTML topic title header or in the TOC).

**Comment by raducoravu** [comment]
Problem can still be reproduced with DITA OT 3.x, the HTML 5 table of contents does not seem to expand the abbreviated form in the presented topic title.
[toc-abbrevform.zip](https://github.com/dita-ot/dita-ot/files/2675252/toc-abbrevform.zip)
