### ISSUE TITLE
Download link gives 404 error

### ISSUE THREAD

**Issue by amy-kurtzman** [dita-ot/dita-ot#1834]
When I tried to download from http://www.dita-ot.org/download by clicking the green button with the label Mac OS X and Linux, I got a 404 error. The button for Windows also gives a 404 error.

**Comment by jelovirt** [comment]
The website was updated before the binaries for 2.0.1 were uploaded. Until they're up, you can access 2.0 binaries at https://github.com/dita-ot/dita-ot/releases/tag/2.0

**Comment by jelovirt** [comment]
Links fixed
