### ISSUE TITLE
Validation for @cols attribute too drastic [DITA OT 2.0]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1835]
The Java method "ValidationFilter.validateCols" should not try to validate a `@cols` attribute value if it is set on a tgroup from a table element which has a conref.
For example this topic could be output to HTML using an older DITA OT:

        <?xml version='1.0' encoding='UTF-8'?>
        <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/topic.dtd">
        <topic id="introduction">
            <title>Introduction</title>
            <body>
                <p>
                    <table conref="#introduction/table_ndw_gjy_qq" id="table_dkx_hjy_qq">
                        <tgroup cols="cols_rgx_hjy_qq">
                            <tbody>
                                <row>
                                    <entry/>
                                </row>
                            </tbody>
                        </tgroup>
                    </table>
                     <table frame="all" rowsep="1" colsep="1" id="table_ndw_gjy_qq">
                        <title>abc</title>
                        <tgroup cols="2">
                            <colspec colname="c1" colnum="1" colwidth="1.0*"/>
                            <colspec colname="c2" colnum="2" colwidth="1.0*"/>
                            <thead>
                                <row>
                                    <entry/>
                                    <entry/>
                                </row>
                            </thead>
                            <tbody>
                                <row>
                                    <entry/>
                                    <entry/>
                                </row>
                                <row>
                                    <entry/>
                                    <entry/>
                                </row>
                                <row>
                                    <entry/>
                                    <entry/>
                                </row>
                            </tbody>
                        </tgroup>
                    </table></p>
            </body>
        </topic>

**Comment by raducoravu** [comment]
Any updates on this? The problem is that when from Oxygen you insert a conref to a table we will automatically add required XML content to the table element which has the conref attribute and the required content will have some random generated value for the cols attribute, something like cols="cols_rgx_hjy_qq".
So people who used Oxygen to create DITA content and to reuse DITA table will not be able to publish anymore using DITA OT 2.0 because the error seems fatal, it breaks completely the processing.

**Comment by jelovirt** [comment]
My vote is :-1: because for

```xml
<table conref="#introduction/table_ndw_gjy_qq" id="table_dkx_hjy_qq">
  <tgroup cols="cols_rgx_hjy_qq">
    <tbody>
      <row>
        <entry/>
      </row>
    </tbody>
  </tgroup>
</table>
```
The value of `@cols` should clearly be "1".

**Comment by robander** [comment]
I think that the `@cols` value generated by Oxygen is invalid - the specification states that this attribute "Indicates the number of columns in a <tgroup> in a table", and that's true whether or not conref is in use (the same way these elements are required whether or not conref is used). I agree that the sample @jelovirt added should have a `@cols` value of "1".

So I think values like "cols_rgx_hjy_qq" are really an error. Given that these values probably exist in tables today (particularly for Oxygen users), it would be nice if this didn't completely stop processing - or if it only did so when running in a strict mode.

**Comment by jelovirt** [comment]
This is actually what OT2 currently does, processing fails only in strict mode.

**Comment by robander** [comment]
FWIW I have other processing code (outside of DITA-OT) that just failed this morning for a user with similar `@cols` values. Given the definition in the spec, I suspect other tools probably also rely on this value being a number.

**Comment by jelovirt** [comment]
Closing as `won't fix` as both DITA and OASIS Table Exchange Model specs are pretty clear in this, that it must be an integer. Since only strict processing treats this as a fatal error, it's only an inconvenience, not a show stopper.

**Comment by raducoravu** [comment]
There is a situation in which the "ValidationFilter.validateCols" validation MUST not report a problem:

        <table frame="all" rowsep="1" colsep="1" id="table_cny_g1d_tq">
            <title>abcdef</title>
            <tgroup cols="-dita-use-conref-target" conref="#introduction/tgroup_sh4_g1d_tq">
                <tbody>
                    <row>
                        <entry/>
                    </row>
                </tbody>
            </tgroup>
        </table>

In this case the validation should allow the "-dita-use-conref-target" value set on the @cols attribute.

**Comment by raducoravu** [comment]
The processing-mode is LAX by default, right?

**Comment by jelovirt** [comment]
Per the DITA 1.2 spec, `-dita-use-conref-target` is not explicitly allowed in `@cols`. @robander, the spec says:

> The value -dita-use-conref-target is available on enumerated attributes and may also be specified on other attributes.

What's the intent here? Is it implicitly allowed in `@cols`?

**Comment by raducoravu** [comment]
If "-dita-use-conref-target" would not be an allowed value in @cols it would be impossible to state that the tgroup takes the number of columns from the conref target element because it needs to specify a value for @cols in order to be valid according to the schema.
I think this is the main reason that attributes which were intended to have numeric values are still specified in the specification as being NMTOKEN, to allow for this particular attribute value.

**Comment by robander** [comment]
Hmm, interesting questions.

`@cols` was defined with `NMTOKEN` long before we had the token -dita-use-conref-target, so I don't think that was connected.

I do think that the DITA TC thought "oh, this can go anywhere", implicitly allowing it anywhere, but I don't remember any discussion of using it on attributes that explicitly would not allow such a value (such as `@cols` here, or the date fields in metadata). It was explicitly not limited to `#REQUIRED` attributes, because a specialization could make any attribute required. Probably should send a note to the TC to discuss. 

Final comment: while legal, I think it would be very unusual to actually use `@conref` on a `<tgroup>` element...

**Comment by drmacro** [comment]
The only reason I can think of to use conref on tgroup would be where the table content was invariant but the table title was different, but that seems like a vanishingly rare edge case.

**Comment by robander** [comment]
Agreed - very low use case, and I suspect that many editors would not be able to handle it, given that many editors rely on common, DITA-unaware (sometimes very old) code to handle CALS tables. But the question is still an interesting one, and applies to any other attributes that we're validating against the standard (as opposed to validating against the schema).

**Comment by jelovirt** [comment]
@robander @drmacro if you can get back to this question, whether `-dita-use-conref-target` is implicitly allowed on any attribute (even `@id`) and this issues can be used to correct the implementation if needed.

**Comment by robander** [comment]
Sending a note to the TC. The answer cannot be "any attribute" - because some are restricted in the schema enough that this value is not allowed. For example, `@id` on `<topic>` is defined as `ID` type in the grammar files, so that is not legal, and DITA can't explicitly break basic XML parsing rules. So I think the question is whether we implicitly allow this on any attribute (where the token itself is legal according to the schema).

**Comment by robander** [comment]
Sent: https://lists.oasis-open.org/archives/dita/201501/msg00046.html

**Comment by robander** [comment]
Discussed at OASIS TC today - determined that -dita-use-conref-target is implicitly allowed anywhere that it is not forbidden by the grammar files. We could also explicitly disallow it somewhere in the spec, but that is not done for any attribute today, so the result is that it's legal unless forbidden by the DTD/XSD/RNG.
