### ISSUE TITLE
Allow -t as synonym for -temp for dita command

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1836]
I found the inconsistency between the -i, -o, and -temp parameters confusing: my expectation was that -t would be temp.

There doesn't appear to be any other use of -t in either the dita or ant commands, so I would suggest making -t a synonym for -temp

**Comment by eerohele** [comment]
:+1: from me. I keep typing `dita -t mytempdir ...`.

**Comment by jelovirt** [comment]
Easy first pull request :)
