### ISSUE TITLE
New plugin extension to add extra CSS to the base XHTML processing

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1841]
We have an useful extension "dita.xsl.xhtml" which can add XSLT stylesheets to the base XHTML processing.
Ideally we could also have a "dita.xsl.xhtml.css" extension which would add a custom CSS to the XHTML-based outputs. The custom CSS would need to be automatically copied to the output folder + referenced correctly from all HTML output files.

This would allow a plugin which styles all XHTML-based outputs to contribute both XSLT templates and CSSs which match the new constructs it adds.

**Comment by jelovirt** [comment]
WRT implementation, this will require adding generating the stylesheet import in the XSLT as well as copying the CSS files to output.

**Comment by robander** [comment]
Nice idea. We've (not exactly) done this in the past when creating overrides for a specialization; in that case, the CSS is only referenced when the specialization is used for a specific XHTML output chunk, so we used some hacks to try and only copy it out when needed. I'm assuming for a "dita.xsl.xhtml.css" extension, it would be imported to all XHTML output files / always copied to output folder.

**Comment by raducoravu** [comment]
Yes, the CSS could be imported all the time. I got this idea when looking at a learning training plugin Eliot Kimber is developing. The plugin has a CSS which matches certain spans added by the XSLT and styles them a certain way but users right now need to manually specify this CSS contributed by the plugin as a custom CSS in the DITA OT params.

**Comment by jelovirt** [comment]
Is it enough that the CSS URI in plugins.xml is either

* relative to plugin directory (copied to output)
* absolute (CDN URI, not retrieved by OT)

**Comment by raducoravu** [comment]
Right.

**Comment by jelovirt** [comment]
To be implemented in HTML5, but the CSS design for HTML5 has not been completed yet.
