### ISSUE TITLE
Conref'd note element loses styling in OT 1.8.5

### ISSUE THREAD

**Issue by juliovaz** [dita-ot/dita-ot#1842]
A conref to a note loses the styling of the label. All content, including the label is in place but the label does not get styled as bold.

**Comment by eerohele** [comment]
Can't reproduce with DITA-OT 1.8.5 and [this set of files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1842). I'm assuming this is about the `pdf2` transtype.

@juliovaz: Can you tell whether I'm missing something? Otherwise there must be something else at play here.

**Comment by juliovaz** [comment]
I think that it was a combination of a source and an override problem. You
can close this.
