### ISSUE TITLE
Processing of DITA <source> element

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1845]
One of our clients is using the DITA source element to refer to an image which is then used in the PDF output.

The image is referenced like:

```xml
<map>
  <title>THE TITLE</title>
  <topicmeta>
    <source href="images/Snowdrop.jpg"/>
  </topicmeta>
  ......
````

But when the PDF processing builds the map_MERGED.xml file, that file will contain the source element replicated thought the file in all the topicmeta elements for each topicref in the map.

Is this right? What is the purpose of the source element anyway? I looked in the specs but it a practical use case for it seems to be missing.

**Comment by ColinMaudry** [comment]
"The <source> element identifies a resource from which the present topic is derived, either completely or in part."

The semantics are meant to be identical to Dublin Core source term: http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-source

For instance, if the topic or map is the result of a conversion from a resource that has a URL, this URL should go in source/@href.

**Comment by raducoravu** [comment]
I agree with the abusing part :)

**Comment by drmacro** [comment]
Metadata in topicrefs is propogated to the topic referenced and all descendant topics, per the rules for metadata propagation. 

DITA 1.3 provides additional controls metadata cascade, so you can, for example, turn it off for a given instance.

But Colin is correct, their use of <source> is inconsistent with the intended semantic. 

Would need a deeper description of their requirements to know what the most appropriate markup or general solution is.

**Comment by raducoravu** [comment]
Ok, so if the specs says that metadata from the <map> root should be propagated to all descendant topic refs:

http://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/cascading-in-a-ditamap.html#cascading-in-a-ditamap

and it does, then the source element is correctly added to the merged XML.

Indeed using the <source> element to refer to an image which should be used for the PDF cover is not the proper way to do this, probably the <data> element would be better suitable for this.

**Comment by drmacro** [comment]
The D4P pubmap domain provides topicref specializations for identifying publication covers.

One cheap trick would be to use a resource-only topicref with an outputclass of "pubcover" or some such.

The tag name of the element you suggested didn't survive in your latest post (need to surround markup with "~~~~" (for tildes): 

~~~~
<tagged><stuff>
~~~~

**Comment by raducoravu** [comment]
Agreed.
