### ISSUE TITLE
DITAVAL flagging images not copied to output directory

### ISSUE THREAD

**Issue by sorin-ristache** [dita-ot/dita-ot#1846]
The images referenced in a DITAVAL for flagging content in DITA topics should be copied to the output directory of a DITA transformation in the same way that the images referenced with <image> elements in a DITA topic are copied to the output directory. Example of DITAVAL flagging using images:

```
<prop att="product" val="impress" action="flag">
  <startflag imageref="delta_olive.gif">
    <alt-text>Start of product - Impress</alt-text>
  </startflag>
</prop>
```

**Comment by jelovirt** [comment]
What if the `imageref` is an absolute URI, for example "https://cnd.example.com/delta_olive.gif"?

**Comment by jelovirt** [comment]
What if the DITAVAL file is located outside the directory where map and topic files are? For example:

    filters/
      osx.ditaval
    data/
      maps/
        userguide.ditamap
      topics/
        install.dita
Should the output directory be adjusted to capture both DITAVAL and source files, ie, output will contain `filters` and `data` directories, or should flagging images be copies to the same structure as actual data?

**Comment by robander** [comment]
In our early pre-DITA-OT code that works with flagging images, which is of course not normative:
* With an absolute URI, we do not copy it
* We treat the ditaval as if it is in the map directory or common directory. In the case above, "flag.png" would end up in the same (default) directory as the CSS files we copy. If the DITAVAL itself references with something like `subdir/flag.png` we maintain that subdir path.

Again, not normative, and it's broken down a couple times when people try odd things - I think it had trouble with file organization like the peer maps / topics directories in your sample.

**Comment by raducoravu** [comment]
I can no longer reproduce this problem for XHTML and PDF-based outputs with DITA OT 3.1.
