### ISSUE TITLE
Review the "Readme.txt" from the "org.dita.pdf2" plugin

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1860]
https://github.com/dita-ot/dita-ot/tree/develop/src/main/plugins/org.dita.pdf2

It seems to be quite old:

1) It contains a change history which was probably moved to the main DITA OT distribution at some time.
2) It mentions IDIOM
3) It mentions Saxon 6.
4) It mentions folders like "demo" which no longer exist.
5) Something about "index extensions" which can probably be removed

**Comment by jelovirt** [comment]
@infotexture The only reason the README.txt is still there is that it has some documentation. Do you think you could take that and during 2.1 cycle add all useful information and merge to topics in docs repo?

**Comment by infotexture** [comment]
Sure, makes sense.

**Comment by jelovirt** [comment]
Readme files were removed in 05e7b0d
