### ISSUE TITLE
copy-to Not Applied to Topics Referenced by Key In Navigation tree

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1861]
Given this map:

```
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
 <title>Test of @copy-to For Keyreffed Topics</title>
 <topicgroup>
   <keydef keys="topic-01" href="topic01.dita"/>
 </topicgroup>
  <topicref href="root-topic.dita">
    <topichead>
      <topicmeta>
        <navtitle>Use 1 of topic01 (no copy-to)</navtitle>
      </topicmeta>
      <topicref keyref="topic-01"/>
    </topichead>
    <topichead>
      <topicmeta>
        <navtitle>Use 2 of topic01 (copy-to use-02.dita)</navtitle>
      </topicmeta>
      <topicref keyref="topic-01" copy-to="use-02.dita"/>
    </topichead>
    <topichead>
      <topicmeta>
        <navtitle>Use 3 of topic01 (copy-to use-03.dita, keys="use-03")</navtitle>
      </topicmeta>
      <topicref keyref="topic-01" keys="use-03" 
        copy-to="use-03.dita"/>
    </topichead>
  </topicref>
</map>
```

The preprocessing does not generate the copied-to topic "use-03.dita". A key-based xref to key "use-03" thus fails (because the topic does not exist).

I haven't yet looked at the code to see what is causing this behavior but it's definitely a problem.

**Comment by drmacro** [comment]
Here is gist with full test data set:

https://gist.github.com/c5e4bf92110a3695d150.git

**Comment by eerohele** [comment]
This happens because copy-to files are generated in the `debug-filter` stage, at which point keyrefs aren't resolved yet.

I wonder if it would be an option to extract copy-to-related code into a separate pipeline stage that would be executed after the `keyref` stage (and possibly `conref` and `conrefpush` stages)? I haven't examined what the repercussions of that would be, but this can't work with the current preprocessing order, at least.

Insofar as this issue is related to preprocessing order, it might have dependencies to #1482 and #1605 at least.

**Comment by drmacro** [comment]
This particular markup configuration still fails in 2.5.4 and 3.0.4

With 2.5.4 it fails with an NPE in the copy-to phase

With 3.0.4 HTML the copy-to is simply not reflected in the temp files, so the referenced topics aren't there.

With 3.0.4 PDF the temp map appears to be correct but then it fails with an NPE in the topic-reader stage:

topic-reader:
[topic-reader] Using Xerces grammar pool for DTD and schema caching.
[topic-reader] Reading file:/Users/ekimber/workspace-d4p/dita4publishers_ot2.x/sample_data/key-test/temp/1a8b62c55335d398e41db4ca2242f4e2fe2ac09d.ditamap
Error: java.lang.NullPointerException

**Comment by raducoravu** [comment]
👍 Another one of our end users encountered the same problem. Sample DITA Map structure:

      <keydef href="topics/introduction.dita" keys="intro"/>
      <topicref keyref="intro" copy-to="topics/intro2.dita"/> 

Indeed with DITA OT 2.x we have a NPE, with DITA OT 3.x no NPE but the topic is not copied under the new "intro2.dita" name which results in a broken link in the table of contents.
