### ISSUE TITLE
Second level index entries (conkeyreferenced) don't appear in index

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#1864]
This produces a nested index entry:

```xml
<indexterm>first level<indexterm>second level</indexterm></indexterm>
```

Unfortunately it does not work correctly with *conkeyref* attributes:

```xml
<indexterm conkeyref="Index/FirstKey"><indexterm conkeyref="Index/SecondKey"/></indexterm>
```

Only the index entry *Index/FirstKey* appears, but not *Index/SecondKey*. Tested with DITA-OT2.0.

**Comment by jelovirt** [comment]
When "Index/FirstKey" is resolved, the original contents of the `indexterm` will be replaced. This is per spec. You need to use something like:

```xml
<indexterm>
  <keyword  conkeyref="Index/FirstKey"/> 
  <indexterm>
    <keyword conkeyref="Index/SecondKey"/>
  </indexterm>
</indexterm>
```

**Comment by xephon2** [comment]
Thanks
