### ISSUE TITLE
DITA 1.1 DTDs should point to each other using 1.1 specific Public IDs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1865]
Let's say my DITA topic has a DOCTYPE like:

    <!DOCTYPE glossentry PUBLIC "-//OASIS//DTD DITA 1.1 Glossary//EN" "glossary.dtd">

which is usually mapped to this DTD file:

     DITA_OT_DIR\plugins\org.dita.specialization.dita11\dtd\glossary.dtd

which is OK. But if you open that, it refers to all modules like:

    <!ENTITY % topic-type   PUBLIC
    "-//OASIS//ELEMENTS DITA Topic//EN"
     "topic.mod"                                                          >
     %topic-type;

Notice that the public IDs are not 1.1 specific. Because of this, they
will be mapped through the XML catalog support to the default 1.2 public
IDs.
All these inner-reference PUBLIC IDs between the DTDs (including 1.2
DTDs) should have been modified to refer directly using the proper version.

**Comment by jelovirt** [comment]
Do you have interest in sending a pull request for this?

**Comment by raducoravu** [comment]
Not really, it was just something one of our integrators stumbled into.
Also this looks like it needs some time and manual labor to do.

**Comment by jelovirt** [comment]
I think this may be a task that could be done using regexp search and replace. Just add version number to every public ID in `.dtd`, `.mod`, and `.ent` file.

**Comment by raducoravu** [comment]
Fortunately the DTDs for 1.2 like:

    DITA-OT\dtd\technicalContent\dtd\glossentry.dtd

properly refer explicitly to 1.2 public IDs.

So we will not have the same issue when the DITA 1.3 standard is released in the DITA OT and people will want to use explicitly the DITA 1.2 public IDs.

**Comment by robander** [comment]
I realize this may be obsolete, but I'm looking to close out simple old issues where I can and this seemed like a nice cleanup item. I tested it by switching everything in the `samples` directory to use 1.1 specific DTDs, then built `hierarchy.ditamap` and `taskbook.ditamap`, which hits almost every domain and topic type.

**Comment by robander** [comment]
Well, that failed the Travis build, but I haven't checked why yet - will look into it.

**Comment by robander** [comment]
Ah. Our test cases actually contain files that are technically invalid. First one I checked has this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA 1.1 Topic//EN"
 "file:/C:/DITA-OT1.4/dtd/topic.dtd">
 <topic id="critdates_replace" xml:lang="en-us">
     <title>TestCritdates</title>
     <prolog>
         <source href="http://www.ibm.com" format="html" scope="external">somewhere,someplace</source>
     </prolog>
     <body>
         <p>asbsdf</p>
     </body>
     
 </topic>
 ```

The `<source>` element did not have the `@format` attribute in DITA 1.1, so the test case was correct to fail (that attribute was added in DITA 1.2). Need to update this test case and potentially others in order for this to pass.

**Comment by jelovirt** [comment]
@robander is this fixed now?
