### ISSUE TITLE
Proposed metadata changes in plugin.xml for org.dita.xhtml plugin [DOT 2.0.1]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1866]
Both the xhtml and html5 transtypes are defined in the plugin.xml like:
```xml
<transtype name="xhtml html5" extends="base-html" desc="HTML">
  <param name="args.xhtml.contenttarget" desc="Specifies the value of the @target attribute on the &lt;base&gt; element in the TOC file." type="string">
    <val default="true">contentwin</val>
  </param>
  <param name="args.xhtml.toc" desc="Specifies the base name of the TOC file." type="string">
    <val default="true">index</val>
  </param>
  <param name="args.xhtml.toc.class" desc="Specifies the value of the @class attribute on the &lt;body&gt; element in the TOC file." type="string"/>
</transtype>
```
I don't think it would be a good idea for the name of a transtype to be an enumeration of values.
Plus both transtypes share the same descriptors.
This could be re-written like:
```xml
<transtype name="common-xhtml-html5" extends="base-html" abstract="true">
  <param name="args.xhtml.contenttarget" desc="Specifies the value of the @target attribute on the &lt;base&gt; element in the TOC file." type="string">
    <val default="true">contentwin</val>
  </param>
  <param name="args.xhtml.toc" desc="Specifies the base name of the TOC file." type="string">
    <val default="true">index</val>
  </param>
  <param name="args.xhtml.toc.class" desc="Specifies the value of the @class attribute on the &lt;body&gt; element in the TOC file." type="string"/>
</transtype>

<transtype name="xhtml" extends="common-xhtml-html5" desc="XHTML">
</transtype>

<transtype name="html5" extends="common-xhtml-html5" desc="HTML 5">
</transtype>
```

**Comment by jelovirt** [comment]
The current documentation generation generates documentation for abstract trantypes, like http://www.dita-ot.org/2.1/readme/ant-parameters-common-html-transtypes.html (OK, it really doesn't generate them yet, but it will.) If we add common-xhtml-html5, we'd need to make sure we don't redundantly generate page for it. Have to think about this, it may be a better way than the current one.

**Comment by raducoravu** [comment]
I understand, sometimes like in this case it's convenient to create abstract transtypes just to group sets of params together.
Maybe the documentation generation could create complete doc pages (including params inherited from super transtypes) for all non-abstract transtypes. 
So we would no longer have a page for common HTML or common base transtypes. When I'm interested in a certain transformation I could go to the page for it and find all the params there without links to other pages.
Another alternative would be to have special cases which generate docs for certain particular abstract transtypes (like the base transtype and the common HTML transtype).

**Comment by jelovirt** [comment]
The current docs have one reference page for an abstract type, common HTML. So we could keep that one exception. But, for HTML docs I think it would be better to have a single reference page and JavaScript that dynamically filters the page per transtype selection or search. For PDF it would make sense to use the current approach, to reduce page count.
