### ISSUE TITLE
Nested xref text is replaced by three asterisks (***) during topicpull preprocess

### ISSUE THREAD

**Issue by naguila** [dita-ot/dita-ot#1868]
I have a xref which retrieves a topic's shortdesc that also contains an xref. The text I'm getting are three asterisks (***) as specified by the following template rule in the topicpullImpl.xsl file, instead of being pulled from the referenced element:

https://github.com/dita-ot/dita-ot/blob/develop/src/main/xsl/preprocess/topicpullImpl.xsl#L1894

I have overridden that rule with an extension point and replaced the three asterisks (***) by calling the following instruction:

`<xsl:apply-templates select="."/>`

It works for me now but I don't know if this approach is correct.

**Comment by jelovirt** [comment]
In your test, were all files in the same directory. I have a feeling that if your files are in multiple different directories, the base URI resolution will fail.

We may have to pass the base URI as a tunnel parameter to get it right.

**Comment by naguila** [comment]
I did a test with both all the files in the same directory and the inner xref element in a different directory. The xref content pull was successful without need to pass the base URI.

**Comment by eerohele** [comment]
@naguila: Could you maybe create a [Gist](https://gist.github.com) with a set of sample files? I'm having trouble reproducing this one.

**Comment by robander** [comment]
Reading this and thinking it should be tagged as bug rather than feature - but I'm also having trouble reproducing.

Using the garage samples, I updated `changingtheoil.xml` so that the short description included:
```
<ph>maybe <xref href="washingthecar.xml#washcar"
/>, <xref href="takinggarbage.xml#takinggarbage">link text for garbage topic</xref></ph>
```
I also updated `organizing.xml` so that it included an `<xref>` to this topic. Results:
* Generated child links in the parent topic included the correct short description, with proper link text and proper link targets
* Hover help for the short description pulled into the XREF was wrong, but did not include ***. The `<xref>` that had no link text did not show up in the hover text, the `<xref>` with link text added that link text to the hover help.
* Both of these links result in errors from topicpull, though I'm not sure if that was part of the original issue here:
```
[topicpull] Processing C:\Users\IBM_AD~1\AppData\Local\Temp\temp20160504144125887\tasks\organizing.xml
[topicpull] Recoverable error on line 581 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\washingthecar.xml (The system cannot find the file specified)
[topicpull] file:/C:/DITA-OT/dita-ot-2.2.4/reproduce/tasks/changingtheoil.xml:15:3: [DOTX031E][ERROR]: The file washingthecar.xml is not available to resolve link information.
[topicpull] Recoverable error on line 659 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\washingthecar.xml (The system cannot find the file specified)
[topicpull] Recoverable error on line 1113 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\washingthecar.xml (The system cannot find the file specified)
[topicpull] Recoverable error on line 1849 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\washingthecar.xml (The system cannot find the file specified)
[topicpull] Recoverable error on line 581 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\takinggarbage.xml (The system cannot find the file specified)
[topicpull] file:/C:/DITA-OT/dita-ot-2.2.4/reproduce/tasks/changingtheoil.xml:15:50: [DOTX031E][ERROR]: The file takinggarbage.xml is not available to resolve link information.
[topicpull] Recoverable error on line 659 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\takinggarbage.xml (The system cannot find the file specified)
[topicpull] Recoverable error on line 1849 of topicpullImpl.xsl:
[topicpull]   FODC0002: java.io.FileNotFoundException:
[topicpull]   C:\DITA-OT\dita-ot-2.2.4\xsl\preprocess\takinggarbage.xml (The system cannot find the file specified)
```
