### ISSUE TITLE
PDF2 output plugin fails rendering tables

### ISSUE THREAD

**Issue by wschildbach** [dita-ot/dita-ot#1870]
I've been building my DITA sources with pre-2.0 version successfully for a while now. Trying a build on DITA-OT 2.0.1 on a 64 bit Windows 7 system, I get the following problem in a lot of places:

>    [xslt] C:\DITA-OT2.0.1\plugins\org.dita.pdf2\xsl\fo\tables.xsl:507: Fatal Error! An empty sequence  is not allowed as the value of variable $entryNumber
     [xslt] Failed to process C:\DITA-OT2.0.1\temp\temp20150313171311548\stage1a.xml

> BUILD FAILED
C:\DITA-OT2.0.1\build.xml:41: The following error occurred while executing this line:
C:\DITA-OT2.0.1\plugins\org.dita.pdf2\build.xml:155: The following error occurred while executing this line:
C:\DITA-OT2.0.1\plugins\org.dita.pdf2\build.xml:335: Fatal error during transformation using C:\DITA-OT2.0.1\plugins\org.dita.pdf2\xsl\fo\topic2fo_shell_fop.xsl: An empty sequence is not allowed as the value of variable $entryNumber; SystemID: file:/C:/DITA-OT2.0.1/plugins/org.dita.pdf2/xsl/fo/tables.xsl; Line#: 507; Column#: -1

The offending code seems to be in org.dita.pdf2/xsl/fo/tables.xsl:

```xml
<xsl:template name="countEntryNumber">
  <xsl:choose>
    <xsl:when test="@colname">
      <xsl:variable name="colname" select="@colname"/>
      <xsl:if test="ancestor::*[contains(@class, ' topic/tgroup ')][1]/*[contains(@class, ' topic/colspec ')][@colname = $colname]">
        <xsl:number select="ancestor::*[contains(@class, ' topic/tgroup ')][1]/*[contains(@class, ' topic/colspec ')][@colname = $colname]"/>

```
Where apparently a colname in an entry element is matched up with a colname in the colspec.

My source contains neither a colname attribute in the failing table entry, nor a colspec. Adding an appropriate number of empty colspecs with colname="col[1-9]" solves the problem.

I assume that the pdf2 plugin is not the actual culprit, but some other code fails with appropriately populating colspecs in tables that don't have them.

If this helps at all, the problem seems to appear in files that have more than one table.

**Comment by jelovirt** [comment]
Could you create a Gist with source files to reproduce this issue?

**Comment by wschildbach** [comment]
I'll try and build a small repro case.

**Comment by wschildbach** [comment]
(I did not mention this in the beginning: I am running DITA-OT 2.0.1 on a 64 bit Windows 7 system)

To repro the case, please download the gist at https://gist.github.com/wschildbach/137313f7088554253b24 and unpack that into c:\temp\mygist

Then enter the DITA-OT directory and start the transformation:

SET AC4=c:\temp\mygist
ant -f build.xml -Dargs.input=%AC4%\foo.ditamap -Dtranstype=pdf2 -Doutput.dir=c:\temp\mygist-output -Dretain.topic.fo=yes -Dorg.dita.pdf2.use-out-temp=yes -Dargs.debug=yes -Dargs.tablelink.style=NUMBER -Dargs.figurelink.style=NUMBER -Dargs.logdir=c:\temp\mygist-output

I then get

...
     [xslt] C:\DITA-OT2.0.1\plugins\org.dita.pdf2\xsl\fo\tables.xsl:507: Fatal Error! An empty sequence is not allowed as the value of variable $entryNumber
     [xslt] Failed to process C:\DITA-OT2.0.1\temp\temp20150322132256323\stage1a.xml

BUILD FAILED
C:\DITA-OT2.0.1\build.xml:41: The following error occurred while executing this line:
C:\DITA-OT2.0.1\plugins\org.dita.pdf2\build.xml:155: The following error occurred while executing this line:
C:\DITA-OT2.0.1\plugins\org.dita.pdf2\build.xml:335: Fatal error during transformation using C:\DITA-OT2.0.1\plugins\org.dita.pdf2\xsl\fo\topic2fo_shell_fop.xsl: An empty sequence is not allowed as the value of variable $entryNumber; SystemID: file:/C:/DITA-OT2.0.1/plugins/org.dita.pdf2/xsl/fo/tables.xsl; Line#: 507; C
olumn#: -1

- Wolfgang

**Comment by krishhub** [comment]
I experimented as follows with parallel installation of DITA2.0.1 and DITA1.8.5. 

While creating a custom pdf plugin for DITA2.0.1 I faced exactly same problem. I just replaced 'tables-attr.xsl' and 'tables-attr_fop.xsl' files from <DITA2.0.1 installation>/plugins/myplugin/cfg/fo/attr with the same files of <DITA-1.8.5 installation>\plugins\org.dita.pdf2\cfg\fo\attrs

Similarly, I replaced tables.xsl from <DITA2.0.1 install>\plugins\myplugin\xsl\fo with <DITA-OT1.8.5 install >\plugins\org.dita.pdf2\xsl\fo\tables.xsl

After replacing these three files, Build Successful and output is generated properly however, log file shows the same error
<addr>
[mappull] Error on line 500 of mappullImpl.xsl:
  [mappull]   XTTE0570: A sequence of more than one item is not allowed as the value of variable $target
  [mappull]   (<concept/>, <title/>) </addr>

**Comment by eerohele** [comment]
[Fixtures](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/1870).

The error message is different with the latest code in the `develop` branch, but the issue remains the same: if there are two tables in the same topic, [`NormalizeFilter`](https://github.com/dita-ot/dita-ot/blob/25b1f0541c7e6064ed5b29b4bc26004a7287832c/src/main/java/org/dita/dost/writer/NormalizeFilter.java) adds only one `<colspec>` element to the second table even though it should add three.

The error doesn't occur if there's only one `<table>` element.

**Comment by jelovirt** [comment]
@eerohele Thanks for the test case and issue analysis.
