### ISSUE TITLE
Link to index term repeats itself

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1872]
Topic which defines a simple index term:

    <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/topic.dtd">
    <topic id="topic-1">
        <title>Copyright</title>
        <body>
         <p><indexterm>modifying</indexterm></p>
        </body>
    </topic>

Topic which has an index see to it:

     <!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
     <concept id="topic-id">
      <title></title>
      <prolog>
       <metadata>
        <keywords>
         <indexterm>changing <index-see>modifying</index-see>
         </indexterm>
        </keywords>
       </metadata>
      </prolog>
      <conbody>
       <p>
       </p>
      </conbody>
     </concept>

When generating the PDF, the Index page has the "modifying" term with two page links next to it.

**Comment by raducoravu** [comment]
As a proposed fix in the XSLT:

DITA-OT/plugins/org.dita.pdf2/xsl/fo/index_fop.xsl

there is a for-each which outputs page references:

      <xsl:for-each select="//opentopic-index:refID[not(ancestor::opentopic-index:index.groups)][@value]">

which should not apply on indexes which have ancestors with @no-page set to them:

             <xsl:for-each select="//opentopic-index:refID[not(ancestor::opentopic-index:index.groups)][not(ancestor::*[@no-page='true'])][@value]">

**Comment by jelovirt** [comment]
Only applies to FOP.

**Comment by jelovirt** [comment]
Fixed by pull request #1875
