### ISSUE TITLE
Codephrase used in topic title has very small font [PDF output DOT 1.8 and 2.0]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1874]
If I use codeph inside a topic title like:

     <title>Introdu <codeph>codephrase</codeph> ction</title>

The PDF output renders it with font size 10 but the rest of the title is rendered with size 18 font.

Somehow the template which processes the codephrase:

     DITA-OT/plugins/org.dita.pdf2/xsl/fo/pr-domain.xsl

needs to somehow avoid outputting in the XSL:FO a font size for it, rely on the fixed font size set by the parent.

So probably the attribute set which defines properties for "codeph" would not link at all to the base-font attribute set. Maybe this would be true also for other inlines.

**Comment by eerohele** [comment]
Yeah, inline elements should probably use `font-size: inherit` instead of using the `base-font` attribute set.

**Comment by raducoravu** [comment]
Thanks J
