### ISSUE TITLE
Searchtitle Incorrectly Used for HTML Title

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#1877]
In OT 2.0, if you specify a `<searchtitle>` in a topic, that value is used for the `<title>` element in HTML transformations.

If anything, the `<searchtitle>` should be copied to the generated topic's metadata (in my plugin, I create `<meta name="searchtitle">`), but not used for `<title>` unless there is a specific use case that demands it.

I saw this in OT 1.8 with `<navtitle>` (but never tested `<searchtitle>`).

**Comment by jelovirt** [comment]
[Code in question](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl#L3659), the title is generated  from:

*   `topic/titlealts/searchtitle`
*   `dita/topic[1]/titlealts/searchtitle`
*   `topic/title`
*    `/dita//topic[1]/title`
*    `topic/titlealts/searchtitle` (this is `map/searchtitle`)

I have no idea why search title is used here.

**Comment by jelovirt** [comment]
:+1: for removing searchtitle use as title completely.

**Comment by ru-fu** [comment]
This is not (really) according to specification: https://www.oxygenxml.com/dita/1.3/specs/langRef/base/searchtitle.html

> When a topic is rendered as XHTML, the contents of the <searchtitle> will typically appear in the XHTML's title element, which used in the result summary for many search engines. 

I agree that it makes more sense to have the search title in the metadata for HTML5 output, but Eclipse Infocenter uses whatever is in the title element. So this is a regression for eclipsehelp.
