### ISSUE TITLE
Custom processing instructions for controlling certain settings during PDF generation

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1878]
Sometimes there are regular end users who want to do stuff like this:

> I need to insert a page break between Table 1 and name of the subheading, which is appearing at the end of the page. I want to move name of the heading to next page. 

And right now they need to:

1.  Assign an @outputclass attribute either on the element above or on the element below the page break.
2.  Customize an XSLT template which matches the element and insert a line break using XSL-FO.

Ideally we would have a DITA OT processing instruction for forcing a page break at some point, something like the one Docbook has:

```xml
<?hard-pagebreak?>
```
I think other companies with custom publishing pipelines also have something like this implemented.

**Comment by jelovirt** [comment]
For compatibility, what PIs do IBM, DITAC, and DITA2Go use for this?

**Comment by raducoravu** [comment]
I'm not 100% sure what IBM uses and it they use a PI to break the page, maybe Robert could help us there. Also I cannot find anything abouyt ditac and dita2go
I would suggest supporting some simple forms like:

     <?pagebreak?>

and

       <?page-break?>

with a template like:

     <xsl:template match="processing-instruction('pagebreak')">
       <fo:block break-after="page"/>
     </xsl:template>

**Comment by jelovirt** [comment]
For compatibility, we should also add a PI for hard line break.

**Comment by jelovirt** [comment]
DocBook has both soft and hard line breaks, but I'm not sure about [the implementation for soft break](https://github.com/docbook/xslt20-stylesheets/blob/92e516699d1381b0559c69617cd2e1625392d275/xslt/base/fo/pi.xsl#L55). We could add support hard page break with the same name as DocBook, [`hard-pagebreak`](http://www.sagehill.net/docbookxsl/PageBreaking.html#HardPageBreaks).

**Comment by raducoravu** [comment]
+1 for the hard line break. 
It would also make sense in the HTML-based outputs as well.

Probably we should have the same architecture as Docbook, a separate XSLT stylesheet which handles various PIs.

**Comment by DJBHollis** [comment]
I'm sorry, but the idea of adding forced page break processing instructions into topics is simply anathema, and could lead to all sorts of problems. In some instances of the topic it will be necessary, and in others not.

DocBook is far more monolithic than DITA, and this idea obviously works for them.

The idea should be to consider rules for adding keep-with-next. So, if I've understood Radu's post correctly, add a keep-with-next to the subheading, and it should move to the top of the next page, and 'attach' to the table.

**Comment by raducoravu** [comment]
I agree with you David about using keep-with-next as much as possible. It seems to be already used in the PDF plugin XSLT code to keep most titles in sections, figures, tables together with the content.
I'm not sure what precisely the user wanted, from the quote I initially posted I understood he wanted to insert a break after the end of a table because the title of the next section was there but the content of the section was on another page. But this should not happen by default from what I've tested.

**Comment by DJBHollis** [comment]
I got caught out with a long <shortdesc/> once. Its processing checks for length, and processes a keep-with-next only for shorter  content.

.. probably red herring?

D.

**Comment by Phil-Champ** [comment]
Circumstances may sometimes make using manual page breaks a practical necessity. Let me give you a real-world example.

At Sophos, we found ourselves in a position where we had acquired a company whose documentation had been authored in Word for many years. The documents were full of very large tables, sometimes running to five A4 pages in English. We were also translating into seven languages, including German and French. Both of those languages increase the “character count” of English by a significant factor.

The German and French translators were persistently unhappy about where the page breaks were falling in the long tables. At one point, the localisation manager was interrupting the build, adding page breaks to the topic.fo files, and then regenerating the PDFs. That was clearly unacceptable, so I implemented a version of Radu’s code above. In time, my colleague added XSL customisations to paginate the long tables better in German and French and we eventually rewrote the documents.

Time is not always on the side of the author/translator...

**Comment by DJBHollis** [comment]
Would keeping table rows together have helped?

**Comment by DJBHollis** [comment]
There have been two occasions when I've needed a line break. First, with a company name and address. Second with ridiculously long terms that had to fit in a table cell. On both occasions, I used a simple list, <sl>. The typical styling is an indent, but no bullets or line numbering. This is fine for an address. It worked OK, too, with an <sl> inside a table <entry>. There was an indent, but it wasn't too noticeable. I'm sure it would be possible to capture various instances of <sl>, and adjust or remove the indent accordingly. If all else fails, there is the outputclass attribute to provide an <sl>, with no indent.

Would this be sufficient?

What, actually, is a hard line break? Surely it's a paragraph break? Are there instances where it is not possible to add a <p>, paragraph?

IMHO, Docbook is primarily about monolithic docs, so various types of break makes sense. DITA is about topic based authoring, and not monolithic docs, so makes much less sense.

**Comment by robander** [comment]
We do have support for page breaks and line breaks in our IBM usage, but it's limited. They were primarily added to support translated documents, where the translators did not have the freedom to change markup around when content did not flow the same way as in English. Our support for the page break PI (using the old dita->sgml->PDF mechanism) actually checks for the current language, and is only supported for non-English. Basically - it and line breaks are both strongly discouraged, but support is there because sometimes we could not find a better alternative.

**Comment by raducoravu** [comment]
You can probably close this one.

**Comment by robander** [comment]
Closing, as suggested by original submitter.
