### ISSUE TITLE
[Documentation issue] Certain extension points are not explained anywhere

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1879]
For example all the extension points in the pdf2 plugin:
 
      <extension-point id="org.dita.pdf2.xsl.topicmerge" name="PDF2 topic merge XSLT import"/>
     <extension-point id="depend.org.dita.pdf2.format.pre" name="Formatting pre-target"/>
     <extension-point id="depend.org.dita.pdf2.format" name="Formatting target"/>
     <extension-point id="depend.org.dita.pdf2.format.post" name="Formatting post-target"/>
    <extension-point id="org.dita.pdf2.catalog.relative" name="Configuration XML catalog"/>
     <extension-point id="dita.conductor.pdf2.param" name="PDF XSLT parameters"/>

I cannot find them anywhere in the docs:
http://www.dita-ot.org/2.0/

Actually I cannot find in the docs a list with all extension points anymore.

**Comment by jelovirt** [comment]
This issue should be moved to https://github.com/dita-ot/docs/issues

**Comment by jelovirt** [comment]
@raducoravu could you report this documentation issue at [dita-ot/docs](https://github.com/dita-ot/docs/issues) repo, and close this?

**Comment by raducoravu** [comment]
Done:
https://github.com/dita-ot/docs/issues/20
