### ISSUE TITLE
Error running DITA-OT 2.0.1 with XEP

### ISSUE THREAD

**Issue by gsejourne** [dita-ot/dita-ot#1886]
Faced this when trying to upgrade to DITA-OT 2.0.1:
May be more a doc bug, you'll be judge.

If you follow the install instructions that are available at http://www.dita-ot.org/2.0/readme/installing-minimal-package-on-linux.html you end up stuck for the PDF renderer section:

It says:
Optional: For PDF output, set up the XSL-FO processor:

Processor	Action
RenderX	Add the RenderX installation directory to the local.properties file as the xep.dir property, for example:
xep.dir=/usr/share/java/xep

Unfortunately, this does not seem to be enough to have xep run properly on a DITA-OT 2.0 install.

It's eventually missing the "pdf.formatter=xep" instruction at least, but also fails when run:

[xep] Error: Could not find or load main class com.idiominc.ws.opentopic.fo.xep.Runner
[xep] Java Result: 1

If it requires additional steps, they should be described in the install guide.

I'd be happy to contribute on the doc update... if I get the list of required steps to follow to have xep run properly.

**Comment by gsejourne** [comment]
Found the reason in the end:

- the fo.jar shipped with the client package does not contain the XEP classes.
So, this is what I did:
1/ Downloaded the 2.0.1 sources for data-ot from github
2/ Compiled the various classes
3/ the fo.jar file still did not contain the xep classes.
4/ Found out that In the ./src/main/plugins/org.dita.pdf2/buildPackage.xml, looks like the if="xep-available" condition for building the xep class should be removed altogether...
I don't think it makes sense to force copy the XEP directory in the build environment...

So, in the end, I copied my XEP install dir over to the build library path (compile.path), and compiled the classes again: it worked.

I can suggest 3 possible fixes here:

1/ Clearly document the fact that XEP support is not available from the Client distribution package,
2/ Clearly document the fact that if you want XEP support, you have to compile the java classes yourself, after copying your XEP install dir in the build ${compile.path} lib directory.
3/ Disable the if="xep-available" test in the buildPackage altogether, as I don't see how it would harm to have it in the fo.jar and not use it, and would make things much simpler for people using XEP.

Let me know what you think the best solution would be, and I'll send a merge-request for the changes (be them doc or code).

**Comment by jelovirt** [comment]
@robander I think you build the 2.0.1 distribution packages. Does your build clone contain XEP?

**Comment by jelovirt** [comment]
@gsejourne the distribution packages should have been build with XEP. You can't disable the `xep-available` test because the classes in fo.jar refer to XEP classes and XEP support cannot be compiled if XEP classes are not available at compile time. I've been thinking about creating mock copies of the XEP classes into PDF2 source directory, as XEP is not available at Maven Central, but haven't gotten round to that.

**Comment by gsejourne** [comment]
@jelovirt well, it seems the client package is built WITHOUT XEP support anyway. 
There's something wrong here in both cases: either the doc should mention you can't use XEP with the default client distribution, and redirect to how to build the dita-ot from source for XEP, which actually does not exist, or ship a pre-bundled fo.jar with XEP classes within the client distribution.

In any case, let me know if I can write something up about that.

**Comment by gsejourne** [comment]
And... at least, we should probably try to see if XEP is already available system-wide, instead of having to install it under the DITA-OT source tree before compiling, that sounds like an uncommon thing to do;

e.g. add a xep.dir parameter in the build.properties file, that points to an existing XEP installation.

**Comment by raducoravu** [comment]
I have the same problem with DITA OT 2.0 and XEP. Is there an official place from where I can download a DITA OT 2.0 "fo.jar" library which has the "com.idiominc.ws.opentopic.fo.xep.Runner" compiled class inside it?

**Comment by gsejourne** [comment]
Unfortunately no, and I wouldn't recommend it (licensing is one... ).
Instead, you have to compile the libs from source, after you made sure the xep.jar is available -- not in your classpath or environment variables -- but in the dita-ot source build environment, e.g. set the xep.dir parameter within your build properties.

**Comment by raducoravu** [comment]
I ended up using an Archiving utility to copy from the fo.jar which came with DITA OT 1.8 the missing package "com.idiominc.ws.opentopic.fo.xep" to the fo.jar which comes with DITA OT 2.0. And this also works.

**Comment by eerohele** [comment]
@jelovirt: I think this one can be closed, right?
