### ISSUE TITLE
[OT-2.0] Can't Use Extension Point dita.xsl.html.cover

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#1893]
Trying to add overrides to this extension point fails because the extension point is specified after templates in map2html-coverImpl_template.xsl.

This code:
```<dita:extension id="dita.xsl.html.cover" behavior="org.dita.dost.platform.ImportXSLAction" xmlns:dita="http://dita-ot.sourceforge.net"/>```
is at the end of map2html-coverImpl_template.xsl, after templates, so on build you get an error that all import statements must occur at the start.

To fix:
* Move the templates from map2html-coverImpl_template.xsl to another XSL file.
* Specify an <xsl:import> to the new XSL file before the extension point.

**Comment by shaneataylor** [comment]
I'll fork & submit a fix later. Trying to get other work done, too. :-)

**Comment by jelovirt** [comment]
Fixed in pull request #1896
