### ISSUE TITLE
DITA OT 2.1.dev chm properties folder in org.dita.pdf2

### ISSUE THREAD

**Issue by leesmith2** [dita-ot/dita-ot#1897]
I wondered if the following folder makes sense in the pdf2 plugin:
https://github.com/dita-ot/dita-ot/tree/develop/src/main/plugins/org.dita.pdf2/cfg/common/properties

The properties make sense, but I would expect them in org.dita.htmlhelp

**Comment by jelovirt** [comment]
I haven't removed these files from PDF2 just in case someone is using them. The same information is already in e.g. [language.properties](https://github.com/dita-ot/dita-ot/blob/develop/src/main/resources/org/dita/dost/util/languages.properties) thus deleting these would not actually remove any information.

Will remove these as obsolete files.
