### ISSUE TITLE
Othermeta and source metadata should not cascade to child topicref

### ISSUE THREAD

**Issue by ghost** [dita-ot/dita-ot#1899]
Here is an example of the present behaviour:
The map:

``` xml
<bookmap>
    <booktitle>
        <mainbooktitle>Simple example</mainbooktitle>
    </booktitle>
    <bookmeta>
       <othermeta name="this_meta" content="should not be inherited"/>
    </bookmeta>
    <chapter href="child.dita"/>
</bookmap>
```

The topic:

``` xml
<topic id="topic-1">
    <title>The child</title>
    <body>
        <p>Should not have any meta.</p>
    </body>
</topic>
```

The result xhtml transformation of the topic:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us" lang="en-us">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="copyright" content="(C) Copyright 2015" />
<meta name="DC.rights.owner" content="(C) Copyright 2015" />
<meta name="DC.Type" content="topic" />
<meta name="DC.Title" content="The child" />
<meta name="this_meta" content="should not be inherited" />
<meta name="DC.Format" content="XHTML" />
<meta name="DC.Identifier" content="topic-1" />
<link rel="stylesheet" type="text/css" href="commonltr.css" />
<title>The child</title>
</head>
<body id="topic-1">

        <h1 class="title topictitle1" id="ariaid-title1">The child</h1>

        <div class="body">
                <p class="p">Should not have any meta.</p>

        </div>

</body>
</html>
```

As you can see, the othermeta has been inherited by the topic. But, as stated in the [dita 1.2 spec](https://dita.fluidtopics.com/book#!book;uri=urn%253Adita%253ADITA1%255C0dita-1.2-specification.ditamap%253Fv%255C2DITA1.2-spec-XHTML;breadcrumb=urn%253Adita%253ADITA1%255C0architectural_specification.dita%253Fv%255C2DITA1.2%255C3-spec%255C3-XHTML-urn%253Adita%253ADITA1%255C0archSpec%255C3-base.dita%253Fv%255C2DITA1.2%255C3-spec%255C3-XHTML-urn%253Adita%253ADITA1%255C0archSpec%255C0ditamarkup.dita%253Fv%255C2DITA1.2%255C3-spec%255C3-XHTML-urn%253Adita%253ADITA1%255C0archSpec%255C0dita%255C3-metadata.dita%253Fv%255C2DITA1.2%255C3-spec%255C3-XHTML-urn%253Adita%253ADITA1%255C0archSpec%255C0reconciling%255C3-topic%255C3-and%255C3-map%255C3-metadata.dita%253Fv%255C2DITA1.2%255C3-spec%255C3-XHTML), othermeta and source metadata (among others) should not cascade to children.

This bug has been introduced has part of the fix for #1086.

The fix may be to revert the incriminated commit (the one that I am unable to find).

**Comment by jelovirt** [comment]
The 1.2 spec is inconsistent. http://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/cascading-in-a-ditamap.html says the `othermeta` cascades inside map, but then http://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/reconciling-topic-and-map-metadata.html says it doesn't.

I've brought this to @robander's attention and we will fix the implementation based on what the correct behaviour should be.

**Comment by robander** [comment]
I've verified that the spec is still inconsistent in the latest DITA 1.3 draft. I think the "reconciling" topic is correct, which would mean we need to change DITA-OT behavior, but when the spec says 2 conflicting things I'll need to raise it to the TC for an official ruling.

**Comment by robander** [comment]
I just sent a note about this to the OASIS Technical Committee - it should come up for discussion with OASIS next week, time permitting.

**Comment by anythinwilldo** [comment]
Thanks for your answers.
Let's wait and see what the TC decides.

**Comment by jelovirt** [comment]
@robander has this been discussed by the TC?

**Comment by ianbd** [comment]
One observation from testing a ditmap; when you reuse files the same metadata is added to the output (HTML, certainly) for each time the file is referenced.
Four uses of the same file, containing no metadata within the file get four copies of the metadata in the bookmap. Whether the information cascades or not, four copies surely is not correct.

**Comment by mikeewins** [comment]
I've just encountered this issue in DOT 1.8.5 and have verified that it is still present in DOT 2.4.

As reported, it cascades in the topic but also the pre-processed map too, where each topicref down the hierarchy inherits all ancestor <othermeta> tags..

Since the <othermeta> is set directly against a specific topicref, inheritance, at most, should be an option. It certainly makes no sense for it to be automatic - it can be added by processors relatively easily, if needed, but it would be impossible to discern distinct metadata and to remove if not needed.

Any news on the status of this issue?

**Comment by lionelmoi** [comment]
The DITA 1.3 spec is very clear on this subject, see:
https://dita.fluidtopics.com/reader/ZpXfjIuWDRHQoBsB_ApPHQ/UayN8_cZ13W~uZcOikT4uw


Element | How does it apply to the topic? | Does it cascade to child topicref elements? | What is the purpose when set on the map element?
-- | -- | -- | --
othermeta | Add to the topic | No | Define metadata for the entire map

Othermeta should not cascade.

**Comment by jelovirt** [comment]
Fixed in https://github.com/dita-ot/dita-ot/pull/3326
