### ISSUE TITLE
Formatting of child indexterms

### ISSUE THREAD

**Issue by pmasal** [dita-ot/dita-ot#1903]
Some of our writers would like to see the DITA-OT intelligently determine: If only one child `<indexterm>` exists for a parent `<indexterm>`, format it differently than "when multiple children exist for a parent." 

For example, if a bookmap includes the following index terms:

``` xml
<indexterm>devices
   <indexterm>details</indexterm></indexterm>
<indexterm>devices
   <indexterm>provisioning</indexterm></indexterm>
 <indexterm>CSV<indexterm>formatting</indexterm></indexterm>
```

PDF2 currently outputs:

```
CSV
    formatting
devices
   details
   provisioning
```

But it would look better like this:

```
CSV, formatting
devices
   details
   provisioning
```

This might be something I can update in PDF2 and xsl-fo/xslt for the various other formats, but I can't immediately determine how it can be done. Any suggestions? Thanks!!

**Comment by jelovirt** [comment]
The two output look identical. My quess is that the latter example should be something like
```
CSV: formatting
devices
   details
   provisioning
```
Would need to check what e.g. Chicago Manual of Style says about index formatting.

**Comment by pmasal** [comment]
Whoops, sorry, you're right, here's what I meant to provide as the "better" formatting:

CSV, formatting
devices
   details
   provisioning

As you remarked, the character separating the <indexterm_parent> from the sole <indexterm_child> could change, based on the decisions of writing/editing groups and style guides. The main requirement is that the sole <indexterm_child> appear inline with the parent term, rather than in an indented block beneath the parent term.

Any ideas about how that could be handled? Many thanks for your response!
Paul M.

**Comment by pmasal** [comment]
Obviously cut/paste has become a major challenge for me, as I meant to indent the "details" and "provisioning" entries in the previous example...

**Comment by pmasal** [comment]
If you check the index for the online version of the Chicago Manual of Style (http://www.chicagomanualofstyle.org/16/indexI.html), you'll find that the "comma style" for the "parent of a single child entry" is used. Here is an example:

India, names in, 16.80
Indonesia, names in, 8.17, 16.81
infinitives
    as adjectives and adverbs, 5.105
    dangling, 5.107

Paul M.
