### ISSUE TITLE
Sort plugin folders before integration

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1905]
The "org.dita.dost.platform.Integrator.execute()" has a set with all plugin directories "org.dita.dost.platform.Integrator.descSet".
Ideally it would be a TreeSet. In this way if I run the integrator on mac, linux, or windows, with no matter what Java VM I obtain the same result. This is useful when you have the DITA OT committed to a SVN or GIT project and you run the integrator and try to commit with the least amount of changes.

Also it's useful if you have two plugins with the same ID and no matter on what platform/Java VM you run the integrator the plugin from the folder which comes lexicographically first will be loaded and used.

**Comment by jelovirt** [comment]
Sounds like a good idea. Instead of going for `TreeSet`, it might be just easier to sort by ID before processing them. Note that other places in code use `Maps` to contain data, so you might not always get the same results even if the processing order was stable.

The integration should actually work the same way e.g. Eclipse does for multiple plugins with the same ID: the one with largest version number wins. If you don't have a version number, it defaults to `0`. If there are multiple plugins with the same version number and that version number is the latest, it should throw an error.

**Comment by raducoravu** [comment]
As long as the processing order of the plugins is predictable I don't care much about the actual order.
I suppose that if two plugins add an XSLT for PDF processing for example and both XSLTs match on the same template it might become important to have a predictable way of deciding which XSLT from which plugin is imported first in the common XSLT.

**Comment by robander** [comment]
I'm guessing that if 2 plugins override the same template in the same output format, the person who encounters it will either not notice, or will have no idea how to fix / how to resolve. But, it's probably still nice to have predictable results for the person who does end up trying to track it down...

**Comment by raducoravu** [comment]
One possible problem which may arise out of this:

Eliot created a set of DITA 1.3 plugins which have a catalog.xml mapping the generic DITA topic public IDs to the DITA 1.3 DTDs.
His plugin is called "org.oasis-open.dita.dita13.doctypes".
But in DITA OT 2.0 there is also a plugin called "org.oasis-open.dita.v1_2" which contributes the default DITA 1.2 generic public ID to DTD mappings.

So depending on the order in which the integrator will process the plugins, the catalog-dita.xml will either refer to the catalog files like this:

     <nextCatalog catalog="plugins/org.oasis-open.dita.dita13.doctypes/catalog.xml"/>
    <nextCatalog catalog="plugins/org.oasis-open.dita.v1_2/catalog.xml"/>

or like this:

    <nextCatalog catalog="plugins/org.oasis-open.dita.v1_2/catalog.xml"/>
     <nextCatalog catalog="plugins/org.oasis-open.dita.dita13.doctypes/catalog.xml"/>

changing the DTDs to which default public IDs like "-//OASIS//DTD DITA Topic//EN" get resolved.

**Comment by drmacro** [comment]
Note that in the 1.x OT, because the built-in DTDs always come first in the catalog, the 1.3 plugin can never override the mapping of the non-versioned public IDs. I did not expect that plugin to be used with the 2.x OT as it will have the 1.3 grammars built in.

**Comment by jelovirt** [comment]
Yes, for 2.2. we will probably ship 1.3 DTDs is the standard has been released by that time.

**Comment by jelovirt** [comment]
Sorting priority was added in ffa63df.
