### ISSUE TITLE
What does topic-fragment step actually do?

### ISSUE THREAD

**Issue by ColinMaudry** [dita-ot/dita-ot#1908]
Hello,

I'm creating a picture that gives an overview of the DITA OT process when running the PDF transtype:
https://www.lucidchart.com/documents/view/ad0f0ec5-795c-4e40-86b4-4e18a44048b6

I have figured out the role of all steps, except *topic-fragment*. In build_preprocess.xml, the comment states it "resolves same topic fragment identifiers". I know what fragment identifiers are, but I have compared the content of the temp folder after *conref* and after *topic-fragment* the input content (DITA OT documentation, especially xrefs) and .job.xml looked identical.

So, what does this step do?

**Comment by jelovirt** [comment]
It's a DITA 1.3 feature that resolves topic identifieds after conref processing.

In the future, questions like these should be sent to DITA-OT Users mailing list.
