### ISSUE TITLE
Refactor troff code to be usable for other text-like transform types

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1910]
We already ship the troff code as a plug-in, which has two steps. First, convert to an intermediate syntax, mostly blocks and phrases. Then, convert to troff. This should be split up to make that intermediate format more usable by other transform types. Currently, I'm intending to refactor the troff code into two plugins; first converts to the div/span syntax, second takes that and creates troff output. Long term goal is to reuse that intermediate format for a plain text transform, but that will not be part of this issue. I'm not sure if the plain text transform will be bundled with a DITA-OT package or not - guessing @jelovirt would suggest it be a separate download? - but given that we already ship troff, I think we should split the two steps into distinct plugins that continue to ship with DITA-OT.

**Comment by robander** [comment]
@jelovirt you referred to the intermediate syntax as AST (abstract syntax tree) - assuming this is split to a new plugin, should that be part of the plugin name? Do you care? And finally - with this as a new plugin, should we actually use a name of "org.dita-ot.whatever" or is that just adding confusion to the "org.dita.whatever" values we have now?

**Comment by jelovirt** [comment]
The problem I see with the intermediate AST XML is that it's different in every output format. For troff, [Markdown](https://github.com/jelovirt/dita-ot-markdown/blob/master/src/main/resources/ast.rnc), or reStructuredText the AST XML is pretty close to each other, but they are still all different. For that reason, I would prefer to start with combining the XSLT code that splits block and inline content. In the [DITA-OT Markdown plugin](https://github.com/jelovirt/dita-ot-markdown/blob/master/src/main/resources/ast2markdown.xsl#L350) the split can be configured basically with two functions that determine whether an element forms block content, and whether is may only contain elements that are block content. This will simplify processing and if it's combined with DITA-OT preprocessing that handles some of the complexity in tables, each transtype could just process plain DITA into transtype specific AST XML and then render it. The block-inline separation is also being [introduced into ODT output](https://github.com/jelovirt/dita-ot/blob/feature/odt/src/main/plugins/org.dita.odt/xsl/xslodt/commons.xsl#L113), thus it could just be part of the common utility templates in `org.dita.base` plugin.

**Comment by robander** [comment]
OK, a couple of thoughts. Ideally, the combined XSLT code could go in base, and the troff code would be refactored to use the updated format. But, I don't think anybody will want to spend the time on troff to do that - so it's probably going to stick with the current one.

That probably means keeping the troff-specific-AST as is. So rather than creating a new plugin, I think I'd rather just split up the Ant targets within the Troff code so that the troff-AST process can be more easily be reused (if anybody wants to) - right now it's tied into the troff second step. This still cleans up the code and gives me what I want - I have a plugin that builds on troff, using that AST format, and I'd rather just call that "step1" without duplicating Ant code. It's also not worth converting that code to use a new AST.

There may be one or two aspects of the troff-AST that should go in the base AST but I'm not sure - guessing we can look at that later if/when that AST goes in the base.

Thoughts?

**Comment by jelovirt** [comment]
Sounds like a good idea. While code reuse is key in actually being able to generate different output types, using a common intermediate representation may actually be harmful. Thus I prefer the idea of having utility templates that enables some processing that then makes transtype specific processing easier. Examples of these are OASIS table normalization or block-inline separation.

**Comment by robander** [comment]
OK. I've already got the Ant code split apart for easier reuse. I'll do a bit more testing before committing. Given the (likely) low use of the troff code, do you see any problem with moving the XSL files a bit? Right now it's a bit silly, we have 
`org.dita.troff/xsl/troff/` [xsl files]

The extra directory is a legacy of some old coding practices - seems like the XSL should just be inside `xsl/`

**Comment by jelovirt** [comment]
:+1: I think it's ok moving the files around since troff customizations are probably quite rare.

**Comment by robander** [comment]
Cool. First commit will be:
* Refactor Ant code so that it's 2 steps (making the AST step reusable)
* Shuffle the XSL files a bit and make _template files out of the main ones for extension
* Update `plugin.xml` to declare the templates and extension points

I'll keep this open to do some additional cleanup to the troff code.

**Comment by geewrites** [comment]
@robander and @jelovirt: A (very) long-term goal of mine is to customize the troff output, so I appreciate your efforts in this obscure code path.

**Comment by robander** [comment]
Marking this closed - the commits from this issue were all part of DITA-OT 2.1. @infotexture it didn't get tagged with a milestone, so it wasn't in the release notes. Should we update the 2.1 notes now, or list in 2.2, or ignore it?
