### ISSUE TITLE
Consolidate packages to one version

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#1914]
We've had more than one DITA-OT distribution for many years now, to try and meet the needs of different audiences. That has been useful for the few who really only want the small packages, but I think the benefit is outweighed by the confusion from people who need the Everything package and end up with standard or minimal. I've tried to keep the package distinction for quite a while, but I think I'm finally convinced it's not worth the effort - we should just have the one package (corresponding to the DITA-OT 2.0 Client distribution). Those who do not need extra libraries can remove them, or build the minimal packages directly from Git.

**Comment by jelovirt** [comment]
:+1:

**Comment by robander** [comment]
Also need to notify @infotexture as I'm sure this will require an important doc update for 2.1.

**Comment by infotexture** [comment]
I'm listening… :smile:

**Comment by jelovirt** [comment]
Preferably we should only have a single `.zip` for all platforms, not `.tag.gz` for *NIX.

**Comment by infotexture** [comment]
Aren't the `tar.gz` packages required to preserve executable permissions?

**Comment by jelovirt** [comment]
IIRC they are, but will have to verify.

**Comment by jelovirt** [comment]
Tested `.zip` and `dita` file rights were 755. The distribution was built on OS X, I don't know if that makes a difference. Need to verify with Windows built packages.

**Comment by jelovirt** [comment]
Ok, seems we've had old information. Downloaded `.zip` package from Github for 2.1-M1 and unzipped that. The `dita` command execution permissions were ok and everything seemed to work. So it seems we can drop `.tar.gz`.

**Comment by robander** [comment]
See the comment from Shane on Slack? "FWIW, zip is not ubiquitous. On the platform where I do continuous integration builds, it's not installed and I'd have to request it be installed by another team." Just wanted to point it out, I spend most of my time on Windows so am not really qualified to speak about the usefulness of an extra `.tar.gz` download.

**Comment by jelovirt** [comment]
Ok, let's keep it then for 2.1 and remove later if we find it unnecessary in the future.

**Comment by robander** [comment]
Sounds good - I think going from 3 variants to 1 on each system is the most important change, anyway.

**Comment by shaneataylor** [comment]
:thumbsup: for reducing complexity
