### ISSUE TITLE
Add "Example:" static text before each <example> element

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1918]
For DITA <note>s, the "Note:" static text is added before each node.
Wouldn't it be proper to also do the this by default for DITA examples?

**Comment by robander** [comment]
It would probably be fine to do that for examples that do not have a title. Our internal style has always been to put them out for tasks (I think you'll get that from DITA-OT if you activate task labels) but not to do it elsewhere - but I'm not sure why, I'm not even sure if that is intentional.

**Comment by raducoravu** [comment]
Yes, I saw that for tasks there are some special cases.
