### ISSUE TITLE
ditaval not coloring anymore in 2.0.1 but colored nicely in 1.x

### ISSUE THREAD

**Issue by quipsy-karg** [dita-ot/dita-ot#1923]
I just migrated from DITA-OT 1.x to 2.0.1 and noticed that the same, unchanged project does not apply colors for PDF anymore provided by ditaval:
```
<val>
	<prop att="audience" val="developer" action="flag" backcolor="blue" />
	<prop att="audience" val="service" action="flag" backcolor="orange" />
	<prop att="audience" val="admin" action="flag" backcolor="yellow"/>
</val>
```
What happens is that the text in fact is still included, but not colored at all, it still has transparent / white background.

As I do not assume that the ditaval syntax has changed significantly, I assume this is a bug.

**Comment by jelovirt** [comment]
Which transtype?

**Comment by quipsy-karg** [comment]
pdf

**Comment by quipsy-karg** [comment]
I can provide a closed-source ("confidential" DITA content) project reproducing the problem if you like, so you can reproduce rather simple. Just send me your e-Mail address and I will provide a download link for it.

**Comment by jelovirt** [comment]
Please create a small test set of dummy information as a Gist to reproduce this issue instead.

**Comment by quipsy-karg** [comment]
Cannot reproduce anymore. I assume it was a side effect of #1294 or at least might have a related cause. I suggest to close #1293 to see if it will happen again after #1294 is fixed.
