### ISSUE TITLE
Warnings processing bookmap with notices and which refers to Subject Scheme Map [DITA OT 2.1.0]]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1931]
I publish a bookmap to PDF using DITA OT 2.0 and the latest Saxon 9 processor. My bookmap has "notices" and "bookabstract" elements and it also refers to a subject scheme map like:
```xml
<topicref href="productSbjSchemeVals.ditamap" format="ditamap" type="subjectScheme"/>
```
For example the bookmap which comes in the Oxygen samples folder `OXYGEN_INSTALL_DIR\samples\dita\MobilePhone\mobilePhone.ditamap` at some point the XSLT task complains:

>[xslt] Processing D:\projects\eXml\samples\dita\it-book\temp\pdf\stage1a.xml to D:\projects\eXml\samples\dita\it-book\temp\pdf\stage2.fo
[xslt] Loading stylesheet D:\projects\eXml\frameworks\dita\DITA OT2.x\plugins\org.dita.pdf2\xsl\fo\topic2fo_shell_fop.xsl
[xslt] No topicTitleNumber mode template for bookabstract
[xslt] No topicTitleNumber mode template for notices

**Comment by raducoravu** [comment]
One problem I see is that the referenced subject scheme map is actually published and appears inside the PDF content. This did not happen with DITA OT 1.8. As a workaround I can set toc="no" to it:

      <topicref href="productSbjSchemeVals.ditamap" format="ditamap" type="subjectScheme" toc="no"/>

**Comment by ronatartifact** [comment]
I have the following DITA
	<frontmatter>
		<mapref href="adtransform_variables.ditamap" format="ditamap" />
		<booklists>
			<toc />
		</booklists>
		<bookabstract keyref="abstract" />
		<notices keyref="notices">
			<topicref keyref="trademarks" />
		</notices>
		<preface keyref="preface"/>
	</frontmatter>

and get the same message when processing with DITA-OT-2.2
transform.topic2fo.main:
     [xslt] Processing c:\RAMDrive\temp\stage1a.xml to c:\RAMDrive\temp\stage2.fo
     [xslt] Loading stylesheet c:\RAMDrive\dita-ot-2.2\plugins\org.dita.pdf2.fop\xsl\fo\topic2fo_shell_fop.xsl
     [xslt] No topicTitleNumber mode template for bookabstract
     [xslt] No topicTitleNumber mode template for notices
The pages still get generated properly.
