### ISSUE TITLE
Version 2.0.1: Fatal Error! xsl:import elements must come first

### ISSUE THREAD

**Issue by gsejourne** [dita-ot/dita-ot#1936]
After installing a XHTML extension plugin to the stock DITA-OT 2.0.1, I got the following error:

/opt/DITA-OT2.0.1/plugins/org.dita.xhtml/xsl/map2html-coverImpl.xsl:82:103: Fatal Error! xsl:import elements must come first

After looking around and bisecting the map2html-coverImpl(_template).xsl, it turns out that
the extension id for " dita.xsl.html.cover" is at the end of the template.
Thus, when installing a plugin that creates an extension to dita.xsl.html.cover, it adds a <xsl:import /> line after the named templates.

**Comment by jelovirt** [comment]
Closed by Bug #1937
