### ISSUE TITLE
How to fix ANT Copy-HTML problem? [1.8.M2]

### ISSUE THREAD

**Issue by ossified** [dita-ot/dita-ot#1940]
Greetings,

I'm a DOT rookie here, still learning the ropes. I'm having an issue getting JavaHelp and EclipseHelp output with DOT 1.8.M2. My builds are failing with this error:

BUILD FAILED

/home/cmsadmin/Dita/DITA-OT1.8.M2.3-20410128/build.xml:44: The following error occurred while executing this line:

/home/cmsadmin/Dita/DITA-OT1.8.M2.3-20410128/plugins/org.dita.base/build_preprocess.xml:400: Includesfile /mnt/vasont_cms/cmsadmin/cmsrender02workdir/sgill/v2281471/temp/${htmlfile} not found.

I set the ANT Property preprocess.copy-html.skip. That error then went away, but it was replaced with: 
BUILD FAILED

/home/cmsadmin/Dita/DITA-OT1.8.M2.3-20410128/build.xml:44: The following error occurred while executing this line:

/home/cmsadmin/Dita/DITA-OT1.8.M2.3-20410128/plugins/org.dita.base/build_preprocess.xml:171: Includesfile /mnt/vasont_cms/cmsadmin/cmsrender02workdir/sgill/v2281471/temp/${fullditamapfile} not found.

Doing a preprocess skip for that brings another, similar error and it appears to be an endless time. I skip one, another one shows up.

Can anyone please provide some assistance with this? Thanks!

**Comment by jelovirt** [comment]
Are you using unmodified version of OT? Something in you customization is skipping processing steps and `htmlfile` property isn't being set. The `fullditamapfile` should also be set, but somehow it's not being declared. Have you checked the log for other error before the build fails?

**Comment by ossified** [comment]
Hey Jelovirt, thanks for commenting. No, we have custom modifications in our version of OT. I have a feeling it's because the job-helper.xsl file has been removed, I don't see it in our /xsl directory, and it is present in the base OT /xsl directory. I doubt there's much you can do without actually seeing what we've got going on. I'm just completely clueless with the OT, got this project dumped on me with no prior experience.

**Comment by ossified** [comment]
I ended up fixing the above issues. The job-helper file just needed to be included, and I needed to modify the build_init file.

However, now I'm having an issue where I can't figure out how to get content to be on the bottom of every eclipsehelp/javahelp topic file. We have this copyright stuff that we need to be in the footer of every topic. Works fine in DOT1.7.2, but not working in DOT1.8.M2.

**Comment by jelovirt** [comment]
@ossified please use DITA-OT Users or DITA Users mailing lists for support. This issue tracker is for DITA-OT bugs and feature requests.
