### ISSUE TITLE
Syntax for @src on fo:external-graphic is not right, fails with AHF

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1944]
In both 1.8.5 and 2.1, the code that is generating fo:external-graphic is using:

````
<fo:external-graphic src="url(file:/l...../*.jpg)"/>
````

This is in the template for topic/note:

````
<xsl:template match="*[contains(@class,' topic/note ')]">
````
and the default template in mode 'placeImage':
````
<xsl:template match="*" mode="placeImage">
````
However, per the FO spec, the syntax of "url()" requires single quotes around the URI value. 

The output should be:

````
<fo:external-graphic src="url('file:/l...../*.jpg')"/>
````

Without the single quotes this fo:external-graphic:
````
src="url(file:/Users/ekimber/workspace/tic/source-data/dita/(j)(2.1)%20FOD/topics/media/doc0424-image4.jpg)"/></fo:inline></fo:block><fo:block
````

Fails with Antenna House but succeeds under FOP.

If I add the missing single quotes then the reference succeeds with both FOP and XEP.

The fix is to add the sinqle quotes.

I suspect that the problem is coming from the use of absolute URLs in this example. Nevertheless, the current code is not correct per the XSL-FO 1.1 spec and Antenna House is correct to not handle it as expected (it appears to treat the entire @src value as a relative URI, prepending the URL of the FO instance to it, creating an unresolvable URL).

**Comment by jelovirt** [comment]
The XSL 1.1 spec says:

> A sequence of characters that is "url(", followed by optional white space, followed by an optional single quote (') or double quote (") character, followed by an IRI reference as defined in [RFC3987], followed by an optional single quote (') or double quote (") character, followed by optional white space, followed by ")".

That is, the single or double quote is optional. We can, however, add the quote characters if it's a workaround for AHF.

**Comment by drmacro** [comment]
Hmm, I missed the optional when I read it in the context of this issue. However, my testing indicates that AHF does expect it and FOP does not mind it.
