### ISSUE TITLE
Chunking with keyrefs result in missing images and random HTML file names

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1946]
Let's say I have a DITA Map which uses chunking on a topicref keyref like:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/map.dtd">
    <map title="Growing Flowers">
      <keydef href="topics/care.dita" keys="T1">
      </keydef>
      <topicref keyref="T1" chunk="to-content">
      </topicref>
    </map>
```

and in the "topics" folder I have a "care.dita" which refers to an image:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/topic.dtd">
    <topic id="care">
        <title>Test</title>
        <body>
            <p><image href="../images/Gardeniaflower.jpg"/></p>
        </body>
    </topic>
```

The XHTML output has two problems:

1) The name of the HTML file which is the chunk is random, something like "Chunk1347483821.html".
2) The reference to the image is broken.

**Comment by raducoravu** [comment]
The issue can be reproduced both with DITA OT 1.8 and 2.0

**Comment by jelovirt** [comment]
1) Is by design. Since there is no `copy-to` attribute, DITA-OT is allowed to generate a new file name for the topic. In this case the original file name could be used since it's not reused anywhere in else, but the current implementation will rewrite all chunked blobs.

**Comment by raducoravu** [comment]
Interesting, so from what I tested the workaround for both cases is to specify the copy-to attribute like:

    <topicref keyref="T1" chunk="to-content" copy-to="topics/care2.dita">

**Comment by raducoravu** [comment]
Maybe the key name could have been used as a seed for the HTML file name.

**Comment by jelovirt** [comment]
The chunking code is SAX based and the code quality is not particularly good. If it was rewritten to use a tree based model or done in two stages, it would be easier to reuse the original file names.

**Comment by drmacro** [comment]
Note that the DITA Community adjust-copy-to plugin offers the option to use the @keys value as the base for generated @copy-to attributes. It would be great to have this functionality built into the preprocessing, as long as the name generation details were extensible and overridable.

There are some potential complexities with using @keys, such as ensuring that the resulting filenames are in fact unique or choosing among multiple @keys values, but the simple approach of using the first @keys token if it's present is easy enough to implement.

**Comment by raducoravu** [comment]
Can no longer reproduce problem with DITA OT 3.x, attaching samples zip to issue.
[chunk-keyrefs.zip](https://github.com/dita-ot/dita-ot/files/2675216/chunk-keyrefs.zip)
