### ISSUE TITLE
Extend `dita` command with an option to run build scripts

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#1948]
As the `dita` command is essentially a wrapper around Ant, add an option that would allow users to run Ant build scripts by passing the script as an argument to the `dita` command (perhaps `-s` or `-script`):

    `dita -s build-script [target]`

This would simplify migration to OT v2.1 for those who use Ant build scripts to define parameters in advance, copy and rename files and generate output for multiple targets with a single command.

Users who previously relied on `ant -f` would benefit from the advantages of the new `dita` command as the preferred method of transforming DITA content without having to install and configure a separate copy of Ant as suggested in dita-ot/docs#24.

**Comment by jelovirt** [comment]
My vote is hard -1.

The `dita` command should not be tainted with features that just facilitate legacy ways of working. If we make `dita` a wrapper for running Ant, we can't change the implementation behind the CLI to e.g. not use Ant anymore or change it to work differently.

If `startcmd.bat` is too essential and people are unable to install Ant, my vote is for reinstating easy install distribution package, not compromise `dita` command.

**Comment by easirois** [comment]
Or at least a way to build the easy install distribution from the build file in github. At least as a possible intermediate until folks who have dependencies on the OT can fully support the DITA command. I will ask some folks at work about it.

**Comment by macksol** [comment]
I am a bit confused by @jelovirt comment (probably my lack of understanding)
Surely the dita command IS already a wrapper for running Ant surely?

e.g.last line says
ant_exec_command="exec \"$JAVACMD\" $ANT_OPTS -classpath \"$LOCALCLASSPATH\" -Dant.home=\"$DITA_HOME\" -Ddita.dir=\"$DITA_HOME\" -Dant.library.dir=\"$ANT_LIB\" $ant_sys_opts org.apache.tools.ant.launch.Launcher $ANT_ARGS -cp \"$CLASSPATH\""

We use a commercial DITA CMS with integrated OT tookit publishing.
It works by created a build file with all the options set (by the user at runtime, by the system at a configuration level) and the build file is then run by running ant -f
This is actually pretty helpful as 
a) for debugging/traceability we have the build file that was exec'd by the system that we can look into
b) we have the ability to run multiple versions of the OT simply by changing paths
Also in the past we also have set-up test scenarios by creating build files that can be re-run.

I know that this could all be re-done (we can create bat/sh files that pass standard args for test scripts and the CMS supplier has hopefully started to change their system) but I just wanted to point out that the ant -f approach was at the heart of various workflows of real usrs.

**Comment by jelovirt** [comment]
@macksol you can still call the default Ant command line and that is the preferred way to embed DITA-OT. Thus, if you had a toolchain use DITA-OT before `dita` command by calling `ant` command, the old approach should still be used.

You can use `--propertyfile <file>` to pass arguments to `dita` command as a Java properties file, that may also fulfil your requirements if you want to use `dita`.

**Comment by macksol** [comment]
Ah ok,

Thanks for the clarifiaction

On 29 June 2015 at 10:21, Jarno Elovirta <notifications@github.com> wrote:

> @macksol <https://github.com/macksol> you can still call the default Ant
> command line and that is the preferred way to embed DITA-OT. Thus, if you
> had a toolchain use DITA-OT before dita command by calling ant command,
> the old approach should still be used.
>
> You can use --propertyfile <file> to pass arguments to dita command as a
> Java properties file, that may also fulfil your requirements if you want to
> use dita.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dita-ot/dita-ot/issues/1948#issuecomment-116560841>.
>



-- 

Colin Mackenzie

Mobile : 07786 621254
Email : colin@mackenziesolutions.co.uk
Web : www.mackenziesolutions.co.uk
Linked In : uk.linkedin.com/in/mrcolinmackenzie

**Comment by robander** [comment]
I understand/accept the reasons for not wanting to tie `dita` directly to Ant (means we can never re-implement with something else). So I can agree with Jarno's -1 about the initial request.

That said - DITA-OT users had a lot of trouble in the early days because they had to set up Ant (and other things). I think experience shows that we'll lose users if we make them do that again, particularly after pushing people to create Ant builds and shipping Ant for so long. Or if we don't lose users directly, many will be unwilling to upgrade. So, I like the current bundle that still includes the `ant` command; even without using `startcmd` this means that somebody can run `bin/ant buildfile.xml` and have builds run as in the past.

**Comment by jelovirt** [comment]
Closing as won't fix.
