### ISSUE TITLE
File dita-ot-2.1.0/bin/ant throws errors when executed in a Ubuntu 15.04 shell

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#1954]
Here's a screenshot. It shows dita-ot-2.1.0/bin/ant failing to execute "ant -version". It also shows this same command succeeding when run as /usr/bin/ant.
![ant](https://cloud.githubusercontent.com/assets/3413005/8387651/9183ed38-1c17-11e5-9a35-cede7fec82d3.png)

**Comment by jelovirt** [comment]
The distribution packages were build on Windows and at some point the line ending characters in shell files were change to Windows line endings.

**Comment by jelovirt** [comment]
@robertnthomas do you have the same issue with `dita` command?

**Comment by robander** [comment]
So when I do a simple pull from `develop` before building packages, it's changing line endings? Anything I can do to prevent that in future builds, without messing up the Windows ones?

**Comment by robertnthomas** [comment]
Understood. \ and ^M are evil.

On Fri, Jun 26, 2015 at 3:32 PM, Jarno Elovirta <notifications@github.com>
wrote:

> The distribution packages were build on Windows and at some point the line
> ending characters in shell files were change to Windows line endings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dita-ot/dita-ot/issues/1954#issuecomment-115893036>.
>



-- 
Bob Thomas
+1 720 201 8260
Skype: bob.thomas.colorado
Instant messaging: Gmail chat (bob.thomas@tagsmiths.com) or Skype
Time zone: Mountain (GMT-7)

**Comment by robertnthomas** [comment]
I'll try it and let you know.

On Fri, Jun 26, 2015 at 3:34 PM, Jarno Elovirta <notifications@github.com>
wrote:

> @robertnthomas <https://github.com/robertnthomas> do you have the same
> issue with dita command?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dita-ot/dita-ot/issues/1954#issuecomment-115893520>.
>



-- 
Bob Thomas
+1 720 201 8260
Skype: bob.thomas.colorado
Instant messaging: Gmail chat (bob.thomas@tagsmiths.com) or Skype
Time zone: Mountain (GMT-7)

**Comment by jelovirt** [comment]
The problem is that we can use Git configuration to control this, but it's per file extension. In this case `ant` and `dita` do not have a file extension.

**Comment by robertnthomas** [comment]
dita-ot-2.1.0/bin/dita -version executes without issues from Ubuntu

On Fri, Jun 26, 2015 at 3:36 PM, Jarno Elovirta <notifications@github.com>
wrote:

> The problem is that we can use Git configuration to control this, but it's
> per file extension. In this case ant and dita do not have a file
> extension.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dita-ot/dita-ot/issues/1954#issuecomment-115895049>.
>



-- 
Bob Thomas
+1 720 201 8260
Skype: bob.thomas.colorado
Instant messaging: Gmail chat (bob.thomas@tagsmiths.com) or Skype
Time zone: Mountain (GMT-7)
