### ISSUE TITLE
Chunk to-content produces invalid doc when nested topic not same type as parent topic

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1956]
Given a topic like:
````
<concept>
 ...
 <topic>
  ...
 </topic>
</concept>
````

And a topicref that chunks the root topic like so:
````
<topicref keyref="ch01"
       copy-to="chunk-01.dita"
       chunk="to-content select-topic by-topic"
    >
````

The resulting topic is not well formed in that the closing tag is `</topic>` not `</concept>`

This result is produced by the ChunkModule Java code.

I get the same result with 1.8.5 and 2.1 official release.

I have not yet determined the code issue.

Will provide a gist with test case docs.

**Comment by robander** [comment]
...[Marking this as Reason 758 that I dislike chunking (both the specification of it and the difficult implementation based on that difficult specification)]...

**Comment by drmacro** [comment]
Can't disagree with that. It took a while to work out whether or not by-topic or by-document was the correct chunking policy for this use case (although the chunking policy used doesn't affect this bug).

**Comment by drmacro** [comment]
Gist is here: https://gist.github.com/drmacro/ad757c820d97e0b809d3

**Comment by drmacro** [comment]
The logic bug must be in org.dita.dost.writer.AbstractChunkTopicParser. Inspecting the code I don't see an obvious error but the bug must almost certainly be in the endElement() method since that's where the end tag gets written.

**Comment by jelovirt** [comment]
The chunking code is by far the most complex and spaghetti-like code in the DITA-OT code base. So just because an end tag somewhere is incorrect, it may not have anything to do with `endElement` method.

**Comment by drmacro** [comment]
This is a blocking issue for RSI so I'm going to put the scope on it and see if I can find the cause.

**Comment by robander** [comment]
Tried all 3 cases in the linked test, and none of them fail. All three produce this warning:
```
    [chunk] file:/C:/DITA-OT/dita-ot-2.3/reproduce/test-case-03/chunk-test-03.di
tamap:11:6: [DOTJ064W][WARN] Chunk attribute uses both "to-content" and "by-topi
c" that conflict with each other. Ignoring "by-topic" token.
```

I don't know if that means this is fixed, or not, but it would seem to be - if the end tags coming out of the chunk were mis-matched, the rendering step would fail.
