### ISSUE TITLE
Need dita action to list IDs of installed plugins

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1960]
The dita -uninstall action requires knowledge of the plugin ID but there is no way to get the plugin IDs of the installed plugins from the dita command--you have to look in the plugin.xml files for each plugin.

Would like an action that lists the plugin IDs and plugin versions

This would also allow for scripts that can check dependencies and current installation status in support of coordinated installation of multiple plugins.

**Comment by jelovirt** [comment]
Argument like -plugins would be suitable for this. In tools like Homebrew this would be -list, in OT it's not the best command word. Similarly -transtypes could list all transtypes.

**Comment by drmacro** [comment]
I would find -plugins and -transtypes intuitive. I guess the danger is if there are more things that would be usefully listed, a -list {type} command would be more general, but for now there is really only plugins and transtypes.

**Comment by blefort-uo** [comment]
+ 1

**Comment by jelovirt** [comment]
@robander this could be fixed as part of #3028.

**Comment by robander** [comment]
Yep - just noticed it while thinking about how easy this might be to implement, and put in the comment so it wouldn't get lost.

**Comment by robander** [comment]
Implemented for 3.2 with #3037
