### ISSUE TITLE
glossary entry file resolution fails from term and abbreviated-form DOTX058W

### ISSUE THREAD

**Issue by tg73** [dita-ot/dita-ot#1966]
Using `<term>` or `<abbreviated-form>`, notably when working with a non-flat directory structure, yields messages like:

```
[xslt] file:/C:/dev/docs/dita/sandbox/1/glossary/test.dita:7:47: [DOTX058W][WARN]: No glossary entry was found associated with key 'gloss-foo' on term element. The build will try to determine the best display text and hover text for terms and abbreviations.
```

The expected display and hover text is missing in the transformed output.

I have a proposed fix, a pull request is on its way.

**Comment by raducoravu** [comment]
+1, we encountered the same problem, the fix also looks good to us.
