### ISSUE TITLE
colspec added by default to tables in OT2.1 causes non optimal presentation

### ISSUE THREAD

**Issue by macksol** [dita-ot/dita-ot#1970]
In preprocessing (NormalizeFilter.java ?) colspecs are added for columns in tables that have no colspec specified by the user.
For users of XEP and AntennaHouse the best results are achieved by letting the FO processor decide on the width of the columns based on the content of those columns.
Where an author does  require a specific column width ratio they will specify colspecs in the usual way.

Now, after preprocessing I cannot tell if the specified colowidths are deliberately added by the user (and set to be all the same width) or added by the preprocessor.
Please  can we have an Ant param that controls if the colwidth is added automatically or not by the pre processor (or at least some additional indication that the colwidths that exist were not specified by the author)

example below

```xml
<table frame="all" id="table_3vm_b3f_lf" outputclass="tablewidthcolumn dochistory">
  <tgroup cols="4">
    <thead>.....
```
becomes

```xml
<table frame="all" id="table_3vm_b3f_lf" outputclass="tablewidthcolumn dochistory" class="- topic/table ">
  <tgroup cols="4" class="- topic/tgroup ">
    <colspec class="- topic/colspec " colnum="1" colname="col1" colwidth="1*"/>
    <colspec class="- topic/colspec " colnum="2" colname="col2" colwidth="1*"/>
    <colspec class="- topic/colspec " colnum="3" colname="col3" colwidth="1*"/>
    <colspec class="- topic/colspec " colnum="4" colname="col4" colwidth="1*"/>
```

**Comment by macksol** [comment]
Appears to be caused by "Add extension attributes to table #1871"

**Comment by jelovirt** [comment]
When in doubt, CALS Table Model Document Type Definition:

> If the number in cols is larger than the number of `<colspec>`s, then additional `<colspec>`s of colwidth "1*" should be inferred.

Thus the normalization process is correct in generating the default with "1*". However, not generating the default would make sense in that it would allow formatter specific auto layout.

**Comment by jelovirt** [comment]
The default `1*` appeared in #1694.

**Comment by macksol** [comment]
Many thanks, this is important to us as the majority of our tables work with auto layout.
My customer is looking to go live with 2.1 in a matter of week and they have a ton of customizations at XSLT level that takes time to integrate.
If a patched of the 2.1 jar could me made available that would be massively helpful

**Comment by jelovirt** [comment]
You can just comment out [line 226 from `NormalizationFilter`](https://github.com/dita-ot/dita-ot/blob/hotfix/2.1.1/src/main/java/org/dita/dost/writer/NormalizeFilter.java#L226) and build DITA-OT yourself, the instructions in the [README](https://github.com/dita-ot/dita-ot/blob/hotfix/2.1.1/README.markdown) should be pretty easy to follow.

**Comment by macksol** [comment]
Thanks that has done the trick, I owe you a beer.
Now that I have learned how to use Github, I will try and find time to contribute form time to time (on the XSLT side not on Java)
