### ISSUE TITLE
Discussion: managing plugins dependencies (id, list and versions)

### ISSUE THREAD

**Issue by blefort-uo** [dita-ot/dita-ot#1971]
I really like the new install feature of the DITA-OT 2.x, and I am wondering if this feature could be pushed deeper. Maybe this is already planned for the future.  
For a single project, managing all the plugins dependencies and versions can become a challenging issue with the number of plugins involved. 
This problem might be fixed using a dependency manager, but those are complex to set-up.
Another way to fix the issue is to have a repo with a copy of the entire installations but it is not always easy to update all the dependencies in this scenario too.

While working with Javascript, I use to work with npm to manage javascript dependencies and I am wondering if some ideas could be implemented in the DITA-OT. npm uses a package.json file to manage dependencies, an xml alternative would be great too.

Below is a theorical example
```xml
<package>
  <name>Project one</name>
  <version>1.3.1</version>
  <otversion>2.0.1</otversion>
  <description>My company project</description>
  <author></author>
  <keywords>
    <keyword>html5</keyword>
 </keywords>
 <dependencies>
   <plugin id="org.dita-community.adjust-copy-to" url="git@github.com:dita-community/org.dita-community.adjust-copy-to.git#develop"/>
 </dependencies>
<license>MIT</license>
</package>
 ```
Check the dependencies repo url: `git@github.com:dita-community/org.dita-community.adjust-copy-to.git#develop`. Usually the '#' specify the branch or the tag. A convention is needed here.

It would be great to have the following features built-in in the OT:

1.   a standardized way to document plugins version 
2.   adding the version information when declaring plugin dependencies
3.   an install option to install a plugin using a repository, in the correct branch or tag, documented  in the a package.xml file, specially since most of the plugins available are in git repos.
4.   a way to list all plugins installed with their versions (ref https://github.com/dita-ot/dita-ot/issues/1960)
5.   a way to update dependencies
6.  a way to remove plugins from the package.

One interesting thing, is that the generated package.xml could exchange between people, so it makes things easier for everyone to get all the same set-up for a project.

I know this is a huge work and I am wondering if it could be useful for the community.

**Comment by jelovirt** [comment]
While this would be fun coding task and a nice feature to have, I don't think DITA-OT should write its own package manager. The world is full of package and dependency managers and writing your own isn't something you should get into lightly. Then the question becomes, which package manager could you use to get the desired functionality.

**Comment by blefort-uo** [comment]
I clearly understand your point.
I have not tried many package manager, just found that the classic ones are often very big for a simple task.

 Can we leave the discussion open to see if someone wants to share a simple solution?

**Comment by blefort-uo** [comment]
For me a simple solution would be to use bower http://bower.io/ because it is simple, generic and unopinionated.

**Comment by jelovirt** [comment]
A big issue with Bower is

> Bower requires Node and npm and Git.

**Comment by blefort-uo** [comment]
As I am doing lots of Web development, for me it is not a big deal, but for someone who don't, I think Bower might not be a good spot. I might have been too fast with my idea, sorry for that.

**Comment by eerohele** [comment]
I haven't actually tested this so I'm not sure whether this makes much sense, but one option might be to publish DITA-OT plugins into a Maven repository as JAR or ZIP files, use [Apache Ivy](https://ant.apache.org/ivy/) to declare and manage those plugins as regular Ivy dependencies, and write a simple Ant buildfile that resolves and retrieves the Ivy dependencies and uses the targets in DITA-OT's `integrator.xml` to install/uninstall the plugins that Ivy retrieves.

**Comment by jelovirt** [comment]
Ivy could probably work since it would be easy to integrate with Ant, but I'm not sure how deploying to Maven repositories would work. The easiest would be to have a dedicated Maven repo for DITA-OT plugins, hosted by party X.

**Comment by drmacro** [comment]
Anybody know  (or know where to look) what is involved in setting up a Maven repo?

**Comment by xephon2** [comment]
Our team is using a dependency management with pure Ant. See  org.doctales.buildcentral on Github. We're going to implement a Git-Clone target soon. So you tell the system what plugin you want to install and it resolves the dependencies and clones their repos and integrates them.

Von meinem CyanogenMod-Telefon gesendet

Am 18.07.2015 19:02 schrieb Eliot Kimber <notifications@github.com>:

Anybody know  (or know where to look) what is involved in setting up a Maven repo?

---

**Comment by eerohele** [comment]
>Anybody know (or know where to look) what is involved in setting up a Maven repo?

There are multiple open-source products for hosting a Maven repository. For example:

- [Artifactory](https://www.jfrog.com/open-source/)
- [Nexus](http://www.sonatype.org/nexus/go/)
- [Archiva](https://archiva.apache.org/index.cgi)

I have no personal experience with any of them, but they all purport to be easy to set up.

**Comment by xephon2** [comment]
Maybe we can discuss that at the [DITA-OT day](https://www.oxygenxml.com/events/2015/dita-ot_day.html)?

**Comment by jelovirt** [comment]
@xephon2 definitely, either in the panel or as a corridor meetup for that interest topic.

**Comment by xephon2** [comment]
@jelovirt recommends Apache Ivy + repository. This is a possible non-standard dependency management solution, but only at publishing time, there is no extension point for `dita -install`: [org.doctales.dependencyResolverExample](https://github.com/doctales/org.doctales.dependencyResolverExample).

**Comment by robander** [comment]
This has been open for quite a while with periodic discussion. As part of our effort to clear out the backlog of items that aren't actually under / leading to development, I wonder if a better discussion spot for dependency management would be the dita-ot-dev list? Or perhaps a new page at the rarely-used developer wiki (https://github.com/dita-ot/dita-ot/wiki)?

**Comment by robander** [comment]
No comment on my post from 3 weeks ago, so I'm going to close this. I think the project wiki would probably be a handy place to store info, if somebody has experience with or suggestions for package managers that work with DITA-OT.
