### ISSUE TITLE
colwidth="*" causes Fatal Error! Cannot convert string "" to a double

### ISSUE THREAD

**Issue by hessu801** [dita-ot/dita-ot#1978]
Following DITA Table:
```xml
<table pgwide="1"> 
	<tgroup cols="3">
		<colspec colnum="1" colname="col1" colwidth="1*" />
		<colspec colnum="2" colname="col02" colwidth="1*" />
		<colspec colnum="3" colname="col2" colwidth="*" />
		<thead> 
			<row> 
				<entry namest="col1" nameend="col02">H1 Span</entry>
				<entry colname="col2">H2</entry> 
			</row>
		</thead> 
		<tbody> 
			<row> 
				<entry colname="col1">E1</entry>
				<entry colname="col02">E2</entry> 
				<entry colname="col2">E3</entry>  
			</row> 
		</tbody> 
	</tgroup> 
</table>
```
causes `Fatal Error! Cannot convert string "" to a double` while generating XHTML output.

Error message says:
>C:\dita-ot-2.1.0\plugins\org.dita.xhtml\build_general.xml:159: Fatal error durin
>g transformation using C:\dita-ot-2.1.0\plugins\org.dita.xhtml\xsl\dita2xhtml.xs
>l: Cannot convert string "" to a double; SystemID: file:/C:/dita-ot-2.1.0/plugin
>s/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl; Line#: 1932; Column#: -1

According to https://www.oasis-open.org/specs/a502.htm the colwidth value `*` is equivalent to value `1*`, which works just fine, so this might be possible to catch in `dita2htmlImpl.xsl`

**Comment by jelovirt** [comment]
Fix in table normalization.
