### ISSUE TITLE
Reltables don't get processed if external conrefs are defined

### ISSUE THREAD

**Issue by vgrif** [dita-ot/dita-ot#1980]
I have a number of ditamaps each in a directory with its respective content. One map contains generic content that we share with other topics via conrefs. In one map, when the conrefs are active, its reltable content is not processed. If the conrefs are commented out, the reltables are processed as expected.

The source topic IDs are in the file ./ADMINISTRATION/g_virtualChassis.dita.
The destination topics are consumed by the file ./REFERENCE/API/c_aboutDDS.dita.

We have DITA-OT 2.0.1. There are no errors thrown. The reltables just quietly fail to appear.

The above scenario works as expected using the built-in DITA-OT 1.8 provided by OxygenXML.

**Comment by robander** [comment]
I'd like to try to reproduce this with 2.2 or 2.3. Assuming this is still an issue, is there any chance the sample files are still available?

**Comment by vgrif** [comment]
Last time I checked, this was still an issue. Give me a couple days to assemble a sample for you to experiment with. Let me know where to place it.

Thanks


> On May 26, 2016, at 14:48, Robert D Anderson <notifications@github.com> wrote:
> 
> I'd like to try to reproduce this with 2.2 or 2.3. Assuming this is still an issue, is there any chance the sample files are still available?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/dita-ot/dita-ot/issues/1980#issuecomment-222004740>

—
Grif Rosser <http://bloodnok.co.uk/>
Tech Pubs


-- 
This message is for the designated and authorized recipient only and may 
contain privileged, proprietary, confidential or otherwise private 
information relating to vArmour Networks, Inc. and is the sole property of 
vArmour Networks, Inc.  Any views or opinions expressed are solely those of 
the author and do not necessarily represent those of vArmour Networks, Inc. 
If you have received this message in error, or if you are not authorized to 
receive it, please notify the sender immediately and delete the original 
message and any attachments from your system immediately. If you are not a 
designated or authorized recipient, any other use or retention of this 
message or its contents is prohibited.

**Comment by robander** [comment]
Thanks - the easiest way is probably to create a zip of the source, and attach it to a comment here.

**Comment by crun** [comment]
Attached is a clean build that illustrates this bug. You can enable the reltables in this example by placing symlinks to the content in the template directory and removing the relative path from the topicrefs in the ditamap. Hope you find a solution.
[Test.zip](https://github.com/dita-ot/dita-ot/files/296163/Test.zip)

**Comment by crun** [comment]
The paths in my original report are not applicable to the provided example. You'll find two topicrefs in the ditamap and a conref in g_threatAPItitle.dita pointing into ../../templates. One or both causes the reltable to quietly fail.
