### ISSUE TITLE
[xep-support] [xep] [XEPJ002E][ERROR] Element 'fo:external-graphic' must be empty.

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#1985]
Bug report from Dave Gibbons sent to XEP list:

http://lists.renderx.com/pipermail/xep-support/2015-July/007935.html

Oxygen 17 and DITA toolkit version 2.1 with XEP 4.24

Helpful comments from Kevin Brown.

D.

**Comment by jelovirt** [comment]
Can't reproduce the issue exactly as described in the original question to XEP support. However, fixed whitespace output by the stylesheets.
