### ISSUE TITLE
Problem with chunking (DITA OT 2.x).

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1991]
I uploaded a zip here:

http://www.oxygenxml.com/forum/files/ug.zip

If the usermanual DITA Map gets published to plain XHTML the "eppo-installation-linux" HTML file should contain inside it the content from the two subtopics but it no longer does that.

The used chunk method is:

      <topicref href="topics/eppo-installation-linux.dita" chunk="select-branch to-content" navtitle="Linux Installation" locktitle="yes">
        <topicref href="concepts/installation-installer-linux.dita" toc="no"/>
        <topicref href="concepts/installation-requirements-linux.dita" toc="no"/>
      </topicref>

**Comment by jelovirt** [comment]
@raducoravu are you able to verify whether this is a regression bug or something that's never worked?

**Comment by jelovirt** [comment]
`select-branch` is redundant since you're targetting the root topic in `eppo-installation-linux.dita`. Have you tried removing it, in case the problem is there?

**Comment by raducoravu** [comment]
Still does not work if I remove "select-branch". It works with DITA OT 1.8. But it seems that it does not work even with the stable DITA OT 2.1 release.

**Comment by jelovirt** [comment]
Ok, so it's a regression bug.

**Comment by raducoravu** [comment]
I tested the changes and I confirm Chris' commit fixes this issue. Thanks Chris :)
