### ISSUE TITLE
Branch filtering does not seem to work with entire DITA Maps [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1992]
I uploaded a sample project here:

http://www.oxygenxml.com/forum/files/branchFiltering.zip

 you should publish to XHTML the test.ditamap which has content like:

     <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 1.3 Map//EN" "map.dtd">
     <map>
      <title>DITA Topic Map</title>
      <topicref href="flowers.ditamap" format="ditamap">
       <ditavalref href="expert.ditaval"/>
      </topicref>
      
      <topicref href="flowers.ditamap" format="ditamap">
       <ditavalref href="novice.ditaval"/>
      </topicref>
     </map>

and in the resulting TOC the flowers content appears twice but it does not seem to be profiled in any way.

**Comment by jelovirt** [comment]
From #1992

> If my main DITA Map has something like this:

>      <topicref href="flowers.ditamap" format="ditamap">
       <ditavalref href="expert.ditaval"/>
       <ditavalref href="novice.ditaval"/>
      </topicref>

> The DITA Open Toolkit publishing reports:

>>       [DOTX068W]: A topicref element that references a map contains child topicref elements. Child topicref elements are ignored.

**Comment by jelovirt** [comment]
Mapref processing needs to be modified to correctly pass `ditavalref` elements in map references.

**Comment by jelovirt** [comment]
@raducoravu could you verify that the current output matches your expectations?

**Comment by raducoravu** [comment]
Great, seems to be properly working, I will try some more complex cases and get back. 
I also get this error reported:

     [branch-filter] file:/C:/Users/radu_coravu/Desktop/branchFiltering/flowers.ditamap:8:66: [DOTJ065E][ERROR] Branch filter generated topic topics/index.dita used more than once. Renaming topics/index.dita to topics/index-1.dita.

As a suggestion either we report it as a warning or even info or we do not report it at all because this might be an usual case when branching.

**Comment by jelovirt** [comment]
@raducoravu You're right about DOTJ065E, it should be either warning or info, not an error. I'm inclined to mark it as warning.

**Comment by raducoravu** [comment]
Maybe report it as a warning as long as the dvrResourcePrefix/dvrResourceSuffix constructs are not explicitly used, see:

https://github.com/dita-ot/dita-ot/issues/1998
