### ISSUE TITLE
Branch filtering with DITA Maps and metadata keys [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1997]
If in the example uploaded for:

 https://github.com/dita-ot/dita-ot/issues/1992

in the flowers.ditamap you add this:

      <keydef keys="product" audience="expert">
        <topicmeta><keywords><keyword>Expert Product</keyword></keywords></topicmeta>
      </keydef>
      
      <keydef keys="product" audience="novice">
        <topicmeta><keywords><keyword>Novice Product</keyword></keywords></topicmeta>
      </keydef>

and in the index.dita you use the title like this:

      <title>Index <ph keyref="product"/></title>

then publish to XHTML there will be an error reported:

     [DOTJ045I] The key "product" is defined more than once in the same map file. The reference href="null" is ignored.

and in the generated content both the TOC and the XHTML topics will have the "expert" value for the title.

**Comment by jelovirt** [comment]
Both flowers.ditamap references are in the same key scope, thus they share the same (implicit root) key scope and expert will take precedence because it's first in document order.

**Comment by raducoravu** [comment]
The "product" key is set on two keydefs but with different @audience attribute values.
So if filtering would be done before gathering the key then the "product" key would have distinct values depending on each branch.
Is there another way in which I could express this?

**Comment by jelovirt** [comment]
Branch filtering is done before key processing, since branch filtering can change key scope names. I think you want

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 1.3 Map//EN" "map.dtd">
<map>
  <title>DITA Topic Map</title>
  <topicref href="flowers.ditamap" format="ditamap" keyscope="expert">
    <ditavalref href="expert.ditaval"/>
  </topicref>
  <topicref href="flowers.ditamap" format="ditamap" keyscope="novice">
    <ditavalref href="novice.ditaval"/>
  </topicref>
</map>
```
This way the two index.dita renditions will be processed in different key scopes and the effective key definitions are different.

**Comment by raducoravu** [comment]
Thanks J.
I updated your latest changes, your proposes workaround work. Indeed probably my first impression was that once you define a branch you also have some kind of anonymous keyscope for it.

**Comment by robander** [comment]
I would expect the `<dvrKeyscopePrefix>` or `<dvrKeyscopeSuffix>` elements to work here too -- you could do:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 1.3 Map//EN" "map.dtd">
<map>
  <title>DITA Topic Map</title>
  <topicref href="flowers.ditamap" format="ditamap">
    <ditavalref href="expert.ditaval">
       <ditavalmeta><dvrKeyscopePrefix>expert</dvrKeyscopePrefix></ditavalmeta>
    </ditavalref>
    <ditavalref href="novice.ditaval">
       <ditavalmeta><dvrKeyscopePrefix>novice</dvrKeyscopePrefix></ditavalmeta>
     </ditavalref>
  </topicref>
</map>
```
There is no existing scope name on the branch, so the "prefix" becomes the scope name. It might look a bit more logical if you added a simple scope value on the topicref as well, but I don't think it's necessary.

**Comment by jelovirt** [comment]
I would *not* expect the prefix/suffix to actually create scopes. This means for consistency `<dvrResourePrefix>expert</dvrResourcePrefix>` should create a resource `expert` from a `<topichead>` inside the branch, and IMO that's really not what users would expect.

**Comment by robander** [comment]
@jelovirt has convinced me -- if you want to create a scope there, use `@keyscope`; if you want different scopes, also add the prefix or suffix metadata. Otherwise, there's no way to tweak the name of nested scopes without also creating one on the parent. [Also chatted a bit with Chris Nitchie, inventor of the key scope, who agrees with that.]

**Comment by robander** [comment]
So @raducoravu I think to do what you originally wanted, you could use the map @jelovirt included, or you could do something like this - adding some value for `@keyscope` on the map reference:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 1.3 Map//EN" "map.dtd">
<map>
  <title>DITA Topic Map</title>
  <topicref href="flowers.ditamap" format="ditamap" keyscope="value">
    <ditavalref href="expert.ditaval">
       <ditavalmeta><dvrKeyscopePrefix>expert</dvrKeyscopePrefix></ditavalmeta>
    </ditavalref>
    <ditavalref href="novice.ditaval">
       <ditavalmeta><dvrKeyscopePrefix>novice</dvrKeyscopePrefix></ditavalmeta>
     </ditavalref>
  </topicref>
</map>
```

**Comment by drmacro** [comment]
I agree: the keyscope must be specified on the topicref that contains the ditavalref, otherwise there is no keyscope, even if a prefix or suffix is specified.

It should go without saying, but if @keyscope is specified and no prefix or suffix is specified, then you end up with two peer keyscopes with the same scope name. In that case, the qualified keys from the first keyscope take precedence over those from the second.

So in general, it would be user error to specify a @keyscope attribute and *not* specify a prefix or suffix for each implicit copy.

**Comment by raducoravu** [comment]
Right, thanks.
