### ISSUE TITLE
dvrResourcePrefix/dvrResourceSuffix not used [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1998]
If my DITA Map has a construct like this:

```
  <topicref href="UserManual.ditamap" format="ditamap" keyscope="A1">
   <ditavalref href="author.ditaval">
    <ditavalmeta>
     <dvrResourcePrefix>mr</dvrResourcePrefix>
     <dvrKeyscopePrefix>ks</dvrKeyscopePrefix>
    </ditavalmeta>
   </ditavalref>
  </topicref>
```

the topics on disk either have the original name or they have the suffix "-1" but the dvrResourcePrefix/dvrResourceSuffix do not seem to be used.

**Comment by raducoravu** [comment]
This seems to work now, should the issue be closed?
One problem I see would be that if we have an original DITA topic like "topics/index.dita" and the DITA Map specifies prefix and/or suffix for resources:

      <dvrResourcePrefix>abc</dvrResourcePrefix>
      <dvrResourceSuffix>zzz</dvrResourceSuffix>

then in the output folder besides the "abcindexzzz.html" HTML file created by applying the suffixes you will still have the "index.html" output although it is not used anywhere in the TOC. So somehow the original topic file name should no longer be processed and generated in the output folder.

**Comment by jelovirt** [comment]
@raducoravu that's a good improvement feature. Right the code doesn't remove the original file from job configuration if all occurrences are renamed.

**Comment by raducoravu** [comment]
I'm closing this bug, for my remark:

        then in the output folder besides the "abcindexzzz.html" HTML file created by applying the suffixes you will still have the "index.html" output although it is not used anywhere in the TOC. So somehow the original topic file name should no longer be processed and generated in the output folder.

I added this separate issue:

https://github.com/dita-ot/dita-ot/issues/2980
