### ISSUE TITLE
Parent/Child links in nested Troubleshooting Topics fail when map is in a different folder than the other topics

### ISSUE THREAD

**Issue by IsabellGombert** [dita-ot/dita-ot#2000]
We are building an online-help system using DITA including troubleshooting topics. These topics are nested inside other topics to create a decision tree in a map.

So the map looks like this: 
```
topic problems
  topic unread emails
  topic decision
    troubleshooting topic 1
    troubleshooting topic 2
```

The map contains a relationship table in which all those to topics are linked. These links work properly when we put the map and the topics in the same folder. But in our foldersystem the maps are located in a different folder: the path to a topic looks like: `.../common/email_tr_unread_emails.xml`. When using this folder hierarchy the links generated from the relationship table don't work because we can't see them. 

Is this a bug or just not yet implemented?

**Comment by jelovirt** [comment]
Which version of DITA-OT? Which transtype?

**Comment by IsabellGombert** [comment]
We use DITA OT 2.0 and transtype XHTML.

**Comment by sebschmied** [comment]
Hi, I'm a colleague of OP's. It turns out we were mistaking an xmetal feature ("Dita 1.3 preview") for a DITA-OT 2.0 feature here. DITA-OT 2.0 doesn't implement troubleshooting yet (neither does 2.1.2), so I guess you can close this. Sorry for the trouble.
