### ISSUE TITLE
Cannot call multiple transformations with Ant and DITA-OT 2.1.1

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2001]
It seems, that it is not possible anymore to call the DITA-OT via Ant multiple times.

**Example**

```xml
<target name="crashTest">
    <ant antfile="${dita.dir}${file.separator}build.xml">
      <property name="args.input" value="${mymap}"/>
      <property name="transtype" value="webhelp"/>
      <property name="output.dir" value="${basedir}/out/foo1"/>
    </ant>
    <ant antfile="${dita.dir}${file.separator}build.xml">
      <property name="args.input" value="${mymap}"/>
      <property name="transtype" value="webhelp"/>
      <property name="output.dir" value="${basedir}/out/foo2"/>
    </ant>
  </target>
```

The build fails with:

```bash
gen-list:
 [gen-list] Using Xerces grammar pool for DTD and schema caching.
 [gen-list] Processing file:/C:/Users/[USER]/DITA/mymap.ditamap

BUILD FAILED
C:\Users\[USER]\DITA\build.xml:662: The following error occurred while executing this line:
C:\Users\[USER]\DITA\build.xml:998: The following error occurred while executing this line:
C:\Users\[USER]\DITA-OT\dita-ot-2.1.1\build.xml:41: The following error occurred while executing this line:
C:\Users\[USER]\DITA-OT\dita-ot-2.1.1\plugins\org.dita.base\build_preprocess.xml:78: Failed to run pipeline: org.dita.dost.util.XMLGrammarPoolImplUtils cannot be cast to com.sun.org.apache.xerces.internal.xni.grammars.XMLGrammarPool
```

This was working with the DITA-OT 1.8.5. Probably the DITA-OT does not tear down as it did before.

This probably also means, that the given example at [Creating an Ant build script](http://www.dita-ot.org/2.1/user-guide/creating-an-ant-build-script.html) does not work anymore, but I did not test that yet.

**Comment by jelovirt** [comment]
Does OT fail on the first or the second call to `<ant>`?

**Comment by eerohele** [comment]
I'm not able to reproduce this with `develop` or 2.1.1. How does your classpath look like, or are you setting it with the Ant `-lib` switch?

**Comment by xephon2** [comment]
The problem is reproducable. @raducoravu examined that the problem occurs only with the webhelp plugin and is related to a bug in its indexer lib. So it is no dita-ot issue.
