### ISSUE TITLE
dita -install does not work on Windows

### ISSUE THREAD

**Issue by AnthonyStevens** [dita-ot/dita-ot#2002]
org.dita.dost.invoker.Main assumes that the dita.dir property is defined (in processArgs). The dita.bat file does not define this, which causes an NPE and a silent failure. Since the dita shell script sets this property when calling java, should dita.bat do it as well?

**Comment by robander** [comment]
This was reported in August, meaning it would have been on 2.0 or 2.1, but the related issue linked above showed that this error in 2.1 was resolved in 2.2. I think this issue is most likely obsolete as well, and can be fixed by upgrading to 2.2.

**Comment by robander** [comment]
Double checked with 2.2.4 and I'm about to run `dita -install` on Windows without any errors - I'm assuming that this was resolved in 2.2 as with #2182. Marking this closed.
