### ISSUE TITLE
Ditaval File with DOCTYPE declaration crashed DITA-OT

### ISSUE THREAD

**Issue by darichard** [dita-ot/dita-ot#2005]
When a ditaval file contains the ditaval.dtd public declaration.
The following error is raised:

dita-ot:     [xslt] D:\Programs\dita-renderer\DITA-OT2.0.1\plugins\org.dita.pdf2\xsl\fo\flagging-preprocess.xsl:46: Error! java.io.FileNotFoundException: D:\Programs\dita-renderer\temp\render_1437644417852\extracted\ditaval.dtd 

it seems that the catalog declaring the ditaval.dtd is not loaded well at that time.
If we remove the DOCTYPE declaration in the ditaval file, everything is ok.

**Comment by raducoravu** [comment]
Probably when the DITAVAL is parsed, the parser could have a custom entity resolver set to it. In the meantime indeed you should remove the declaration from the file.

**Comment by darichard** [comment]
Yes but then in Componize the ditaval file ine not valid is the dtd is not
declared.

**Comment by raducoravu** [comment]
If the CMS prohibits publishing with a DITAVAL which does not have a DOCTYPE (although it should not), as another workaround you could declare the DTD content model directly in the DOCTYPE declaration like:

            <!DOCTYPE val[
            <!ELEMENT val (style-conflict?, (prop | revprop)*)>
            <!ELEMENT style-conflict EMPTY>
            <!ATTLIST style-conflict
              foreground-conflict-color CDATA #IMPLIED
              background-conflict-color CDATA #IMPLIED
            >
            
            <!ELEMENT prop (startflag?, endflag?)>
            <!ATTLIST prop
              att       CDATA	    #IMPLIED
              val       CDATA       #IMPLIED
              action    (flag|include|exclude|passthrough)  #REQUIRED
              color     CDATA       #IMPLIED
              backcolor CDATA       #IMPLIED
              style     (underline|double-underline|italics|overline|bold)       #IMPLIED
              >
            
            <!ELEMENT startflag (alt-text?)>
            <!ATTLIST startflag
              imageref  CDATA       #IMPLIED
            >
            
            <!ELEMENT endflag (alt-text?)>
            <!ATTLIST endflag
              imageref  CDATA       #IMPLIED
            >
            
            
            <!ELEMENT alt-text (#PCDATA)>
            
            <!ELEMENT revprop (startflag?, endflag?)>
            <!ATTLIST revprop
              val		CDATA		#IMPLIED
              action	(include|passthrough|flag)  #REQUIRED
              changebar CDATA       #IMPLIED
              color     CDATA       #IMPLIED
              backcolor CDATA       #IMPLIED
              style     (underline|double-underline|italics|overline|bold)       #IMPLIED
              >
            ]>
            <val>
                <prop action="exclude" att="audience" val="novice" />
                <prop action="flag" att="audience" val="general"/>
            </val>

**Comment by eerohele** [comment]
I can't reproduce this on 2.0.1 with [these files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/2005).

@darichard: could you post the DITAVAL file that crashes DITA-OT for you?

**Comment by eerohele** [comment]
Ah, never mind, I can reproduce it on Windows. Platform-specific, then.

**Comment by eerohele** [comment]
>Ah, never mind, I can reproduce it on Windows. Platform-specific, then.

Scratch that, I was also able to reproduce it on OS X now with the files in my repo — sorry about going back and forth. I was looking for the error message in the wrong place.

**Comment by SmashManiac** [comment]
I have a slightly different behavior on DITA-OT 2.3.2 on OS X. When I pass directly over the command line a DITAVAL file as filter with same public doctype declaration given as example by eerohele, I get this error:
`[gen-list] Failed to read DITAVAL file: [...]/ditaval.dtd (No such file or directory)`

**Comment by raducoravu** [comment]
+1 Somebody else reported this problem on the Oxygen forum:
https://www.oxygenxml.com/forum/post47111.html#p47051

**Comment by Nico-Amplexor** [comment]
Hello,
For information, I made some tests on version 3.4.1 until 3.5.4, and the problem still remains.
It not persist anymore since version 3.6.
