### ISSUE TITLE
Copy-to usage with URI support does not properly work [DITA OT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2006]
I'm publishing a DITA Map directly from an HTTP public server (no authentication).
At some point the DITA Map has a copy-to attribute:
```xml
<topicref href="topics/dita-pdf-select-processor.dita"
  copy-to="topics/dita-pdf-select-processor-transform-documents.dita"/>
```
The XHTML publishing fails like:

>BUILD FAILED
>D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:41: The following error occurred while executing this line:
>D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.xhtml\build_general.xml:112: Failed to run pipeline: Failed to transform C:\Users\RADU_C~1\AppData\Local\Temp\OxygenXMLTemp\https___raw.githubusercontent.com_oxygenxml_userguide_master_DITA\temp\xhtml\topics\dita-pdf-select-processor-transform-documents.dita: Error reported by XML parser processing file:/C:/Users/RADU_C~1/AppData/Local/Temp/OxygenXMLTemp/https___raw.githubusercontent.com_oxygenxml_userguide_master_DITA/temp/xhtml/topics/dita-pdf-select-processor-transform-documents.dita: Premature end of file.

and indeed the file "pdf-select-processor-transform-documents.dita" in my temporary files folder is empty, it has no content.

Looking into the entire console output, here are some stages which deal with that copy-to:

>[filter] Processing https://raw.githubusercontent.com/oxygenxml/userguide/master/DITA/topics/dita-pdf-select-processor-transform-documents.dita
[filter] Recoverable error 
[filter]   I/O error reported by XML parser processing

so the filter stage attempts to download it directly from the website although it is a topic which does not exist there, it is artificially created in the temporary files folder.

In the same console I see at some point:

>[filter] Processing https://raw.githubusercontent.com/oxygenxml/userguide/master/DITA/topics/dita-pdf-select-processor.dita
[filter] [DOTX064W][WARN] The copy-to attribute [copy-to="topics\dita-map-edit-output-transform-documents.dita"] uses the name of a file that already exists, so this attribute is ignored.

which seems to indicate the file already exists, although it does not exist on the server. Trying to connect directly to the file `https://raw.githubusercontent.com/oxygenxml/userguide/master/DITA/topics/dita-pdf-select-processor-transform-documents.dita` should at some point throw a 404 not found exception which should be interpreted as a missing resource.

**Comment by jelovirt** [comment]
This may be caused by optimistic exists-function. If you want to check whether a URI resolves to a resource, you'll have to actually retrieve it and currently the code it's really ready for that yet. For HTTP and HTTPS it's just a matter of a HEAD request, but for other URI schemes you basically have to try to retrieve it and then just ignore the stream.

**Comment by raducoravu** [comment]
Yes, exactly, the safest way would be to open the input stream to the URL connection and read a byte from it, then close the stream.
Indeed for http and https connections you could also directly create a SUN HTTP Connection and obtain the head status.
Sometimes the head status will be 403 (forbidden to use HEAD on some servers) or 405 (about the same thing) or 204 (on some Exist servers) and you would still need to open the stream to make sure.

The problem with using directly SUN HTTP Connections would be that the URL abstraction would not be used anymore. For example we plan to provide our own HTTP protocols when DITA OT 2.x is run from Oxygen but our protocols (which may know more authentication techniques) would not be used if you perform the checks using SUN connections.

**Comment by jelovirt** [comment]
A longer term intent is to not use built in `URI.getConnection`, but rather use e.g. Apache HTTP Client to allow e.g. authentication and cache control.

**Comment by raducoravu** [comment]
We also use the Apache HTTP Client for Oxygen so the HTTP protocols we would install in the DITA OT 2.x would be based on that. But it might have some improvements, for example use the authentication details already set up by our users. Also some CMSs (most of them are HTTP based anyway) may want to control the HTTP connection as well. So maybe in the future a parameter could be used to specify if the HTTP should be done via Apache or via the default installed protocols. Or maybe in the future we could have a plugin extension which is called to install the protocols.

**Comment by jelovirt** [comment]
If we didn't use Ant as the driver, I'd just go with dependency injection and allow people to use that to use their own clients and in testing just use mocks. Maybe it's possible to do that even now, since the intent is that Ant code doesn't pull the content from source, but rather custom Java code.

**Comment by raducoravu** [comment]
Yes, exactly. Unrelated to this, does this support for remote URIs also work with remote (HTTP for example) DITAVAL files? If not, I canadd an issue. We had CMS users who wanted to use their DITAVAL files directly from remote locations.

**Comment by jelovirt** [comment]
Please, create an issue for remote DITAVAL, I haven't implemented it yet.

**Comment by raducoravu** [comment]
I tested the fix with our entire public github user's manual and the publishing works now. There are 4 more reported issues which may still be obtained even when performing local processing, I will look into them.
