### ISSUE TITLE
Make it possible to use variables in the ditaval file

### ISSUE THREAD

**Issue by tyrin** [dita-ot/dita-ot#2007]
I want to flag items that are new based on version. I already supply the version as a property to the build: project.ver. I'd like to be able to specify this in the ditaval file, so that I don't have to update every ditaval file for every language each release. For example, instead of:   
&lt;revprop action=&quot;flag&quot; val=&quot;15.8&quot; backcolor=&quot;LemonChiffon&quot;&gt;
    &lt;startflag imageref=&quot;img/images/New2.gif&quot;&gt;&lt;alt-text&gt;What&#39;s New&lt;/alt-text&gt;&lt;/startflag&gt;
&lt;/revprop&gt;  
I'd like to be able to use:
&lt;revprop action=&quot;flag&quot; val=&quot;${project.version}.8&quot; backcolor=&quot;LemonChiffon&quot;&gt;
    &lt;startflag imageref=&quot;img/images/New2.gif&quot;&gt;&lt;alt-text&gt;What&#39;s New&lt;/alt-text&gt;&lt;/startflag&gt;
&lt;/revprop&gt;

**Comment by jelovirt** [comment]
You can already do this with e.g.

```xml
<echoxml file="${dita.temp.dir}/filter.ditaval">
  <revprop action="flag" val="${project.version}.8" backcolor="LemonChiffon">
    <startflag imageref="img/images/New2.gif"><alt-text>What's New</alt-text></startflag>
  </revprop> 
</echoxml>
```

And just run the code before `preprocess` task and pass that file as the filter file.

Closing as wont'f fix, as we don't want to modify the DITAVAL processing in a way that's not per spec, especially when there's a easy workaround.

**Comment by tyrin** [comment]
Eh. That's a good idea. Thanks Jarno.
