### ISSUE TITLE
Command line parameters not working with Windows PowerShell

### ISSUE THREAD

**Issue by dagoss** [dita-ot/dita-ot#2010]
When using the command line `dita` tool, passing parameters during the build does not seem to work. For example:

```
dita -i mymap.ditamap -f pdf2 -Dargs.draft=yes
```

produces the following error message:

```
Error: Target "yes" does not exist in the project "DOST".
```

This error only seems to occur when trying to build using the Windows PowerShell. If using the normal Command Prompt (cmd.exe), the map builds successfully. 

Using the `-propertyfile [file]` argument _does_ can be used as a work around

**Comment by robander** [comment]
I ran into the same message today when I typed in a parameter wrong. I don't see that in the one you typed in above, but I am going out on a limb and wondering if you pared down your command line for simplicity?

My command line in a DOS prompt was:
```
C:\DITA-OT\dita-ot-2.2.4>dita -i reproduce\2321.ditamap -f html5 -o out -v -temp -Dclean.temp=no
Error: Target "no" does not exist in the project "DOST".
```

I should have set `-temp temp` but didn't actually specify the temp directory, and somehow this caused the "no" after `-Dclean.temp=no` to be treated as an Ant target.
