### ISSUE TITLE
Pre-processing of map <navtitle> elements different in DITA-OT >=2.0

### ISSUE THREAD

**Issue by ywestra** [dita-ot/dita-ot#2016]
Pre-processing of map `<navtitle>` elements different in DITA-OT >=2.0 

After a couple of hours deep-dive I'm pretty sure that the pre-processing behaviour of populating the `<navtitle>` elements inside the pre-processed DITA maps during mappull has changed. I'm almost sure that this is not intentional behaviour and hope it can be fixed or worked around easily. 

Given the following minimalistic input. 
map.ditamap: 

``` xml
<map> 
<topicref href="topic.dita"> 
<topicmeta> 
<navtitle>Topic navtitle</navtitle> 
</topicmeta> 
</topicref> 
</map> 
```

topic.dita: 

``` xml
<concept id="topic";> 
<title>Concept title</title> 
<conbody> 
<p>My concept</p> 
</conbody> 
</concept> 
```

This will generate the following pre-processed version of map.ditamap in the temp folder (stripped debug attributes etc....): 

``` xml
<map> 
<topicref href="topic.dita"> 
<topicmeta> 
<navtitle>Topic navtitle</navtitle> 
<?ditaot gentext?> 
<linktext>Concept title</linktext>
<?ditaot genshortdesc?> 
<shortdesc /> 

</topicmeta> 
</topicref> 
</map> 
```

In previous DITA-OT versions the content would be: 

``` xml
<map> 
<topicref href="topic.dita"> 
<topicmeta> 
<navtitle>Concept title</navtitle&gt; 
........ 
```

The result of this changes is that all navigational items in output like an index.html TOC file or a CHM HHC file show the `<navtitle>` of the map and not the `<title>` of the topic while the `<navtitle>` of the map should only be used if the `@locktitle` attribute was set to 'yes'. 

To rule out some possible causes I tried the following: 
-   Remove the `<navtitle>` element from the map: then it works as expected 
-   Set a `@locktitle` attribute to 'no': no change 
-   Add an empty `<navtitle>` element: no change, the empty navtitle is preserved still 

Most prominent questions: 
1.  Is this a known issue? 
2.  Can you please confirm it is not intentionally so should be changed? 
3.  Are there any (known) workarounds 

Please, note that I've tested on different DITA-OT versions and on different systems. All with the same result. Doing a deep-dive in mappullImpl.xsl proofs that the behaviour is not as expected.

**Comment by eerohele** [comment]
Confirmed with the latest `develop` branch with [these files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/2016) and that the issue doesn't occur with 1.8.5.

**Comment by ywestra** [comment]
Great this has been identified

**Comment by eerohele** [comment]
Bisected; the issue was introduced in 77d3cd64eccf66868753f4853c7f86117daaa8bd.

**Comment by jelovirt** [comment]
Since 77d3cd6 is quite a large refactoring, it's probably easier to fix this by trying the current code instead of locating which change in 77d3cd6 broke it.

**Comment by eerohele** [comment]
@jelovirt: Do you think this is a bug in the preprocessing, or should this be handled by transtype-specific code?

Asking because the [`getNavTitle` template](https://github.com/dita-ot/dita-ot/blob/9a66a4b0c0f9528a3d6c256616ece6935cea978f/src/main/plugins/org.dita.pdf2/xsl/fo/commons.xsl#L1096-L1111) handles navtitles for PDFs (which means this issue doesn't affect the PDF transtype), but the HTML transtype assumes it's handled in preprocessing.

My initial feeling is that the transtype-specific approach is more logical — the navtitle is a somewhat transtype-specific concept, after all.

**Comment by jelovirt** [comment]
I kinda agree in having transtype stylesheets handle navtitles (and links). In order not to break backwards compatibility, we could have a preprocessing step do one navtitle resolution, but one that could be disabled in a transtype prefers to do its own thing.

**Comment by robander** [comment]
I think it's a bug in the preprocessing - the spec says when `navtitle` in the map should be respected, and when it should not. That's what led to the earlier preprocessing logic - a `navtitle` in the map is really just an authoring hint or guide, but titles should be pulled from the topic (replacing the one in the map) unless `locktitle="yes"` clearly tells a processor to respect the one in the map.

That said, if PDF has its own rules for navigation that don't match the map, that's fine with me ... but the spec really does say when `navtitle` values are meaningful, so we should update it (or not) based on that rule. Transtype specific stylesheets can then use it or not. Put another way ... nothing in the spec says that you have to use `navtitle` values found in the map for anything, but if you do, preprocess should have it updated for you based on the spec rules.

**Comment by ywestra** [comment]
Hi, I totally agree with Robert. Fact is that almost all transtypes like htmlhelp; javahelp and others rely on this behavior of pulling the topic title into the navtitle depending on the @locktitle attribute during pre-processing.
So even if it was agreed to change the logic of the navtitle pre-processing then both built-in and existing plugins all need to be adapted. I think this is not intentional and desired.
