### ISSUE TITLE
Reltables do not work if using any keys outside map directory

### ISSUE THREAD

**Issue by dagoss** [dita-ot/dita-ot#2017]
When key definitions are includes from outside the current map directory, links that should be generated by `<reltable>` elements do not appear in PDF2 output. This happens even if the `<reltable>` doesn't use any keys from the external map. 

Consider the following map:

```
<map>
    <mapref href="../common/keydefs.ditamap"/>
    <keydef keys="foo" href="foo.dita"/>
    <keydef keys="bar" href="bar.dita"/>

    <topicref keyref="foo"/>
    <topicref keyref="bar"/>

    <reltable>
        <relcell>
            <topicref keyref="foo"/>
        </relcell>
        <relcell>
            <topicref keyref="bar"/>
        </relcell>
    </reltable>
</map>
```

In this example, the keys foo and bar are defined locally, but the map also has keys from another map a level above the current maps's directory.

The links that should be appearing with topics foo and bar do not appear in PDF2 output. If the reference to the external map is removed, the `<reltable>` links are generated as expected.

**Comment by eerohele** [comment]
This is actually not related to keyrefs.

This is enough to reproduce the issue:

```xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">

<map id="map" title="DITA Map">
  <topicref href="topic1.dita"/>
  <topicref href="../topic2.dita"/>

  <reltable>
    <relrow>
      <relcell>
        <topicref href="topic1.dita"/>
      </relcell>
      <relcell>
        <topicref href="../topic2.dita"/>
      </relcell>
    </relrow>
  </reltable>
</map>
```

The issue is similar to #2190 in that the path to the file to which related links are inserted is resolved against the root of the temp directory instead of against the URI of the map that includes the file.

This should fix that issue:

```diff
diff --git a/src/main/java/org/dita/dost/module/MoveLinksModule.java b/src/main/java/org/dita/dost/module/MoveLinksModule.java
index 012909f..8d28e11 100644
--- a/src/main/java/org/dita/dost/module/MoveLinksModule.java
+++ b/src/main/java/org/dita/dost/module/MoveLinksModule.java
@@ -86,11 +86,11 @@ final class MoveLinksModule extends AbstractPipelineModuleImpl {
             linkInserter.setLogger(logger);
             linkInserter.setJob(job);
             for (final Map.Entry<File, Map<String, Element>> entry: mapSet.entrySet()) {
-                final File f = new File(job.tempDir, entry.getKey().getPath());
-                logger.info("Processing " + f);
+                final URI uri = inputFile.toURI().resolve(entry.getKey().getPath());
+                logger.info("Processing " + uri);
                 linkInserter.setLinks(entry.getValue());
                 try {
-                    linkInserter.write(f);
+                    linkInserter.write(new File(uri));
                 } catch (final DITAOTException e) {
                     logger.error("Failed to insert links: " + e.getMessage(), e);
                 }
```

That won't solve the issue completely, though, because `maplinkImpl.xsl` also resolves `<link>` `@href` attributes incorrectly. This change will cause the `@href` attributes to resolve correctly:

```diff
diff --git a/src/main/xsl/preprocess/maplinkImpl.xsl b/src/main/xsl/preprocess/maplinkImpl.xsl
index e8779e7..de35602 100644
--- a/src/main/xsl/preprocess/maplinkImpl.xsl
+++ b/src/main/xsl/preprocess/maplinkImpl.xsl
@@ -43,7 +43,9 @@
         <xsl:apply-templates select="node()" mode="strip"/>
       </xsl:document>
     </xsl:variable>
-    <xsl:apply-templates select="$map/node()"/>
+    <xsl:apply-templates select="$map/node()">
+      <xsl:with-param name="base-uri" select="base-uri()" tunnel="yes" as="xs:anyURI"/>
+    </xsl:apply-templates>
   </xsl:template>
   
   <xsl:template match="node() | @*" mode="strip">
@@ -517,6 +519,7 @@
     <xsl:param name="pathBackToMapDirectory" as="xs:string" tunnel="yes"/>
     <!-- child found tag -->
     <xsl:param name="found" select="true()" as="xs:boolean"/>
+    <xsl:param name="base-uri" as="xs:anyURI" tunnel="yes"/>
     <!-- If going to print, and @print=no, do not create links for this topicref -->
     <xsl:if test="not(($FINALOUTPUTTYPE = 'PDF' or $FINALOUTPUTTYPE = 'IDD') and @print = 'no') and 
                   not(@processing-role = 'resource-only') and $found">
@@ -563,9 +566,7 @@
             </xsl:when>
             <!--ref between two local paths - adjust normally-->
             <xsl:otherwise>
-              <xsl:call-template name="simplifyLink">
-                <xsl:with-param name="originalLink" select="concat($pathBackToMapDirectory, @href)"/>
-              </xsl:call-template>
+              <xsl:value-of select="resolve-uri(@href, $base-uri)"/>
             </xsl:otherwise>
           </xsl:choose>
         </xsl:attribute>
```

But that will generate absolute URIs for `<link>` elements, and they really need to be relative for them to work correctly in all transtypes. I'm not really hyped about the idea of writing XSLT code for relativizing paths, though. Using the Java 7 [relativize](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#relativize%28java.nio.file.Path%29) method would probably be the most robust option. @jelovirt: opinions?

**Comment by jelovirt** [comment]
@eerohele I'll clean the maplink code a bit first before we fix this. I've already removed some über legacy code that handles back slashes in URIs, just to get rid of code that's completely useless at this point. I'll add datatypes to the XSLT code too, just to make the a bit more robust. After that, we can implement the changes you've proposed and add the relativization code to XSLT. It's not the way I would really prefer to do it, but if we add `dita-ot:relative($href, $base)` function to common code and add a solid set to XSpec tests, it should be ok. I can later on add the XSpec integration to unit test target in Gradle.

**Comment by eerohele** [comment]
@jelovirt it should now be pretty straightforward to fix this one since you added the relativize function in e4c4d902e84ff91b029b39824a68459e88bb3045, I think.

**Comment by jelovirt** [comment]
@eerohele are you able to send a PR?
