### ISSUE TITLE
Purpose and improvement request for the "resources/plugins.xml" [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2018]
In DITA OT 2.x after the integrator is run there is a resource  "resources/plugins.xml" which keeps a list with all the contents of all the plugin.xml's in the DITA OT distribution.
What is the purpose of that file? 
Could it be modified to also include xml:base so that when I parse it and I find references like "dita.conductor.target.relative" which are relative to the plugin folder I can determine where that target is located?

**Comment by jelovirt** [comment]
`plugins.xml` is used by e.g. documentation generation to get a list of extension points etc.

:+1: for addding `@xml:base` to each plugin configuration element so that file paths in plugin configuration can be resolved.

**Comment by raducoravu** [comment]
There is a problem, the xml:base should be relative to the plugin.xml and not absolute.
In this way, I cannot share a DITA OT distribution with somebody else, commit it for example on a SVN server or in the case of Oxygen bundle it with an application.

**Comment by jelovirt** [comment]
Reopening to make `xml:base` relative.

**Comment by raducoravu** [comment]
Thanks Jarno, I tested and it seems to make the proper relative paths.
