### ISSUE TITLE
Support RELAXNG parsing and validation

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2019]
Integrate George's RNG DTD compatibility libraries into the OT's DITA parsing code.

**Comment by nakohdo** [comment]
+1 from me

JFTR linking this to the discussion in the DITA-OT Users group
["Using DITA-OT with RNG files?"](https://groups.google.com/forum/#!topic/dita-ot-users/0XZAloq2cOY)

**Comment by jelovirt** [comment]
If possible, we should handle this as plugin to the parsing infrastructure. Can you provide the code that's to be integrated and info how forks of OT currently handle this?

**Comment by drmacro** [comment]
Yes, we have a plugin that does this (George set it up originally as part of his ditarng project). I'll take the task of reworking it as something that can be part of the OT plugin set and submit a pull request.

**Comment by queshaw** [comment]
I have a fork of DITA-NG that adds schema validation support, if that interests anyone. I made a fork here:

https://github.com/queshaw/dita-ng/tree/validation

Essentially, if a properties file named **dita-ng.properties** contains **validate=yes**, after the document is augmented with default values (class attribute etc.), the parse tree is validated using the validation part of Jing (org.thaiopensource.relaxng.sax.PatternValidator).

I also added commands for invoking DITA-OT with the classpath set. They are wrappers around the  dita command. You can install the plugin using the command, e.g.:

bin/dita-ng -install somewhere/dita-ng20150914.zip -v
bin/dita-ng -uninstall org.dita-ng.doctypes -v

And, I added some unit tests.

**Comment by drmacro** [comment]
This seems like appropriate default behavior. I would think most, if not all, users would expect this level of validation.

**Comment by queshaw** [comment]
I've made more changes that I hope might serve as at least exercising dita-ng.

In my fork, I split the plugin into two plugins, one is a library plugin, that adds dita-ng and jing to the classpath, the other is a catalog plugin.

I also changed the flowers demo files to use the OASIS urns and added the dita spec from CS01 part3 all inclusive. And I got rid of the dita-ng commands since you don't need to adjust the classpath.

So, for testing the integration you can process the DITA spec. I hope there isn't a problem with including the spec.

For the build, there is separate dist target to do the conversion and dist thing that was there and then there is dist.minimal which creates the two separate plugins and doesn't run any conversion.

**Comment by queshaw** [comment]
Oh, and I made validation the default.

**Comment by jelovirt** [comment]
To make things more simple, could you split the two plugins into two separate Github repos and add a Gradle build script to build the validation capability plugin. This makes it easier to build them and possibly use alternative RNG files.

**Comment by queshaw** [comment]
I've split off the library and replaced ant with gradle.

https://github.com/queshaw/dita-ng-library

The dist target puts the zip file in the dist directory. I will change the readme file to reflect the changes and work on the catalog repo.

**Comment by queshaw** [comment]
I created another repo for a catalog plugin:

https://github.com/queshaw/dita-ng-catalog

It is essentially the same catalog from dita-ng, but the flowers demo files are changed to use oasis urns, it uses the cs01 dita-1.3 grammars and includes the cs01 dita spec as another demo.

**Comment by raducoravu** [comment]
+1 

One of our users tried to publish a DITA RNG-based DITA Map using an external DITA OT command line:

https://www.oxygenxml.com/forum/post39350.html#p39340

**Comment by raducoravu** [comment]
I created a DITA OT 2.x plugin which adds RNG default attributes specialization support to DITA OT 2.x:

https://github.com/oxygenxml/dita-relaxng-defaults

Maybe at some point the libraries from this plugin can be taken and included with the default DITA OT 2.x plugins.

**Comment by queshaw** [comment]
Hi, I'm pretty distracted these days but. Briefly looking at the dita-ng repo that the plugin references I didn't immediately see if it supports validation. The plugins that I posted a while back:

https://github.com/queshaw/dita-ng-library
https://github.com/queshaw/dita-ng-catalog

were a fork of dita-ng that split it out into a separate library plugin. The library plugin added support for relaxng schema validation.

So, maybe Radu and George would be interested in including the changes from ditaq-ng-library.

**Comment by ToshihikoMakita** [comment]
Is RELAX NG validation in DITA-OT scheduled surely in 2.4? I've been working with DITA 1.3 specializations by RELAX NG. The validation works fine in oXygen. But the newest (2.3.3) DITA-OT seems to not support it. yet I'm looking forward the official release.

**Comment by xephon2** [comment]
@jelovirt The modified file structure of [dita-relaxng-defaults](https://github.com/oxygenxml/dita-relaxng-defaults) makes it possible to add it as a Git Submodule into the plugins directory. That would bring RelaxNG support to the OT. I'd be happy, if you'd add it.

**Comment by shaneataylor** [comment]
@xephon2 FWIW, I installed the dita-relaxng-defaults plugin yesterday to DITA-OT 2.3.1 and still got this build error for a RNG-based topic:

[DOTJ013E][ERROR] Failed to parse the referenced file 'file:competencies.dita'.: file:competencies.dita Line 4:cvc-elt.1.a: Cannot find the declaration of element 'concept'.

The file validates fine in the Oxygen editor, so I don't *think* it's the RNG itself.

**Comment by xephon2** [comment]
@shaneataylor Have you tried the [samples](https://github.com/oxygenxml/dita-relaxng-defaults/tree/master/samples)? You have to use the correct `xml-model` instead of the default DTD `DOCTYPE`. Please also check, that the libraries (jar files) hava been added correctly to the path.

**Comment by shaneataylor** [comment]
@xephon2 Ultimately, my error was running the dita command with the -noclasspath parameter. Not sure why I added that (2 years ago) but that's what was causing the failure. 

@infotexture Although we don't want to be in the business of documenting Ant, we might note in the docs that -noclasspath can (will?) cause plugin JARs not to be available, possibly leading to build failures. This feels to me like troubleshooting info: if you have an unexplained build failure, check to see if you are using the -noclasspath parameter and try building without that parameter. That the JARs were not available was not apparent from the log. That this parameter caused the JARs not to be available was not discoverable in the DITA-OT docs. Possibly it's also a best practice to avoid using this parameter altogether.

Ref: https://ant.apache.org/manual/running.html

**Comment by infotexture** [comment]
@shaneataylor I agree with the first part: 

> Although we don't want to be in the business of documenting Ant, we might note in the docs that -noclasspath can (will?) cause plugin JARs not to be available

The `-noclasspath` option is not currently mentioned anywhere in the docs and to my knowledge we have never advocated using it, so I'm reluctant to add content that describes what seems like a rather unique edge case.

Feel free to submit a docs PR if you feel it's important enough to include and discuss further.

**Comment by chrispitude** [comment]
> 
> 
> This seems like appropriate default behavior. I would think most, if not all, users would expect this level of validation.

New user here. Can confirm, expected this level of validation. Got confused when it didn't!
