### ISSUE TITLE
CHM encoding of HTML content inside topics should always be UTF-8

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2020]
One of our users had the following problem:

Let's say I have a DITA topic, I have no language specified to it's considered to be en-us.
At a certain point in the topic I use a certain non-ASCII character `<ph>&#10003;</ph>`.

After publishing to CHM, the character is replaced with an invalid character in the HTML output.
This happens because the "org.dita.dost.util.ConvertLang" Java task has looked into the `/org/dita/dost/util/codepages.xml` and considered that for en-us it should use "iso-8859-1" which cannot encode that specific character. Looking in the same codepages.xml file the encoding is UTF-8 for certain languages.

In my opinion the encoding used for the HTML content obtained from the DITA topics (not for the HHP and HHC files which are created separately) should always pe UTF-8 and the codepages.xml should be eliminated.

What I could find on the web about this:

> If the HTML is encoded as Unicode (UTF-8 or UTF-16 aka UNICODE) non-English chars won't be handed correctly in the HH navigation (TOC, Index, Search). The embedded browser (content area on right of the help viewer) will however display the topic text fine since this is a UNICODE enabled control.

Or at least for en-us we could use utf-8 because it is a perfect superset of ASCII which can encode all English chars.

**Comment by jelovirt** [comment]
I'm unable to test this as Windows is needed. Can someone confirm that CHM will work on "all" cases if the actual content pages are output as UTF-8 and only TOC, index, and search are converted to language specific encoding?

**Comment by robander** [comment]
We've been using UTF-8 for the content for years, while converting the HHP, HHC, and HHK files to a specific codepage for the locale. It's worked for all of the languages we use (all those currently in the toolkit).

**Comment by robander** [comment]
Looking at this again - it looks like there were a couple of closed pull requests but the function hasn't been added yet in 2.2. I think this would be a good change. It might also take care of #1383, at least for text in the content (at least for those not in the TOC / index / search).

**Comment by raducoravu** [comment]
I think I closed this one myself because there were failed tests after my changes. Maybe you could try to make changes on your side and run the tests, see if they should be rectified in some way.

**Comment by raducoravu** [comment]
+1 

Had one more end user using reserved chars in the DITA content like "&#xe020;" and expecting them to be carried as such to the HTML content in order to be displayed with a custom font they have.

**Comment by robander** [comment]
3.0.1 fixed the project files so that they use Windows code pages and avoid entities when possible. I'd forgotten about this one, otherwise it probably would have made sense to make the same change at the same time. As mentioned in 2016, I think it's a good idea to leave the HTML as-is, because the system browser used to handle it can handle UTF-8 without any problems. This would also mean we don't need to convert any entities in the HTML files for HTML Help -- only the project files would need to be converted.

**Comment by raducoravu** [comment]
Another encoding problem, let's say the title of the DITA Map contains the character "³". The ".hhp" contains this map title and when the "ConvertLang" is run, it will convert the character to "&sup3;" which will appear as it is in the opened CHM help. This conversion to an entity reference is done even if the "windows-1252" encoding can encode this specific character.

**Comment by raducoravu** [comment]
👍 Just had another end user encounter this problem.

**Comment by raducoravu** [comment]
👍 and yet another client using Chinese content with DITA to CHM output complained about this.

**Comment by raducoravu** [comment]
Spent some more time today on this.
About the problem with "³" being shown in the window title bar as &sup3;, the code in:

org.dita.dost.ant.ConvertLang.convertEntityAndCharset(File, String)

seems to prefer using the entity reference although sometimes the output encoding can encode a certain character.
The patch I made on my side was to first check that the output encoding can or cannot encode a character before using the entity reference equivalent. Something like:


            //START OXYGEN PATCH FOR EXM-44494
            CharsetEncoder outputCharsetEncoder = null;
			try {
				Charset outputCharset = Charset.forName(charset);
            	outputCharsetEncoder = outputCharset.newEncoder();
            } catch(Exception ex) {
            	//This should not happen
            	ex.printStackTrace();
            }
            //END OXYGEN PATCH FOR EXM-44494

            //read a character
            int charCode = reader.read();
            while(charCode != -1) {
                final String key = String.valueOf(charCode);
                //Is an entity char
                if (entityMap.containsKey(key) &&
                        !entityExceptionSet.contains(charCode)) {
                    //START OXYGEN PATCH FOR EXM-44494
                	if(outputCharsetEncoder != null && outputCharsetEncoder.canEncode((char)charCode)) {
                		//Can be encoded, no need to convert to entity
                		writer.write(charCode);
                	} else {
                    //END OXYGEN PATCH FOR EXM-44494		
                		//get related entity
                		final String value = entityMap.get(key);
                		//write entity into output file
                		writer.write(value);
                	}
                } else {
                    //normal process
                    writer.write(charCode);
                }
                charCode = reader.read();
            }
