### ISSUE TITLE
Chunking a document loses @xml:lang from root topic

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2022]
I've edited `garagetaskoverview.xml` to add `xml:lang="fi-fi"` to the root, add a `<note>` that generates text, and add a nested topic that doesn't set the language. I then added `chunk="by-topic"` to the map reference. I get 2 output files as expected. The root file uses the expected generated text for the note: Huomautus. The nested topic uses the default English, losing the `@xml:lang` value set on the parent element.

Edited version of the file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN"
 "../../dtd/technicalContent/dtd/concept.dtd">
<concept id="taskconcept" xml:lang="fi-fi">
  <title>Garage Tasks</title>
  <shortdesc>When you go into the garage, be prepared to get your hands dirty!</shortdesc>
  <conbody>
    <note>This is a note in the root topic</note>
  </conbody>
  <concept id="concept_hg1_xl2_2t">
    <title>Nested Garage Tasks</title>
    <shortdesc>When you go into the garage, be prepared to get your hands dirty!</shortdesc>
    <conbody>
      <note>This is a note in the nested topic</note>
    </conbody>
  </concept>
</concept>

```

**Comment by robander** [comment]
Note: this actually came up in the context of a `<dita>` element that wraps several topics, which failed when they chunked the document in NLS versions. The `<concept>` element is just a slightly simpler case based on our existing sample files.

**Comment by Nikulinnn** [comment]
Could somebody please clear up the following issue for me.
Let's assume I have a file with the following structure: 
```
<concept id="roort-concept" xml:lang="en">
  <title>Garage Tasks</title>
  <shortdesc>When you go into the garage, be prepared to get your hands dirty!</shortdesc>
  <conbody>
    <note>This is a note in the root topic</note>
  </conbody>
  <concept id="first-nested-concept-level-1" xml:lang="ru">
    <title>Nested Garage Tasks</title>
    <shortdesc>When you go into the garage, be prepared to get your hands dirty!</shortdesc>
    <conbody>
      <note>This is a note in the nested topic</note>
    </conbody>
    <concept id="nested-concept-level-2">
      <title>Nested Garage Tasks</title>
      <shortdesc>When you go into the garage, be prepared to get your hands dirty!</shortdesc>
      <conbody>
        <note>This is a note in the nested topic of the nested topic</note>
      </conbody>
    </concept>
  </concept>
  <concept id="second-nested-concept-level-1">
    <title>Nested Garage Tasks</title>
    <shortdesc>When you go into the garage, be prepared to get your hands dirty!</shortdesc>
    <conbody>
      <note>This is a note in the nested topic</note>
    </conbody>
  </concept>
</concept>
```
Do I understand correctly that `nested-concept-level-2` should inherit the language ("ru") from `first-nested-concept-level-1`, while `second-nested-concept-level-1` should inherit the language ("en") from the `roort-concept`?

**Comment by robander** [comment]
@Nikulinnn That is correct - it comes from the closest _containing_ element - peer elements that come before or after do not affect the current language.
