### ISSUE TITLE
Glossref inside topicgroup no longer processed in PDF output [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2024]
If my DITA Map has a glossref like:

      <topicgroup>
        <glossref keys="GlossEntGloballyUniqueIdentifier" href="g_GlossEntGloballyUniqueIdentifier.xml" print="yes"/>
      </topicgroup>

the PDF output does not contain it at all although it has print="yes". 
This worked in DITA OT 1.8.5.

Another problem deriving from this, a topic which has a keyref to it like:

       <xref keyref="GlossEntGloballyUniqueIdentifier"/>

has the proper title but is missing the page number.

Samples here:

http://www.oxygenxml.com/forum/files/topicGroupAndMapref.zip

**Comment by raducoravu** [comment]
Actually this also does not work in DITA OT 1.8.5.
In the root-processing.xsl there is a for-each at some point:

      <xsl:for-each select="opentopic:map/*[contains(@class, ' map/topicref ')]">

which should probably treat topicgroups as transparent.

**Comment by eerohele** [comment]
#1848 sounds related.

**Comment by raducoravu** [comment]
Indeed, this issue duplicates the other.

**Comment by eerohele** [comment]
Closing as duplicate of #1848.
