### ISSUE TITLE
Move to Java 8

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2026]
Use Java 8 as the minimum version.

**Comment by geezen** [comment]
If possible, please use OpenJDK 8 as the reference platform.

**Comment by jelovirt** [comment]
While I personally would like to move to Java 8 as soon as possible to get lambdas and additional Java 8 features into use, it's probably going to take a while before we get there. (Hopefully before Java 8 reaches end-of-life.)
