### ISSUE TITLE
Report warning for undefined element template match

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2033]
The "dita2htmlImpl.xsl" stylesheet has a template which matches:

``` xml
<xsl:template match="*" name="topic.undefined_element">
```

and issues a HTML yellow span like some kind of warning that the DITA element was not styled in any way.
Wouldn't it be better to issue an xsl:message with the warning and abstain from adding a yellow <span> in the HTML output?

**Comment by jelovirt** [comment]
That code has been in DITA-OT since the dawn of time.

:+1: for using warnings in log instead of yellow output in HTML.

**Comment by raducoravu** [comment]
Right, because right now a reviewer would need to go through all the HTML generated topics to see if such a problem arises.

**Comment by robander** [comment]
Yeah, that's been in the code since DeveloperWorks days, before there was a DITA-OT. :+1: for using a warning.

**Comment by robander** [comment]
The current template also adds a bold span before and after the element showing the XPATH for the problem element - assuming we add an error message here, should that XPATH info stay in the XHTML, or move to a message? (For what it's worth, I've found the info helpful before in debugging bad `@class` values in a specialization, but it might have been just as useful if found in a log.)
