### ISSUE TITLE
PDF flagging should use common preprocess code

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2047]
A couple years ago we introduced a preprocess step to add flagging information from DITAVAL documents into DITA content. This makes it easy for any output format to support flagging without having to re-implement the logic for flagging. XHTML code was converted to use the preprocess step at that time.

The PDF2 plugin runs the common preprocess step but ignores the result. It runs an extra processing step to set up flagging, so the logic is duplicated. We should remove the extra step and make use of the common preprocess logic.

I've got the basics working now but need additional updates for elements where fall-through processing of flags would result in out of context images (such as flagged `<tbody>` or `<ol>`).

**Comment by robander** [comment]
Commit includes initial implementation plus support for lists, where flagging inside of the main list causes context errors. Remaining tasks to fix context issues are mostly table elements and images (flagging currently disabled for those, needs to be re-enabled with context issues resolved).

**Comment by robander** [comment]
This feature makes the recent addition of the following extension point obsolete, as we no longer have any reason to run the step:
```xml
  <extension-point id="dita.xsl.xslfo.flagging-preprocess" name="PDF flagging preprocess import"/>
```

**Comment by jelovirt** [comment]
@robander is this ready?

**Comment by robander** [comment]
Yes, ready [for some reason I thought I'd added that comment a couple weeks ago].

**Comment by jelovirt** [comment]
The extension-point `dita.xsl.xslfo.flagging-preprocess` was never deprecated in docs and it hasn't been supported since 2.2. I removed it in 7868113 and streamlined the Ant configuration by removing the old flagging target completely.
