### ISSUE TITLE
Different behaviour when using locktitle attribute for PDF and XHTML transformations

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2052]
The _locktitle_ attribute is treated different when producing the TOC for the PDF or XHTML transformations. I get this difference both for DITA 1.8 and DITA 2.0.

The sample DITA map:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN"
 "http://docs.oasis-open.org/dita/v1.1/OS/dtd/map.dtd">
<map title="Eclipse content aggregated by a map">
    <topicgroup locktitle="yes">
        <topicref href="tasks/changingtheoil.dita" type="task">
            <topicmeta><navtitle>DT - Changind the oil</navtitle></topicmeta>
        </topicref>
        <topicref href="tasks/organizing.dita" type="task" locktitle="yes">
            <topicmeta><navtitle>DT - Organizing the workbench and tools</navtitle></topicmeta>
        </topicref>
    </topicgroup>

    <topicref href="tasks/shovellingsnow.dita" type="task" locktitle="yes">
        <topicmeta><navtitle>DT - Shovelling snow</navtitle></topicmeta>
    </topicref>
</map>
```

The difference comes from the fact that the HTML transformation treat the _locktitle_ attribute as **inheritable** and PDF not when the TOC is computed.

In the HTML transformation the TOC title for _tasks/changingtheoil.dita_ topic is taken from DITA map because the _locktitle_ attribute is set on the parent topic group.

The specification is a bit confusing for me:
http://docs.oasis-open.org/dita/v1.2/os/spec/langref/navtitle.html#navtitle

> When navtitle is used in a map, it functions in the same way as the navtitle attribute; both are used to specify a navigation title for the target of the <topicref> element. That is, the title itself will only be used as an actual navigation title when the title is locked; the title is locked when the closest ancestor topicref element sets or inherits the attribute locktitle="yes".

It says that the locktitle attribute can be inherited.

But in the section _Metadata in maps and topics_,  you can find the next phrase.

http://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/metadata-in-maps-and-topics.html#metadata-in-maps-and-topics

> The content of the <navtitle> element is used as a navigation title only if the @locktitle attribute of the parent <topicref> element is set to "yes".

that tells nothing about inheritance.

Is it the _locktitle_ inheritable? Which output is correct?

**Comment by robander** [comment]
To answer the easy question - `@locktitle` should not be inheritable. This was discussed back at the OASIS TC before DITA 1.2 came put, which led to the explicit update of that content in the referenced metadata-in-maps-and-topics link above, but it was missed in the topic about `<navtitle>`. The `<navtitle>` element description was updated in 1.3 to remove any mention of inheritance:
docs.oasis-open.org/dita/dita/v1.3/os/part1-base/langRef/base/navtitle.html

So, the PDF behavior is correct. You mention running into this with DITA 2.0 - I'm not sure if this issue still exists in 2.2 or the latest develop code.

**Comment by radu-pisoi** [comment]
I've tested with DITA-OT 2.2.3 and the text from 'topicref/topicmeta/navtitle' is displayed in TOC of the HTML output regardless of the value of the 'locktitle' attribute, #2187. 

So, the inheritance behavior cannot be tested.
