### ISSUE TITLE
Table processing different for first child of conbody and subsequent children

### ISSUE THREAD

**Issue by tyrin** [dita-ot/dita-ot#2057]
Two structurally identical tables that are both children of conbody are processed differently. Both tables have colspec=2 and no colwidth specified. The toolkit injects an automatic colwidth of 50% in the first table and nothing in the second table. Reversing the order of the tables shows that it's always the first table that has the colwidth injected and not subsequent tables.
The behavior of the second table is preferable, because autofit is a better option when localizing the doc into multiple languages. 
I have attached a test file and output to a public GIST: https://gist.github.com/tyrin/50768345d5a037f53802

**Comment by eerohele** [comment]
@tyrin: Which DITA-OT version are you using?

**Comment by tyrin** [comment]
DITA-OT1.8.4_standard_bin

**Comment by eerohele** [comment]
I can't reproduce this. On 1.8.x, there are no width values of any kind in the first two tables in `TableTest.html`, and on 2.1.1, both tables have 2 x `<col style="width:50%" />`.

Do you have any plugins installed that might affect the output?

**Comment by tyrin** [comment]
No plugins or customizations. I run this on mac os using an ANT build. From what you're telling me, if I upgraded the toolkit to a newer version this might go away?

**Comment by eerohele** [comment]
>From what you're telling me, if I upgraded the toolkit to a newer version this might go away?

Well, if you upgrade to 2.1.1, the behavior will be different than with 1.8.4, but I'm not sure whether it'll be what you want, since both of the first two tables will have 50% colwidths.

Still, would be nice to be able to reproduce this issue, but with the `TableTest.dita` file in your Gist and DITA-OT 1.8.4, this is the output I get:

https://gist.github.com/eerohele/a34d4f884a5c4e30d35d

**Comment by macksol** [comment]
Note that the issue with default behavior being the creation of evenly
proportioned column widths has already been reported by me (and marked for
a fix in 2.2).

There is an easy workaround (one line commented out) but you do need to
download the Java source.

See https://github.com/dita-ot/dita-ot/issues/1970

Colin Mackenzie

On 25 September 2015 at 07:13, Eero Helenius <notifications@github.com>
wrote:

> From what you're telling me, if I upgraded the toolkit to a newer version
> this might go away?
>
> Well, if you upgrade to 2.1.1, the behavior will be different than with
> 1.8.4, but I'm not sure whether it'll be what you want, since both of the
> first two tables will have 50% colwidths.
>
> Still, would be nice to be able to reproduce this issue, but with the
> TableTest.dita file in your Gist and DITA-OT 1.8.4, this is the output I
> get:
>
> https://gist.github.com/eerohele/a34d4f884a5c4e30d35d
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dita-ot/dita-ot/issues/2057#issuecomment-143138393>.
>



-- 

Colin Mackenzie

Mobile : 07786 621254
Email : colin@mackenziesolutions.co.uk
Web : www.mackenziesolutions.co.uk
Linked In : uk.linkedin.com/in/mrcolinmackenzie

**Comment by robander** [comment]
I think with update in #1970 this should now be resolved - tables without any width specification use auto-layout in 2.2. The original test case now only sets a width for the final table, under "This table has both colspec and colwidth".

**Comment by robander** [comment]
Marking this closed - I am not able to reproduce this with recent releases, and I think that the referenced fix in 2.2 resolved the issue.
