### ISSUE TITLE
French translation of Table of contents is incorrect

### ISSUE THREAD

**Issue by catrachos** [dita-ot/dita-ot#2060]
French translation for Table of contents incorrect in: fr.xml (org.dita.pdf2)
Observed in Dita OT ver 2.1.0 and earlier.

My localization vendor says that the following two French localized entries are incorrect:
variable id="Table of Contents": Sommaire
variable id="Contents button title": Sommaire

Expected:
variable id="Table of Contents": Table des matières
variable id="Contents button title": Table des matières

I did check Bing online translator:
Sommaire = Summary
Table des matières = Table of Contents

**Comment by robander** [comment]
The common string file `xsl\common\strings-fr-fr.xml` uses the suggested text:
```
   <str name="Contents">Table des matières</str>
```

**Comment by robander** [comment]
Checking around with the help of a colleague, it looks like Sommaire is used for some books but is not terribly common, seems to be more like a high-level TOC. I think it's better to use the suggested text Table des matières, which also means our different transforms will pick up the same term.

**Comment by robander** [comment]
Corrected to the suggested text for our 2.2 release. Oddly, the suggested text was already used in comments in the file about TOC values, so I'm not sure why it was changed for the actual translated text.
