### ISSUE TITLE
Table not localized in French translation org.dita.pdf2 - fr.xml

### ISSUE THREAD

**Issue by catrachos** [dita-ot/dita-ot#2061]
Dita OT 2.1.0 and earlier. Localization vendor says that Table should be Tableau in table headings for French version.

id="Table.title"
id="Table Number"

Table isn't localized from English.

Observed: Table 
Expected: Tableau

**Comment by robander** [comment]
Looks like the issue is still there in the latest code: 
https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/common/vars/fr.xml#L158

XHTML and other plugins that pull from `xsl\common\strings-fr-fr.xml

**Comment by robander** [comment]
Corrected to the suggested text for our 2.2 release.
