### ISSUE TITLE
Support "artlbl" option in PDF

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2062]
We have the argument `args.artlbl` in HTML based transforms - useful for review, it shows the name of an image alongside that image. Any objections if I add support for that same parameter to PDF2? I know that @keberlein has clients that would like it, and I've got some users who expect it as well.

**Comment by jelovirt** [comment]
:+1:

The name of the argument is ugly, but we should probably keep it the same in HTML and PDF.

**Comment by robander** [comment]
Agreed. Implementing with same argument name `args.artlbl`, for XSL parameter I'll pass it in with the slightly more meaningful `artLabel`. For inline images, the label will appear immediately after the image; for standalone images, it will appear on a line following the image. I picked bold italic as the default style for the label so that it stands out a bit, but could easily change that if something else is preferred.
