### ISSUE TITLE
When using @chunk="to-content", Next topic link from merged chunks points to same page

### ISSUE THREAD

**Issue by bogdan-cercelaru** [dita-ot/dita-ot#2064]
I uploaded a zip here: 
http://www.oxygenxml.com/forum/files/sample.zip

When the "UserGuide_TEST.ditamap" DITA Map gets published to plain XHTML, the "Next topic" link from "out/xhtml/Getting_Started/FirstConcept.html" page should point to "out/xhtml/Getting_Started/FourthConcept.html" instead of "out/xhtml/Getting_Started/FirstConcept.html#second_concept".

**Comment by jelovirt** [comment]
Which version of DITA-OT?

**Comment by bogdan-cercelaru** [comment]
DITA-OT 1.8.5 and DITA-OT 2.1 have the same problem.

**Comment by raducoravu** [comment]
Can no longer reproduce problem with DITA OT 3.x.
