### ISSUE TITLE
HTML output discards trademark symbols

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2065]
HTML processing currently discards trademark symbols in certain languages, whereas PDF processing includes the &#x2122; and <sup>&#xAE;</sup> symbols as expected regardless of the XML language setting.

With DITA source such as:

```xml
<p xml:lang="en">This is a trademark: <tm tmtype="tm">MyProduct</tm>.</p>
<p xml:lang="de">This is a trademark: <tm tmtype="tm">MyProduct</tm>.</p>
```

the HTML output includes the &#x2122; trademark symbol in the first _(English)_ paragraph, but discards it in the second where the `@xml:lang` attribute marks the content as German:

```html
<p xml:lang="en" lang="en" class="p">This is a trademark: MyProduct™.</p>
<p xml:lang="de" lang="de" class="p">This is a trademark: MyProduct.</p>
```

In PDF output, the trademark symbol appears in both cases as MyProduct™.

According to comments in `org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl` [Line 1142](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl#L1142), this behavior appears to be intentional, though no such rule seems to be applied in other transformation types:

> Use the TM for US English and the AP languages (Japanese, Korean, and both Chinese).
> Ignore the TM for all other languages.

Though the appropriate usage of trademark symbols in non-English languages is certainly debatable, I would expect OT to handle them consistently across transformation types and render them in HTML output as authored.

**Comment by jelovirt** [comment]
For example in Finland the trademark or registered trademark symbols have no legal meaning and they can be omitted. However, I think it should be easy to enable them per language. Not sure what the default should be, though. At least it should be consistent between PDF and HTML.

**Comment by robander** [comment]
I'm sure this is a legacy of some early processing in place when the code transitioned from IBM to open source. In IBM we override all trademark processing anyway, to make sure we comply with our latest rules, so any change here won't affect us. Generally - I think it makes sense that the default should mark them the same way, regardless of language. FWIW, I don't know what led to the "US and AP" rule at that time, maybe most other countries work the same as Finland, but author expectation is probably to see them unless they say otherwise?

**Comment by infotexture** [comment]
Revisiting this for a client, I have a custom plugin that preserves trademarks in German HTML output by adding an extra line to the `<xsl:choose>` group that begins on [Line 1150](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl#L1150):

```xsl
<xsl:when test="$parentlang = 'de-de' or $parentlang = 'de'">tm</xsl:when>
```

This works well enough for now, but the client anticipates additional localizations, so I'd rather not revisit this for each new language.

Can we just eliminate the conditional code in this template and pass trademarks through as authored like in PDF output?

**Comment by jelovirt** [comment]
:+1:
