### ISSUE TITLE
PDF index should not drop terms based on first character

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2071]
Index sorting in PDF2 is based on groups with specified characters. If a primary index begins with a character from a group, it goes in that group. If the starting character is not part of a group, the term is dropped with an error message. For example, all of the following are dropped from English indexes:
```xml
<indexterm>© copyright sample</indexterm>
<indexterm>пример</indexterm>
<indexterm>Å and other accents</indexterm>
<indexterm>Übersample</indexterm>
```

Rather than dropping terms, we should move unexpected terms to the "Special characters" section of the index. We should keep a message but maybe lower to Info level (sometimes useful to know, as in the second two samples, but often the correct behavior, as in the first).

I've got this working when the index grouping file consistently uses the key "Specials" for the group that includes special characters. This is inconsistent today; some use it, some have no key for the group, some translate the key. The key itself is just an ID, and never appears in rendered output; as part of this, I plan to add that specific key to the special character group in all languages. 

If the sort can't find that key, I think the only option is to continue the current behavior (drop the term, with an error). We could create another group with the key, but that would give bad results if the group already exists using a different key (presumably, part of a plugin or customization dir that already modifies the sort).

**Comment by robander** [comment]
Looks like the key was missing for DE, IT, FR, was in Chinese for zh-TW, and was "/" for JA. I'll update all of those to use the key Specials.

**Comment by robander** [comment]
@infotexture this feature adds a message to the message guide, not sure if additional updates are necessary? Message is just that a term has been moved to the "Special characters" section of the index.

**Comment by infotexture** [comment]
No further updates necessary. 

The `user-guide/DITA-messages.xml` topic is generated automatically during the docs build and the new message appears there as expected once that runs.
