### ISSUE TITLE
Ambiguous message for example with two titles

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2078]
If in a DITA topic I have an "example" with two titles inside it the warning received from the DITA OT is something like:

     Found more than one title element in a section. Using the first one for the section's title. Make sure that the title you wish to appear as a title is the first one. Then remove other title elements, or change them to a more appropriate element.

We should try to see if we have access to the real element name when giving the warning.

**Comment by robander** [comment]
:+1: The message is called from the context of the element with two titles, so it should be pretty easy to pass in the element name as a parameter. The message is currently the very last template in `dita2htmlImpl.xsl`.

**Comment by robander** [comment]
@jelovirt @infotexture - I just noticed this one, and I think it's a fix to a broken message - marking for 2.2, definitely seems more like a fix than a feature (I'm ready to stop myself adding new features at this point).
