### ISSUE TITLE
Imprecise error message for duplicate keydef

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2079]
I have two keydefs in my DITA Map with the same key like:

```
 <keydef keys="product">
  <topicmeta>
   <keywords>
    <keyword>Oxygen XML Editor</keyword>
   </keywords>
  </topicmeta>
 </keydef>
```

DITA OT complains with:

```
 The key "product" is defined more than once in the same map file. The reference href="null" is ignored.
```

which is quite incorrect in this case, I'm reusing metadata and not references.

**Comment by jelovirt** [comment]
The error message there is very old and should be modified to not use the `href="null"` part.
