### ISSUE TITLE
Extra warnings reported when project using key scopes and branch filtering is published

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2096]
We are using branch filtering and key scopes, I'm attaching a small project:

http://www.oxygenxml.com/forum/files/mobilePhoneBrochure.zip

The published content is correct but the publish process issues warnings like:

       [gen-list] [DOTJ045I][INFO] The key "model" is defined more than once in the same map file. The  reference href="null" is ignored.
       [gen-list] [DOTJ045I][INFO] The key "image" is defined more than once in the same map file. The reference href="image/Syncro_x2000_black.png" is ignored.
      [gen-list] [DOTJ045I][INFO] The key "description" is defined more than once in the same map file. The reference href="null" is ignored.

and:

      [branch-filter] file:/C:/Users/radu_coravu/Desktop/to%20upload/mobilePhoneBrochure/phoneDetails.ditamap:5:46: [DOTJ065W][WARN] Branch filter generated topic topics/specifcations.dita used more than once. Renaming topics/specifcations.dita to topics/specifcations-1.dita.
      [branch-filter] file:/C:/Users/radu_coravu/Desktop/to%20upload/mobilePhoneBrochure/phoneDetails.ditamap:6:55: [DOTJ065W][WARN] Branch filter generated topic topics/colors-and-accessories.dita used more than once. Renaming topics/colors-and-accessories.dita to topics/colors-and-accessories-1.dita.

The first set of messages received in the gen-list stage seems incorrect. The "model" key for example is defined twice but in different key scopes:

    <map>
     <title>Mobile Phone Brochure</title>
     <topicref href="phoneOverview.dita" keyscope="X1000Scope">
      <keydef keys="model">
       <topicmeta><keywords><keyword>X1000</keyword>        </keywords>       </topicmeta>
      </keydef>
      ......
     </topicref>
     <topicref href="phoneOverview.dita" keyscope="X2000Scope">
      <keydef keys="model">
       <topicmeta>        <keywords>         <keyword>X2000</keyword>        </keywords>      </topicmeta>
      </keydef>
      ......
     </topicref>
    </map>

The second set of messages I think is not necessary. The feature works as it should, it renames topics in various context. So I don't think it should advertise this as a warning. It should probably report nothing in this case.

**Comment by jelovirt** [comment]
@robander, what's your take on DOTJ065W, should it be a warning or info message. IIRC the spec doesn't say anything about the note level, just that message should be logged.

**Comment by jelovirt** [comment]
WRT DOTJ045I, that's old code. We still read keys _without_ scope information in the beginning of processing, because subject schemes use that. To implement both subject scheme filtering and key scopes, we'd need to move subject scheme filtering to take place after key resolution. But, this means _normal_ filtering will take place after that too.

This is a large refactoring that may break existing content due to processing order in filtering.

**Comment by raducoravu** [comment]
How about if at the stage of subject scheme processing those duplicate key warnings would not be issued at all? If there is a real problem would they still be issued as warnings in later stages?
I also wonder how subject schemes fit into this whole key scope idea.

**Comment by infotexture** [comment]
Regarding **DOTJ065W**: I think the current warning level is a bit much. 
Seems to suggest something's wrong when this is actually intended behavior.

We may want to extend the message _(and/or docs)_ to mention that users can use `<dvrResourcePrefix>` & `<dvrResourceSuffix>` to control renaming — and avoid this message.

**Comment by jelovirt** [comment]
IMO the error/info messages should not start describing how to fix something. That's the role of the docs.

**Comment by raducoravu** [comment]
Great, thank you.

**Comment by raducoravu** [comment]
+1
Another one of our users is properly using keys with key scopes and receives errors like this one:

             [gen-list] [DOTJ045I][INFO] The key "keyName" is defined more than once in the same map file. The reference href="null" is ignored.

In my opinion this information message could be removed completely. Even if the end user is not using key scopes, there is no problem when you have the same duplicate key, the specs tells precisely what should happen in these cases.

My problem is that there are other information messages which are important and indicate problems like this one:

                [DOTJ048I] Unable to find key definition for key reference "key_name" in scope "scope_name. The href attribute may be used as fallback if it exists

so I cannot advice the end user to just ignore all information messages.

**Comment by jelovirt** [comment]
@raducoravu could you open a new issue for removal of `DOTJ045I`.

**Comment by raducoravu** [comment]
Here we go: https://github.com/dita-ot/dita-ot/issues/2857
