### ISSUE TITLE
The HTML output for caution/danger notes differs from the one of the other type of notes

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2100]
This issue was reported by a users on the oXygen forum:
https://www.oxygenxml.com/forum/topic12547.html

There seems to be an inconsistent output for some kind of notes. For instance, if we have the next snapshoot in a topic:
```xml
<note type="important">Important node.</note>
<note type="warning">Warning note.</note>
<note type="caution">Caution note.</note>
```
in the HTML output we'll get:
```xml
<div class="note important">
   <span class="importanttitle">Important:</span> Important node.
</div>

    <div class="note warning">
        <span class="warningtitle">Warning:</span> Warning note.
    </div>

    <div class="cautiontitle">CAUTION:</div>
    <div class="note caution">Caution note.</div>
    
    <div class="dangertitle">DANGER</div>
    <div class="note danger">Danger note.</div>
```
Our user is complaining that having no parent container for caution and danger makes it a bit complicated to style HTML output. 

Analysing the stylesheet 'plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl', there seems to be different processing from caution and danger notes.
https://github.com/dita-ot/dita-ot/blob/hotfix/1.8.6/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl#L666

Could you explain what was the reason for this different processing. Is it better to include the `<div class="note caution">` in the `<div class="cautiontitle">`?
```xml
<div class="cautiontitle">CAUTION:
    <div class="note caution">Caution note.</div>
</div>
```

**Comment by jelovirt** [comment]
Taken into account in HTML5, will not be fixed in XHTML.

**Comment by ak-ldube** [comment]
This is also a problem in the CHM output but ONLY for Caution in the CHM output.

`            <div class="note tip"><span class="tiptitle">Tip:</span> 
               <p class="p">tiptiptiptiptiptiptiptiptiptiptiptiptiptiptiptip.</p>

            </div>

            <div class="cautiontitle">CAUTION:</div><div class="note caution">
               <p class="p">cautioncautioncautioncautioncautioncautioncautioncaution</p>

            </div>

            <div class="note warning"><span class="warningtitle">Warning:</span> 
               <p class="p">warningwarningwarningwarningwarningwarningwarningwarningwarning</p>

            </div>

            <div class="note note"><span class="notetitle">Note:</span> 
               <p class="p">notenotenotenotenotenotenotenotenotenotenotenote</p>

            </div>`

Dita version in image
![image](https://user-images.githubusercontent.com/72398301/129955859-533499fa-858d-4c03-89e7-cd442bbd09bc.png)
