### ISSUE TITLE
installing plugins from directory missing

### ISSUE THREAD

**Issue by achary** [dita-ot/dita-ot#2106]
It should be possible to install plugins existing in directories outside of dita installation directory:

Proposal:
```
./dita -install /path/to/existing/plugin/directory
```
Such command should not cause plugin to be copied to the plugin directory, but 'register' it and make it simply available.

Niether neccessity of putting them in to dita-otX.Y.Z/plugins/ directory, nor using intermediate ZIP files for that operation seems to be conventient.

**Comment by jelovirt** [comment]
You can already add additional plugins root directories with `plugindirs` property. Closing as won't fix to avoid feature creep in dita command.
