### ISSUE TITLE
gradle build fails with 'Could not load FFI Provider ..' on Windows

### ISSUE THREAD

**Issue by ropley** [dita-ot/dita-ot#2108]
Cloned the develop repository, updated the submodules and ran ./gradlew. I got the error below. Googling suggests its a jruby configuration problem but I'm not clear about how jruby is configured for this project.

    $ ./gradlew
    :compileJava 
    warning: [options] bootstrap class path not set in conjunction with -source 1.7
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details. 
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    ... some lines skipped
    ERROR:  Loading command: install (LoadError)
    Could not load FFI Provider: (NotImplementedError) FFI not available: null
    See http://jira.codehaus.org/browse/JRUBY-4583
    ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
                                                                               :
    html5:compassCompile                                                           FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':html5:compassCompile'.
    > Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished wi
    th non-zero exit value 1

**Comment by ropley** [comment]
... it works fine on Linux :0)

**Comment by eerohele** [comment]
This is a problem with the Gradle Compass plugin. See https://github.com/robfletcher/gradle-compass/issues/37 and https://github.com/robfletcher/gradle-compass/issues/39.

[This comment](https://github.com/robfletcher/gradle-compass/issues/37#issuecomment-87546969) suggests a workaround.

**Comment by jelovirt** [comment]
Can someone with Windows test the workaround in OT's gradle configuration and verify it would work?

**Comment by eerohele** [comment]
>Can someone with Windows test the workaround in OT's gradle configuration and verify it would work?

Works for me.

**Comment by jelovirt** [comment]
@eerohele could you fix and push to `develop` directly, no PR needed.
