### ISSUE TITLE
Topic in temp folder is generated not wellformed for XHTML output [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2109]
The sample contains a DITAVAL, a DITA map and a simple topic with two inner topics. The [content](https://www.oxygenxml.com/forum/files/filterNotWellformed.zip) is published by applying the DITAVAL filter:

```xml
<val>
  <prop att='product' val='mnr' action='include'/>
  <prop att="audience" val="internal" action='exclude'/>
</val>
```

The received error is something like:

>[move-meta] Error on line 4 column 959 of test.dita:
[move-meta]   SXXP0003: Error reported by XML parser: Attribute "ditaarch" bound to namespace
[move-meta]   "http://www.w3.org/2000/xmlns/" was already specified for element "topic".

and if you look in the temporary files folder the test.dita contains the `ditaarch:version` attribute defined twice on it.

Tested with DOT 2.1.2.

**Comment by jelovirt** [comment]
@raducoravu could you add the DITAVAL, it's missing from the ZIP. Also, does this occur in 2.0, 2.1, or develop version?

**Comment by raducoravu** [comment]
Tested with DOT 2.1.2.

DITAVAL contents:

    <val>

	   <prop att='product' val='mnr' action='include'/>

	   <prop att="audience" val="internal" action='exclude'/>

     </val>

**Comment by eerohele** [comment]
I can't reproduce this on OS X or Windows.

**Comment by jelovirt** [comment]
@eerohele on 2.1 or develop?

**Comment by eerohele** [comment]
Ah, 2.1.2. I can reproduce it with the `develop` branch.

**Comment by jelovirt** [comment]
`ProfilingFilter` doesn't correctly handle namespace prefix mapping. Fixed but will still have to write unit tests to verify the code is correct.

**Comment by raducoravu** [comment]
Great, thanks for the fix. I will also test it on my side with the user's samples.
