### ISSUE TITLE
Validation errors/warning in XSL-FO generated using DITA OT

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2110]
I generate PDF from a sample DITA Map using DITA OT 2.x (but probably it's the same issue with older versions). The PDF is generated succesfully. But if you open the XSL-FO file, it has lots of problems reported in it. And they seem to be quite easily fixable.

Like:

```
 <fo:wrapper id="tasks:_unique_d87e216"/>

 Description: value of attribute "id" is invalid; must be an XML name without colons
```

We should try to avoid ":" when constructing such ID attributes.

```
 <fo:basic-link color="blue" font-style="italic"
                                              internal-destination="flowers:autumn:chrysanthemums:_unique_d87e988"

value of attribute "internal-destination" is invalid; must be an XML name without colons
```

Same thing again, colons in ID references.

```
  <fo:page-number-citation
                                              ref-id="flowers:autumn:chrysanthemums:_unique_d87e988"
                                              />
```

Same thing again, colons in ID references.

```
    <fo:list-item-label end-indent="label-end()"
                                keep-together.within-line="always"
                                keep-with-next.within-line="always">

 Error: attribute "keep-with-next.within-line" not allowed here
```

The specs seems not to allow that attribute there.

**Comment by jelovirt** [comment]
That looks like indexing code. Instead of colon we should use e.g. code point from Unicode private use area, that way we're pretty sure delimiter will not clash with index key value.

**Comment by raducoravu** [comment]
Sure, as long as it remains a valid ID value. Or use instead of it some pattern like "-.-" or "-_-"

**Comment by jelovirt** [comment]
Since in theory it's possible that an index term may use "-.-" in the key, IMO it's better to just use [a code point from PUA](https://en.wikipedia.org/wiki/Private_Use_Areas), e.g. simply `&#xE000;`

**Comment by robander** [comment]
Ran across this when trying to debug a crash during my PDF build -- the PDF is 1500+ pages with 25+ pages of index, and the log is so full of errors about `:` that I can't find the actual errors. I tried replacing every one of the `:` characters in an index with `&#xF000;` as suggested and AH didn't like that character either --
`AHFCmd :WARNING: Invalid property value: id="publications_unique_d117e24383".`

**Comment by robander** [comment]
Thought I had a relatively easy fix with the commit above -- turn the full term into a hash, which replaces any special characters that might be invalid (I found a lot of them, with spaces, slashes, parens, etc). But somehow turning it into a hash breaks the `index-see-also` processing that comes later in XSLT.

**Comment by raducoravu** [comment]
Maybe you can try an easier fix and replace ":" and maybe some other characters with underline both in the Java code and in the XSLT which looks for it. Even if the original index key value contains an underline, I do not see a reason why this would not work.

**Comment by robander** [comment]
It should work for the simple case - what I discovered with this specific document is that we have index entries full of characters that are not valid in IDs, and I was trying for a simple solution that handled all of these. For example, the document I was working with here had several thousand index terms, and most of them still reported errors after removing `:` because they had commas or spaces. I definitely don't want to have to handle 100 cases of "If I find `x` replace with `y`" so the hash initially seemed like a good way to guarantee a valid ID.

**Comment by robander** [comment]
(Initially I just tried to fix the FO file by replacing `:` ... then spaces ... then commas ... and then `(` and `)` showed up ... then slashes ... then I stopped looking for new ones, that could go on for a long time and still not be complete.)

**Comment by raducoravu** [comment]
Maybe replace all non alphanumeric chars with underline.
