### ISSUE TITLE
Third relcolspec title on a reltable no longer taken into account for publishing [DOT 2.1.2]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2119]
I'm attaching a sample project:
https://www.oxygenxml.com/forum/files/reltableColspecProblems.zip

It defines a reltable with three columns and distinct names for each column specified in the relheader:

     <relheader>
      <relcolspec type="topic" processing-role="normal">
       <title>Data</title>
      </relcolspec>
      <relcolspec type="topic" processing-role="normal">
       <title>Format</title>
      </relcolspec>
      <relcolspec type="topic" processing-role="normal">
       <title>Support</title>
      </relcolspec>
     </relheader>

After publishing to XHTML the "test.html" HTML file should have two related link sections, one for "Data" and one for "Support".
This works with DITA OT 1.8.5.

**Comment by raducoravu** [comment]
The problem is in the method:
org.dita.dost.module.MoveLinksModule.getMapping(Document)

which at some point does something like:

                Node c = maplink.getFirstChild();
                while (c != null) {
                  Node removedChild = maplink.removeChild(c);
                    stub.appendChild(removedChild);
                    c = c.getNextSibling();
                }

That code does not properly work, it works only on the first iteration, once the child is removed its next sibling reference it also reset.

Suggested fix:

                Node c = maplink.getFirstChild();
                while (c != null) {
                  Node nextSibling = c.getNextSibling();
                  stub.appendChild(maplink.removeChild(c));
                  c = nextSibling;
                }

**Comment by raducoravu** [comment]
Looking in the code for similar potential problems, in the MapMetaReader.removeIndexTermRecursive we have a for loop:

     for (int i = 0; i < children.getLength(); i++) {

in which children are removed from the parent. As the value returned by "children.getLength()" is potentially modified (decreased) on every iteration it might be possible that not all children are properly processed because the "i" index keeps increasing while the length keeps decreasing.
Usually in such cases in which there are side effects I iterate starting from the last child down to the first one like:

   for (int i = children.getLength() - 1; i >= 0; i--) {

**Comment by jelovirt** [comment]
Yet another reason to favor immutable structures and return copies. The easiest way to handle this in a readable way would be to create a `List` of child nodes and then go through that list, not `NodeList`.

**Comment by raducoravu** [comment]
Xerces is highly optimized in terms of memory efficiency. It usually returns as lists wrapper projections over the real content.

**Comment by jelovirt** [comment]
IMO, the problem here is DOM, which is bad API in all languages it's been ported to. Also, it favors live and mutable objects, when in most cases we would prefer to use an immutable tree model.

**Comment by raducoravu** [comment]
Great, thanks Jarno.
