### ISSUE TITLE
Branch filtering and keyrefs [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2120]
If in the DITA Map has in it a construct like:

    <topicref keyref="topicKey">
      <ditavalref href="filter.ditaval"/>
    </topicref>

the DITAVAL filter will not get applied on the referenced topic.
From what I've seen the branch filtering stage seems to be applied before resolving keys and this might be the reason for it.
If you want and if it is not a known issue I can try to provide a complete sample for this.

**Comment by jelovirt** [comment]
Yes, branch filtering takes place before key resolution. This is because ditavalref can change the key scope name and DITA-OT has not support for delayed branch filtering.

In the future this may change, but the initial DITA 1.3 implementation has this limitation.
