### ISSUE TITLE
Separate all transtype plugins into own Git repos

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2121]
Separate all transtype, i.e. all other than `org.dita.base` into separate Git repositories. This will allow developing each transtype with its own release cycle.

**Comment by raducoravu** [comment]
Would it mean that we would have to check out about 10 repositories in the same folder and update those individually?

**Comment by jelovirt** [comment]
Which role do you mean? OT developer, plugin developer, or end user?

For OT developer, it may be convenient to check those out to `plugins`, but that's for 2-3 people in the world.

**Comment by raducoravu** [comment]
End user who sometimes builds custom DITA OT distributions from the develop branch.

**Comment by jelovirt** [comment]
They can build a distribution using the normal distribution targets. But those users are not "end users" in my terminology, they're developers.

**Comment by raducoravu** [comment]
Maybe you could do that based on particular use cases only for particular plugins. Possibly for most plugins there would be no such necessity.

**Comment by xephon2** [comment]
I really like the idea of extracting the plugins to separate repositories. It would be more elegant for developers. But I recommend to rework the concept of how plugins are organized. I sometimes click through Git repos and sometimes I find a plugin and think, 'damn someone already did what I'm currently developing'. So I would really appreciate a kind of repository and a mechanism, that resolves [Plugin dependencies](http://www.dita-ot.org/2.1/dev_ref/plugin-dependencies.html), something like Maven Central. The DITA-OT should than get an `install plugin` command, that resolves the dependencies and than clones the plugin. I like the concept of [makepkg](https://wiki.archlinux.org/index.php/Makepkg) with small install scripts. A plugin could have a small install script, that resolves its dependencies and clones the plugins directly from Git. So Git would become an integral part of the DITA-OT (like Ant/Gradle). All popular plugins could be listed in a small repository file with their Git clone URLs. It would be even nicer, if you would be able to rate and comment those plugins...

Well, that's a little off-topic, but **please do not only extract the plugins without implementing a repository concept**. This would indeed facilitate the workflow for developers but complicate the workflow for the end users. For me, an end user can publish a DITA Map and install a plugin with `dita -install`. An end user does not understand what a dependency is and how to manually resolve them by cloning, packaging and installing plugins!

I'd definitely like to contribute...

**Comment by jelovirt** [comment]
The problem with the plugin repository is old and the team has gone through the discussions multiple times. If we establish a repository, we have to maintain it and also verify that no malicious plugin gets in. Due to limited resources, we haven't wanted to get into the repository game. #1971 is the current placeholder for the plugin directory feature.

IMO moving the plugins into separate Git repos should not rely on a plugin repository, since all those plugins can still be installed with a URL to the distribution package.

**Comment by jelovirt** [comment]
@xephon2, note that "end users" would never see this change, as the normal DITA-OT distribution package would still ship with the built-in plugins. This would only effect the version management and distribution build, not _use_ of DITA-OT.

**Comment by sebschmied** [comment]
Hi, I'm one of these "end users building directly from dev branch". If I get this right, seperating the plugins shouldn't be a problem since you can still keep them up-to-date using `git submodule update -r`, right?

**Comment by jelovirt** [comment]
@sebschmied the repo in Github would not be using submodules, but locally submodules could be used if it makes development easier.
