### ISSUE TITLE
Use Guava 

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2122]
Take [Guava](https://github.com/google/guava) into use. Main features to use include better collections and Optional before Java 8.

**Comment by jelovirt** [comment]
Adding Guava had to be reverted because Travis CI builds started to fail. There was some interaction between the Guava version that was used as a dependency and one that Gradle itself uses.

**Comment by jelovirt** [comment]
@eerohele Currently the only reason why we can't use Guava is that Gradle uses Guava too and when we try to run OT during dist build, things break. How about we refactor the Gradle build to handle the dist a bit differently. Instead of running integrator and docs build in the same JVM as the rest of the build, we fork a new JVM for gradle and docs build. That way we would not have to patch the [classloader][1] and we could take Guava into use.

[1]: https://github.com/dita-ot/dita-ot/blob/develop/build.gradle#L165

**Comment by eerohele** [comment]
I was actually looking into a similar problem with the DITA-OT Gradle Plugin yesterday: I discovered that Gradle bundles a fairly old version of `commons-io`, and my plugin uses a newer version of the same library. The older version of `commons-io` has a private method that was made public in later versions, and apparently the classloader randomly picks which version of `commons-io` to use, leading to spurious build errors when the daemon is enabled.

I can look into refactoring the Gradle buildfile when I get the chance.
