### ISSUE TITLE
Index page should contain link to page also for parent indexterm

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2126]
Let's say I have a DITA topic with a prolog like:
```xml
<prolog>
  <metadata>
    <keywords>
      <indexterm>Info<indexterm>Locale</indexterm></indexterm>
    </keywords>
  </metadata>
</prolog>
```
and I publish to PDF using Apache FOP. In the index page the "Info" word has no page link next to it, only the sub index "Locale" term does.
When publishing with XEP, both index terms have the page link next to them.

**Comment by raducoravu** [comment]
At some point in the XSLT:

plugins/org.dita.pdf2/xsl/fo/index.xsl

there is an xsl:if:

     <xsl:if test="contains($isNormalChilds,'true ')">

which applies templates in a certain mode:

     <xsl:apply-templates select="." mode="make-index-ref">

We could add to that apply-templates an extra parameter:

        <xsl:with-param name="idxs" select="opentopic-index:refID"/>

because it is used to generate the link in the index_fop.xsl stylesheet.
This does not seem to influence XEP because it overrides this base template completely in the index_xep.xsl.

**Comment by raducoravu** [comment]
I could issue a pull request if you agree with my proposed solution.

**Comment by jelovirt** [comment]
:+1: for PR.

**Comment by raducoravu** [comment]
Does the fix look right or should I close the pull request?

**Comment by robander** [comment]
I'm not sure what to think about this one. The behavior you describe for FOP above is the one I've always assumed correct (it is the design I've been given for various index programs in IBM). But, I'd also like the outputs to be consistent.

**Comment by raducoravu** [comment]
No problem, you can choose to close and not merge this one, we'll see if we have future feedback from others regarding this behavior.

**Comment by robander** [comment]
There is a related issue #1903 that suggests merging the parent/child into one line for this case, rather than adding the page number to the parent. I don't have strong feelings for or against that request - if it came with a pull request, I'd probably be fine with it - but I generally think that would be a better approach than duplicating the page number.

**Comment by jelovirt** [comment]
I agree with @robander here, there should not be two page numbers, especially with the original example. If the example was

```xml
<prolog>
  <metadata>
    <keywords>
      <indexterm>Info</indexterm>
      <indexterm>Info<indexterm>Locale</indexterm></indexterm>
    </keywords>
  </metadata>
</prolog>
```
that would be a different case.

**Comment by drmacro** [comment]
At least with the way I've always done index construction and page number generation, Jarno's last example would still result in Info/Locale, with one set of page number references, for Locale. Not Info and Info/Locale.

That is there is only one entry for Info in the index and it has (based on this example), one secondary entry, Locale.

Having page number references for non-leaf items is clearly an editorial choice but I would not consider it to be normal practice. Unfortunately I don't have my Chicago Manual to hand but that would certainly be my first choice of authority.

**Comment by jelovirt** [comment]
CMOS doesn't have items like these in it's own index and AFAICT the index they recommend would not have the duplicate page numbers.

Closing this PR and original issue.
