### ISSUE TITLE
PDF: Missing variables in localizations

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2131]
Several of the variables that are available in [common/vars/en.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/common/vars/en.xml) are missing in other languages.

For example, the German variant does not include the following variables:

	<variable id="Table of Contents Notices">
	<variable id="Notices title">
	<variable id="Child topics">
	<variable id="Related references">
	<variable id="Index multiple entries separator">
	<variable id="Online Help Search Method Field">, etc.

When continuing the localization harmonization process from #2085 & #2089, the missing variables should be synced to the remaining localizations where possible and appropriate.

**Comment by jelovirt** [comment]
Actually, e.g. `Online Help Search Method Field` should removed from English variable files as it's obsolete. I haven't removed them in the slight case that someone is actually using them.

Instead of adding those variable to all languages, we should instead check which variables are not used and remove them.

**Comment by infotexture** [comment]
:+1:

**Comment by robander** [comment]
The variable `<variable id="Table of Contents Notices">` was added (with no value) with #2343 - that string is used by PDF and generated an error when undefined. 

The missing "Notices title" does not generate an error. I'm not sure why; without searching, best guess is that the code tries to use the TOC version both in the TOC / Bookmarks and in the content.

All instances of the "Online help" related variables are marked deprecated with #2383.

"Child topics" and "Related references" are not marked deprecated. I'm pretty sure that we do not use them in any location, but was not confident enough to mark them "Deprecated" this close to the release boundary.

**Comment by robander** [comment]
Fixed with b53f3f9 - I've added the three variables "Notices title", "Child topics", and "Related references". I did not bother to add the Online help variables, which have now been marked deprecated in all other languages.
