### ISSUE TITLE
Relative path for `args.hdr` treated as absolute

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2133]
When I specify a running header file for the docs `html` target with

    <property name="args.hdr" value="resources/header.xml"/>

the build process throws an error, because it looks for the header file in the wrong place:

     Error! java.io.FileNotFoundException: /resources/header.xml (No such file or directory) 

The value is prefixed with an extra slash and treated as an absolute path, although the initial `echo` suggests the value was parsed properly as a relative path _(without the slash prefix)_:

     [echo] args.hdr=resources/header.xml

When I [add](https://github.com/infotexture/docs/commit/1c5b0803d54d4a5fb6662a5017c1733cdef4289a) the `${basedir}/` prefix to the `args.hdr` value, the header file is properly resolved:

    <property name="args.hdr" value="${basedir}/resources/header.xml"/>

This extra step shouldn't be necessary, since the build file sets the `@basedir="."`, so I would assume all paths to be resolved relative to the location of the build file.

The source files are available for testing at https://github.com/infotexture/docs/tree/feature/args-hdr-test.

**Comment by jelovirt** [comment]
The `args.hdr` and `args.ftr` have always required an absolute path, so this is not an implementation bug. The documentation should probably mention this requirement.

**Comment by jelovirt** [comment]
Regardless whether the parameters should accept a relative path and what the relative path should be, the implementation for header and footer injection is really old and poor quelity. The code should be refactored to follow the current approaches to handling these types of things.
