### ISSUE TITLE
HTML output discards @othertype note titles

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2136]
Given a `<note>` of `@type=other`, the user-specified note title defined in the `@othertype` attribute is missing in HTML output, but retained in PDF output.

```
<note type="other" othertype="Update">Note text.</note>
```

This renders as expected in PDF:

> **Update:** Note text.

In HTML output, the note title is missing:

```
    : Note text.
```

The generated HTML source reveals that the `@othertype` attribute is included on the `<span>` element, but only the colon character appears in the span content:

```
<div class="note note note_note">
  <span class="note__title notetitle" othertype="Update">:</span> Note text.
</div>
```

**Comment by robander** [comment]
I think this one is obsolete - when I have anything in the `@othertype` attribute, it appears in both XHTML and HTML5 using the same style as other note elements. In both cases:
`<note type="other" othertype="My other type">other note here</note>`
results in
**My other type:** other note here
