### ISSUE TITLE
Run dita command using java headless mode

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2140]
On OS X (also Windows?), running DITA builds annoyingly steals the focus when the java process is started. However, java can be run in headless mode and not do this. Headless mode also consumes fewer system resources, and as far as I can tell there's no reason not to build in headless mode.

To do this now, users need to set ANT_OPTS before running the dita command:
```export ANT_OPTS="$ANT_OPTS -Djava.awt.headless=true"```

We could improve the dita command by running java in headless mode by default. If there's a reason why headless mode might be problematic for some users, we could add a build flag "--not-headless" to override this behavior.

**Comment by raducoravu** [comment]
+1, we also run the DITA OT Java process headless when running it from Oxygen.

**Comment by jelovirt** [comment]
This should be added to `dita` command and our build scripts, but not to e.g. `startcmd.*`.
