### ISSUE TITLE
Add configuration for SAX pipes

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2144]
Add support for configuring SAX pipes in Ant `<pipeline>` task. The configuration syntax could look something like:

```xml
<pipeline message="Resolve topic fragment." taskname="topic-fragment">
  <sax>
    <filter class="com.example.filter.FooFilter"/>
    <filter class="com.example.filter.BarFilter">
      <param name="bar" expression="true"/>
      <param name="baz" expression="true" if="baz.skip"/>
    </filter>
    <filter class="com.example.filter.BazFilter" singleton="false" unless="baz.skip"/>
  </sax>
</pipeline>
```

* All filters must implement [`AbstractXMLFilter`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/AbstractXMLFilter.java)
* Filters are singleton by default

**Comment by jelovirt** [comment]
After the initial implementation, the code could be extended to also allow XSLT stylesheets as filters.

**Comment by raducoravu** [comment]
Could this extension be possibly used to implement a plugin which would fix references which point to resources outside of the DITA Map folder? 
So while a topic is parsed and the extensions detects a reference to a file outside of the dita map folder (even on another drive), it could for example copy it to the temporary files folder to a special folder (some kind of unique name) and fix that reference to point to the copied file?
