### ISSUE TITLE
Footnote in table header cell not properly displayed in PDF output

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2145]
If in my DITA table in the header part one of the cells defines a footnote:

                    <thead>
                        <row>
                            <entry>E1<fn>THIS IS FN</fn></entry>
                            <entry>E2</entry>
                        </row>
                    </thead>

in the generated PDF the foot note text does not appear at the end of the page. 
This can be reproduced with both DITA OT 1.8 and 2.x.

**Comment by eerohele** [comment]
If you're using FOP, this is probably a duplicate of #1220.

**Comment by raducoravu** [comment]
Right, thanks Eero. 
Indeed the XSL-FO structure seemed to be fine. And I confirm this works in XEP.
I'll close this one.
