### ISSUE TITLE
Disable PDF2 I18N processing as default

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2152]
Disable PDF2's I18N font processing as a default and move physical font configuration into XSLT.

**Comment by robander** [comment]
As I've been adding new languages, I've been creating new files in the `i18n` directory that I think are related to this. I'm not sure how they are used by the I18N processing, but have followed existing patterns in creating them. Do you know yet if these will need to change, or will they simply become obsolete?

**Comment by jelovirt** [comment]
They will become obsolete for the default configuration, but I18N can still remain in PDF2, since it's the only solution for some complex use cases.

**Comment by jelovirt** [comment]
Not sure if we can do this after all just because it would break plugin font configuration. It's likely better we document that I18N processing should be disabled.
