### ISSUE TITLE
PDF title metadata is not generated correctly when a DITA map document has xml:lang attribute set

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2154]
Let's consider a sample DITA Map:
```
<map title="цветы" xml:lang="ru-ru">
  <topicref href="topics/introduction.dita"/>
</map>
```
I've transformed the map to PDF using **pdf2** transformation. After that, I've loaded the PDF in the **Adobe Reader** and I've displayed the **Document Properties** dialog. 
In the **Document Properties** dialog the document title is not displayed correctly. It is displayed the label **XMP structure: 1** instead of the map title.

I've analyzed a bit the PDF transformation and I've noticed that the **x:xmpmeta//dc:title** element from the **topic.fo** document contains **fo:inline** elements.
```
<x:xmpmeta>
      <rdf:RDF>
        <rdf:Description rdf:about="">
          <dc:title line-height-shift-adjustment="disregard-shifts">
            <fo:inline line-height="100%" font-family="Times New Roman, Times">цветы</fo:inline>
          </dc:title>
          <xmp:CreatorTool>DITA Open Toolkit</xmp:CreatorTool>
        </rdf:Description>
      </rdf:RDF>
    </x:xmpmeta>
```
I think this could be the reason of the problem because the **Apache FOP** processor is not expected to encounter these elements inside the XMP metadata language.

A solution would be to skip these elements from the **i18n-postprocess.xsl** stylesheet which processed the **stage3.fo** and produces the **topic.fo**
```
<xsl:template match="x:xmpmeta//opentopic-i18n:text-fragment" priority="+10" xmlns:x="adobe:ns:meta/">
<xsl:apply-templates/>
</xsl:template>
```

**Comment by jelovirt** [comment]
The ignore template in the description is not enough, it will also need to ignore `@line-height-shift-adjustment` that a separate template will generate. Maybe the clean up stylesheet should first clean up all incorrectly marked sections and only then handle the font mapping.
