### ISSUE TITLE
"No digits found" when publishing DITA to RTF [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2157]
If in the DITA topic in a table I have a colspec with a fixed value like:

    <colspec colname="c1" colnum="1" colwidth="10px"/>

and I publish to RTF I get:

       [xslt] D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.wordrtf\xsl\xslrtf\dita2rtf-table.xsl:496: Fatal Error! No digits found

**Comment by raducoravu** [comment]
Another user stepped into this problem. Not sure if he has the same situation or not, I will ask.

**Comment by robander** [comment]
This looks very similar to #1190, which is fixed in 2.2.5. Adding the "needs-reproduction" tag to see if this issue is fixed by that update.

**Comment by raducoravu** [comment]
I can confirm fix works.
