### ISSUE TITLE
Make it easier to hide table and figure static texts via CSS

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2160]
Let's say that when the HTML is generated I want that instead of "Table 10: Table Title" displayed for each table to only have the table title present, without that static text in front of it.
Right now I need to perform an XSLT customization for this.
Ideally in the XSLT stylesheet `plugins\org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl` in the places where the following spans are created:
```xml
<span class="figcap">
```
and:
```xml
<span class="tablecap">
````

we would have additional spans with custom class values set around the static table label and numbering.
Something like:
```xml
        <span class="tablecap">
          <span class="tablelabel">
            <xsl:choose>   
             .........
            </xsl:choose>
          </span>
          <xsl:apply-templates select="*[contains(@class, ' topic/title ')]" mode="tabletitle"/>
          <xsl:if test="*[contains(@class, ' topic/desc ')]">
            <xsl:text>. </xsl:text>
          </xsl:if>
        </span>
```
In this way we could hide via the CSS all spans with "tablelabel" and "figlabel" classes and have that static text before the title disappear.

**Comment by eerohele** [comment]
Slightly OT, but for HTML5, `<span class="figcap">` should really be `<figcaption>` and `<span class="tablecap">` should be `<caption>`.

**Comment by raducoravu** [comment]
Thanks @jelovirt and happy indepedence day :)
