### ISSUE TITLE
Small improvement in generated HTML code for unordered related links

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2164]
I would like to request a small improvement for the generated output for the unordered related links. 
More exactly, the improvement is related to the HTML code generated in case the referenced topic has an abstract description.

``` xml
<concept id="summerFlowers">
    <title>Summer Flowers</title>
   <shortdesc>A short description for summer flowers.</shortdesc>
```

This kind of output is generated when the parent topic in the DITA map has the `collection-type` attribute set to `unordered`.

In this case, the HTML output is:

``` xml
<ul class="ullinks">
    <li class="link ulchildlink">
      <strong><a href="../concepts/summerFlowers.html">Summer Flowers</a></strong>
      <br />
      A short description for summer flowers.
    </li>   
</ul>
```

Could we change the output in order to wrap the abstract description text in a `div` element? 
This would also be helpful when you want to change the CSS style for the abstract text.

Moreover, when the value of the attribute `collection-type` is set to sequence, an order list is generated for the related links. Something similar with:

``` xml
<ol class="olchildlinks">
  <li class="link olchildlink">
    <a href="../concepts/summerFlowers.html">Summer Flowers</a>
    <div>A short description for summer flowers.</div>
  </li>
</ol>
```

As you can observe, in this case, the text for abstract description is wrapped in a `div` element. So, there is also an inconsistency between the generated output for the ordered and unordered related links.

**Comment by jelovirt** [comment]
:+1:

**Comment by robander** [comment]
:+1:

**Comment by robander** [comment]
Just checked on this one again and I see that in both XHTML and HTML5, the ordered *and* unordered links come out with a `<br/>` before the short description. So, this seems to have gone a bit backwards.

**Comment by robander** [comment]
Looks like the commit https://github.com/robander/dita-ot/commit/b4ef3979398a801a68636e91e952120e4ca2c9ff fixes this for both XHTML and HTML5, but a bunch of `integrationTest` cases need to be tweaked before it can be merged.
