### ISSUE TITLE
Wrong key for dita format entries in configuration file

### ISSUE THREAD

**Issue by georgebina** [dita-ot/dita-ot#2166]
The /dita-ot/src/main/java/org/dita/dost/util/Configuration.java file checks for a key starting with "parser." for DITA format values - the same is done for obtaining the parser map, so it looks like a copy/paste error. I do not know what it should be the actual value the code should check for. 
```
public static final Set<String> ditaFormat;
    static {
        final Set<String> s = new HashSet<>();
        for (final Map.Entry<String, String> e: configuration.entrySet()) {
            final String key = e.getKey();
            if (key.startsWith("parser.")) {
                s.add(key.substring(7));
            }
        }
        ditaFormat = Collections.unmodifiableSet(s);
    }
```

**Comment by jelovirt** [comment]
I can't see where there's a bug and what doesn't work. Could you elaborate on the issue?

**Comment by georgebina** [comment]
Sorry, my mistake. It looked like the values set in ditaFormat were the same as the ones from the parserMap but I see that they are different.
