### ISSUE TITLE
DOTX012W appears in DITA-OT 2.2.0

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2169]
I probably have a mistake in my customization and get many of these errors:

```
[DOTX012W]: When you conref another topic or an item in another topic, the domains attribute of the target topic must be equal to or a subset of the current topic's domains attribute. Put your target under an appropriate domain. You can see the messages guide for more help.
```

The docs say in the explanation of [DOTX012W](http://www.dita-ot.org/2.2/user-guide/DITA-messages.html)`This message is deprecated and should no longer appear in any logs.`

So, there is either a mistake in the code or in the docs. If you need debugging output, please let me know.

**Comment by jelovirt** [comment]
Please create a Gist with a set of files to reproduce the issue.

**Comment by xephon2** [comment]
https://gist.github.com/xephon2/7d848e8ce8d4f35a9c5c

**Comment by xephon2** [comment]
So, the *.mod* file of the first type contained:

```
<!ENTITY % ph                 "ph |
                               %sw-d-ph; | 
                               %ui-d-ph;
                              ">
```

and the *.mod* file of the second topic type contained:

```
<!ENTITY % ph                 "ph |
                               %ui-d-ph;
                              ">
```

I resolved the error in my customization by myself but, as I said, either the docs or the code need a change, depending on whether you want to keep the message. For me it was helpful, so please keep it, if possible.

**Comment by xephon2** [comment]
DITA-OT 2.2.1 is also affected.

**Comment by xephon2** [comment]
The message is confusing here. I had an error in an element constraint. So no DITA-OT issue.
