### ISSUE TITLE
configuration.properties has version as 2.1.2 not 2.2 on develop branch

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2171]
I'm implementing 2.x support for the DITA Community preprocessing extensions. As part of that I use the configuration.properties to get the OT version so I can then condition various version-specific targets.

The 2.2 release and the code on the develop branch set the otversion property to 2.1.2 not 2.2.

**Comment by infotexture** [comment]
This was fixed November 24 on the `hotfix/2.2.1` branch with commit a04f1ac.

The change will land on the `develop` branch when the hotfix branch is merged.
