### ISSUE TITLE
v2.2: Ant fails on Windows

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2172]
Several users have reported `$ANT_HOME` errors with the `dita-ot-2.2.0.zip` distribution package on Windows:

1. Download `dita-ot-2.2.0.zip`.
2. Unpack to `C:\`.
3. Run `startcmd.bat`.
4. Run `ant`.

**RESULT:**

>	ANT_HOME is set incorrectly or ant could not be located. Please set ANT_HOME.

Reproduced on a system where the  `$ANT_HOME` system environment variable was not set manually.

[Line 14 of `startcmd.bat`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/startcmd.bat#L14) still contains `set ANT_HOME=%DITA_DIR%` as in earlier versions, but it seems this is somehow ignored or  overridden in v2.2 — possibly related to the `:stripAntHome` task on [Line 45 of `ant.bat`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/bin/ant.bat#L45)?

**Comment by dagoss** [comment]
I can confirm that this is happening.

It looks like ant.bat is looking for %DITA_DIR%\ant.jar, which existed in OT 2.1.0. In 2.2.0, the ant jar now has the version number (lib\ant-1.9.4.jar), which it didn't before.

Changing ant.bat to look for the jar with the correct name or renaming the ant-1.9.4.jar to ant.jar both seem to fix the problem.

**Comment by jelovirt** [comment]
@dagoss thanks for the reproduction and debugging.
