### ISSUE TITLE
Cannot make conref to step inside DITA composite [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2186]
If I have a DITA composite something like:

            <!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "ditabase.dtd">
            <dita>
                <topic id="topic_rqs_pyy_25">
                    <title></title>
                    <body>
                        <p></p>
                    </body>
                </topic>
                <task id="task_tsn_qyy_25">
                    <title/>
                    <taskbody>
                        <steps>
                            <step id="step">
                                <cmd>Step</cmd>
                            </step>
                        </steps>
                    </taskbody>
                </task>
            </dita>

and in some topic I have a conref to it:

            <step conref="composite.dita#task_tsn_qyy_25/step">
                <cmd/>
            </step>

and publish with DITA OT 2.x the conref is not resolved and in the console I get:

               [conref] Error on line 317 of conrefImpl.xsl:
               [conref]   XTTE0790: A sequence of more than one item is not allowed as the first argument of
               [conref]   conref:isValid() ("(topic task)...", "(topic task)...") 
               [conref]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/conrefImpl.xsl#1212)
               [conref]      processing /task/taskbody[1]/steps[1]/step[2]

As a fix suggestion, in the XSLT stylesheet:

        xsl/preprocess/conrefImpl.xsl

the variable:

    <xsl:variable name="domains" select="document($file, /)/*/@domains | document($file, /)/dita/*[@domains][1]/@domains"/>

should return only the first item in the possible sequence:

    <xsl:variable name="domains" select="(document($file, /)/*/@domains | document($file, /)/dita/*[@domains][1]/@domains)[1]"/>

Of course, if this variable computes the domains of the topic which contains the target elements, it should first find the closest topic which contains the current element and then get the domains attribute value from it.

**Comment by jelovirt** [comment]
This has already been fixed in 2.2.1, see 1088a138dc6e5ff9bf75ad4eacf0075dec42a98a

**Comment by jelovirt** [comment]
The correct fix would be to check the closest topic, as described by @raducoravu

**Comment by raducoravu** [comment]
Thanks Jarno.
