### ISSUE TITLE
Referencing a file outside of the current director causes processing to fail

### ISSUE THREAD

**Issue by dagoss** [dita-ot/dita-ot#2190]
(tested with OT 2.2.1 pdf)

Create a map that references a file above the current directory:

	<map>
		<title>Title</title>

		<mapref href="../common/keydefs.ditamap"/>-->

		<topicref href="topics/topic1.dita"/>
		<topicref href="topics/topic2.dita"/>

	</map>

During processing, you'll get all sorts of errors about "path/to/temp/topics/topic1.dita does not exist or cannot be loaded"

If you looked in the temp/, all of the processed topics are inside a directory named after the build directory. For example, if the above map was built in "myproject/", you would find temp/myproject/topics/topic1.dita instead of temp/topics/topic1.dita that the error message says is missing.

This happens if generate.copy.outer is 1 or 3. It almost seems like generate.copy.out isn't working...

**Comment by dagoss** [comment]
After some further investigation, this seems to have something to do with keydefs/keyrefs. For example, this is OK:

    <topicref href="../common/mytopic.dita"/>

But this fails:

    <keydef keys="mykey" href="../common/mytopic.dita"/>
    <topicref keyref="mykey"/>

This will even fail if the me has nothing to do with the external entity. For example, this fails:

    <keydef keys="mykey" href="topics/mytopic.dita"/>
    <topicref keyref="mykey"/>
    <topicref href="../common/mytopic.dita"/>

**Comment by dagoss** [comment]
I'm attaching a minimal working example that illustrates this issue

[mwe.zip](https://github.com/dita-ot/dita-ot/files/83413/mwe.zip)

I also attempted to build this against OT 2.1.2, and it *does* build successfully with that version (OT2.2.1 was tested on both Windows and Linux; OT 2.1.2 was tested on Linux)

**Comment by eerohele** [comment]
Reproduced and bisected; the bug was introduced in a4952323848288eaac31a13f943cef7bb4494d61.

**Comment by eerohele** [comment]
>Reproduced and bisected; the bug was introduced in a495232.

Well, "bug was introduced" is wrong. The *error messages* appear because of the changes in that commit. The bug seems to be somewhere else, because prior to a495232, the keyrefs in the topicrefs aren't resolved at all, as the commit message for that commit indicates.

**Comment by linok1** [comment]
Does this mean that this issue will be addressed in 2.3 version?

**Comment by jelovirt** [comment]
@linok1 Yes, it should be part of 2.3 release. (Unless we have to revert the change for some reason before the release.)

**Comment by linok1** [comment]
Okay...when  2.3 will be available? Any Tentative dates? Also is there any way to get pre release version of DITA OT. I found zip file on this link https://github.com/dita-ot/dita-ot but i think i cant fire ant or Dita command straight a way on command line. Any tweaking required?

**Comment by jelovirt** [comment]
Late spring.

See [README](https://github.com/dita-ot/dita-ot/blob/develop/README.markdown) for build instructions.
