### ISSUE TITLE
HTML: Short description in <abstract> rendered as <div> rather than <p>

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2191]
If a `<shortdesc>` element directly follows the topic `<title>` element, it appears in HTML output as a standard paragraph:

```html
<p class="shortdesc">…</p>
```
If the short description is wrapped in an `<abstract>` element, a nested HTML `<div>` element is generated for the `<shortdesc>` instead of a paragraph:

```html
<div class="abstract">
    <div class="shortdesc">…</div>
    <p class="p">…</p>
</div>
```

To ensure consistent presentation of short descriptions, they should be rendered as paragraphs within abstracts as well:

```html
<div class="abstract">
    <p class="shortdesc">…</div>
    <p class="p">…</p>
</div>
```

While additional CSS rules can be defined using the `.shortdesc` class selector to align presentation, this extra step should not be necessary. 

It would be preferable to generate consistent markup and render short descriptions as paragraphs in either case, so default user agent stylesheets or existing custom rules for paragraph elements are applied.

**Comment by eerohele** [comment]
I didn't test, but I think the easiest fix is to modify [`dita2htmlImpl.xsl`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl#L430-L451) as suggested.
