### ISSUE TITLE
Conrefs not supported on tgroup elements in DITA-OT 2.2.1

### ISSUE THREAD

**Issue by jlowther** [dita-ot/dita-ot#2192]
When attempting to publish tgroup elements with conrefs using DITA-OT 2.2.1, the processing fails.

Example input: 

```xml
<table frame="all" colsep="1" rowsep="1">
  <tgroup cols="0" conref="../conrefs/c_launching_service.dita#id13B4B0990HK/launch_service_tgroup">
    <tbody>
      <row>
        <entry/>
      </row>
    </tbody>
  </tgroup>
</table>
```

Error message:

> Fatal error during transformation using /Users/jdoe/git/dita-ot-2.2.1/plugins/org.dita.xhtml/xsl/dita2html.xsl: An empty sequence is not allowed as the value of variable $colspec;

**Comment by eerohele** [comment]
I can't reproduce this. @jlowther: could you also post the table whose `<tgroup>` element is the conref target?

**Comment by jlowther** [comment]
tgroup target is as follows:

<table frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" colsep="1" rowsep="1" id="launch_service_tgroup" outputclass="FormatA">
                <colspec colnum="1" colname="1" colwidth="50*"/>
                <colspec colnum="2" colname="2" colwidth="50*"/>
                <thead>
                    <row conref="../../conrefs/c_various.dita#various_conrefs/row_tjf_1vz_zs"
                        rowsep="1">
                        <entry colname="1"/>
                        <entry colname="2"/>
                    </row>
                </thead>
                <tbody>
                    <row rowsep="0">
                        <entry colname="1">Launch the Service</entry>
                        <entry colname="2">In a Web browser, type the URL of the server that is
                            running the Java Web Start service, choose service plug-ins, and click
                                <uicontrol>Launch Service</uicontrol></entry>
                    </row>
                </tbody>
            </tgroup>
        </table>

**Comment by jelovirt** [comment]
Can't reproduce. Could you create a ZIP with complete set of files that will cause error condition?

**Comment by jlowther** [comment]
The error occurs when attempting to build JavaHelp and HTML  Help. Please try building in those formats.

**Comment by jelovirt** [comment]
Can't reproduce with HTML Help.

**Comment by jlowther** [comment]
[doc_testing.zip](https://github.com/dita-ot/dita-ot/files/89634/doc_testing.zip)

Source files as requested.

**Comment by eerohele** [comment]
>doc_testing.zip

I can reproduce the error with those files, but the root cause is not related to the `<tgroup>` element. It's caused by errors like this:

```
   [conref] Error on line 189 of conrefImpl.xsl:
   [conref]   XTTE0570: An empty sequence is not allowed as the value of variable $domains
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#812)
   [conref]      processing /concept/conbody[1]/section[2]/p[26]/ph[1]/ph[1]
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#326)
   [conref]      processing /concept/conbody[1]/section[2]/p[26]/ph[1]
   [conref]   at xsl:for-each (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#322)
   [conref]      processing /
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#1216)
   [conref]      processing /concept/conbody[1]/section[2]/p[1]/ph[1]/ph[1]
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#1216)
   [conref]      processing /concept/conbody[1]/section[2]/p[1]/ph[1]
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#1216)
   [conref]      processing /concept/conbody[1]/section[2]/p[1]
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#1216)
   [conref]      processing /concept/conbody[1]/section[2]
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#1216)
   [conref]      processing /concept/conbody[1]
   [conref]   at xsl:apply-templates (file:/opt/dita-ot/xsl/preprocess/conrefImpl.xsl#30)
   [conref]      processing /concept
   [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
```

The error doesn't cause processing to stop, but it prevents conrefs from being resolved. The `$colspec` error is a side effect of that.

Doing something like this "fixes" the error but doesn't address the root cause:

```diff
diff --git a/src/main/xsl/preprocess/conrefImpl.xsl b/src/main/xsl/preprocess/conrefImpl.xsl
index e410bd4..d7d8dd9 100644
--- a/src/main/xsl/preprocess/conrefImpl.xsl
+++ b/src/main/xsl/preprocess/conrefImpl.xsl
@@ -182,7 +182,7 @@
       </xsl:call-template>
     </xsl:variable>
     <!-- get domains attribute in the target file -->
-    <xsl:variable name="domains" select="(document($file, /)/*/@domains | document($file, /)/dita/*[@domains][1]/@domains)[1]" as="xs:string"/>
+    <xsl:variable name="domains" select="(document($file, /)/*/@domains | document($file, /)/dita/*[@domains][1]/@domains)[1]" as="xs:string*"/>
     <!--the file name is useful to href when resolveing conref -->
     <xsl:variable name="conref-filename" as="xs:string">
       <xsl:call-template name="replace-blank">
```

I'm guessing that the root cause has something to do with how the conref code resolves relative paths, but I didn't get to the bottom of it yet.

**Comment by jelovirt** [comment]
The issue may be that conref target has conref, and the target is in the same document.

**Comment by eerohele** [comment]
>The issue may be that conref target has conref, and the target is in the same document.

It seems to be related to that, but the issue is also related to relative paths / subdirectories.

After a long struggle, I managed to produce a minimal set of files to reproduce the issue:

https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/2192

The conref in `topic1/topic1.dita` doesn't work. The topicref in `topic3.dita` does. The only difference is that `topic1.dita` is in a subfolder, and thus the conref starts with `../`.

**Comment by eerohele** [comment]
The simplest possible fix might be:

```diff
diff --git a/src/main/xsl/preprocess/conrefImpl.xsl b/src/main/xsl/preprocess/conrefImpl.xsl
index e410bd4..51fbf89 100644
--- a/src/main/xsl/preprocess/conrefImpl.xsl
+++ b/src/main/xsl/preprocess/conrefImpl.xsl
@@ -1224,20 +1224,24 @@
   <xsl:template name="get-file-uri" as="xs:string">
     <xsl:param name="href" as="xs:string"/>
     <xsl:param name="file-prefix" as="xs:string"/>
-    <xsl:value-of>
-      <xsl:value-of select="$file-prefix"/>
-      <xsl:choose>
-        <xsl:when test="starts-with($href, '#')">
-          <xsl:value-of select="$file-being-processed"/>
-        </xsl:when>
-        <xsl:when test="contains($href, '#')">
-          <xsl:value-of select="substring-before($href, '#')"/>
-        </xsl:when>
-        <xsl:otherwise>
-          <xsl:value-of select="$href"/>
-        </xsl:otherwise>
-      </xsl:choose>
-    </xsl:value-of>
+    <xsl:choose>
+      <xsl:when test="starts-with($href, '#')">
+        <xsl:value-of select="base-uri()"/>
+      </xsl:when>
+      <xsl:otherwise>
+        <xsl:value-of>
+          <xsl:value-of select="$file-prefix"/>
+          <xsl:choose>
+            <xsl:when test="contains($href, '#')">
+              <xsl:value-of select="substring-before($href, '#')"/>
+            </xsl:when>
+            <xsl:otherwise>
+              <xsl:value-of select="$href"/>
+            </xsl:otherwise>
+          </xsl:choose>
+        </xsl:value-of>
+      </xsl:otherwise>
+    </xsl:choose>
   </xsl:template>
 
   <xsl:template name="get-original-element" as="xs:string">
```

But really, `conrefImpl.xsl` could use quite a bit of refactoring.

**Comment by raducoravu** [comment]
This particular error:

    XTTE0570: An empty sequence is not allowed as the value of variable $domains

was reported and fixed (at least that particular case) here:

https://github.com/dita-ot/dita-ot/issues/2186

**Comment by eerohele** [comment]
>This particular error:
>XTTE0570: An empty sequence is not allowed as the value of variable $domains
>was reported and fixed (at least that particular case) here:
> #2186

This is a different error, though — it still occurs with the `develop` branch.

**Comment by jelovirt** [comment]
The `$domains` problem is caused because the target document cannot be read. Fixing the URI resolution bug with 5215545 seems to fix this issue too with the provided test files.
