### ISSUE TITLE
DITA-OT creates duplicated related links entries

### ISSUE THREAD

**Issue by georgebina** [dita-ot/dita-ot#2194]
I attached a map and two topics. One of the topic contains a related link to the other one. The result of the transformation to XHTML for example contains 2 related links to that topic.

**Comment by georgebina** [comment]
For some reason GitHub does not work for me when trying to attach the samples... Here they are inline:

`test.ditamap`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
 <title>DITA Topic Map</title>
 <topicref href="intro.dita">
  <topicref href="sample.dita"/>
 </topicref>
</map>
```

`intro.dita`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="intro">
  <title>intro</title>
  <body>
    <p></p>
  </body>
</topic>
```

`sample.dita`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="untitled2">
  <title>sample</title>
  <body>
    <p/>
  </body>
  <related-links>
    <linkpool>
      <link class="- topic/link " format="dita" href="intro.dita" role="parent">
        <linktext class="- topic/linktext ">intro</linktext>
      </link>
    </linkpool>
  </related-links>
</topic>
```

**Comment by xephon2** [comment]
@georgebina , you can create a ZIP archive and drop the file to the comment text area.

**Comment by jelovirt** [comment]
I think the original implementation assumed parent role links will not be written explicitly. When the map also defines the parent link, the duplicates are not dealt with. The link de-duplication code should probably be extracted into common preprocessing task and made customizable enough to support the most common cases.

**Comment by georgebina** [comment]
@xephon2 This is exactly what I tried and it did not work...

**Comment by georgebina** [comment]
It will be a good idea if DITA-OT marked somehow the generated content - this will allow a further processing step to distinguish between actual content and generated content.
