### ISSUE TITLE
Any link to a dlentry element is broken in PDF

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2198]
With either DITA OT 1.8 and 2.x:

I have a topic with a definition list containing a dlentry:

        <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
        <topic id="gogu">
          <title>GOGU</title>
          <body>
            <p><dl>
                <dlentry id="dlentry_spq_wtg_r5">
                  <dt>aaaa</dt>
                  <dd>bbbbbb</dd>
                </dlentry>
              </dl></p>
          </body>
        </topic>

and a topic which has a link to it:

        <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
        <topic id="gigi">
          <title>GIGI</title>
          <body>
            <p><xref href="gogu.dita#gogu/dlentry_spq_wtg_r5">THIS IS A TEST</xref></p>
          </body>
        </topic>

In the PDF output, the link is broken, when Apache FOP processes, it issues warnings like:

      [fop] 7764 WARN [ main ] org.apache.fop.apps.FOUserAgent - Page 3: Unresolved ID reference "unique_2_Connect_42_dlentry_spq_wtg_r5" found.

**Comment by raducoravu** [comment]
Looks like the problem is that the XSL-FO processing generates an FO table for the definition list in which the dlentry is a row:

               <fo:table-row id="unique_2_Connect_42_dlentry_spq_wtg_r5">

and Apache FOP does not seem to be able to handle links to table rows.
It works in XEP though.

In my opinion we should try to render the definition lists in the PDF without using an FO table. 
We've had user requests in the past about allowing the definition terms to span over the entire page for example. This cannot be done right now because the definition term is inside a table.

**Comment by xephon2** [comment]
@raducoravu What is the alternative? Rendering `<dl>` as tables is extremely important for us. Please do not remove this feature. At least the resulting output should be equivalent.

If linking to `<dlentry>` elements is a must-have-requirement (I did not know that it should work and, to be honest, I do not understand why that is useful), why not bending the links to the corresponding `<dl>` as a fallback solution? Linking to `<dl>` should work, I think. Probably, that's easier to maintain.

**Comment by raducoravu** [comment]
I guess linking to dlentries should work in the same way as linking to individual task steps and list items and for the same use cases.
Could you tell me more about the requirement for using tables to render this? If it would be rendered like any other list but with the "dd" indented a little bit to the right, wouldn't that be about the same?

**Comment by jelovirt** [comment]
E.g. http://dita-generator.elovirta.com/ allow users to style dl lists as either

* table
* HTML type list with intended term content
* bulleted list

There are probably other output types too and they are all equally correct. I think the table one is really the only one that can handle headers. Thus changing the default output to be something other than table would be risky and difficult so that the new solution would make everyone happy.

**Comment by xephon2** [comment]
If you have hundreds of long `<dl>` in your output, you waste a lot of whitespace and pages.

Please save the environment and don't kill the table.  :green_heart: :deciduous_tree:

**Needs one line**
```
| dt | dd |
```

**Needs two lines**
```
dt
    dd
```

**Comment by raducoravu** [comment]
Remember this, Jarno?
https://issues.apache.org/jira/browse/FOP-2110

**Comment by raducoravu** [comment]
I'll close this one, although we have links to dlentries, we do not need this for our user's manual because we produce it with RenderX XEP.

**Comment by jelovirt** [comment]
@raducoravu it would be nice to have a workaround for this, for FOP. It could be that all links to `<dlentry>` elements would be rewritten to link the first `<dt>` or `<dd>`. So a PR is appreciated if someone wants to fix this.

**Comment by raducoravu** [comment]
Indeed maybe the links could be re-written but a warning should be also issued because the publisher will not obtain exactly what they want.

**Comment by drmacro** [comment]
Should be able to generate an empty fo:inline with the ID of the dl entry within the cell containing the <dt> content. That should work with any FO engine.

**Comment by raducoravu** [comment]
The idea is good, also as a general workaround the ID can be set on the "dt" instead of the "dlentry".

**Comment by drmacro** [comment]
Authors should not link to <dt> elements, they should link to the dlentry, as that's the unit of information. Any link rendition problems should be handled in the processor.

**Comment by xephon2** [comment]
@drmacro strongly agree

**Comment by jelovirt** [comment]
Since the issue here is that FOP cannot link to `fo:table-row`, it might be better to add a generalized fix. We could post-process the generated FO file only when FOP is used and use a rewrite rule:

*   if `fo:table-row` contains `@id`, generate `fo:inline` into the first block inside row and move the `@id` there.

This would fix the issue at FO level, not while doing DITA to FO transformation, and it would be general fix for any link to table rows.

**Comment by keberlein** [comment]
The DITA spec relies heavily on links to <dlentry> elements for most of the attribute definitions. We generate the PDF using Antenna House, but this problem means that anyone republishing the spec using FOP will have lots of dead hyperlinks.

**Comment by robander** [comment]
Commit linked to above overrides default processing for `dlentry/@id` with FOP to drop it from the table row, and create the markup Eliot suggested (`<fo:inline id="ID"/>` in the first term). No change to processing for AH or XEP.

The more general post-process that @jelovirt mentioned would still be useful for links to any other `fo:table-row`, but I went with the easy fix for the common scenario. If/when a general post-process is added to fix this, the specific fix for `<dlentry>` will be unnecessary, but will not interfere in any way.

**Comment by robander** [comment]
Closed with #1764 as described above.
