### ISSUE TITLE
Common string logic for org.dita.pdf2 fails to retrieve a string for "Task Result" 

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#2203]
The PDF code looks for "task_result" in the common strings. Unfortunately, ~/xsl/common/strings-en-us.xml has no str named "task_result" even though it does have a str named "task_results".

**Comment by jelovirt** [comment]
String is used by `src/main/plugins/org.dita.pdf2/xsl/fo/task-elements.xsl`.
