### ISSUE TITLE
Conrefing of simple tables leads to duplicated content in PDF

### ISSUE THREAD

**Issue by keberlein** [dita-ot/dita-ot#2204]
DITA-OT 2.1.1 running on Windows 64-bit edition.

Content is repeated three times in each table cell or table header. The attached ZIP includes a small source sample and output from both 1.8.5 and 2.1,

[test-files-for-DITA-OT-project.zip](https://github.com/dita-ot/dita-ot/files/99092/test-files-for-DITA-OT-project.zip)

**Comment by jelovirt** [comment]
Unable to reproduce with 2.2.2.

**Comment by keberlein** [comment]
I think there are gremlins in my laptop. I reinstalled DITA-OT 2.1.1 and do not have the problem.
