### ISSUE TITLE
Change order of chunk and move-meta-entries

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2207]
Move chunk processing to take place before move-meta-entries. The DITA spec doesn't mandate a given order between these processing steps.

**Comment by drmacro** [comment]
Chunking doesn't change the hierarchical relationship between the map and the topics or the topics and each other so it shouldn't matter what order you do things in--the result has to be correct regardless.

That is, whether the configuration of topics as organized into XML documents is created at authoring time or through chunking, the effective result must be identical. How you achieve this in a processor is an implementation detail.
