### ISSUE TITLE
HTML5: <choicetable>  output does not respect `@frame` attribute

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2208]
The HTML5 output for `<choicetable>` elements seems to be ignoring the value of the `@frame` attribute.

Setting `<choicetable frame="none">` to disable borders currently yields the same output as `<choicetable frame="topbot">`:

```html
<table border="1" frame="hsides" rules="rows" cellpadding="4" cellspacing="0" summary="" class="simpletable choicetable choicetableborder">
```

The `<simpletable>` element from which `<choicetable>` is specialized behaves as expected: setting `<simpletable frame="none">` yields the following HTML output:

```html
<table cellpadding="4" cellspacing="0" summary="" border="0" class="simpletable">
```

**Comment by eerohele** [comment]
Fixed via #2239.
