### ISSUE TITLE
Add transtype specific extension points

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2209]
This is a feature request.

It is possible to create multiple `<transtype/>` elements in the same `plugin.xml`

```xml
<feature extension="dita.conductor.transtype.check" value="mytranstype"/>
<transtype name="mytranstype" extends="html5"/>
```

Unfortunately it is not possible to bind extension points to transtypes. For example, I'd like to set the chunking method for only one transtype. So what I'd like to do is this (pseudocode):

```xml
<plugin id="my.plugin.id">
  
  <!-- No special chunking here -->
  <feature extension="dita.conductor.transtype.check" value="mytranstype"/>
  <transtype name="mytranstype" extends="html5"/>

  <!-- Change the chunking -->
  <feature extension="dita.conductor.transtype.check" value="mytranstype2"/>
  <transtype name="mytranstype2" extends="html5">
    <feature extension="depend.preprocess.chunk.pre" value="setchunk"/>
  </transtype>

</plugin>
```

AFAIK this does not work.

**Comment by jelovirt** [comment]
This is handled in Ant code, not plugin configuration. Thus closing as won't fix because this is already possible and easy to implement.

**Comment by xephon2** [comment]
Oh, it is possible via parameter. Did not recognize that. Sorry

```xml
<transtype name="mytranstype" extends="html5">
    <param name="root-chunk-override" default="true">to-content</param>
</transtype>
```

**Comment by jelovirt** [comment]
No, that just adds the configuration for a parameter, but you still have to declare it as a default in Ant.

**Comment by xephon2** [comment]
But this is what `default="true"` does, I think.

**Comment by jelovirt** [comment]
The `default` attribute is not supported in `param` element. See https://github.com/dita-ot/dita-ot/blob/develop/src/main/resources/plugin.rnc#L26
