### ISSUE TITLE
"No digits found" when publishing DITA to ODF [DOT 2.2.1]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2211]
Using a recent version of Saxon EE.
In one of my DITA topics I have a reference to an SVG like:
```xml
<image href="../image/shapes.svg" alt="shapes"/>
```
the publishing fails with:

>D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.odt\build_dita2odt.xml:93: Fatal error during transformation using D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.odt\xsl\dita2odt.xsl: No digits found; SystemID: file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/plugins/org.dita.odt/xsl/xslodt/dita2odt-img.xsl; Line#: 238; Column#: -1

That particular line is something like:
```xml
<xsl:when test="not(contains(@href,'://')) and ($height > 0) and ($width > 0)">
```
Maybe we could at least cast the params to numbers in the expression or type the received parameters.

**Comment by jelovirt** [comment]
ODT code assumes height and width is available. SVG is not supported by the image metadata filter, thus the dimension data is not there.

**Comment by raducoravu** [comment]
Thanks Jarno, I had an automated test on my side which happen to catch this.
