### ISSUE TITLE
Move DITA 1.3 DTD, XSD, RNG into a plugin

### ISSUE THREAD

**Issue by shudson310** [dita-ot/dita-ot#2220]
The current plugin (v2.2.1) does not resolve DITA 1.3 documents that use RelaxNG declarations (for example). All DTD, XSD and RNG schemas should be in a toolkit plugin with appropriate catalog entries.

**Comment by raducoravu** [comment]
Could you elaborate? The DITA OT 2.2.2 has a plugin called "org.oasis-open.dita.v1_3" which contains all the proper URI mappings for the RNG schemas.

**Comment by shudson310** [comment]
I am using DITA-OT 2.2.1. I will try with 2.2.2. The error I get is:
"
Invalid RNG Schema: urn:dita-ng:dita:rng:map.rng, unknown protocol: urn "

On Thu, Feb 4, 2016 at 11:21 PM, Radu Coravu <notifications@github.com>
wrote:

> Could you elaborate? The DITA OT 2.2.2 has a plugin called
> "org.oasis-open.dita.v1_3" which contains all the proper URI mappings for
> the RNG schemas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dita-ot/dita-ot/issues/2220#issuecomment-180218100>.
>



-- 
--Scott

http://shudson310.blogspot.com

**Comment by shudson310** [comment]
Think I found the problem: the catalog actually has an entry for
"urn:oasis:names:tc:dita:rng:map.rng" rather than the dita-ng referenced in
the document.

On Fri, Feb 5, 2016 at 8:23 AM, Scott Hudson <shudson310@gmail.com> wrote:

> I am using DITA-OT 2.2.1. I will try with 2.2.2. The error I get is:
> "
> Invalid RNG Schema: urn:dita-ng:dita:rng:map.rng, unknown protocol: urn "
>
> On Thu, Feb 4, 2016 at 11:21 PM, Radu Coravu <notifications@github.com>
> wrote:
>
>> Could you elaborate? The DITA OT 2.2.2 has a plugin called
>> "org.oasis-open.dita.v1_3" which contains all the proper URI mappings for
>> the RNG schemas.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dita-ot/dita-ot/issues/2220#issuecomment-180218100>.
>>
>
>
>
> --
> --Scott
>
> http://shudson310.blogspot.com
>



-- 
--Scott

http://shudson310.blogspot.com

**Comment by raducoravu** [comment]
The DITA RNGs that yuou previously used were not OASIS provided, they were provided by Oxygen as a DITA OT plugin. As you've discovered the official OASIS DITA 1.3 RNGs have another URI pointing to the OASIS RNG files.
The folder:

      OXYGEN_INSTALL_DIR\frameworks\dita\DITA-OT2.x\plugins\org.oasis-open.dita.v1_3\oxygen_templates

contains new file templates for this and they are automatically added to the Oxygen new file templates if in the Oxygen Preferences->"DITA" page you use the bundled DITA OT 2.x. Otherwise, you can add them manually in the Oxygen Preferences->"Document Templates" page.
