### ISSUE TITLE
Improve error message for keyref that includes topic ID

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2221]
GIven a keyref like this:

```
<xref keyref="getting-started/concept_qd2_gt4_t5"/>. 
```

Where "concept_qd2_gt4_t5" is the ID of a topic (not an element within a topic), the OT fails to resolve the reference and does not produce a working link.

The keyref is incorrect as authored: you are only supposed to include non-topic element IDs, so this case is author error.

However, the OT could detect this error and report it as "You specified a topic ID as part of a key ref, that won't work."

In addition, it could also go ahead and treat the keyref as a keyref to the topic since that's what the author thought they were requesting.

The current behavior is to simply report the reference as unresolvable. But using oXygen, for example, the link is resolved (because oXygen is clearly not distinguishing between keyrefs to topics by ID an other keyrefs--they should also report this issue or simply not allow it to occur). So it's confusing to a typical user as to why the link didn't work when clearly the reference is correct.

It took me a while to figure out what I had done wrong, and that was only in the context of making this issue report. And I helped design the keyref mechanism.

**Comment by jelovirt** [comment]
:+1: for adding a better error message

**Comment by robander** [comment]
same :+1: for better error message.

Of course we also need to be careful that we don't give the message when somebody comes up with this:
```xml
<topic id="breakME">
  <title>This is designed to break things</title>
  <body>
    <fig id="breakme"><title>Haha</title></fig>
  </body>
</topic>
```

**Comment by jelovirt** [comment]
Having a duplicate ID is hopefully reported earlier on in the processing chain.

**Comment by drmacro** [comment]
Hmm, I never considered that case before. Does the spec say whether or not having the same value on the topic ID and an element within the topic is allowed?

I imagine most tools will break in that case if they doing e.g., *[@id = $targetID]

But without reviewing the spec I think that topic IDs and element-within-topic-IDs are completely distinct ID spaces.

So in the breakME case I would expect the keyref "foo/breakME" to work since it is correct (the ID component is the ID of a non-topic element within a topic unless that case is explicitly disallowed by the spec (which I doubt it is).

**Comment by drmacro** [comment]
I just realized that oXygen 17.1 is creating this type of keyref value for any xref to a topic created using its xref dialog. If the only element with an ID is the topic itself that is automatically selected and there's no way to unselect it.

That's a serious bug and I'll report it to Radu.

**Comment by robander** [comment]
I'm fairly certain that having an ID on the topic, and matching inside the topic, is legal. They are distinct IDs, always referenced separately. In the same way that you you can have the same ID in a within topic and within a sub-topic.

**Comment by drmacro** [comment]
Cool--if you and I agree it must be true :-)

**Comment by jelovirt** [comment]
Development branch doesn't complain about the ID reuse, didn't try older versions.

**Comment by robander** [comment]
In the past there has (apparently) been some ambiguity over whether 2 matching IDs within the same topic is an error. I've always considered it an error and feel that the spec does too, but some have protested for one reason or another. However, I think it's clearer with the topic ID versus ID within topic.

**Comment by raducoravu** [comment]
@drmacro You are right, our dialog for inserting keyrefs behaves badly in this case. We'll work on this.
