### ISSUE TITLE
Build parameters should accept consistent true-ish and false-ish values

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2225]
Currently, different build parameters accept true / false or yes / no values, and might be case-sensitive. This increases the likelihood of user errors when building content.

My recommendation is twofold:
- For consistency in usage and documentation, we standardize the default build parameters to use either true / false or yes / no (not a mishmash).
- For backward compatibility and to help users avoid errors, the build should parse, case-insensitively, "true-ish" values equivalently and likewise with "false-ish" values. That is to say, YES = yes = true = True.

**Comment by robander** [comment]
The main problem with updating for consistency (yes, the problem we always run into) is that if we change the values taken in by our program, any user extensions that make use of the value will break. This has held us back in the past from attempts to standardize on values or even on parameter names.

For example, today, we have some parameters that take in the value YES. If we accept other values, we have the following issues (possibly more):

- If the command line value is passed directly into XSLT/Java, any new value will break customizations / plugins that make use of the parameter. That is, if my XSLT extension checks to see if `gen.task.labels=YES` then that code will break if the value passed in is `yes` or `true`.
- We could try to handle this with some ugly Ant code that says "For any of this long list of values, set a property to this old value" - then the old value is passed in to existing programs using the new property. I think the only way to do this is by having Ant examine the command line value for a series of accepted values, and set a new property with a new name. That new property would then be passed to XSLT/Java in place of the old property. So, the same breakage comes up with any Ant extensions that make use of the old property.

Overall I really wish we'd been consistent from the start, and agree that being consistent would be much more usable. I'm less certain about yes=true but if we were consistent from the start, I don't think that would come up. At this point, I'm not sure how to _become_ consistent without breaking lots of existing users. If we make a change like this, it will have to be in a major release (like 3.0) where everybody has more attention on compatibility issues.

**Comment by jelovirt** [comment]
What @robander said. We would have fixed this ages ago if the problem wasn't breaking customizations. We can change our code to accept `yes` and `true` with case-insensitive comparison for true values, but the problem is plugin/customization X that will still expect the value to be `YES` and only with that case.

To be implemented in 3.0.
