### ISSUE TITLE
Add dimension metadata reader for SVG

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2230]
Add support for SVG in image metadata reader.

**Comment by raducoravu** [comment]
Great. SVG image dimensions can also be specified with units like px, em, pt. 
Is the code which does the scaling in the XSLT stylesheets capable of using these typed dimensions set on the image? Or does it expect that the width and height that you compute in this stage are float values?

**Comment by jelovirt** [comment]
The dimension metadata we inject used to only contain an `int` for pixel count. Now the dimensions are treated as `String`. It's up to the code that processes the information to be unit agnostic. I haven't looked into that, I just wanted to add the reader first.

**Comment by jelovirt** [comment]
Right now the code assumes that if the dimensions don't have a unit, then they are pixels. It might be a better idea to just always add the unit into the metadata reader output, to make things explicit.

**Comment by raducoravu** [comment]
The problem is that adding always the unit of measure would break compatibility with older written stylesheets which used these metadata attributes. Maybe a better approach would be to perform the conversion to pixels directly in the svg image reader. Our code which does such conversions for the Author visual editing mode is something like this:

              /**
               * Convert the given value in pixels.
               * 
               * @param value       The value to convert in pixels. 
               * @param unit        The unit of the given value.  
               * @param fontSize    The reference font size.
               * @param dotsPerInch The dots per inch value.
               * @return            The float representing the value converted in pixels.
               */
              public static int convertToPx(float value, Unit unit, float fontSize, int dotsPerInch) {
                float toReturn = 0f;
                switch (unit) {
                  case CENTIMETER:
                    // Converts to inches and then multiplies with the dots per inch.
                    toReturn = value * dotsPerInch / 2.54f;
                    break;
                  case EM:
                    // The EM is relative to the font size. 1 em is the font size. 
                    toReturn = value * fontSize;
                    break;
                  case EX:
                    // The EX is relative the the height of the "x" character.
                    toReturn = value * fontSize * 0.6f;
                    break;
                  case INCH:
                    // Value in inches, multiplies with the dpi.
                    toReturn = value * dotsPerInch;
                    break;
                  case MILLIMETER:
                    // Converts to inches and then to pixels 
                    toReturn = value * dotsPerInch / 25.4f;
                    break;
                  case PICA:
                    //A unit of measure equal to 12 points or one sixth of an inch.
                    toReturn = value * dotsPerInch / 6.0f;
                    break;
                  case PIXEL:
                    // Directly in pixels. No conversion
                    toReturn = value;
                    break;
                  case POINT:
                    // A point is approximately 1/72 inch
                    toReturn = value * dotsPerInch / 72.0f;
                    break;
                }
                return Math.round(toReturn);
              }

The dots per inch can be approximated with "90". Before the method was called, the string was decomposed in a float value + a UNIT enumeration.

**Comment by jelovirt** [comment]
The problem is that for print media the desired DPI might be 300. IMO the metadata reader should only state what the image claims its dimensions are, and all processing should be left to code that knows where it's using the file.

**Comment by jelovirt** [comment]
@raducoravu Do you think I should add support for gzipped SVG, the `.svgz` extension? I could check that the file extension is `.svgz` and that the two first bytes are [`0x1f` and `0x8b`][1], then decode the file and run it through the normal reader.

[1]: https://tools.ietf.org/html/rfc1952#page-6

**Comment by raducoravu** [comment]
About SVGZ, if the file has the right extension, you can open directly a GZIPInputStream() over it, it should fail if the document is not an actual gzip, so that's quite doable. I've encountered usecases (not many) in which clients were using SVGZ.

**Comment by raducoravu** [comment]
About computing the pixel dimensions in the XSLT code, in my opinion the code which produces the XSL-FO should not use these metadata attributes at all because from what I remember "external-graphic" supported specifying width and height in percents.
The XHTML-based outputs should not have anything to do with DPI information. So for XHTML-based outputs the DPI could be a constant in the Java code.
