### ISSUE TITLE
Cannot unzip dita open toolkit

### ISSUE THREAD

**Issue by robertnorledge** [dita-ot/dita-ot#2235]
I have downloaded the zip file for dita open toolkit onto my windows 7 machine. When I try and unzip it, it gets stuck.

**Comment by xephon2** [comment]
Have you tried downloading it again? Please post the link to make sure which ZIP file is affected.

**Comment by robertnorledge** [comment]
thanks

 

I was double-clicking the zipped file directly.

 

I have opened 7zip using the explorer, and have now unzipped the file.

 

Robert

**Comment by xephon2** [comment]
OK, so please close this issue, if the file is not corrupt.

**Comment by robertnorledge** [comment]
Thanks for xephon2 for helpful comment.
I have now fixed this issue.
The unzip got stuck when I double-clicked the zipped file directly.
I tried using the Explorer to find 7zip, and running zip directly I was able to unzip the file.
