### ISSUE TITLE
Links generated from link elements render incorrectly

### ISSUE THREAD

**Issue by keberlein** [dita-ot/dita-ot#2236]
V2.2.2 PDF

If a link element contains linktext and desc elements, the hyperlink is rendered with the contents of the desc elements appended to the contents of the linktext element.

See the DITA-OT documentation for an example. Look at DITA Open Toolkit User Guide > DITA Open Toolkit overview > DITA specification support > DITA 1.3 support

**Comment by xephon2** [comment]
Maybe this one is related to the link issue: [glossentry references are not rendered correctly](https://github.com/dita-ot/dita-ot/issues/2173#issuecomment-166338955)

**Comment by infotexture** [comment]
Re. the `needs-reproduction` label here: the issue is evident in `doc/userguide.pdf` for the 2.2.2 release.

HTML-based outputs are fine.

**Comment by jelovirt** [comment]
The `needs-reproduction` tag is always added until someone from the development team is able to reproduce the issue and verified whether the issue still persists in `development` branch.

**Comment by infotexture** [comment]
OK, got it. Confirmed w/ dita-ot@3d05fca.

**Comment by robander** [comment]
Looks like this shipped in 2.2.3 - it's in the release notes, and in 2.2.4 the PDF of the user guide looks right with the topic / links suggested above. Marking this closed and adding the 2.2.3 tag.
