### ISSUE TITLE
commons.xsl: Fatal Error: Cannot compare xs:integer to xs:untypedAtomic

### ISSUE THREAD

**Issue by bdcz** [dita-ot/dita-ot#2238]
Generating a PDF, I get the following error (extract from the log file):

transform.topic2fo.main:
     [xslt] Processing C:\Users\...\AppData\Local\Temp\temp20160221114813963\stage1a.xml to C:\Users\...\AppData\Local\Temp\temp20160221114813963\stage2.fo
     [xslt] Loading stylesheet c:\Users\...\DITA-OT2.2.2\plugins\org.dita.pdf2.fop\xsl\fo\topic2fo_shell_fop.xsl
     [xslt] c:\Users\...\DITA-OT2.2.2\plugins\org.dita.pdf2\xsl\fo\commons.xsl:1219:69: Fatal Error! Cannot compare xs:integer to xs:untypedAtomic

(bdcz)

**Comment by bdcz** [comment]
The error relates to the comparison expression:
<xsl:if test="string-length(.) lt $maxCharsInShortDesc">

**Comment by bdcz** [comment]
The error refers to the following comparison expression:

<xsl:if test="string-length(.) lt $maxCharsInShortDesc">

**Comment by bdcz** [comment]
The error refers to the following comparison expression:

<xsl:if test="string-length(.) lt $maxCharsInShortDesc">

**Comment by bdcz** [comment]
The error refers to the following comparison expression:

<xsl:if test="string-length(.) lt $maxCharsInShortDesc">

**Comment by bdcz** [comment]
The error refers to the following comparison expression:

<xsl:if test="string-length(.) lt $maxCharsInShortDesc">

(bdcz)

**Comment by bdcz** [comment]
The error refers to the following comparison expression:

xsl:if test="string-length(.) lt $maxCharsInShortDesc"

**Comment by drmacro** [comment]
Looking at the commons.xsl in PDF 2 $masCharsInShortDesc is declared as xs:integer on line 89:

~~~~
    <xsl:variable name="maxCharsInShortDesc" as="xs:integer">
        <xsl:call-template name="getMaxCharsForShortdescKeep"/>
    </xsl:variable>
~~~~

So the error you're reporting should not happen. Likewise the template "getMaxCharsForShortdescKeep" is declared as type xs:integer.

Do you have any customizations in play? The most likely cause of this would be a customization that overrides the declaration of $maxCharsInShortDesc and does not specify the @as attribute.

**Comment by bdcz** [comment]
Thanks, Eliot.
It is as you indicate - my PDF customization file commons.xls did not declare the variable as integer - now it works.
Boris (bdcz)

**Comment by AlastairDent** [comment]
I'm seeing exactly the same error, but I do not have a customized commons.xsl file.
