### ISSUE TITLE
2.2.2 performance issues

### ISSUE THREAD

**Issue by tyrin** [dita-ot/dita-ot#2251]
In upgrading from 1.8.4 to 2.2.2 our build went from 1 min 49 seconds to 2 min 53 seconds. It also required me to increase the memory allocated to ant (it was 1024 and is now 2048.)

That's quite an increase in building exactly the same content.

**Comment by jelovirt** [comment]
A lot has happened between 1.8 and 2.2, not just DITA 1.3 but also refactoring the preprocessing code to make it easier to test and reason about.

If you're interested in helping us out, it would help to get some statistics which areas have slowed down. If you could run your source with both 1.8 and 2.2 and use

```
ant <normal-arguments> -logger org.apache.tools.ant.listener.ProfileLogger -l test.log
```
to collect processing time information to the test.log. Then, send the logs to us. If the processing log contains information you can't share, you can do

```
grep -F 'ms)' test.log
```

To just extract the lines that actually contain timing information.

**Comment by eerohele** [comment]
The difference might also vary quite a bit depending on which DITA features the document uses and possibly which transtype you're using.

I'm guessing that 2.2 simply having to parse the DITA 1.3 DTDs explains some of the difference, though.

Here's some benchmark results for running just the preprocessing stage on the DITA-OT user guide on DITA-OT 1.8.4 vs DITA-OT 2.2:

https://s3.amazonaws.com/f.cl.ly/items/15150N0s321j2h2a1g1A/preprocess.html

The mean difference is around 4 seconds.

Incidentally, reusing JVM instances helps quite a bit here, too. This is for publishing XHTML output for the same document with 1.8.4 vs 2.2 with the [DITA-OT Gradle plugin](https://eerohele.github.io/dita-ot-gradle/):

https://s3.amazonaws.com/f.cl.ly/items/2z151t2a1w3O1r3Z1p0v/dita-ot-gradle.html

That takes the difference down to 0.7 seconds for the entire processing.

**Comment by jelovirt** [comment]
1.3 doesn't just mean we use different DTDs. For 1.3 we have to have an additional step to resolve same topic fragments, we have to read key definitions separately from initial parse step, we have to check for branch filtering even if we don't actually have any branch filtering in source, etc. So there's a lot of new stuff that makes things slower. But, without exact number for what actually takes more time, it's difficult to try to optimize.

**Comment by robander** [comment]
Marking as obsolete - there have been many changes since this issue came in so there is no reason to compare to 1.8 or 2.2.
