### ISSUE TITLE
PDF2: Navtitle on topicgroup rendered when it should not be

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2253]
Per the 1.2 spec, navigation titles on topicgroup elements should always be ignored in output.

This markup:

```
<topicgroup>
  <topicmeta>
   <navtitle>Some Nav title</navtitle>
  </topicmeta>
</topicgroup>
```

Results in a ToC entry and main flow title using the PDF2 transform and OT 2.2.2

**Comment by robander** [comment]
I wonder if the `mappull` step should add a check for the `<topicgroup>` element, and explicitly drop the navtitle element / attribute, though perhaps this should show up earlier in a validation step. Wherever it appears, the same check could be used to warn about `<topichead>` that is missing a heading. Attaching samples that use both.
[2253.zip](https://github.com/dita-ot/dita-ot/files/252748/2253.zip)

**Comment by shudson310** [comment]
We actually want the navtitles to render, especially for large glossaries, such as:
```
<topicgroup>
   <topicmeta>
    <navtitle>A</navtitle>
   </topicmeta>
   <topicref print="yes" toc="yes" href="../common/glossary/gl_acars.dita"/>
   <topicref href="../common/glossary/gl_ACAS.dita" print="yes" toc="yes"/>
   <topicref print="yes" toc="yes" href="../common/glossary/gl_arinc.dita"/>
   <topicref print="yes" toc="yes" href="../common/glossary/gl_acta.dita"/>
   <topicref print="yes" toc="yes" href="../common/glossary/gl_API.dita"/>
   <topicref print="yes" toc="yes" href="../common/glossary/gl_AUP.dita"/>
  </topicgroup>
```
Without it, I get a gigantic list of glossary terms. This works well in OT 2.3.2, but they get ignored in 2.4.3. What is the use of a navtitle if it is not rendered as part of the navigation?!

**Comment by jelovirt** [comment]
@robander we could implement this fairly easily by actually removing all `<topicgroup>` element at the end of preprocessing, or near the end.
