### ISSUE TITLE
Keyref resolution fails if input path contains ../

### ISSUE THREAD

**Issue by eerohele** [dita-ot/dita-ot#2258]
2.2.3 and `develop`.

If you do e.g. `dita -i ../docsrc/userguide.ditamap -f pdf`, keyref resolution fails:

```
[keyref] file:/tmp/docsrc/index.dita:6:55: [DOTJ047I][INFO] Unable to find key definition for key reference "release" in root scope. The href attribute may be used as fallback if it exists
```

If you do `dita -i docsrc/userguide.ditamap -f pdf` instead, it works fine.

**Comment by jelovirt** [comment]
`Main` should normalize path argument values.

**Comment by eerohele** [comment]
Yeah, calling `getCanonicalPath()` instead of `getAbsolutePath()` fixes the issue.

**Comment by jelovirt** [comment]
Or, we could use [`java.nio.file.Path`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html) as it's the preferred way to work with paths in Java 7.
