### ISSUE TITLE
DITA-OT assumes strong constraints rather than weak constraints

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#2259]
[Section 2.5.5.4 of the DITA 1.3 Specification](http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/constraints-strong-and-weak.html) states

> By default, constraints are weak unless they are explicitly designated as strong

Technically, the DITA-OT is in compliance with the spec because 2.5.5.4 also states

> Processors also can be configured to treat all constraints as strong

Strong constraints can be overly restrictive in many use cases. This is why the specification defaults to weak. For instance, strong constraint processing prevents a step in a task topic from having a conref to a step in a general task topic, despite the fact that step in both cases have identical content models and are  unaffected by the strictTaskbody constraint that is preventing the conref from being resolved.

This issue is important to me because I use constraints extensively in the technical content DTDs. Having the DITA-OT default to strong constraints prevents easy interoperation between out-of-the-box technical content instances and the constrained technical content instances.

I understand that there may be use cases where strong constraint enforcement is essential. Perhaps the DITA-OT could be modified to accept an ant parameter that makes strong and weak constraint processing selectable.

**Comment by jelovirt** [comment]
The conref code hasn't been touched for 1.3, thus we're still using 1.2 era processing. Makes sense to add a flag to enable/disable strict processing.

**Comment by jelovirt** [comment]
The domain validation function `conref:isValid` in [conrefImpl.xsl](https://github.com/dita-ot/dita-ot/blob/develop/src/main/xsl/preprocess/conrefImpl.xsl) should be  reimplemented by separating the parsing and validation steps. The `@domains` value should be parsed to some element structure so that the validation step could just check whether the models match. This would also make it easier to write XSpecs tests for the validation.

**Comment by robander** [comment]
This was fixed in 3.2 with https://github.com/dita-ot/dita-ot/pull/3097 -- marking closed before the bot gets a chance.
