### ISSUE TITLE
Java Help Improvements

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2263]
A list of improvements we made on our side for generating Java Help from DITA content:
- [ ] In the XSL "map2javahelpset.xsl" the main title of the map should be normalized because the JavaHelp application does not normalize it when displayed, something like:
  
  ``` xml
  <xsl:value-of select="normalize-space(*[contains(@class,' topic/title ')])"/>
  ```
  
  Titles should be also normalized in the "map2javahelptoc.xsl" stylesheet.
- [ ] If I reuse multiple times in the DITA Map a topic which has other topicrefs under it, in the second context the child topicrefs will not be displayed.
  In the XSL stylesheet "map2javahelpmap.xsl" there is a call template to:
  
  ``` xml
   <xsl:apply-templates select="$subtopicNodes"/>
  ```
  
  which could be made no matter if the current topicref is the first or not.
- [ ] If I have a bookmap with a `<frontmatter>` without a `@href` and the front matter contains topicrefs inside it, the TOC will contain an empty item corresponding to the frontmatter.
  In the "map2javahelptoc.xsl" there is at some point a comparison like:
  
  ``` xml
  <xsl:when test="$title">
  ```
  
  but in our case the $title is the empty string and the toc item is added with the empty title.
  So (because the XSLT is still 1.0) the xsl:when could be re-written like:
  
  ``` xml
  <xsl:when test="$title and $title != ''">
  ```

**Comment by raducoravu** [comment]
3) If I have a bookmap with a <frontmatter> without a @href and the front matter contains topicrefs inside it, the TOC will contain an empty item corresponding to the frontmatter.
In the "map2javahelptoc.xsl" there is at some point a comparison like:

     <xsl:when test="$title">

but in our case the $title is the empty string and the toc item is added with the empty title.
So (because the XSLT is still 1.0) the xsl:when could be re-written like:

    <xsl:when test="$title and $title != ''">

**Comment by jelovirt** [comment]
@raducoravu are you able to put these into a PR?

**Comment by raducoravu** [comment]
@jelovirt I will try to find some time for this.
We also have some custom build targets which create the final Java Help JAR and call the "com.sun.java.help.search.Indexer" to perform the indexing before the JAR is created. But for this an extra "jsearch.jar" library is necessary.
Not sure how many people are interested in JavaHelp, we still are because the Oxygen help on Mac OSX can be browsed using JavaHelp.
