### ISSUE TITLE
No link present in TOC (DITA OT 2.2.2)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2264]
I'm attaching a sample DITA Map:
http://www.oxygenxml.com/forum/files/noLinkInTOC.zip

When published to XHTML, the TOC has no link in it. It should have one because inside the subordinate DITA Map there is a topicref with keyref:

    <topicref keyref="topicref_intro"/>

This works with DITA OT 1.8.
I tested on the 2.2.3 branch and does not seem to work. This also does not seem to work on the "develop" branch.

**Comment by xephon2** [comment]
Does not work with `2.2.2` either.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us" lang="en-us">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="copyright" content="(C) Copyright 2016" />
<meta name="DC.rights.owner" content="(C) Copyright 2016" />
<meta name="DC.Type" content="map" />
<meta name="DC.Title" content="Example Guide" />
<meta name="DC.Format" content="XHTML" />
<link rel="stylesheet" type="text/css" href="commonltr.css" />
<title>Example Guide</title></head>
<body><h1 class="title topictitle1">Example Guide</h1><div><ul class="map"></ul></div></body></html>
```

**Comment by jelovirt** [comment]
This isn't an issue with XHTML, but rather preprocessing and keyref resolution in particular.

**Comment by raducoravu** [comment]
:+1: Thanks @jelovirt I confirm this works for me.
