### ISSUE TITLE
Conref to mapref doesn't work

### ISSUE THREAD

**Issue by eerohele** [dita-ot/dita-ot#2265]
`develop`.

``` xml
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">

<map>
  <mapref href="foo.ditamap" id="foo"/>
  <topicref conref="#foo"/>
</map>
```

Doesn't work.

[Files](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/2265).

**Comment by raducoravu** [comment]
Reported recently on the Oxygen XML forum:

https://www.oxygenxml.com/forum/post50891.html#p50856

From what I tested problem still occurs with DITA OT 3.2.

**Comment by raducoravu** [comment]
Again the stalebot closed this issue although I commented on it.
