### ISSUE TITLE
Consider more languages as RTL

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2267]
In the XSLT stylesheet "dita-utilities.xsl" there is a template with the mode "get-render-direction". There should be more tests there for RTL.
According to Wikipedia the following language codes are RTL:

https://en.wikipedia.org/wiki/Right-to-left

    'ar' – 'العربية', Arabic
    'arc' – 'ܐܪܡܝܐ', Aramaic
    'bcc' – 'بلوچی مکرانی', Southern Balochi
    'bqi' – 'بختياري', Bakthiari
    'ckb' – 'Soranî / کوردی', Sorani Kurdish
    'dv' – 'ދިވެހިބަސް', Dhivehi
    'fa' – 'فارسی', Persian
    'glk' – 'گیلکی', Gilaki
    'he' – 'עברית', Hebrew
    'lrc' - 'لوری', Northern Luri
    'mzn' – 'مازِرونی', Mazanderani
    'pnb' – 'پنجابی', Western Punjabi
    'ps' – 'پښتو', Pashto
    'sd' – 'سنڌي', Sindhi
    'ug' – 'Uyghurche / ئۇيغۇرچە', Uyghur
    'ur' – 'اردو', Urdu
    'yi' – 'ייִדיש', Yiddish

**Comment by robander** [comment]
Makes sense. The current list is only based on languages that are otherwise supported for generated text. It's possible to generate content that doesn't use any generated text, in which case it would be nice if we "just worked"...
