### ISSUE TITLE
Table with colspec @name attribute that doesn't start with alpha causes build to fail

### ISSUE THREAD

**Issue by juliovaz** [dita-ot/dita-ot#2271]
This is related to issue #2212. If a table has an `@colname` attribute value that doesn't begin with an alphabetical character, the build fails with the same message as reported in #2212. It seems the code does not treat a numeric value for `@colname` as a string which causes an empty sequence. This is a sample that causes the error.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="c983815">
  <title id="v934523">Other LED Behavior</title>
  <conbody id="v934524">
    <p id="v934525">
      <table id="v934526" colsep="1" frame="all" rowsep="1">
        <tgroup id="v934527" cols="2" colsep="1" outputclass="FormatA" rowsep="1">
          <colspec id="v934703" colname="1" colnum="1" colwidth="50*"/>
          <colspec id="v934704" colname="2" colnum="2" colwidth="50*"/>
          <thead id="v934530">
            <row id="v934531" rowsep="1">
              <entry id="v934532" colname="1">
                <b>LED Behavior</b>
              </entry>
              <entry id="v934533" colname="2">
                <b>Indicates...</b>
              </entry>
            </row>
          </thead>
          <tbody id="v934534">
            <row id="v934535" rowsep="1">
              <entry id="v934536" colname="1">All LEDs fast blinking Blue </entry>
              <entry id="v934537" colname="2">Device has a problem. Contact WD Support.</entry>
            </row>
            <row id="v934538" rowsep="1">
              <entry id="v934539" colname="1">All LEDs blinking blue in one long (3 sec) and 3 short
                blinks.</entry>
              <entry id="v934540" colname="2">Device in recovery mode.</entry>
            </row>
            <row id="v934541" rowsep="1">
              <entry id="v934542" colname="1">Blinking Blue</entry>
              <entry id="v934543" colname="2">Firmware update in progress; File I/O in SD card/USB
                port syncing; Mounting USB storage; Scanning SD card </entry>
            </row>
          </tbody>
        </tgroup>
      </table>
    </p>
  </conbody>
</concept>
```

**Comment by raducoravu** [comment]
In order to properly display code blocks you should add at least 4 spaces before each line of the pasted content.

**Comment by jelovirt** [comment]
Fixed the issue description formatting.

**Comment by jelovirt** [comment]
Name attribute? The example topic has no `@name` attribute.

**Comment by juliovaz** [comment]
Sorry. I meant colname I better get some coffee.

sent from Android

**Comment by raducoravu** [comment]
I cannot reproduce the problem with the sample concept, I can publish it to PDF using either DITA OT 2.2.2 or the code on the develop branch.
@juliovaz can you reproduce the problem with the same sample? Do you have maybe PDF XSLT customizations?

**Comment by juliovaz** [comment]
I have no customizations for table processing. When I used the sample file
in place of a corrected one, I got the failure.

sent from Android

**Comment by juliovaz** [comment]
I may have spoken too soon. I have verified and corrected all the tables in the document and I still get the message. I'm unsure what's causing this error now.
     [xslt] C:\dita-ot-2.2.2\plugins\org.dita.pdf2\xsl\fo\tables.xsl:426: Fatal Error! An empty sequence is not allowed as the value of variable $entryNumber
     [xslt] Failed to process C:\Western_Digital\Extract\temp\pdf\oxygen_dita_temp\stage1a.xml

**Comment by jelovirt** [comment]
@juliovaz close this is the issue is invalid.

**Comment by juliovaz** [comment]
Okay. Still have no clue which table is causing the problem in 2.2.2 as it works in 1.8.5.

**Comment by raducoravu** [comment]
A possibility to find out more would be to open the XSLT stylesheet:

   C:\dita-ot-2.2.2\plugins\org.dita.pdf2\xsl\fo\tables.xsl

at line 426, and add an xsl:message to it to log the entire table structure which is processed when this fails. Then try to map that to the original DITA topic which has the table with problems.

**Comment by juliovaz** [comment]
I'll give that a shot. Thanks.

sent from Android
