### ISSUE TITLE
DITA to ODF generates not wellformed content.xml [DITA OT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2272]
If the DITA topic looks like this:

```
    <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
    <topic id="topic_zk3_y1k_z5">
      <title>Product safety</title>
      <body>
        <note type="warning">
          <p><b>ABC</b></p>
          <p>DEF</p>
          <ul>
            <li>1</li>
            <li>2</li>
          </ul>
          <p>44</p>
        </note>
      </body>
    </topic>
```

and I publish it to ODF, the generated "content.xml" from inside the ODT archive is not wellformed.

**Comment by raducoravu** [comment]
In the XSLT stylesheet:

plugins\org.dita.odt\xsl\xslodt\dita2odt-utilities.xsl

there is a comment somewhere like:

     

followed by a "note_count" variable which multiples the number of notes with 3, while all other variables multiple it with 2. This seems to fix my small example. But the larger project still does not publish with a similar problem somewhere else.
The XSLT for ODF is horrible.

**Comment by jelovirt** [comment]
I started to refactor the ODF code and since you can't really refactor it because the basis is so bad, it ended up being a rewrite. I haven't had time to finish this task because it really rewrites just about everything.

**Comment by raducoravu** [comment]
Similar problem with this simple task:

            <!DOCTYPE task PUBLIC "-//OASIS//DTD DITA Task//EN" "task.dtd">
            <task id="task_xvk_dsw_z5">
                <title>T</title>
                <shortdesc>SDC</shortdesc>
                <taskbody>
                    <context>
                        <note type="note">
                            <ul>
                                <li>
                                    <p>ABV</p>
                                </li>
                            </ul>
                        </note>
                    </context>
                </taskbody>
            </task>

**Comment by raducoravu** [comment]
This second case seems to be related to the fact that the "context" element is also a "section" element so the "calculate_span_depth" template computes too many end tags to output for it.

**Comment by robander** [comment]
The ODT transformation type has a lot of issues (as indicated above), and is not regularly maintained; if this issue is still causing problems, it should be re-opened in the ODT repo: https://github.com/dita-ot/org.dita.odt
