### ISSUE TITLE
Add type boolean to param element in DITA-OT 3.x

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2281]
If the DITA-OT 3.x is going to use typified variables in XSLT, the `@type` of the `<param>` element should support primitive data types, e.g. `boolean`.

**Comment by jelovirt** [comment]
[Ant XSLT][1] already has this.

[1]: https://ant.apache.org/manual/Tasks/style.html

**Comment by xephon2** [comment]
I mean the `@type` of the `<param>` element of the `plugin.xml` file.

**Comment by jelovirt** [comment]
There's already the `enum` type that would allow you to define the value space to be either `true` or `false`.
