### ISSUE TITLE
Toolkit Log Should List Referenced But Undefined Keys

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2282]
Although there might be situations where it is expected that some keyrefs point to keys that are not defined, it is probably far more frequent that content creators need to know about undefined key references. They can't rely on authoring tools to provide this information because the authoring scope could easily differ from that of publication.

Some closed issues suggest that in the past, the toolkit logged such instances, but recent versions (1.8, 2.0) do not.

It might be desirable to have the option to suppress such logging by a build parameter or to log these as information-only rather than warnings.

**Comment by robander** [comment]
I've had a number of my users request this as a way to diagnose missing keys. (They generally assume this should be an error.)

**Comment by jelovirt** [comment]
We already have [`DOTJ047I`][1], doesn't that solve this?

[1]: http://www.dita-ot.org/dev/user-guide/DITA-messages.html#msgs__DOTJ047I

**Comment by xephon2** [comment]
Maybe [DOTJ047I](http://www.dita-ot.org/dev/user-guide/DITA-messages.html#msgs__DOTJ047I) could also output the name of the file, where the unresolvable key is defined.

**Comment by jelovirt** [comment]
It already does

```
[keyref] file:/Volumes/tmp/topic.dita:7:45: [DOTJ047I][INFO] Unable to find key definition for key reference "b" in root scope. The href attribute may be used as fallback if it exists
```

**Comment by robander** [comment]
Not sure why I forgot about that current info message - I think over time we've had and removed messages like this.

**Comment by shaneataylor** [comment]
Yep, the messages are there; I wasn't seeing them for an unrelated reason.
