### ISSUE TITLE
This-topic fragment IDs not resolved correctly in conreffed content

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2284]
Using this test case: https://github.com/dita-community/dita-test-cases/tree/master/this-topic-fragment-ids

With the 2.2.3 release I get the following results:

HTML: this-topic fragment IDs within conreffed elements are not resolved correctly. It looks like they are being resolved to the element as it would exist in the HTML produced from its containing topic, rather than to the element as it would be in the HTML for the referencing topic.

The references are resolved correctly when the topic containing the this-topic reference is processed directly.

PDF: Same result: references within conreffed elements are not resolved, same reference is resolved when processed directly.

[dita-ot-logs.zip](https://github.com/dita-ot/dita-ot/files/197987/dita-ot-logs.zip)

**Comment by shaneataylor** [comment]
I see the same failure in 2.2.4. Some additional detail:

In `source.dita`:
```xml
<step id="click_integrate">
  <cmd>Click <uicontrol><text conref="#./lti_text"/> integration</uicontrol>.</cmd>
</step>
```

In `context.dita`:
```xml
...
<text id="lti_text">Canvas</text>
...
<step conref="source.dita#source/click_integrate"><cmd/></step>
```

- If a target for the **lti_text** conref can be found in `source.dita`, it is used and no error is thrown
- Otherwise, the **lti_text** conref is not resolved and an error is thrown

Both of these behaviors are incorrect.

Per the [specification](http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/handling-xref-and-conref-within-topics.html#handling-xref-and-conref-within-topics):

> processors _MUST_ resolve it relative to the location of the content reference (referencing context)

This is not happening.

**Comment by raducoravu** [comment]
+1 Our client encountered the same problem here:

https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=11595&p=46237#p46237

Attached sample project:
[self-link-to-step.zip](https://github.com/dita-ot/dita-ot/files/1903132/self-link-to-step.zip)

**Comment by drmacro** [comment]
I added a new test case to the test set here: https://github.com/dita-community/dita-test-cases/tree/master/this-topic-fragment-ids  and rested with OT 3.2.1

Test case 2, a link from inside the conref to a location outside the conref works, but the other two cases fail.

It looks like test cases 1 and 3, *almost* work but the generated IDs are not identical between the link and the IDs on the target elements (although they are similar).

Not sure what code is involved but from the nature of the failure it looks like it is probably not too hard to fix (looks like generate-id() is being used in one context and not in the other).
