### ISSUE TITLE
Implement release management domain processing for org.dita.html5

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2286]
I implemented the processing of the `relmgmt-d` elements for `org.dita.pdf2` (https://github.com/dita-ot/dita-ot/pull/2248). Here I used a custom `<booklist>` element to hook the creation of a change-history, compareable to `<figurelist>` or `<toc>`.

``` xml
<booklists>
  <booklist type="change-historylist"/>
</booklists>
```

Now I think about how to implement the processing for  `org.dita.html5`. Personally I'd like to hook the creation of the change-history by element, as I did for `org.dita.pdf2`. Unfortunately there is no pendant for `bookmap` (no `webmap`). The `bookmap` is not intended for webhelp publishing (but it works fine), so hooking on `<booklist type="change-historylist"/>` may not be the best decision. And there is no pendant for the `<booklist>` element in the standard DITA Map.

> **Info** The `<booklist>` element is a specialization of `<topicref>`.

@jelovirt suggested to discuss this in a public manner (in a Github issue), because this is a design decision.

I'd personally prefer if processing is toggled technically equal, independent of the transtype. Why should I set an Ant property for HTML but use an XML element for PDF to hook the same processing? This feels weird to me. But the `pdf2` is more focussed on element hooks and the `xhtml` types are more focussed on Ant property hooks.

What do you think? How would you like to have this implemented?

**Comment by xephon2** [comment]
To clarify: This whitepaper explains, how the Release Management domain elements should be processed: [White Paper: Release Management Domain](https://lists.oasis-open.org/archives/dita-adoption/201411/msg00000/Release_Management_WP.pdf)

**Comment by xephon2** [comment]
I still would like to do it. Status is unchanged, I need requirements.

**Comment by robander** [comment]
Not sure why the stale bot closed this after the comment from @xephon2 -- reopening it now.
