### ISSUE TITLE
build_dita2htmlhelp.xml should use environment variable

### ISSUE THREAD

**Issue by hscherzer** [dita-ot/dita-ot#2288]
Line 30 of **build_dita2htmlhelp.xml** codes

    <target name="use-init.hhcdir" unless="env.HHCDIR">
    <condition property="hhc.dir"
                      value="C:\Program Files (x86)\HTML Help Workshop"
                      else="C:\Program Files\HTML Help Workshop">
      <available file="C:\Program Files (x86)\HTML Help Workshop" type="dir"/>
    </condition>
    <available file="${hhc.dir}/hhc.exe"
               property="HTMLHelpCompiler"
               value="${hhc.dir}${file.separator}hhc.exe"/>
  </target>

which should actually use

```
<target name="use-init.hhcdir" unless="env.HHCDIR">
    <!--HSX Flaw in Dita-OT ... do not use C: but use ${env ...} -->
    <condition property="hhc.dir"
           value="${env.ProgramFiles(x86)}\HTML Help Workshop"
           else="${env.ProgramFiles)}\HTML Help Workshop">
      <available file="${env.ProgramFiles(x86)}\HTML Help Workshop" type="dir"/>
    </condition>
    <available file="${hhc.dir}/hhc.exe"
               property="HTMLHelpCompiler"
               value="${hhc.dir}${file.separator}hhc.exe"/>
  </target>
```
The hard assignment to C:\ ... might work for 99% of Windows installations and is probably there for some reason in the past. However, my OS is on D:\ (for good reasons) and nevertheless it seems appropriate to me that the environment variables are used.

The severity of this issue is of course moderate, but I think it's a good time for the small change.
Cheers ... Helmut

**Comment by robander** [comment]
Fixed with https://github.com/dita-ot/dita-ot/commit/d7f0daae6be146cc702900f0c4296f7ce9d728fc
