### ISSUE TITLE
Jetpack support

### ISSUE THREAD

**Issue by carlosevia** [dita-ot/dita-ot#2291]
Sorry... I had to request it.
;-)

**Comment by infotexture** [comment]
:rocket:

**Comment by lief-erickson** [comment]
+1

I'm also in need of a jetpack.

**Comment by jelovirt** [comment]
The work takes place in a pull request https://github.com/jelovirt/dita-ot/tree/feature/jetpack

**Comment by jelovirt** [comment]
Closing as we'll get there some day.
