### ISSUE TITLE
PDF2 drops ® trademark symbols in footers & MiniToCs

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2293]
If a product name variable is defined in a `<keyword>` with a registered trademark ® symbol as follows, the product name appears correctly in body text when referenced via a key reference such as `<keyword keyref="productname_long"/>`:

``` xml
<keydef keys="productname_long">
  <topicmeta>
    <keywords>
      <keyword>A&amp;P<tm tmtype="reg"/>ProductName&#xA0;S</keyword>
    </keywords>
  </topicmeta>
</keydef>
```

However, the symbol is **dropped** when referenced in PDF footers via `<param ref-name="prodname"/>`, which picks up the content of the `<prodname>` element in `<bookmeta>`, defined via a reference to the same key as:

``` xml
<prodinfo>
  <!-- $productName in footers = <prodname> element in topicmeta or bookmeta -->
  <prodname><keyword keyref="productname_long"/></prodname>
</prodinfo>
```

With the product name defined in this fashion, the trademark symbol is _also_ dropped from any heading links in the chapter-level MiniTOCs when headings contain `<keyword keyref="productname_long"/>`.

If a literal registered trademark ® symbol is used in either `<keyword>` or `<prodname>`, the symbol renders as expected, but is not superscripted as it is when proper `<tm>` markup is used, which scales font size to 75% and applies a 20% baseline shift via the `tm__content` attribute set.

**Comment by infotexture** [comment]
@dita-ot/tc: Since the `<tm>` element is not permitted within `<prodname>`, the client is using the key reference as a workaround.

Does anyone recall the rationale for excluding `<tm>` from the `<prodname>` content model? Seems like a natural candidate for inclusion…

**Comment by infotexture** [comment]
@robander Do you think this is another case of “opinionated” trademark processing like #2065, or just  inconsistent text-only processing in some places, but not in others?

**Comment by robander** [comment]
I suspect that with the content model not allowing trademarks, the processing assumes it's safe to treat as plain text. I'm not sure I've ever seen the contents of `<prodname>` used outside of the cover / front matter, and at least with typical use in our own products, we don't use the TM symbol along with the product name in those locations. 

For what it's worth - I've never seen the `<tm>` element used like this:

```A&amp;P<tm tmtype="reg"/>ProductName&#xA0;S```

That certainly wasn't the intent -- if that's being used as a way to generate the TM symbol in all cases, I think it's better just to use the character. The intent was that it be used more like this, assuming A&P is the actual trademark:

```<tm tmtype="reg">A&amp;P</tm> ProductName```

Including the actual trademarked text inside of the element is what lets some process determine whether the contents should be marked with a symbol. The common practice we've aimed for is "Mark first occurrence", which probably wouldn't help you here, because that would mean you only get one mark across the entire PDF.

**Comment by infotexture** [comment]
@robander Yes, I noticed the client's use of `<tm tmtype="reg"/>` seems a bit … creative and not exactly as intended in the spec. 

My first thought before posting the issue was whether that might be part of the problem, but a quick test with the conventional markup yielded the same results, so it seems that's not the problem here.

**Comment by robander** [comment]
Probably worth checking into - it may just be that the header/footer code isn't set up to handle trademarks. But my own expectation would be that this does not get marked. My own expectation for trademarks is that they just get marked the first time they appear in a PDF (it's just the way we've done things for decades now). Processing for "first occurrence" will hit this trademark each time, and treat it as a trademark of "" (empty string). After the first time it marks empty string, I would not expect it to be marked again.

**Comment by robander** [comment]
This comes from the fact that the product name is put into a variable for use all around the PDF code:
```
<xsl:variable name="productName">
        <xsl:variable name="mapProdname" select="(/*/opentopic:map//*[contains(@class, ' topic/prodname ')])[1]" as="element()?"/>
        <xsl:choose>
            <xsl:when test="$mapProdname">
                <xsl:value-of select="$mapProdname"/>
...
```

My first instinct was to change that from `value-of` to process the contents with the `text-only` mode. That would probably be a good change, even ignoring the `<tm>` issue. But, that mode doesn't currently add anything for `<tm>` elements. And at least for our case, we wouldn't want it to -- we're pretty strict about marking first-occurrence only, so having ™ appear in every footer would be frowned at.

If we do change this to use `text-only` mode when setting up the variable, it would then be pretty easy for you to add a rule in your own customization that preserves `<tm>` based trademark characters in all instances of the product name. (By easy, I mean 3 or 4 lines of XSL.) This would also prevent them from suddenly appearing for other companies with rules like mine. Would that be a good way to resolve this?

**Comment by infotexture** [comment]
If the fix you're proposing would produce the same results as the current code (drop trademark symbols in footers & MiniToCs) but make it easier for users to customize processing to render trademark symbols everywhere, that sounds like a good solution.

We might want to provide sample code that could be used to preserve the trademark characters —either here in the issue thread, or directly in the _Release Notes_.

**Comment by robander** [comment]
Pushed up the suggested fix. With that in place, the override to get trademark symbols in every text-only context that currently drops them would be:
```
<xsl:template match="*[contains(@class,' topic/tm ')]" mode="dita-ot:text-only">
      <xsl:apply-templates mode="dita-ot:text-only"/>
      <xsl:choose>
        <xsl:when test="@tmtype='service'">
          <xsl:text>&#8480;</xsl:text>
        </xsl:when>
        <xsl:when test="@tmtype='tm'">
          <xsl:text>&#8482;</xsl:text>
        </xsl:when>
        <xsl:when test="@tmtype='reg'">
          <xsl:text>&#174;</xsl:text>
        </xsl:when>
      </xsl:choose>
    </xsl:template>
```

**Comment by drmacro** [comment]
I would make the tm case the otherwise so that there's no chance of not getting a result.

**Comment by robander** [comment]
@drmacro the `<tm>` element currently requires `@tmtype`, with one of those three values, so if your input is valid, it's not possible to end up without a result. That said ... making the TM case into an otherwise would make the code look cleaner. (FWIW, I just copied the `xsl:choose` from the existing `<tm>` element logic.)
