### ISSUE TITLE
ANT variables in PDF renderer config files

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2295]
Is there any reason to not use ANT variables in PDF renderer config files?

I'm writing a custom PDF plug-in, and I would like to include a custom RenderX XEP config file in the plug-in, rather than in its usual location inside the XEP installation. This is to define custom fonts.

However, the config file includes references to files and directories in the standard installation.

Standard file:

```xml
<options>
    <option name="LICENSE" value="license.xml"/>
    <option name="TMPDIR" value="none"/>
    <option name="BROKENIMAGE" value="images/404.gif"/>
    <option name="LOGO" value="images/logo-renderx.svg"/>
    <option name="STAMP_PNG" value="images/stamp-renderx.png"/>
```

Becomes:

```xml
<options>
    <option name="LICENSE" value="${xep.dir}/license.xml"/>
    <option name="TMPDIR" value="none"/>
    <option name="BROKENIMAGE" value="${xep.dir}/images/404.gif"/>
    <option name="LOGO" value="${xep.dir}/images/logo-renderx.svg"/>
    <option name="STAMP_PNG" value="${xep.dir}/images/stamp-renderx.png"/>
```

Using `${xep.dir}` is a whole lot easier than setting the actual file path several times over.

I have tried this out, and it seems to work. However, OT 1.8.5 includes this in the log file:

```
transform.fo2pdf.xep:
     [echo] Maximum Java memory: -Xmx384m
     [java] Could not create XEP formatter: com.renderx.xep.lib.LicenseException: Cannot read license file 'file:/Applications/oxygen/frameworks/dita/DITA-OT/plugins/com.adaptive.pdf/xep/${xep.dir}/license.xml'
     [java] java.io.FileNotFoundException: /Applications/oxygen/frameworks/dita/DITA-OT/plugins/com.adaptive.pdf/xep/${xep.dir}/license.xml (No such file or directory)
```

Please advise if I'm doing something I shouldn't!

**Comment by jelovirt** [comment]
The reason for not using Ant property references in XEP configuration file is simply that they are not processed by Ant. If you want to process them, you'd need to some code to do the processing.

**Comment by DJBHollis** [comment]
OK, got it - thanks.

Is there a way to somehow split a XEP config file, possibly using a catalog.xml file?

In this way, I could have a partial config file with the custom fonts, and then point to the standard config file for all the standard items.

One of this issues, I imagine, would be that the OT only recognises a single config file.

But, then again, would RenderX XEP accept a split config file?

**Comment by jelovirt** [comment]
That is completely XEP specific. I suggest you take it up with their support and if there's something DITA-OT can do to make this easier, let us know.

**Comment by robander** [comment]
Looks like this is resolved from the DITA-OT perspective (Jarno answered the original question, and follow-up appears to be an XEP issue for now). Marking closed.
