### ISSUE TITLE
DITA-OT 2.2.3: Build.xml not found

### ISSUE THREAD

**Issue by KptainBiwouak** [dita-ot/dita-ot#2297]
Starting from DITA-OT 2.2.3,  I' m trying to generate PDF output from DITA package, but I'm facing following issue.

Buildfile:  ...............\DITA-OT\build.xml does not exist!

However build.xml exists at root path of DITA-OT.

What is wrong?

I've used following command line:
dita -i AN/AN446.ditamap -f pdf -o AN/DITA-OT

Thanks for your help? Do I have to write an other build.xml or to change output format?

**Comment by xephon2** [comment]
Hi, you probably want to call the transtype `pdf2`. So the correct command would be:

```
dita -i AN/AN446.ditamap -f pdf2 -o AN/DITA-OT
```

Anyway, you have another problem, because `build.xml does not exist!` refers to another problem. Maybe there is something wrong with your environment variable. To make sure that the DITA-OT works, call the `dita` command directly from the `~/dita-ot/bin` directory.

**Comment by jelovirt** [comment]
Could you add more information, like DITA-OT installation directory, directory where the command is ran, PATH variable, whether DITA_HOME variable is set, complete log etc.

**Comment by KptainBiwouak** [comment]
I've restarted using "pdf2" format instead of "pdf" but without succeeded.
Same issue by using full path for accessing dita.

Path to DITA-OT is: C:\GFMWK\tools\DITA-OT
build.xml file exists from this folder.

Command is launched from:
C:\TECHDOC

Do I have to use DOS syntax for command line or POSIX syntax as I'm using TCSH terminal base from Cygwin?

Other information:
 C:\GFMWK\tools\DITA-OT\bin is defined in PATH
DITA_HOME: not defined
JAVA_HOME: C:\GFMWK\tools\jdk\jre

Let me know if you need more details,

**Comment by jelovirt** [comment]
Could you past the _full_ log from running the command? Run `dita` command with -v or -d option.

**Comment by KptainBiwouak** [comment]
Same results: nothing new is reported from command line by using -d or -v options

I've tried both syntax (DOS & POSIX) not knowing exactly which one is expected by dita command, even if I guess all parameters have to be compliant with DOS syntax:
![snapdita2pdf_issue](https://cloud.githubusercontent.com/assets/13914766/14493980/c0d721e8-0188-11e6-97ac-618fcf305888.PNG)

**Comment by jelovirt** [comment]
Most likely a Cygwin issue.

**Comment by KptainBiwouak** [comment]
Yes, you're right. It works from DOS prompt. I just have to convert arguments to DOS syntax.
