### ISSUE TITLE
pdf2 xsl folder moved

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2299]
Hi,

I'm sorry, but I couldn't easily find the issue or issues that led to the xsl folder being moved from `cfg/fo/xsl` to `xsl`.

Is it still possible to overide the style sheets in this folder, and if so, how?

Would I still use `cfg/fo/xsl/custom.xsl`, and import a modified copy of the original stylesheet?

The last time I hacked a PDF customisation was around OT 1.5, so I'm doing a lot of catching up!

Many thanks,
David

**Comment by xephon2** [comment]
I'd recommend to generate a new plugin using the [dita-generator](https://dita-generator-hrd.appspot.com/). A clean plugin is probably a good starting point to examine new patterns and structures.
