### ISSUE TITLE
Fatal Error When Related Link Text Includes <tm>

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2303]
This worked fine as late as OT 2.1.2. When I moved to 2.2, however, my builds broke with the following message in my log:

> /Users/staylor/Dev/dita_source_files/build/deps/DITA-OT2.2.4/build.xml:41: The following error occurred while executing this line:&#xa;/Users/staylor/Dev/dita_source_files/build/deps/DITA-OT2.2.4/plugins/org.dita.xhtml/build_general.xml:162: Fatal error during transformation using /Users/staylor/Dev/dita_source_files/build/deps/DITA-OT2.2.4/plugins/org.dita.html5/xsl/dita2html5.xsl: In the key() function, the node supplied in the third argument (or the context node if absent) must be in a tree whose root is a document node; SystemID: file:/Users/staylor/Dev/dita_source_files/build/deps/DITA-OT2.2.4/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl; Line#: 1128; Column#: -1

After much experimenting, I discovered this was breaking when a `<tm>` tag was present in the link text of a related link, as in this example.

``` xml
<relrow>
    <relcell>
        <topicref href="c_a_allow_cookies.xml"/>
    </relcell>
    <relcell>
        <topicref href="c_a_blackboard_3rd_party_cookies.xml">
            <topicmeta>
                <linktext>Enable Third-Party Cookies for <ph><tm tmtype="reg" tmowner="Blackboard, Inc."
                            trademark="blackboard">Blackboard</tm></ph></linktext>
            </topicmeta>
        </topicref>
    </relcell>
</relrow>
```

**Comment by infotexture** [comment]
Looks like this was resolved in #2394.
