### ISSUE TITLE
The dita command interprets args.filter as relative to the OT

### ISSUE THREAD

**Issue by dagoss** [dita-ot/dita-ot#2306]
Create a file `myproject.properties`. In this file, specify the `args.filter` properties.

    
    args.filter=ditavals/myfilter.ditaval

When processing the ditamap, specify this properties file using the `-propertyfile` argument.

    $ dita -i mymap.ditamap -f pdf2 -propertyfile myproject.properties

The args.filter is interpretated as being relative to the `dita` build script in the OT. (e.g. /path/to/dita-ot/ditavals/myfilter.ditaval). I would expect the property to be resolved relative to the location where the `dita` command was run.

**Comment by jelovirt** [comment]
Backwards compatibility. If you use the command line argument `-filter`, that is relative to the current directory; if you use the Ant property `args.filter`, it will be relative to the DITA-OT installation directory.

This will probably change in DITA-OT 3.0

**Comment by eerohele** [comment]
In the meantime, one possible workaround is to use the built-in `${user.dir}` Ant property in `myproject.properties`:

```properties
args.filter = ${user.dir}/ditavals/myfilter.ditaval
```

Of course, that requires you to run the `dita` command in the same directory where `myproject.properties` is, so it might not always be what you want.

Another option is to pass the `basedir` property:

```bash
$ dita -i mymap.ditamap -f pdf2 -propertyfile myproject.properties -Dbasedir=.

**Comment by dagoss** [comment]
@eerohele Thanks. Passing the `basedir` to the dita call results in the behavior I was expecting and is a good workaround.
