### ISSUE TITLE
Huge performance drop down when using huge database topics.

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2307]
Hi, I noticed a huge performance drop down, if a huge database topic (a topic containing only blocks for reference) is used instead of multiple smaller database topics containing the same amount of blocks. The performance drop down is immense.

Test case:
[2307.zip](https://github.com/dita-ot/dita-ot/files/223172/2307.zip)

Build time for comparison using `DITA-OT 2.2.4`:
`map1.ditamap`: 1 database topic with 10000 dlentry elements: Total time: 428 minutes 56 seconds
`map2.ditamap`: 4 database topics with 2500 dlentry elements: Total time: 25 minutes 3 seconds
`map3.ditamap`: 10 database topics with 1000 dlentry elements: Total time: 3 minutes 56 seconds

Build time for comparison using `DITA-OT 1.8.5`:
`map1.ditamap`: 1 database topic with 10000 dlentry elements: Total time: 714 minutes 38 seconds

**Comment by xephon2** [comment]
@eerohele, thanks a lot. :smiley:  :+1: 
Awesome!!! Your XSLT changes boost our publication time from > 60 min down to < 2 min.

**Comment by infotexture** [comment]
@robander The fix was merged to `hotfix/2.2.5` with #2309. 

Can you add the milestone so it appears in the list of issues fixed in the release?
