### ISSUE TITLE
Remove unimplemented parameter extension points from HTML5 plug-in

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2312]
The HTML5 plug-in declares two "parameter" type extension points:
```
  <extension-point id="dita.conductor.html5.param" name="XHTML XSLT parameters"/>
  <extension-point id="dita.conductor.html5.toc.param" name="HTML/XSLT XSLT parameter"/>
```
However, these can't be used because they aren't implemented in an Ant build template `<xslt>` step. That wasn't done (rightly, I think) because the HTML5 plug-in uses the base HTML Ant templates.

- Implementing the missing extension-points would require duplicating the templates from the base HTML plug-in, which would be a maintenance problem and just bad generally.
- Implementers who want to add parameters to the HTML5 transformation can instead:
  - require the base HTML plug-in as well as the HTML5 plug-in
  - extend the base HTML plug-in's parameter extension points
- Keeping the un-implemented HTML5 extension points obscures that fact and creates confusion because implementers should rightly expect these extension points to work.

I'll submit a PR to remove these.

**Comment by robander** [comment]
Closed with #2314

**Comment by infotexture** [comment]
See also #2181.

**Comment by robander** [comment]
Hmm - I did check with Jarno before adding this in to 2.2.5, and he was fine with it, while planning to re-implement these in 3.0.
