### ISSUE TITLE
OT 1.8.5 - Nested UL not displayed correctly in PDF

### ISSUE THREAD

**Issue by juliovaz** [dita-ot/dita-ot#2334]
Nested ULs do not indent or change widgets (though I understand the widgets might be a configuration issue).
This code:
`<ul>
<li>Some content
<ul>
<li>Second level</li>
<li>Second level<ul>
<li>third level</li>
<li>third level</li>
</ul>
</li>
</ul>
</li>
</ul>`
Does not display as I would expect. Am I missing something?

**Comment by robander** [comment]
@juliovaz this one opened and closed really quickly, so just double checking - did you intend to mark it closed?

**Comment by juliovaz** [comment]
Yes. I discovered that start indents in the configuration was causing the
issue. I have to figure out how to get additional indenting without killing
the display.
