### ISSUE TITLE
@keyscope on the root <map> element causes builds to fail

### ISSUE THREAD

**Issue by leighw** [dita-ot/dita-ot#2339]
It seems that using `@keyscope` on the root `<map>` element causes builds to fail. (Put aside for the moment the fact that a keyspace on `<map>` is a bad practice. The spec allows it, so it should work: "Map authors define  the boundaries for key scopes by specifying the `@keyscope` attribute on `<map>` elements, `<topicref>` elements, or elements that are specializations of `<map>` or `<topicref>`. ")

Sample map:

```xml
<map keyscope="widget">
   <title>Keyscope test 4</title>
   <keydef keys="module">
      <topicmeta>
         <keywords>
            <keyword>Widget</keyword>
         </keywords>
      </topicmeta>
   </keydef>
   <topicgroup keyscope="gadget">
      <keydef keys="module">
         <topicmeta>
            <keywords>
               <keyword>Gadget</keyword>
            </keywords>
         </topicmeta>
      </keydef>
      <topicref href="topic1.xml" keyscope="doodad">
         <keydef keys="module">
            <topicmeta>
               <keywords>
                  <keyword>Doodad</keyword>
               </keywords>
            </topicmeta>
         </keydef>
      </topicref>
   </topicgroup>
</map>
```

With a simple keyref such as `<ph keyref="module"/>` in topic1.xml, the build fails. With a pathed keyref such as `<ph keyref="widget.gadget.doodad.module/>` in topic7.xml, the build still fails.

Removing the keyspace definition from the `<map>` and using `<ph keyref="module"/>` in topic1.xml, the key resolves to "Widget," as expected. Using `<ph keyref="gadget.doodad.module"/>`, the key resolves to "Doodad," as expected.

**Comment by infotexture** [comment]
Looks like the XML portions of your comment were lost.

You should be able to edit your previous comment and wrap inline code with backtick quotes (\`) like this: `` `<xml>` `` or use a [fenced code block](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for syntax highlighting.

**Comment by robander** [comment]
Heh - I just edited the comment to add that as @infotexture was suggesting it. So I guess @leighw no need to update but good to know for next time.

**Comment by robander** [comment]
@leighw which version of DITA-OT are you using to produce the failure?

**Comment by drmacro** [comment]
I'm not sure specifying @keyscope on map elements is necessarily bad practice. On root maps it basically has no effect (because all the keys defined in the map will be within the named scope so unqualified key references will resolve).

On submaps it can make sense to specify @keyscope on the map element, which can then be used as the scope name for references to keys within that submap from outside the submap's context. That ensures that the submap is always a separate scope even if the author of the using map does not specify a scope on the reference to the submap.

**Comment by leighw** [comment]
OT 2.2.2, 2.2.3, 2.2.4.

Do I still need to add the backtick quotes or no?

**Comment by robander** [comment]
No need to add backtick quotes -- I edited your initial issue to add them. [I often do that just to help myself read issues, but for regular contributors I should actually point out the syntax like @infotexture did.]

**Comment by raducoravu** [comment]
The transformation fails with a NullPointerException like:

            BUILD FAILED
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\build.xml:41: The following error occurred while executing this line:
            D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.base\build_preprocess.xml:270: java.lang.NullPointerException
            	at org.dita.dost.module.KeyrefModule.walkMap(KeyrefModule.java:154)
            	at org.dita.dost.module.KeyrefModule.walkMap(KeyrefModule.java:176)
            	at org.dita.dost.module.KeyrefModule.collectProcessingTopics(KeyrefModule.java:124)
            	at org.dita.dost.module.KeyrefModule.execute(KeyrefModule.java:81)
            	at org.dita.dost.pipeline.PipelineFacade.execute(PipelineFacade.java:68)
            	at org.dita.dost.invoker.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:193)
            	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
            	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
            	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by eerohele** [comment]
Since `@keyscope` on the root element has no effect, I think the simplest solution is simply not process the root element when looking for key scopes:

```diff
diff --git a/src/main/java/org/dita/dost/module/KeyrefModule.java b/src/main/java/org/dita/dost/module/KeyrefModule.java
index 8e90ebc..1258119 100644
--- a/src/main/java/org/dita/dost/module/KeyrefModule.java
+++ b/src/main/java/org/dita/dost/module/KeyrefModule.java
@@ -122,7 +122,9 @@ final class KeyrefModule extends AbstractPipelineModuleImpl {
         final List<ResolveTask> res = new ArrayList<>();
         res.add(new ResolveTask(rootScope, job.getFileInfo(job.getInputMap()), null));
         // Collect topics from map and rewrite topicrefs for duplicates
-        walkMap(doc.getDocumentElement(), rootScope, res);
+        for (final Element child : getChildElements(doc.getDocumentElement(), MAP_TOPICREF)) {
+            walkMap(child, rootScope, res);
+        }
         // Collect topics not in map and map itself
         for (final FileInfo f: fis) {
             if (!usage.containsKey(f.uri)) {
```

Fixes the NPE, at least.

**Comment by raducoravu** [comment]
The fix still takes into account keyscopes set on submaps, right? Because they make sense.

**Comment by eerohele** [comment]
If I'm understanding the code correctly, it should, because the `<submap>` element has the ` map/topicref ` class and `walkMap` recurses into and looks for `@keyscope` in all elements with ` map/topicref `.

Of course, the more elegant solution is probably to modify the code not to throw an NPE if you give it a DITA map — didn't get that far yet, though.

(Also, I'm having some trouble running the integration tests at the moment so I didn't check those yet.)

**Comment by jelovirt** [comment]
Fix NPE root cause, not with a workaround.
