### ISSUE TITLE
Logic bug in findString

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2345]
Through 2.2.5, the findString template has this code:

```xml
<xsl:when test="exists($l)">
  <xsl:variable name="stringfile" select="$stringFiles[@xml:lang = $l]/@filename" as="xs:string*"/>
  <xsl:variable name="str" as="element()*">
    <xsl:for-each select="$stringfile">
      <xsl:sequence select="document(., $stringFiles[1])/*/*[@name = $id or @id = $id]"/><!-- strings/str/@name opentopic-vars:vars/opentopic-vars:variable/@id -->
    </xsl:for-each>
  </xsl:variable>
```

I've highlighted `$stringFiles[1]`. I think this must be wrong because the `$stringfile` variable is a list of filenames that is then iterated by the for-each but the for-each will only ever use the first value in `$stringFiles`. I think the correct behavior (or intended behavior) is to use the current item in the for-each loop.

The result of this bug should be that overrides are never found or are found if and only if the override happens to be the first one found.

**Comment by jelovirt** [comment]
The `$stringFiles[1]` to define the base URI of the `stringfile` relative URI and it's the same for all values in `$stringfile`. I don't see a bug.

**Comment by robander** [comment]
I've got output that is pulling strings from multiple (pre-integration) variable files for the same language, so I think the code is working properly even if it looks odd.

**Comment by drmacro** [comment]
Right you are. I misread the code. Sorry for the misreport.
