### ISSUE TITLE
Ship the ANT contrib library along with the core ANT libraries

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2346]
The ANT contrib library "ant-contrib-1.0b3.jar" allows more flexibility when writing the DITA OT ANT build files, for example modifying the value of an ANT parameter using a regular expression and assigning that value to another parameter, iterate using some kind of for task.

**Comment by jelovirt** [comment]
My vote is 👎 because the core code in DITA should not implement features at Ant layer, but rather in XSLT or Java. (This has been discussed earlier, Ant is the first technology/library we should remove if possible.)

**Comment by jelovirt** [comment]
A plugin can contribute Ant contrib library, so this can be done as a plugin.

**Comment by raducoravu** [comment]
Yes, actually I did this already for our Webhelp plugin.

**Comment by robander** [comment]
I think I'm neutral on this. I understand @jelovirt's objections but also know that I regularly use this as a plugin; guessing @raducoravu and I are not the only ones.

**Comment by markgif** [comment]
I use the Ant contrib library often outside of the OT. I like its for loop capability and other things.

**Comment by jelovirt** [comment]
The problem I have with Ant contrib is that is basically makes it impossible to optimize preprocessing code automatically. If we just use default Ant, it has the functionality that as was intended for, a built configuration language. Ant contrib adds programming language functionalities to Ant. While it's convenient to have those when you use Ant, they're awful when compared to "real" programming languages.

My long term goal has been to have as little dependency to Ant as possible and use Ant only as a configuration language. If we decide to push Ant contrib as a bundled library, we can't take it out later on without breaking backwards compatibility. Thus, I think this should be done as a plugin, not as core functionality.

**Comment by robander** [comment]
@jelovirt has convinced me. It helps that, for anybody who _really_ wants to use it, antcontrib on its own is one of the easier plugins to create - just use `plugin.xml` to declare the JAR file. But don't tell Jarno you're doing it...

**Comment by raducoravu** [comment]
Ok, I guess I'll close this one
