### ISSUE TITLE
Support additional definition list rendering options

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2349]
The default definition list output differs significantly between HTML & PDF output, which often confuses new users. 
- In HTML output for `<dl>` & `<parml>`, terms are rendered on one line, with definitions on a line below. 
- In PDF output, definition list entries are converted to table rows, with term and definition in columns.
- Parameter list entries render in PDF with an style reminiscent of HTML, with indented definitions.

We should consider adding a parameter that would toggle definition list rendering between the default (table) and an indented style as used for `<parml>` or [alternative presentation styles](https://github.com/dita-ot/dita-ot/issues/2198#issuecomment-171953011) such as those provided by the [dita-generator](http://dita-generator.elovirta.com/#p4).

This would permit users to configure the rendering style that best matches their needs and allow them to sync presentation between HTML & PDF, or render  `<dl>` & `<parml>` consistently.

While some users [prefer](https://github.com/dita-ot/dita-ot/issues/2198#issuecomment-171953766) the default tabular output to conserve vertical space in simple scenarios where term and definition are both short, this format actually requires **more** space in lists where definitions are significantly longer than their terms.

**Comment by jelovirt** [comment]
While I'm sympathetic towards this feature request, I'm worried about feature bloat. If we add this, we have three different output alternatives to maintain. Same goes for three different alternatives for e.g. glossary or alternative output for index.

I would really prefer PDF2 to implement the basic functionality for producing PDF from DITA and then allow other plugins the add alternative layout and output.

**Comment by xephon2** [comment]
@jelovirt Does that mean you would like to ship another PDF plugin that is based on PDF2 with the core OT?

**Comment by jelovirt** [comment]
Pretty much yes. Just like the current default output should be a separate plugin and the core PDF2 plugin would be pretty much unstyled. But not sure where the sweet spot is. I prefer modular approach where the end product is constructed from multiple plugins. I'm pretty sure most OT users would prefer to just get rid of the whole plugin system and just change files in situ, but that's not sound approach from software development point of view.

**Comment by DJBHollis** [comment]
I certainly don't like the table form of `<dl/>`, and had also been thinking about a variable to switch between table and list form.

The problem with a table is that each `<dt/>` cell resizes to the length of its content, and it is not easy on the eye. It is actually quite awkward.

I also like the modular approach to PDF2. AS a starting point, it would be great to see the bookmap requirements separated from the basic ditamap and topic only processing.

**Comment by raducoravu** [comment]
+1 from our tech writer, nested dl lists look horrible with the current table representation.

**Comment by raducoravu** [comment]
:+1: from user on DITA Users List:
https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/40353
