### ISSUE TITLE
losts an "s" in word "resources" in line 8 of file "sample_xhtml.xml" for dita-ot-2.2.5

### ISSUE THREAD

**Issue by ericchenkai** [dita-ot/dita-ot#2362]
Hi, I have just downloaded dita-ot-2.2.5 from http://www.dita-ot.org/. 
Below error happens when I tried a quick demo.

I run:
`bin\ant -f `samples\ant_sample\sample_xhtml.xml`

Error:
```
BUILD FAILED
C:\dita-ot-2.2.5\samples\ant_sample\sample_xhtml.xml:17: C:\dita-ot-2.2.5\resource does not exist.

```
Fix:
Change "resource" into"resources" in the file "sample_xhtml.xml"
```
<copy todir="${dita.dir}/out/samples/web">
      <fileset dir="${dita.dir}/resource**s**" includes="index.html"/>
</copy>
```

**Comment by jelovirt** [comment]
Samples have been moved to docs repo already for 2.3, no point fixing this in 2.2.

**Comment by ericchenkai** [comment]
That is OK. Thanks.
