### ISSUE TITLE
Improve documentation of args.hdf

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2365]
It is possible to inject code into the HTML header using a hdf file, that can be passed using the `args.hdf` parameter. A hdf file must be a valid XML file. Therefore it needs to have a root element. So it is not possible to inject multiple elements.

**Valid**:
```xml
<link rel="stylesheet" type="text/css" href="flag-icon.min.css"><!----></link>
```

**Invalid**:
```xml
<link rel="stylesheet" type="text/css" href="flag-icon.min.css"><!----></link>
<script src="jquery.min.js"><!----></script>
```

But there is a template in `dita2htmlImpl.xsl` which unwraps a root `<div>` element, if it exists.

```xml
<!-- For header file processing, pull out the wrapping DIV if one is there -->
<xsl:template match="/div" mode="add-HDF">
  <xsl:apply-templates select="*|comment()|processing-instruction()|text()" mode="add-HDF"/>
</xsl:template>
```

**Valid**:

```xml
<div>
  <link rel="stylesheet" type="text/css" href="flag-icon.min.css"><!----></link>
  <script src="jquery.min.js"><!----></script>
</div>
```

Currently this is not explained in the docs, see [HTML-based output parameters](http://www.dita-ot.org/2.2/parameters/parameters-base-html.html) -> `args.hdf`.

@infotexture: Could you please explain that in the docs?

**Comment by robander** [comment]
Best to open this in the docs tracker: https://github.com/dita-ot/docs/issues
