### ISSUE TITLE
PDF2 pagination: Map type determination

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2377]
#2335, `root-processing.xsl`

`$mapType` currently has two values: `'bookmap'` or `'ditamap'`.

There is actually a third possibility which could be either `'noMap'` or `'topicOnly'`.

If this third option is recognised, it might be useful for processing topics to PDF.

It should, at least, make it easier to follow the logic.

**Comment by robander** [comment]
I can see how this might be useful. A new value would not cause the default processing to change in any way with today's code, though it's possible that a customization expecting only the current values `bookmap` and `ditamap` could fail when a new value is presented.

I think a value for topic as input would just be `topic`. This would also match the `$mapType` variable in the ODT code, though the ODT code is in no way a shining example of best practices.
