### ISSUE TITLE
Invalid ODT after conversion

### ISSUE THREAD

**Issue by wdonne** [dita-ot/dita-ot#2379]
Hello,

If you convert the DITA 1.3 specification source at http://docs.oasis-open.org/dita/dita/v1.3/os/part3-all-inclusive/dita-v1.3-os-part3-all-inclusive-dita.zip to ODT you get an invalid document, which can't be opened with LibreOffice. In fact the content.xml entity in it is not well formed XML.

These are the steps to reproduce it:

1) Unzip the downloaded file
2) Go to dita-v1/dita-1.3-specification-learningTraining
3) Run "dita -i dita-1.3-specification-learningTraining.ditamap -f odt -o <directory>"
4) Open the result in LibreOffice 5.

Best regards,

Werner.

**Comment by raducoravu** [comment]
Similar problem here:
https://github.com/dita-ot/dita-ot/issues/2272

XSLTs for ODT are quite dreadful to trace so I could not propose a fix for it.

**Comment by wdonne** [comment]
Did you try Saxon? It has good tracing functionality.

**Comment by raducoravu** [comment]
Usually an XSLT stylesheet cannot output not wellformed XML. The problem occurs when outputting unescaped text content in the XSLT stylesheet. This is something which is highly avoided but the ODT XSLs do that a lot in order to insert XML elements in some places. It's something basically un maintainable.

**Comment by wdonne** [comment]
I agree.

**Comment by robander** [comment]
The ODT transformation type has a lot of issues (as indicated above), and is not regularly maintained; if this issue is still causing problems, it should be re-opened in the ODT repo: https://github.com/dita-ot/org.dita.odt
