### ISSUE TITLE
keydef.xml is no longer being produced in the transformation temp folder

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2389]
The method "KeyrefModule.writeKeyDefinition" is not used from anywhere. There are still stylesheets, even in the DITA OT 2.x distribution which load (or used to load) this keydef.xml from the temporary files folder.
Am I missing something?

**Comment by raducoravu** [comment]
Any input on this?

**Comment by jelovirt** [comment]
I just removed all code that uses keydef.xml from HTML5 and that's what should happen with all transtypes. The keydef.xml is old code that is not generated or used anymore, as all transtypes will received resolved key references and the old keydef.xml format didn't support key scopes.

**Comment by raducoravu** [comment]
I agree, then you can close this one if you want.
