### ISSUE TITLE
Flagging does not work with specialized props attribute (XHTML, DITA OT 2.x)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2392]
It all started with this report:
https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=13226&p=38549#p38549

I tested with DITA OT 2.x and the flagging (setting a foreground color from the DITAVAL on a paragraph) no longer works.
My samples are here:

https://www.oxygenxml.com/forum/files/flaggingDoesNotWorkOnSpecialization.zip

Error in the console related to this:

```
        [preprocess_flag]   XTTE0505: Required item type of result of template ext-getrules is element(); supplied
        [preprocess_flag]   value has item type document-node()
        [preprocess_flag]   at xsl:call-template name="ext-gen-prop" (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/flagImpl.xsl#427)
        [preprocess_flag]   at xsl:call-template name="ext-getrules" (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/flagImpl.xsl#375)
        [preprocess_flag]   at xsl:call-template name="getrules" (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/flagImpl.xsl#85)
        [preprocess_flag]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/flagImpl.xsl#124)
        [preprocess_flag]      processing /topic/body[1]/p[2]
        [preprocess_flag]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/flagImpl.xsl#124)
        [preprocess_flag]      processing /topic/body[1]
        [preprocess_flag]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/flagImpl.xsl#80)
        [preprocess_flag]      processing /topic
        [preprocess_flag] Failed to transform document: Required item type of result of template ext-getrules is element(); supplied value has item type document-node()
```

**Comment by drmacro** [comment]
The current flagging processing is very, very broken. I have an open pull request where I am refactoring the code completely so that it works correctly and reflects modern XSLT practices. 

https://github.com/dita-ot/dita-ot/pull/2366

**Comment by raducoravu** [comment]
Also from what I think the flagging should also work directly with the @props attribute.

**Comment by drmacro** [comment]
Yes, my refactor of the code handles direct @props values correctly.

I've got this mostly working but i put it aside in order to focus on the topicpull and mappull refactors, which I was hoping to get into 2.3. But since those have also been targeted to 3.0, I'm working on higher priorities now.

**Comment by raducoravu** [comment]
:+1: We've had one more user trying to flag in the DITAVAL using the @props attribute.

**Comment by raducoravu** [comment]
👍 And yet another one of our users tried to flag in the DITAVAL using the @props attribute, which does not work at all.

**Comment by jelovirt** [comment]
Works in 3.0.1

**Comment by raducoravu** [comment]
I confirm this works with DITA OT 3.0.1.
