### ISSUE TITLE
The collection-type on DITA Map should affects all topics from the map

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2396]
Reading the DITA 1.3 documentation, it is not very clear if the collection-type attribute on a DITA map should cascade to all topicrefs from the DITA map or other referenced DITA map.
https://www.oxygenxml.com/dita/1.3/specs/archSpec/base/ditamap-attributes.html

So, for the next DITA map:

```
<map collection-type="sequence">
 <title>Sample DITA map</title>
 
 <topicref href="topic-A.dita">
  <topicref href="topic-A1.dita"/>
  <topicref href="topic-A2.dita"/>
 </topicref>
 
 <topicref href="topicB.dita"/>
</map>
```

I expected to find in the XHTML ouput the next links between topics:
topic-A --next--> topic-A1 --next--> topic-A2 --next--> topic-B
topic-B --prev--> topic-A2 --prev--> topic-A1 --prev--> topic-A

For the moment, only the topics from the first level of the DITA map are affected by this property:

topic-A --next--> topic-A1
topic-B --prev--> topic-A2

Should the collection-type value cascade to all topicrefs when it is set on a DITA map?

**Comment by robander** [comment]
The `@collection-type` attribute does not cascade within a map. It is not listed among the attributes that cascade: http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/cascading-in-a-ditamap.html

I think a link sequence like that makes sense for some scenarios, but is not the default behavior expected for this attribute.
