### ISSUE TITLE
Temporary files folder no longer interpreted as relative to base dir [DOT 2.3]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2398]
Looking at some tests we have on our side, there seems to be a regression in DITA OT 2.3.
I'm passing to the started ANT process the temporary files folder as a relative location like:

    "-Dbasedir=D:\projects\eXml\test\dita\transform" "-Doutput.dir=output" "-Ddita.temp.dir=temporary/oxygen_dita_temp"

and for most of the stages the temporary files folder is considered relative to the "basedir" folder but somehow the stage which writes the ".job.xml" writes it relative to the folder where the Java process started (instead of being relative to the base.dir).

**Comment by jelovirt** [comment]
IMO we should change `dita.temp.dir` to require absolute path in 3.0. But, for 2.3.1 we can fix this.

**Comment by jelovirt** [comment]
@raducoravu are you able to test the fix 5b6066b?

**Comment by raducoravu** [comment]
I will try to do this in 10-20 minutes and get back.

**Comment by raducoravu** [comment]
Tested and it looks good to me. Used both relative temp and relative output folder.
