### ISSUE TITLE
Remove the text-align="justify" property for the PDF TOC entries

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2403]
If the TOC entries are long enough to be rendered on multiple lines, the first lines are displayed justified. We have users that dislike this presentation mode and ask how to disable it.

Searching in the GitHub history, I see that this property was set to fix an issue regarding an uneven right edge on PDF TOC, see #735. 

I've tested with Apache FOP 2.1 and DITA-OT 2.5 and the numbers from the right side seems to be aligned correctly. 

So, could we discard the changes from the issue #735?

**Comment by jelovirt** [comment]
There is no DITA-OT 2.5 and FOP 2.1 isn't shipped with stable DITA-OT.

**Comment by radu-pisoi** [comment]
Link to our forum where you can see the images posted by our user:
https://www.oxygenxml.com/forum/post38630.html

**Comment by robander** [comment]
Sample files with a TOC that has a short title, 2 line title, and 3 line title (with only long words so the justification is obvious):
[2403.zip](https://github.com/dita-ot/dita-ot/files/2254388/2403.zip)

**Comment by robander** [comment]
Fixed with https://github.com/dita-ot/dita-ot/commit/d822cb3c83647b9cbb1d90c414a54b02591edbda
