### ISSUE TITLE
Fatal error if DITA-OT directory contains plus sign

### ISSUE THREAD

**Issue by eerohele** [dita-ot/dita-ot#2414]
1. Download the [DITA-OT nightly build](https://s3-eu-west-1.amazonaws.com/dita-ot/dita-ot-develop.zip).
2. Extract the ZIP file. A directory called something like `dita-ot-2.3+45e1331` is created.
3. Run `dita-ot-2.3+45e1331/bin/dita -i whatever.ditamap -f html5`.

Error:

```
Error: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/tmp/test/docsrc/userguide.ditamap' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.
```

If you remove the `+` from the DITA-OT directory name, the error goes away. It doesn't matter whether the input file path has a `+`.

**Comment by jelovirt** [comment]
Probably because space can be escaped with `+` in URI.

**Comment by infotexture** [comment]
@jelovirt Would fixing this be as simple as replacing the plus sign on [Line 157 of build.gradle](https://github.com/dita-ot/dita-ot/blob/develop/build.gradle#L157) with another character such as an `@` sign, dash or underscore?
