### ISSUE TITLE
Add support for long options with double hyphen in dita command

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2422]
To follow the UNIX convention in command arguments, long option form should start with double hyphen. For backwards compatibility, the single hyphen form should be retained. After the change, the following commands are equivalent:

``` bash
$ dita -install
$ dita --install
```

**Comment by jelovirt** [comment]
Should we also extend the CLI syntax so that you could set parameters directly with the long form? That is, the following would be equivalent

```bash
$ dita -Dfoo.bar=baz
$ dita --doo.bar=baz
```

The long form option would only be available for parameters configured in plugin configuration file.

**Comment by infotexture** [comment]
👍 

> Should we also extend the CLI syntax so that you could set parameters directly with the long form?

I think that would make the CLI syntax more readable, as the `-D` syntax is hardly intuitive. 

In the Ant/Java world, I'm sure `-D` was originally intended as a mnemonic for something — perhaps _**D**efine … a value for a property_? — but I'm not sure how many users find this helpful.

**Comment by robander** [comment]
> The long form option would only be available for parameters configured in plugin configuration file

Maybe you are already thinking this ... but when supporting this for parameters in the shipped code, do we take the opportunity to consolidate on a parameter naming scheme? On the plus side - we'd officially have consistent, defined "parameters for common use on the command line". On the down side, we'd end up with different values -- `-Dclean.temp=no` versus `--args.clean.temp=no`

**Comment by xephon2** [comment]
I think, because breaking things seem to be OK for `3.0`, that it would be a good point of time to harmonize the naming patterns of parameters and deprecate deviations (e.g. `args.`, `dita.`).

**Comment by jelovirt** [comment]
@robander, remember... years ago, I suggested we'd harmonize the argument names, with three different groups: public, internal but overridable, private. That never happened :)

**Comment by jelovirt** [comment]
One option would be to add a backwards compatibility layer that mapped e.g. the old `dita.temp.dir` into new `temp-dir`. The problem is, backwards compatibility layers have a tendency to become permanent fixture.

**Comment by robander** [comment]
I definitely remember. The argument against is for the churn - existing scripts have to change, in addition to the general mess of making the changes. I don't like breaking things without a really good reason.

The reason I ask here is that these are, in a sense, new parameters. There is no parameter like `--some.parm.name` today. So when adding them, we could declare new values, even if the ones in Ant (under the covers) stay the same.

@xephon2 :
> I think, because breaking things seem to be OK for 3.0, that it would be a good point ...

While we're allowed to break things, I still feel pretty strongly that we need to do it with great care. Even some of the relatively minor (incompatible) changes in 2.0 have proven scary enough to DITA-OT customers that they have not upgraded. If there are significant changes in 3.0 then I think we really risk people sticking at 1.8.5 forever.

>

**Comment by robander** [comment]
> One option would be to add a backwards compatibility layer ... 
> The problem is, backwards compatibility layers have a tendency to become permanent fixture.

In this case, I'd probably be fine with such a layer, particularly with the push to use `dita` making the Ant code less visible / less relevant. I think the biggest problem with compatibility layers is that they can get in the way of new development. For this, I don't really see that happening. Provided that we use the standardized scheme for any new parameters, the compatibility layer will never have a reason to grow; it can exist forever as an import to the Ant code without being edited or in the way. Still not exactly elegant - but provides for the new common scheme with zero disruption for existing scripts.

**Comment by xephon2** [comment]
> @robander: While we're allowed to break things, I still feel pretty strongly that we need to do it with great care. Even some of the relatively minor (incompatible) changes in 2.0 have proven scary enough to DITA-OT customers that they have not upgraded. If there are significant changes in 3.0 then I think we really risk people sticking at 1.8.5 forever.

Sure, I think it is way too early to start developing a new major release with > 250 open bugs, but that is another topic. 

I'd recommend to implement fallback solutions for such things from major version to major version (e.g. from 3.0 to 4.0) and write a list with deprecated things at the end of each build log to force people to do somethin.

**Comment by robander** [comment]
I know we talked about that sort of layer in the past, but decided against it, and I don't remember exactly why. It might have just been "this is too much work for too little benefit" -- and at the time everything was still Ant, so the changes would have been more in-your-face.

**Comment by jelovirt** [comment]
The backwards compatibility layer would need to be at Ant level, not CLI (`dita` command), because not all users use CLI.

**Comment by jelovirt** [comment]
One of the problems with a backwards compatibility layer is that if we e.g. have support for `args.xsl` -> `stylesheet`, users could use either the old or new name when passing the name to CLI or Ant. But, then we'd need to add a forwards compatibility layer, so that when user sets the new parameter, custom plugins would have access to the old parameter.

**Comment by robander** [comment]
Ah, right. I remember that. They basically have to be interchangeable ... old stylesheets that set the old parameter need to keep working, old code that expect the old parameter need to keep working, so just switching to the new parameter (but pulling a value from the old) isn't enough. All coming back now.

**Comment by infotexture** [comment]
Looks like this is covered by PR #2492. I think we can close this.
