### ISSUE TITLE
Integrator fails

### ISSUE THREAD

**Issue by shudson310** [dita-ot/dita-ot#2426]
I cannot integrate my DITA-OT plugins.

Executing:
"c:\program files\oxygen xml editor 17\jre/bin/java" "-Dhttp.proxySet=true" "-Dhttp.proxyHost=ipv4.169.143.0.105.webdefence.global.blackspider.com" "-Dhttps.proxyHost=ipv4.169.143.0.105.webdefence.global.blackspider.com" "-Dhttp.proxyPort=80" "-Dhttps.proxyPort=80" -Xmx256m -classpath "C:\Program Files\Oxygen XML Editor 17\tools\ant/lib/ant-launcher.jar" "-Dant.home=C:\Program Files\Oxygen XML Editor 17\tools\ant" org.apache.tools.ant.launch.Launcher -lib "C:\SVN\ptd\content\trunk\dita-ot-2.3.1\lib\commons-io.jar" -lib "C:\Program Files\Oxygen XML Editor 17\frameworks\dita\DITA-OT2.x\lib\commons-io-2.4.jar" -f "C:\SVN\ptd\content\trunk\dita-ot-2.3.1/integrator.xml" "-Dstrict=true" "-Dwebhelp.trial.license=no"

Buildfile: C:\SVN\ptd\content\trunk\dita-ot-2.3.1\integrator.xml

strict:

integrate:

BUILD FAILED
C:\SVN\ptd\content\trunk\dita-ot-2.3.1\integrator.xml:66: The following error occurred while executing this line:
C:\SVN\ptd\content\trunk\dita-ot-2.3.1\integrator.xml:44: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet

**Comment by raducoravu** [comment]
You need to run the integrator an extra JAR library located in "DITA-OT\lib\guava-19.0.jar".
For this you can edit the integrator transformation scenario and in the "Advanced" tab click the "Libraries" button and add a reference to the library. The integration process in Oxygen 18.0 should work without any changes but you are using 17.
