### ISSUE TITLE
DTD-defined entities disappear from document

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2427]
I recognize that many feel entities are evil, wrong, and should not exist, but please leave that aside for the moment.

The DITA DTD from OASIS defines one entity in `topic.mod`:
```
<!ENTITY nbsp                   "&#xA0;"                             >
```

We've got this in a lot of documents, because for a long time, our editor-of-choice was set to save characters as entities when possible. Because it's in `topic.mod`, it's a legal entity in any DITA topic or topic specialization (because all topic shells should include that module). When that entity exists, it is dropped during parsing - the entity is removed, and no character is inserted in its place. 

It appears that any entity defined in a DTD has this problem; entities defined in the document as part of the `!DOCTYPE` do not. To test, I've added an entity into a topic, and I've added one new entity in the DTD. 

For ease of testing, I added this into `topic.mod` next to the current definition of `nbsp`, but keep in mind that (however silly) this would be valid as part of any doctype shell or specialization module:
```
<!ENTITY testy "This is UGLY so please forgive me">
```

My topic uses this entity, and one defined within the file:
````
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN"
 "../../dtd/technicalContent/dtd/concept.dtd"[
  <!ENTITY phrasey       "This is a bit of text">
]>
<concept id="conceptconcept" xml:lang="en-us">
<title>Garage&nbsp;Concepts</title>
<conbody>
<p>Test an entity that's defined in this topic: [&phrasey;]</p>
<p>Now an entity from the DTD: [&testy;]</p>
</conbody>
</concept>
```

When built to HTML or PDF, the output looks like this - both `nbsp` and `testy` from the DTD are dropped, but `phrasey` from the topic is preserved:

**GarageConcepts**

Test an entity that's defined in this topic: [This is a bit of text]

Now an entity from the DTD: []

**Comment by robander** [comment]
With additional testing, realizing that this is somehow connected to grammar caching.

When I turn off caching (which is on by default), the entities resolve properly.

Guessing this means there is nothing we can do to resolve this, other than (for my own use) turning off the caching.

**Comment by raducoravu** [comment]
That's the Xerces bug which produces the entity resolution problem when caching DTD grammars:

https://issues.apache.org/jira/browse/XERCESJ-1205

When we run the DITA OT from Oxygen we apply a patch on the Xerces libraries in order to work around this. We've had users who had patched their own Xerces libraries in order to achieve the correct behavior even when running DITA OT from the command line.

**Comment by robander** [comment]
Marking this closed -- the main issue was a defect, and docs have been updated as part of another commit or issue.
