### ISSUE TITLE
Remove "Draft comment area found. " message

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2429]
If I'm publishing DITA content using draft comments and the "args.draft" parameter enabled, the DITA OT console emits this message for each encountered draft-comment:

```
  [DOTX040I]: Draft comment area found. To remove this message and hide the comments, build your content without using the DRAFT parameter.
```

I don't think this message is useful, I have explicitly enabled the parameter, so it just pollutes the console log.

**Comment by shaneataylor** [comment]
I agree it's not useful on each occurrence, but a single warning could be useful, as it's possible someone else turned on draft comments for your build (say, for a review) and forgot to turn them off. 

I wouldn't want not to be warned about draft comments if I thought my deliverable might be ready to deploy!

**Comment by shaneataylor** [comment]
Actually, I can envision a workflow where this setting is always left on and part of the review process is to remove all the draft comments as they are addressed. In such a workflow, it's possible that "by occurrence" warnings would be useful, and at a minimum the warning should indicate whether any draft comments actually were encountered and not just whether the parameter was set.

One possibilitity would be to add new values to the **args.draft** parameter:
**yes** - current "yes" behavior, for backward compatibility
**log-each** - current "yes" behavior, but with a more accurate description
**log-first** - includes draft comments, but only log a warning for the first one
**log-none** - includes draft comments, but doesn't warn about them in the log

**Comment by robander** [comment]
The reason for current logging goes back to the early beta days, where there were two issues (both addressed by @shaneataylor above):

1. Fear that somebody would take draft content, publish with `args.draft` on because that's what the script does, and unknowingly deploy draft comments
2. The need to find draft comments or required-cleanup items - errors in the log provided an easy summary of topics that explicitly needed review or cleanup.

**Comment by raducoravu** [comment]
Ok, you can close this if you want...

**Comment by robander** [comment]
Radu suggested we could close this one over two years ago -- with no updates since then I think it's finally time to pay attention.
