### ISSUE TITLE
Use of keyword keyref in a DITA Map

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2430]
Let's say my DITA Map has inside it something like:

```
      <keydef keys="original">
        <topicmeta><keywords><keyword>Original Content</keyword></keywords></topicmeta>
      </keydef>
      <keydef keys="product_name">
        <topicmeta>
          <keywords><keyword keyref="original"/></keywords>
        </topicmeta>
      </keydef> 
```

and in a DITA topic I have:

```
 <ph keyref="product_name"/>
```

Should the "product_name" key be resolved to the "Original Content" text in the published output for the HTML topic?
Right now it is not, with either DITA OT 1.8 or 2.x.

A workaround would have been to use a conref instead of a keyref in the DITA Map:

```
  <keydef keys="original">
    <topicmeta><keywords><keyword id="originalID">Original Content</keyword></keywords></topicmeta>
  </keydef>
  <keydef keys="product_name">
    <topicmeta>
      <keywords><keyword conref="#originalID"/></keywords>
    </topicmeta>
  </keydef> 
```

but this no longer works with DITA OT 2.x because of this bug:
https://github.com/dita-ot/dita-ot/issues/2420

**Comment by drmacro** [comment]
I can't think of any reason why the keyref to "original" should not be resolved in this context. I would certainly expect it to be resolved.

**Comment by jrbickford** [comment]
Hello. My team would like to use this construct in order to add flexibility to our reuse strategy. Do you know if this is in fact an OT bug? Or could our implementation (as Radu demonstrated above) incorrect? We would appreciate any insight or suggestions you can offer at this time. Thank you!

**Comment by jelovirt** [comment]
This would be fixed using map first preprocessing that I'm working on. It _may_ land on 3.0.

**Comment by raducoravu** [comment]
Ping, this should be tested again with DITA OT 3.x HTML and PDF, I think only the PDF output has map first processing turned on.
