### ISSUE TITLE
Prevent "recoverable errors" to pass

### ISSUE THREAD

**Issue by gsejourne** [dita-ot/dita-ot#2435]
I discovered recently that in some cases, malformed XML or other things are reported as recoverable errors in the OT processing, typically:

```
[mappull] Recoverable error on line 58 of mappullImpl.xsl:
  [mappull]   FODC0002: java.io.FileNotFoundException:
  [mappull]   /tmp/cmgw.dita-ot/file.dita (No such file or directory)
```

This kind of errors does not prevent the build from passing (e.g., the OT transformation returns a non-error code).
The problem is that the build mechanism can be used in a continuous integration system, and in some cases, we need to control whether these errors should fail the build or not.

**Comment by eerohele** [comment]
Enabling [strict processing mode](http://www.dita-ot.org/2.3/parameters/parameters-base.html#base__processing-mode) should stop processing if an error like that is encountered.
