### ISSUE TITLE
PDF2 setExpanse template has a bad test for textline

### ISSUE THREAD

**Issue by robertnthomas** [dita-ot/dita-ot#2438]
The test for textline in the setExpanse template checks for @expanse = column rather than for @expanse = textline

**Comment by raducoravu** [comment]
Problem still persists in DITA OT 3.2: DITA-OT3.x/plugins/org.dita.pdf2/xsl/fo/topic.xsl

      <xsl:when test="@expanse = 'column'">
           <element xsl:use-attribute-sets="__expanse__textline"/>
         </xsl:when>

specification:
https://www.oxygenxml.com/dita/1.3/specs/langRef/attributes/displayAttributes.html
