### ISSUE TITLE
Lax mode should allow leading-space in href

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2440]
Through cut-and-paste errors, we've encountered links with a leading space in `href`:
`<xref href=" http://www.example.com" format="html">`

In lax processing mode, this should be allowed with a warning (preferably by stripping the leading space). Currently, it results in a build failure after the space is converted to `%20`:
```
gen-list:
 [gen-list] Using Xerces grammar pool for DTD and schema caching.
 [gen-list] Processing file:/C:/test/space.dita
Error: Failed to run pipeline: Illegal character in scheme name at index 0: %20http://www.example.com
```

I expect this to fail in strict mode, but lax should continue with a warning.

**Comment by xephon2** [comment]
I thought it has been removed: #2151

**Comment by jelovirt** [comment]
@xephon2  that's for integration process. This is for actual DITA processing.
