### ISSUE TITLE
Mapref to conref fails to resolve the conref, PDF is empty

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2442]
I've got a set of docs where a bookmap is used for PDF, with lots of front/back matter, but the content is all pulled from maps used in other formats. Using 2.3.1 for testing.

The PDF input map looks like this, ignoring most of the front/back matter:

``` xml
<bookmap>
 <booktitle><mainbooktitle>Sample book title</mainbooktitle></booktitle>
 <frontmatter>
  <booklists><toc/></booklists>
 </frontmatter>
 <chapter format="ditamap" href="secondMap.ditamap" navtitle="Reference codes (1x - Ax)"/>
 <appendix href="appendix.dita"/>
</bookmap>
```

Second map just consists of a conref:

``` xml
<map>
 <title>Second Map, use conref</title>
<topicref conref="thirdMap.ditamap#kickoff"/>
</map>
```

The DITA-OT preprocess does not resolve the conref. However, it does follow the reference. My real-world doc with this construct had a few thousand topics in `thirdMap`; all were processed, but none actually show up in my PDF because the conref isn't resolved.

With the attached sample files, `thirdMap` just contains a parent and child. If you build to PDF, the TOC and appendix appear, but the parent/child content from the main chapter do not appear. This is because the `mainbookmap.ditamap` file in the temp directory has resolved the mapref, but not the conref. A slightly edited version of the temp file is here:

``` xml
<bookmap class="- map/map bookmap/bookmap " ditaarch:DITAArchVersion="1.3" xtrc="bookmap:1;3:10" xtrf="file:/C:/DITA-OT/dita-ot-2.3.1/test/mainbookmap.ditamap">
 <booktitle class="- topic/title bookmap/booktitle " xtrc="booktitle:1;4:13" xtrf="file:/C:/DITA-OT/dita-ot-2.3.1/test/mainbookmap.ditamap"> ... </booktitle>
 <frontmatter class="- map/topicref bookmap/frontmatter " xtrc="frontmatter:1;5:15" xtrf="file:/C:/DITA-OT/dita-ot-2.3.1/test/mainbookmap.ditamap">...</frontmatter>
 <topicref class="- map/topicref bookmap/chapter " conref="thirdMap.ditamap#kickoff" xtrc="topicref:1;5:46" xtrf="file:/C:/DITA-OT/dita-ot-2.3.1/test/secondMap.ditamap"/>
 <appendix class="- map/topicref bookmap/appendix " xtrc="appendix:1;9:34" xtrf="file:/C:/DITA-OT/dita-ot-2.3.1/test/mainbookmap.ditamap" href="appendix.dita" type="topic">...</appendix>
</bookmap>
```

Small sample files to reproduce the issue:
[maprefconref.zip](https://github.com/dita-ot/dita-ot/files/404025/maprefconref.zip)

**Comment by eerohele** [comment]
#2265 is probably related (but not exactly the same).
