### ISSUE TITLE
Use fo:block instead of fo:wrapper for ID containers

### ISSUE THREAD

**Issue by PStellmann** [dita-ot/dita-ot#2455]
I wrote this already as comment to the pull request #2229. But I noticed that one was already closed/merged. So here a new issue:

Using FOP I have additional space before a title and I could identify the empty fo:wrapper elements to cause this.

My sample fo code looks like this (the spaces for indention were added by hand to make it easier to read and are not present in the actual code):

```
<fo:block border="solid blue">
    <fo:marker marker-class-name="current-h2">Title</fo:marker>
    <fo:wrapper id="unique_3"/>
    <fo:wrapper id="_OPENTOPIC_TOC_PROCESSING_d89e342"/>
    <fo:block border="solid red">Title</fo:block>
</fo:block>
```

producing this output:
![dita-ot-title-wrapper](https://cloud.githubusercontent.com/assets/12510240/17726447/4d4d938c-6453-11e6-9216-6d10ad1750d2.PNG)
So the fo:wrapper elements generate a blank line.

When I change the fo:wrapper to fo:inline the result doesn't change.

When I change the fo:wrapper to fo:block the additional space disappears:
![dita-ot-title-block](https://cloud.githubusercontent.com/assets/12510240/17726492/abbb6732-6453-11e6-8058-6b3e9c82c2cd.PNG)

So I think at least for FOP fo:block should be used. I can't test it with XEP or AH, though.

Maybe there could be a named template "idContainer" with different overriding for different engines?

However, when using fo:block the @keep-with-next behavior of two consecutive titles will no more work since the first title will only be kept together with the (empty) id container block. So an additional keep-together.within-column="always" for the while title element is required - which should have no negative side effects...

**Comment by ToshihikoMakita** [comment]
> So the fo:wrapper elements generate a blank line.

According to the XSL 1.1 specification, fo:wrapper itself does not generate any areas.

6.13.4 fo:wrapper
[https://www.w3.org/TR/2006/REC-xsl11-20061205/#fo_wrapper](https://www.w3.org/TR/2006/REC-xsl11-20061205/#fo_wrapper)

So I think this problem should be reported to FOP mailing list.

**Comment by raducoravu** [comment]
Same problem reported here:

https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=16970&p=48563#p48563

I can reproduce this bug in FOP by adding an indexterm between a title and a paragraph like this:

        <section id="section_jqn_pnt_s2b"><title>My
                section</title><indexterm>abcdef</indexterm><p>My content</p></section>

and publishing to PDF, I get extra empty space between the title and the paragraph.

**Comment by raducoravu** [comment]
Actually the bug is already opened on the Apache FOP users list:
https://issues.apache.org/jira/browse/FOP-2016

**Comment by robander** [comment]
Interesting. We've been using `fo:wrapper` like this to add anchors for cross-book linking, but have not been using that feature with FOP, so I had not noticed any extra space.
