### ISSUE TITLE
DITA 1.3 catalog.xml points to non-existing resource

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2458]
A continuation of: https://github.com/dita-ot/dita-ot/issues/2266

with DITA OT 2.3.2 looking in this catalog file:
 
    plugins/org.oasis-open.dita.v1_3/dtd/subjectScheme/catalog.xml

at some point there are 2 mappings:

        <public publicId="-//OASIS//ELEMENTS DITA Subject Classification Domain//EN"
           uri="dtd/classifyDomain.mod"/>
       <public publicId="-//OASIS//ELEMENTS DITA Map Subject Classification Domain//EN"
            uri="classifyDomain.mod"/>

The @uri attribute for the second mapping should probably be "dtd/classifyDomain.mod".

**Comment by robander** [comment]
Looks like this one is already fixed in the errata for DITA 1.3 - we should update the shipped catalog here in advance of that errata, as we've done with other catalog issues that are going into the errata.

**Comment by robander** [comment]
Corrected version in the OASIS SVN repository is here: https://tools.oasis-open.org/version-control/svn/dita/trunk/doctypes/src/1.3/dtd/subjectScheme/catalog.xml

**Comment by jelovirt** [comment]
@robander do you want to take this?

**Comment by robander** [comment]
Yeah. I was mistaken about the fix. We added a value to this catalog in advance of errata; it was added with typo. Actual errata never got fix - still on errata list at oasis without the "COMPLETED" note.

**Comment by robander** [comment]
Also restoring the values that were used in 1.2 for `classifyDomain.ent`, which should have been in the OASIS catalog as delivered:
```
<public publicId="-//OASIS//ENTITIES DITA 1.3 Map Subject Classification Domain//EN"
           uri="dtd/classifyDomain.ent"/>
   <public publicId="-//OASIS//ENTITIES DITA Map Subject Classification Domain//EN"
           uri="dtd/classifyDomain.ent"/>
```
