### ISSUE TITLE
Feature request: Test if PDF file is open before publishing it

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2463]
The Adobe Reader locks a file, that means you cannot overwrite it, when it is opened in the Adobe Reader. Sometimes, when publishing locally, authors forget to close the PDF file before publishing it. Then, the FOP publishing runs (what can be time consuming) and then tries to overwrite the file. If it is open, it fails, and authors need to close the PDF and rerun the process. It would be nice, if the process would try to delete the output file before publishing. If it cannot be deleted, because the file is open, the author would save duplicate publishing time.

**Comment by raducoravu** [comment]
:+1: 
We added a similar check in our DITA + CSS = PDF plugin:

  	<delete file="${outputFile}" failonerror="false"/>
  	<fail message="[DOTP002] [ERROR] Cannot overwrite the output file: ${outputFile}. Make sure it is not opened in Acrobat Reader or other program that locks it.">
  	     <condition>
  	     	<available file="${outputFile}"></available>
  	     </condition>
	</fail>

**Comment by xephon2** [comment]
I'm not sure, but I think this is still not implemented. @jelovirt, should I send a PR with @raducoravu s fix ?

**Comment by xephon2** [comment]
😞

**Comment by lief-erickson** [comment]
@xephon2, I'm with you! I learned from @infotexture that Mac users don't have this issue. Do you use Windows?

**Comment by xephon2** [comment]
@lief-erickson, I only know that Adobe Acrobat is locking the file on Windows. Other PDF readers don't care if the PDF is replaced while it is open in the PDF viewer.

**Comment by markgif** [comment]
On Windows 10 I use the SumatraPDF reader, which doesn't care if the PDF is already open and updates it with the new PDF. It's also real fast.

**Comment by lief-erickson** [comment]
I use PDF X-Change Editor. Like Adobe Acrobat, when the file is open it's locked. Boo.
