### ISSUE TITLE
Behavior with ditavalref and copy-to

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2472]
Let's say I'm using ditavalref on a topicref which also has a copy-to attribute:

```
  <topicref href="test.dita">
     <ditavalref href="filter1.ditaval"/>
  </topicref>
   .........
  <topicref href="test.dita" copy-to="test-unique.dita">
     <ditavalref href="filter2.ditaval"/>
  </topicref>
```

it seems that right now the output folder seems to contain both "test-unique.html" and "test-1.html". Somehow I would expect for only the copy-to attribute to to be obeyed when branching.

**Comment by drmacro** [comment]
[branch-filtering-test-02-copy-to.zip](https://github.com/dita-ot/dita-ot/files/1895394/branch-filtering-test-02-copy-to.zip)

This test case demonstrates that with a copy-to, the branch filtering goes haywire. Without the copy-to this test case produces the expected correct filtered result.

**Comment by thendarion** [comment]
I just ran into the same issue

branch filtering and copy-to don't play nice with each other :(

(I'm using 3.5.4 at the moment but considering the state of this ticket it hasn't been fixed)

**Comment by raducoravu** [comment]
Branch filtering is implemented by generating copy-to attributes for each branch, so indeed it does not play well with copy-to. Maybe you can avoid copy-to and instead create a new topic file on disk which has a conref to the original topic file.
