### ISSUE TITLE
Publishing problems when DITA content is in folder containing German characters [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2476]
I'm attaching a sample project.

[sample-german-chars-in-folder-name.zip](https://github.com/dita-ot/dita-ot/files/466786/sample-german-chars-in-folder-name.zip)

When the folder containing the main DITA Map has German characters in its name, the DITA processing which merges all submaps in the main DITA Map does not succeed in properly updating the @href's for the topicrefs located in the subtopics. Especially the link to the "child-1-1-1.dita" becomes broken in the XHTML outout.

**Comment by raducoravu** [comment]
One more observation, if the "dita.preprocess.reloadstylesheet" parameter is set to "true" this issue can be reproduced with the sample files even if the folder does not contain German characters in it.

The explanation (I had to dig 2 days for this) is this:

The "org.dita.base\build_preprocess.xml" build file has a "mapref" target which calls XSLT processing for all DITA Maps:

                <pipeline message="Resolve mapref in ditamap" taskname="mapref">
                  <xslt basedir="${dita.temp.dir}" reloadstylesheet="${dita.preprocess.reloadstylesheet.mapref}" style="${dita.plugin.org.dita.base.dir}/xsl/preprocess/mapref.xsl" filenameparameter="file-being-processed">
                    <ditafileset format="ditamap"/>
                    <param name="TRANSTYPE" expression="${transtype}"/>
                    <xmlcatalog refid="dita.catalog"/>
                  </xslt>
                </pipeline>

so instead of being called only on the root map, this processing gets called on all submaps and then on the root map in the order:

              file:/C:/Users/radu_coravu/Desktop/hierarchy-äöü/temp/xhtml/child-1/child-1-1/_child-1-1.ditamap
              file:/C:/Users/radu_coravu/Desktop/hierarchy-äöü/temp/xhtml/child-1/_child-1.ditamap
              file:/C:/Users/radu_coravu/Desktop/hierarchy-äöü/temp/xhtml/hierarchy.ditamap

For each of these maps, the processing applies the "maprefImpl.xsl" which will read using the "document" function the submaps and then the processing replaces the original file with the processed file.
When the processing is applied on the "hierarchy.ditamap", because the XSLT processor does not reload the stylesheet by default, the document() function used on the other referenced DITA Maps will usually return the original content and will not load the file content already modified on disk.

When the DITA content is in a folder with German characters the XSLT "maprefImpl.xsl" computes the URIs for DITA Maps loaded using the document() function using ASCII-encoded URIs:

               file:/C:/Users/radu_coravu/Desktop/hierarchy-%C3%A4%C3%B6%C3%BC/temp/xhtml/child-1/child-1-1/_child-1-1.ditamap

But when the  org.dita.dost.module.XsltModule transforms an XML, it does not escape the source URI to an ASCII string so it transforms using a source like this:

              file:/C:/Users/radu_coravu/Desktop/patrik/hierarchy-äöü/temp/xhtml/child-1/child-1-1/_child-1-1.ditamap

so in this case, when "maprefImpl.xsl" processes the "hierarchy.ditamap", it will load the modified contents from disk for the two maprefs, resulting in the XSLT stylesheet not being able to properly fix relative paths.

**Comment by raducoravu** [comment]
So this issue would need two fixes:

1) In the "org.dita.dost.module.XsltModule" compute the URI of the source using ASCII escaping:

      new InputSource(in.toURI().toASCIIString())

This would again allow for properly processing the sample DITA project I attached with the default parameters ("dita.preprocess.reloadstylesheet" set to "no")

2) But when "dita.preprocess.reloadstylesheet" is set to "yes" the problem can still be reproduced.
In my opinion the "mapref" target should only process the root map or at least process first the root map and then the other DITA Maps. Otherwise when the root map is processed the content of the modified intermediary DITA Maps is loaded instead of their original content.

**Comment by PStellmann** [comment]
Thanks a lot, Radu. That's really tricky...

I modified the mapref target to process only the root map and now my real map is transforming without errors as well:
```
<target name="mapref" depends="mapref-check" unless="preprocess.mapref.skip" description="Resolve mapref in ditamap">
  [...]
  <xslt basedir="${dita.temp.dir}" in="${dita.temp.dir}/${user.input.file}" out="${dita.temp.dir}/${user.input.file}.tmp" reloadstylesheet="${dita.preprocess.reloadstylesheet.mapref}" style="${dita.plugin.org.dita.base.dir}/xsl/preprocess/mapref.xsl" filenameparameter="file-being-processed">
    <xmlcatalog refid="dita.catalog"/>
  </xslt>
  <rename src="${dita.temp.dir}/${user.input.file}.tmp" dest="${dita.temp.dir}/${user.input.file}" replace="yes"/>
</target>
```

**Comment by raducoravu** [comment]
Glad the (2) suggestion worked for you @PStellmann, probably Oxygen 18.1 will contain an alternate Java patch for this (the (1) suggestion that I gave).

**Comment by jelovirt** [comment]
I can't reproduce this on 3.0. When I run the conversion, link to "child-1-1-1.dita" look ok in all files after mapref. @raducoravu are you able to still reproduce this and describe in more detail exactly what and how output is broken?

**Comment by raducoravu** [comment]
I also cannot reproduce the problem with DITA OT 3.0.1, basically with DITA OT 2.5.2 the table of contents had a broken link to one of the subtopics, see screenshot.

![tocproblem](https://user-images.githubusercontent.com/1005979/34662471-a204b288-f459-11e7-8560-36ff4fc2088e.png)
