### ISSUE TITLE
Provide option of extending main class path with a path ref

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2478]
In the context of trying to integrate AH's i18n extension plugin, that plugin provides a named path that references a number of libraries, including libraries included using a wildcard. I need to integrate this path with the main OT class path.

However, at least by the documentation, the dita.conductor.lib.import only supports adding individual `<pathelement>` entries, not `<path>` entries.

Not sure what the best solution here is, either an alternative value for @type or a new extension point.

**Comment by jelovirt** [comment]
Could you give a bit more info on what you need to asd to the classpath and how it doesn't work.

**Comment by jelovirt** [comment]
Ah, now I got it, wildcards. Since the libraries are listed outside Ant too, I don't endorse this. Also, there should not ve issues with explicitly listing the dependencies.

**Comment by drmacro** [comment]
The plugin defines a `<path>` element with an ID. I would like to add a `<path refid="{id from plugin}">` to the main class path rather than a `<pathelement>` pointing to a single library.

The AH plugin has this:

```
    <path id="i18n_index.class.path">
        <!--pathelement location="${com.antennahouse.i18n_index.plugin.lib}${file.separator}i18n_support${file.separator}lib${file.separator}icu4j-4_8.jar"/>
        <pathelement location="${com.antennahouse.i18n_index.plugin.lib}${file.separator}ah_i18n_index.jar"/>
        <pathelement location="${com.antennahouse.i18n_index.plugin.lib}${file.separator}i18n_support.jar"/-->
        <fileset dir="${com.antennahouse.i18n_index.plugin.lib}${file.separator}i18n_support${file.separator}lib">
            <include name="*.jar"/>
        </fileset>
        <fileset dir="${com.antennahouse.i18n_index.plugin.lib}">
            <include name="*.jar"/>
        </fileset>
    </path>
```

Seems reasonable to be able to add that to the main classpath with a single extension call rather than having to replicate it entirely in the plugin.xml file.

The wildcards are something of a red herring here.

**Comment by jelovirt** [comment]
Closing as rejected
