### ISSUE TITLE
Replace HTML tables with 

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2480]
This is an **enhancement** request for **org.dita.html5**.

It would be nice, if (at least) `<dl>` tables would be made of (floatable) `<div>` elements.

```html
<div class="wrappingTable">
  <div class="tableRow">
    <div class="tableCell header">term</div>
      <div class="tableCell">definition</div>
    </div>
  </div>
</div>
```

This would be more HTML5 aware, I think.

**Comment by jelovirt** [comment]
For tables the corrent HTML5 element is table, not div. However, for element structures that may be table-like but are not tables, like note with note type text, div is more appropriate.
