### ISSUE TITLE
Problem with xref to topic which has abbreviated-form in shortdesc [DITA OT 2.3.2]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2482]
This bug seems to have appeared in DITA OT 2.3.2 and possibly it was caused by this fix: https://github.com/dita-ot/dita-ot/issues/1599
I'm attaching some samples:

[abbrev-form-problems.zip](https://github.com/dita-ot/dita-ot/files/476496/abbrev-form-problems.zip)

If you publish to XHTML the console complains at some point:

            [topicpull] Recoverable error on line 584 of topicpullImpl.xsl:
            [topicpull]   FODC0002: I/O error reported by XML parser processing
            [topicpull]   file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/bubu.dita:
            [topicpull]   D:\projects\eXml\frameworks\dita\DITA-OT2.x\xsl\preprocess\bubu.dita (The system cannot
            [topicpull]   find the file specified)

so the "bubu.dita" file which is the glossentry file is searched relative to the XSLT location.
This seems to happen because when the "WORKDIR" param is computed, the processing 'workdir-uri' cannot be found anymore as the templates are applied only on a nodeset and not on an entire document.

**Comment by raducoravu** [comment]
In the first example the processing at least finishes but I modified the example a little bit (still valid) and now the publishing fails completely:

[abbrev-form-problems-worse.zip](https://github.com/dita-ot/dita-ot/files/476732/abbrev-form-problems-worse.zip)

**Comment by jelovirt** [comment]
This issue is tricky and I would really like to refactor the topicpull code first to be cleaner, and then fix this issue. However, we can't do that for patch release, so either this needs a quick fix or will need to be pushed to next proper release.

**Comment by raducoravu** [comment]
The only quick fix I found was to disable the initial fix from https://github.com/dita-ot/dita-ot/issues/1599.

**Comment by raducoravu** [comment]
Fix looks good to me, running with both samples I attached and after making some patches to remove the problems introduced in: https://github.com/dita-ot/dita-ot/issues/2486#issuecomment-249129598
I will try to run all our DITA OT automated tests with the fixes in place, see if they report anything, I will update the issue tomorrow if I find anything.
