### ISSUE TITLE
Problem with conkeyref resolution

### ISSUE THREAD

**Issue by juliovaz** [dita-ot/dita-ot#2483]
This was discovered on OT 2.3.1 and exists still in 2.3.2.

If a bookmap contains a <data> element that contains an <image> element with a relative path in the @href attribute, all keyref file resolutions prepend the file resolutions with the relative path. That is, if the image @href contains something like ../../, that is prepended to all resolved file references for conkeyrefs.

**Comment by raducoravu** [comment]
So basically you have references to resources outside of the folder where the main DITA Map is located, right?
As far as I know such problems have always been around, even in DITA OT 1.8, if you are using Oxygen there is a parameter which you can set to avoid them:
https://www.oxygenxml.com/doc/versions/18.0/ug-editor/topics/dita-ot-external-refs.html

**Comment by juliovaz** [comment]
An oxygen solution won't work for the production environment which just
uses the ot.

sent from Android
