### ISSUE TITLE
Keyrefs to images not working

### ISSUE THREAD

**Issue by dagoss** [dita-ot/dita-ot#2489]
The OT is attempting to resolve the href of keyrefs for images based on the topic's path rather than the root map. So if the key is defined with the href `images/test-image.png` but the topic is in `topics/topic.dita`, it looks like the merged map attempts to find the image in `../images/test-image.png`.

[Sample map demonstrating the issue](https://github.com/dita-ot/dita-ot/files/485406/dita-image-keyref-error.zip)

## dita command

    > dita -version
      DITA-OT version 2.3.2
    > dita -f pdf -i test.ditamap

## Error
Note: This error is only shown if the dita command is run with `-v`. Without `-v` there are no errors shown, but the image content is missing from the output.

    transform.fo2pdf.fop:
          [fop] [ERROR] Image not found. URI: ../images/test-image.png. (See position 3:-1)
          [fop] /var/tmp/temp20160921105249494/topic.fo -> /hdrs/goss/test/dita-image-keyref/out/test.pdf

The issue does not occur if the topic and the root map are in the same location.

## Example

    test.ditamap         <--- keydefs be here
    images/
        test-image.png
    topics/
        topic.dita       <--- keyref used here

### test.ditamap

    <map id="test">
            <title>Test Map</title>
            <keydef keys="test-image"
                  format="png"
                  scope="external" 
                  href="images/test-image.png"
                  />
            <topicref href="topics/topic.dita"/>
    </map>

### topic.dita

    <topic id="topic">
            <title>Test topic</title>
            <body>
                    <p>Test image below:</p>
                    <image placement="break" keyref="test-image"/>
            </body>
    </topic>

## Question
Is this not a typical use-case for keyrefs on images? I frequently see recommendations to use keyrefs for images on the dita-users mailing list, so I'm surprised that (what I think is) a very basic use does not work.

**Comment by xephon2** [comment]
Please try again without `scope="external"`.

**Comment by dagoss** [comment]
Wow, I completely misunderstood what that attribute was for. I'll close this issue because it's working as expected.
