### ISSUE TITLE
copy-to fails to update CSS paths

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2491]
I published to XHTML using the samples attached in https://github.com/dita-ot/dita-ot/issues/2486
The generated HTML file "copyup.html" has the wrong path to the CSS, the HTML is generated in the base output folder but the path to the CSS is one level up "../commonltr.css"

**Comment by jelovirt** [comment]
The `path2project-uri` PI has a wrong path `../` when it should be `` (or `./`)
