### ISSUE TITLE
related-links should not generate links to unreferenced topics

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2493]
I could not find an issue for this and I'm unsure, whether this a desired behavior. So I do not know, whether this is a bug report or an enhancement request.

**tl;dr:** We use keymaps to define keys once and then refer to those maps to propagate the keys to use them in publication maps. Unfortunately, the related-links mechanism, as it is implemented, does not care for, if a topic is referenced in a map, it looks for, whether the key is defined and then processes it. This creates link stubs, see screenshot.

DITA-OT: `2.3.2`
transformation: `pdf2` and `xhtml`
samples: [related-links-issue.zip](https://github.com/dita-ot/dita-ot/files/494854/related-links-issue.zip)

![screen](https://cloud.githubusercontent.com/assets/3266567/18864751/fe27b25a-8497-11e6-8abf-e93ded5c499a.png)

**Explanation**

This is the publication map **map.ditamap**. It has a link to the key map and refers to **chapter1** and **chapter2** but not to **chapter3**.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>DITA Topic Map</title>
  <topicref>
    <mapref href="keymap.ditamap" toc="no" format="ditamap"/>
  </topicref>
  <topicref keyref="chapter1"/>
  <topicref keyref="chapter2"/>
</map>
```

The **keymap.ditamap** defines keys for all 3 topics:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>Keymap</title>
  <topicgroup>
    <keydef keys="chapter1" href="chapter1.dita" processing-role="resource-only"/>
    <keydef keys="chapter2" href="chapter2.dita" processing-role="resource-only"/>
    <keydef keys="chapter3" href="chapter3.dita" processing-role="resource-only"/>
  </topicgroup>
</map>
```

The **chapter1** topic has related links to **chapter2** and **chapter3**, but, because **chapter3** is not referenced in the map, the related link should not be generated.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="topic_kky_2y5_kx">
  <title>chapter1</title>
  <shortdesc>chapter1 is defined on keymap and referenced in map.</shortdesc>
  <related-links>
    <link keyref="chapter2"/>
    <link keyref="chapter3"/>
  </related-links>
</topic>
```

**Comment by drmacro** [comment]
I agree--related links should only reflect links to normal-role topics.

**Comment by xephon2** [comment]
Same applies to `xhtml`:

![screen2](https://cloud.githubusercontent.com/assets/3266567/18865163/31b9780e-849a-11e6-8741-d37bf29019b5.png)
