### ISSUE TITLE
Cannot conref from one submap to another

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2494]
I'm attaching a sample:

[topicref-conref-problem.zip](https://github.com/dita-ot/dita-ot/files/497186/topicref-conref-problem.zip)

Basically one submap conrefs to an ID set on a topicref in another submap. The conref is not expanded at all in the output.
In my opinion the problem is that the [conref] stage applies only on the submap which has the actual original conref, when in fact it should apply on all DITA Maps, because all DITA Maps have been expanded by the previous [mapref] stage.

**Comment by raducoravu** [comment]
As a possible quick fix in "build_preprocess.xml" the target named "conref" besides having a fileset like this:

            <ditaFileset conref="true"/>

could have an additional file set with all DITA Maps:

               <ditaFileset format="ditamap"/>

**Comment by raducoravu** [comment]
Or have two conref stages, one for DITA Maps which is applied before mapref, and one for topics which is applied later on...

**Comment by jelovirt** [comment]
The correct fix is to update job configuration after map merge, to cascade conref flag up to the main map from submaps.

**Comment by robander** [comment]
@raducoravu or @jelovirt do you know if this might be fixed with `preprocess2`? If so it might still need to be open against `preprocess` but it would be nice if we've already made some progress.

**Comment by raducoravu** [comment]
I tested but it still does not work with the default DITA OT 3.0.1 processing (which should be from what I know proprocess2).

**Comment by robander** [comment]
Just FYI -- `preprocess2` is now the default for PDF, but not for XHTML / HTML5, so depending on your transform type you can still get either one.

**Comment by raducoravu** [comment]
I did not know that, from what I remember I tried also with PDF and it did not work though.

**Comment by jelovirt** [comment]
IMO the fix that after map merge we check the map files for conref is still the correct one, but the fix is a bit tricky because map merge is implemented with XSLT. Thus we have no simple post-tranformation hook where we can check whether `@conref` attributes have been added. If we change the code to not just use `<pipeline><xslt>`, then that cannot really go into a bug fix release due to the extend of the changes. So this should probably go to 3.1.

**Comment by robander** [comment]
No strong preference - sounds like there are advantages to both. It sounds like the latter approach with dedicated module might be _slightly_ better because if other things like this come up in the future they'll be easier to handle. But yeah that would need to be for 3.1.

**Comment by jelovirt** [comment]
@robander #2875 fixes this. Are you able to review?

**Comment by robander** [comment]
@jelovirt reviewed -- fix looks good.
