### ISSUE TITLE
Problems when ditavalref points to ditavals outside of main DITA Map folder

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2495]
I'm attaching a sample project:

[ditavalref-to-external-ditavals.zip](https://github.com/dita-ot/dita-ot/files/497242/ditavalref-to-external-ditavals.zip)

The DITAVAL files are outside of the folder where the published DITA Map is located. Because of this, in the topic "dita_contextvars\topic.dita" the conkeyref is not expanded anymore.
Also no errors are reported.
If the DITAVAL files are copied next to the DITA Map and links to them are updated, the title of the "dita_contextvars\topic.dita" is correctly computed.

**Comment by raducoravu** [comment]
Reported also more recently on the DITA Users List:
https://groups.yahoo.com/neo/groups/dita-users/conversations/topics/43844

**Comment by robander** [comment]
Added to 3.2.1 because it looked like this would be resolved by #3155, but reading more closely I'm not sure -- need to test to be sure.

**Comment by robander** [comment]
It looks like 3155 only partially fixes this.

The conkeyref attributes are now resolved in the same way, whether the DITAVAL docs are in the same directory or one level up. But they're not filtered in the first branch (each key is resolved as "product-1 product-2" or "handler-1 handler2"). The second branch is filtered. So, there is still an issue here.

**Comment by jelovirt** [comment]
@robander Do you want to tackle this in 3.2.1, or fix in a later release?

**Comment by robander** [comment]
@jelovirt I think this is for later - it's likely an unrelated part of the code so the recent fix won't help much with diagnosing.
