### ISSUE TITLE
./gradlew fails because of missing dependency (compass-1.0.3.gem)

### ISSUE THREAD

**Issue by dfemia** [dita-ot/dita-ot#2498]
./gradlew for DITA-OT fails for 2.2.4 and 2.3.3.

Full error message:
10:56:05 FAILURE: Build failed with an exception.
10:56:05 
10:56:05 * What went wrong:
10:56:05 Execution failed for task ':html5:compassCompile'.
10:56:05 > Could not resolve all dependencies for configuration ':html5:compass'.
10:56:05    > Could not determine artifacts for rubygems:compass:1.0.3
10:56:05       > Could not get resource 'http://rubygems-proxy.torquebox.org/releases/rubygems/compass/1.0.3/compass-1.0.3.gem'.
10:56:05          > Could not HEAD 'http://rubygems-proxy.torquebox.org/releases/rubygems/compass/1.0.3/compass-1.0.3.gem'.
10:56:05             > org.apache.http.client.ClientProtocolException (no error message)
10:56:05 
10:56:05 * Try:
10:56:05 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Link to issue seen on Travis CI:
[https://travis-ci.org/dita-ot/dita-ot/builds/165141741](url)

**Comment by jelovirt** [comment]
#2499 for replacing Compass with more direct use of libsass.

**Comment by jelovirt** [comment]
Fixed in #2499

**Comment by dfemia** [comment]
Thank you for fixing this issue so quickly!
