### ISSUE TITLE
 The topic reference href="#null" could not be found when publishing to PDF

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2501]
With the attached DITA project which is valid I'm getting an error in the console when publishing to PDF:

> [xslt] file:/C:/Users/radu_coravu/Desktop/chunk-map-stuff/maps/abc.ditamap:7:78: [PDFX005F][FATAL]: The topic reference href="#null" could not be found. Please correct the reference, or set the scope or format attribute if the target is not a local DITA topic.

**Comment by raducoravu** [comment]
Uploaded the ZIP to our web site, somehow I could no longer update it using GitHub's facilities:
https://www.oxygenxml.com/forum/files/chunk-map-pdf.zip

**Comment by fviolette** [comment]
Same issue here when chunking topics. `preprocess.chunk.skip` saves the day but, unless I missed it, it's not in the docs.

**Comment by raducoravu** [comment]
I tried to publish again to PDF my original samples using DITA OT 2.4.4 and I cannot seem to reproduce the problem anymore. What DITA OT version are you using? Do you obtain the problem using my samples or only using yours?

**Comment by fviolette** [comment]
With my own samples, I confirm that the issue is not found in DITA-OT 2.4.6 or 2.5.
