### ISSUE TITLE
Adjust table row span after filtering

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2504]
DITA source has tables with row spans and profiling attributes on rows. When publishing, the filter strips out some rows and the original `@morerows` is no longer valid. Right now this will fail in error because XSLT cannot deal with invalid tables like these.

One solution to fix this would be to write the custom table coordinate attributes during initial parse _and_ replace the `@morerows` with `@dita:rowspan-end`. This is similar to what CALS does with column span, specifying span end column name instead of span length. After filtering this could be converted back to `@morerows` by calculating the length with the current coordinates.

This would also work when conref push is used to push new rows into a rows span.
## Example

For DITA source and filter:

``` xml
<table>
  <tgroup cols="2">
    <tbody>
      <row>
        <entry morerows="2">A1</entry>
        <entry>A2</entry>
      </row>
      <row audience="expert">
        <entry>B2</entry>
      </row>
      <row>
        <entry>C2</entry>
      </row>
    </tbody>
  </tgroup>
</table>
```

``` xml
<val>
  <prop action="exclude" att="audience" val="expert"/>
  <prop action="include" att="audience"/>
</val>
```

Before filtering:

``` xml
<table xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot">
  <tgroup cols="2">
    <tbody>
      <row>
        <entry morerows="2" dita-ot:x="1" dita-ot:y="1" dita-ot:rowspan-end="3">A1</entry>
        <entry dita-ot:x="2" dita-ot:y="1">A2</entry>
      </row>
      <row audience="expert">
        <entry dita-ot:x="2" dita-ot:y="2">B2</entry>
      </row>
      <row>
        <entry dita-ot:x="2" dita-ot:y="3">C2</entry>
      </row>
    </tbody>
  </tgroup>
</table>
```

After filtering:

``` xml
<table xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot">
  <tgroup cols="2">
    <tbody>
      <row>
        <entry morerows="2" dita-ot:x="1" dita-ot:y="1" dita-ot:rowspan-end="3">A1</entry>
        <entry dita-ot:x="2" dita-ot:y="1">A2</entry>
      </row>
      <row>
        <entry dita-ot:x="2" dita-ot:y="3">C2</entry>
      </row>
    </tbody>
  </tgroup>
</table>
```

After `@morerows` and coordinate attribute adjustment:

``` xml
<table xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot">
  <tgroup cols="2">
    <tbody>
      <row>
        <entry morerows="2" dita-ot:x="1" dita-ot:y="1" dita-ot:rowspan-end="2">A1</entry>
        <entry dita-ot:x="2" dita-ot:y="1">A2</entry>
      </row>
      <row>
        <entry dita-ot:x="2" dita-ot:y="2">C2</entry>
      </row>
    </tbody>
  </tgroup>
</table>
```

**Comment by drmacro** [comment]
That seems reasonable. 

It would also be useful to have that information in the final table as provided to the table renderer. I have a client that was setting different edge borders on table cells by seeing if the cell was leftmost or rightmost, but the logic could account for row spans and determining that a given cell is adjacent to preceding vertically-spanned cell is hard to do. Having these attributes would have made solving the problem easier (we solved it by not doing it any more and using consistent rule weights throughout but that was the client's decision).
