### ISSUE TITLE
Generated IDs and hrefs do not match when chunk = "to-content" with DITA-OT 2.3.3

### ISSUE THREAD

**Issue by tomorales** [dita-ot/dita-ot#2505]
With DITA-OT 2.3.3, when using chunk = "to-content", the generated IDs and hrefs do not match. Attaching chunktest.zip which clearly demonstrates the problem. The output was generated with the DITA-OT html5 plugin.

The zip file contains two directories: nochunk and chunk

The nochunk directory contains a simple .ditamap with three topics. Examining the DITA sources and the output we see:

chunktest.ditamap references the three topics intro.dita, overview.dita, and creating.dita. The output index.html file references intro.html, overview.html, and creating.html.

intro.dita contains an id="intro" on the topic <concept> element and an id="animals" on the <table> element. intro.html contains an id="intro" on the <body> element and an id="intro__animals" on the <table> element; the html5 plugin concatenates the topic's ID, a '__' instead of a '/', and the element's ID.

The chunk directory contains the same .ditamap except now chunk="to-content" is on the intro.dita topicref, which means that intro.dita, overview.dita, and creating.dita will be chunked into a single output file.

Examining chunk/out/index.html now shows hrefs to intro.html#intro, overview.html#overview, and creating.html#sqlj which attempt to point to the IDs for the individual topics which are now part of the single ditabase output file. The fragment identifiers are the original, unmodified IDs.

Examining chunk/out/intro.html now shows IDs "intro" (at the start of the original intro topic), intro__overview, and intro__sqlj. The IDs seem to be formed by concatenating the topmost topic ID, a '__' and the original subtopic ID.

The IDs and hrefs don't match.
[chunktest.zip](https://github.com/dita-ot/dita-ot/files/529892/chunktest.zip)

**Comment by shudson310** [comment]
We are seeing the same problem, regardless of whether the chunk attribute is set or not. The / in the href is converted to _, which breaks the link.
[Test_OT.zip](https://github.com/dita-ot/dita-ot/files/534100/Test_OT.zip)

I think the issue is in <xsl:template name="href"> in rel-links.xsl
