### ISSUE TITLE
Branch Filtering Does not Correctly Filter Topic

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2514]
The map is valid in Oxygen and Oxygen reflects the expected filtering when using the included ditavals as the basis for Oxygen profiling conditions.

When I run with current development code only one of the result HTML files reflects the filtered-in value, the other two topics reflect no value. The value actually used seems to be random.T

There are no errors reported in the log

[getting-started-guide.zip](https://github.com/dita-ot/dita-ot/files/562226/getting-started-guide.zip)

**Comment by SanFanDocu** [comment]
In my Oxygen setup (18, build-in OT) this problem occurs if a profiling conditional set is selected during transformation.
In this case only the selected scenario/DITAVAL is processed and all other are not.
I have selected in the Transformation Scenario Preferences on the Filters tab the option `Use DITAVAL file` without assigned filepath. With this it is not relevant whether a profiling conditional set is selected/active during transformation or not.
