### ISSUE TITLE
Issue with dita-ot 2.2+

### ISSUE THREAD

**Issue by arronvarga** [dita-ot/dita-ot#2517]
When trying to output documentation with mailto reference in a xref.  If the reference has a space the DITA-OT engine fails.

BUILD FAILED
D:\sApps\Ixiasoft\OutputGenerator\OG_4.2\temp\HCIT_Reverb.axhxu.140.1478621441933\build.xml:7: The following error occurred while executing this line:
D:\sApps\Ixiasoft\OutputGenerator\OG_4.2\data\dita-ot-2.3.3\build.xml:41: The following error occurred while executing this line:
D:\sApps\Ixiasoft\OutputGenerator\OG_4.2\data\dita-ot-2.3.3\plugins\org.dita.base\build_preprocess.xml:42: Failed to run pipeline: Illegal character in opaque part at index 50: mailto:doc_feedback@agfa.com?subject=Documentation feedback

There were no issues in 1.8.5 or 2.1.1

**Comment by xephon2** [comment]
Hi,

I cannot reproduce that with DITA-OT 2.3.3. Please make sure that you set `format="html"` and `scope="external"`:

```xml
<xref href="mailto:name@mail.com?subject=Mail Subject" format="html" scope="external">name@mail.com</xref>
```

If that still does not work, please replace any spaces or characters with their corresponding entities, for example a space with `%20`:

```xml
<xref href="mailto:name@mail.com?subject=Mail%20Subject" format="html" scope="external">name@mail.com</xref>
```

I hope that helps. :smile:
