### ISSUE TITLE
Chinese punctuation looks lower than Chinese characters in published PDF

### ISSUE THREAD

**Issue by CiraGuo** [dita-ot/dita-ot#2518]
We use DITA-OT with FOP to publish DITA files into PDF file and find the following problem. (But when we test it using AH to do the publish, it is correct.)

The content in DITA files are most in Chinese. The requirement is Chinese characters should use SimSun or SimHei while number and Alphabat characters should use Times New Roman. We find some Chinese punctuations like ‘%，。’ will be shown lower than other Chinese characters, which looks not good.

But if we changed font-mappings file like following, the Chinese punctuations shown as the same baseline as Chinese Character. 

```xml
<logical-font name="Normal">
      <physical-font char-set="default">
        <font-face> SimSun, Times New Roman, Times</font-face>
      </physical-font>
      <physical-font char-set="Simplified Chinese">
        <font-face>SimSun</font-face>
      </physical-font>
      <physical-font char-set="Symbols">
        <font-face>ZapfDingbats</font-face>
      </physical-font>
      <physical-font char-set="SubmenuSymbol">
        <font-face>ZapfDingbats</font-face>
      </physical-font>
</logical-font>
```

The only thing we do is changed `<font-face> Times New Roman, Times, SimSun</font-face>`
to `<font-face> SimSun, Times New Roman, Times</font-face>`

But it make another problem: all characters in files are in SimSun or SimHei, including number and alphabat which we want them in Times New Roman. Furthermore, some entity like `&#160;` defined in `zh-CN.xml` file will be shown in "#", which looks like it doesn't find the correct character set.

**Comment by jockster74** [comment]
@CiraGuo Please provide:

- Sample files to allow reproducing the problem locally,
- Information on what version of DITA OT you are using, as well as what version of FOP, AH are used, etc.

Details, details. Without them no one can give analyze the issue properly.

**Comment by CiraGuo** [comment]
@jockster74 
how to provide sample files?  I haven't found the way to upload files.
The DITA version is DITA-OT2.0.M1 and it is easy fully installed. So we used the embed FOP tool.

**Comment by xephon2** [comment]
@CiraGuo, create a ZIP file and pull it to the comment window.

> Attach files by dragging & dropping, selecting them, or pasting from the clipboard.

**Comment by CiraGuo** [comment]
The steps to reproduce the issue:
1.Please put the following font-mappings.zip file into DITA-OT2.0.M1\plugins\org.dita.pdf2\cfg\fo folder:
[font-mappings.zip](https://github.com/dita-ot/dita-ot/files/605578/font-mappings.zip)

2. Use the TestData to do PDF publish
[TestData.zip](https://github.com/dita-ot/dita-ot/files/605581/TestData.zip)

3. You can get the published PDF file like this:
[50802.pdf](https://github.com/dita-ot/dita-ot/files/605583/50802.pdf)
On the third page, you can find "95%" is lower than other chinese characters.

4. If you change font-mappping file as following, "95%" is as same baseline as chinese characters, but numberic and alphbat looks different than changed before.
[font-mappings.xml.zip](https://github.com/dita-ot/dita-ot/files/605591/font-mappings.xml.zip)

**Comment by CiraGuo** [comment]
If anyone has any idea about it?
