### ISSUE TITLE
Unresolved internal destination: 'null' (problem added in DITA OT 2.4)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2522]
One of our clients reported a warning given by the PDF publishing using XEP (but can also reproduced using FOP) with the latest DITA OT 2.4. I cannot reproduce the issue with 2.3.3.

Sample files:
[unresolved_internal.zip](https://github.com/dita-ot/dita-ot/files/596919/unresolved_internal.zip)

Warning in console:

          [xep] [XEPJ001W][WARN] unresolved internal destination: 'null'

The issue is related to the use of the collection-type attribute.

**Comment by DaveDITA** [comment]
This issue appears to still exist in 2.4.2, but it's not just a warning. It's broken links (pointing to null) in the PDF output, with FO code like this:

<fo:basic-link internal-destination="null">

2.3.3 didn't have the issue, as Radu says. In my content, collection-type="family" produces these broken links for some related topics. Other values do not. 

Example files attached. On my system, the link labeled "Three" under heading "Two" points to null.

[collectiontype.zip](https://github.com/dita-ot/dita-ot/files/691039/collectiontype.zip)
