### ISSUE TITLE
Dita-OT 2.4 is 50% as fast as 2.3.3

### ISSUE THREAD

**Issue by hscherzer** [dita-ot/dita-ot#2527]
Having migrated to 2.4 I found that the processing of exactly the same file on the same PC (= fair conditions) take approx. DOUBLE THE TIME than in 2.3.3.

To evaluate the Problem I added checks to the log file to see where the time goes.
`Version DITA-OT 2.3.3                                       Version DITA-OT 2.4`
` [echo] Elapsed time:    31 ms (check-arg)                       31 ms (check-arg)`
` [echo] Elapsed time:   234 ms (log-arg)                        234 ms (log-arg)`
` [echo] Elapsed time:  3198 ms (gen-list)                      6271 ms (gen-list)`
` [echo] Elapsed time:  1793 ms (debug-filter)                  2012 ms (debug-filter)`
` [echo] Elapsed time:  1139 ms (mapref)                        1076 ms (mapref)`
` [echo] Elapsed time:   904 ms (keyref)                        1155 ms (keyref)`
` [echo] Elapsed time:    94 ms (copy-to)                       1311 ms (copy-to)`
` [echo] Elapsed time:   249 ms (maplink)                        358 ms (maplink)`
` [echo] Elapsed time:  2261 ms (topicpull)                     1950 ms (topicpull)`
` [echo] Elapsed time:  1803 ms (transform.topic2fo.init)       1935 ms (transform.topic2fo.init)`
` [echo] Elapsed time:  2105 ms (transform.topic2fo.main)       2215 ms (transform.topic2fo.main)`
` [echo] Elapsed time: 14500 ms (map2pdf2)                     31818 ms (map2pdf2)`
 ` BUILD SUCCESSFUL`
` Total time: 35 seconds`         vs                             `Total time: 1 minute 9 seconds`

Could you pls check whether you might have compiled the .jar with some 'debug' mode or any reason why the process takes double the time.  I could continue research but I guess you are much faster than I'd be.

I did not catch all processes, so the total will not be the sum of all the single processes, but the list does show some significant differences nevertheless.

Thanks for caring ... Helmut
[ElapsedTimePDF2-2v3v3vs2v4.txt](https://github.com/dita-ot/dita-ot/files/605992/ElapsedTimePDF2-2v3v3vs2v4.txt)

**Comment by xephon2** [comment]
Dear Helmut,

thank you for reporting this. Please upload a sample project for reproducing this, if possible. If you use *&lt;oXygen/&gt; 18.1*, copy your project and use the *Help* > *Support Tools* > *Randomize XML text content* function to scramble the textual content. That would help the developers a lot.

Greetings,
Stefan

**Comment by hscherzer** [comment]
Dear Stefan,

 

thanks for your answer and I do perfectly understand your point. Since I'm compiling a very normal document and not doing any magic (with personal plugins etc) I assumed that it would be possible to see that difference on any document of your choice. And of course I will provide a full project + document (oxygen 18.1 based) that allows to test ist. Will take a day …

 

Cheers … Helmut

**Comment by hscherzer** [comment]
It took quite some time to continue this thread. I was in South Africa for several weeks and the entire action  was delayed. Here is my current status:
**DITA-OT 2.4.1  compared to 2.3.3 is performing OK (not slower as indicated in this thread)**.
My initial observation (2.4.1 50% slower than 2.3.3) is ONLY true on my company laptop which uses disk encryption. Indeed there the difference is very significant - can be 30 seconds(2.3.3) to 90 seconds(2.4.1).

I created a profiler (see below) and finally I recorded all processing step's execution times in an EXCEL
that showed me the major loss in the **publish.map.pdf** process, I will continue some research there, but I do not want/need the precious DITA-OT team to work on that 'special case'.
**Thanks for caring !!!**
...
So you don't need to change ... but I might give some more good ideas to the point ...

I **profiled** the process in order to learn which of the steps take the time. Find the associated templates attached for your further use, if you ever are interested to take such measurements.

[build_preprocess_template.xml.txt](https://github.com/dita-ot/dita-ot/files/684966/build_preprocess_template.xml.txt)
[build_template.xml.txt](https://github.com/dita-ot/dita-ot/files/684969/build_template.xml.txt)
[build_axf.xml.txt](https://github.com/dita-ot/dita-ot/files/684971/build_axf.xml.txt)
[PROFILES.TXT](https://github.com/dita-ot/dita-ot/files/684972/PROFILES.TXT)

PROFILES.TXT shows where these files belong ... in general the trick is to put two macro definitions into one of the ANT xml files using **chk.start** and **chk.stop**

 ```
 <macrodef name="chk.start">
    <attribute name="testname"/>
    <sequential>
      <script language="javascript">
           project.setProperty('@{testname}_x', new Date().getTime());
      </script>
    </sequential>
  </macrodef>

  <macrodef name="chk.stop">
    <attribute name="testname"/>
    <attribute name="modname"/>
    <element name="params" optional="true" implicit="true"/>
    <sequential>
      <script language="javascript">
          project.setProperty('elapsedTime', new Date().getTime() - @{testname}_x)
      </script>
      <echo>HSCT:Elapsed time: ${elapsedTime} ms (@{modname})</echo>
    </sequential>
  </macrodef>
```
and then to use them in a target like ..
```
  <target name="move-meta-entries"
    dita:depends="{depend.preprocess.move-meta-entries.pre}"
    dita:extension="depends org.dita.dost.platform.InsertDependsAction"
    unless="preprocess.move-meta-entries.skip"
    description="Move metadata entries">
    <chk.start testname="move_meta_entries"/>
    <pipeline message="Move metadata entries." taskname="move-meta"
      inputmap="${user.input.file}">
      <module class="org.dita.dost.module.MoveMetaModule">
        <param name="style" location="${dita.plugin.org.dita.base.dir}/xsl/preprocess/mappull.xsl"/>
        <param name="conserve-memory" expression="${conserve-memory}" if="conserve-memory"/>
        <dita:extension id="dita.preprocess.mappull.param" behavior="org.dita.dost.platform.InsertAction"/>
      </module>
    </pipeline>
    <chk.stop testname="move_meta_entries" modname="move-meta-entries"/>
  </target>

```
_testname_ shall not have operator characters . - / etc. therefore there is
_modname_ which allows to put any text as the label

A potential logfile would then look like the attached logfile

[logpdf2muc.txt](https://github.com/dita-ot/dita-ot/files/684990/logpdf2muc.txt)

using the HSCT:Elapsed time .. statements

I will close this thread by mid January ... just if someone wanted to add something.
