### ISSUE TITLE
List of DITA Open Toolkit issues which in my opinion would need to be addressed

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2528]
At some point I told @jelovirt I had a list of DITA Open Toolkit issues which I considered that need to be addressed so I'm opening this issue as a way to split enumerate those issues in categories and enumerate them. 

- DITA 1.3 support:
  - Support for MathML:
   https://github.com/dita-ot/dita-ot/issues/1774
   https://github.com/dita-ot/dita-ot/issues/2391
  - Support for SVG:
  https://github.com/dita-ot/dita-ot/issues/1123
  - Support for Troubleshooting:      
   https://github.com/dita-ot/dita-ot/issues/1771
  
  - Key scope related bugs:
  https://github.com/dita-ot/dita-ot/issues/2410
  https://github.com/dita-ot/dita-ot/issues/2393
  https://github.com/dita-ot/dita-ot/issues/2525
  ~https://github.com/dita-ot/dita-ot/issues/2523~
  
  - Branch filtering related bugs:
  ~https://github.com/dita-ot/dita-ot/issues/1998~
  https://github.com/dita-ot/dita-ot/issues/2147
  https://github.com/dita-ot/dita-ot/issues/1999
  
Now various other issues:

- Recent problem related to the changing of the processing stages, conref can no longer be used in keyword metadata:
https://github.com/dita-ot/dita-ot/issues/2420

- Issues related to the map reference expansion which possible could be fixed by the mapref processing @jelovirt in working on:
~https://github.com/dita-ot/dita-ot/issues/2494~
~https://github.com/dita-ot/dita-ot/issues/2476~ (obsolete)

- ~Navigation title without locktitle in topicref overrides topic title: 
https://github.com/dita-ot/dita-ot/issues/2187~ (resolved)

- PDF TOC issue which can probably be fixed now after the upgrade to Apache FOP 2.1:
~https://github.com/dita-ot/dita-ot/issues/2403~

- ~Flagging no longer works with specialized @props attributes:~
~https://github.com/dita-ot/dita-ot/issues/2392~ (obsolete)

- Distinct HTML files are created for multiple references to the same topic, even if they are in the same key scope (or there is no key scope defined):
https://github.com/dita-ot/dita-ot/issues/2363

- ~NullPointerException in Eclipse Help output:~ https://github.com/dita-ot/dita-ot/issues/1885 (closed)

- Issues related to chunking. Such issues usually result in broken links between topics, broken references to the CSS files...: 
https://github.com/dita-ot/dita-ot/issues/2298
~https://github.com/dita-ot/dita-ot/issues/2452~ (resolved)
https://github.com/dita-ot/dita-ot/issues/2385
https://github.com/dita-ot/dita-ot/issues/2450
https://github.com/dita-ot/dita-ot/issues/2040
https://github.com/dita-ot/dita-ot/issues/2188
https://github.com/dita-ot/dita-ot/issues/2064

- Problem with abbreviated-form handling:
https://github.com/dita-ot/dita-ot/issues/2067

- Problem with related links and profiling attributes:
 https://github.com/dita-ot/dita-ot/issues/2200 

- Ambiguous error messages:
~https://github.com/dita-ot/dita-ot/issues/2079~

- PDF Bookmark part with no title generates empty entry in TOC:
https://github.com/dita-ot/dita-ot/issues/1930

As a conclusion, I think chunking has the most problems right now in the DITA OT. The DITA 1.3 support is also half baked, support for some major features is missing and there are problems with the implemented features.

**Comment by shaneataylor** [comment]
I'd submit that #2576 is another must-fix branch filtering bug. 

@infotexture If these critical issues can't be fixed — some of them have languished for a while — maybe we should try to identify and document the DITA implementation patterns to avoid (and workarounds where possible) to mitigate their impact. 

While I'm not a big fan of having to code your DITA around the limitations of the DITA-OT, it _is_ an open source project with limited resources, and as a matter of practice I suspect many of us _do_ already code around specific problems we've encountered.

As an extension to this effort, maybe some of these patterns can be identified by (Schematron or other) processing early in the build (or by authoring tools) to warn users that while this is a legal DITA construct it's one that might have limited support in the toolkit.

**Comment by infotexture** [comment]
> maybe we should try to identify and document the DITA implementation patterns to avoid

@shaneataylor Sounds familiar, contributions welcome.

See https://github.com/dita-ot/docs/issues/63 for related discussion.

**Comment by kirkilj** [comment]
I really like the idea @shaneataylor posted about maintaining a Schematron rule set to warn users about unimplemented or buggy OT features.

**Comment by jelovirt** [comment]
Moved into https://github.com/orgs/dita-ot/projects/19
