### ISSUE TITLE
Saxon EE cannot find files

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/dita-ot#2530]
Hi,

While trying to use Saxon EE to support a customization I am developing I encountered this error 

`Error: Failed to run pipeline: Failed to parse map: c:\build\temp\THEMAPNAME.ditamap `
`Process ended with exit code: 1`

Upon investigation I found that the map had been copied to the temp directory but with a suffix :

`c:\build\temp\THEMAPNAME.ditamap.tmp1480328744278`

I am using Saxon EE version 9.7 and I added it to DITA-OT using the **dita.conductor.lib.import** extension point.

Can you help me with this?

**Comment by jelovirt** [comment]
Closing as support
