### ISSUE TITLE
integrator misses libraries (DITA-OT v2.4)

### ISSUE THREAD

**Issue by PStellmann** [dita-ot/dita-ot#2531]
I just ugraded to DITA-OT 2.4. before I just executed 
`ant -f integrator.xml`
from command line to integrate my custom plugins. Now I get a NoClassDefFoundError.

Explicitly adding two libraries solved this:
`C:\SVN\SAIP\Doku-Framework\DITA-OT>ant -f integrator.xml -lib lib/guava-19.0.jar -lib lib/commons-io-2.5.jar`

I'm wondering if there's a way to avoid the necessity of adding these libraries!?

**Comment by infotexture** [comment]
In DITA-OT 2.4, you don't need to run Ant to [install plug-ins](http://www.dita-ot.org/dev/dev_ref/plugins-installing.html), just `dita --install`.

**Comment by PStellmann** [comment]
Indeed, this works fine.
Thanks.
