### ISSUE TITLE
Cannot get correct filtered result using Hierarchy subjectscheme

### ISSUE THREAD

**Issue by CiraGuo** [dita-ot/dita-ot#2544]
I test hierarchy subjectscheme in DITA-OT 2.0, and cannot get the result I want. Following is the steps I do the test:
1.  use DITA-OT 2.0 docsrc sample files as input file, the file name is userguide-book.ditamap
2.  create ditaval file named 2.ditaval, exclude platform="unix", add the following code to 2.ditaval:
     ```xml
     <val>
       <prop action="exclude" att="platform" val="unix"></prop>
     </val>
    ```
    Since in subjectscheme.ditamap file, unix contains linux and osx
    ```xml
    <enumerationdef>
        <attributedef name="platform"/>
        <subjectdef keys="windows"/>
        <subjectdef keys="unix">
          <subjectdef keys="osx"/>
          <subjectdef keys="linux"/>
        </subjectdef>
      </enumerationdef>
    ```
    Thus, if unix is excluded, it means osx and Linux will also be excluded.
3.  use ant command to get pdf published file:
    ```bash
    ant -Dargs.input=D:\DITA-OT2.0.M1\docsrc\userguide-book.ditamap -Doutput.dir=c:\downloads -Dtranstype=pdf2 -Dargs.filter=D:\DITA-OT2.0.M1\docsrc\2.ditaval
    ```
4.  Check if text with platform="linux" or platform="osx" or platform="unix" are excluded, but failed. For example, in "Installing the full-easy-install package" topic, content of "Linux or Mac OSX DITA-OT2.0.M1_full_easy_install_bin.tar.gz" is still exist.

**Comment by raducoravu** [comment]
How exactly are you referencing to the subject scheme map in the main DITA Map? Did you set the type="subjectScheme" attribute on the topicref? 
Otherwise, it might now work:
https://github.com/dita-ot/dita-ot/issues/1482
