### ISSUE TITLE
Can't specify extended properties to dita command using double hyphen format

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2558]
The usage info for the dita command now (2.4.2+) prints the following:

` --<property>=<value>        use value for given property`

But this doesn't work. You must still use a single hyphen, for example:

`dita -Dbasedir=$PWD --propertyfile test.properties`

Also, the usage info probably should include the requirement to prefix additional values with D.

**Comment by infotexture** [comment]
I can't reproduce this. 

I've had no trouble with the double-hyphen syntax since it was introduced.

Can you provide the exact command line call that's failing for you?

**Comment by jelovirt** [comment]
The example you're using is `-Dbasedir=$PWD`, that maps to `--basedir=$PWD`.

Note that Ant's `basedir` should not be overridded.
