### ISSUE TITLE
Problem rendering SVG files in PDF with DITA-OT 2.4.x

### ISSUE THREAD

**Issue by ru-fu** [dita-ot/dita-ot#2571]
SVG files that contain multi-line text are rendered with all text in the same line in PDF. For example:
![input](https://cloud.githubusercontent.com/assets/11227796/21985248/ffa1e4f2-dbf9-11e6-9e54-898f9a1b6b29.PNG) [visio.svg.txt](https://github.com/dita-ot/dita-ot/files/708508/visio.svg.txt)

gives the following output:
![output](https://cloud.githubusercontent.com/assets/11227796/21985297/3440509a-dbfa-11e6-9015-8ce305066a9f.PNG)

It works fine in DITA-OT 2.3.3, and it also works after copying the org.dita.pdf2.fop from 2.3.3 to 2.4.2.

Now, the org.dita.pdf2.fop plugin has changed completely between 2.3.x and 2.4.x, so I can't track down what causes the problem.
The SVG file displays just fine in Batik's Squiggle tool, so I would guess that it's not an error in the Batik 1.8 libraries. Which means it might either be in FOP 2.1 or in DITA-OT. Any ideas how to narrow that down?

**Comment by raducoravu** [comment]
This is an Apache FOP 2.x issue. The Apache FOP bundled with DITA OT was recently upgraded to 2.1:
https://github.com/dita-ot/dita-ot/pull/2399
I added the issue to the Apache FOP issues list a couple of months ago:

https://issues.apache.org/jira/browse/FOP-2617

You might want to test the last workaround proposed by them, to use in fop.xconf:

               <complex-scripts disabled="true"/>
