### ISSUE TITLE
args.logdir has no effect

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2579]
To generate a log file with the toolkit, the log file name must be specified on the DITA command line.  Its path, if not specified, if always relative to the input directory. Setting args.logdir has no effect.

If we are not going to implement this parameter, we should deprecate it and indicate that it does nothing.

**Comment by shaneataylor** [comment]
If we _are_ to implement this parameter:
* when args.logdir is specified and a log filename is not specified, we should turn on logging with a default filename relative to args.logdir.
* when args.logdir is specified and a relative log filepath is specified, the log file should be relative to args.logdir
* when args.logdir is specified and an absolute log filepath is specified, the log filepath should be respected.

It would be helpful when a log file is generated to output the location of the log on the console for the user.

**Comment by shaneataylor** [comment]
Conditions of my experience:
DITA-OT 2.4.2
MacOS
Used dita command line
Specified a log filename only: `-l log.xml` 
Set args.logdir in a properties file

**Comment by jelovirt** [comment]
args.logdit is an obsolete argument. It should be removed in 2.5 or 2.4.3.

**Comment by robander** [comment]
Not sure how to tag this one - going with "enhancement" because it is an update to remove an obsolete feature. I'll open a doc issue to make sure it's either removed or marked obsolete in the docs.

**Comment by infotexture** [comment]
> It would be helpful when a log file is generated to output the location of the log on the console

👍 That would be helpful indeed.
