### ISSUE TITLE
Improve error messages reported when having conref to non-existing topic

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2580]
Let's say that in a DITA topic I have a conref to an non-existing file:

             <p conref="nonExisting.dita#a/b"/>

when publishing to XHTML-based content, the conref resolution stage in the XSLT stylesheet complains like:

			   [conref] Processing D:\projects\eXml\samples\docbook\v5\temp\chm\bla.dita
			   [conref] Recoverable error 
			   [conref]   FODC0002: I/O error reported by XML parser processing
			   [conref]   file:/D:/projects/eXml/samples/docbook/v5/temp/chm/abc.dita:
			   [conref]   D:\projects\eXml\samples\docbook\v5\temp\chm\abc.dita (The system cannot find the file specified)
			   [conref] Type error at char 10 in xsl:variable/@select on line 175 column 144 of conrefImpl.xsl:
			   [conref]   XTTE0570: An empty sequence is not allowed as the value of variable $domains
			   [conref]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/conrefImpl.xsl#799)
			   [conref]      processing /topic/body[1]/p[1]
			   [conref]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/conrefImpl.xsl#799)
			   [conref]      processing /topic/body[1]
			   [conref]   at xsl:apply-templates (file:/D:/projects/eXml/frameworks/dita/DITA-OT2.x/xsl/preprocess/conrefImpl.xsl#29)
			   [conref]      processing /topic
			   [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains

In my opinion this case should be signaled from the XSLT stylesheet using the regular [DOTX....] pattern so that it could be picked up and presented as an error.

**Comment by robander** [comment]
I'd appreciate an update like this - these messages have been an annoyance since the first days of DITA-OT, when the target document of a content reference is unavailable.

**Comment by raducoravu** [comment]
Problem can no longer be reproduced with DITA OT 3.2.1, the publishing engine reports:

       [conref] file:/D:/projects/eXml/samples/dita/flowers/topics/introduction.dita:12:43: [DOTX010E][ERROR]: Unable to find target for conref="nonExisting.dita#a/b".
