### ISSUE TITLE
Provide contents of DITAVAL in log file

### ISSUE THREAD

**Issue by juliovaz** [dita-ot/dita-ot#2582]
Troubleshooting problems caused by filtering requires knowledge of the contents of the ditaval and any topics that may be failing. Currently, the log contains warnings about files that do not generate output which could later cause the build to fail. For a support person who may not have immediate knowledge of the filtering used, it would be useful to have the contents of the DITAVAL file in the log to aid in troubleshooting.

**Comment by robander** [comment]
When @juliovaz suggested this to me yesterday, I suggested opening an issue for discussion. I could see this being useful in some cases, but in an average log it would probably just be noise, so I'm not sure it would be appreciated in most cases. Which leads me to think it would be better as an option - which then leads me to think this would be better as a plugin - but I'd like to hear if anybody else feels differently.

**Comment by juliovaz** [comment]
I wouldn't mind it as an option. I think a plug-in puts a requirement on someone to remember to install it with version changes.

**Comment by robander** [comment]
> I think a plug-in puts a requirement on someone to remember to install it with version changes.

True ... though I'll note that's also true for *any* extension that's not generally applicable / not actively maintained by the very small set of core developers. I've got about 25 or 30 plugins now for various functions / specializations and shells / transform styles that I have to drag over to each new version.

**Comment by xephon2** [comment]
Because filter values are as important as properties for debugging, they should be handled similar.

**Comment by robander** [comment]
Just for kicks, I put together a plug-in that does this - it was simpler than I thought. If you put these two files in a plugin, it will copy the DITAVAL contents into your log before the preprocess starts, for any output format that uses the normal preprocess. It could put them up after if you switch the extension to `depend.preprocess.post`:

***plugin.xml***
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="org.metadita.log.ditaval">
  <feature extension="dita.conductor.target.relative" file="log-ditaval.xml"/>
  <feature extension="depend.preprocess.pre" value="log.my.ditaval"/>
  <require plugin="org.dita.base" />
</plugin>
```

***log-ditaval.xml***
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="org.metadita.log.ditaval">
  <target name="log.my.ditaval" if="args.filter">
    <loadfile property="ditaval.conents" srcfile="${args.filter}"/>
    <echo>Copy DITAVAL contents for debugging:
${ditaval.conents}</echo>
  </target>
</project>
```

Tested with 2.4.3.
[org.metadita.log.ditaval.zip](https://github.com/dita-ot/dita-ot/files/751637/org.metadita.log.ditaval.zip)

**Comment by jelovirt** [comment]
Outputing the ditaval file should not be part of default output. The path of the ditaval file is in the log, it can be found from there. 

Pluging can be used for this.
