### ISSUE TITLE
Local properties is ready from basedir

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2586]
Since users may override `basedir` Ant property, reading `local.properties` should use `dita.dir` as base directory.

**Comment by infotexture** [comment]
@jelovirt Will this change permit users to specify absolute paths using `${basedir}` in custom properties files passed with `--propertyfile=file`?

(See [docs-build-html5.properties]( https://github.com/dita-ot/docs/blob/develop/samples/properties/docs-build-html5.properties#L17) for an example.)

This works with both Ant & Gradle builds, but currently throws an error when passed to the `dita` command as follows:

```
dita --input=userguide.ditamap --format=html5 
     --propertyfile=samples/properties/docs-build-html5.properties

[DOTA008E][ERROR] Cannot find the running-header file "${basedir}/resources/header.xml". 
Please double check the value to ensure it is specified correctly.

[xslt]   FODC0002: java.io.FileNotFoundException: /${basedir}/resources/header.xml 
(No such file or directory)
```

**Comment by jelovirt** [comment]
Basedir should never ever be overridden to be something other than OT installation directory. This change only changes how path to read local properties is constructed.

**Comment by infotexture** [comment]
@jelovirt In the example above, the intention is not to *override* `${basedir}` but rather to _use_ it to construct an absolute path for `args.hdr`.

If this is not the right approach, we should provide guidance on the correct method of specifying absolute paths in cross-platform build environments, but we can carry on that discussion in dita-ot/docs#128.
