### ISSUE TITLE
Need to specify logfile as a build parameter, not just on the command line

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2587]
@infotexture @keberlein / Related to #2579 

Building multiple targets and creating a log file for each target is a common workflow. A log filename can be specified on the command line for Ant or dita-command based builds, but this does not address the problem for a single build with multiple targets, and adds complexity to build scripts that run multiple builds.

Proposing that we create a new `args.logfile` parameter for builds that can be set either by the current `--logfile` command argument or in a properties file.

**Comment by jelovirt** [comment]
If you want multiple log files per or control the log file from Ant, use Ant's `record` target. DITA-OT uses Ant project's logger as the final destination of the log. DITA-OT core should not care what is done with the log and how. Just like DITA-OT doesn't care how it's invoked.

**Comment by robander** [comment]
I think I'm with @jelovirt on this one - I'm very wary of tying us closer into Ant, which currently controls all of the logging. Our current parameter just translates into normal Ant logging, I'd rather we not try to customize Ant further with separate logs.

I've had this same _desire_ for distinct logs in the past - but have personally handled it with a batch script. My windows BAT script looks roughly like this:
```
call bin\dita -i \testfiles\testA.ditamap -f html5 -o out\testA\ -l out\testA\testAhtml.log
call bin\dita -i \testfiles\testA.ditamap -f pdf -o out\testA\ -l out\testA\testApdf.log
call bin\dita -i \testfiles\testB.ditamap -f html5 -o out\testA\ -l out\testB\testBhtml.log
call bin\dita -i \testfiles\testB.ditamap -f pdf -o out\testA\ -l out\testB\testBpdf.log
```

I've also used this with a single Ant build that has multiple targets (this is actually how I created log files when testing builds of the DITA spec):
```
call bin\ant -f dita-1.3-spec.xml xhtml -l specxhtml.log
call bin\ant -f dita-1.3-spec.xml pdf -l specpdf.log
call bin\ant -f dita-1.3-spec.xml chm -l specchm.log
```

**Comment by shaneataylor** [comment]
I don't disagree that the architectural argument has validity, and that it's possible to work around the limitation with external scripting. 

I'll say only that logging is a critical component of the DITA-OT functionality in production (and more so when doing continuous integration) and there is business value in the proposed feature. If we were a business.

**Comment by jelovirt** [comment]
Logging is critical and log output file _can_ be defined with the _current_ code. Thus no business value is lost by not implementing this way of defining logs.
