### ISSUE TITLE
Skip copy of html5 plugin default css

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/dita-ot#2592]
I would like to not copy commonltr.css and commonrtl.css when using a plugin that depends on org.dita.html5 but my Ant-fu is not strong enough.

I have identified the target ``html5.css`` in the [html5 build](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.html5/build_dita2html5_template.xml) as the location of this copy instruction:

```
  <target name="html5.css" unless="user.csspath.url" description="Copy CSS files">
    <condition property="user.copycss.yes">
      <and>
        <equals arg1="${args.copycss}" arg2="yes"/>
        <isset property="args.css.present"/>
      </and>
    </condition>
    <property name="user.csspath.real" location="${output.dir}/${user.csspath}"/>
    <mkdir dir="${user.csspath.real}"/>
    <!-- Always copy system default css files -->
    <copy todir="${user.csspath.real}">
      <fileset dir="${dita.plugin.org.dita.html5.dir}/css" includes="*.css"/>
    </copy>
    <!-- Copy user specify css file when required -->
    <antcall target="html5.copy-css-user"/>
  </target>
```

Is there a way to override the first `<copy>` instruction?

**Comment by jelovirt** [comment]
There is no easy way to skip the copy. A guard should be added to `html5.css` to make it easier to skip it.

**Comment by lionelmoi** [comment]
Yep, that would be swell. 

The only way I found was to add a step named `html5.css` to my plugin build file. It seems to override the one in the core plugin. If I understand well it has something to do with the [import task in Ant](http://ant.apache.org/manual/Tasks/import.html).
