### ISSUE TITLE
Should the PDF link page number (on page X) be part of the link?

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2595]
Whenever we have a link to another topic, the link gets generated in the PDF output to also include the page number (on page X).
Should that "on page" be part of the link or not?
If you look in the XSLT stylesheet:

DITA-OT2.x\plugins\org.dita.pdf2\xsl\fo\links.xsl

in some parts the "insertPageNumberCitation" seems to be called from inside the basic-link, and in others from outside of it.
One of our users somehow preferred for the "on page" to be part of the link.

**Comment by jelovirt** [comment]
This is one of those cases where both answers are correct. Some customers might want it to be inside the link and some prefer to have it outside. I don't feel strongly about either. If we had stats on which is more used approach, then we could go with that.

**Comment by tommyr1962** [comment]
Hello. I am the user working with Radu. We did have a requirement to have the page number citattion inside the link, so I adjusted the code accordingly. I am not sure what the majority feeling is on this, if there is one.

**Comment by drmacro** [comment]
Ideally it would be configurable and overriding the code would be easy (e.g., a separate module with just the cross reference generation code in it).

**Comment by shaneataylor** [comment]
One flexible approach would be to add a new `<link>` element to the language string syntax to specify what portion of the text is inside any generated link. For example, you could configure the string as: 
```xml
<variable id="On the page"><link><param ref-name="title"/> on page <param ref-name="pagenum"/><link></variable>
```
or
```xml
<variable id="On the page"><param ref-name="title"/> on <link>page <param ref-name="pagenum"/><link></variable>
```

**Comment by shaneataylor** [comment]
I could well see the requirements / preferred behavior being different for different languages, and this would give you a straightforward way to accomplish this.

**Comment by jelovirt** [comment]
Using variables is generally the correct way to handle these kinds of cases. However, variables cannot define how wrapping/nesting elements are used.

**Comment by tommyr1962** [comment]
Thanks, everyone. 

Shane, I will consider that as we do translate to over 30 languages.
