### ISSUE TITLE
"dita" command should log verbose output when the "-l" flag is set

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2597]
In my opinion setting the "-l" flag should also trigger verbose output, it would not make sense for somebody to want an empty log file.

Quote from Leigh White:

> If I simply use -l and specify a path and filename:

       C:\dita-ot-2.3.2\bin>dita -i c:\projects\markdowntest\markdowntest.ditamap -o c:\projects\markdowntest\_output -f xhtml -l c:\projects\markdowntest\output.log

> a completely empty log is written. If I add -v, I get most of a log

https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/41832

**Comment by jelovirt** [comment]
Closing as rejected, because adding feature like this would mean we would also need to add argument for getting "quiet" logging level (as opposed to verbose).
