### ISSUE TITLE
force-unique=true causes Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by aziliat** [dita-ot/dita-ot#2599]
I have tried the following command line run from the bin directory in DITA-OT 2.3.1, 2.41, 2.4.2, 2.4.3 and always receive Error: java.lang.NullPointerException

dita -f xhtml -Dforce-unique=true -o ../../out/xhtml -temp ../../temp/xhtml -Dclean.temp=no -verbose -i C:\dita-ot-2.4.3\docsrc\samples\taskbook.ditamap > xhtml.log

in taskbook.ditamap I duplicated the topicref 
<topicref href="taskbook/installdb.dita"/>
without adding a copy-to attribute

[taskbook.zip](https://github.com/dita-ot/dita-ot/files/770367/taskbook.zip)

**Comment by jelovirt** [comment]
Could you add the log file?

**Comment by aziliat** [comment]
attached full log file
[xhtml.zip](https://github.com/dita-ot/dita-ot/files/770372/xhtml.zip)

**Comment by jelovirt** [comment]
The stacktrace is not part of the log. It's probably printed on the console. Could you add that, because we need to know exactly which part of the code causes that exception.

**Comment by aziliat** [comment]
the only piece of information on the screen is the error:

Error: java.lang.NullPointerException

**Comment by aziliat** [comment]
just tested in 2.4.4 and this appears to be working

**Comment by jelovirt** [comment]
Closing as obsolete
