### ISSUE TITLE
html: add parameter to enable/disable table title label

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/dita-ot#2606]
Add a switch to turn off the addition of `<span class="table--title-label">` before the title during table generation.

**Comment by jelovirt** [comment]
My preference is *not* to add parameters for features like this, because it will lead to having 500+ parameters.

A workaround I use for this is

```css
.table--title-label { display: none }
```

To hide the label.

**Comment by lionelmoi** [comment]
OK good enough for me.
