### ISSUE TITLE
stylesheets/transformations relying on output-message.xsl fail

### ISSUE THREAD

**Issue by wschildbach** [dita-ot/dita-ot#2607]
We have a plugin that includes output-message.xsl. When we call a transformation relying on that plugin, we get a compilation error:

```
unit-cleanup:
[unit-cleanup] Transforming into c:\temp\converttmp
[unit-cleanup] Error at xsl:call-template on line 126 column 45 of output-message.xsl:
[unit-cleanup]   XTSE0650: No template exists named replace
[unit-cleanup] Error at xsl:call-template on line 138 column 43 of output-message.xsl:
[unit-cleanup]   XTSE0650: No template exists named replace
  [antcall] Exiting C:\dita\dita-ot-2.4.3\build.xml.
Error: java.lang.RuntimeException: Failed to compile stylesheet 'C:\dita\dita-ot-2.4.3\plugins\com.dolby.unit-cleanup\xsl\unit-cleanup.xsl': Failed to compile stylesheet. 2 errors detected.
```
This is with DITA-OT 2.4.3, on Windows 10.

The problem, I believe, lies with output-message.xsl which needs functionality from dita-utilities.xsl but does not include it.

**Comment by jelovirt** [comment]
Templates that use `output-message.xsl` must also import `dita-utilities.xsl`. Add the missing import to your shell stylesheet.
