### ISSUE TITLE
Can't generate "family" related links in PDF transformations

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2613]
In 2.4.3 (not yet tested for other versions), no parent, child, or sibling links are generated in PDF output, regardless of the args.rellinks and include.rellinks settings.

**Comment by shaneataylor** [comment]
This worked as recently as 2.3.1.

**Comment by shaneataylor** [comment]
This seems to happen before (or as) stage1.xml is generated; at that point (for example) no child links are included.

**Comment by jelovirt** [comment]
Related links are generated in preprocessing. Are the links in topic after preprocess?

**Comment by shaneataylor** [comment]
Turns out, this was caused by my setting `@chunk='to-content'` on the root `<bookmap>`.

While unexpected, I understand ("from a certain point of view", as Obi-Wan would say) why this happens. @infotexture, what are your thoughts about noting this behavior in the docs:

- it's an implementation choice of the DITA-OT
- it could be unexpected (I've been doing DITA for well over a decade and I didn't expect it)
- it should also affect composite HTML topics and any other output created by chunking, since it happens in common preprocessing

OTOH, it might be unlikely that users will encounter it for PDF, as they would need to both set the chunking attribute _and_ override the default args.rellinks / include.rellinks settings.
