### ISSUE TITLE
Further topicrefs in empty <preface> are ignored in PDF output

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2614]
See here for the initial report, it is a regression from DOT 1.8:

https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/41869

For a bookmap with the following preface structure:

        <preface>
            <topicref href="topics/task_preface.dita"  toc="no"/>
        </preface>

the PDF no longer contains the preface content.
It might be connected with: https://github.com/dita-ot/dita-ot/issues/1930

**Comment by chrizzbee** [comment]
Hi Jarno
Was there any progress on this bug in 2.4.x? Topicrefs under Preface and Notice in the Frontmatter are not available in the PDF outoput.
Thanks.

**Comment by robander** [comment]
I've got a fix for this as part of https://github.com/dita-ot/dita-ot/pull/2683 -- should restore topics that are missing after inclusion in empty `<preface>` or empty `<topicref>` inside of the front / back matter.

**Comment by jelovirt** [comment]
Fixed by #2683
