### ISSUE TITLE
pdf2 - Note text overlapping the footer

### ISSUE THREAD

**Issue by tommyr1962** [dita-ot/dita-ot#2615]
The following attribute is set on the note label, but part of the note text overlaps the footer.

<xsl:attribute name="keep-with-next.within-page">always</xsl:attribute>

![notetextbottomofpage](https://cloud.githubusercontent.com/assets/16328327/23331564/0779bd28-fb2e-11e6-9b25-b21f225f3cf3.png)

**Comment by jelovirt** [comment]
Which formatter? FOP?

Since the body of the note maybe has `keep-together`, this could be a formatter bug. If you remove the `keep-with-next` from the label, I assume page break occurs between the note label and the body?

**Comment by tommyr1962** [comment]
Hi Jarno. Correct; when I remove the attribute, the label stays and the text moves to the next page. 

I am using FOP

**Comment by jelovirt** [comment]
Seems to be either a bug in FOP, or then other keeps in the previous blocks force too much to be kept together on the page.

**Comment by tommyr1962** [comment]
I am hoping it's the latter. I've done a lot of coding and maybe something I did previously caused this. I will report back either way. Thanks, Jarno.

**Comment by tommyr1962** [comment]
I submitted a bug report to Apache via their new system, JIRA.

**Comment by tommyr1962** [comment]
Update. The Note is part of a <step> and the <cmd> for that step also had this attribute set: 

<xsl:attribute name="keep-with-next.within-page">always</xsl:attribute>

When I removed that, the entire Note moved to the next page. 

I am going to retain the FOP bug as I believe it still should not happen.
