### ISSUE TITLE
Page number in link text settings

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2617]
Let's say that I create a link to a topic. If I set the custom link text, the label "on page X" is no longer pre-pended to the link when generating the PDF output.
This decision was taken in #274.

Some people may want the "page X" to be generated even if there is custom link text inside the xref:

https://www.oxygenxml.com/forum/post41740.html#p41740

So maybe we should add some setting to control the "on page" behavior. For example there may be people who do not want it at all in the PDF as they intend the PDF for web consumption.

**Comment by jelovirt** [comment]
I agree, is should be configurable whether page numbers are generated, regardless of where the link text came from.
