### ISSUE TITLE
Change in behavior when referencing element which does not have a title

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2619]
[test-rel-links-no-title-in-target.zip](https://github.com/dita-ot/dita-ot/files/820962/test-rel-links-no-title-in-target.zip)

This is a problem which appeared somewhere between DITA OT 2.3.3 and 2.4.4.

Let's say that in a DITA topic I have a related link like:

       <link href="target-topic.dita#topic2/target"/>

The "target" element is a paragraph so the DITA OT cannot automatically obtain a title from it.
In DITA OT 1.8 the following error was reported:

        Unable to retrieve link text from target: 'target-topic.dita#topic2/target'. If the target is not accessible at build time, or does not have a title, provide the link text inside the reference. The location of this problem was at (File = D:\projects\eXml\test\dita\EXM-26705\topic-with-link.dita, Element = link:1;9:55)

and in the HTML document a link was generated looking something like this:

      <a class="link" href="target-topic.html#topic2__target">target-topic.html#topic2__target</a>

With DITA OT 2.4.4 there is no warning generated. The obtained HTML output for the link looks like this:

        <a class="link" href="target-topic.html#topic2__target"></a>

**Comment by raducoravu** [comment]
I think the DITA OT 1.8 behavior was better in this regard, at least it reported a warning and you did not end up with an empty link element.

**Comment by jelovirt** [comment]
Since some transtypes can generate link titles where there is no obvious link text, this code should probable be in transtype specific code, unless they use link generation from preprocessing.

**Comment by raducoravu** [comment]
This side effect may have been caused by the latest recent changes to "xsl/preprocess/topicpullImpl.xsl
" made by either @drmacro or @jelovirt.
Because the "topicpullImpl.xsl" is the one responsible of issuing that particular warning.

**Comment by jelovirt** [comment]
Yes, that's where the bug probably is.
