### ISSUE TITLE
The 'ol/@class' attribute is missing in the generated HTML when 'steps' contains a 'stepsection' element 

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2622]
One of our users is complaining that the `ol/@class` attribute is missing when `steps` element has a `stepsection` child element.

For the case when the `steps/stepsection` element is missing, the generated HTML looks like:
```
<ol class="ol steps">
```
while for the case when it is present, the `class` attribute is omitted.

You can simply reproduce this problem with the following DITA snippet:
```
<steps>
    <step>
        <cmd>Step1</cmd>
    </step>
    <stepsection>The next two steps are very important!</stepsection>
    <step>
        <cmd>Step2</cmd>
    </step>
</steps>
```
I've tested with **DITA-OT 2.4.4**, transtype **html5**.

**Comment by infotexture** [comment]
Looks like this has been resolved by the changes in 306a3f4 and amendments in c45268c.
