### ISSUE TITLE
Passthrough "resourceid" to XHTML and webhelp output

### ISSUE THREAD

**Issue by shudson310** [dita-ot/dita-ot#2630]
Some applications (especially in-app Help) rely on specific IDs for links into the content. The current OT does not pass through the resourceid information in the metadata for topics. Both the @appname and @appid would be useful to have in the metadata for rendered content.

**Comment by robander** [comment]
@shudson310 how would you expect the metadata to appear, and in what output formats? I'm guessing any HTML, but I'm not sure how `<resourceid appname="this" appid="that">` would translate to HTML.

**Comment by lief-erickson** [comment]
How about something like `<span id="_this_:_that_"/>` or `<div style="display:none;"><a id="_this_:_that_" href="link-target">_this___that_</a></div>`?

**Comment by shudson310** [comment]
Perhaps something compatible with https://help.paligo.net/en/context-sensitive-help.html ?
or in the header:
<meta name="resourceid" content="appname='this', appid='that'"/>
or in the content:
<article @data-appname="this" @data-appid="that">

**Comment by shudson310** [comment]
This functionality is still needed. please reopen.

**Comment by raducoravu** [comment]
This can probably be done with a plugin though, right?

**Comment by robander** [comment]
The suggestions above seem like valid ways to pass resource ID information into HTML output, but I don’t think they will be universal. Given that there are many ways to use `resourceid` it’s also likely that many existing docs would not want the IDs to appear like that. As Radu suggested, this function really belongs in a plugin, not in the core code.

**Comment by robander** [comment]
Marked closed - the design for this would not be universal, so we cannot insert the resource IDs in the output without causing problems for some other HTML users. This needs to be handled with a plugin, inserting the IDs in whatever manner works best for your context.
