### ISSUE TITLE
lockmeta attribute on topicmeta seems to be ignored or not handled

### ISSUE THREAD

**Issue by aziliat** [dita-ot/dita-ot#2633]
I have critdates set in a dita topic.
the ditamap also has critdates set

according to: http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part3-all-inclusive/archSpec/base/metadata-in-maps-and-topics.html#metadata-in-maps-and-topics 
the critdates in the map will be used for all topics.

I would like to use the critdates in the topics instead.

the spec says that there is an attribute "lockmeta" but no matter what value I put there, nothing seems to be happening.

is lockmeta supported in Dita-OT 2.4.3?

**Comment by robander** [comment]
I'm not certain about this one. The description of `@lockmeta` seems to differ between DITA 1.2 and 1.3, which shouldn't be the case. 

1.2 says it determines whether metadata in the topics is pulled into / replaces what is in the map (this is what I remembered): http://docs.oasis-open.org/dita/v1.2/os/spec/langref/topicmeta.html#topicmeta

1.3 says it determines whether metadata is pushed into topics: http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part1-base/langRef/base/topicmeta.html#topicmeta
