### ISSUE TITLE
[move-meta] file in output\temp not found // refs to ditamaps with relative paths unstable

### ISSUE THREAD

**Issue by AndreasBella** [dita-ot/dita-ot#2634]
Hi all,

we are using DITA to build documents with more than 1000 pages and about 8 levels of chapter depth.
Changes to these documents are summarised in additional smaller documents which points to the corresponding positions, which are to be changed, in the main documents using maprefs.
Since we changed the DITA-OT Version from 1.5.1 to 2.4.4 we encoutered the following problem.

In our case a reference might look like this:
<pre><code>
&lt;topichead navtitle="04_subSubChapter"&gt;
    &lt;mapref href="../../../../mainDocuments/mainDocument_1/01_chapter/04_subChapter/04_subWorkflows/08_subSubSubChapter/08_Description/_08_Description.ditamap" /&gt;
&lt;/topichead&gt;
</pre></code>

such a reference causes the following warning and error messages
<pre><code>
[DITA-OT]     [chunk] Processing file:/C:/DEV/Repo/testDoc/Output/temp/sideDocument_1.ditamap
[DITA-OT] [job-helper] Processing C:\DEV\Repo\testDoc\Output\temp\.job.xml to C:\DEV\Repo\testDoc\Output\temp\fullditatopic.list
[DITA-OT] [job-helper] Loading stylesheet C:\DEV\Repo\testDoc\Tooling\DITA-OT\xsl\job-helper.xsl
[DITA-OT] [job-helper] Processing C:\DEV\Repo\testDoc\Output\temp\.job.xml to C:\DEV\Repo\testDoc\Output\temp\fullditamap.list
[DITA-OT] [job-helper] Loading stylesheet C:\DEV\Repo\testDoc\Tooling\DITA-OT\xsl\job-helper.xsl
[DITA-OT] [job-helper] Processing C:\DEV\Repo\testDoc\Output\temp\.job.xml to C:\DEV\Repo\testDoc\Output\temp\fullditamapandtopic.list
[DITA-OT] [job-helper] Loading stylesheet C:\DEV\Repo\testDoc\Tooling\DITA-OT\xsl\job-helper.xsl`
[DITA-OT] [job-helper] Processing C:\DEV\Repo\testDoc\Output\temp\.job.xml to C:\DEV\Repo\testDoc\Output\temp\resourceonly.list
[DITA-OT] [job-helper] Loading stylesheet C:\DEV\Repo\testDoc\Tooling\DITA-OT\xsl\job-helper.xsl`
[DITA-OT] [job-helper] Processing C:\DEV\Repo\testDoc\Output\temp\.job.xml to C:\DEV\Repo\testDoc\Output\temp\copytosource.list
[DITA-OT] [job-helper] Loading stylesheet C:\DEV\Repo\testDoc\Tooling\DITA-OT\xsl\job-helper.xsl`
[DITA-OT] move-meta-entries:
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/sideDocument_1.ditamap
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/07_subDescription/_07_subDescription-main.dita
[DITA-OT] [move-meta] File C:\DEV\Repo\testDoc\Output\temp\08_subDescription\08.dita was not found.
[DITA-OT] [move-meta] File C:\DEV\Repo\testDoc\Output\temp\07_subDescription\07.dita was not found.
[DITA-OT] [move-meta] File C:\DEV\Repo\testDoc\Output\temp\08_subDescription\08.dita was not found.
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/02_subDescription/02.dita
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/mainDocuments/mainDocument_1/01_chapter/04_subChapter/04_subWorkflows/08_subSubSubChapter/08_Description/16_subDescription/16.dita
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/08_subDescription/_08_subDescription-main.dita
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/mainDocuments/mainDocument_1/01_chapter/03_subChapter/03_subWorkflows/06_subSubSubChapter/06_Description/12_subDescription/12.dita
[DITA-OT] [move-meta] Processing file:/C:/DEV/Repo/testDoc/Output/temp/mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/01_subDescription/_01_subDescription-main.dita
</pre></code>
...
<pre><code>
  [DITA-OT] [move-meta] Loading stylesheet C:\DEV\Repo\testDoc\Tooling\DITA-OT\xsl\preprocess\mappull.xsl
  [DITA-OT] [move-meta] File C:\DEV\Repo\testDoc\Output\temp\07_subDescription\07.dita was not found.
  [DITA-OT] [move-meta] Recoverable error on line 62 of mappullImpl.xsl:
  [DITA-OT] [move-meta]   FODC0002: java.io.FileNotFoundException:
  [DITA-OT] [move-meta]   C:\DEV\Repo\testDoc\Output\temp\07_subDescription\07.dita (Das System kann den
  [DITA-OT] [move-meta]   angegebenen Pfad nicht finden)
  [DITA-OT] [move-meta] file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/07_subDescription/_07_subDescription.ditamap:5:56: [DOTX023W][WARN]: Unable to retrieve navtitle from target: ' 07_subDescription/07.dita '. 
  [DITA-OT] [move-meta] file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/07_subDescription/_07_subDescription.ditamap:5:56: [DOTX027W][WARN]: Unable to retrieve linktext from target: ' 07_subDescription/07.dita '. 
  [DITA-OT] [move-meta] Recoverable error on line 62 of mappullImpl.xsl:
  [DITA-OT] [move-meta]   FODC0002: java.io.FileNotFoundException:
  [DITA-OT] [move-meta]   C:\DEV\Repo\testDoc\Output\temp\08_subDescription\08.dita (Das System kann den
  [DITA-OT] [move-meta]   angegebenen Pfad nicht finden)
  [DITA-OT] [move-meta] file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/08_subDescription/_08_subDescription.ditamap:5:56: [DOTX023W][WARN]: Unable to retrieve navtitle from target: ' 08_subDescription/08.dita '. 
  [DITA-OT] [move-meta] file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/08_subDescription/_08_subDescription.ditamap:5:56: [DOTX027W][WARN]: Unable to retrieve linktext from target: ' 08_subDescription/08.dita '. 
  [DITA-OT] maplink-check:
  [DITA-OT] maplink:
</pre></code>
...
<pre><code>
  [DITA-OT] [clean-map] Processing C:\DEV\Repo\testDoc\Output\temp\mainDocuments\mainDocument_1\01_chapter\04_subChapter\04_subWorkflows\08_subSubSubChapter\08_Description\_08_Description.ditamap
  [DITA-OT] [clean-map] Processing C:\DEV\Repo\testDoc\Output\temp\mainDocuments\mainDocument_1\01_chapter\01_subChapter\01_subWorkflows\01_subSubSubChapter\01_Description\_01_Description.ditamap
  [DITA-OT] [clean-map] Processing C:\DEV\Repo\testDoc\Output\temp\mainDocuments\mainDocument_1\01_chapter\03_subChapter\03_subWorkflows\06_subSubSubChapter\06_Description\11_subDescription\_11_subDescription.ditamap
  [DITA-OT] [topic-merge] [DOTX008E][ERROR] File 'file:/C:/DEV/Repo/testDoc/Output/temp/07_subDescription/07.dita' does not exist or cannot be loaded.
  [DITA-OT] [topic-merge] [DOTX008E][ERROR] File 'file:/C:/DEV/Repo/testDoc/Output/temp/08_subDescription/08.dita' does not exist or cannot be loaded.
  [DITA-OT] [clean-map] Processing C:\DEV\Repo\testDoc\Output\temp\mainDocuments\mainDocument_1\01_chapter\03_subChapter\03_subWorkflows\06_subSubSubChapter\06_Description\_06_Description.ditamap
  [DITA-OT] [clean-map] Processing C:\DEV\Repo\testDoc\Output\temp\mainDocuments\mainDocument_1\01_chapter\01_subChapter\01_subWorkflows\01_subSubSubChapter\01_Description\01_subDescription\_01_subDescription.ditamap
</pre></code>

These errors occur depending on the deepness of the relative path
It seems to be related to the fact, that the references are outside the ditamap folder
[https://www.oxygenxml.com/doc/versions/18.1/ug-editor/topics/dita-ot-external-refs.html](url)

A testcase reproducing the mentioned errors and resembling the hierarchy of our documents is attached.
Is there a workaround to make references with this deepness possible,
or is it planned to make it working?

Greetings
Andreas
[testCase.zip](https://github.com/dita-ot/dita-ot/files/862039/testCase.zip)

**Comment by xephon2** [comment]
I did not investigated this. Could you please set `clean.temp=no` and check, if all files are copied correctly to the temp directory? Have you tried changing the parameters `outer.control` and/or `generate.copy.outer`, see [Common parameters](http://www.dita-ot.org/2.4/parameters/parameters-base.html)? Does this happen only for topics, that are prefixed with `_`?

**Comment by AndreasBella** [comment]
Thanks for the fast answer.
The files are copied correctly into the temp folder, but looking into the copied ditamap of the sideDocument which includes the references, we have seen something strange.

The relative paths inside the copied ditamaps are partially changed.
As a result the .dita files of the mainDocument cannot be found
Here is an example:
The first block is correct, while the second one has changed paths
<pre><code>
&lt;topichead class="+ map/topicref mapgroup-d/topichead " navtitle="01_subChapter" xtrf="file:/C:/DEV/Repo/testDoc/Content/sideDocuments/sideDocument_1/01_chapter/01_subChapter/_subChapter-side.ditamap" xtrc="topichead:2;7:39"&gt;
    &lt;topichead class="+ map/topicref mapgroup-d/topichead " navtitle="01_subSubChapter" xtrf="file:/C:/DEV/Repo/testDoc/Content/sideDocuments/sideDocument_1/01_chapter/01_subChapter/_subChapter-side.ditamap" xtrc="topichead:3;8:43"&gt;
        &lt;topicref href="../../../../mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/01_subDescription/_01_subDescription-main.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/_01_Description.ditamap" xtrc="topicref:1;5:93"&gt;
            &lt;topicref href="../../../../mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/01_subDescription/01.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/01_subDescription/_01_subDescription.ditamap" xtrc="topicref:1;5:56"/&gt;
        &lt;/topicref&gt;
        &lt;topicref href="../../../../mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/02_subDescription/_02_subDescription-main.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/_01_Description.ditamap" xtrc="topicref:2;8:93"&gt;
            &lt;topicref href="../../../../mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/02_subDescription/02.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/01_subChapter/01_subWorkflows/01_subSubSubChapter/01_Description/02_subDescription/_02_subDescription.ditamap" xtrc="topicref:1;5:56"/&gt;
        &lt;/topicref&gt;
    &lt;/topichead&gt;
&lt;/topichead&gt;
		
&lt;topichead class="+ map/topicref mapgroup-d/topichead " navtitle="02_subChapter" xtrf="file:/C:/DEV/Repo/testDoc/Content/sideDocuments/sideDocument_1/01_chapter/01_subChapter/_subChapter-side.ditamap" xtrc="topichead:4;13:39"&gt;
    &lt;topichead class="+ map/topicref mapgroup-d/topichead " navtitle="02_subSubChapter" xtrf="file:/C:/DEV/Repo/testDoc/Content/sideDocuments/sideDocument_1/01_chapter/01_subChapter/_subChapter-side.ditamap" xtrc="topichead:5;14:43"&gt;
        &lt;topicref href="../../../../mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/07_subDescription/_07_subDescription-main.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/_04_Description.ditamap" xtrc="topicref:1;5:93"&gt;
            &lt;topicref href="07_subDescription/07.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/07_subDescription/_07_subDescription.ditamap" xtrc="topicref:1;5:56"/&gt;
        &lt;/topicref&gt;
        &lt;topicref href="../../../../mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/08_subDescription/_08_subDescription-main.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/_04_Description.ditamap" xtrc="topicref:2;8:93"&gt;
            &lt;topicref href="08_subDescription/08.dita" class="- map/topicref " type="topic" format="dita" xtrf="file:/C:/DEV/Repo/testDoc/Content/mainDocuments/mainDocument_1/01_chapter/02_subChapter/02_subWorkflows/04_subSubSubChapter/04_Description/08_subDescription/_08_subDescription.ditamap" xtrc="topicref:1;5:56"/&gt;
        &lt;/topicref&gt;
    &lt;/topichead&gt;
&lt;/topichead&gt;
</pre></code>

**Comment by AndreasBella** [comment]
> Have you tried changing the parameters outer.control and/or generate.copy.outer
Changing the suggested parameters does not have an effect.

> Does this happen only for topics, that are prefixed with _?
No. It happends also to files, which do not have that prefix.

**Comment by xephon2** [comment]
Do you use chunking? Could you please test this again with [DITA-OT 2.3.3](https://github.com/dita-ot/dita-ot/releases/tag/2.3.3)?

**Comment by AndreasBella** [comment]
We are not using chunking.
Since are many ways to use it, which kind of chunking do you suggest?

**Comment by xephon2** [comment]
Well, if you don't need chunking, don't use it at all. 😃

**Comment by AndreasBella** [comment]
Ah ok.
I thought we should try to use it.
Other good ideas? ;)

**Comment by xephon2** [comment]
Good ideas? Unfortunately not. Maybe you could try it with the DITA-OT 2.3.3, this could make it easier to find the bug.

**Comment by AndreasBella** [comment]
Sure.
May i ask why excatly 2.3.3?

**Comment by xephon2** [comment]
Because `<mypersonalopinion>`DITA-OT 2.4.x introduced new bugs that _may_ be related to your problem.`</mypersonalopinion>`

**Comment by AndreasBella** [comment]
Alright.
I will use version 2.3.3. to build the test case and will give feedback the next days.
Thanks so far.

**Comment by xephon2** [comment]
You're welcome. If that doesn't help and is not extremely urgent, we could debug this together with a 🍺 in Bonn. 😄

**Comment by AndreasBella** [comment]
To be able to build the document, we changed slightly the folder hierarchy, removing a level of depth.
Just a matter of time how long this temporary solution works.
Your suggestion sounds interesting  :wink:

**Comment by AndreasBella** [comment]
Alright, feedback comes faster than expected :wink:.
I tried to build the documents with DITA-OT version 2.3.3 and 2.2.5.
It did not work with both.
Starting from 2.1, DITA-OT does not support DITA 1.3 anymore.
As mentioned in the beginning, we did jump from DITA-OT 1.5.1 to 2.4.4.
Not using DITA 1.3 would not be an option for us.

Greetings
Andreas

P.S. the :beer: in Bonn is still valid :wink:

**Comment by xephon2** [comment]
>  Starting from 2.1, DITA-OT does not support DITA 1.3 anymore.

I don't understand what you mean and I think this is off-topic. Please write me an e-mail or write to the DITA users mailing list to explain what you mean. 😃

**Comment by AndreasBella** [comment]
We encountered this bug again and we like to share some infos which might help.

It seems to be, that this bug does not only depend on the deepness of the relative path of the referenced ditamap, but also on its content.

This bug occoured now by referencing a .ditamap with low hierarchy including about 10 other ditamaps which again included one ditamap.

Greetings
Andreas
