### ISSUE TITLE
map level chunking not producing the html output using 'org.dita4publishers.html2' plugin

### ISSUE THREAD

**Issue by gvinodkumar515** [dita-ot/dita-ot#2639]
I am using chunk="content" in topichead tag like below, to generate merged topic html file using DITA OT Plugin org.dita4publishers.html2 plugin then **its generating Chunk363995000.html output**

My ditamap file

    <map>
    <title>Directory</title>
    <topichead chunk="to-content">
    <topicmeta class="- map/topicmeta "><navtitle>Details</navtitle></topicmeta>
    <topicref class="- map/topicref " href="dita1.xml"/>
    	<topicref class="- map/topicref " href="dita2.xml"/>
    	<topicref class="- map/topicref " href="dita3.xml"/></topichead>
    </map>

If I have used chunk="to-content" in root element 'map' without 'topichead' as mentioned below its **not generating merged topic html** file using DITA OT Plugin org.dita4publishers.html2 plugin

    <map chunk="to-content">
    <title>Directory</title>
    <topicref class="- map/topicref " href="dita1.xml"/>
    	<topicref class="- map/topicref " href="dita2.xml"/>
    	<topicref class="- map/topicref " href="dita3.xml"/>
    </map>

Please give me any suggestions to overcome 'map' level chunking in html2 plugin

Thanks in Advance.

**Comment by xephon2** [comment]
The `org.dita4publishers.html2` plugin is not compatible with `DITA-OT 2.x`. It has been developed to work with `DITA-OT 1.8.x`, but the `DITA-OT 1.8.x` is not developed/fixed anymore. Please switch to the HTML5 plugin and please close this issue. If you are still using the `DITA-OT 1.8.5`, you should ask the question again in the issue tracker of the plugin itself, which is located here: [org.dita4publishers.html2](https://github.com/dita4publishers/org.dita4publishers.html2)
