### ISSUE TITLE
Extra right border generated for last cell on table header

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2640]
Let's say I publish to PDF a DITA topic containing a table like this:

        <table frame="none" rowsep="1" colsep="1" id="table_afc_d1n_hz">
            <title>Straddling</title>
            <tgroup cols="10">
                <colspec colname="c1" colnum="1" colwidth="1.0*"/>
                <colspec colname="c2" colnum="2" colwidth="1.0*"/>
                <colspec colname="c3" colnum="3" colwidth="1.0*"/>
                <colspec colname="c4" colnum="4" colwidth="1.0*"/>
                <colspec colname="c5" colnum="5" colwidth="1.0*"/>
                <colspec colname="c6" colnum="6" colwidth="1.0*"/>
                <colspec colname="c7" colnum="7" colwidth="1.0*"/>
                <colspec colname="c8" colnum="8" colwidth="1.0*"/>
                <colspec colname="c9" colnum="9" colwidth="1.0*"/>
                <colspec colname="c10" colnum="10" colwidth="1.0*"/>
                <thead>
                    <row>
                        <entry/>
                        <entry>Col 2</entry>
                        <entry>Col3</entry>
                        <entry namest="c4" nameend="c6">Col 4, 5, 6</entry>
                        <entry>Col 7</entry>
                        <entry>Col8</entry>
                        <entry>Col 9</entry>
                        <entry>Col 10</entry>
                    </row>
                </thead>
                <tbody>
                    <row>
                        <entry>Row 1</entry>
                        <entry>A</entry>
                        <entry>A</entry>
                        <entry>A</entry>
                        <entry>B</entry>
                        <entry>C</entry>
                        <entry>A</entry>
                        <entry>A</entry>
                        <entry>A</entry>
                        <entry>A</entry>
                    </row>
                </tbody>
            </tgroup>
        </table>

In the published PDF output there is an extra right border drawn for the "Col 10" cell. 
In the XSLT stylesheet "plugins\org.dita.pdf2\xsl\fo\tables.xsl" the "generateTableEntryBorder" template has an xsl:if looking like this:

        <xsl:if test="number($colsep) = 1 and not(following-sibling::*[contains(@class, ' topic/entry ')]) and ((count(preceding-sibling::*) + 1) &lt; ancestor::*[contains(@class, ' topic/tgroup ')][1]/@cols)">
            <xsl:call-template name="processAttrSetReflection">
                <xsl:with-param name="attrSet" select="'__tableframe__right'"/>
                <xsl:with-param name="path" select="$tableAttrs"/>
            </xsl:call-template>
        </xsl:if>

which seems to not take into account the possibility that previous table cells may have spanned on multiple columns.

**Comment by raducoravu** [comment]
I do not quite know why that xsl:if is there, maybe it can be fully removed. Somehow if the row has fewer cells than the number of cols advertised on the parent, the decision is taken that for the last cell the right border should be drawn.

**Comment by robander** [comment]
I'm also not sure why the `xsl:if` is there -- but an alternate solution without removing it might be to update the code to use the `dita-ot:` namespaced table position attributes. That provides a much simpler way to detect if we're in the last cell, just check if the number matches the total number of expected cells.
