### ISSUE TITLE
Integrator should fail more often

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2641]
In my plugin.xml has something like this inside:

	<feature extension="dita.conductor.target.relative" file="integrator.xml"/>

but there is no "integrator.xml" in the plugin folder, the integrator complains:

            [integrate] D:\DITA-OT2.x\plugins\my.plugin\integrator.xml (The system cannot find the file specified)

but it is still successful.

**Comment by jelovirt** [comment]
Some time ago the integrator had two modes, lax and strict. Now there's only strict and IMO the integration could be more strict in failing when e.g files are missing.

**Comment by raducoravu** [comment]
👍

**Comment by raducoravu** [comment]
Problem still persists in DITA OT 3.2.1.

**Comment by jelovirt** [comment]
[`getResult` method in `InsertAction`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/platform/InsertAction.java#L80) catches all exceptions. Removing this catch or changing it to throw a `RuntimeException` will make the integration fail.
