### ISSUE TITLE
In case of chunking, new topic file name should be created using the title.

### ISSUE THREAD

**Issue by riteshksriv** [dita-ot/dita-ot#2644]
When DITA-OT chunks dita file having multiple topics, it generates the names of the chunk using the id attribute of the topic element. This happens in case of chunking "by-topic". It should rather generate the filenames on the basis of the title of that dita topic.

**Comment by jelovirt** [comment]
See DITA 1.3 [Using the `@chunk` attribute](http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part3-all-inclusive/archSpec/base/chunkingdetails.html#chunkingdetails__chunk-resource-naming-steps). The spec uses _SHOULD_ for the naming scheme, so an implementation is allowed to use an alternative scheme, but the default behavior of DITA-OT is to follow the DITA 1.3 specification.
