### ISSUE TITLE
Map-based shortdesc implemented only for "first-use"

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2645]
It's possible to specify a shortdesc in the map to be used for link descriptions, but this works only for the first instance of the topic.

Example:
```xml
<topicref href="t_i_create_course_parent.xml" collection-type="family">
  <topicmeta>
    <shortdesc>MAP BASED SHORTDESC</shortdesc>
  </topicmeta>
```

The impact of this behavior is that the same shortdesc (and linktext) is used for every reference to the topic, even when it's desired to override based on context — which is the main point of being able to specify map-based overrides to the shortdesc and linktext.

Tested in DITA-OT 2.3.1.

**Comment by shaneataylor** [comment]
My error — and requesting this be retitled — this problem is not associated with submaps specifically but has only to do with "first-use". In the case I tested, the topic referenced in the submap had already been referenced in the root map.

The problem, then, is the same for keyrefs and hrefs — it's not possible to override the short description for a particular link instance other than the first. Which would seem to subvert the purpose of being able to override the link description at all.

**Comment by shaneataylor** [comment]
There is a workaround, and that is to specify `@scope="peer"` on the topicref for which you want to override the short description. However:

- this feels like tag abuse (peer scope is not the intent, but a workaround)
- it limits reuse of the map to contexts for which the target topic will already have been built based on a separate topicref; if the topic is not otherwise referenced, it won't be built and you'll have a broken link.

**Comment by jelovirt** [comment]
@shaneataylor you should be able to edit the title of the issue and the original description.

**Comment by robander** [comment]
I think this is another instance of https://github.com/dita-ot/dita-ot/issues/1676 which reported the same issue but for `<navtitle>`. (And @shaneataylor no, I would not have expected you to know about that one or find it in a search.) 

At least, it sounds like the same thing if I'm understanding properly -- you have multiple instances of `t_i_create_course_parent.xml` and want to specify a context-specific short description in the map for at least one of those, which does not match the short description elsewhere.
