### ISSUE TITLE
Trim DOTX010E

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2646]
The `DOTX010E` conref value should be trimmed.

```
[conref] [DOTX010E][ERROR]: Unable to find target for conref=" ../../path/to/my/file.dita#myElementID ".
```

**Comment by jelovirt** [comment]
Exactly which whitespace do you mean?

**Comment by xephon2** [comment]
**before**
conref=" ../../path/to/my/file.dita#myElementID "

**after**
conref="../../path/to/my/file.dita#myElementID"

Sure, that's nitpicking, but can be fixed easily. Spaces are not allowed in `conref` attributes, because `conref` has to be a valid URI, at least oXygen parser claims that.
