### ISSUE TITLE
Key Scopes and Multiple Keyref Levels Produces Incorrect Result

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#2647]
[keys-and-keyrefs.zip](https://github.com/dita-ot/dita-ot/files/894431/keys-and-keyrefs.zip)

In the attached zip there is a map, map-01.ditamap, that has two named scopes, "en", and "jp". Within each scope are navigation topicrefs that defined keys and use keyref to point to resource-only topics defined on keyref elements within the same scope.

Within topic en/topic-0005.dita there is a key-based xref to key "remove-whizbang", which should resolved to the topicref with the @keys value "remove-whizbang", which in turn refers to the resource-only topic bound to key "topic-0003".

None of the topics except topic-0003 produce HTML files when using the XHTML transform and the index.html file only reflects the reference to the peer-root map map-02.

If the topic for key "install-framitz" was generated then the xref should resolve to the corresponding key as defined within the key scope.

**Comment by lief-erickson** [comment]
I tested this with OT 3.3.1 (XHTML and HTML5 transforms) and here are my results in the \out directory.

* Both transforms produce output files for topic-0001 through topic-0005. 
* An index/TOC is produced. There are functioning links topics 0001-0005 in both the 'en' and 'jp' keyscopes but a non-functioning link to map-02.ditamap (even if publishing map-02 first).
* In topic-0005 there is a functioning link to topic-0003.
* Going from topic-0003 to its parent topic topic-0001 works fine.
* In topic-0001 there is a missing link to the key `map-02.chapter-01` (topic-0006).
* The topic-0006 file is not produced unless you specifically publish map-02. Even then there is still not a functioning link between topic-0001 and topic-0006.

I can attach my output results if it's helpful.
