### ISSUE TITLE
RTF Plug-In

### ISSUE THREAD

**Issue by AprilTaylorSE** [dita-ot/dita-ot#2652]
Hi there,
I have been sent here by the Astoria-on-Demand Support Team.
My team and I have been trying to publish some ditamaps to RTF and we aren't having any luck. Sometimes the document freezes when we try to open it, and then if we do open it the page count just keeps spinning (14,000 pages and counting). We also have issues with the images and tables running off the page.
We have tried using the DITA-OT and DITA-0T 1.8.4. The output is an invalid RTF file, and when you try to convert it using MS Word you get an error that says "A table in this document has been corrupted."
The Astoria support people say they tried a more recent version of the Open Toolkit (2.3.2) but it fails in a similar way. The team said they tried the most recent one (2.4.4) and it still has the same issue.
Would you be able to help us with this?
Thanks,
April

**Comment by jelovirt** [comment]
The development for RTF has pretty much stopped years ago. There's #1589 pull-request that improves the RTF output, but I think @nakohdo hasn't made that a separate plugin.

If you really don't need RTF and could live with Word's DOCX format, then there's a plugin that converts DITA directory to DOCX.

**Comment by nakohdo** [comment]
Hi April, Jarno is wright. I haven't  made the improvements to the RTF output a separate plugin yet though it's still in my list. However, even with the improvements the RTF output if far from perfect, especially when it comes to more complex layout features, for example tables. So you are probably far better of with Jarno's DOCX plugin. In fact, that's what we plan to test (and use) for generating Word output from DITA.

Best regards,
Frank

**Comment by AprilTaylorSE** [comment]
Hi Jarno and Frank!
Thanks so much for the reply, sorry for my delayed reply! How do we enable the DOCx plugin?
Thanks!
April

**Comment by jelovirt** [comment]
@AprilTaylorSE install from https://github.com/jelovirt/com.elovirta.ooxml
