### ISSUE TITLE
Problem with determining format="image" for keydefs in the .job.xml

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2653]
Let's say that in the topic I have a keyref to an image:

     <image keyref="welcome" scalefit="yes"/>

and in the DITA Map I have this:

     <keydef keys="welcome" href="i_welcome.png" format="png"/>

and I publish to XHTML for example. Looking in the .job.xml I see this:

        <file src="file:/C:/Users/radu_coravu/Desktop/ann/test_user_guide/i_welcome.png"
            uri="i_welcome.png" path="i_welcome.png"
            result="file:/C:/Users/radu_coravu/Desktop/ann/test_user_guide/i_welcome.png"
            format="html" resource-only="true"/>

So the file appears with format="html" meaning from what I understand that copy operations with file sets like this:

            <dita-fileset format="image"/>

will not match it.
It seems that one of the jobs of ImageMetadataModule is to set the proper format for the image resource. But the ImageMetadataModule seems to be called way after the .job.xml is serialized so this does not seem to help at all....

**Comment by robander** [comment]
I found that keys for images (and other images referenced from the map) only worked if `format="image"` was used, rather than something like `gif` or `png`. I didn't think much of it at the time and considered that to be the design...

**Comment by jelovirt** [comment]
@raducoravu How is the output broken after image metadata module has been ran?

Originally the `@format` in job configuration corresponded with whatever was set on the DITA topics or maps. Over time this is no longer that case and the `@format` should be seen as something that's internal to job configuration. The value `html` is something that's used to categorize non-DITA content, and later on in image metadata module we categorize images as `image`. It would be convenient to use `image` from the start of the preprocess, but e.g. for keys we don't know what the target format is until we actually resolve the keys.

Maybe the `@format` attribute in job configuration should be renamed to something else to make the difference explicit.

**Comment by jelovirt** [comment]
Fixed in ba868f74bf311df79944f0f5574177c901d8c083
