### ISSUE TITLE
@chunk destination folder

### ISSUE THREAD

**Issue by Nikulinnn** [dita-ot/dita-ot#2655]
I have a project, which consists of the following files:
- ` my-project.ditamap`, which is stored in the `/my-project` folder.
- `first-topic.dita`, which is included as a topicref in `my-project.ditamap` and is stored in the nested `concepts` folder (`/my-project/concepts`).

If I set the chunk attribute for the `first-topic.dita` topicref to "by-topic", the output chunked files are generated to the `/output/my-project` folder and not to `/output/my-project/concepts`.

Does this match the expected behavior or is it an error and the files should be generated to `/output/my-project/concepts`?

**Comment by jelovirt** [comment]
This is most likely a "feature, not a but". That is, the exploded topics should be written to `/output/my-project/concepts` because that's what most users would expect, but DITA-OT is writing it to the root.
