### ISSUE TITLE
Extra temp folder created in output folder when a key points to an image, PDF transformation, OT 2.4.5

### ISSUE THREAD

**Issue by DaveGibbons** [dita-ot/dita-ot#2658]
During some PDF transformations with OT 2.4.5 (and several previous versions), temporary folders containing images are created in the output folder as well as the temp folder.

This appears to happen when a key refers to an image.

In my testing, I found that the PDF builds fine without these extra folders if I change plugins\org.dita.base\build_preprocess.xml, Line 472, so that "todir" points to the temp directory ${dita.temp.dir} instead of the output directory ${output.dir}. 

[EDIT: not recommended for production; see comment below]

```
<target name="copy-html" depends="" unless="preprocess.copy-html.skip" description="Copy html files">
    <copy todir="${dita.temp.dir}" failonerror="false">  <!--  Line 472   -->
      <dita-fileset format="html"/>
    </copy>
</target>
```

Impact of the current behavior appears to be minimal, but I wanted to bring it up in case it points to any issues that might need to be addressed.

**Comment by Schelmenzunft** [comment]
I can confirm that, but if you generate not only PDFs but, in my case, oXygen Webhelp, the images are also not copied over and are missing in the final output ... Seems not to be a general solution for this problem.

**Comment by robander** [comment]
Wondering how this is related to https://github.com/dita-ot/dita-ot/issues/2680 (if at all) ...

Also wondering how this workaround is hurt (or improved) by this pull request: #2682. That at least allows you to set up an init target to modify where `copy-image` and `copy-html` place those files, without having to modify `copy-html` directly.
