### ISSUE TITLE
References to topics in ditavalref context lead to broken links in XHTML TOC

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2659]
I'm attaching a sample project:
[branchFilteringJobProblem.zip](https://github.com/dita-ot/dita-ot/files/922135/branchFilteringJobProblem.zip)

Publish to XHTML and then try to open from the TOC the first link. It points to a non-existing HTML document.

It seems that the BranchFilterModule no longer updates the Job object with the new "-1", '-2'... names it gives to topics in ditavalref contexts. Leading to .job.xml not containing <file> mappings for those automatically generated topics.

It's a recent change, before this commit @jelovirt made: https://github.com/dita-ot/dita-ot/commit/07331c3193ebd0cf846ff6a35185075599101914

it had a "generateCopies" method which seemed to update the Job object with the new topics....

**Comment by raducoravu** [comment]
In the method:

org.dita.dost.module.BranchFilterModule.processAttributes(Element, Branch)

the Job gets updated only if the "resourcePrefix" and "resourceSuffix" are specified in the ditavalref.

**Comment by raducoravu** [comment]
The method BranchFilterModule.rewriteDuplicates should probably also update the job for each new generated suffixed attribute value.
I tried a fix like this which seems to work:

                        //EXM-39266 Also update the job with the new destination information
                        final URI dstUri = map.resolve(gen);
                        if(dstUri != null){
                        	final FileInfo hrefFileInfo = job.getFileInfo(currentFile.resolve(attr.getValue()));
                        	if(hrefFileInfo != null){
                        		try {
                        			URI newResult = new URI(addSuffix(hrefFileInfo.result.toString(), suffix));
                        			final FileInfo.Builder dstBuilder = new FileInfo.Builder(hrefFileInfo).uri(dstUri).result(newResult);
                        			if (dstBuilder.build().format == null) {
                        				dstBuilder.format(ATTR_FORMAT_VALUE_DITA);
                        			}
                        			final FileInfo dstFileInfo = dstBuilder.build();
                        			job.add(dstFileInfo);
                        		} catch (URISyntaxException e1) {
                        			//Ignore
                        		}
                        	}
                        }

**Comment by jelovirt** [comment]
If I understood that patch correctly, it seems that part of the code is not covered by any unit test.

**Comment by raducoravu** [comment]
The test project is quite simple really, as long as you do not set suffix or prefix values in the ditavalref the processing which does DITA to HTML will never go through the DITA topics which you have automatically created with -1, -2, etc suffixes in this step as the .job.xml contains no reference to them.

**Comment by jelovirt** [comment]
I'll integrate your test case to the unit test first.

**Comment by raducoravu** [comment]
👍 I'm glad I got close with my fix suggestion.

**Comment by raducoravu** [comment]
Just to double check, the fix for this is not included in 2.4.6, right?

**Comment by jelovirt** [comment]
Yes, AFAICT it will be in 2.5
