### ISSUE TITLE
@chunk and reltable

### ISSUE THREAD

**Issue by mironovalexey** [dita-ot/dita-ot#2660]
Since the [chunk task](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml#L34) is executed after the `mapref`, the exploded topics (`<topciref chunk="by-topic" href="..."/>`) are excluded from `reltable` processing. So none of them can have related links section generated from ditamap. And they cannot be included into other topics related links.

Is this the expected behavior?

**Comment by jelovirt** [comment]
Could you add a very simple test case to reproduce this?

**Comment by mironovalexey** [comment]
Sure. Sorry for not having done this before.

[test.tar.gz](https://github.com/dita-ot/dita-ot/files/950417/test.tar.gz)
