### ISSUE TITLE
scalefit does not work correctly with pdf2

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2663]
If the `@scalefit` attribute is set, the image breaks to the next page and the title is overlapped.

`<image href="screenshot.png" scalefit="yes"/>` | `<image href="screenshot.png"/>`
------------ | -------------
![scalefit1](https://cloud.githubusercontent.com/assets/3266567/25177713/365423fa-2503-11e7-8c68-6ffca403f71c.png) | ![scalefit2](https://cloud.githubusercontent.com/assets/3266567/25177712/363d9d24-2503-11e7-890a-4255373b2728.png)

Formatter: Apache FOP
Test Files: [scalefit.zip](https://github.com/dita-ot/dita-ot/files/933786/scalefit.zip)
DITA-OT: `2.4.6`

**Comment by xephon2** [comment]
To fix this, the following template in **toc.xsl** need to be modified:

```xml
<xsl:template name="createToc">
  <xsl:if test="$generate-toc">
    <xsl:variable name="toc">
        <xsl:choose>
            <xsl:when test="$map//*[contains(@class,' bookmap/toc ')][@href]"/>
            <xsl:when test="$map//*[contains(@class,' bookmap/toc ')]">
                <xsl:apply-templates select="/" mode="toc"/>
            </xsl:when>
            <xsl:when test="/*[contains(@class,' map/map ')][not(contains(@class,' bookmap/bookmap '))]">
                <xsl:apply-templates select="/" mode="toc"/>
                <xsl:call-template name="toc.index"/>
            </xsl:when>
        </xsl:choose>
    </xsl:variable>
    <xsl:if test="count($toc/*) > 0">
        <fo:page-sequence master-reference="toc-sequence" xsl:use-attribute-sets="page-sequence.toc">
            <xsl:call-template name="insertTocStaticContents"/>
            <fo:flow flow-name="xsl-region-body">
                <xsl:call-template name="createTocHeader"/>
                <fo:block>
                    <fo:marker marker-class-name="current-header">
                      <xsl:call-template name="getVariable">
                        <xsl:with-param name="id" select="'Table of Contents'"/>
                      </xsl:call-template>
                    </fo:marker>
                    <xsl:copy-of select="$toc"/>
                </fo:block>
            </fo:flow>
        </fo:page-sequence>
    </xsl:if>
  </xsl:if>
</xsl:template>
```

The line

```xml
<fo:page-sequence master-reference="toc-sequence" xsl:use-attribute-sets="page-sequence.toc">
```

has to be changed to:

```xml
<fo:page-sequence master-reference="toc-sequence" xsl:use-attribute-sets="page-sequence.toc" force-page-count="no-force">
```

I'm unsure whether this has side effects. But at least, it removes the blank page.

**Comment by jelovirt** [comment]
@xephon2 how does modifying the TOC page count enforcement relate to `@scalefit` attribute?

**Comment by xephon2** [comment]
Oops, wrong issue

**Comment by xephon2** [comment]
The [post of Chris Brand on dita-users](https://groups.yahoo.com/neo/groups/dita-users/conversations/topics/42535;_ylc=X3oDMTJzaGVoMG1uBF9TAzk3MzU5NzE1BGdycElkAzEyNzQ0MjA5BGdycHNwSWQDMTcwNjAzMDM5MARtc2dJZAM0MjUzNQRzZWMDZG1zZwRzbGsDdm1zZwRzdGltZQMxNTAyMjQ0OTIz) might help:

>I managed to solve the issue by commenting out <xsl:attribute name="height"> and <xsl:attribute name="content-height"> in the placeImage template within topic.xsl. Now it seems that only the width is honored and the image is still scaled proportionally. No more computed space below the image. Not sure if this was the correct approach, but it does work.

**Comment by xephon2** [comment]
This is related to #2845. If a new attribute set would be implemented as suggested in this issue, the `scalefit` processing could be fixed by defining an attribute set like this for the image (not its wrapping `<fo:block>`):

```xml
<xsl:attribute-set name="blockImage">
    <xsl:attribute name="content-width">scale-to-fit</xsl:attribute>
    <xsl:attribute name="content-height">100%</xsl:attribute>
    <xsl:attribute name="width">100%</xsl:attribute>
    <xsl:attribute name="scaling">uniform</xsl:attribute>
</xsl:attribute-set>
```

**Comment by raducoravu** [comment]
We could consider there are three types of "block" images, images which have width and height smaller than the page, images which have the width larger than the page width and images which have the height larger than the page height. 
Does your proposed fix work in both 3 cases?

**Comment by xephon2** [comment]
yes

**Comment by rjcbop** [comment]
We're having an issue with using @scalefit in conjunction with automatically applying a border to an image. We're applying the border by specifying the relevant attributes on the <fo:external-graphic> element, and we're using the standard code for @scalefit from the placeImage template in topic.xsl. When the image is too wide, the right-hand border scales with the image but the bottom border doesn't, resulting in a white space between the bottom of the rescaled image and the bottom border. Likewise, when the image is too long, the bottom border scales with the image by the right-hand border doesn't, resulting in white space between the right edge of the image and the right-hand border.

I tried the solution specified above for @scalefit in general but that doesn't fix this issue. Has anyone else encountered this?

**Comment by tokup** [comment]
Hint: I fixed the "white space" issue by changing the the lines (in topic.xsl) below `<xsl:if test="@scalefit = 'yes' and not($width) and not($height) and not($scale)"> `
from
```
            <xsl:attribute name="width">100%</xsl:attribute>
            <xsl:attribute name="height">100%</xsl:attribute>
```
to
```
            <xsl:attribute name="max-width">100%</xsl:attribute>
            <xsl:attribute name="max-height">100%</xsl:attribute>
```
I didn't check that it works in all scaling-scenarios, but for my down-scale it works.

**Comment by rjcbop** [comment]
That also seems to work for my scaling-scenarios. Thanks!!

**Comment by Rohit-Metapercept** [comment]
The same attributes for scaling  is not working  under lists in my case. How do I fit it to margin ?

![img error](https://user-images.githubusercontent.com/23625111/61933808-607fdb00-afa4-11e9-85c2-f0893a320ab5.jpg)

**Comment by kirkilj** [comment]
Was this ever addressed? I see a couple workarounds mentioned, but it's still Open. I just came across the same behavior. Images all going to the top of the next page and also putting any subsequent content on the following page. Do @xephon2's and @tokup's workarounds produce the same result in the various scaling scenarios presented? If it wasn't at the end of my day, I'd try several scenarios with both myself, but I thought I'd ask in case one of you knows off-hand.
