### ISSUE TITLE
Keydef containing uplevels

### ISSUE THREAD

**Issue by fviolette** [dita-ot/dita-ot#2667]
In my DITA Map I define a key to an image:
`<keydef keys="arch_diagram" href="../../introduction/images/arch_diagram" format="png"/>`

With the keyref:
`<image keyref="arch_diagram"/>`

It's not expanded in 2.3.3 or 2.4.6 but is in 1.8.
Other keyrefs to keys without uplevels and all other images are impacted.

Also, I have the same issue as #2420, except the conref has also uplevels.

**Comment by mironovalexey** [comment]
Jarno, I'm sorry. Non-image and non-dita links should be resolved [here](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/KeyrefPaser.java#L427) against the `keyDef.source` as well. 

Then #2581 could be closed too.

**Comment by jelovirt** [comment]
Moved the non-image and non-DITA fix discussion to https://github.com/dita-ot/dita-ot/issues/2581#issuecomment-296524755

**Comment by fviolette** [comment]
Only testing now - thanks a lot! :+1:
