### ISSUE TITLE
PDF ToC adds “Chapter :” prefix to "appendices" navtitle

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2695]
As discussed in #2092 ([comments](https://github.com/dita-ot/dita-ot/issues/2092#issuecomment-273640632)), an `<appendices>` element with a `@navtitle` attribute such as

```xml
  <appendices navtitle="Appendices">
```

appears in the PDF ToC with a **“Chapter :”** prefix before the `@navtitle` text. 

> **Chapter : Appendices ………… [page]**

The prefix should be removed to show only the navtitle and align presentation with the PDF bookmark hierarchy.

**Comment by robander** [comment]
Testing this ... in the actual content, you still get an "Appendix" page heading above the appendices, without an appendix number, which is ... odd. Attaching a sample with 3 maps, using each of
`<appendices>`
`<appendices navtitle="Appendix container">`
`<appendices navtitle="appendices.dita">`

[2695.zip](https://github.com/dita-ot/dita-ot/files/1015562/2695.zip)

**Comment by robander** [comment]
Fixed with https://github.com/dita-ot/dita-ot/commit/aa94392068db9d7f031e0da05c1fd92848475039
