### ISSUE TITLE
generated links to topics under a chunked to-content topic point to wrong id

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/dita-ot#2702]
This issue is related to the HTML5 transform.

When linking to a child of a chunked="to-content" topic the resulting href does not correspond to the `@id ` of the target in the output:

`<xref href="child-topic-2.dita#child-topic-2"/>` where _child-topic-2.dita_ is under a chunked topic, outputs as `<a class="xref" href="head-topic-chunked.html#child-topic-2">`.

Whereas  _child-topic-2.dita_ outputs as `<article class="topic nested1" aria-labelledby="ariaid-title3" id="head-topic-chunked__child-topic-2">`.

Note the original `@id`  concatenated with the chunked topic `@id`.

The same issue is true with a keyref instead of an href.

See samples for more info. I used DITA-OT 2.4.6 and develop produce the output.
[DITA.zip](https://github.com/dita-ot/dita-ot/files/1024668/DITA.zip)
[HTML5.zip](https://github.com/dita-ot/dita-ot/files/1024665/HTML5.zip)
[HTML5-develop.zip](https://github.com/dita-ot/dita-ot/files/1024686/HTML5-develop.zip)

**Comment by jelovirt** [comment]
Are you able to reproduce this with `develop` branch?

**Comment by lionelmoi** [comment]
It behaves exactly the same way. See attached output.
[output-develop.zip](https://github.com/dita-ot/dita-ot/files/1024681/output-develop.zip)

**Comment by lionelmoi** [comment]
Seems https://github.com/dita-ot/dita-ot/pull/2686 fixed the issue !
