### ISSUE TITLE
Avoid renaming non-DITA resources used in branch filtering with dvrResourceSuffix or dvrResourcePrefix specified

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2704]
Let's say I have in the DITA Map a portion like this:

        <topicref href="topics/introduction.dita">
          <ditavalref href="test.ditaval">
            <ditavalmeta>
              <dvrResourceSuffix>stuff</dvrResourceSuffix>
            </ditavalmeta>      
          </ditavalref>
          <topicref href="test.pdf" format="pdf" navtitle="THIS IS MY PDF"/>
        </topicref>

Right now (even with latest DITA OT 2.x built from the develop branch) when you generate XHTML, the table of contents will have a broken reference to "teststuff.pdf".
In my opinion the dvrResourceSuffix and dvrResourcePrefix should only act upon topic references made to DITA resource, and not topic references made to non-DITA ones.

**Comment by raducoravu** [comment]
Another one of our users reported her SVG files being renamed depending on the "dvrResourceSuffix" set on the branch although again these resources have the same content in all contexts so they should not be renamed.

**Comment by drmacro** [comment]
When we were designing this feature I don't think we ever considered the possibility of having it apply only to DITA resources, but that does make sense as non-DITA resources cannot be different in different contexts through DITA-defined means.

**Comment by raducoravu** [comment]
Yup

**Comment by raducoravu** [comment]
👍 Feedback from one of our clients:

>  If I put the ditavalref on top of the map, not only all topicrefs get the prefix, but also all images from a keymap that is referenced in the master map, get it. I put a topicgroup around the normal topicrefs and now it works, but I think the default feature is not something that should be the default.

**Comment by raducoravu** [comment]
👍 Another similar report on the DITA Users List:
https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/44818

I quote the posted message below:

I have the following situation with keyscopes and branch filtering, and the HTML output is not correct while the PDF output is correct:

in the main bookmap:

    <chapter>
    <topicref keyscope="iris">
            <ditavalref href="iris.ditaval">
                <ditavalmeta>
                    <dvrResourceSuffix>-suf-iris</dvrResourceSuffix>
                </ditavalmeta>
            </ditavalref>
           
            <topicref href="flowers_topics.ditamap" format="ditamap"/>
         </topicref>

       <topicref keyscope="snowdrop">           
            <ditavalref href="snowdrop.ditaval">
                <ditavalmeta>
                    <dvrResourceSuffix>-suf-snowdrop</dvrResourceSuffix>
                </ditavalmeta>
            </ditavalref>
            <topicref href="flowers_topics.ditamap" format="ditamap"/>
        </topicref>
</chapter>


In flowers_topics.ditamap:
         <keydef keys="key_image" href="IrisSanguinea.jpg" format="jpg" product="iris" />
          <keydef keys="key_image" href="Snowdrop.jpg" format="jpg" product="snowdrop" />


In the topic I want to insert the image of the flower:

           <fig>
         <image keyref="key_image"/>
        </fig>

The HTML output is:

    <figure class="fig fignone">
       <img class="image" src="IrisSanguinea-suf-iris.jpg">
    </figure>

Of course this doesn't work as the image file is still called IrisSanguinea.jpg.
I understand that branch filtering creates copies of the dita files and adds the suffix or prefix, but we don't want that for images, do we?

**Comment by raducoravu** [comment]
As a possible fix, in the method "org.dita.dost.module.BranchFilterModule.processAttributes(Element, Branch)" the "generateCopyTo(URI, Branch)" should not get called for non-DITA resources.

**Comment by raducoravu** [comment]
I think the patched I made on my side for this is pretty stable, if you want I can try to open a pull request for this.
