### ISSUE TITLE
Incorrect DITAArchVersion in Topic RNG modules

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2705]
In the RNG file "plugins\org.oasis-open.dita.v1_3\rng\base\rng\topicMod.rng" search for:

         <attribute name="dita:DITAArchVersion" a:defaultValue="1.2"/>

The default version value should be 1.3. In our case this leads to Oxygen interpreting opened RNG-based topics as being DITA 1.2 compliant and not enabling various DITA 1.3 editing features in them.

**Comment by jelovirt** [comment]
Has this been reported to DITA TC? I would prefer TC to fix this and we just use the latest versions of the schemas. It's slower, though.

**Comment by drmacro** [comment]
I just checked my local version of the RNG source and the 1.2 value is present there as well, so I guess we need to add that as an errata.

I did a search and couldn't find  a:defaultValue="1.2" anywhere else.

It is correctly set to 1.3 in mapMod.rng

Looks like those are the only two places where dita: DITAArchVersion is set in the RNG

**Comment by robander** [comment]
I sent email to the TC to make sure it gets tracked and goes into the next errata. 

It's such a trivial item -- and will definitely be part of the next errata -- that I'd be fine shipping the fix already. (More like the early days when DITA didn't ship official errrata, just posted updated zips.)

**Comment by robander** [comment]
I've now checked this fix into the OASIS source code repository, so it will ship with the second errata, whenever that is available. I'd consider it safe to fix in (presumably) the first patch to 2.5.

**Comment by jelovirt** [comment]
This should be shipped in 2.5.1.

**Comment by robander** [comment]
Fixed with https://github.com/dita-ot/dita-ot/commit/b2d8e954b15e2e8812cb54cc3ae1a31c04a8285d
