### ISSUE TITLE
[DOTX010E] Error in conref processing

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#2720]
When I build the attached DITA instance, I encountered [DOTX010E] error in conref processing.

[20170612-conkeyref-diff.zip](https://github.com/dita-ot/dita-ot/files/1066951/20170612-conkeyref-diff.zip)

- I believe this to be a bug, not a question about using DITA-OT.
- I read the [CONTRIBUTING][] file.

## Expected Behavior

The error message is shown as follows:

```
[conref] file:/D:/SVN/pdf5/diffs/20170612-conkeyref-diff/ja-JP/topic/tStep2CheckThePrinterStatus.dita:4:65: [DOTX010E][ERROR]: Unable to find target for conref="../../collection-topic/tWhenConnectingPrintersStep02Template.dita#title_step02". 
[conref] java.io.FileNotFoundException: D:\SVN\pdf5\diffs\20170612-conkeyref-diff\ja-JP\temp\html5\ja-JP\topic\..\..\collection-topic\tWhenConnectingPrintersStep02Template.dita (指定されたパスが見つかりません。)
```

I believe that the conref correct path is `../collection-topic/tWhenConnectingPrintersStep02Template.dita#title_step02`

Please refer to the attached temp folder structure.
Conref processing should find the target normally.

## Actual Behavior
The conref'ed portion of the document has been vanished from the output.

## Steps to Reproduce

1. Open the attached 20170612-conkeyref-diff.zip. 
2. Run HTML5 transformation scenario. (It will be faster using oXygen project scenario "DITA Map HTML5 - DITA-OT 2.4.6" changing DITA-OT directory.)
3. The phenomenon should occur.

## Copy of the error message, log file or stack trace

error-20170612.log is attached in the ZIP file.

## Environment

* DITA-OT version: 
  2.5
* Operating system and version _(Linux, macOS, Windows)_: 
  Windows 10
* How did you run DITA-OT?
  oXygen, other editor, CMS, etc.
* Transformation type _(HTML5, PDF, custom, etc.)_: 
  HTML5

[CONTRIBUTING]: https://github.com/dita-ot/dita-ot/blob/develop/.github/CONTRIBUTING.md

**Comment by robander** [comment]
I have not looked closely at the source yet but I am getting a lot of errors in 3.0 building html5 with the attached samples, including "empty sequence not allowed as value of `$dita`" early in the `filter` stage. Although ... that's actually coming from `html2dita.xsl` which seems ... strange here. The build starts off with
```
   [filter] Warning at xsl:stylesheet on line 6 column 31 of utils.xsl:
   [filter]   Stylesheet module classpath:///utils.xsl is included or imported m
ore than once. This is
   [filter]   permitted, but may lead to errors or unexpected behavior
   [filter] <html><head/><body>GIF89a22?µ??¿??f?¿??3?¿???¿â?¢â?¢?¿â?¢f?¿â?¢3?¿â?
¢?¿fâ?¢?¿ff?¿f3?¿f?¿3â?¢?¿3f?¿33??????????â?¢????f????3??â?¢????â?¢â?¢??â?¢f??â?
¢3??â?¢??fâ?¢??ff??3â?¢??3fâ?¢???¿â?¢????â?¢??â?¢â?¢??fâ?¢??3â?¢??â?¢â?¢?¿â?¢â?¢
??â?¢â?¢â?¢â?¢â?¢fâ?¢â?¢3â?¢â?¢â?¢f??â?¢fâ?¢f????f??â?¢f??ff??3f??fâ?¢?¿fâ?¢??fâ
?¢â?¢fâ?¢3fâ?¢3????3??33??3â?¢??3â?¢â?¢?ª?ª?ª??????</body></html>
   [filter] Type error at char 4 in xsl:apply-templates/@select on line 18 colum
n 43 of html2dita.xsl:
   [filter]   XTTE0570: An empty sequence is not allowed as the value of variabl
e $dita
   [filter] An empty sequence is not allowed as the value of variable $dita
```
