### ISSUE TITLE
maplink generating additional, spurious links from keydef entries

### ISSUE THREAD

**Issue by strgaltentf** [dita-ot/dita-ot#2729]
Xhtml pages produced with a collection-type="sequence" attribute on the map have been creating navigation links with multiple parents and next entries, as shown in the picture. I would expect a single entry for next previous and parent. 

![dita_map_links_incorrect](https://user-images.githubusercontent.com/1036831/27276133-7a391a10-54da-11e7-8fa3-b2e520cb82b4.png)

The extract is produced from a large map, and I haven't been able to isolate the exact conditions that create it. However I have manage to trace the issue to what I think is a problem in the match condition being used to generate the links in maplinkImpl.xsl. 

For example, for the parent link, maplinkImpl.xsl currently uses the following test (around line 210):
`  
  <xsl:template match="*[contains(@class, ' map/topicref ')][not(ancestor::*[contains(concat(' ', @chunk, ' '), ' to-content ')])]"  mode="link-to-parent" name="link-to-parent">`

The problem arises because the generated map used from temp also includes keydefs, which have the class " map/topicref mapgroup-d/keydef ". The match is picking these up too, creating the spurious links.

Enhancing the match condition to exclude the keydef entries as shown below appears to cure the problem:
`<xsl:template match="*[contains(@class, ' map/topicref ') and not(contains(@class, ' mapgroup-d/keydef ')) ][not(ancestor::*[contains(concat(' ', @chunk, ' '), ' to-content ')])]" mode="link-to-parent" name="link-to-parent">`
The generated output for the same map as above is now as I would expect:

![dita_map_links_correct](https://user-images.githubusercontent.com/1036831/27276160-99e8db7a-54da-11e7-9d33-37a213dcab9d.png)

The correction would be required on at least the matches for parent and next/previous (around line 260), but probably on others too (sibling friend etc.). 

The only problem might be that anybody using the current implementation might have got used to seeng the current, incorrect implementation...

**Comment by strgaltentf** [comment]
(P.S above is based on 2.4.6 code)

**Comment by drmacro** [comment]
The check for parents should be ignoring any topicref with a @processing-role value "resource-only", which includes keydef topicrefs.

**Comment by robander** [comment]
Do you have sample files you can share? From the description, it sounds like maybe `<keydef>` is used as a parent to contain real content, which seems ... not quite right.

As Eliot indicated, we shouldn't ever have code that explicitly checks for the `<keydef>` element - that element is really just a shortcut that means (a-topicref-with-a-set-of-handy-defaulted-attributes), so if it's not processed correctly we should be checking for those attributes rather than for the element.

**Comment by strgaltentf** [comment]
No, I'll have to look at stripping down the dita to get to example files.  However this might take a few days.
It wasn't immediately obvious to me why the other topics that came up were being linked to, which might of course point to another or different upstream error.

**Comment by strgaltentf** [comment]
Sorry for the delay. 

I have now attached a tree in the zip file that exhibits this sort of behaviour, at least on version 2.4.6.
If you build the tree as xhtml , and look at the page for Topic Three, the you will see there are Four entries, with the Parent being duplicated, and the Next and Previous both pointing to the previous topic. 
![topic3_1](https://user-images.githubusercontent.com/1036831/28519674-d804fee0-706c-11e7-8843-47ec7304181f.png)

Interstingly, map 2 in the tree includes the topic ID as a fragment (e.g. "topic3.dita#t3"). If I take out the fragment (which, from my understanding shouldn't make any difference), then the surpluous links disappear, however the Next topic is shown as "Topic 2", although this is not the next but actually the previous topic in the map. 
![topic3_2](https://user-images.githubusercontent.com/1036831/28519910-b075fc8e-706d-11e7-879e-0334572a71e2.png)

[TestStructure.zip](https://github.com/dita-ot/dita-ot/files/1169556/TestStructure.zip)
