### ISSUE TITLE
Where is DITA OT Slack channel

### ISSUE THREAD

**Issue by markgif** [dita-ot/dita-ot#2734]
A DITA OT Slack channel is mentioned in the last video of the 2015 DITA OT Day. It's not on the dita-ot.org home page or anywhere else I can find. How do I find it?

- I believe this to be a bug, not a question about using DITA-OT.
- I read the [CONTRIBUTING][] file./not really, I can't find this either. I did look for it.

## Possible Solution

Add it to the home page of dita-ot.org.

[CONTRIBUTING]: https://github.com/dita-ot/dita-ot/blob/develop/.github/CONTRIBUTING.md

**Comment by jelovirt** [comment]
Move to dita-ot/docs issue tracker.

**Comment by markgif** [comment]
ok thanks
