### ISSUE TITLE
Cannot easily set task step label

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2747]
Let's say I want all my task steps to be displayed in the PDF output as "Step 1", "Step 2", etc.
Looking in the XSLT stylesheet `plugins\org.dita.pdf2\xsl\fo\task-elements.xsl` there is an XSLT template looking like this:
```xml
<xsl:template match="*[contains(@class, ' task/steps ')]/*[contains(@class, ' task/step ')]">
```
which uses a variable called 'Ordered List Number'. Ideally it would use a step-specific variable which could then be changed in the translation files.

I also do not see a way to do this for the HTML-based outputs.

**Comment by jelovirt** [comment]
@raducoravu are you referring to old code, as [develop branch](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/xsl/fo/task-elements.xsl#L249) uses `Step Number` variable.

**Comment by raducoravu** [comment]
Sorry, did not look at the newest code. I'll close this...

**Comment by jelovirt** [comment]
For HTML, we don't generate the step number from string variables, it's just using `<ol>` and the numbering is handled by browser and can be modified with CSS.

**Comment by roopeshnavath** [comment]
hi,

Is there any way to make prereq and  postreq task label for single item
ex: for <postreq> with single paragraph should display "Next Step"
     for <postreq> with single <li> should display "Next Step"

     for <postreq> with two paragraph should display "Next Steps"
    for <postreq> with two <li> should display "Next Steps"

     for <prereq> with one paragraph should display "prerequisite"
     for <prereq> with two paragraph should display "prerequisites"

 my Code sample
under Prereq template

<xsl:when test="count(ol/li) &lt; 2 or count(p) &lt; 2">

		 <xsl:apply-templates select="." mode="dita2xslfo:task-heading">
                <xsl:with-param name="use-label">
                    <xsl:call-template name="insertVariable">
                        <xsl:with-param name="theVariableID" select="'Task Prereq'"/>
                    </xsl:call-template>
                </xsl:with-param>
            </xsl:apply-templates>
		</xsl:when>
		<xsl:when test="count(ol/li) &gt; 1 or count(p) &gt; 1">

		 <xsl:apply-templates select="." mode="dita2xslfo:task-heading">
                <xsl:with-param name="use-label">
                    <xsl:call-template name="insertVariable">
                        <xsl:with-param name="theVariableID" select="'Task Prereqs'"/>
                    </xsl:call-template>
                </xsl:with-param>
            </xsl:apply-templates>
		</xsl:when>
