### ISSUE TITLE
Referencing images above map breaks output

### ISSUE THREAD

**Issue by joshjabs** [dita-ot/dita-ot#2750]
## Expected Behavior

I have a nested map that I want to be able to process independent of the map it is contained in. We have an images folder in the parent directory at the root map level with a logo that must be referenced by the sub-maps. I am using this command:

dita -i submap.ditamap -f html5 -o output/

I expect the toolkit to maintain the output file structure regardless of image links in the content. If one author includes an image from a directory not under my map, it should not re-organize the entire output structure. 

## Actual Behavior

I get expected output for processing my map if there are no references to an image above that map. However if I include a reference to an image above the map, the OT copies all of the directories above the map into the output instead of just referencing the image. This breaks every link in the output.

## Steps to Reproduce

1.Create a ditamap with an empty topic that processes as expected
2.Reference an image in the topic that is a directory above the map ( this would be our global images folder within our root map)
3.Re-process the ditamap. The file structure has changed and every link is broken.

## Environment

* DITA-OT version: 2.5.1
* Operating system and version: Windows 10
  _(Linux, macOS, Windows)_
* How did you run DITA-OT? dita -i submap.ditamap -f html5 -o output/
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type: HTML5
  _(HTML5, PDF, custom, etc.)_

**Comment by robander** [comment]
Reproduced with 2.5.1, the `generate.copy.outer` parameter does not seem to change the behavior.

**Comment by jelovirt** [comment]
@robander this is expected behaviour. Since the base directory is by default the map directory and referencing a file above the map will move the base directory, this is the only possible solution.
