### ISSUE TITLE
Allow for plugin param type 'url'

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2755]
In the plugin.xml for a certain transtype you can specify the type of each parameter. I would like if the type='url' would be allowed like:

            <?xml-model href="dita-ot/plugin.rnc" type="application/relax-ng-compact-syntax"?>
            <plugin id="newPluginID">
                <transtype name="webhelp">
                    <param name="webhelp.head.script"
                        desc="Specifies the URL of a well-formed XHTML document whose content will be copied into the &lt;head&gt; element of your output HTML documents."
                        type="url"/>
                </transtype>
            </plugin>

for example this would allow Oxygen to help the end user when inserting a value for the variable and propose an URL chooser for the parameter value instead of a file chooser.

**Comment by jelovirt** [comment]
The type of the param is not used anywhere right now, other than `enum` types. So adding this doesn't really require that many changes.

**Comment by raducoravu** [comment]
👍
