### ISSUE TITLE
DL indentation issue.

### ISSUE THREAD

**Issue by rui-doc-oliveira** [dita-ot/dita-ot#2756]
## Expected Behavior
In one of our topics we need to have a DL inside a LI (which belongs to an OL). The DL should be indented at the same depth as the LI where the DL is included.

We expect to see something like this:
1 - "This is a LI"
      "This is a DT"
      "This is a DD"
2 - "This is a LI"

When the DL is long enough, coming to the end of the page, the expected behaviour is that the DL should break, continuing on the next page. Or the whole DL, or the LI, should be pushed into the next page.

## Actual Behavior

The DL breaks from the LI indentation. Instead of having something like:

1 - "This is a LI"
      "This is a DT"
      "This is a DD"
2 - "This is a LI"

We get:

1 - "This is a LI"
"This is a DT"
"This is a DD"
2 - "This is a LI"

Another issue is that if I build a longer DL (which I need to for another topic) the DL inside the LI doesn't work well with the page break. The DL never goes to the next page. Instead it overwrites my footer and then disappears from the PDF.

## Possible Solution
Sorry, no idea :(

## Steps to Reproduce
Please see: 
[test.zip](https://github.com/dita-ot/dita-ot/files/1178153/test.zip)
For a test ditamap, and xml, reproducing the problem. Also included is a screenshot of how it looks on OxygenXML and the resulting PDF of the dita-ot transformation.

* DITA-OT version:
2.4.6+b074a2c

* Operating system and version:
Windows 10 Enterprise

* How did you run DITA-OT?
dita-bin\DITA-OT\bin\dita.bat -v -i  -f pdfvb -o E:\output\ -filter .ditaval -DditamapFileName= -Dretain.topic.fo=yes -Dgenerate.copy.outer=3

* Transformation type:
PDF

I tried to look through dita-ot for references to something that might help figure out where I need to debug and figure out what is wrong. Can't find anything. 

So basically... as anyone had a similar problem? Or can someone point me to where I should start looking, please?

**Comment by xephon2** [comment]
You use a custom transformation type `pdfvb`. Could you please publish again with `pdf2`?

```
dita-bin\DITA-OT\bin\dita.bat -v -i -f pdfvb -o E:\output\ -filter .ditaval -DditamapFileName= -Dretain.topic.fo=yes -Dgenerate.copy.outer=3
```

If the output looks good then, the problem is in your custom transformation type and not related to the *dita-ot*.

**Comment by rui-doc-oliveira** [comment]
Thank you for your quick answer.

[test.zip](https://github.com/dita-ot/dita-ot/files/1179291/test.zip)

I should've checked that and it seems it's our plugin's fault. I'll look into it and open a new issue if necessary. I'll try to close this one now...

Thank you!
