### ISSUE TITLE
Menucascade-separator variable missing

### ISSUE THREAD

**Issue by chrizzbee** [dita-ot/dita-ot#2757]
In DOT2.5, the variable for the #menucascade-separator is missing in all language-specific xml files in cfg\common\vars.

**Comment by robander** [comment]
The variable is now in the common string files in `xsl/common/`, along with the colon and quote symbols and the new "and then" translation that is also used for menu cascades:
https://github.com/dita-ot/dita-ot/blob/develop/src/main/xsl/common/strings-en-us.xml#L80

If you use the XSLT `getVariable` template, it should still be picked up properly from that location.
