### ISSUE TITLE
Feedback for the map-first processing functionality

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2771]
Using DITA OT 2.5.2. 
We have a DITA OT WebHelp plugin in which based on the topic:
http://www.dita-ot.org/dev/dev_ref/map-first-preprocessing.html

I made changes in its build files to use "preprocess2" instead of "preprocess".
I encountered two problems when building the output:

1) The "user.input.file" property is no longer defined and we made use of it.
2) The "fullditatopic.list" property is no longer defined and we also make use of it.

The "debug-filter" target defines lots of such properties. For compatibility reasons could maybe some of these definitions be also copied to an equivalent target in the new preprocessing stage?

**Comment by raducoravu** [comment]
PDF2 output also breaks with similar problems:

       D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2\build.xml:273: A source file is missing: D:\projects\eXml\test\dita\${user.input.dir}

**Comment by jelovirt** [comment]
Please use `develop` as basis for all comments, as 2.5.x is old code from preprocess2 perspective.

`fullditatopic.list` is one of the obsolete lists, the current code reads the lists on demand from job configuration.

**Comment by raducoravu** [comment]
It seems we actually depend on the "fullditatopicfile" but same thing really, it is also deprecated since 2.1. We use these in order to try and have the plugin work with both DITA OT 1.8 and 2.x.

**Comment by xephon2** [comment]
@raducoravu, is there a replacement for those files? I currently need both of them for iterating over topics for our new on-the-fly Schematron validator plugin [org.doctales.schematron](https://github.com/doctales/org.doctales.schematron).

* [fullditamap.list.file](https://github.com/doctales/org.doctales.schematron/blob/master/build_schematron-validation.xml#L61)
* [fullditatopic.list.file](https://github.com/doctales/org.doctales.schematron/blob/master/build_schematron-validation.xml#L79)

**Comment by jelovirt** [comment]
Note that you can still use preprocess1 in your transtypes, you just declare that as the dependency in the Ant script. A better way to iterating through the files has been introduced in 2.x already, `<ditaFileset format="dita"/>`.

**Comment by raducoravu** [comment]
As an example in the "plugins\org.dita.xhtml\build_general.xml" there is a macro called "topics.html".
@jelovirt, can I use that "ditaFileset" inside any ANT xslt task or only inside the "xslt" which is inside the "pipeline" ANT custom task?

**Comment by jelovirt** [comment]
It's an implementation of [_resources:](https://ant.apache.org/manual/Types/resources.html), so you should be able to use it anywhere, e.g. in `<copy>`.

**Comment by robander** [comment]
@jelovirt or @raducoravu -- should this issue be closed now, given that it was feedback on the beta version of `preprocess2`, and we now ship a real version in 3.0? I think that @jelovirt provided the alternative for function that was originally reported missing.

**Comment by raducoravu** [comment]
I'll close it and add individual issues when I find them.
