### ISSUE TITLE
Add Markdown plugin to distribution package

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2774]
The [DITA-OT Markdown](https://github.com/jelovirt/dita-ot-markdown) plugin should be added to the default distribution to support lightweight authoring and publishing workflows.

This would allow users to include [Markdown](https://daringfireball.net/projects/markdown/) files as topics and generate Markdown output from DITA source without having to install additional plugins.

**Comment by jelovirt** [comment]
Added the latest Markdown plugin. It's likely that for 3.0 release we will bundle a new version of the plugin if one is available.
