### ISSUE TITLE
Add normalization plugin to distribution package

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2775]
The **DITA to DITA plugin** [org.dita.normalize](https://github.com/dita-ot/org.dita.normalize) should be added to the default distribution.

This would provide access to normalized topics and maps from DITA input without having to install additional plugins or copy files from the `temp` folders created during builds.

Since normalized output includes the results of the pre-processing operations that resolve references, it can be used to access the DITA output generated from [Markdown input](https://github.com/dita-ot/dita-ot/issues/2774), or feed DITA content into less sophisticated authoring tools which may not support certain features from the latest DITA versions.

Normalized output can also be used during plugin development to troubleshoot the results of preprocessing routines.

**Comment by jelovirt** [comment]
Added the latest Normalize plugin. It's likely that for 3.0 release we will bundle a new version of the plugin if one is available.
