### ISSUE TITLE
JPEG image resolution

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#2778]
## Expected Behavior
I'm developing DITA to WordprocessingML plug-in. To convert `<image>` to the `<w:drawing>` the image resolution information is indispensable for JPEG image.

## Actual Behavior
[https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/ImageMetadataFilter.java](
) currently support only PNG image file resolution. It does not return the JPEG resolution.
As a result the plug-in cannot get correct image size, moreover I cannot implement image/@scale attribute.

    <image href="image/tys125f.jpg" id="image_tdk_5tg_dbb" scale="20" placement="inline" class="- topic/image " xtrf="file:/D:/SVN/pdf5/testdata-ooxml/20170907-image/cImageTest.dita" xtrc="image:4;20:74" dita-ot:image-width="1200" dita-ot:image-height="1600"/>

## Possible Solution
Add the code to get the resolution of JPEG image.

## Steps to Reproduce
1. Make a topic that contains image element that contains the href attribute to the JPEG image file.
2. Execute Jarno's plugin com.elovirta.ooxml
3. Confirm that the topic file in temp directory does not contain dita-ot:horizontal-dpi and dita-ot:vertical-dpi attribute. for JPEG image

## Environment

* DITA-OT version: 2.5.1
* Operating system and version: Windows 10 64bit 
* How did you run DITA-OT? From oXygen or command-line
* Transformation type: com.elovirta.ooxml

**Comment by jelovirt** [comment]
Which colour space does the JPEG use? If I recall correctly, for example CMYK colour spaces are not support out of the box.

**Comment by ToshihikoMakita** [comment]
CMYK will not be used. Most of the jpeg file that has been taken from cellar phone has Exif format .  I attached for your reference.

![2017-09-10-3](https://user-images.githubusercontent.com/1801890/30248532-7ae6c630-9664-11e7-97fa-79c0bd95e37a.png)

**Comment by ToshihikoMakita** [comment]
As far as I know Exif uses sRGB color space.
