### ISSUE TITLE
current.date/dita.temp.dir is undefined after preprocessing on Linux since DITA-OT 2.4.3

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2779]
## Expected Behavior

The property `dita.temp.dir` should be available after preprocessing on Linux. Since DITA-OT **2.4.3** the property is not defined anymore. It is quite weird, it works on our Jenkins instance, which is Ubuntu based, I think. But it does not work on my private _Manjaro Linux (Arch based)_ machine and on _Travis CI_, e.g. [in this job](https://travis-ci.org/doctales/org.doctales.terminology/builds/271989898#L3554).

## Actual Behavior
Property is undefined

## Possible Solution
Check, what has changed with this release.

## Steps to Reproduce
Simply call `<echo>dita.temp.dir=${dita.temp.dir}</echo>`

## Environment

* DITA-OT version: **2.4.3+**
* Operating system and version: **Manjaro Linux (Arch based)**
* How did you run DITA-OT? **dita command**
* Transformation type: **HTML5**

**Comment by xephon2** [comment]
As you can see in the build history, downgrading the DITA-OT helps to fix the build of our plugin: https://travis-ci.org/doctales/org.doctales.terminology/builds/273897438

**Comment by xephon2** [comment]
The problem is related to `current.date`, which is then used to create `dita.temp.dir`. To reproduce this, call a new target:

```xml
<target name="dita2mynewtarget">
  <antcall target="dita2html5"/>
  <antcall target="mytarget"/>
</target>
```

Echo the properties:

```xml
<echo>current.date=${current.date}</echo>
<echo>base.temp.dir=${base.temp.dir}</echo>
<echo>dita.temp.dir=${dita.temp.dir}</echo>
<echo>output.dir=${output.dir}</echo>
<echo>basedir=${basedir}</echo>
```

**Output DITA-OT 2.4.2**
```
     [echo] current.date=20170911210146672
     [echo] base.temp.dir=/tmp
     [echo] dita.temp.dir=/tmp/temp20170911210146672
     [echo] output.dir=/home/stefan/workspace/org.doctales.terminology/samples/./out
     [echo] basedir=/home/stefan/workspace/DITA/dita-ot
```

**Output DITA-OT 2.5.3**
```
     [echo] current.date=${current.date}
     [echo] base.temp.dir=/tmp
     [echo] dita.temp.dir=${dita.temp.dir}
     [echo] output.dir=/home/stefan/workspace/org.doctales.terminology/samples/./out
     [echo] basedir=/home/stefan/workspace/DITA/dita-ot
```

**Comment by robander** [comment]
The usual way to call these, as I understand it (at least as I've always done it) is to do a dependency chain --

```
<target name="dita2mynewtarget" depends="dita2html5, mytarget">
</target>
```

I know properties are set / passed / preserved differently when using `<antcall>`, but I don't know enough to say for sure it's the issue here. If you run the target that way does it resolve the problem, or is there some reason that won't work here?

**Comment by xephon2** [comment]
@robander Thank you for your response. Yes, I know. I've tested it with `depends` instead of `<antcall>` and that would help. **But**: I remembered why I used `<antcall>` here. The problem with using `depends` is, that the DITA-OT/Ant breaks, if a target is not available. It does not break, if an `<antcall>` target is not available. Our plugin [org.doctales.terminology](https://github.com/doctales/org.doctales.terminology) optionaly uses **com.oxygenxml.webhelp** to generate _webhelp_ based output. But I want the plugin to work _without_ **com.oxygenxml.webhelp**  (without the targets `dita2webhelp` and `dita2webhelp-responsive`) as well, e.g. to publish `html5` based output. **com.oxygenxml.webhelp** is not free software and therefore I do not want to have it as a hard dependency. So it would be very nice, if it would work with `<antcall>`, too. Or maybe there is another technical solution. But I'm afraid that Ant changed the property handling and that this is not an DITA-OT issue.

**Comment by xephon2** [comment]
```xml
<target name="dita2mynewtarget">
  <antcall target="dita2html5"/>
  <!-- The property is here not available as well, so I cannot push it with <param> -->
  <echo>dita.temp.dir=${dita.temp.dir}</echo>
  <antcall target="mytarget"/>
</target>

**Comment by robander** [comment]
The `dita2html5` target itself should always be there -- would it work to set it up like this?
```
<target name="dita2mynewtarget" depends="dita2html5">
  <echo>dita.temp.dir=${dita.temp.dir}</echo>
  <antcall target="mytarget"/>
</target>
```

**Comment by xephon2** [comment]
Let's look at the real code

This does not work, because of the `<antcall>` issue.

```xml
<target name="dita2termbrowser-responsive" depends="is.com.oxygen.webhelp.available">
  <antcall target="dita2webhelp-responsive"/>
  <antcall target="termbrowser-termstats"/>
  <antcall target="semanticnet"/>
</target>
```

This works, but only if **com.oxygenxml.webhelp** is installed.

```xml
<target name="dita2termbrowser-responsive"
    depends="is.com.oxygen.webhelp.available,
             dita2webhelp-responsive,
             termbrowser-termstats,
             semanticnet"/>
```

I could work around by calling `init-properties` _before_ calling `dita2webhelp-responsive`. So it actually is called twice, but this does not really matter.

```
<target name="dita2termbrowser-responsive" depends="is.com.oxygen.webhelp.available, init-properties">
  <antcall target="dita2webhelp-responsive"/>
  <antcall target="termbrowser-termstats"/>
  <antcall target="semanticnet"/>
</target>
```

I can live with the workaround, so I close this issue.
