### ISSUE TITLE
DITA OT integrator fails to properly integrate on Linux

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2792]
I'm running on Linux the DITA OT integrator calling the "integrator.xml" directly having in the classpath all the DITA OT libraries.
I receive in the console warnings for each of the XML documents which need to be parsed and incorporated:
```
[integrate] no protocol: /home/test/projets en développement/eXml/frameworks/dita/DITA-OT2.x/plugins/org.dita.pdf2/resource/messages.xml
[integrate] no protocol: /home/test/projets en développement/eXml/frameworks/dita/DITA-OT2.x/plugins/org.dita.specialization.eclipsemap/params.xml
```

From what I analyzed the method `org.dita.dost.platform.InsertAction.getResult(ContentHandler)` iterates over file-like paths and should convert them to URL-like paths before calling the parser to parse them, something like:

```java
currentFile = fileName;
try{
  new URL(currentFile);
} catch(MalformedURLException ex){
  currentFile = new File(currentFile).toURI().toASCIIString();
}
reader.parse(currentFile);
```

Another problem is that despite of this error being thrown for each parameters XML document, the integrator reports Build Successful at the end.

**Comment by jelovirt** [comment]
Which DITA-OT version?

**Comment by raducoravu** [comment]
DITA OT 2.5.2 but probably older versions have the same problem. I'm not sure how this usually works when running the DITA OT integrator from the command line using the "dita -install".
Possibly because my DITA OT is installed in a folder which has French accents... we run our automated tests in such a folder.

**Comment by jelovirt** [comment]
It's because the integrator requires DITA-OT classes and configuration to be in the classpath. Older versions of DITA-OT were able to run the integrator without classpath configuration because they used Ant to handle the classpath. This is no longer the case and the integration code requires the classpath; when running the dita command, the classpath is configured by the shell/batch script.

**Comment by jelovirt** [comment]
This issue seems to have multiple issues. The last issue about "Build Succssful" should be moved to a separate issue.

**Comment by raducoravu** [comment]
I added: https://github.com/dita-ot/dita-ot/issues/2794

**Comment by raducoravu** [comment]
One more fix to make the integrator properly work in such cases is that in the class "org.dita.dost.platform.InsertAntActionRelative" replace this:

                final File targetFile = new File(
                        new File(currentFile).getParentFile(),
                        attributes.getValue(i));

with this:

            	File currentFileFile = null;
            	try {
            		URL currentFileURL = new URL(currentFile);
            		//It's an URL
            		currentFileFile = new File(currentFileURL.toURI());
            	} catch(MalformedURLException | URISyntaxException ex){
            		currentFileFile = new File(currentFile);
				}
                final File targetFile = new File(
                		currentFileFile.getParentFile(),
                        attributes.getValue(i));

because the "currentFile" variable will become an URL due to the changes in "InsertAction".
