### ISSUE TITLE
Related links to external web sites using scope="external" no longer shown in PDF

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2795]
Tested with 2.5.3, seems to occur also with 2.4, but with DITA OT 2.3 it seemed to work.
The topic has a related link section at the end:

    <related-links>
        <link href="http://www.oxygenxml.com" format="html" scope="external"/>
    </related-links>

I'm using "args.rellinks="all"". The generated PDF has in the topic related links section a title like "Related links" but it's not followed by any link.
Related links to internal topics still work though.

**Comment by raducoravu** [comment]
Using scope="peer" on the link element starts showing the link in the PDF.

**Comment by raducoravu** [comment]
It also works if you specify a linktext element inside the link.

**Comment by robander** [comment]
I've reproduced with 2.5.3 (including the peer / linktext updates, not sure what is going on.

**Comment by robander** [comment]
Fixed with #2802
