### ISSUE TITLE
Windows: rendering of codeblock/coderef with RTL chars not correct

### ISSUE THREAD

**Issue by spoeschel** [dita-ot/dita-ot#2812]
## Expected Behavior
A codeblock/coderef file within a DITA topic (within a DITA map) that contains bidirectional text (left-to-right as well as right-to-left characters) is rendered correctly; I attached a respective example (see below).

## Actual Behavior
When using DITA-OT on Linux, the behaviour is as expected and all characters including the RTL ones look fine. The resulting PDF and HTML5 files also look fine when opened on Windows.

But using DITA-OT on Windows, the RTL characters are not rendered correctly. Instead something like the following is rendered: `Ù†Ø1Ù...ØŒ Ø£Ù†Ø§ Ø£Ø1ÙŠØ ́ Ù‡Ù†Ø§ Ø£ÙŠØ¶Ø§.`

## Steps to Reproduce
- extract the files from [rtl_test_problem.zip](https://github.com/dita-ot/dita-ot/files/1381801/rtl_test_problem.zip) into a folder
- execute: `dita -i rtl_test.ditamap -f pdf`
- execute: `dita -i rtl_test.ditamap -f html5`

## Environment

* DITA-OT version: 2.5.4
* Operating system and version:
  * Linux, Ubuntu MATE 16.04 AMD64
  * Windows 7 Pro 64bit
* How did you run DITA-OT?
  * directly via cmd
* Transformation type:
  * PDF
  * HTML5

**Comment by jelovirt** [comment]
Note that when using `<coderef>`, the file is read using system default charset. If the file contains non-ASCII characters, this likely will not work on all platforms as they use different default charsets.

See http://www.dita-ot.org/2.5/user-guide/extended-functionality.html#code-reference__coderef-charset how to set the charset of the `<coderef>` target document.

**Comment by spoeschel** [comment]
Thank you, this instantly fixes the problem!
