### ISSUE TITLE
Clarify licensing terms of "com.sophos.tocjs" plugin

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2813]
There is a license in the plugin "plugins\com.sophos.tocjs\license.txt" stating something like:

            "If, at the time of use, the Project Management Committee has designated another 
            version of this license or another license as being applicable to the 
            DITA Open Toolkit, user may select to have its subsequent use of the 
            DITA Open Toolkit governed by such other designated license.  "

which our legal is not quite comfortable with. Maybe it can be removed as the entire DITA OT has a license anyway. Or maybe the entire "com.sophos.tocjs" could be removed as a plugin...

**Comment by jelovirt** [comment]
Please raise this issue at https://github.com/dita-ot/com.sophos.tocjs

**Comment by robander** [comment]
I think that was copied as-is from an old DITA-OT `license.txt`, which was cleaned up a couple releases ago. Same update should be made here. But yes, technically request should be made in the other repository.

**Comment by robander** [comment]
Opened a pull request: https://github.com/dita-ot/com.sophos.tocjs/pull/1

**Comment by raducoravu** [comment]
Thanks @robander.
