### ISSUE TITLE
Support relative paths for HTML headers/footers

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2815]
Currently several HTML parameters require absolute path values, which prevents portable cross-platform builds with the `dita` command:

* `args.ftr`
* `args.hdf`
* `args.hdr`

If absolute paths for these parameters are defined on one system, the same command/value may not work on other operating systems or machines where paths differ.

Allowing the `dita` command to interpret relative paths in these cases would reduce the need for Ant or other build scripts to set paths with variables that resolve to the correct local path when the build runs. 

These parameter values could then be passed in `.properties` files that work on multiple systems, which is apparently not possible at the moment per [comments](https://github.com/dita-ot/docs/pull/163#issuecomment-337163323) in https://github.com/dita-ot/docs/pull/163:

> WRT the absolute paths and properties file: cannot be fixed so that it will work every[w]here and will not break OT itself.

Various toolkit parameters currently use different approaches to path resolution. Perhaps the resolution mechanism for the HTML header/footer files could be aligned with one of these other approaches:

* `args.filter`

	> Relative paths are resolved against the DITA-OT base directory (for backwards compatibility) and internally converted to absolute paths.

* `args.input`

	> The path can be absolute, relative to `args.input.dir`, or relative to the directory where your project's Ant build script resides if `args.input.dir` is not defined.

**Comment by jelovirt** [comment]
If those properties are made to support relative paths, it will only be at the outer API, i.e. in `dita` command. They will need to be resolved to absolute paths before the files are read by XSLT.

**Comment by shaneataylor** [comment]
I think it's reasonable only to support this enhancement for the dita command and not Ant.

I'd also like to suggest that relative path resolution follow a common set of rules that minimizes the likelihood of unresolved paths by accepting the first of the following potential resolutions for which the target is found:

1. Relative to the properties file (if one is specified)
2. Relative to `input.dir` (if specified)
3. Relative to the `args.input` path (maybe set the default value of `input.dir` based on `args.input`?)
4. Relative to the transtype's plugin directory (not unusual to set headers and footers as part of an HTML customization)
5. Relative to DITA-OT home

I realize this adds some complexity, but it also (I think) addresses the most common assumptions users have about how such relative paths _should_ be resolved.

**Comment by jelovirt** [comment]
The only correct base path is the properties file when the properties are set in a properties file, and the current directory when set using `-D`.

**Comment by infotexture** [comment]
Based on discussion in #3016, it looks like `args.cssroot` may (now?) also require an absolute path to ensure custom CSS is applied.
