### ISSUE TITLE
Task Module RNGs do not allow for easy domain attribute substitution

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2818]
If you look at this RNG file:

https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.oasis-open.dita.v1_3/rng/technicalContent/rng/taskMod.rng

at some point it contains something like:

        <optional>
          <attribute name="domains"
            a:defaultValue="(topic task)                            (topic hi-d)                             (topic ut-d)                             (topic indexing-d)                            (topic hazard-d)                            (topic abbrev-d)                            (topic pr-d)                             (topic sw-d)                            (topic ui-d)   "
          />
        </optional>

which should probably be replaced with:

            <ref name="domains-att"/>

because the "domains-att" is defined in the "task.rng" and this also allows for easier substitution of the attribute default value when creating a specialization of the task which for example adds a new profiling attribute which needs to be defined also in the domains attribute.

**Comment by raducoravu** [comment]
One side effect of the current issue is that the "deliveryTarget" attribute also does not appear in the task @domains default value, so possibly filtering content inside tasks based on it does not work.

**Comment by raducoravu** [comment]
Same problem seems to occur in "referenceMod.rng"

**Comment by drmacro** [comment]
These do seem to be present in the official versions. I think we can get this fixed for Errata 2. In any case, I'll fix the files and submit a pull request to the OASIS repo.

**Comment by drmacro** [comment]
Also looks like subjectSchemeMod.rng has this problem.

**Comment by drmacro** [comment]
Pull request submitted to TC's GitHub repo:

https://github.com/oasis-tcs/dita/pull/80

**Comment by raducoravu** [comment]
👍

**Comment by robander** [comment]
Fixed with #2860
