### ISSUE TITLE
HTML5 warning: map2html5Impl.xsl is included or imported more than once

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2821]
HTML5 builds throw the following XSLT warning in the console:

    [xslt] Warning at xsl:stylesheet on line 12 column 59 of map2html5Impl.xsl:
    [xslt]   Stylesheet module plugin:org.dita.html5:xsl/map2html5Impl.xsl is included or imported more
    [xslt]   than once. This is permitted, but may lead to errors or unexpected behavior

Output appears to be generated correctly, but the presence of this warning will cause confusion for users if it continues to appear.

**Comment by infotexture** [comment]
The duplicate imports are in [org.dita.html5/xsl/map2html5-coverImpl_template.xsl](https://github.com/dita-ot/dita-ot/blob/3c152945ccf3c95b333276711fe3042b17f9a5ad/src/main/plugins/org.dita.html5/xsl/map2html5-coverImpl_template.xsl#L16) and [nav.xsl](https://github.com/dita-ot/dita-ot/blob/3c152945ccf3c95b333276711fe3042b17f9a5ad/src/main/plugins/org.dita.html5/xsl/nav.xsl#L16) 
— but they've been there since 2.4, so it's not immediately apparent why the errors began appearing during the 3.0 release cycle.

**Comment by robander** [comment]
> it's not immediately apparent why the errors began appearing during the 3.0 release cycle.

I would guess it's related to the big jump in Saxon versions that came with 3.0...

**Comment by infotexture** [comment]
Resolved for 3.1 in #2939, cherry-picked to 3.0.4 in #2950.

**Comment by infotexture** [comment]
#2950 was reverted from 3.0.4 in 0197aed.

**Comment by jelovirt** [comment]
Implemented by #2970.
