### ISSUE TITLE
Update Saxon 9.8 used in DITA OT to version 9.8.0.5

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2822]
Saxon 9.8 is still not very stable and we should probably always try to update to the latest version for it.

**Comment by raducoravu** [comment]
One of the problems we encountered running DITA OT with Saxon 9.8.0.2:
https://saxonica.plan.io/issues/3364
and it was fixed in 9.8.0.4.

**Comment by jelovirt** [comment]
This was shipped in 3.0

**Comment by raducoravu** [comment]
👍 I confirm this.
