### ISSUE TITLE
PDF: Conref regression with preprocess2

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2823]
When building the docs using dita-ot/dita-ot@19abe1998, there are missing conrefs in the PDF output _(empty bullets on page 12, for example)_.

This is apparently related to recent changes in the conref processing and/or `preprocess2`, as the content appears as expected when building with the `master` branch of the `dita-ot` repo.

**Comment by infotexture** [comment]
The source for this portion of the content is [using-dita-command.dita#L24-L40](https://github.com/dita-ot/docs/blob/develop/user-guide/using-dita-command.dita#L24-L40).

**Comment by jelovirt** [comment]
This looks like the cause is branch filtering. When `using-dita-command.dita` is duplicated in branch filtering, the file info fields that mark this topic as having conref are not copied. I updated the code to copy "content fields" from source to destination file info.

**Comment by infotexture** [comment]
👍 Verified. The changes in ea50ceb solve the problem, thanks.
