### ISSUE TITLE
Problems processing topics which have "%" in their file name

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2829]
Tested with DITA OT 2.5.2.
One of our users references in the DITA Map a topic which has the file name containing the "%" character, something like: "between10-20%of_overall.dita".
The publishing fails to parse the topic:

          [topic-merge] Malformed escape pair at index 24: topics/flowers/iris10-20%.dita

**Comment by drmacro** [comment]
What does the initial URI reference in the doc source look like? The % must be escaped in the original reference or it wouldn't be a valid URI.

**Comment by jelovirt** [comment]
We attempt to fix invalid URIs, e.g. to fix a space in filename to `%20`. In this case it may be too aggressive or does the wrong thing.

**Comment by raducoravu** [comment]
The reference to the topic (which is named for example 'iris10-20%.dita') in the DITA Map is correct and it looks like this:

         <topicref href="topics/flowers/iris10-20%25.dita"/>

**Comment by raducoravu** [comment]
That same user had a topic using simple quotes like for example "Radu's Topic.dita" but that works OK.

**Comment by robander** [comment]
Just tried this based on the comments in 2844, and like with that one, a file reference that includes `%25` works in 3.0 for PDF but fails with HTML5. For my test I just renamed our sample `garagetaskoverview.xml` to `garage%taskoverview.xml`, and updated the reference to `href="garage%25taskoverview.xml`:
```
maplink:
  [maplink] Processing file:/C:/Users/IBM_AD~1/AppData/Local/Temp/temp2017111611
0719056/concepts/wwfluid.xml
  [maplink] Processing file:/C:/Users/IBM_AD~1/AppData/Local/Temp/temp2017111611
0719056/concepts/lawnmower.xml
  [maplink] Processing file:/C:/Users/IBM_AD~1/AppData/Local/Temp/temp2017111611
0719056/tasks/washingthecar.xml
Error: java.lang.IllegalArgumentException: Malformed escape pair at index 12: ta
sks/garage%taskoverview.xml
```

**Comment by raducoravu** [comment]
Thanks, I confirm fix works for XHTML and PDF outputs.
