### ISSUE TITLE
Use original file name in CHM generation

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2830]
Use original topic file names in generated HTMLHelp to support stable file names for linking.

**Comment by drmacro** [comment]
Provide option (ideally, the default) to prefer keys when keys are specified on normal-role topics as the basis for result filenames.

**Comment by jelovirt** [comment]
What about generated topics, e.g. from `@copy-to`, chunking, or branch filtering? They don't have key based identity?

**Comment by drmacro** [comment]
Any topic referenced by a topicref with a @keys value has a key-based identity, irrespective of chunking, copy-to, or filtering. 

That is, once the map is resolved and branch filtering is applied, every topicref either does or does not have an associated key for each reference to it (including ignoring or removing @keys values that end up being non-effective duplicate key definitions).

The logic here is that @keys is the most reliable and stable way to ensure unique identifiers for unique uses of topics within a given root map context. The map author has no reliable control over source filenames but has absolute control over the keys associated with uses of topics.

One way to model this is to use @keys (and by extension, applicable key scopes) to construct effective @copy-to values, which is of course exactly what my adjust-copy-to plugin for OT 1.8.5 does.

There either needs to be a preprocessing extension point where I can add this behavior myself or it needs to be built in with appropriate configuration options and/or extension points so the details of how result filenames (more generally, deliverable anchors) are constructed can be adapted to specific requirements.

**Comment by jelovirt** [comment]
What are the two key based identities for

```

**Comment by drmacro** [comment]
This requirement can be generalized to all output types, not just HTML help of course.

It also suggests that it's best done as part of the final-form processing, not as part of preprocessing, although it's handy to be able to do a trick like setting @copy-to during pre processing, which works well for multi-file outputs but won't help with monolithic outputs.

I think what I'd really like, but I haven't had a chance to really think it through, is some kind of "anchor determination service" that can be called from final-form transforms to get anchors, where the details of how the anchor is determined is a function of the service. This is looking forward to enhancing existing final-form to support cross-deliverable linking where you may need to be able to get anchors for other publications.

**Comment by drmacro** [comment]
Here:

```
<topicref keys="foo" href="original.dita" copy-to="copy.dita"/>
```

The key-based identity is "foo", so I would expect e.g. "foo.html" as the result. Neither the original href nor the copy-to value is particularly interesting except to the degree that the copy-to is a clear signal that the use should result in a distinct result file (if you think it's appropriate to ever have one result file for multiple uses of a given topic).

**Comment by jelovirt** [comment]
Since `@copy-to` has been part of DITA since 1.0, we can't ignore it and just say "it's not particularly interesting". We need to produce two unique resources based on `original.dita` and `copy.dita` URIs, and forcing them to use the same final identity is _one_ solution. But it is also completely wrong solution in some cases because we'd be throwing away the two unique identities.

**Comment by drmacro** [comment]
I mean "not interesting" in the case where what you want is for the key to determine the result anchor.

That's why it needs to be an option: as an Information Architect I make an informed decision to use keys as the basis for my published anchors. In that case copy-to and source filenames are not interesting.

Of course, if I've not made that decision then source filenames and copy-to values (which is the same thing) remain interesting.

But we should be encouraging users to use the most reliable solution, which is to use keys.

**Comment by jelovirt** [comment]
Because we must still be able to convert DITA 1.0 written 15 years ago, we can't make the key based identity the default. Having key based identity can thus only be an option, and not the default.

**Comment by drmacro** [comment]
If there are no keys then they can't contribute to the result anchor names. But I understand the reticence to make it the default.

The processing has to provide a precedence order, e.g. @keys value, if present (or more completely, effective scope-qualified @keys value), then @copy-to, if present, then source filename or generated value.
