### ISSUE TITLE
References to non-existing libraries in DITA OT 3.0

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2832]
In this build template:

        dita-ot-3.0\plugins\org.dita.pdf2\build_template.xml

there are references to JARs which no longer exist:

      <pathelement location="${lib.dir}/saxon.jar"/>
      <pathelement location="${lib.dir}/saxon-dom.jar"/>

**Comment by robander** [comment]
3.1.2 will remove the references from the dedicated class path variable, and the variable itself will be removed in 3.2.
