### ISSUE TITLE
Built PDF file for 3.0 in input directory, not output directory

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2834]
## Expected Behavior
As with earlier DITA-OT versions, the PDF should be placed in the specified output directory.

## Actual Behavior
The PDF is in the input directory.

## Possible Solution
No solution yet, but this is related to map-first preprocessing. If you change the `dita2pdf2` target to use the old `preprocess` step, the generated PDF is in the correct location.

## Steps to Reproduce
1. Build a PDF with DITA-OT 3.0.

## Environment
* DITA-OT version: 3.0
* Operating system and version: MacOS 10.12.6
* How did you run DITA-OT? dita command (via Ant)
* Transformation type: PDF

**Comment by robander** [comment]
I'm not sure what is going on here - when I build PDF with 3.0 (or the 3.0.1 dev code), my PDF still goes into the output directory, so I'm unable to reproduce. I'm building using the `dita` command on Windows.
