### ISSUE TITLE
Integration issues - Jarno's Markdown parser

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/dita-ot#2836]
## Expected Behavior
Generate markdown_github output from one of the ./docsrc sample domains.

c:\dita-ot-3.0_demo1\bin\dita --input=hierarchy.ditamap 
   --format=markdown_github 
   --output=output/markdown-github/hierarchy 
   --args.input.dir=c:/dita-ot-3.0_demo1/docsrc/samples

## Actual Behavior
Received the build error:
Error: stylesheet c:\dita-ot-3.0_demo1\${dita.plugin.com.elovirta.dita.markdown.
dir}\xsl\dita2markdown_github.xsl doesn't exist.

## Possible Solution
I installed Jarno's plugin manually and the build succeeded.

The _Release Notes_ confused me in that they seemed to indicated that Jarno's plug-in had been integrated with dita-ot-3.0. 

## Copy of the error message, log file or stack trace
Error: stylesheet c:\dita-ot-3.0_demo1\${dita.plugin.com.elovirta.dita.markdown.
dir}\xsl\dita2markdown_github.xsl doesn't exist.

## Environment

* DITA-OT version:  3.0
* Operating system and version: Windows
* How did you run DITA-OT? dita (see above, run it yourself)
* Transformation type: markdown_github

**Comment by infotexture** [comment]
Resolved with jelovirt/org.lwdita#1.

Since DITA-OT 3.0 bundled plug-in version 2.0, this fix was not yet included there. 

DITA-OT 3.0.1 should include this change.

**Comment by StanDoherty** [comment]
Thanks . . . makes sense. Thank you so much for all your good work.

Stan

**Comment by infotexture** [comment]
Implemented in 6feb56b with #2846.
