### ISSUE TITLE
DITA OT 3.0 Markdown pipeline error

### ISSUE THREAD

**Issue by wbrisett** [dita-ot/dita-ot#2837]
I’m trying to do some testing to see how the Markdown to DITA plug-in works with some content I have, but after installing DITA-OT 3.0 and trying it, I continue to get this error during the transform: 

Error: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.typographic.TypographicSmarts

I can't find anything related to this error via a google search, and I would assume the preinstalled plug-in would have all the libraries, so I'm puzzled. 

I am using the following: 
`dita -i <input ditamap> -f markdown -o <output dir> `

my map simply has one topicref that looks like this: 

`<topicref href="xxx.md" format="mdita" />`

**Comment by infotexture** [comment]
See #2866 & jelovirt/org.lwdita#3.

**Comment by infotexture** [comment]
Resolved in 8806bad for 3.0.2 with LwDITA plug-in v2.0.2 (see jelovirt/org.lwdita@2c01572).
