### ISSUE TITLE
Publish topic to PDF breaks if topic has conref to element defined in DITA Map

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2840]
Tested with DITA OT 2.5.2.
I have a DITA Map which has a keyword with an ID:

    <topicmeta>
      <keywords>
        <keyword id="kid">
          some text.
        </keyword>
      </keywords>
    </topicmeta>

and a topic which refers to it:

        <p><keyword conref="../../eXml/samples/dita/flowers/flowers.ditamap#kid"/></p>

When I publish that topic to PDF, the output breaks with:

       D:\projects\eXml\frameworks\dita\DITA-OT2.x\plugins\org.dita.pdf2\build.xml:136: Failed to run pipeline: Failed to process merged topics: Invalid element name. Invalid QName {}

The failure is on an "xsl:element" in the "org.dita.pdf2\xsl\common\topicmergeImpl.xsl"

This occurs because somehow the transformation considers that a DITA Map is processed instead of a DITA topic and the "topic-merge" pre-processing steps are called although it is a plain topic.

**Comment by raducoravu** [comment]
Another way to reproduce this (which was the case of the original content I obtained from the end user) is to have in the published DITA topics a link pointing to a DITA Map:

            <link href="../../../someName.ditamap" format="ditamap"/>

Of course this is a problem with the DITA content as that link will never work but again this confuses the build process to consider that a DITA Map is published and not a DITA topic.

**Comment by robander** [comment]
This (at least the conref case originally reported) is fixed in DITA-OT 3.0 with `preprocess2`. My sample set fails in 2.5.4 but builds a PDF in 3.0 (with the conref resolved).
[2840.zip](https://github.com/dita-ot/dita-ot/files/1518203/2840.zip)

I expect that PDF based transform types that use `preprocess` will still see the error in 3.0.
