### ISSUE TITLE
Producing PDF using XEP no longer works with DITA OT 3.x

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2863]
Using DITA OT 3.x to publish to PDF using XEP I get this error:

            transform.fo2pdf.xep:
                  [xep] Processing D:\projects\eXml\samples\dita\flowers/temp/pdf/oxygen_dita_temp/topic.fo to D:\projects\eXml\samples\dita\flowers\out\pdf/flowers.pdf
                  [xep] Rendering failed: XSLT 1.0 compatibility mode is not available in this configuration
                  [xep] [XEPJ003E][ERROR] XSLT 1.0 compatibility mode is not available in this configuration
            
            BUILD FAILED
            D:\projects\oxygen-dita-ot-3.x\build.xml:45: The following error occurred while executing this line:
            D:\projects\oxygen-dita-ot-3.x\plugins\org.dita.pdf2\build.xml:143: The following error occurred while executing this line:
            D:\projects\oxygen-dita-ot-3.x\plugins\org.dita.pdf2.xep\build_xep.xml:194: Java returned: 1

The error is probably caused by the fact that XEP applies internally some XSLT 1.0 processing and the new Saxon 9 HE no longer supports XSLT 1.0 compatibility mode (you need the commercial PE or EE for that).

**Comment by robander** [comment]
Not sure how to classify this one ... clearly we want to be able to work with XEP but I don't think we can downgrade the tools we ship just to keep it working. Clearly will need some discussion with @jelovirt when he's back.

**Comment by raducoravu** [comment]
Just wanted us to have some kind of record about this problem, if somebody searches for it for example. I wrote an email to somebody from XEP, see if they are interested in upgrading their processor to work again with Saxon 9 he. 
This kind of problem might also affect people with oldish plugins which have version="1.0" set on the main XSLT.

**Comment by robander** [comment]
Yes - I ran into the same issue with some of my old plugins (much of the Syntax Diagram code still declares XSLT 1.0).

**Comment by kbrown01** [comment]
I have forwarded this into RenderX support for comments and to get to a solution. Right now there are four areas in which internal XSLs may be applied:

1) folint.xsl which is used in Validation
2) preprocessor.xsl which is used to reorganize some information in SVGs for accurate processing
3) xsl11-to-rx.xsl which is used to convert (some) XSL 1.1 constructs to the old rx: extensions
4) footnote-reordering.xsl which is a switchable XSL applied when users what to reorder footnotes in specific ways

Because of 2 and 3, unless we internalize this (i.e. remove the XSL and make it code), the solution would be to go to version 2 XSLs. We will examine possible quick workarounds and post back here shortly.

**Comment by raducoravu** [comment]
You could have two sets of XSLs (1.0 and 2.0) and in the Java code you could look at the transformer you obtained via the transformer factory and if it is a Saxon 9 instance use the 2.0 ones. In this way, XEP will still work with Saxon 6.

**Comment by kbrown01** [comment]
An option. Actually I took Eclipse and the xep.jar and edited the four XSLs just changing them to 2.0. Then i ran XEP and had no issues with Saxon 6 ... I think that maybe it only throws a warning like "Running a 2.0 stylesheet with 1.0 processor" and that message is squashed. I am not sure I did it all right though and I do not have a DITA/Saxon 9 installation. If I send you that JAR, can you test it?

**Comment by raducoravu** [comment]
@kbrown01 I made the same changes on my side directly in the xep.jar I was using and I confirm I can now produce a PDF with DITA OT 3.x and XEP.
There is a set of incompatible changes between XSLT 1.0 and 2.0:

https://www.w3.org/TR/xslt20/#incompatibilities

and setting the 2.0 version in the XSLT might make it produce a slightly different output depending on how it was written. So you would still need to run some automated tests to see if you have changes in the generated FO area tree when processing various XSL-FO documents.

**Comment by raducoravu** [comment]
I'm closing this issue, just wanted to have something logged is somebody else has this problem.
If RenderX releases a new version fixing this issue maybe @kbrown01 can add details about it here.
