### ISSUE TITLE
Command line cannot properly pass file names with non-ASCII characters

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2881]
Let's say I have a DITA topic called something like "α.dita" (the Greek Alpha character) and I'm invoking the command line like this:

          dita -i D:\projects\eXml\samples\dita\flowers\topics\α.dita -f xhtml

I get this error:

           Error: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/D:/projects/eXml/samples/dita/flowers/topics/a.dita' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.

So although I passed a value containing "α.dita" the ANT build file on the other side got "a.dita".
This is probably a bug in the Java VM but I'm logging it just to have a common knowledge about this case.

**Comment by raducoravu** [comment]
This issue registered on the Java issued lists seems to list most of the issues reported on the same problem, that the on Windows the Java executable is not Unicode enabled, at least with English language:

https://bugs.java.com/view_bug.do?bug_id=8124977

**Comment by raducoravu** [comment]
Maybe a workaround would be that if the "org.dita.dost.invoker.Main.processArgs(String[])" method receives arguments which contain encoded characters using for example the URI escaping or the XML character entity encoding scheme, for example if it received "&#945;.dita" as an argument, it could unescape it to "α.dita" and then continue the processing using the un-escaped value.

**Comment by jelovirt** [comment]
You can give the input file as a URL and use [URL escaping](https://en.wikipedia.org/wiki/Percent-encoding) to escape non-ASCII characters as a workaround.

**Comment by raducoravu** [comment]
@jelovirt What you are suggesting does not work for me:

          C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.0.1\bin>dita -i file:/D:/projects/eXml/file:/D:/projects/eXml/samples/dita/flowers/tasks/%25CE%25B1.dita -f xhtml
         Error: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/D:/projects/eXml/file:/D:/projects/eXml/samples/dita/flowers/tasks/%25CE%25B1.dita' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.

and I would also somehow want to make this work without using the "dita" command, maybe have some kind of an "args.input.url" param which gets processed to assign a value to "args.input."

**Comment by raducoravu** [comment]
Actually the DITA OT project covers this because you just need to have the project file name with ascii characters but inside the project file you can refer to the XML documents using any character possible in the file names.
