### ISSUE TITLE
Images in bookmap title cause NPE and break PDF rendering wit DITA OT 3.0.1

### ISSUE THREAD

**Issue by boris-horner** [dita-ot/dita-ot#2885]
## Expected Behavior
An image in bookmap title should be displayed on the first page of the rendered PDF.

## Actual Behavior
A NPE is thrown. With DITA-OT 2.5.4, no error occurs and a correct PDF is created.

## Possible Solution
Unknown - seems to be a bug that must be fixed.

## Steps to Reproduce
[manual_test.zip](https://github.com/dita-ot/dita-ot/files/1676889/manual_test.zip)

1. `path\to\dita-ot-3.0.1\bin\dita -f pdf2 -i test.ditamap -v`

## Copy of the error message, log file or stack trace
`topic-reader:
[topic-reader] Using Xerces grammar pool for DTD and schema caching.
[topic-reader] Reading file:/C:/Users/Demo/AppData/Local/Temp/temp20180130004418366/aadcc03c12e05a7a01b6aba3ecb0be7c3526f358.ditamap
Error: java.lang.NullPointerException`

## Environment
* DITA-OT version: 3.0.1
* Operating system and version: Windows 10
* How did you run DITA-OT? dita command
* Transformation type: PDF

**Comment by xephon2** [comment]
This is no bug. To create a cover image, use a `<data>` element...

```xml
<data name="cover-image">
    <image href="cover.svg"/>
</data>
```

... or a `<topicref>`.

```xml
<topicref href="cover.dita" outputclass="front-cover" toc="no"/>
```

You will then have to process the elements in your customization plugin. The default PDF plugin does not create cover images. You should use the [dita-generator](http://dita-generator.elovirta.com/) to generate a base PDF plugin and customize it to fit your needs. If you follow the wizard, it'll create a template to process cover images for you.

**Comment by boris-horner** [comment]
Thanks for your help, but I still get the same problem.

I created this plugin
[com.texolution.test.zip](https://github.com/dita-ot/dita-ot/files/1677380/com.texolution.test.zip)

I modified the map using the data approach
[manual_test.zip](https://github.com/dita-ot/dita-ot/files/1677382/manual_test.zip)

I still get the same NPE. I tried putting the data element into various locations where it is valid according to DITA 1.2 documentation (and actually, an image directly inside mainbooktitle is also valid).

I also tested with the topic approach you mentioned. That actually creates a PDF but is quite far away from the desired output - don't know how to address the topic containing the title page in the generator...

**Comment by boris-horner** [comment]
I just downloaded OT 3.0.2 and with that, it no longer crashes with a NPE. I don't see the coverimage yet, but for that I will try the hints you gave me in your previous comment (using the data element). If I run into new problems, I'll comment on this.

**Comment by xephon2** [comment]
It is somewhat easier to use the `<data>` element approach to create cover images. If you use a `<topic>`, it is processed as a topic and is flavored with additional `<xsl:attribute-set/>` rules. This makes it much harder for you, because you have additional interferring processing.

ℹ️ You should buy and read [DITA for Print V2](https://www.amazon.de/dp/1937434540/ref=cm_sw_em_r_mt_dp_U_9oNJAbJTHTSCJ)

**Example Bookmap**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="urn:oasis:names:tc:dita:rng:bookmap.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<bookmap>
    <booktitle>
        <mainbooktitle>Title</mainbooktitle>
    </booktitle>
    <bookmeta>
        <data name="cover-image">
            <image href="my.png"/>
        </data>
    </bookmeta>
</bookmap>
```

If you have generated a plugin using the **dita-generator**, you can find the cover-processing in this file:

**my.custom.plugin\xsl\fo\front-matter.xsl**

```xml
<?xml version='1.0' encoding='utf-8'?>
<xsl:stylesheet exclude-result-prefixes="ditaarch opentopic e dita-ot opentopic-func" version="2.0" xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" xmlns:e="my.custom.plugin" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:opentopic="http://www.idiominc.com/opentopic" xmlns:opentopic-func="http://www.idiominc.com/opentopic/exsl/function" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <!--cover-->
  <xsl:template name="createFrontCoverContents">
    <fo:block xsl:use-attribute-sets="__frontmatter__title">
      <xsl:choose>
        <xsl:when test="$map/*[contains(@class,' topic/title ')][1]">
          <xsl:apply-templates select="$map/*[contains(@class,' topic/title ')][1]" />
        </xsl:when>
        <xsl:when test="$map//*[contains(@class,' bookmap/mainbooktitle ')][1]">
          <xsl:apply-templates select="$map//*[contains(@class,' bookmap/mainbooktitle ')][1]" />
        </xsl:when>
        <xsl:when test="//*[contains(@class, ' map/map ')]/@title">
          <xsl:value-of select="//*[contains(@class, ' map/map ')]/@title" />
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="/descendant::*[contains(@class, ' topic/topic ')][1]/*[contains(@class, ' topic/title ')]" />
        </xsl:otherwise>
      </xsl:choose>
    </fo:block>
    <xsl:apply-templates select="$map//*[contains(@class,' bookmap/booktitlealt ')]" />
    <fo:block xsl:use-attribute-sets="__frontmatter__owner">
      <xsl:apply-templates select="$map//*[contains(@class,' bookmap/bookmeta ')]" />
    </fo:block>
    <fo:block xsl:use-attribute-sets="image__block">
      <xsl:call-template name="e:cover-image" />
    </fo:block>
  </xsl:template>
  <xsl:template name="e:cover-image">
    <xsl:for-each select="($map//*[contains(@class, ' topic/data ')][@name = 'cover-image']/*[contains(@class, ' topic/image ')])[1]">
      <xsl:apply-templates mode="placeImage" select=".">
        <xsl:with-param name="imageAlign" select="@align" />
        <xsl:with-param name="href" select="if (@scope = 'external' or opentopic-func:isAbsolute(@href)) then @href else concat($input.dir.url, @href)" />
        <xsl:with-param name="height" select="@height" />
        <xsl:with-param name="width" select="@width" />
      </xsl:apply-templates>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
```

If you're unhappy with the appearance, this is the code snippet you need to touch/use as a starting point for your modifications.

**Comment by boris-horner** [comment]
I bought DITA for Print V2 and read the interesting sections in Google books (I will receive the printed book today). Thanks for the hint, very good book!

Maybe I'm doing something fundamentally wrong, but I still can't include the cover image, even though I get no more NPE.

My map starts like this:
``
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap id="bookmap" xml:lang="de-DE">
  <booktitle>
    <mainbooktitle>
      Handbuch EXAMPLE</mainbooktitle>
    <booktitlealt>Version vom xxx</booktitlealt>
  </booktitle>
  <bookmeta>
      <data name="cover-image">
          <image align="center" href="EXAMPLE_Titel.jpg"/>
      </data>
    </bookmeta>
  <frontmatter>
    <booklists>
      <toc />
    </booklists>
    <topicref href="foo.dita" />
  </frontmatter>
``
When I render, I get before the first page:
``
      [fop] SEVERE: Image not found. URI: file:/home/install/manual_test/dd0180d0133ce33df916b90d20969c641562272c.jpg. (See position 19:26264)
``
Setting the explicit path to the image does not help. The file is there, but of course the name is the one in the href, and not the hex number.jpg.

Commenting out the entire bookmeta element from the map removes the error message, so apparently the problem is caused by the data element or its processing.

front-matter.xsl looks like this (created by online plugin generator):
``
<?xml version='1.0' encoding='utf-8'?>
<xsl:stylesheet exclude-result-prefixes="ditaarch opentopic e dita-ot opentopic-func" version="2.0" xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" xmlns:ditaarch="http://di$
  
  <xsl:template name="createFrontCoverContents">
    <fo:block xsl:use-attribute-sets="__frontmatter__title">
      <xsl:choose>
        <xsl:when test="$map/*[contains(@class,' topic/title ')][1]">
          <xsl:apply-templates select="$map/*[contains(@class,' topic/title ')][1]" />
        </xsl:when>
        <xsl:when test="$map//*[contains(@class,' bookmap/mainbooktitle ')][1]">
          <xsl:apply-templates select="$map//*[contains(@class,' bookmap/mainbooktitle ')][1]" />
        </xsl:when>
        <xsl:when test="//*[contains(@class, ' map/map ')]/@title">
          <xsl:value-of select="//*[contains(@class, ' map/map ')]/@title" />
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="/descendant::*[contains(@class, ' topic/topic ')][1]/*[contains(@class, ' topic/title ')]" />
        </xsl:otherwise>
      </xsl:choose>
    </fo:block>
    <xsl:apply-templates select="$map//*[contains(@class,' bookmap/booktitlealt ')]" />
    <fo:block xsl:use-attribute-sets="__frontmatter__owner">
      <xsl:apply-templates select="$map//*[contains(@class,' bookmap/bookmeta ')]" />
    </fo:block>
    <fo:block xsl:use-attribute-sets="image__block">
      <xsl:call-template name="e:cover-image" />
    </fo:block>
  </xsl:template>
  <xsl:template name="e:cover-image">
    <xsl:for-each select="($map//*[contains(@class, ' topic/data ')][@name = 'cover-image']/*[contains(@class, ' topic/image ')])[1]">
      <xsl:apply-templates mode="placeImage" select=".">
        <xsl:with-param name="imageAlign" select="@align" />
        <xsl:with-param name="href" select="if (@scope = 'external' or opentopic-func:isAbsolute(@href)) then @href else concat($input.dir.url, @href)" />
        <xsl:with-param name="height" select="@height" />
        <xsl:with-param name="width" select="@width" />
      </xsl:apply-templates>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
``
Has anybody ever succeeded in rendering a cover image into the PDF using this method, and if so, may I ask for a short sample map where this actually works? I have no idea what to do to get this working.

**Comment by boris-horner** [comment]
I bought DITA for Print V2 and read the interesting sections in Google books (I will receive the printed book today). Thanks for the hint, very good book!

Maybe I'm doing something fundamentally wrong, but I still can't include the cover image, even though I get no more NPE.

My map starts like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap id="bookmap" xml:lang="de-DE">
  <booktitle>
    <mainbooktitle>
      Handbuch EXAMPLE</mainbooktitle>
    <booktitlealt>Version vom xxx</booktitlealt>
  </booktitle>
  <bookmeta>
      <data name="cover-image">
          <image align="center" href="EXAMPLE_Titel.jpg"/>
      </data>
    </bookmeta>
  <frontmatter>
    <booklists>
      <toc />
    </booklists>
    <topicref href="foo.dita" />
  </frontmatter>
```
When I render, I get before the first page:
```
[fop] SEVERE: Image not found. URI: file:/home/install/manual_test/dd0180d0133ce33df916b90d20969c641562272c.jpg. (See position 19:26264)
```
Setting the explicit path to the image does not help. The file is there, but of course the name is the one in the href, and not the hex number.jpg.

Commenting out the entire bookmeta element from the map removes the error message, so apparently the problem is caused by the data element or its processing.

front-matter.xsl looks like this (created by online plugin generator):
```
<?xml version='1.0' encoding='utf-8'?>
<xsl:stylesheet exclude-result-prefixes="ditaarch opentopic e dita-ot opentopic-func" version="2.0" xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" xmlns:ditaarch="http://di$
  <!--cover-->
  <xsl:template name="createFrontCoverContents">
    <fo:block xsl:use-attribute-sets="__frontmatter__title">
      <xsl:choose>
        <xsl:when test="$map/*[contains(@class,' topic/title ')][1]">
          <xsl:apply-templates select="$map/*[contains(@class,' topic/title ')][1]" />
        </xsl:when>
        <xsl:when test="$map//*[contains(@class,' bookmap/mainbooktitle ')][1]">
          <xsl:apply-templates select="$map//*[contains(@class,' bookmap/mainbooktitle ')][1]" />
        </xsl:when>
        <xsl:when test="//*[contains(@class, ' map/map ')]/@title">
          <xsl:value-of select="//*[contains(@class, ' map/map ')]/@title" />
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="/descendant::*[contains(@class, ' topic/topic ')][1]/*[contains(@class, ' topic/title ')]" />
        </xsl:otherwise>
      </xsl:choose>
    </fo:block>
    <xsl:apply-templates select="$map//*[contains(@class,' bookmap/booktitlealt ')]" />
    <fo:block xsl:use-attribute-sets="__frontmatter__owner">
      <xsl:apply-templates select="$map//*[contains(@class,' bookmap/bookmeta ')]" />
    </fo:block>
    <fo:block xsl:use-attribute-sets="image__block">
      <xsl:call-template name="e:cover-image" />
    </fo:block>
  </xsl:template>
  <xsl:template name="e:cover-image">
    <xsl:for-each select="($map//*[contains(@class, ' topic/data ')][@name = 'cover-image']/*[contains(@class, ' topic/image ')])[1]">
      <xsl:apply-templates mode="placeImage" select=".">
        <xsl:with-param name="imageAlign" select="@align" />
        <xsl:with-param name="href" select="if (@scope = 'external' or opentopic-func:isAbsolute(@href)) then @href else concat($input.dir.url, @href)" />
        <xsl:with-param name="height" select="@height" />
        <xsl:with-param name="width" select="@width" />
      </xsl:apply-templates>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
```
Has anybody ever succeeded in rendering a cover image into the PDF using this method, and if so, may I ask for a short sample map where this actually works? I have no idea what to do to get this working.

**Comment by boris-horner** [comment]
I did some further analysis on this issue. The image I reference in the bookmeta and that's reported as missing by fop is not contained in the file image.list in the temp folder, contrary to the other objects referenced in the body content.

Could it be that there is still an issue in the preprocessing where such references are (or should be) extracted, or am I missing some configuration? I am really stuck here, and if I can't solve this within the next couple of days, I must go back to DITA-OT 2.5.x where this (hopefully) works.

Am I really the only person using cover images in DITA-OT 3.x?

**Comment by boris-horner** [comment]
... the image file reference is already missing from .job.xml. Seems to be an issue in or before the gen-list step, it apparently fails to collect the file inside of the data element.

**Comment by boris-horner** [comment]
Since I didn't get it to work with the data element approach, I linked in a topic in the frontmatter before the booklists as suggested as "plan b" above. Whenever I start referencing the image in that topic in front-matter.xsl though, I get the same problem again, a SEVERE error message in the fop block telling me it can't find the image.

I go back to DITA OT 2.5.4 now. Either 3.x still has a bug in that area (probably in or before gen-lists) or I am doing something fundamentally wrong that I can't resolve myself. I invested almost 3 days to no avail. With 2.5.4, I get the cover image without any modifications to the map (image directly placed inside mainbooktitle element). This might not be the most elegant approach, and it's based on an outdated DITA-OT version, but at least it yields the result the customer expects. Sorry :-(

**Comment by shelden93** [comment]
Stuck with the same problem on the DITA OT 3.0.4 version. I fixed this problem in the AbstractReaderModule class by adding nonTopicrefReferenceSet to resourceOnlySet but I think it's not a good solution.

**Comment by SanFanDocu** [comment]
Tried to insert images via data elements.
OT 3.0.1 throws NPE, if href is used to reffer image. 
Processing successfull with conkeyref instead of href.

In OT 3.1 both reference types processed without NPE.
But image publising does not work. A temporary numeric filename without path is pushed into the topic.fo.

**Comment by lief-erickson** [comment]
Using DITA-OT 3.3.3 I also tried using `<data>`. I am getting the same errors reported by @boris-horner. Looking at the code from `front-matter.xsl` it seems that setting `@external` on `<image>` or using an explicit path would help, but neither do.

```xml
<bookmeta>
  <data name="cover-image">
    <image href="my.svg"/>
  </data>
</bookmeta>
```
