### ISSUE TITLE
Upgrade to Saxon-HE 9.8.0.7 to restore XSLT 1.0 support

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2887]
Saxon has apparently backtracked on their decision to abandon XSLT 1.0 support in Saxon-HE:

> **From 9.8.0.7, XSLT 1.0 backwards-compatibility mode is reinstated in Saxon-HE.** 
> In earlier versions of 9.8, this mode requires Saxon-PE or higher 
> _(that is, Saxon-HE will reject stylesheets that specify version=“1.0”)_.

— https://www.saxonica.com/html/documentation/conformance/xslt30.html

We currently ship Saxon-HE 9.8.0.5 in DITA-OT 3.0.1, but we could spare users some update grief by upgrading to 9.8.0.7 for DITA-OT 3.0.2.

This would make it easier for users with custom plug-ins that still use XSLT 1.0 syntax to upgrade to 3.x.

**Comment by robander** [comment]
Part of me thinks "everybody should upgrade because 1.0 is ancient" and part of me thinks "I really don't want to touch those old plugins if I don't have to so this would be great."

**Comment by infotexture** [comment]
👍 Exactly.

I think upgrading to Saxon-HE 9.8.0.7 now is the pragmatic approach here, since even Saxon has apparently realized how much trouble their initial approach caused.

This encouraged us to purge our own codebase of XSLT 1.0 for 3.0, but not sure how many users will be able to do that.

I suggest we add an XSLT 2.0 recommendation to the upcoming _coding conventions for plugins_ topic for dita-ot/docs#191, since Saxon still says they [hope to eliminate it entirely in due course](https://www.xml.com/news/release-saxon-98/), so users are forewarned.
