### ISSUE TITLE
News for NullPointerException in DITA OT 3.x #2828

### ISSUE THREAD

**Issue by hscherzer** [dita-ot/dita-ot#2893]
#2828 is closed but I do have new results and a potential observation on something to be fixed acc. to these results. 

I added my observations into the original (closed) thread #2828.

I don't know whether to continue right here or whether original thread shall be re-opened.  Pls. advise ... Thanks for caring ... Helmut

**Comment by jelovirt** [comment]
Open a new issue or pull request.

**Comment by hscherzer** [comment]
Thanks for the answer and I hope we agree that THIS is a new issue ... otherwise pls. help me to understand.  So I repeat my observation ... processing DITA-OT3 the issue is to receive a NullPointerException in **TopicReaderModule.java** line 169.

I had the same problem as indicated in #2828 and patched **TopicReaderModule.java** to get some more info. Finally I found that in Line 169
`if (fi == null) { fi = job.getFileInfo(tmp.resolve(href)); } assert fi != null;`
getFileInfo(....) does not find the chapters's children (the topicrefs) in the temp-directory (and they aren't there).
Further research showed that my definition of the tempdir = ${cfd}..\build\temp is THE PROBLEM because the parent notation ..\ (or /../) is not interpreted by that process that stores the topicrefs into the tempdir.

Since DITA-OT3 this process has changed because it does name mangling (changing a name of a file like "mychapter.dita" into something like "bb308a949b3f699f027435c09ca750e19ae16dce.dita" (which is perfectly OK). But the process doing that (and storing those mangled files) doesn't seem to correctly understand such ${cfd}..\build\temp parent notation as target dir and therefore does not store the topicrefs into the tempdir.

Consequently ... **getFileInfo(....)** does not find the chapters's children. And the assertion kills the process.

I could fix that with a contribution but it would be helpful to know where the topicref files are being stored (JAVA module ... function () ...), before I have to parse the full dost set.

**SOLUTION:** Do no use relative notation in the tempdir definition ... until the problem is solved. I do not consider this a severe bug, but a bit hard to find ... so I hope this contributes to some change when time is available.

Feel free to contact me under helmut.scherzer@gi-de.com I might not scan this issue often enough.

**Comment by hscherzer** [comment]
Sorry for the close ... don't know how it happened but should be open again ...

**Comment by hscherzer** [comment]
Closed, the problem didn't occur anymore in later versions.
