### ISSUE TITLE
Chapter references break with mapref

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2898]
The DITA-OT docs use `<chapter>` references in a bookmap to pull in content from submaps for the PDF output, as in [userguide-book.ditamap Line 33](https://github.com/dita-ot/docs/blob/develop/userguide-book.ditamap#L33):

```xml
<chapter href="topics/customization.ditamap" format="ditamap"/>
```

The referenced chapter submap pulls in content for each section via `<mapref>` elements, as on [Line 8](https://github.com/dita-ot/docs/blob/develop/topics/customization.ditamap#L8):

```xml
<mapref href="html-customization.ditamap"/>
```

Up to 3.0, these references worked fine, and maprefs were rendered as chapters in the ToC 
(see  `docs/userguide.pdf` in the 3.0 distribution package — ToC Page 4, Part V):
<img width="880" alt="dita-ot_mapref-ok-in-3-0" src="https://user-images.githubusercontent.com/129995/36400845-c0358a5c-15d3-11e8-94a5-358e3ce66373.png">

As of 3.0.1, these maprefs are no longer treated as chapters:
<img width="880" alt="dita-ot_mapref-error_with-mapref" src="https://user-images.githubusercontent.com/129995/36400888-0812a86e-15d4-11e8-9c2f-13590861ed69.png">

The error is apparently related to `<mapref>` processing, as it works fine if one of the maprefs is replaced with the content of the referenced map:
<img width="880" alt="dita-ot_mapref-error_no-mapref" src="https://user-images.githubusercontent.com/129995/36401040-045e57a8-15d5-11e8-847a-4751a531dda5.png">

**The issue is still present in 3.0.2.**

**Comment by infotexture** [comment]
May be a rare UNIX-only issue, as @robander was unable to reproduce on Windows, though it appears consistently on multiple macOS systems and our own UNIX-based CI servers that generate the distribution builds.

**Comment by infotexture** [comment]
@jelovirt The `hotfix/3.0.4` branch of the docs repo cannot be used to reproduce this issue, as the failing markup was removed there in [497eb66](https://github.com/dita-ot/docs/commit/497eb66) to work around the issue for the 3.0.3 release.

If you temporarily set the `docsrc` submodule pointer to the `hotfix/3.0.4` branch of the docs repo @ `747b135` and then `git revert 497eb66`, you should be able to reproduce the issue with the core repo code from the `hotfix/3.0.4` branch by running `ant pdf` in the `docsrc` folder.

**Comment by jelovirt** [comment]
I tested with `dita-ot` repo  `hotfix/3.0.4` branch  and `docs` repo `develop` branch, that still uses the nested maprefs. I did not use the docs build scripts, rather ran OT directory through Ant.

**Comment by jelovirt** [comment]
But are you able to reproduce the issue with `hotfix/3.0.4` code when running with Ant, not docs scripts?

**Comment by infotexture** [comment]
Verified with latest code from `develop`, no longer reproducible, closing.
