### ISSUE TITLE
xref with format pdf, txt, .. do not work properly in DITA OT 3.x

### ISSUE THREAD

**Issue by ritti** [dita-ot/dita-ot#2899]
## Expected Behavior

I have a dita Topic that contains file references to different formats (txt, pdf, docx, zip).
The files are located in the same Directory as the dita Topic file.
When transforming this Topic to xthml I would expect that the files are also copied to the Output Directory. 
According to the spec at least pdf and txt should be supported:
https://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part1-base/langRef/attributes/theformatattribute.html

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "ditabase.dtd">
<dita>
  <topic id="id_40a72787efc94c2a8bb6e60f8cac2b2c">
	<title>Test</title>
	<shortdesc>Test format attribute with zip, pdf, ...</shortdesc>
	<body>
		<p>
			<ul>
				<li><xref href="Test.pdf" format="pdf">pdf file</xref></li>
				<li><xref href="Test.zip" format="zip">zip file</xref></li>
				<li><xref href="Test.docx" format="docx">docx file</xref></li>
				<li><xref href="Test.txt" format="txt">txt file</xref></li>
			</ul>
		</p>
	</body>
  </topic>
</dita>
```

## Actual Behavior

With DITA OT 2.4 all files are copied to the Output Directory and the links work correctly.
With DITA OT 3.x the files are NOT copied to the Output Directory. Consequently the links do not work.

## Steps to Reproduce

1.
2.
3.

## Environment

* DITA-OT version: dita-ot 3.0.2
* Operating system and version:
 Windows
* How did you run DITA-OT?
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
```
//Xhtml with dita-ot 3.0.2
"C:\dita-ot-3.0.2\bin\dita" --input=Test.ditamap --output=out\xhtml302 --format=xhtml --temp=temp302 --logfile=log302.xml --clean.temp=no --verbose

//Xhtml with dita-ot 2.4
"C:\\dita-ot-2.4\bin\dita" --input=Test.ditamap --output=out\xhtml24 --format=xhtml --temp=temp24 --logfile=log24.xml --clean.temp=no --verbose
```

* Transformation type:
xhtml

**Comment by raducoravu** [comment]
Tested the problem with DITA OT 3.0.4, it's still there. In this case the ".job.xml" has no reference to the "Test.pdf" whatsoever.

**Comment by raducoravu** [comment]
Similar problem when in the DITA Map I have a reference to the PDF (tested using DITA OT 3.0.4):

        <topicref navtitle="PDF TITLE" href="tasks/flowers.pdf" format="pdf"/>

The .job.xml has a reference to it:

        <file src="file:/D:/projects/eXml/test/dita/transform/tasks/flowers.pdf"
            uri="tasks/flowers.pdf" path="tasks\flowers.pdf"
            result="file:/D:/projects/eXml/test/dita/transform/tasks/flowers.pdf" format="pdf"/>

but the "copy-files" target only copies images and html files by calling the "copy-image" and "copy-html" targets. 
What it should actually do would be to maybe merge the "copy-html" and "copy-images" to a target called "copy-non-dita" and copy all non-DITA resources in the same way to the output folder.

**Comment by raducoravu** [comment]
Problem persists in DITA OT 3.1. Referenced non-DITA and non-HTML files are no longer copied to the output folder.

**Comment by raducoravu** [comment]
Same problem with DITA OT 3.2. In "dita-ot-3.2\plugins\org.dita.base\build_preprocess_template.xml" the "copy-files" target depends on "copy-image" and "copy-html", how about if it would depend on a "copy-non-dita" target which copies all resources in the job.xml which do not have DITA or DITAMap format.
Otherwise we would need to add extra targets like "copy-pdf", "copy-zip" and so on.

**Comment by raducoravu** [comment]
@jelovirt what's your opinion on this?

**Comment by jelovirt** [comment]
The most simple solution would probably be to copy all resources that are not `dita`, `ditamap`, or `ditaval`.

**Comment by jelovirt** [comment]
Then it would need to be `not(dita | ditamap | ditaval)`, i.e. a custom language. Need to think what would be an alternative way to solve that.

**Comment by raducoravu** [comment]
Something like:

         <ditafileset format="dita" exclude="true"/>

which would mean copy all resources excluding the "dita" ones.
And afterwards we would join the "copy-image" and "copy-html" targets to a single "copy-other" target.

**Comment by jelovirt** [comment]
I think the most Ant-like option would be to add support for

```
<ditafileset>
  <exclude format="dita"/>
  <exclude format="ditamap"/>
  <exclude format="ditaval"/>
</ditafileset>
```
