### ISSUE TITLE
Remove obsolete <xsl:value-of> elements

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2902]
The following `<xsl:value-of>` elements should be removed, because they are either obsolete or invalid.

* [dita-utilities.xsl#L322](https://github.com/dita-ot/dita-ot/blob/develop/src/main/xsl/common/dita-utilities.xsl#L322)
* [output-message.xsl#L126](https://github.com/dita-ot/dita-ot/blob/develop/src/main/xsl/common/output-message.xsl#L126)

**Comment by xephon2** [comment]
[Oh, the `@select` attribute is optional since XSLT 2.0](https://www.data2type.de/xml-xslt-xslfo/xslt/xslt-referenz/value-of/). I missed that.

**Comment by jelovirt** [comment]
Yes, those are there for a purpose, to concat nested text nodes into a single string.
