### ISSUE TITLE
DITA-OT3\lib\dost.jar does not contain CHMIndexWriter.class

### ISSUE THREAD

**Issue by hscherzer** [dita-ot/dita-ot#2903]
## Expected Behavior
The DITA-OT3\lib\**dost.jar** does not contain CHMIndexWriter.class

This would be required to process htmlhelp (.hhk)

## Actual Behavior
Processing transtype=htmlhelp produces error
`dita.map.htmlhelp.hhk:
 [pipeline] java.lang.ClassNotFoundException: org.dita.dost.writer.CHMIndexWriter`

## Possible Solution
Add `CHMIndexWriter.class` to `dost.jar` as it was in DITA-OT2.x

## Steps to Reproduce
Compile any .ditamap with transtype=htmlhelp

* DITA-OT version: 3.0.2 (and any previous 3.0.x)

* Operating system and version:
Windows

* How did you run DITA-OT?
ANT 

* Transformation type:
htmlhelp

**Comment by raducoravu** [comment]
That particular class was moved to this JAR library:

dita-ot-3.0.2\plugins\org.dita.htmlhelp\lib

so it was moved from the dost.jar to a jar particular for that CHM plugin type.

**Comment by hscherzer** [comment]
Thanks Radu, good catch ! All works ...
