### ISSUE TITLE
PDF ignores titlealts/navtitle unless locked in map

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2904]
## Expected Behavior

Navigation titles defined in topics via `<titlealts>`/`<navtitle>` should be used in PDF bookmarks unless explicitly overridden with other navtitles that are defined and locked in the map.

In HTML this works as intended: navtitles from topic `<titlealts>` are honored without any map modifications.

## Actual Behavior

In PDF output, navtitles from topic `<titlealts>` are ignored unless the `@locktitle` attributes are set to `yes` in the map — even though the map doesn’t set any navtitles at all.

But this shouldn't be necessary: the locking mechanism should *only* be required to force-apply navtitles that are defined in the map. 

— If the map doesn't define one but the topic does, use the one from the topic.

Observed with the latest code on the `hotfix/3.0.3` branch — possibly related to recent changes in #2897.

**Comment by robander** [comment]
Fixed with #2906
