### ISSUE TITLE
Choicetable PDF header generation doesn't create description heading

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2908]
## Expected Behavior

Choicetable without a specified header in DITA generates default heading in PDF output.

## Actual Behavior
Only the choption heading is created.

## Possible Solution
There's a typo in org.dita.pdf2/xsl/fo/task-elements.xsl:
xsl:apply-templates refers to **emptyDescHd**, but template is named **emptyChdescHd**.

## Steps to Reproduce
In 2.5.4 (presumably later and earlier versions) build a PDF from DITA source with a choicetable with no specified heading row.

## Environment
* DITA-OT version: 2.5.4
* Operating system and version: NA
* How did you run DITA-OT? NA
* Transformation type: PDF

**Comment by robander** [comment]
Fixed with #2909.
