### ISSUE TITLE
PDF file is not generated in specified output location

### ISSUE THREAD

**Issue by dvint** [dita-ot/dita-ot#2910]
## Expected Behavior
PDF file generated should appear in the location specified at the command line

## Actual Behavior
I'm seeing 3 different behaviors with different inputs
- Most results are written to the directory level immediately above the one specified
- One result was written several levels above the expected location
- The last variation is a file that fails to start the clean-preprocess: with Error: java.lang.NullPointerException. I have files in the temp folder and it has content

## Possible Solution
I was using 3.0.1 when I initially discovered the problem. Going back to 2.5.2 yielded the correct results. I've also tested in 3.0.2 and the problem exists there as well.

## Steps to Reproduce

1) run any input with the OT and specify an output location.
2) results will be written above the level specified. Not sure what is triggering the other results.

## Environment

* DITA-OT version:
3.0.1 and 3.0.2
* Operating system and version:
Mac high Sierra
* How did you run DITA-OT?
Command line
* Transformation type:
custom PDF

**Comment by raducoravu** [comment]
Can you also attach a sample DITA project, maybe paste the entire command line that you use to start it? Also for the "NullPointerException" maybe attach the entire received console log output?

**Comment by tinks** [comment]
I see the same behaviour using DITA-OT version 3.0.3

## Environment

* DITA-OT version:
   3.0.3
* Operating system and version:
   Mac Sierra
* How did you run DITA-OT?
   Command line, using ant
* Transformation type:
   Standard PDF (pdf2)

## Project configuration

### Project structure

The documentation folder structure:
* build_project.xml (ant project file, see below)
* oadtech.ditamap (the master ditamap)
* main_source_folder
  * other_ditamap.ditamap
  * another_ditamap.ditamap
  * sub_source_folder_01
    * source_file_01.xml
    * source_file_02.xml
    * ...
  * sub_source_folder_02
    * source_file_03.xml
    * source_file_04.xml
    * ...
* minor_source_folder
  * source_file_05.xml
  * source_file_06.xml

### Ant project file

```
<?xml version="1.0" encoding="UTF-8" ?>

<project xmlns:dita="http://dita-ot.sourceforge.net" name="build-adtech" default="init" basedir="." >

  <property environment="env"/>

  <property file="${dita.dir}/local.properties"/>
  <property name="dita.output.dir" value="${basedir}${file.separator}out" />

  <tstamp>
    <format property="TODAY_FORMATTED" pattern="yyyy-MM-dd" />
  </tstamp>

  <echo message="The DITA base directory is ${env.DITA_INSTALLATION}"/>
  <echo message="Today's date is ${TODAY_FORMATTED}"/>

  <!-- Where is the dita installation located, set this in your environment variables with the name DITA_INSTALLATION -->
  <property name="dita.dir" location="${env.DITA_INSTALLATION}"/>

  <import file="${dita.dir}${file.separator}build.xml" />
  <property name="args.logdir" value="logs"/>

  <property name="adtech.dir" value="${basedir}"/>
  <property name="output.adtech.dir" location="${adtech.dir}${file.separator}out" />
  <property name="output.adtech.pdf.dir" location="${output.adtech.dir}${file.separator}pdf" />
  <property name="output.adtech.js.dir" location="${output.adtech.dir}${file.separator}js" />

  <target name="all" description="build the adtech documentation"/>

  <target name="adtech.del_all">
    <delete dir="${output.adtech.dir}" />
    <echo message="Deleted ${output.adtech.dir}." />
  </target>

  <target name="adtech.init">
    <mkdir dir="${output.adtech.dir}" />
    <mkdir dir="${output.adtech.js.dir}"/>
  </target>

  <target name="adtech.js" description="Generate tocjs javascript file" depends="adtech.del_all,adtech.jsweb,pulse_ug.pdf">
    <ant antfile="${dita.dir}${file.separator}build.xml">
      <property name="args.input" location="${basedir}${file.separator}oadtech.ditamap"/>
      <property name="output.file" value="${output.adtech.js.dir}${file.separator}toctree.js"/>
      <property name="transtype" value="tocjs"/>
    </ant>
    <copy todir="${output.adtech.js.dir}">
      <fileset dir="${dita.dir}${file.separator}plugins${file.separator}com.sophos.tocjs${file.separator}basefiles">
        <include name="**/*"/>
      </fileset>
    </copy>
  </target>

  <target name="adtech.jsweb" description="build the adtech content for the web" depends="adtech.init">
    <ant antfile="${dita.dir}${file.separator}build.xml">
      <property name="args.input" location="${basedir}${file.separator}oadtech.ditamap"/>
      <property name="output.dir" location="${output.adtech.js.dir}"/>
      <property name="args.css" location="${dita.dir}${file.separator}plugins${file.separator}com.sophos.tocjs${file.separator}sample${file.separator}basefiles${file.separator}sample.css"/>
      <property name="args.copycss" value="yes"/>
      <property name="transtype" value="xhtml"/>
    </ant>
    <copy file="${basedir}${file.separator}frameset.html" tofile="${output.adtech.js.dir}${file.separator}frameset.html"/>
  </target>

  <target name="pulse_ug.init">
    <mkdir dir="${output.adtech.pdf.dir}"/>
  </target>

  <target name="pulse_ug.pdf" description="build the Pulse User Guide PDF" depends="pulse_ug.init">
    <ant antfile="${dita.dir}${file.separator}build.xml">
      <property name="args.input" location="${basedir}${file.separator}oadtech${file.separator}user_guide_pulse.ditamap"/>
      <property name="transtype" value="pdf2"/>
      <property name="output.dir" location="${output.adtech.pdf.dir}"/>
      <property name="outputFile.base" value="User Guide"/>
    </ant>
  </target>
</project>
```

## Command used

Run from the top folder where the build project file is located.
`ant -f build_project.xml pulse_ug.pdf`

## Expected PDF output location

I'd expect the pdf file to be located here:
* out
  * pdf
    * User Guide.pdf

## Actual PDF output location

The file is always located at the top folder:
* out
* User Guide.pdf

## Other

I see a similar issue when building the xhmtl output. The files do end up in folders in the `out` directory, but not in the `out/js` directory as instructed.

**Comment by robander** [comment]
Pretty sure the pull request #2923 will fix the problem reported in the title. It won't do anything about the null pointer error, but at least one NPE that ended at the same point was fixed in 3.0.2 so that may be resolved already (I don't think Radu got a response to the request for samples there, so I can't try to reproduce).

**Comment by jelovirt** [comment]
@robander close this if you think #2923 fixes this.

**Comment by robander** [comment]
Marking closed - the pull request fixes the issue of PDF going to the wrong output directory. If other issues with PDF generation like the Null pointer error still exist in 3.0.3 or 3.0.4, please open another issue (ideally with a source sample) so we can track it down.
