### ISSUE TITLE
<indexterm> elements create whitespace in PDF with FOP

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2914]
## Expected Behavior

Index terms should not create whitespace.

## Actual Behavior
They create whitespace.
![screenshot_2018-03-13_12-35-50](https://user-images.githubusercontent.com/3266567/37339759-03b5a156-26bc-11e8-8d96-03a1fed82646.png)

## Possible Solution
Whitespaces are probably preserved somewhere (see also [FOP-2520](https://issues.apache.org/jira/browse/FOP-2520)), but I could not find out where this happens.

## Steps to Reproduce

1. In **topic-attr.xsl**, set a background-color in the attribute-set **div**:
    ```xml
    <xsl:attribute-set name="div">
        <xsl:attribute name="background-color">red</xsl:attribute>
    </xsl:attribute-set>
    ```
2. In **topic-attr.xsl**, set a background-color in the attribute-set **section.title**:
    ```xml
    <xsl:attribute-set name="section.title" use-attribute-sets="common.title">
        <xsl:attribute name="font-weight">bold</xsl:attribute>
        <xsl:attribute name="space-before">15pt</xsl:attribute>
        <xsl:attribute name="keep-with-next.within-column">always</xsl:attribute>
        <xsl:attribute name="background-color">green</xsl:attribute>
    </xsl:attribute-set>
    ```
3. Download [DITA-Whitespace Massacre.zip](https://github.com/dita-ot/dita-ot/files/1806701/DITA-Whitespace.Massacre.zip).
4. Publish the **map.ditamap**.

## Environment

* DITA-OT version: **2.5.4**
* Operating system and version: **Windows 10**
* How did you run DITA-OT? **dita command**
* Transformation type: **pdf2**
* PDF-Formatter: **FOP**

**Comment by robander** [comment]
Fixed with #3381
