### ISSUE TITLE
ClassCastException in org.dita.dost.index.TopicrefElement

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2920]
I got this report here:

https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=15632&p=46034#p46034

     C:\Oxygen XML Editor 19\frameworks\dita\DITA-OT2.x\plugins\org.dita.htmlhelp\build_dita2htmlhelp.xml:15: The following error occurred while executing this line:
     C:\Oxygen XML Editor 19\frameworks\dita\DITA-OT2.x\plugins\org.dita.htmlhelp\build_dita2htmlhelp.xml:139: java.lang.ClassCastException: org.dita.dost.index.TopicrefElement cannot be cast to org.dita.dost.index.IndexTerm
        at org.dita.dost.reader.DitamapIndexTermReader.endElement(DitamapIndexTermReader.java:164)
       at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
       at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.endElement(Unknown Source)
       at org.apache.xerces.impl.XMLNSDocumentScannerImplXerces.scanEndElement(Unknown Source)
      at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)

and looking at the code it seems feasible even with the code in DITA OT 3.x so at least the code should be guarded with an instanceof instead of casting the popped element directly to IndexTerm.

I managed to reproduce the problem by adding in the DITA Map an indexterm with an index see like:

     <topicref href="topics/index.dita" collection-type="sequence">
        <topicmeta>
          <keywords>
            <indexterm><index-see>see this</index-see></indexterm>
          </keywords>
       </topicmeta>

**Comment by raducoravu** [comment]
I can also reproduce the problem if inside a topic title element a similar index term is used:

      <topic....>
            <title>Flowers by S<ph><indexterm><index-see>see this</index-see></indexterm></ph>son</title>

because the title gets pulled in the DITA Map and results in the same class cast exception.

**Comment by jrhooker** [comment]
Is there a patch available for this?

**Comment by raducoravu** [comment]
The DITA OT 3.2.1 bundled with Oxygen XML Editor "OXYGEN_INSTALL_DIR\frameworks\dita\DITA-OT3.x" comes with a plugin containing various patches for the DITA OT: "plugins/com.oxygenxml.dost.patches". But the plugin will only work with this particular DITA OT 3.2.1 version.
If you need the patch for a specific DITA OT version you would need to check out the DITA OT project at that specific version then compile your patched version of the Java class "org.dita.dost.reader.DitamapIndexTermReader" based on those source Java files.
