### ISSUE TITLE
Feature request: Add new depend.process.post extension point

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2924]
This is again a topic I thought I had created an issue for long time ago, but it does not seem so. I would like to have a `depend.process.post` (after everything) extension point.

**Why**
I extract metadata from the map using the `depend.preprocess.post` extension point, so after all keys have been resolved. This metadata is stored in properties, because I use [OOPS xmltask](http://www.oopsconsultancy.com/software/xmltask/). These properties are cleared, when the processing is done. So I need to store them in a property file and load this file after the processing. This feels really crappy. It would be much more elegant to do some moving, renaming, copying, uploading with all properties available. This could be done really simple by adding a new extension point to all transtypes.

**Comment by jelovirt** [comment]
The reason why we haven't added this before is that a transtype can add this already by just adding their custom tasks after `preprocess` in their transtype's `@depends` configuration. Do you need the extension point to add it to your plugin that extends preprocessing?

**Comment by xephon2** [comment]
I need that extension point to define global processing instruction rules for all plugins, even those that are not maintained by myself, e.g. **com.elovirta.ooxml** or **com.oxygenxml.webhelp**. I handle those plugins as black boxes.

**Comment by jelovirt** [comment]
This is something that would need to be added to every `dita2<transtype>` task separately, and we only control the built-in transtypes. An alternative solution would be to rewrite the `@depends` attributes during integration, but we only process template files, and not all entry point tasks are in those template files. So I can't come up with a way to implement this so that it works for all transtypes.

**Comment by xephon2** [comment]
Maybe this could be implemented with `@extensionOf`:

```xml
<target name="dita2docx.post" extensionOf="dita2docx">
   ...
</target>
```

**Comment by xephon2** [comment]
@robander, you're right. I even upvoted Shane's request, which was opened two years before mine. Also funny that _years_ is a word that occurs quite often when speaking about periods and the toolkit. ;)

**Comment by stefan-jung** [comment]
@raducoravu has suggested in https://github.com/orgs/dita-ot/discussions/4531 to use the `depend.preprocess.clean-temp.pre` extension point.
