### ISSUE TITLE
Table rowheader does not take into account cells spanning more rows

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2942]
If I have a DITA topic containing a table like this:

       <table frame="none" rowheader="firstcol">
                <title>Flowers</title>
                <tgroup cols="3">
                    <colspec colname="c1" colnum="1" colwidth="171.0pt"/>
                    <colspec colname="c2" colnum="2" colwidth="99.0pt"/>
                    <colspec colname="newCol3" colnum="3" colwidth="200px"/>
                    <thead>
                        <row>
                            <entry>Flower</entry>
                            <entry>Type</entry>
                            <entry>Soil</entry>
                        </row>
                    </thead>
                    <tbody>
                        <row>
                            <entry morerows="2">Chrysanthemum</entry>
                            <entry>perennial</entry>
                            <entry>well drained</entry>
                        </row>
                        <row>
                            <entry>perennial</entry>
                            <entry>acidic</entry>
                        </row>
                        <row>
                            <entry>annual</entry>
                            <entry>sandy, well-drained</entry>
                        </row>
                    </tbody>
                </tgroup>
            </table>

and I publish to PDF, because the attribute (rowheader="firstcol") is specified on the table, only the "Chrysanthemum" cell should be bold. No other cell should be bold because this particular cell spans over two other lines. But for the PDF output both the "perennial" and "annual" cells will be shown as bold.
The XHTML output seems to work properly.
Tested with both DITA OT 2.x and 3.x.

**Comment by raducoravu** [comment]
As a possible workaround in the XSLT:

          plugins\org.dita.pdf2\xsl\fo\tables.xsl

there is a check like:

          <xsl:when test="ancestor::*[contains(@class, ' topic/table ')][1]/@rowheader = 'firstcol'
                        and empty(preceding-sibling::*[contains(@class, ' topic/entry ')])">

which can be replaced with:

            <xsl:when test="ancestor::*[contains(@class, ' topic/table ')][1]/@rowheader = 'firstcol'
                and @dita-ot:x = '1'">

because that's how the HTML-based output XSLTs handle the same situation.

**Comment by robander** [comment]
Thanks for the pointer, I created a pull request using that fix.

**Comment by infotexture** [comment]
Resolved in #2946.
