### ISSUE TITLE
build preprocess target name="copy-files" unless="preprocess.copy-files.skip" does not work as expected.

### ISSUE THREAD

**Issue by leesmith2** [dita-ot/dita-ot#2954]
https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml
```
 <!-- copy-files
      Copy files to the output directory. -->
  <target name="copy-files"
    dita:depends="{depend.preprocess.copy-files.pre},copy-image,copy-html,copy-flag"
    dita:extension="depends org.dita.dost.platform.InsertDependsAction"
    unless="preprocess.copy-files.skip" />
```

## Expected Behavior
You would expect that the copy-files target is skipped if you set preprocess.copy-files.skip, right?

## Actual Behavior
But the preprocess.copy-files.skip skips only the contents of the copy-files target.  But it is an empty target anyway. 
Because the copy-flag has a more detailed skip, it also influences copy-flag. 
But copy-image and copy-html are executed anyway.

## Possible Solution
Imitate <target name="copy-flag-check"> for copy-image and copy-html

**Comment by jelovirt** [comment]
This is unfortunately not how Ant works. Using `@unless` in `<target>` will only skip the contents of the target, but it will always run the dependent targets. Right now we don't have anything inside `copy-files` target, so the guard condition will actually never do anything. The reason for having that guard condition is _probably_ for backwards compatibility, but I'm not sure.

Closing this as works as expected (but unfortunately not as desired.)
