### ISSUE TITLE
table top border displayed wrongly

### ISSUE THREAD

**Issue by shidmei** [dita-ot/dita-ot#2959]
Hi, 
I'm using dita-ot 3.0.3 and I'm generating a pdf.

I have a table of which the border is displayed wrongly if the previous column has a column span.
Please see this example:
![3border](https://user-images.githubusercontent.com/13753977/39986458-500168d4-5794-11e8-8618-c923f8bca2f5.png)

And the output is wrong.
![1border](https://user-images.githubusercontent.com/13753977/39986432-34d995fe-5794-11e8-9625-d254a5fd706c.png)
And in tables.xsl, I found this line, entryNum variable that contains the wrong value.  It's referring to previous sibling entry BUT previous siblings having column span which is not counted. The entryNum variable here has a value of 4 but it should be 3 as there's column span on previous column.

![2border](https://user-images.githubusercontent.com/13753977/39986453-495b4d06-5794-11e8-9782-c42a68e31199.png)

I tested on the sample file installing.dita with these codes:

`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">

<topic id="installing" xml:lang="en-us">
  <title>Installing</title>
  <shortdesc>You install components to make them available for your solution.</shortdesc>
  <body>
    <p>Testing table </p>
    <table frame="topbot">
      <tgroup cols="6" align="center">
        <colspec colname="c1" colnum="1" colwidth="30%" colsep="0" rowsep="0"/>
        <colspec colname="c2" colnum="2" colwidth="10%" colsep="0" rowsep="0"/>
        <colspec colname="c3" colnum="3" colwidth="10%" colsep="0" rowsep="0"/>
        <colspec colname="c4" colnum="4" colwidth="30%" colsep="0" rowsep="0"/>
        <colspec colname="c5" colnum="5" colwidth="10%" colsep="0" rowsep="0"/>
        <colspec colname="c6" colnum="6" colwidth="10%" colsep="0" rowsep="0"/>
        <tbody>
          <row rowsep="0">
            <entry rowsep="0">Treatment</entry>
            <entry namest="c2" nameend="c3" rowsep="1">Replicate</entry>
            <entry rowsep="0">Treatment</entry>
            <entry namest="c5" nameend="c6" rowsep="1">Replicate</entry>
          </row>
          <row rowsep="1">
            <entry>Combination</entry>
            <entry>I</entry>
            <entry>II</entry>
            <entry>Combination</entry>
            <entry>I</entry>
            <entry>II</entry>
          </row>
          <row rowsep="0">
            <entry>(1)</entry>
            <entry>90</entry>
            <entry>93</entry>
            <entry><i>d</i></entry>
            <entry>98</entry>
            <entry>95</entry>
          </row>
          
        </tbody>
      </tgroup>
    </table>
  </body>
  
</topic>`

Attached is the testing file.

[installing.txt](https://github.com/dita-ot/dita-ot/files/1999945/installing.txt)

Please advise.
Thank you.

**Comment by shidmei** [comment]
Can anyone fix this table border bug?  Thank you.

**Comment by shidmei** [comment]
HI @drmacro , thank you so much for looking into the matter.  May I know if this solution will be implemented in future dita-ot version/release, as for my current example, the table border really isn't displaying correctly.
Thank you.

**Comment by drmacro** [comment]
Given the degree to which we all hate the PDF2 transform and the fact that we are all volunteers and the fact that there are probably 100s of existing customizations based on the current code it is probably highly unlikely that such a change would be made to the base PDF2 transform.

I have done it for specific cases in the context of paid engagements and it's not too hard to override things in an ad-hoc way to get the effect you need. However, a more general solution is a lot more work because it has to handle all the cases.
