### ISSUE TITLE
If relcolspec titles are specified, related links are no longer properly merged at end of topic

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2966]
I'm attaching a sample DITA project:

[rellinksNotMerging.zip](https://github.com/dita-ot/dita-ot/files/2022503/rellinksNotMerging.zip)

The DITA Map looks like this:

             <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
            <map>
                <title>TEST-reltable</title>
                <topicref id="fA" href="function_a.dita" keys="fA" />
                <topicref id="fB" href="function_b.dita" keys="fB" />
                <topicref id="C1" href="common_1.dita" keys="C1" />
                <topicref id="C2" href="common_2.dita" keys="C2" />
                <reltable>
                    <relheader>
                        <relcolspec><title>Function</title></relcolspec>
                        <relcolspec><title>Reference</title></relcolspec>
                        <relcolspec><title>Usage</title></relcolspec>
                    </relheader>
                    <relrow>
                        <relcell><topicref keyref="fA" /></relcell>
                        <relcell><topicref keyref="C1" /></relcell>
                        <relcell><topicref keyref="C2" /></relcell>
                    </relrow>
                    <relrow>
                        <relcell><topicref keyref="fB" /></relcell>
                        <relcell><topicref keyref="C1" /></relcell>
                        <relcell><topicref keyref="C2" /></relcell>
                    </relrow>
                </reltable>
            </map> 

After generating with DITA OT 3.0.4 the HTML output for "C1=>common_1.html" it will contain at the end two duplicate links, both pointing to "C2=>common_2.dita".
If the titles are removed from the relcolspecs, then the links are de-duplicated properly when the HTML output is constructed.

**Comment by fviolette** [comment]
Thanks Radu for raising this issue :+1:

**Comment by fviolette** [comment]
Just to put things in perspective: we use relationship tables in HTML output without any XSL customization - because the DITA-OT opinionated output suites us very well. We handle everything else in the browser with pseudo elements and the like.

That's already bad practice, but, with this bug, we need to hide elements (<strong>, <br>) and fiddle with the tilde (~) CSS selector to count the tables and override the labels. Fortunately, we generate the relationship tables upstream and we only have one doc set that have such related links, but it is not going to scale.

**Comment by raducoravu** [comment]
In the XSLT "dita-ot-3.1\xsl\common\related-links.xsl" there is a key called "hideduplicates" and a function called "related-links:hideduplicates". But the key is applied only if the link is not a child of a  "linklist". Because the relcolspec titles will result in "linklist"'s with links inside, the duplicates minimization will not work anymore.

**Comment by raducoravu** [comment]
Received a report for a similar situation:

https://www.oxygenxml.com/forum/topic16794.html

Once the relcolspecs have titles, the first topic HTML document will have two "Related information" categories at the end.

[relatedtopicsissue.zip](https://github.com/dita-ot/dita-ot/files/2159209/relatedtopicsissue.zip)
