### ISSUE TITLE
Long-form --logfile option throws error

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2968]
## Expected Behavior

Both the `dita` command help and docs suggest that either the long-form `--logfile` or the `-l` short option can be passed to the `dita` command to write log output to a file.

`dita --help`:
>   -l, --logfile=\<file>        use given file for log

https://www.dita-ot.org/dev/parameters/parameters-base.html
> To write the log to a file, use dita --logfile=file

## Actual Behavior

When  the long-form `--logfile` option is passed to the `dita` command, the following error appears and no output is generated:

        Error: Error: Unknown argument: /path/to/dita-ot/src/main/build.xml

_(Note duplicate `Error: Error:` reference)_

## Steps to Reproduce

1. `dita --input=userguide-book.ditamap --format=pdf --logfile=logfile.txt` 

        Error: Error: Unknown argument: /path/to/dita-ot/src/main/build.xml

2. `dita --input=userguide-book.ditamap --format=pdf -l logfile.txt`
    _(output is generated as expected and messages are written to the specified log file)_

## Environment

* DITA-OT version: `develop` @ 4cee2e4 
* Operating system and version: macOS 10.12.6
* How did you run DITA-OT? `dita` command

**Comment by xephon2** [comment]
This is probably a duplicate of #2849

**Comment by infotexture** [comment]
Indeed, should've checked for existing issues before opening this, thanks for the reference.

I'll close this as a duplicate and update #2849 accordingly.
