### ISSUE TITLE
Files renamed via dvrResourcePrefix/Suffix still copied to output

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2980]
Tested using DITA OT 3.0.4
If in my DITA Map I have a dvrResourcePrefix:

      <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
      <map title="Growing Flowers">
        <ditavalref href="test.ditaval">
          <ditavalmeta>
            <dvrResourcePrefix>abc_</dvrResourcePrefix>
          </ditavalmeta>
        </ditavalref>
        <topicref href="topics/introduction.dita">

and I generate HTML 5 output in the output folder besides the "topics/abc_introduction.html" you will also get the "topics/introduction.html" although in my opinion this should no longer be copied to the output folder.

**Comment by infotexture** [comment]
Per https://github.com/dita-ot/dita-ot/issues/1998#issuecomment-131033096: 

> the code doesn't remove the original file from job configuration if all occurrences are renamed

### Example from DITA-OT docs

- The [using-dita-command.dita](https://github.com/dita-ot/docs/blob/develop/topics/using-dita-command.dita) file is filtered once for novice audiences on [Lines 10–22 of installing.ditamap](https://github.com/dita-ot/docs/blob/develop/topics/installing.ditamap#L10-L22) and published as [first-build-using-dita-command.html](http://www.dita-ot.org/dev/topics/first-build-using-dita-command.html).
- The same topic is re-filtered for expert audiences on [Lines 7–18 of publishing.ditamap](https://github.com/dita-ot/docs/blob/develop/topics/publishing.ditamap#L7-L18) and published as [build-using-dita-command.html](http://www.dita-ot.org/dev/topics/build-using-dita-command.html).
- The unfiltered topic is still copied to the output as [using-dita-command.html](http://www.dita-ot.org/dev/topics/using-dita-command.html) although it is not referenced anywhere else.

**Comment by Schelmenzunft** [comment]
Customers started to blame us about these not referenced topics they get using webhelp search. I had to change our dvrResourcePrefix from "strasse_" and "bahn_" to "strasse" and "bahn and adding a leading underscore to the original files (Oxygen refactoring was of great help, but it had to be done manually for 412 topis), so that by putting a "topics/_*" in a search.exclude file these go not into the search index. They still get copied to the html output though ...
