### ISSUE TITLE
Override of map2html5-coverImpl.xsl in HTML5 plugin

### ISSUE THREAD

**Issue by Nico-Amplexor** [dita-ot/dita-ot#2981]
## Expected Behavior
Extension point `<feature extension="dita.xsl.html5.cover" file="xsl/map2html5-coverImpl.xsl"/>` (in plugin.xml) permit to override templates present in map2html5-coverImpl.xsl.

## Actual Behavior
Actually I try, via dita.xsl.html5.cover extension point, to override template `<xsl:template match="*[contains(@class, ' map/map ')]" mode="chapterBody">` present in map2html5-coverImpl.xsl.
But I can't see modifications made in my custom stylesheet in HTML5 output,.

## Steps to Reproduce

1. Create a custom HTML5 plugin
2. Add dita.xsl.html5.cover extension point in plugin.xml to override xsl/map2html5-coverImpl.xsl
3. Make modifications on `<xsl:template match="*[contains(@class, ' map/map ')]" mode="chapterBody">` in custom map2html5-coverImpl.xsl
4. Run HTML5 transformation

## Environment

* DITA-OT version: 3.0.4
* Operating system and version: Windows 10
* How did you run DITA-OT? : Oxygen
* Transformation type: HTML5

**Comment by Apollo102** [comment]
In OT 3.4 I still have the problem. When I switched from 2.5.4 I wanted to try to implement the correct way. I can't overwrite the template `<xsl:template match="*[contains(@class, ' map/map ')]" mode="chapterBody">` in xsl/map2html5-coverImpl.xsl via the dita.xsl.html5.cover extension point.
