### ISSUE TITLE
Attribute @if is deprecated. Use attribute @if:set instead

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2996]
Using DITA OT 3.1, for some build files included in the DITA OT I get the warning specified in the subject.

For PDF:

```
file:/D:/projects/oxygen-dita-ot-3.x/plugins/org.dita.pdf2/build.xml:292:15: [DOTA014W][WARN] Attribute @if is deprecated. Use attribute @if:set instead.
```

For HTML5:

```
file:/D:/projects/oxygen-dita-ot-3.x/plugins/org.dita.html5/build_dita2html5.xml:199:71: [DOTA014W][WARN] Attribute @if is deprecated. Use attribute @if:set instead.
```

For XHTML:

```
file:/D:/projects/oxygen-dita-ot-3.x/plugins/org.dita.xhtml/build_general.xml:128:17: [DOTA014W][WARN] Attribute @if is deprecated. Use attribute @if:set instead.
```

**Comment by infotexture** [comment]
For custom plug-ins, the docs describe migration steps in [Migrating to release 3.1](https://www.dita-ot.org/dev/topics/migrating-to-3.1.html).

Are you seeing this for builds that use only default plug-ins?

**Comment by raducoravu** [comment]
These are not custom plugins, they are the regular plugins for producing PDF, XHTML and HTML5

**Comment by raducoravu** [comment]
Is this warning about using "if" on an ANT target or on a "param"? If it's only the latter than indeed I think I have some older plugins which contribute params and are responsible for this. The warning is not precisely reported so I'm not sure to what it refers. But if it's only for params, then indeed this is something I need to do on my side.

**Comment by jelovirt** [comment]
It's on the `param` elements. On `target` you still have to use `@if`.
