### ISSUE TITLE
Why is the documentation shipped with the builds?

### ISSUE THREAD

**Issue by SMillerDev** [dita-ot/dita-ot#2998]
Just wondering what the reason is to basically ship example data with the release archive.

**Comment by infotexture** [comment]
This can be used to verify the installation and allows users with custom plug-ins to extend the docs with the full list of parameters and extension points that are valid in their specific environment as described in [Rebuilding the DITA-OT documentation](http://www.dita-ot.org/dev/topics/rebuilding-the-dita-ot-documentation.html).

For support questions, please use the community support channels listed in the [SUPPORT file](https://github.com/dita-ot/dita-ot/blob/develop/.github/SUPPORT.md).
