### ISSUE TITLE
Relative path in <nextcatalog>

### ISSUE THREAD

**Issue by Nico-Amplexor** [dita-ot/dita-ot#3001]
## Expected Behavior
I would like to reference catalog of a custom plugin (first) in another inherit custom plugin (second) using `<nextcatalog>` in catalog.xml with a relative path : 
`<nextCatalog  catalog="../../first.pdf/cfg/catalog.xml" />`

## Actual Behavior
If I use a relative path in nextcatalog (`<nextCatalog  catalog="../../first.pdf/cfg/catalog.xml" />`) I have the following error : 

> Apache resolver library found, xml-commons resolver will be used
>      [xslt] Failed to process C:\Temp\NDE\temp\stage1.xml
>   [antcall] Exiting C:\PROJETS\Landis-Gyr\dita-ot-2.5.4\build.xml.
>   [antcall] Exiting C:\PROJETS\Landis-Gyr\dita-ot-2.5.4\build.xml.
> Error: The following error occurred while executing this line:
> C:\dita-ot-2.5.4\plugins\org.dita.pdf2\build.xml:276: java.lang.reflect.InvocationTargetException

If I use an explicit path in next catalog (`<nextCatalog  catalog="c:/dita-ot-2.5.4/plugins/first.pdf/cfg/catalog.xml" />`) it works.

## Steps to Reproduce

1. Create a first plugin
2. Create a second plugin which reference first plugin catalog through a relative path in `nextcalalog`. 

## Copy of the error message, log file or stack trace
> Apache resolver library found, xml-commons resolver will be used
>      [xslt] Failed to process C:\Temp\NDE\temp\stage1.xml
>   [antcall] Exiting C:\PROJETS\Landis-Gyr\dita-ot-2.5.4\build.xml.
>   [antcall] Exiting C:\PROJETS\Landis-Gyr\dita-ot-2.5.4\build.xml.
> Error: The following error occurred while executing this line:
> C:\dita-ot-2.5.4\plugins\org.dita.pdf2\build.xml:276: java.lang.reflect.InvocationTargetException

## Environment
* DITA-OT version: 2.5.4
* Operating system and version: Windows
* How did you run DITA-OT? `dita` command
* Transformation type: custom PDF2

**Comment by infotexture** [comment]
Have you tried using the `dita.plugin.plugin-id.dir` property instead of a relative path?

See [Plug-in coding conventions](http://www.dita-ot.org/dev/topics/plugin-coding-conventions.html).

**Comment by Nico-Amplexor** [comment]
I try different ways, but nothing works:

- ` <nextCatalog  catalog="dita.plugin.first.pdf.dir/cfg/catalog.xml" />`
- ` <nextCatalog  catalog="plugin:first.pdf:cfg/catalog.xml" />`
- ` <nextCatalog  catalog="${dita.plugin.first.pdf.dir}/cfg/catalog.xml" />`

**Comment by jelovirt** [comment]
Using the plugin URI scheme will not work in catalogs, because the XML Catalog Resolver library we use doesn't support custom URI resolvers.

**Comment by Nico-Amplexor** [comment]
Ok, but is there a way to use relative path in nextcatalog?

**Comment by jelovirt** [comment]
@Nico-Amplexor have you tried with DITA-OT 3.x, can you still reproduce the issue with that?

**Comment by Nico-Amplexor** [comment]
@jelovirt  I have the same problem with DITA-OT 3.x

**Comment by raducoravu** [comment]
@Nico-Amplexor Can you run the "dita" command with "-d" and "-v" ? Maybe the stack trace for that java.lang.reflect.InvocationTargetException will be fully printed.
You said you want to refer from the "catalog.xml" of one PDF plugin to another plugin's catalog.xml. Why? Don't both plugins contribute their "catalog.xml" to the main DITA OT catalog?
What extension points are you using in your plugin.xml's to contribute the XML catalogs? dita.specialization.catalog.relative or dita.specialization.catalog?
Can you maybe try to create a ZIP with both PDF plugins and attach it to the open issue? Or create two sample PDF plugins similar to what you have and attach them to the issue...

**Comment by skulle** [comment]
I have the same issue. In one of our plugins an ANT build uses a xslt task which fails because DTDs are unknown. This was solved rather ugly. 

Now, I introduced a xml catalog file in this plugin which has an entry like this
 `<nextCatalog catalog="file:///C:/.../org.dita.base/catalog-dita.xml"/>`
This works for test purposes, however I need to replace the full path with a relative path but couldn't manage. 
Is there a way to do this or to provide the org.dita.base/catalog-dita.xml to xslt tasks in a plugin's build file? Any help or link to example/documentation is welcome. I already googled but currently i am stuck.

**Comment by skulle** [comment]
Well that is just typical. I found a solution right now. :)
I wrap the the xslt task in ANT with dita-ot's pipline element. Then i just add a reference to dita-ots xml catalog: (previously i used the wrong reference)

		<pipeline>
			<xslt in="xxx" out="xxx" style="my.xsl">
				<xmlcatalog refid="dita.catalog"></xmlcatalog>
			</xslt>
		</pipeline>

**Comment by raybiss** [comment]
Hi,

Try adding an xmlcatalog and referencing it in the xslt transformation.

        <xmlcatalog id="dita.catalog">
            <catalogpath>
                <fileset dir="${dita.dir}" includes="**/catalog.xml"/>
                <fileset dir="${dita.dir}" includes="**/catalog-dita.xml"/>
            </catalogpath>
        </xmlcatalog>

        <xslt processor="trax" style="..." in="${args.input}" out="...">
            <xmlcatalog refid="dita.catalog"/>
        </xslt>

It fixed a similar problem I was having.

Regards,
Raymond


________________________________

**Comment by skulle** [comment]
Hi Raymond,

that solved my problem :)

Thank you for the quick help.

Best regards,
Sven
