### ISSUE TITLE
Better PDF styling for DITA "lq"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3009]
The DITA "lq" element is styled in the HTML output by having some horizontal indent before it but for the PDF output there is no particular styling for it, it looks like a plain paragraph.
The template matching "topic/lq" is in "plugins\org.dita.pdf2\xsl\fo\topic.xsl", maybe it could have a custom attribute set defined to at least add some indentation to the left.

**Comment by robander** [comment]
Agreed it should have some indent by default (that's the default presentation of HTML5 `<blockquote>` and the expected rendention based on [DITA's definition of `lq` in 1.3](https://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/langRef/base/lq.html): 
> Although rendering is left up to implementations, processors generally render <lq> as an indented block.

There is already a defined attribute set `lq` that should be used for this, but the attribute set is not called from the `fo:block` that wraps the quote, so adding an indent to that attribute set won't do anything.
