### ISSUE TITLE
Change copyrights in org.dita.pdf2 plugin folders

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3018]
There are 3 XSLTs:

org.dita.pdf2.axf\xsl\fo\index_axf.xsl
org.dita.pdf2.axf\cfg\fo\attrs\index-attr_axf.xsl
org.dita.pdf2.axf/cfg/fo/attrs/tables-attr_axf.xsl
org.dita.pdf2.axf/cfg/fo/attrs/toc-attr_axf.xsl

which seem to have a comment with AntennaHouse copyright at the beginning of the file.

There are lots of other XSLTs with Copyright by Idiom Technologies.

Maybe we can change the comments to have IBM copyright or remove the comments completely.

**Comment by jelovirt** [comment]
Those files have been originally written by Idiom Technologies or AntennaHouse and we can't change the original copyright.

**Comment by raducoravu** [comment]
@jelovirt  Maybe at the end of each comment for those AH provided XSLTs we could prepend:

       This file is part of the DITA Open Toolkit project. 
       See the accompanying LICENSE file for applicable license.

as this seems to be done for the other XSLTs.
