### ISSUE TITLE
[PDF] Index terms create extra space between section title and content

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3042]
Reported here:
https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=16970&p=48639#p48639

Let's say we have this DITA topic:

```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="introduction">
  <title>Introduction</title>
  <body>
    <section>
      <title>test section</title>
      <indexterm>flowers
        <indexterm>summer</indexterm></indexterm>
      <p>some text for the test section</p>
    </section>
  </body>
</topic>
```

which has some indexterms between the title and the paragraph in the section.

When publishing it to PDF using Antenna House or RenderX XEP the following equivalent XSL-FO output is generated:

```xml
<fo:block space-before="0.6em">
  <fo:block font-weight="bold" 
            keep-with-next.within-column="always" 
            space-before="15pt" 
            line-height-shift-adjustment="disregard-shifts" 
            font-family="Helvetica, Arial Unicode MS, Tahoma, Batang, SimSun">test section
  </fo:block>
  <fo:inline index-key="flowers:"/>
  <fo:inline index-key="flowers:summer:"/>
  <fo:block space-after="0.6em" 
            space-before="0.6em" 
            text-indent="0em">some text for the test section
  </fo:block>
</fo:block>
```

Those `<fo:inline index-key="flowers:"/>` add extra spacing when publishing using Antenna House so they should be replaced with `fo:wrapper`.

When publishing using Apache FOP, the constructed XSL-FO already has `fo:wrapper` elements there, but because of a bug in FOP the fo:wrappers also take vertical space, but that's another story: https://github.com/dita-ot/dita-ot/issues/2455

**Comment by raducoravu** [comment]
The XSLT stylesheet "plugins/org.dita.pdf2/xsl/fo/index.xsl' is the place where those fo:inline elements with the @index-key attribute are emitted.

**Comment by robander** [comment]
Sounds like the `fo:inline` is actually preferred in FOP to work around the known issue? In that case maybe the default should use `fo:wrapper` but the FOP plugin should override that to keep `fo:inline`.

**Comment by raducoravu** [comment]
The FOP plugin already somehow overrides this XSLT template, as it has no support for "@index-key" it already adds fo:wrappers with IDs, so when generating the XSL-FO for using with Apache FOP, fo:wrappers are generated, when generating XSL-FO for using with XEP and AH those fo:inline's are generated and they should probably be fo:wrapper.

**Comment by xephon2** [comment]
This may be related to #2914

**Comment by infotexture** [comment]
The corresponding FOP code comes from [org.dita.pdf2.fop/xsl/fo/index_fop.xsl#L42-L44](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2.fop/xsl/fo/index_fop.xsl#L42-L44), which was refactored for 2.2 with #2098 to:

```xml
<xsl:template match="opentopic-index:refID" mode="make-wrapper">
  <fo:wrapper id="{opentopic-func:get-unique-refid-value(.)}"/>
</xsl:template>
```

Changing that template to use `fo:inline` instead has no effect, as the empty inline/wrapper that is created on the page where the index entries appear is still surrounded by a spurious `fo:block`:

```xml
<fo:block space-after="0.6em" space-before="0.6em">
  <fo:wrapper id="locale:_unique_d80e7783"/>
</fo:block>
```

Not sure how to prevent that. ☝️ 

Perhaps @eerohele or @robander know?
