### ISSUE TITLE
dita-ot-3.1.2+5a45620 Won't pull in ditamap

### ISSUE THREAD

**Issue by wbrisett** [dita-ot/dita-ot#3053]
## Expected Behavior
When I was testing the latest dev build, I found it would not pull in the bookmap. When I switched to version 3.1.1, it worked properly. 

## Actual Behavior
Error: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/Users/waybri01/Documents/output/wb_registers/izr1532634556645.ditamap' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.

My actual command: 
dita -i /Users/waybri01/Documents/output/wb_registers/izr1532634556645.ditamap -f markdown_gitbook -o /Users/waybri01/Documents/output/wb_registers/markdown_gitbook/ 
Error: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/Users/waybri01/Documents/output/wb_registers/izr1532634556645.ditamap' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.
c02t508lhf1t:~ waybri01$ dita --version
DITA-OT version 3.1.2

Switching back to 3.1.1 worked...
dita --version
DITA-OT version 3.1.1
waybri01$ dita -i /Users/waybri01/Documents/output/wb_registers/izr1532634556645.ditamap -f markdown_gitbook -o /Users/waybri01/Documents/output/wb_registers/newgitbook/

## Environment

* DITA-OT version: 3.1.2
* Operating system and version:
Mac OS X
* How did you run DITA-OT?
 dita command
* Transformation type:
markdown_gitbook / any type of markdown

**Comment by raducoravu** [comment]
@wbrisett Do you have a small DITA project to exemplify this? Do you possibly have a DITA DTD specialization plugin which you forgot to integrate in the newer DITA OT?

**Comment by wbrisett** [comment]
Sorry Radu, got tied up with thing. I have no specializations this was the stock builds in both cases. I found it odd only in that the latest dev build wouldn't pull in the topics, but going back to released public build did.

**Comment by jelovirt** [comment]
Closed as inactive
