### ISSUE TITLE
DITA to various flavors of CommonMark/Markdown

### ISSUE THREAD

**Issue by wbrisett** [dita-ot/dita-ot#3054]
In DITA tables we have a lot of flexibility. For example, we can do this: 

```
<entry colname="col3">
	<p>Generic text here.</p>
	<p>More generic text here. </p>
	<dl compact="yes"">
		<dlentry>
			<dt>0</dt>
			<dd><p>There's a lot going on here.</p></dd>
		</dlentry>
		<dlentry>
			<dt>1</dt>
			<dd><p>More content is placed here.</p></dd>
		</dlentry>
	</dl>
	<p>More explanation goes here.</p>
</entry>

```
## Expected Behavior
To be fair, this falls within the CommonMark/Markdown limitations. But what I would hope to get out is a table with some representation of that data. However, that's not what happens. I end up with a table entry that has the first paragraph item in it, then the table pretty much breaks at that point and the remaining content is placed in the file, but not in the table.

## Possible Solution

Multiple lines are extremely hard to deal with in Markdown tables. In fact, the only solution I know of is to make tables HTML tables instead of MD text. 

## Steps to Reproduce
 See my example code. 

## Environment

* DITA-OT version: 3.1.1
* Operating system and version: Mac OS X
* How did you run DITA-OT? dita command. 
 
* Transformation type:
markdown (all flavors)

**Comment by jelovirt** [comment]
This feature request should be opened at https://github.com/jelovirt/org.lwdita/, the repository for the LwDITA plugin. DITA-OT only bundles the LwDITA plugin.
