### ISSUE TITLE
Add option --update as alternative to --uninstall/--install

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#3070]
## Expected Behavior

Can install a new version of an already-installed plugin using a single `dita` action without having to first delete the plugin's directory from the OT installation.

## Actual Behavior

`--install` fails if plugin is already installed.

Must first run `--uninstall` or manually delete the plugin's directory.

However, if you are uninstalling a plugin on which other plugins depend, you get messages about being unable to load those other plugins, which are accurate but unhelpful in this case.

## Possible Solution

Provide new action, "update" (or whatever name is most appropriate) that installs a plugin that is already installed, or alternatively, provide an additional command flag like "force-update" or something (but I think a separate action would be clearer).

Ideally, could provide a list of plugins to be installed or updated, which would allow installing plugins in dependency order.

## Steps to Reproduce

1. Given a Zip file containing a plugin, run `dita --install {path-to-zip}`. Install should succeed
2. Run same command again, it should fail with "Plugin already installed" message

## Environment

* DITA-OT version:

    * 2.5.4
    * 3.1.2

**Comment by infotexture** [comment]
Implemented in #3120.
