### ISSUE TITLE
Installing elovirta pdf custom plugin

### ISSUE THREAD

**Issue by jcglegs** [dita-ot/dita-ot#3074]
DITA OT 3.0.1 FM 2019 elovirta plug-in

Generate elovirta pdf customplug-in
unzip file and install in plugins folders
run the dita -install plug-in.zip  cmd

The Build keeps running with old org.dita.pdf2 custom.xsl

There might be a missing file chnage somewhere if anyone can help please?

**Comment by raducoravu** [comment]
So how exactly do you run the publishing from the command line? Do you specify in the command line the custom transtype for the custom PDF plugin?
This same question seems to have been also asked on the DITA Users List so I'm closing the opened issue for now.
