### ISSUE TITLE
No HTML generated from XDITA map and topics in 3.1.2

### ISSUE THREAD

**Issue by markgif** [dita-ot/dita-ot#3076]
## Expected Behavior
An xdita map and topics should generate html5 files the same way it is done with regular DITA 1.3.

## Actual Behavior
The XDITA build runs with no errors or warnings in the log, and exit code 0. But no HTML files are generated except for index.html, which has no content.

(By the way I had to install the XDITA DTDs before the build would run at all.)

## Possible Solution
I'm not sure how to fix it. If you give me a clue where to look, I will try for a fix.

## Steps to Reproduce

1. Install XDITA DTDs to 3.1.2 OT.
2. Run XDITA map and topic from gist below with this 3.1.2 OT.
3. Inspect error-free log, and missing HTML output.
https://gist.github.com/markgif/a1e689ed50f786fd4c7909e8d00d76ea

## Copy of the error message, log file or stack trace
https://gist.github.com/markgif/623ee1d848482a20fbec67a66604460e

## Environment

* DITA-OT version: 3.1.2
* Operating system and version: Windows 7
* How did you run DITA-OT? oXygen 20.1
* Transformation type: html5

**Comment by raducoravu** [comment]
The problem is probably this one:

https://github.com/oasis-tcs/dita-lwdita/issues/16

All topicrefs in XDita are marked by default as resource only.

**Comment by lief-erickson** [comment]
@raducoravu, I would like to see @markgif confirm this before it's closed.

**Comment by robander** [comment]
@lief-erickson -- the issue @raducoravu identified would definitely have this result - he reported the defect in XDITA doctypes yesterday, and Carlos has already checked in a fix (not sure if he's created a new release yet). I think it's appropriate to close this item, as the defect is in the external OASIS product that doesn't yet ship with DITA-OT.

(I'm not sure if Radu verified the issue in the other tracker before Carlos closed it -- it doesn't look like any commit is attached to the issue.)

**Comment by raducoravu** [comment]
Encountered in some random internal tests same problem as @markgif, in a way this illuminates us about just how many people are using lw dita maps.

**Comment by markgif** [comment]
This DTD fix works, thanks @raducoravu !! And thanks @jelovirt for a basically sound lwdita plugin.

**Comment by carlosevia** [comment]
Will create a new release as soon as DITA TC approves/discusses my fix (created an entity for processing in the LwDITA map mod file)
