### ISSUE TITLE
Errors caused by link to topic with xref in shortdesc

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#3078]
## Expected Behavior

When I have the following condition:

1. Topic contains `<xref>` to another topic `xref-in-shortdesc.dita`
1. The referenced topic has a short description, *and* that short description also contains an `<xref>` to `finaltarget.dita`
1. The xref inside that short description is missing link text or `<desc>`

The `topicpull` step ends up grabbing the short description from the middle file `xref-in-shortdesc.dita`, putting that in a variable, and then processing the variable. The result is that the `<xref>` to `finaltarget.dita` is processed again but in the context of that variable, which causes the processor to look for it in our XSLT directory, and ends with errors. Happens with both `preprocess` and `preprocess2`, here is the error log from `preprocess`:
```
C:\DCS\test\apiref>\dita-ot\dita-ot-3.1.2\bin\dita -i in.ditamap -f html5
[topicpull] I/O error reported by XML parser processing file:/C:/DITA-OT/dita-ot-3.1.2/xsl/preprocess/finaltarget.dita: C:\DITA-OT\dita-ot-3.1.2\xsl\preprocess\finaltarget.dita (The system cannot find the file specified.)
[topicpull] file:/C:/DCS/test/apiref/xref-in-shortdesc.dita:5:68: [DOTX031E][ERROR]: The file finaltarget.dita is not available to resolve link information.
```

This worked at some point in the past (at least, the `xref` inside shortdesc was processed to get text) but could have been broken as far back as 1.8 -- the text was pulled and no errors were thrown.

## Actual Behavior

Errors appear as shown above. `preprocess2` has the same issue:
```
C:\DCS\test\apiref>\dita-ot\dita-ot-3.1.2\bin\dita -i in.ditamap -f pdf
[topicpull] I/O error reported by XML parser processing file:/C:/DITA-OT/dita-ot-3.1.2/xsl/preprocess/dd3f451dd1448c00ddc872728d9573466227ad65.dita: C:\DITA-OT\dita-ot-3.1.2\xsl\preprocess\dd3f451dd1448c00ddc872728d9573466227ad65.dita (Thesystem cannot find the file specified.)
[topicpull] file:/C:/DCS/test/apiref/xref-in-shortdesc.dita:5:68: [DOTX031E][ERROR]: The file dd3f451dd1448c00ddc872728d9573466227ad65.dita is not available toresolve link information.
```

## Possible Solution

Once everything is in the variable context, I'm not sure how easy it is to get away from this. Most likely, the only way around it is to update the `copy-shortdesc` mode so that when it finds an xref, it actually goes to process the file, but I'm not sure yet.

## Steps to Reproduce

Samples attached:
[xrefshortdesc.zip](https://github.com/dita-ot/dita-ot/files/2412523/xrefshortdesc.zip)

## Copy of the error message, log file or stack trace

Shown above

## Environment

* DITA-OT version: 3.1.2
* Operating system and version: _Windows_
* How did you run DITA-OT? _dita command_
* Transformation type: _html5_ and _pdf_

**Comment by xephon2** [comment]
This is probably also related to DITA-OT 2.5.x and to other linking elements like `<term>` and so on. I remember I went crazy because the error message is absolutely useless for authors.

To other crazy people: If you like to avoid problems related to this bug, you may want to use a Schematron rule to prohibit links completely in `<shortdesc>`.

```xml
<sch:pattern id="no-linking-in-shortdesc" see="https://github.com/dita-ot/dita-ot/issues/3078">
    <sch:rule context="*[contains(@class, ' topic/shortdesc ')]">
        <sch:report test="*[@keyref] or *[contains(@href, '.dita')]">
            Do not link to other topics in &lt;shortdesc&gt;. This does not work.
        </sch:report>
    </sch:rule>
</sch:pattern>
```

**Comment by raducoravu** [comment]
+1 Same problem when generating the PDF. Similar to your case, console output shows that the target file is searched in a very strange location, instead of being searched in the transformation temporary files folder, it's searched in the place where the XSLT is located:

    [topicpull] I/O error reported by XML parser processing file:/D:/projects/oxygen-dita-ot-3.x/xsl/preprocess/bdc88ce59a00abe01b1103acb5739f573e7a34d5.dita

**Comment by raducoravu** [comment]
Somewhere in the "topicpullImpl.xsl" there is a document() function using the relative reference to the file. Somehow the "$linkElement" which should be used to retrieve a base URI is a node set which is not part of a document.

**Comment by raducoravu** [comment]
BTW, attached sample project is incomplete, it's missing a "xrefshortdesc\haslink.dita" attaching a complete sample:
[xrefshortdesc.zip](https://github.com/dita-ot/dita-ot/files/2749968/xrefshortdesc.zip)

**Comment by robander** [comment]
Interesting timing, I just had somebody run into this again yesterday (completely different author / set of content, but same message from `topicpull` trying to open a topic in the `xsl/` directory).

**Comment by raducoravu** [comment]
Think I found the problem, in "topicpullImpl.xsl" there is a variable called "shortdesc" which gets computed and there is an apply-templates on it. But the variable no longer has a base-uri().

**Comment by robander** [comment]
Yes - that sounds right. Over the last few years we've had more pieces of code that put elements into variables, and when working on content in the variable the context is lost.

**Comment by raducoravu** [comment]
The question maybe for @jelovirt would be what possible side effects would be if in the build file "plugins\org.dita.base\build_preprocess.xml" in the ""preprocess"" target we would move the call to the "topicpull" stage before the call to the "move-meta-entries" stage.

**Comment by robander** [comment]
I don't think we want to do that, especially with `preprocess2` moving all of map processing early, it's not a great idea to move one of the all-topic steps before one of the map steps. (I know these steps switched places in the first couple years of DITA-OT but cannot remember all of the reasons that they ended up in this order.)

**Comment by raducoravu** [comment]
👍 One more report:
https://www.oxygenxml.com/forum/viewtopic.php?p=53982#p53982

again a short description contains an xref, and at some point in the [topicpull] stage we get this error in the console view (using DITA OT 3.3.1):

             DITA-OT3.x\plugins\org.dita.base\xsl\preprocess\process_edit.dita (The system cannot find the file specified)

so the "process_edit.dita" is searched for in the wrong folder.

**Comment by robander** [comment]
@raducoravu do you still have the code set up that used `$baseContextElement` to fix this? I tried to do something like that just now and it didn't seem to work, so I think I missed something. If you could make a pull request with the code change, and allow maintainer edits, I could verify it and then add a test case to the same pull request?

**Comment by raducoravu** [comment]
I will do this on Monday

**Comment by raducoravu** [comment]
@robander added my changes as a possible pull request, they don't need to be integrated as they are if you have a better solution, it's just for you to know what I did on my side.
As I said before there are two aspects for the problem and the XSLT changes fix only the first aspect.

**Comment by raducoravu** [comment]
👍 We had another end user asking for a fix for this on DITA OT 2.5.4.

**Comment by raducoravu** [comment]
Attaching the end user's samples for which html5 publishing still reports errors like "The file topic_a.dita is not available to resolve link information." even with my fix applied.
[sample_xref_in_shortdesc.zip](https://github.com/dita-ot/dita-ot/files/3405052/sample_xref_in_shortdesc.zip)
In those samples there are three DITA topics, the short description for each topic has an xref to the title of the next topic in a circular fashion with the shortdesc of the last topic having an xref to the title of the first topic.
The reported errors seem benign as the tooltips properly resolve on each link in the shortdesc of each topic.

Why are the errors still reported?
So for expanding the reference from topic A's shortdesc to topic B the topicpull XSLT code finds the xref to topic B and loads topic B in a document. Then it applies the template which resolve topic B's title but the XSLT processing also tries to resolve topic B's shortdesc. Because it tries to resolve topic B's shortdesc, it goes into that shortdesc, finds a reference to topic C, tries to expand that and so on.
As in the end topic B's title will appear as a tooltip when hovering over the xref to it, resolving its shortdesc is not quite necessary but the information does appear in the processed topic so possibly it might be used by some customizers.

I give up :(

**Comment by raducoravu** [comment]
Probably one more problem. Again, topic is searched for in the wrong folder:
https://www.oxygenxml.com/forum/post56095.html#p56082

**Comment by reifsnid** [comment]
Hi, is still an issue in the latest version of the DITA-OT? 

We're using 3.7.2 and are encountering this issue in several of our publications and would like to avoid refactoring our short descriptions if possible.

Thanks!
