### ISSUE TITLE
<notices> should come before TOC in PDF output

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#310]
Converted from [SourceForge issue 1942252](http://sourceforge.net/support/tracker.php?aid=1942252), submitted by hmichaud

In bookmap, if you insert content (for example, a copyright page) in the <notices> element and generate a PDF, it comes after the TOC in the output, even if in the map it is placed before the <booklists> element. Typically in print formats such information comes before the TOC and is not listed in the Contents. If content is inserted before the <toc> in the map, it should come before the contents page in the output.

**Comment by shaun-teknop** [comment]
Hi, can you please share the version of dita in which this issue was fixed?
