### ISSUE TITLE
Review third party dependencies

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3105]
There is a "NOTICES.txt" which does not seem to enumerate all JAR libraries found in the DITA OT "lib" folder, libraries like "checker-qual", "animal-sniffer", "error_prone_annotations". Maybe some of these libraries are not necessary to be present in the installation kit, maybe they are used only when developing the code.
For example the "checker-qual" has dual licensing and from what I talked with our legal, the NOTICES could state what license is used for it (MIT instead of GPL).

This list in the docs should probably also be updated:
http://www.dita-ot.org/dev/reference/third-party-software.html

**Comment by jelovirt** [comment]
I'm wondering, could we just add `lib/<lib>.license.txt` for every `lib/<lib>.jar` file, and not have a separate notices at all?

**Comment by raducoravu** [comment]
Looking at this:
https://www.apache.org/licenses/LICENSE-2.0

> The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License. 

it would seem the NOTICE is not required. But Stefan our CEO disagrees with this, he said he'll comment on this issue directly.
