### ISSUE TITLE
copy-to with missing file causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by marknyma** [dita-ot/dita-ot#3122]
## Expected Behavior
A concise error message should be output in this situation.

## Actual Behavior
**Error: java.lang.NullPointerException** is thrown and naturally the transformation fails

## Steps to Reproduce
See the example 'copyimage' in #2486 

1. Rename the `test.dita` file to something else.
2. Run transformation

## Environment
We are using dita-ot v2.5.4 with the [oXygen WebHelp](https://www.oxygenxml.com/xml_webhelp/download_oxygenxml_webhelp.html?os=DITAOT) transformation.

* DITA-OT version: 2.5.4
* Operating system and version:
  _Linux and Windows_
* How did you run DITA-OT?
  _`dita` command_
* Transformation type:
  _oXygen WebHelp_

**Comment by raducoravu** [comment]
The problem can also be reproduced with DITA OT 3.1.3 when running a plain HTML5 transformation:

    C:\Users\radu_coravu\Desktop\DITA OT newest\dita-ot-3.1.3\plugins\org.dita.base\build_preprocess.xml:298: java.lang.NullPointerException
	at org.dita.dost.module.CopyToModule.performCopytoTask(CopyToModule.java:165)
	at org.dita.dost.module.CopyToModule.execute(CopyToModule.java:75)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

and the obtained stack trace is identical to the one in the issue I posted here some time ago:

https://github.com/dita-ot/dita-ot/issues/2733

**Comment by raducoravu** [comment]
Just encountered this problem again trying to create a PDF from a single topic in our user's manual.
Basically if in the DITA Map I have this topicref:

          <topicref href="topics/care.dita" copy-to="topics/care2.dita">

and the care.dita topic is invalid (has some extra non-DITA XML tag inserted in it for example) probably the "Map<FileInfo, FileInfo>" will contain a not null key mapped to a null value.
