### ISSUE TITLE
HTML5 output failing in dev OTs

### ISSUE THREAD

**Issue by markgif** [dita-ot/dita-ot#3123]
## Expected Behavior
HTML5 output of docsrc/sample content should build successfully

## Actual Behavior
Build fails with error like this:

`C:\Users\Mark\dita-ots\dita-ot-3.1.3+93cf848\plugins\org.dita.base\build_preprocess.xml:62: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/C:/Users/Mark/dita-ots/dita-ot-3.1.3+93cf848/docsrc/samples/hierarchy.ditamap' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.`

The same DITA files build successfully with released 3.1.3 OT.

## Possible Solution
Not sure but it seems like the kind of error I get when the right DTDs are not available.

## Steps to Reproduce

1. Use dev OT dita-ot-3.1.3+2be7362 or dita-ot-3.1.3+93cf848.
2. Run HTML output on docsrc/samples/hierarchy.ditamap

## Copy of the error message, log file or stack trace
```
gen-list:
 [gen-list] Using Xerces grammar pool for DTD and schema caching.
 [gen-list] Processing file:/C:/Users/Mark/dita-ots/dita-ot-3.1.3+93cf848/docsrc/samples/hierarchy.ditamap

BUILD FAILED
C:\Users\Mark\dita-ots\dita-ot-3.1.3+93cf848\build.xml:46: The following error occurred while executing this line:
C:\Users\Mark\dita-ots\dita-ot-3.1.3+93cf848\plugins\org.dita.base\build_preprocess.xml:62: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/C:/Users/Mark/dita-ots/dita-ot-3.1.3+93cf848/docsrc/samples/hierarchy.ditamap' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.

Total time: 7 seconds

The process finished with exit code: 1

```

## Environment

* DITA-OT version: dita-ot-3.1.3+93cf848
* Operating system and version: Windos 7, macOS
* How did you run DITA-OT? Oxygen 20.1
* Transformation type: HTML5

**Comment by robander** [comment]
I think this is a duplicate of #2414 -- if you remove the `+` sign in the directory name and try again, does the map build properly?

**Comment by markgif** [comment]
Yes it works fine if I remove the `+` from `dita-ot-3.1.3+93cf848`. Thanks @robander! It's a duplicate of #2414 .
