### ISSUE TITLE
PDF table of content does not show section numbers when using dita "<map>"

### ISSUE THREAD

**Issue by hcw70** [dita-ot/dita-ot#3131]
## Expected Behavior
PDF toc should show section numbers of the topics rendered with the topic number.

```
Contents
1. Introduction...................................................................... 4
1.1 Block diagram colors........................................................4
```

## Actual Behavior
```
Contents
Introduction...................................................................... 4
Block diagram colors........................................................4
```

## Steps to Reproduce
Grab Dita version 3.1.2, add topics "Introduction" and "Block diagram colors" where the second one is a child of the first

## Environment
* DITA-OT version: 3.1.2
* Operating system and version: Linux
* How did you run DITA-OT? `dita` command

* Transformation type: PDF

**Comment by takesson** [comment]
I am also investigating numbering.

Works in both content and Toc:
 - Bookmap parts
 - Bookmap chapters
 - I suspect bookmap appendix works as well based on the code in `xsl/fo/commons.xsl`

When it comes to numbering of other topicrefs there seems to be some code inserted by the PDF Plugin generator that only handles the content, not the Toc.

**Comment by hcw70** [comment]
@takesson What exactly do you mean by "Works in both content and Toc"? 
Are you using Dita 3.1.2 also and the described bug here does not occur for you?

**Comment by hcw70** [comment]
For reference, i use a ditamap which looks like the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
 <title>Documentation for Schema File MessageDB.xsd</title>


  <topicref href="MessageDB.xsd-overview.dita"/>
  

  <topichead navtitle="Element definitions">
    <topicref href="MessageDB.dita"/>
    
    <topicref href="doc_142.dita"/>
    
    <topicref href="altName_142.dita"/>

  </topichead>

</map>

```

**Comment by takesson** [comment]
@hcw70 Numbering of the bookmap elements that I listed works. You are NOT using a bookmap so the last section I wrote applies to your sample map. 

I believe numbering of generic topicref in a generic map is not at all implemented in DITA-OT. There is some XSL added by http://dita-generator.elovirta.com that attempts to do numbering of generic topicref but it does not work for the toc.

**Comment by takesson** [comment]
I am testing on DITA-OT 3.3.3 but I doubt there is any difference.

**Comment by hcw70** [comment]
@takesson Ok thanks for the information. So my best bet would be to switch to bookmap then...

**Comment by takesson** [comment]
@hcw70 Well, that gives you a quite different look with Part and Chapter. 

You can easily have a look by publishing the included user guide, e.g.:
`bin/dita --input docsrc/userguide-book.ditamap -f pdf2 --processing-mode=strict`

**Comment by hcw70** [comment]
Tried with DITA-OT-3.1.2 via
<?xml version="1.0" encoding="UTF-8"?>
```
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap>
 <title>Usage</title>
 <bookmeta>
  <author>XX</author>
 </bookmeta>
 <frontmatter>
  <booklists>
   <toc/>
   <figurelist/>
   <tablelist/>
  </booklists>
 </frontmatter>
 <chapter>
 <topicref ...>
```

But still no chapter numbering in the TOC.... 8-<

Trying to upgrade to 3.3.3 reveals some custom-PDF plugin errors which i am not able to resolve....

**Comment by takesson** [comment]
I would initially test with the standard pdf2 output, no custom plugins to keep complexity at a minimum.

**Comment by hcw70** [comment]
we have fixed the issue with a custom pdf plugin now.

**Comment by takesson** [comment]
@hcw70 Is the custom pdf plugin open-source?

Maybe there is some improvement that can be fed back to the [dita-generator](http://dita-generator.elovirta.com/) if it was based on that XSL?

**Comment by hcw70** [comment]
@takesson It is not open source. It is developed in a commercial context. However, it is a small xslt plus plugin stuff. I will check if it can be released separately....

**Comment by LouIentile** [comment]
I am having the same problem. Any updates on this? Is there a custom pdf plug-in that can be shared? No part/chapter/appendix numbers displaying in the TOC of the PDF from a bookmap. I am using DITA OT 3.3.3 and transforming with the XSL-FO scenario.

**Comment by hcw70** [comment]
Just found https://github.com/oxygenxml/dita-ot-numbering maybe that will also fix the issue....

**Comment by hcw70** [comment]
Tried above plugin and it looks good. Numbering in TOC and in chapter titles works.
