### ISSUE TITLE
Add a mapping file to map original file names to scrambled temp file names 

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#3132]
## Description
I need to find out the original file names of all processed DITA maps and topics. The OT "renames" the files in the temp dir. I think there was a file in DITA-OT 1.x file that listed all those file names. It would be easy, if everyone would follow the authoring rule "topic ID equals filename", but this is not always the case.

Something like this:

```
foo.dita=9324982374928347897asd87.dita
```

**Comment by jelovirt** [comment]
The `file` elements in `.job.xml` file in the temporary file directory will give you the mapping.

**Comment by jelovirt** [comment]
@robander which label should we use for "already works" or "this is already available"?

**Comment by robander** [comment]
@jelovirt not sure - I've used `obsolete` for similar issues in the past (requests that only apply to older releases), but that feels a bit wrong in this case?
