### ISSUE TITLE
Support the @href attribute for images referenced with URL (not the relative path)

### ISSUE THREAD

**Issue by rahulraykor** [dita-ot/dita-ot#3151]
## Description
Currently image href attribute only supports relative path on which image is present. If we provide image URL (hosted online) or full path of image on local machine it is getting failed.

`
<image placement="break" class="- topic/image " alt="Infection" width="570" height="738" href="https://images.pexels.com/photos/1266007/pexels-photo-1266007.jpeg"  />
`

**Comment by robander** [comment]
Have you tried putting `@scope="external"` on the image to indicate that it is not a local image?

**Comment by rahulraykor** [comment]
Yes. If you do so that image is not appearing in converted PDF.

**Comment by robander** [comment]
External images referenced by URL are not currently supported in PDF.

The image needs to specify `scope="external"`, which is required for all external references; this will work for HTML, where the browser can still resolve external image references. This is the first time I've heard the request for support in PDF.

**Comment by rahulraykor** [comment]
Well not only for PDF. In my case I am using this for DOCX conversion. So if we think of a general solution that can work for all cases, and can be helpful for other who want to extend the functionality for other conversions.
I think a solution can be,
1. Copy the external sources and keep in temp dir.
2.Update the resources list as well as source xml with the name of that resource

And I guess that can work for all the extensions. Need your views
