### ISSUE TITLE
glossentry reports missing if used in shortdesc and another topic uses <xref> to origin topic

### ISSUE THREAD

**Issue by jomjohn** [dita-ot/dita-ot#3153]
## Expected Behavior
When `<term keyref="gloss_term"/>` is used in a `<shortdesc>` the value needs to resolve when shortdesc is read.  

## Actual Behavior
The glossterm is left blank: ![broken_term_in_shordesc_preview](https://user-images.githubusercontent.com/2067998/48743690-0068b600-ec19-11e8-912c-8cf70a96c87a.png)

## Possible Solution
I am not sure if this is a keyref issue or a topicpull issue. I would think that the keyref would already be resolved by the time topicpull happens. The keyref is trying to resolve relative to the dita-ot/xsl location rather than the doc source location.

## Steps to Reproduce

My sample source and output is included in this zip: [samples.zip](https://github.com/dita-ot/dita-ot/files/2597553/samples.zip)

1. Updated files:

**hierarchy.ditamap**, added glossary.ditamap:
`<mapref href="glossary.ditamap"/>`

**glossary.ditamap (new)**
`  <topichead>
    <topicmeta>
      <navtitle>Glossary</navtitle>
    </topicmeta>
    <glossref href="glossary/gloss_google.dita" keys="gloss_google"/>
  </topichead>`

**glossary/gloss_google.dita (new):**
`<glossentry id="gloss_google">
    <glossterm>Google</glossterm>
    <glossdef>The place where you find stuff.</glossdef>
</glossentry>`

**concepts/lawnmower.xml**, added term glossentry reference in `<shortdesc>`
`<shortdesc>The lawnmower is a machine used to cut grass in the yard. You can look it up on <term keyref="gloss_google"/></shortdesc>`

**concepts/oil.xml** added `<link>` to lawnmower.xml:
`<link href="lawnmower.xml" format="dita" type="concept"></link>`

2. Run `dita -v --input=samples/hierarchy.ditamap --format=xhtml`
3. In one case (where child links are created) the term resolves correctly:
![glossary_term_resolved](https://user-images.githubusercontent.com/2067998/48743929-1d51b900-ec1a-11e8-969c-11d1c200252e.png)
In Oil.xml the term is blank:
![broken_term_in_shordesc_preview](https://user-images.githubusercontent.com/2067998/48743945-2e9ac580-ec1a-11e8-955b-b5ac30186bfc.png)

## Copy of the error message, log file or stack trace
[topicpull] java.io.FileNotFoundException: C:\*****\dita-ot.git\src\main\xsl\glossary\gloss_google.dita (The system cannot find the path specified)
[topicpull] file:/C:/*****/dita-ot-docs/samples/concepts/lawnmower.xml:11:121: [DOTX031E][ERROR]: The file ../glossary/gloss_google.dita is not available to resolve link information.

## Environment

* DITA-OT version: 3.2 and older
* Operating system and version: Windows
* How did you run DITA-OT? `dita -v --input=samples/hierarchy.ditamap --format=xhtml`
* Transformation type: xhtml

Thank you for any help you can provide to fix this issue!

**Comment by robander** [comment]
I've seen other issues over time with short descriptions that include links being pulled into cross reference hover-help ... ran into another just a week or two ago and couldn't see a good way to resolve it. Usually the problem is worse when files are not in the same directory, but that's not always the issue.

**Comment by robander** [comment]
I think this is probably a duplicate of #3078. Whether `@keyref` or `<xref>`, the defect is caused by cross references that end up in the short description ==> pulled into hover help.
