### ISSUE TITLE
Show original file path with 'args.artlbl' and preprocessing2

### ISSUE THREAD

**Issue by qvrijt** [dita-ot/dita-ot#3154]
## Expected Behavior
Printing a filepath to the source image. 
So after a document review, anybody can find the bitmap to update for change request to a figure.

```
[image]
subdir\images\figure.jpg 
Figure 1: This is a caption for the figure 

```
## Actual Behavior
Printing of the hashed filename, as introduced in DITA-OT 3.0.
Great for debugging, but as a temporary file, does not makes sense to an end-user of a PDF.
```
[image]
429954c4b28a55d144ff42e5a07b51ffda9d185a.jpg 
Figure 1: This is a caption for the figure 

```
## Steps to Reproduce
Calling DITA-OT from commandline 
` dita.bat -i path\to\bookmap.ditamap -f pdf -Dargs.artlbl=yes `

## Environment
Windows 10, DITA-OT 3.2

**Comment by robander** [comment]
Not sure how best to manage this, but it's pretty clear the current result for `args.artlbl` in PDF is not usable for the originally intended purpose.

**Comment by qvrijt** [comment]
document (@xtrf)/image[@xtrc]/@href

Something like that?


Op vr 7 dec. 2018 16:54 schreef Robert D Anderson <notifications@github.com:

**Comment by raducoravu** [comment]
I also agree that when producing the PDF errors like this:

      [DOTX031E]: The file 774e41ff5f82421fb7ad88659287b754810c368a.dita            is not available to resolve link information.

are not helpful at all, maybe when computing the error message you should look in the ".job.xml" and also show the original file name and path for the hashed topic.

**Comment by qvrijt** [comment]
Suggested solution/override for 
    
    <xsl:template match="*" mode="image.artlabel">
        <xsl:variable name="artRef"     select="tokenize(@xtrc,';')[1]"/>
        <xsl:variable name="artElement" select="xs:string(tokenize($artRef,':')[1])"/>
        <xsl:variable name="artIndex"   select="xs:int(tokenize($artRef,':')[2])"/>
        <xsl:variable name="artHref"    select="document(@xtrf)//*[name() = $artElement][$artIndex]/@href"/>

        <fo:block xsl:use-attribute-sets="image.artlabel">
            <xsl:text> </xsl:text>
            <xsl:value-of select="concat(@xtrf,',',$artHref)"/>
            <xsl:text> </xsl:text>
        </fo:block>
    </xsl:template>

**Comment by qvrijt** [comment]
Suggested solution (or customization):
```
    <!-- Override for dita-ot-3.2.1\plugins\org.dita.pdf2\xsl\fo\topic.xsl -->
    <xsl:template match="*" mode="image.artlabel">
        <xsl:variable name="artRef"     select="tokenize(@xtrc,';')[1]"/>
        <xsl:variable name="artElement" select="xs:string(tokenize($artRef,':')[1])"/>
        <xsl:variable name="artIndex"   select="xs:int(tokenize($artRef,':')[2])"/>
        <xsl:variable name="artHref"    select="document(@xtrf)//*[name() = $artElement][$artIndex]/@href"/>

        <fo:block xsl:use-attribute-sets="image.artlabel">
            <xsl:text> </xsl:text>
            <xsl:value-of select="concat(@xtrf,',',$artHref)"/>
            <xsl:text> </xsl:text>
        </fo:block>
    </xsl:template>
```
The template is primarily called for images, but other use cases may be valid so I explicitly extract and use $artElement.
The did not resolve into a full filepath because I don't know how this works out for references when using a CCMS.
I changed the fo:online into and fo:block, so it is rendered nicely below the image.

**Comment by jelovirt** [comment]
@qvrijt Note that `@xtrc` is not available if you use [`generate-debug-attributes=false`](https://www.dita-ot.org/dev/parameters/parameters-base.html#base__generate-debug-attributes).

**Comment by qvrijt** [comment]
@jelovirt Good point. Never noticed it, because i used the option in combination with debugging.

Change of tactics: Capture output of placeImage and extract fo:external-graphic/@src.
In my case, it also returns the resolved path to the original source.

See attachement [artlabel-from-fographic.txt](https://github.com/dita-ot/dita-ot/files/2836125/artlabel-from-fographic.txt)

**Comment by qvrijt** [comment]
```
    <!-- Override of dita-ot-3.2.1\plugins\org.dita.pdf2\xsl\fo\topic.xsl -->
    <!-- 
        Print the path of the image source file.
        To use @xtrf, render document with DITA argument -Dgenerate-debug-flags=yes 
    -->
    <xsl:template match="*" mode="image.artlabel">
        <fo:inline xsl:use-attribute-sets="image.artlabel">
            <xsl:choose>
                <!-- Added workaround for dita-ot-3.x -->
                <xsl:when test="@xtrf">
                    <xsl:text> </xsl:text>
                    <xsl:value-of select="@xtrf"/>
                    <xsl:text> </xsl:text>
                </xsl:when>
                <!-- Correct for dita-ot-1.x/2.x. Returns tempdir file name for dita-ot-3.x -->
                <xsl:when test="@href">
                    <xsl:text> </xsl:text>
                    <xsl:value-of select="@src"/>
                    <xsl:text> </xsl:text>
                </xsl:when>
                <!-- May work for HTML -->
                <xsl:when test="@src">
                    <xsl:text> </xsl:text>
                    <xsl:value-of select="@src"/>
                    <xsl:text> </xsl:text>
                </xsl:when>
            </xsl:choose>
        </fo:inline>
    </xsl:template>

    <!-- Override of dita-ot-3.2.1\plugins\org.dita.pdf2\xsl\fo\topic.xsl -->
    <!-- 
        Print the path of the DITA source file after the topic title.
        To use @xtrf, render document with DITA argument -Dgenerate-debug-flags=yes 
    -->
    <xsl:template match="*[contains(@class,' topic/topic ')]/*[contains(@class,' topic/title ')]">
        <!-- render title by current template -->
        <xsl:next-match/>
        <!-- postfix source file name -->
        <xsl:if test="$artLabel='yes' ">
            <xsl:apply-templates select="." mode="image.artlabel"/>
        </xsl:if>
    </xsl:template>
```
