### ISSUE TITLE
Installation of a custom plugin fails on linux with different partitions / file systems

### ISSUE THREAD

**Issue by kluba** [dita-ot/dita-ot#3162]
## Expected Behavior
dita --install plugin.zip should install a new plugin

## Actual Behavior
On linux with several partitions / file systems (/tmp and /home are separated) the command above fails with the following exemplary error message:

Error: /tmp/2913888489706122428/plugin/com.scoop-software.plugin

The class PluginInstallTask tries to move a nonempty directory

`Files.move(tempPluginDir.toPath(), pluginDir.toPath());
`

what does not work if the source and the target are located on different partitions

## Possible Solution
I've replaced the Files.move line with the following code:

```
Files.walkFileTree(tempPluginDir.toPath(), new SimpleFileVisitor<Path>() {

	@Override
	public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
		Path targetPath = pluginDir.toPath().resolve(tempPluginDir.toPath().relativize(dir));
		if(!Files.exists(targetPath)) {
			Files.createDirectory(targetPath);
		}
		return FileVisitResult.CONTINUE;
	}

	@Override
	public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
		Files.copy(file, pluginDir.toPath().resolve(tempPluginDir.toPath().relativize(file)));
		return FileVisitResult.CONTINUE;
	}
});
```

which fixes the problem on my linux server (and also works on my Windows 10 PC)

## Steps to Reproduce
A linux server with two different partitions is needed 

1. Create a new folder on the first partition. Create a file in it
2. Adopt the paths in the following class. The second path has to point to a different (second) partition

```
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class MoveFailure {
	private static final String tempDir = "/tmp/plugin";
	private static final String homeDir = "/home/user/plugin";
	
	public static void main(String[] args) throws IOException {
            final File tempPluginDir = new File(tempDir);
            final File pluginDir = new File(homeDir);

            Files.move(tempPluginDir.toPath(), pluginDir.toPath());
	}
}
```

3. Run the class using java. It results in:

```
Exception in thread "main" java.nio.file.DirectoryNotEmptyException: /tmp/plugin
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:498)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at TestMove.main(TestMove.java:17)
```

## Copy of the error message, log file or stack trace
```
 java.nio.file.DirectoryNotEmptyException: /tmp/2913888489706122428/plugin/com.scoop-software.plugin
     at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:498)
     at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
     at java.nio.file.Files.move(Files.java:1395)
     at org.dita.dost.ant.PluginInstallTask.execute(PluginInstallTask.java:133)
     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
...
```

## Environment

* DITA-OT version: 3.2
* Operating system and version: Linux (SLES 11.4)
* How did you run DITA-OT: `dita` command
* Transformation type: custom (based on PDF)

**Comment by hcw70** [comment]
Affects me too. Because of this we are no longer able to install our plugin.

A fix is needed in order to update to 3.2.1 .....

**Comment by hcw70** [comment]
And that /tmp and /usr (or wherever your dita-install reside) is quite normal on most linux setups....

**Comment by hcw70** [comment]
@kluba Could you open a merge request, in the hope that any from dita-ot picks up that fix quicker?

**Comment by kluba** [comment]
I've never did that before... But why not. I will try it

**Comment by hcw70** [comment]
This problem was introduced by the pull request #3028 via commit 95385bd62eea3a4b419c28b507d57567af262283. The faulty java implementation was introduced with commit a87bb818a05c50134f1e2bebd80c23c713e97059 by @jelovirt in file PluginInstallTask.java. 

Pls could someone provide a fix for this problem? @kluba provided already some fix proposals for this....

**Comment by kluba** [comment]
@hcw70 I submitted a pull request (#3238)
