### ISSUE TITLE
XSLT error in customized plugin

### ISSUE THREAD

**Issue by ant28** [dita-ot/dita-ot#3164]
I have a customized plugin to transform dita files into new transtype form. 
the following was the structure of my plugin folder:
--resource
   ----aimlDomain.ent
   ----aimlDomain.mod
   ----basic-concepts.xsl
   ----catalog-dita.xml
   ----topic.dtd
--build_dita2aiml.xml
--integratorWrapper.xml
--plugin.xml

When I run the plugin with ant command, I got an error message as following:

BUILD FAILED
C:\Users\lenovo\Desktop\dita-ot-3.0\build.xml:45: The following error occurred while executing this line:
C:\Users\lenovo\Desktop\dita-ot-3.0\plugins\com.example.aiml\build_dita2aiml.xml:21: The following error occurred while executing this line:
C:\Users\lenovo\Desktop\dita-ot-3.0\plugins\com.example.aiml\build_dita2docbook.xml:43: stylesheet C:\Users\lenovo\Desktop\dita-ot-3.0\${dita.plugin.com.example.aiml.dir}\resource\basic-concepts.xsl doesn't exist.

I don't know why I got this message when the file exists in my folder. Can someone know how to fix it?  I am new to the DITA-OT plugin and learning to write it.

**Comment by robander** [comment]
My first guess is that your Ant code uses `${dita.plugin.com.example.aiml.dir}`, but that the plugin ID in your `plugin.xml` file is not `com.example.aiml` (the constructed Ant parameter is based on the plugin ID).

**Comment by jelovirt** [comment]
Closing as support, but feel free to continue discussion here.

**Comment by ant28** [comment]
Thank you so much! Your guess is right, now the plugin worked after I changed the ID in the plugin.xml file.
