### ISSUE TITLE
DITA-OT is not working without "@class" attribute

### ISSUE THREAD

**Issue by rahulraykor** [dita-ot/dita-ot#3166]
## Expected Behavior
I have following content in my topic
```
<p><u>Underline content:</u>  Should be without underline</p>
<p>Second Paragraph</p>
```

## Actual Behavior
DITA-OT is populating above content in single line even though they are separate paragraphs.

## Possible Solution
While creating a xml from the topic (during preprocess) check if "class" attribute is present. If not populate class attribute using node name. We can ignore some of them (u,i,ul etc)

**Comment by robander** [comment]
It looks like when opening the template, you've deleted some of the critical template sections. There is no way for us to help debug this without that information -- for example:

* DITA-OT version:
* Operating system and version:
  _(Linux, macOS, Windows)_
* How did you run DITA-OT?
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type:
  _(HTML5, PDF, custom, etc.)_

I have never seen 2 paragraphs come out on one line with any default transformation type, so I'm most interested in what transform you are running.

I also don't see any way that this could be related to `@class` -- DITA-OT always populates `@class` based on the grammar files, so if some of your files don't respect `@class` then I think something else in your environment is interfering.
