### ISSUE TITLE
Support <required-cleanup>, <unknown>, and <foreign> in more elements

### ISSUE THREAD

**Issue by chrispitude** [dita-ot/dita-ot#3167]
## Description
I'm working on FrameMaker-to-DITA migration for our team. There are places where I need `<foreign>`, `<unknown>`, or `<required-cleanup>` elements to preserve external information for later review, but the OASIS content models do not allow them.

Two real-world examples are:

- allow `<required-cleanup>` in `<uicontrol>` (for unsupported nested styles)
- allow `<foreign>` in `<cmdname>` (for links to external interactive help systems)

This enhancement requests that these three tags be supported in more places.

## Potential Alternatives
For now, I annotate plaintext 'FIXME' where I'm forced to, but this means the converted content is not publishable until significant post-conversion work is done.

## Additional Context
I am attaching a perl script (cm.pl) that dumps a content model for a given document-type shell. It requires jing/trang, perl, and the XML::Twig perl CPAN library.

I ran it as follows to find the elements that allow text **but not** each of the three tags, and I'm attaching those results as well. (Note that f.txt and u.txt are identical, which is expected as they're allowed similarly.)

```
cd plugins/org.oasis-open.dita.v1_3/rng/technicalContent/rng
fgrep -v required-cleanup cm | fgrep -v 'ns1:' | egrep -v -E '_[0-9]' | fgrep text > rq.txt
fgrep -v unknown cm | fgrep -v 'ns1:' | egrep -v -E '_[0-9]' | fgrep text > u.txt
fgrep -v foreign cm | fgrep -v 'ns1:' | egrep -v -E '_[0-9]' | fgrep text > f.txt
```

Discretion can be used to decide what is supported where, if there are technical issues that prohibit full support.

[rq.txt](https://github.com/dita-ot/dita-ot/files/2657914/rq.txt)
[f.txt](https://github.com/dita-ot/dita-ot/files/2657917/f.txt)
[u.txt](https://github.com/dita-ot/dita-ot/files/2657918/u.txt)

**Comment by robander** [comment]
This is not something we can fix in DITA-OT -- it is a limitation of the DITA content model itself. The DITA standard is maintained by OASIS; you can suggest changes on the `dita-comment` list, although I'll warn you up front that I think they are unlikely to add block level elements like `<required-cleanup>` into text-only contexts, or to nearly text-only contexts like `<keyword>` or `<cmdname>`.

https://www.oasis-open.org/committees/comments/index.php?wg_abbrev=dita
