### ISSUE TITLE
Show containing element in Relax NG content model violation messages

### ISSUE THREAD

**Issue by chrispitude** [dita-ot/dita-ot#3168]
## Description
It would be very helpful to include the parent element in content model violations (see boldface):

[gen-list] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:/mnt/c/Users/chrispy/Documents/DITA/xml_for_all_digital_books/sample_doc/char_def_nesting_tests.dita'.: [58:82] element "required-cleanup" not allowed **in "uicontrol"** here; expected the element end-tag, text or element "apiname", "cmdname", "data", "data-about", "foreign", "image", "keyword", "mathml", "term", "text" or "unknown"

Note that I am using a Relax NG document-type shell; my own request is specific to that.

**Comment by drmacro** [comment]
Validation is a function of the XML parser and is not under the direct control of the OT.

**Comment by chrispitude** [comment]
What library or component is used for this? I can open an enhancement request there.

**Comment by raducoravu** [comment]
@chrispitude The Relax NG provided default values are expanded using the Jing GitHub project:
https://github.com/relaxng/jing-trang
Ideally you could try to use that project to validate an XML with a Relax NG schema using its command line utility, and if the problem can be reproduced, try to add an issue on that project.

**Comment by chrispitude** [comment]
[jing/trang issue #242](https://github.com/relaxng/jing-trang/issues/242) filed. Thanks!
