### ISSUE TITLE
DITA-OT 3.2.1 triggers Windows Defender on batik-all-1.10.jar as Severe

### ISSUE THREAD

**Issue by qvrijt** [dita-ot/dita-ot#3171]
## Expected Behavior
Downloading dita-ot-3.2.1.zip from dita-ot.org with Google Chrome.

## Actual Behavior
On completing download, Windows Defender comes in with antivirus safety check.
It triggers on detection of **Trojan:Java/Tisifi.C with level Severe** in: 
- org.dita.pdf2.fop/lib/batik-all-1.10.jar 

Screendump with details attached.
![20181224-windefender-triggered-ditaot-3 2 1-batik-all-1 10 jar](https://user-images.githubusercontent.com/41584738/50401158-55ea3280-0784-11e9-91d4-ac7f1a6a80ae.png)

**Comment by qvrijt** [comment]
www.virustotal.com does not confirm.
![virustotal com-doesnot-confirm](https://user-images.githubusercontent.com/41584738/50401509-01948200-0787-11e9-9db5-66725ca727c3.png)

**Comment by raducoravu** [comment]
Using Windows 10 with latest updates, I invoked the Windows Defender on a folder containing an unzipped DITA OT 3.2.1 and I cannot reproduce the problem.

**Comment by imck** [comment]
I'm getting the same problem - Using Chrome or IE to download 3.2.1 Windows Defender deletes the download because of Trojan:java/Tisifi.C

**Comment by raducoravu** [comment]
Somehow when I directed the Windows Defender to particularly scan the folder it reported no problem, but after some time I looked a couple of days ago at the "Virus and Thread Protection" and indeed it seems to signal that particular JAR library as a problem.

**Comment by jelovirt** [comment]
FYI, the reason we use batik-all JAR is that the classpath is shorter this way. We could use the separate JARs, but then we get the complaints/bug reports that the classpath is too long. 🤷‍♀️

**Comment by raducoravu** [comment]
I will try to submit this JAR library as a false positive to the Windows Defender web site. Splitting the large JAR in multiple JAR libraries may possibly not solve the problem, this would need to be tested though. And also indeed the problem listed here would occur more often for end users running the DITA OT on Windows: https://github.com/dita-ot/dita-ot/issues/2827

**Comment by raducoravu** [comment]
I submitted a report for Windows Defender incorrectly identifying the JAR library as a virus, attached to the report the entire DITA OT 3.2.1 zip downloaded from the web site but they did not find anything wrong with the JAR:

![malwaresubmission](https://user-images.githubusercontent.com/1005979/51601445-09be1980-1f0d-11e9-9ee0-5bd20dffa985.png)

So I'm not sure what else could be done.

**Comment by lief-erickson** [comment]
I downloaded 3.3 today. Windows 10 Security Center quarantined the .zip file because of Tisifi.C. I allowed it, because I am aware of this issue. Actually, I had to redownload the 3.3 .zip file. I realize there's not much anyone here can do. I'm adding this in case someone else comes across this.

**Comment by qvrijt** [comment]
Yes, same for me Lief, i got it also for dita-it-3.3, with updated Windows
Defender to March 1st 2019

Quick

Op vr 1 mrt. 2019 23:32 schreef Lief Erickson <notifications@github.com>:

**Comment by raducoravu** [comment]
Maybe one of you can try again re-submitting the DITA OT 3.3 for analysis: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by lief-erickson** [comment]
Thanks for the link, @raducoravu. I submitted dita-ot-3.3.zip for analysis.

**Comment by infotexture** [comment]
Windows “Defender” has apparently been throwing `Tisifi.C` false positives for quite some time now. 

There's a 2016 [post on the Intellij IDEA forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/203366870-IDEA-version-2016-2-4-reported-as-malware-on-Windows-10-TrojanDownloader-JS-Tisifi?page=1#community_comment_203662524), and several other open-source projects have logged similar issues recently, including: 

- https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/267#issuecomment-394736642
- https://github.com/rest-assured/rest-assured/issues/1005

If the submission process allows for comments, it might help to point out that this is not an isolated issue for DITA-OT, but is also affecting other projects.

**Comment by lief-erickson** [comment]
My results were the same as Radu's. 

![image](https://user-images.githubusercontent.com/10221562/53743557-5d703b00-3e9b-11e9-9b6a-0261947342fe.png)

There is an opportunity to provide comments, which I did. I included a link to this issue and other comments, but not that this issue affects other open source projects, too. I had already submitted my issue before then. 

I can't say for certain, but it felt like no analyst actually looked at the case. Perhaps an analyst would look at it if the automated process had flagged a file. Because no file was flagged as malicious I'm not sure that any human saw (or will see) my comment.

**Comment by lief-erickson** [comment]
Update from Microsoft...

Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. 3. Run “MpCmdRun.exe -SignatureUpdate” 

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by lief-erickson** [comment]
I completed the steps suggested by Microsoft. I then scanned `dita-ot-3.3.zip`. No issues were found.

![image](https://user-images.githubusercontent.com/10221562/53873969-b78b1080-4001-11e9-8ea9-4c337d351237.png)

If others have the same results, then perhaps this issue can be closed?

**Comment by qvrijt** [comment]
Windows Defender, with latest updates on March 8
Downloaded dita-ot-3.3.zip, 
- Windows Defender accepts the download. 
- After specific scanning of the zip file, also no threats detected.
Repeated the process for dita-ot-3.2.1.zip.
- org.dita.pdf2.fop/lib/batik-all-1.10.jar is now accepted in both cases.
My issue seems solved.
