### ISSUE TITLE
Topic conref itself not work 

### ISSUE THREAD

**Issue by my-f** [dita-ot/dita-ot#3172]
my topic file:

    <section id="section_ks2_h1k_ggb"><title>test-conref</title><p>my test</p></section>
    <section conref="#concept_pkn_5l1_yfb/section_ks2_h1k_ggb" id="section_ycv_j1k_ggb"/>

dita-ot command:
./bin/dita -i out/test-conref.dita -v -f html5 -o out/

dita-ot version: 3.0.4

Can not generate html file,but two .css files

    <section id="section_ks2_h1k_ggb"><title>test-conref</title><p>my test</p></section>
    <section conref="#concept_pkn_5l1_yfb/section_ks2_h1k_ggb" id="section_ycv_j1k_ggb"/>

**Comment by raducoravu** [comment]
I see you posted a complete example on the DITA OT users list, I'm pasting it here:

            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
            <concept id="concept_pkn_5l1_yfb" xml:lang="zh-CN">
                <title>check</title>
                <shortdesc></shortdesc>
                <conbody>
                    <p>test</p>
            <section id="section_ks2_h1k_ggb">
            <title>test-conref</title>
            <p>my test</p>
            </section>
            <section conref="#concept_pkn_5l1_yfb/section_ks2_h1k_ggb" id="section_ycv_j1k_ggb"/>
                  
                </conbody>
            </concept>

I cannot reproduce your problem using DITA OT 3.2.1, the HTML file is properly generated and the conref is properly expanded.
