### ISSUE TITLE
Setting an id attribute on a "dt" duplicates it twice in the XSL-FO file

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3180]
I have a DITA topic with a simple definition list:

            <dl>
                <dlentry>
                    <dt id="dtid">dasdas</dt>
                    <dd/>
                </dlentry>
            </dl>

When generating classic PDF, the id gets set both on a fo:block and a fo:inline so the Apache FOP generates a warning for it.

**Comment by infotexture** [comment]
Resolved with #3185.
