### ISSUE TITLE
plugin.rnc missing from distribution

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3183]
Reported on the DITA OT users list:

>Is there some reason why plugin.rnc referenced in plugins is specifically excluded from the build?

I also encountered the same problem when integrating DITA OT 3.2.1 in Oxygen, I had to manually copy the plugin.rnc in there because Oxygen uses the RNC file for plugin.xml validation and content completion.

**Comment by jelovirt** [comment]
It’s probably been left out by accident.

**Comment by jelovirt** [comment]
When `config` directory was added, we stopped distributing `resources`, because those files are in `dost.jar`. Not sure if we should stick

1.  `plugin.rnc` into `resources`, or
2.   place everything into `config`.
