### ISSUE TITLE
Classification Map - Bug in DITA 1.3 specification XML Schemas 

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3202]
This Classification DITA Map based on the XML Schema should be considered valid:

        <map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="urn:oasis:names:tc:dita:spec:classification:xsd:classifyMap.xsd">
            <title></title>
            <topicref>
                <topicsubject>
                    <subjectref/>
                    <subjectref/>
                </topicsubject>
            </topicref>
        </map>

but it's not. 
In the XML Schema "org.oasis-open.dita.v1_3\schema\subjectScheme\xsd\classifyMap.xsd" next to this group reference:

        <xs:group ref="glossref-d-topicref"/>

there should be another one:

        <xs:group ref="classify-d-topicref"/>

**Comment by drmacro** [comment]
I have verified that this error is in the TC-provided shell. The TC-provided shells are not normative so this does not require an errata but we certainly need to fix the shell. Not sure what the process is there but shouldn't be a big deal. Probably need to confer with Robert on how the grammars are coordinated between the TC and the OT team.

**Comment by robander** [comment]
Reported to DITA TC here: https://lists.oasis-open.org/archives/dita/201911/msg00006.html

My preference would be to have the TC create a new branch with that fix, and we update our shipped copy accordingly.
