### ISSUE TITLE
Getting DOTX061W when chunking map with keydefs setting hrefs to topic files

### ISSUE THREAD

**Issue by caotrem** [dita-ot/dita-ot#3203]
## Expected Behavior
The publishing process should run without warnings.

## Actual Behavior
When publishing a ditamap with `<keydef>` elements referencing topics via the `@href` attribute and setting `@chunk=to-content` on the `<map>` element warnings of type 

`[DOTX061W][WARN] ID '%1' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.`

 are shown in the command line.

The output looks okay, but the warning is wrong. There are topics referenced. See code example at **Steps to Reproduce**

## Steps to Reproduce

[example.zip](https://github.com/dita-ot/dita-ot/files/2836238/example.zip)

Remove the `@chunk` attribute in the `<map>` in `root.ditamap` and everything runs fine without warnings

## Environment

* DITA-OT version: Tested with dita-ot-3.2.1 and dita-ot-2.5.4 and dita-ot-3.3.0-SNAPSHOT+07cf66a
* Operating system and version:
Windows 10 
![image](https://user-images.githubusercontent.com/47040897/51772305-f5844300-20eb-11e9-9fa3-042883e0f60a.png)

* How did you run DITA-OT?
Warnings occur:
   dita-ot-3.3.0\bin\dita --input=root.ditamap --format=html5 (SNAPSHOT+07cf66a)
  dita-ot-3.2.1\bin\dita --input=root.ditamap --format=html5
   dita-ot-2.5.4\bin\dita --input=root.ditamap --format=html5
   dita-ot-2.5.4\bin\dita --input=root.ditamap --format=pdf2
No warnings occur:
   dita-ot-3.3.0\bin\dita --input=root.ditamap --format=pdf2 (SNAPSHOT+07cf66a)
   dita-ot-3.2.1\bin\dita --input=root.ditamap --format=pdf2

* Transformation type:
HTML5
PDF

**Comment by robander** [comment]
I no longer get any errors for PDF for this; for HTML I don't get the `DOTX061W1 anymore. I get the following messages:

```
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:6:55: [DOTX061W][WARN]: ID 'id5' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:6:55: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'root.dita#id5'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:6:55: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'root.dita#id5'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:11:59: [DOTX061W][WARN]: ID 'id1' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:11:59: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'root.dita#id1'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:11:59: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'root.dita#id1'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:12:57: [DOTX061W][WARN]: ID 'id2' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:12:57: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'root.dita#id2'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:12:57: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'root.dita#id2'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:13:57: [DOTX061W][WARN]: ID 'id3' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:13:57: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'root.dita#id3'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:13:57: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'root.dita#id3'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:14:57: [DOTX061W][WARN]: ID 'id4' was used in topicref tag but did not reference a topic element. The href attribute on a topicref element should only reference topic level elements.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:14:57: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'root.dita#id4'.
[move-meta] file:/C:/dita-ot/TESTGITHUB/3203/root.ditamap:14:57: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'root.dita#id4'.
```

I'm not sure how exactly to resolve that but it's clearly not a good result. We have key definitions for topics that are (or sort of are) merged into one merged doc, so we rewrite them, but they aren't actually merged because they are just key definitions so they should not be there. As long as keys are resolved before chunking it might be best if key definitions are ignored for this step, provided that the key resolution has already moved the appropriate metadata from the definition.
