### ISSUE TITLE
Auto generate glossaries list for PDF and HTML-based outputs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3206]
Use case from one of our clients:
I have a single common submap which defines about 100 key definitions, each bound to a glossentry topic.
And I have multiple master DITA Maps which import the submap. Some of the topics in the master DITA Map use some of the keys, but not all of them. So for each master DITA Map right now I need to explicitly refer in the table of contents to the used glossary entries.
Maybe when pre-processing the topics, all references to glossentries could be gathered and the bookmap could be modified to contain them in the place of the "glosslist" element:

https://www.oxygenxml.com/dita/1.3/specs/langRef/technicalContent/glossarylist.html

**Comment by drmacro** [comment]
I will be developing something for this in the context of the paper I'm doing for DITA NA with Wayne Brissette. There is a challenge however, in that you can't have links to glossary entry topics that are not referenced using normal-role topicrefs but if you have normal-role topicrefs what do you do with them in the context of a generated glossary? This is a DITA architecture issue, not a DITA OT issue but it requires coming up with some kind of convention and/or map rewriting during preprocessing.
