### ISSUE TITLE
Feedback about integrated extension functions support added to DITA OT

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3225]
It's about this pull request which added support for integrated extension functions in the DITA OT XSLT module:
https://github.com/dita-ot/dita-ot/pull/2880

There was recently a discussion on the Saxon mailing list started by @drmacro:
https://sourceforge.net/p/saxon/mailman/saxon-help/?viewmonth=201902&viewday=18

and one of the posters there had some feedback that I will summarize below:

1.

> If a dita-ot feature, was there some coordination with Saxonica on
the use of net.sf.saxon.lib.ExtensionFunctionDefinition as the name
of the service? I wonder if that could lead to complications should Saxonica later
decide to use such a ServiceLoader in Saxon itself. I haven't played
much with multiple ServiceLoaders looking for the same service ...
I suppose if called in different class loader contexts they could
end up finding different providers, but maybe that's not a big deal.

2.

> P.S.: This test

https://github.com/dita-ot/dita-ot/blob/0b3e3d221fe8e78286f88ad81ce30a872beaf3fc/src/main/java/org/dita/dost/module/XsltModule.java#L218

> looks as if the simpler (tf instanceof
net.sf.saxon.TransformerFactoryImpl) would test exactly the condition
wanted, without the potential to NPE (if a null tf is passed) or
ClassCastException (in the unlikely case a tf is passed of some type
<T super net.sf.saxon.TransformerFactoryImpl>; unlikely because it
may be that no other such instantiable T exists anyway). Sometimes
the simplest ways are still the best.

3.

> I also wondered why

https://github.com/dita-ot/dita-ot/blob/0b3e3d221fe8e78286f88ad81ce30a872beaf3fc/src/main/java/org/dita/dost/module/XsltModule.java#L233

> takes the ExtensionFunctionDefinition instance that the ServiceLoader
just gave it, gets its class, then makes a new instance.

**Comment by raducoravu** [comment]
In my opinion 2 and 3 make sense. For 1 we could maybe ask Michael K's opinion but changing the service name to some DITA OT specific key will break compatibility for already implemented extension functions.

**Comment by jelovirt** [comment]
Case 3, the reason is that the service loader will always return the same instance. In order to not force the function to be thread-safe, we create a clone of it.

**Comment by raducoravu** [comment]
@jelovirt Ok, so if the service loader caches the instances it makes sense to clone them. And calling "java.util.ServiceLoader.reload()" resets the caches for every usage of ServiceLoader so it's not a good idea to call it.

**Comment by raducoravu** [comment]
These problems do not seem to exist anymore.
