### ISSUE TITLE
Coderef using keyref also prints temporary file name

### ISSUE THREAD

**Issue by qvrijt** [dita-ot/dita-ot#3232]
## Expected Behavior

I am using a codeblock with coderef to a C# file pointed to by a keyref.
Only the file content is listed in the codeblock. 

Following snapshot shows output using direct href path to the same file.
![image](https://user-images.githubusercontent.com/41584738/53175086-941c9a80-35eb-11e9-9602-90b78da1f2ab.png)

## Actual Behavior

After the codeblock, the file name of the temporary file is printed.
![image](https://user-images.githubusercontent.com/41584738/53175259-e1007100-35eb-11e9-8a36-2d72f5d8a0ae.png)

## Environment

* DITA-OT version: 3.2.1 out-of the box, no external plugins
* Operating system and version: Windows 10
* How did you run DITA-OT? calling dita.bat 
* Transformation type:  PDF, using FOP

My bookmap project used:
[coderef-test.zip](https://github.com/dita-ot/dita-ot/files/2889667/coderef-test.zip)

**Comment by robander** [comment]
Reproduced in 3.3.4 with both HTML and PDF.

In HTML output, the last line of the code block includes the full path name of the snippet:
`}snippets/csharp-regions-simple.cs`

**Comment by masofcon** [comment]
Same in DITA-OT version 3.4.1

Do you have any plans to fix this?

**Comment by masofcon** [comment]
> Reproduced in 3.3.4 with both HTML and PDF.
> 
> In HTML output, the last line of the code block includes the full path name of the snippet:
> `}snippets/csharp-regions-simple.cs`

Same in DITA-OT version 3.4.1

Do you have any plans to fix this?

**Comment by jelovirt** [comment]
Unable to reproce with 3.5. @robander, how about your?
