### ISSUE TITLE
PDF transformation ignores --args.rellinks=nofamily

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#3233]
## Expected Behavior

According to the [documentation](https://www.dita-ot.org/dev/parameters/parameters-base.html#base__args.rellinks), the `args.rellinks` parameter should default to `nofamily` for PDF output:

> • `nofamily` – Parent, child, next, and previous links are not included.
> For PDF output, the default value is `nofamily`. For all other formats, the default value is `all`.

## Actual Behavior

Family links are included in PDF output regardless of this parameter setting.

## Steps to Reproduce

Run the `dita` command on the DITA-OT documentation bookmap and generate default PDF output:

    dita --input=userguide-book.ditamap --format=pdf

Pass the `args.rellinks` parameter:

    dita --input=userguide-book.ditamap --format=pdf --args.rellinks=nofamily

In both cases, family links are included in the output, for example in _“[Customizing HTML output](https://www.dita-ot.org/dev/topics/html-customization.html)”_, which defines [family collections](https://github.com/dita-ot/docs/blob/develop/topics/html-customization.ditamap#L7-L8).

## Environment

* DITA-OT version: latest `develop`
* Operating system and version: macOS
* How did you run DITA-OT: `dita` command
* Transformation type: PDF

💯

**Comment by robander** [comment]
I'm not sure, but ... I don't think this is a change, and I think it may come back to two different uses of the word "family".

For as long as I can remember the desire for PDF was to turn off next/previous and parent/child links, which were grouped as "family" links. It looks like it (still) correctly excludes all of those link roles by default - I'm not getting the parent/child links, and if I set `collection-type="sequence"` I'm not getting next/previous links.

The `collection-type="family"` attribute generates links in between all of the child topicrefs in that group, but they're defined with `role="sibling"`. I think I've always included those (inside / outside of DITA-OT), under the assumption that next/previous are probably on the same page and should be removed, while "sibling" can end up 3 or 30 or 100 pages apart and should be preserved. It appears that's what is happening here - the "sibling" links are preserved - and it looks like the same result going back at least to 2.5.4.

None of that is to say "this behavior is good / right / obvious" ... not sure I've ever thought about the contradiction in having the parameter value `nofamily` include links generated by `collection-type="family"`. Basically ... I think this was the design, just not sure it makes sense when I step back and look at it that way.

**Comment by robander** [comment]
I guess in a larger since this means:

1. PDF is still defaulting to `args.rellinks=nofamily`
1. That option is working the same as in previous releases
1. That option is confusing because "no family" includes links that we call "sibling"

**Comment by infotexture** [comment]
@robander Thanks for your analysis, that's probably what's going on.

It's certainly counterintuitive that "siblings" aren't part of the "family" and that an option value named `nofamily` doesn't **not** exclude links created by `collection-type="family"` markup. 🤔 

Your point about preserving sibling links by default makes sense for large documents. I noticed this during a recent refactoring that split up a large topic into multiple (short) subtopics, several of which appear on the same page in PDF output.

In this case, I'd like to be able to suppress the creation of sibling links along with the other auto-generated variants that depend on topics' proximity in the map, but still create related links for any topics that were intentionally defined via relationship tables.

Unless I'm overlooking something, it seems there's currently no way to achieve this, as the next arrow in the quiver is `none`.

**Comment by infotexture** [comment]
Closing as `invalid` — working as designed per https://github.com/dita-ot/dita-ot/issues/3233#issuecomment-466231749.
