### ISSUE TITLE
Problem when referring to remote image without scope external

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3246]
Tested with DITA OT 3.2.1. 
Let's say I have a DITA topic with this image reference inside it:

         <image href="https://www.oxygenxml.com/img/Content_fusion80.png"/>

When producing HTML-based output the .job.xml contains this reference:

         <file src="https://www.oxygenxml.com/img/Content_fusion80.png"
            uri="https://www.oxygenxml.com/img/Content_fusion80.png"
            path="https:\www.oxygenxml.com\img\Content_fusion80.png"
            result="https://www.oxygenxml.com/img/Content_fusion80.png" format="image"/>

and in my opinion the @path attribute value is wrong. Then because of this the "copy" stage breaks trying to use that @path attribute value:

      BUILD FAILED
     D:\projects\eXml\frameworks\dita\DITA-OT3.x\build.xml:46: The following error occurred while executing this line:
     D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:452: java.nio.file.InvalidPathException: Illegal char <:> at index 66: D:\projects\eXml\samples\dita\flowers\out\webhelp-responsive\https:\www.oxygenxml.com\img\Content_fusion80.png
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)

**Comment by robander** [comment]
We fixed this for `<object>` elements not long ago by explicitly looking for absolute paths, and leaving those out of the Job. That was largely because `<object>` does not allow for the `@scope` attribute, while images do, so this could be avoided by setting `scope="external"`. 

At the same time ... maybe we should apply the same processing to images, because it won't ever make sense to copy an image with an absolute path?

**Comment by raducoravu** [comment]
It would probably make sense if a similar behavior would be done for both image and object. Somehow the example above used to work in dita ot 2.x without the need to specify scope external. Would adding this behavior go against the specification?

**Comment by raducoravu** [comment]
Another one of our users has links like this:

        <xref href="http://www.google.com/index.html" format="html"/>

which worked in DITA OT 2.x even if the scope external was not set on them. They somehow want this to work even without setting scope=external on the xref.

**Comment by raducoravu** [comment]
The DITA 1.3 specs says something like:

    However the processing default is "external" whenever the absolute URI in the @href attribute begins with one of the following schemes:

    http
    https
    ftp
    mailto

    Processors can consider additional URI schemes as "external" by default.
