### ISSUE TITLE
My anti-virus says 3.21 and 3.3 contain a Trojan

### ISSUE THREAD

**Issue by bjthomson** [dita-ot/dita-ot#3247]
## Copy of the error message, log file or stack trace
Trojan:Java/Tisifi.C
This program is dangerous and executes commands from an attacker.
containerfile: E:\Downloads\DITA\dita-ot-3.2.1.zip
and
containerfile: E:\Downloads\DITA\dita-ot-3.3.zip

* DITA-OT version:

3.2.1 and 3.3
* Operating system and version:
 Windows 10

**Comment by raducoravu** [comment]
Duplicate of: https://github.com/dita-ot/dita-ot/issues/3171
