### ISSUE TITLE
RelaxNG content model validation no longer works

### ISSUE THREAD

**Issue by chrispitude** [dita-ot/dita-ot#3252]
## Expected Behavior
When tags are present that invalidate the content model, DITA-OT 3.1.3 would issue errors:

> $ ~/dita-ot-3.1.3/bin/dita -i t.dita -f xhtml
> Error: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'file:/mnt/c/Users/chrispy/Documents/DITA/xml_books/dg_tclug/t.dita'.: [10:31] element "foobar" not allowed here; expected the element end-tag, text or element "b", "boolean", "cite", "data", "data-about", "div", "dl", "draft-comment", "fig", "fn", "foreign", "hazardstatement", "i", "image", "imagemap", "indexterm", "indextermref", "keyword", "line-through", "lines", "lq", "note", "object", "ol", "overline", "ph", "pre", "q", "required-cleanup", "simpletable", "sl", "sort-as", "state", "sub", "sup", "table", "term", "text", "tm", "tt", "u", "ul", "unknown" or "xref"

## Actual Behavior
In DITA-OT 3.3, no content model violations are issued. Instead, there are strange messages issued and the transformation completes "successfully":

> $ ~/dita-ot-3.3/bin/dita -i t.dita -f xhtml
>  [pipeline] [DOTX074W][WARN]: No formatting defined for unknown class attribute value "".
>  [pipeline] [DOTX074W][WARN]: No formatting defined for unknown class attribute value "".

## Possible Solution
Unsure.

## Steps to Reproduce
Validate the attached file as follows:

dita -i foobar.dita -f xhtml

[foobar.zip](https://github.com/dita-ot/dita-ot/files/2957358/foobar.zip)

## Copy of the error message, log file or stack trace
>  [pipeline] [DOTX074W][WARN]: No formatting defined for unknown class attribute value "".
>  [pipeline] [DOTX074W][WARN]: No formatting defined for unknown class attribute value "".

## Environment
Windows Subsystem for Linux (Ubuntu 18.04) on Windows 10
DITA-OT 3.3

**Comment by drmacro** [comment]
The empty @class values suggests that the RNG DITA compatibility support library is not being used.

**Comment by chrispitude** [comment]
Confirmed and closed as user error.

**Comment by chrispitude** [comment]
Yes, this was it. I assumed the RelaxNG enhancements in 3.2 meant that this
was no longer needed. I'll close the issue. Thanks!

 - Chris

**Comment by raducoravu** [comment]
@chrispitude DITA OT 3.3 out out the box expands DITA class attribute values based on the RelaxNG schemas associated to the topic but it does not provide on the fly validation at publishing time of the XML content. @jelovirt, was there an issue to also provide validation at publishing time for RNG-based topics or should we keep this one?

**Comment by chrispitude** [comment]
If I was getting empty @class attribute messages (""), does that mean
@class wasn't getting populated by default as expected in DITA-OT 3.3?

Here was the closed issue that led me to believe validation was implemented:

https://github.com/dita-ot/dita-ot/issues/2019

**Comment by raducoravu** [comment]
@chrispitude your original report is from what I understood for a RNG-based DITA topic which somewhere inside has an XML element named "foobar" which is not defined in the schema. As I said in my last comment, the class attribute values should be expanded automatically on all DITA elements which have a correspondent in the RNG schema but for that particular element not defined in the schema no class attribute value will be set. So #2019 was partially implemented, class attribute values are automatically expanded but validation problems (like elements not defined in the schema) are not reported and do not break the build.

**Comment by chrispitude** [comment]
Okay, I think I understand now. I would argue that an empty @class
attribute should be a blocking error even if true RelaxNG content model
validation is not performed, but I understand the need for backward
compatibility. And the point is moot once validation is supported and the
unknown element becomes a validation error.

With the closure of issue #2019 ("Support RELAXNG parsing and validation"),
there is no longer an open issue requesting RelaxNG *validation*. I will
open one.

Thanks guys!

 - Chris
