### ISSUE TITLE
Natively support RelaxNG validation

### ISSUE THREAD

**Issue by chrispitude** [dita-ot/dita-ot#3253]
## Description
This is a request to natively perform RelaxNG validation by default. Issue #2019 requested native class attribute propagation and validation, but the issue was closed once the former was implemented; this issue carries the torch for the latter request.

## Possible Solution
Include the dita-ng-library in the DITA-OT installation by default. Or, run jing (or equivalent) at an existing suitable point in the processing pipeline.

## Potential Alternatives
Currently I manually install dita-ng-library with each new DITA-OT release.

**Comment by robander** [comment]
Somehow this was left open, but support for this was added in DITA-OT 3.2. Marking this one closed.

**Comment by chrispitude** [comment]
@robander - can we please reopen this issue?

According to #3252, in [this comment](https://github.com/dita-ot/dita-ot/issues/3252#issuecomment-472397728) from @raducoravu,

> So #2019 was partially implemented [in DITA-OT 3.2], class attribute values are automatically expanded but validation problems (like elements not defined in the schema) are not reported and do not break the build.

If the input files have incorrectly structured content, **the DITA-OT does not complain**.

When #3252 was closed with a resolution that `dita-ng-library` must be manually installed to get RelaxNG validation, I opened this issue for native DITA-OT support.

Using the testcase from #3252, note that neither of these DITA-OT versions complains of invalid elements:

```
$ ~/dita-ot-3.2/bin/dita -i foobar.dita -f dita -o out1
[normalize] file:/mnt/c/nobackup/validation/out1/foobar.dita
$ ~/dita-ot-3.6.1/bin/dita -i foobar.dita -f dita -o out2
[normalize] file:/mnt/c/nobackup/validation/out2/foobar.dita
$
```

but `jing` (the RelaxNG validator) does report the issues:

```
$ jing \
  -C dita-ot-3.6.1/catalog-dita.xml \
  dita-ot-3.6.1/plugins/org.oasis-open.dita.v1_3/rng/base/rng/basetopic.rng \
  foobar.dita
/home/chrispy/foobar.dita:10:31: error: element "foobar" not allowed here; expected the element end-tag, text or element "b", "boolean", "cite", "data", "data-about", "div", "dl", "draft-comment", "fig", "fn", "foreign", "hazardstatement", "i", "image", "imagemap", "indexterm", "indextermref", "keyword", "line-through", "lines", "lq", "note", "object", "ol", "overline", "ph", "pre", "q", "required-cleanup", "simpletable", "sl", "sort-as", "state", "sub", "sup", "table", "term", "text", "tm", "tt", "u", "ul", "unknown" or "xref"
/home/chrispy/foobar.dita:11:12: error: element "foobar" not allowed here; expected the element end-tag, text or element "b", "boolean", "cite", "data", "data-about", "div", "dl", "draft-comment", "fig", "fn", "foreign", "hazardstatement", "i", "image", "imagemap", "indexterm", "indextermref", "keyword", "line-through", "lines", "lq", "note", "object", "ol", "overline", "ph", "pre", "q", "required-cleanup", "simpletable", "sl", "sort-as", "state", "sub", "sup", "table", "term", "text", "tm", "tt", "u", "ul", "unknown" or "xref"
```

Interestingly, `jing` is in the DITA-OT tree:

```
$ find dita-ot* -name '*jing*'
dita-ot-3.2/lib/jing-2.0.0.jar
dita-ot-3.6.1/lib/jing-20181222.jar
```

but we don't seem to use it for validation.

**Comment by robander** [comment]
Re-opening after discussion at DITA-OT meet-up call today - this issue still exists

**Comment by chrispy-snps** [comment]
I think this can be marked as fixed now. Thanks for implementing it!
