### ISSUE TITLE
Report template plug-in suggestion

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#3254]
## Description
After seeing this thread: [Generating a reference report](https://groups.yahoo.com/neo/groups/dita-users/conversations/topics/44509), I wondered how a plug-in might generate such a report. I've looked at the impressive list of plug-ins, but none stood out as a starting point for a report.

## Possible Solution
I suppose the obvious way to generate a report would be with a transformation that 'kills off' the majority of elements, leaving only the desired elements. The equally obvious drawback is the maintenance overhead with any specialisation, or new versions of DITA.

## Potential Alternatives
The thread mentions the use of an XPath query, and this seems a whole lot more sensible. Filter out only the desired elements. So the question / suggestion is: "Is it possible to build an XPath query into a plug-in?" If so, would it be reasonable to have a plug-in that demonstrates this?

**Comment by raducoravu** [comment]
At some point I created a DITA OT plugin which produces a single merged XML document from the entire structure of DITA Maps and topics:

https://github.com/oxygenxml/dita-merged

so this plugin could be extended to also apply an XSLT stylesheet on the merged XML document which should have all the information needed to generate any report.

**Comment by jelovirt** [comment]
Closing as discussion. Mailing lists or DITA-OT Slack is more suitable for this discussion.
