### ISSUE TITLE
External xrefs with a certain anchor format cause fatal error

### ISSUE THREAD

**Issue by TinoKraft68** [dita-ot/dita-ot#3261]
For example the following URLs cannot be used as link targets
* https://tagmanager.google.com/#/admin/accounts/create
* https://tagmanager.google.com/?hl=en#/admin/accounts/create

Tested with the following link format:
`<xref href="https://tagmanager.google.com/#/admin/accounts/create" format="html" scope="external">link text</xref>`

Using the DITA-OT3.x bundled with Oxygen 21

**Comment by raducoravu** [comment]
Using DITA OT 3.2.1 I can publish a topic containing such a link without any problems.
Is this a publishing or a validation problem?
The link can be alternatively written by escaping the "/" which occur after the anchor part:

            "https://tagmanager.google.com/#%2Fadmin%2Faccounts%2Fcreate"

**Comment by TinoKraft68** [comment]
> Using DITA OT 3.2.1 I can publish a topic containing such a link without any problems.
> Is this a publishing or a validation problem?
> The link can be alternatively written by escaping the "/" which occur after the anchor part:
> 
> ```
>         "https://tagmanager.google.com/#%2Fadmin%2Faccounts%2Fcreate"
> ```

I found the issue when trying to transform a Ditamap to XHTML, which gave an unnamed fatal error in Oxygen. I then found the issue by validating all the map's files.

Thanks for the escape suggestion, it worked for me. In fact, you only need to escape the first "/" after the anchor character.

**Comment by raducoravu** [comment]
I also cannot reproduce this problem publishing with an older DITA OT (version 2.5.4).
Oxygen reports a validation error on the link but I'm not sure that in this case our reported error is accurate or not, I will add an internal issue on our side to look into this.
Indeed, the workaround to avoid Oxygen complaining about the link is to escape at least the first "/".
