### ISSUE TITLE
Unable to run pdf transformation with Java API

### ISSUE THREAD

**Issue by cinthyargc** [dita-ot/dita-ot#3266]
### Description of the Issue
I am unable to run any PDF transformation using Java API (https://www.dita-ot.org/3.3/reference/java-api.html). I was able to transform to PDF with previous versions of Dita-OT

**How to reproduce?**
1. Install Dita-OT 3.3
1. Create a sample java class with following content:
```java
String ditaOTDir = ".../dita-ot-3.3/";
String tmpDir = "<tmp-dir>";
String outputDir = "<output-dir>";
String mapFile = "<map-file>";

	// Create a reusable processor factory with DITA-OT base directory and temporary directory
	ProcessorFactory ditaProcessFactory = ProcessorFactory.newInstance(new File(ditaOTDir));
	ditaProcessFactory.setBaseTempDir(new File(tmpDir));

	// Create a processor using the factory and configure the processor
	Processor ditaProcessor = ditaProcessFactory.newProcessor("pdf")
		.setInput(new File(mapFile))
		.setOutputDir(new File(outputDir))
		.setProperty("args.input", mapFile)
		.setProperty("args.debug", "true")
		.setProperty("org.dita.pdf2.i18n.enabled", "false")
		.createDebugLog(true);

	// Run conversion
	ditaProcessor.run();
```
3. Exception thrown:
```xml
Exception in thread "main" org.dita.dost.exception.DITAOTException
	at org.dita.dost.Processor.run(Processor.java:219)
	at com.ibm.ditaot.java.sample.RunDitaOT.main(RunDitaOT.java:47)
Caused by: /Users/crgarcia/Documents/dita-ot-3.3/plugins/org.dita.pdf2/build.xml:151: The following error occurred while executing this line:
/Users/crgarcia/Documents/dita-ot-3.3/plugins/org.dita.pdf2.fop/build_fop.xml:144: taskdef class org.apache.fop.tools.anttasks.Fop cannot be found
 using the classloader AntClassLoader[]
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:571)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
...
Caused by: /Users/crgarcia/Documents/dita-ot-3.3/plugins/org.dita.pdf2.fop/build_fop.xml:144: taskdef class org.apache.fop.tools.anttasks.Fop cannot be found
 using the classloader AntClassLoader[]
	at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:597)
...
```

**Environment:**
MacOs
DITA-OT 3.3 

Thank you!

**Comment by jelovirt** [comment]
Do you have FOP plugin related JARs in you CLASSPATH? The Java API does not manage classpath for you, unlike Ant or the DITA-OT CLI.

**Comment by cinthyargc** [comment]
@jelovirt, Thanks for your reply.

I don't have them on my classpath, I have recently moved from DITA-OT 2.5.4, and in that version I did not require any FOP jar in my classpath.

I don't know if it is related, but I have just noticed `dita.conductor.lib.import` extension point from https://www.dita-ot.org/dev/topics/plugin-javalib.html 

I think it would be great if DITA-OT 3.3 could resolve the jars inside the plug-ins, just like 2.5.4 version used to do.

**Comment by jelovirt** [comment]
@cinthyargc The Java API has been explicitly designed to not to handle the classpath, so it's unlikely this will change. If it worked with 2.5, it was because the FOP plugin Ant script was written that way.

**Comment by cinthyargc** [comment]
Thank you @jelovirt!

I have included the additional libraries to my classpath, it is working now.
In case some one else jump into this same issue, below the libraries I had to include to make it run.


![image](https://user-images.githubusercontent.com/37708042/55013584-04358c00-4faf-11e9-83c2-2621ea1098ed.png)
