### ISSUE TITLE
Backslash Escapes not working in Markdown input

### ISSUE THREAD

**Issue by tokup** [dita-ot/dita-ot#3267]
The escape sequences doesn't work in DITA (version 3.3):

```
\\   backslash
\`   backtick
\*   asterisk
\_   underscore
\{\}  curly braces
\[\]  square brackets
\(\)  parentheses
\#   hash mark
\+	plus sign
\-	minus sign (hyphen)
\.   dot
\!   exclamation mark
```

The leading '`\`' is not removed.

**Comment by raducoravu** [comment]
I can reproduce this problem too, the default "com.vladsch.flexmark.html.HtmlRenderer" does not have this problem.
@tokup can you add an issue here instead? https://github.com/jelovirt/org.lwdita/issues

**Comment by infotexture** [comment]
Resolved in jelovirt/org.lwdita@5532f7f per jelovirt/org.lwdita#49 for `org.lwdita` version 2.3.1, which is queued for the 3.4 release with #3371.

**Comment by ritti** [comment]
Can you please reopen this issue. Detailed description why it should be reopened is described in https://github.com/jelovirt/org.lwdita/issues/49

**Comment by raducoravu** [comment]
@ritti this bug and https://github.com/jelovirt/org.lwdita/issues/49 are about Markdown to DITA conversions, publishing Markdown content referenced in a DITA Map to various output formats. And this seems to work with DITA OT 3.4.
You seem to want this the other way around, DITA to Markdown. Maybe you can add a new issue for this on the "org.lwdita" project along with some samples, explaining what you expect to happen and what happens instead.

**Comment by ritti** [comment]
Agree. Thanks. -> https://github.com/jelovirt/org.lwdita/issues/61
