### ISSUE TITLE
Integrator class uses method not defined in "xml-apis-1.4.01.jar"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3272]
It uses this method "XMLInputFactory.newFactory()" which is defined in the JRE 1.8 default classes but is not defined in the similar implementation from "xml-apis-1.4.01.jar". Publishing probably works because the Java default classes are usually stronger than the extra JAR libraries from the classpath.
But when compiling the "dos.jar" if for example the compilation classpath favors "xml-apis-1.4.01.jar" instead of the runtime libraries, you get a compilation error.
I suggest replacing "newFactory()"=>"newInstance()" which does the same thing.

**Comment by jelovirt** [comment]
Fixed by #3273
