### ISSUE TITLE
OT 3.3.1 with Saxon-PE  9.9.1 fails in mapref

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#3279]
When I use the newest Saxon-PE release (9.9.1.2), DITA-OT 3.3.1 fails with `java.lang.NoSuchMethodError`. It woks fine with Saxon-PE 9.8.0.14.

**[command-line]**
   bin/dita -f pdf -i docsrc/samples/sequence.ditamap -o out -l out/log.txt -v

**[Log File:out/log.txt]**

init:

dita2pdf2.init:

init-properties:

check-arg:
    [mkdir] Created dir: C:\Users\toshi\AppData\Local\Temp\temp20190410101743125

log-arg:
     [echo] *****************************************************************
     [echo] * basedir = D:\DITA-OT\dita-ot-3.3.1
     [echo] * dita.dir = D:\DITA-OT\dita-ot-3.3.1\bin\..
     [echo] * transtype = pdf
     [echo] * tempdir = C:\Users\toshi\AppData\Local\Temp\temp20190410101743125
     [echo] * outputdir = D:\DITA-OT\dita-ot-3.3.1\out
     [echo] * clean.temp = true
     [echo] * DITA-OT version = 3.3.1
     [echo] * XML parser = Xerces
     [echo] * XSLT processor = Saxon
     [echo] * collator = ICU
     [echo] *****************************************************************
     [echo] #Ant properties
     [echo] #Wed Apr 10 10:17:43 JST 2019
     [echo] dita.plugin.org.dita.base.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.base
     [echo] preprocess.chunk.skip=true
     [echo] dita.temp.dir=C\:\\Users\\toshi\\AppData\\Local\\Temp\\temp20190410101743125
     [echo] dita.plugin.org.dita.troff.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.troff
     [echo] args.grammar.cache=yes
     [echo] dita.plugin.org.oasis-open.xdita.v0_2_2.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.oasis-open.xdita.v0_2_2
     [echo] dita.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\bin\\..
     [echo] dita.plugin.org.dita.pdf2.axf.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2.axf
     [echo] dita.plugin.com.sophos.tocjs.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\com.sophos.tocjs
     [echo] dita.plugin.org.oasis-open.dita.v1_3.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.oasis-open.dita.v1_3
     [echo] dita.plugin.org.lwdita.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.lwdita
     [echo] dita.plugin.org.dita.htmlhelp.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.htmlhelp
     [echo] dita.output.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\out
     [echo] args.rellinks=nofamily
     [echo] dita.plugin.org.dita.eclipsehelp.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.eclipsehelp
     [echo] dita.plugin.org.dita.normalize.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.normalize
     [echo] dita.plugin.org.dita.xhtml.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.xhtml
     [echo] dita.plugin.org.dita.pdf2.xep.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2.xep
     [echo] dita.plugin.org.dita.specialization.dita11.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.specialization.dita11
     [echo] dita.plugin.org.oasis-open.dita.v1_2.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.oasis-open.dita.v1_2
     [echo] dita.plugin.org.dita.pdf2.fop.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2.fop
     [echo] args.input=D\:\\DITA-OT\\dita-ot-3.3.1\\docsrc\\samples\\sequence.ditamap
     [echo] args.xml.systemid.set=yes
     [echo] dita.plugin.org.dita.pdf2.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2
     [echo] dita.plugin.org.dita.html5.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.html5
     [echo] args.logdir=D\:\\DITA-OT\\dita-ot-3.3.1\\out
     [echo] preprocess.copy-image.skip=true
     [echo] *****************************************************************

build-init:

preprocess2.init:
     [echo] *****************************************************************
     [echo] * input = D:\DITA-OT\dita-ot-3.3.1\docsrc\samples\sequence.ditamap
     [echo] *****************************************************************

ditaval-merge:

map-reader:
[map-reader] Using Xerces grammar pool for DTD and schema caching.
[map-reader] Processing file:/D:/DITA-OT/dita-ot-3.3.1/docsrc/samples/sequence.ditamap to file:/C:/Users/toshi/AppData/Local/Temp/temp20190410101743125/f7f208540ed460242874049c8cc5c8f4bcc5665b.ditamap
[map-reader] Serializing job specification
[job-helper] Processing C:\Users\toshi\AppData\Local\Temp\temp20190410101743125\.job.xml to C:\Users\toshi\AppData\Local\Temp\temp20190410101743125\fullditamap.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-3.3.1\plugins\org.dita.base\xsl\job-helper.xsl
   [delete] Deleting: C:\Users\toshi\AppData\Local\Temp\temp20190410101743125\fullditamap.list

map-mapref:
   [mapref] Processing file:/C:/Users/toshi/AppData/Local/Temp/temp20190410101743125/f7f208540ed460242874049c8cc5c8f4bcc5665b.ditamap
Error: java.lang.NoSuchMethodError: net.sf.saxon.Controller.setMessageEmitter(Lnet/sf/saxon/event/Receiver;)V

**Comment by robander** [comment]
The current release of DITA-OT requires 9.8 (which is bundled in the download) to function properly.

I encountered this same issue when testing with 9.9 a few months ago, and tracked it down to a method that moved from the `Controller` class into the `XsltController` class. Based on reading the latest Saxon docs, I think that when we update DITA-OT to ship with 9.9 we will have to switch from calling
`net.sf.saxon.Controller.setMessageEmitter`
to call
`net.sf.saxon.XsltController.setMessageEmitter`

I have not tried any of this and could be wrong, but a few months back I found the latest method documented here: http://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/trans/XsltController.html#setMessageEmitter-net.sf.saxon.event.Receiver-

In the 9.8 docs it's part of the `Controller` class: https://www.saxonica.com/html/documentation9.8/javadoc/net/sf/saxon/Controller.html#setMessageEmitter-net.sf.saxon.event.Receiver-

**Comment by ToshihikoMakita** [comment]
More problem is here. My user must purchase Saxon-PE because they must call external Java function library from DITA-OT 3.2.1. When they use Saxon-PE 9.8.0.15, the build fails with following error (In my test environment: using OT 3.3.1):

**[The Log FIle]**

init:

dita2pdf2.init:

init-properties:

check-arg:
    [mkdir] Created dir: C:\Users\toshi\AppData\Local\Temp\temp20190410115510437

log-arg:
     [echo] *****************************************************************
     [echo] * basedir = D:\DITA-OT\dita-ot-3.3.1
     [echo] * dita.dir = D:\DITA-OT\dita-ot-3.3.1\bin\..
     [echo] * transtype = pdf
     [echo] * tempdir = C:\Users\toshi\AppData\Local\Temp\temp20190410115510437
     [echo] * outputdir = D:\DITA-OT\dita-ot-3.3.1\out
     [echo] * clean.temp = true
     [echo] * DITA-OT version = 3.3.1
     [echo] * XML parser = Xerces
     [echo] * XSLT processor = Saxon
     [echo] * collator = ICU
     [echo] *****************************************************************
     [echo] #Ant properties
     [echo] #Wed Apr 10 11:55:10 JST 2019
     [echo] dita.plugin.org.dita.base.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.base
     [echo] preprocess.chunk.skip=true
     [echo] dita.temp.dir=C\:\\Users\\toshi\\AppData\\Local\\Temp\\temp20190410115510437
     [echo] dita.plugin.org.dita.troff.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.troff
     [echo] args.grammar.cache=yes
     [echo] dita.plugin.org.oasis-open.xdita.v0_2_2.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.oasis-open.xdita.v0_2_2
     [echo] dita.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\bin\\..
     [echo] dita.plugin.org.dita.pdf2.axf.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2.axf
     [echo] dita.plugin.com.sophos.tocjs.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\com.sophos.tocjs
     [echo] dita.plugin.org.oasis-open.dita.v1_3.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.oasis-open.dita.v1_3
     [echo] dita.plugin.org.lwdita.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.lwdita
     [echo] dita.plugin.org.dita.htmlhelp.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.htmlhelp
     [echo] dita.output.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\out
     [echo] args.rellinks=nofamily
     [echo] dita.plugin.org.dita.eclipsehelp.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.eclipsehelp
     [echo] dita.plugin.org.dita.normalize.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.normalize
     [echo] dita.plugin.org.dita.xhtml.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.xhtml
     [echo] dita.plugin.org.dita.pdf2.xep.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2.xep
     [echo] dita.plugin.org.dita.specialization.dita11.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.specialization.dita11
     [echo] dita.plugin.org.oasis-open.dita.v1_2.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.oasis-open.dita.v1_2
     [echo] dita.plugin.org.dita.pdf2.fop.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2.fop
     [echo] args.input=D\:\\DITA-OT\\dita-ot-3.3.1\\docsrc\\samples\\sequence.ditamap
     [echo] args.xml.systemid.set=yes
     [echo] dita.plugin.org.dita.pdf2.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.pdf2
     [echo] dita.plugin.org.dita.html5.dir=D\:\\DITA-OT\\dita-ot-3.3.1\\plugins\\org.dita.html5
     [echo] args.logdir=D\:\\DITA-OT\\dita-ot-3.3.1\\out
     [echo] preprocess.copy-image.skip=true
     [echo] *****************************************************************

build-init:

preprocess2.init:
     [echo] *****************************************************************
     [echo] * input = D:\DITA-OT\dita-ot-3.3.1\docsrc\samples\sequence.ditamap
     [echo] *****************************************************************

ditaval-merge:

map-reader:
[map-reader] Using Xerces grammar pool for DTD and schema caching.
[map-reader] Processing file:/D:/DITA-OT/dita-ot-3.3.1/docsrc/samples/sequence.ditamap to file:/C:/Users/toshi/AppData/Local/Temp/temp20190410115510437/f7f208540ed460242874049c8cc5c8f4bcc5665b.ditamap
[map-reader] Serializing job specification
[job-helper] Processing C:\Users\toshi\AppData\Local\Temp\temp20190410115510437\.job.xml to C:\Users\toshi\AppData\Local\Temp\temp20190410115510437\fullditamap.list
[job-helper] Loading stylesheet D:\DITA-OT\dita-ot-3.3.1\plugins\org.dita.base\xsl\job-helper.xsl
   [delete] Deleting: C:\Users\toshi\AppData\Local\Temp\temp20190410115510437\fullditamap.list

map-mapref:
   [mapref] Error on line 8 column 80 of mapref.xsl:
   [mapref]   Malformed URL plugin:org.dita.base:xsl/preprocess/maprefImpl.xsl(base
   [mapref]   file:/D:/DITA-OT/dita-ot-3.3.1/plugins/org.dita.base/xsl/preprocess/mapref.xsl): unknown
   **[mapref]   protocol: plugin
Error: java.lang.RuntimeException: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: Malformed URL plugin:org.dita.base:xsl/preprocess/maprefImpl.xsl(base file:/D:/DITA-OT/dita-ot-3.3.1/plugins/org.dita.base/xsl/preprocess/mapref.xsl)**

The cause was very curious. `catalog-dita.xml` was generated with `xmlns=''` entries for plugin.

[Catalog  File: dita-ot-3.3.1/plugins/org.dita.base/catalog-dita.xml]

	<?xml version="1.0" encoding="UTF-8"?><catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog" xmlns:dita="http://dita-ot.sourceforge.net">

	  <rewriteURI uriStartString="platform:" rewritePrefix="../../"/>

	  <rewriteURI xmlns="" uriStartString="plugin:org.dita.htmlhelp:" rewritePrefix="../org.dita.htmlhelp/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.base:" rewritePrefix="../org.dita.base/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.pdf2.xep:" rewritePrefix="../org.dita.pdf2.xep/"/><rewriteURI xmlns="" uriStartString="plugin:com.sophos.tocjs:" rewritePrefix="../com.sophos.tocjs/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.pdf2.fop:" rewritePrefix="../org.dita.pdf2.fop/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.eclipsehelp:" rewritePrefix="../org.dita.eclipsehelp/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.specialization.dita11:" rewritePrefix="../org.dita.specialization.dita11/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.normalize:" rewritePrefix="../org.dita.normalize/"/><rewriteURI xmlns="" uriStartString="plugin:org.oasis-open.xdita.v0_2_2:" rewritePrefix="../org.oasis-open.xdita.v0_2_2/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.troff:" rewritePrefix="../org.dita.troff/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.pdf2.axf:" rewritePrefix="../org.dita.pdf2.axf/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.html5:" rewritePrefix="../org.dita.html5/"/><rewriteURI xmlns="" uriStartString="plugin:org.lwdita:" rewritePrefix="../org.lwdita/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.xhtml:" rewritePrefix="../org.dita.xhtml/"/><rewriteURI xmlns="" uriStartString="plugin:org.dita.pdf2:" rewritePrefix="../org.dita.pdf2/"/><rewriteURI xmlns="" uriStartString="plugin:org.oasis-open.dita.v1_2:" rewritePrefix="../org.oasis-open.dita.v1_2/"/><rewriteURI xmlns="" uriStartString="plugin:org.oasis-open.dita.v1_3:" rewritePrefix="../org.oasis-open.dita.v1_3/"/>

	   
	   <nextCatalog catalog="../org.oasis-open.dita.v1_3/catalog.xml"/><nextCatalog catalog="../org.oasis-open.dita.v1_2/catalog.xml"/><nextCatalog catalog="../org.dita.pdf2/cfg/catalog.xml"/><nextCatalog catalog="../org.dita.specialization.dita11/catalog.xml"/><nextCatalog catalog="../org.oasis-open.xdita.v0_2_2/catalog-dita.xml"/>
	  
	</catalog>

As a result my user is very confusing.

**Comment by drmacro** [comment]
In addition to the API changes Robert mentioned, 9.9 changes the API for registering extension functions, which will require a change to the current code for automatic extension function registration for plugins and the corresponding code in plugins that contribute extension functions.

**Comment by jelovirt** [comment]
The namespace issue in catalogs has been fixed in #3287. Can this be closed, given that 3.4 will use Saxon 9.9?

**Comment by ToshihikoMakita** [comment]
> Can this be closed, given that 3.4 will use Saxon 9.9?

Yes, I agree!
