### ISSUE TITLE
Provide option to retain submap details in cleaned merged map

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#3280]
As of 3.3.1 the Clean Map preprocess stage removes the topicgroup elements introduced in earlier phases to capture details about submaps.

This this has the effect of losing key scope definition boundaries, making it impossible to use the final merged map to resolve references to scoped keys.

ideally the the clean map process would simply retain the submap-reflecting topicgroups but that could break processes that make assumptions about the markup structure (e.g., tools that don't account for the possibility of an additional layer of containment around Bookmap chapters managed as submaps or something).

So would like a runtime option to retain the submap topicgroups in the final merged map.

Alternatively, provide an extension point in the clean map transform so that this kind of functionality can be added by plugins.

**Comment by robander** [comment]
I could see an extension point for that item. I've run into this in the past, and handled it by calling my own `clean-map` step as an alternative, but extending the current one would have been easier. I feel like I brought this up somewhere, maybe, and got a somewhat tepid response, so I didn't push for it at the time ... but it's possible I could be remembering something else.

**Comment by jelovirt** [comment]
Since you can skip the map clean step with `preprocess.clean-map-check.skip=true` and add your own cleaning step to the end of preprocess, this should be left to plug-ins.
