### ISSUE TITLE
ditamap to docx paragraph number error

### ISSUE THREAD

**Issue by my-f** [dita-ot/dita-ot#3282]
When i convert a ditamap to docx by com.elovirta.ooxml plug-in, something errors happened. 
map structure:
![image](https://user-images.githubusercontent.com/44290176/55923807-b620b980-5c39-11e9-849f-eae0cac15b8e.png)
ditamap:
![image](https://user-images.githubusercontent.com/44290176/55923984-95a52f00-5c3a-11e9-96a5-241e6624df49.png)
docx file: 
![image](https://user-images.githubusercontent.com/44290176/55923919-524ac080-5c3a-11e9-8d90-613a9f4bde8e.png)

**Comment by raducoravu** [comment]
Would it be possible to create a very small sample DITA project with which the problem can be reproduced, zip it and attach it to the issue?

**Comment by my-f** [comment]
ok,
Attachment information:
 1. Docx template: template_zh-CN.dotx
 2. dita source file: src.tar.gz
 3. dita-ot version 3.2.1
 4. plug-in install: dita --install com.elovirta.ooxml
Command:
       ./dita-ot-3.2.1/bin/dita -i src/ditamap_DNICMS19100042_zh-CN.ditamap -f docx --dotx.file=docxtemplate/template_zh-CN.dotx -o out -v  -t temp








At 2019-04-11 12:52:33, "Radu Coravu" <notifications@github.com> wrote:

Would it be possible to create a very small sample DITA project with which the problem can be reproduced, zip it and attach it to the issue?

**Comment by raducoravu** [comment]
Sorry but I do not know why this does not work properly, looks like some kind of problem in the template you are using but I'm not using Word that much so I do not know exactly how those counters should be defined.

**Comment by robander** [comment]
I think this issue needs to be opened against https://github.com/jelovirt/com.elovirta.ooxml -- it is really an issue against that plugin, which does not natively ship with DITA-OT.
