### ISSUE TITLE
"fo:list-item" is not a valid child of "fo:block"

### ISSUE THREAD

**Issue by coderliz** [dita-ot/dita-ot#3283]
dita-ot ver 3.2 with format pdf:
transform.fo2pdf.fop:
      [fop] [WARN] Font "Arial Unicode MS,normal,700" not found. Substituting with "Arial Unicode MS,normal,400".
      [fop] [WARN] Font "SimSun,normal,700" not found. Substituting with "SimSun,normal,400".
      [fop] [INFO] Rendered page #1.
      [fop] [ERROR] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] [ERROR] Anttask - Error rendering fo file: C:\AppData\Local\Temp\temp20190411162757165\topic.fo <org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)>org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:671)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:532)
      [fop] 	at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:448)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:469)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
      [fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:448)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:469)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [fop] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [fop] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:446)
      [fop] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
      [fop] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
      [fop] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      [fop] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      [fop] 	at java.lang.reflect.Method.invoke(Unknown Source)
      [fop] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [fop] 	at org.apache.tools.ant.Task.perform(Task.java:350)
      [fop] 	at org.apache.tools.ant.Target.execute(Target.java:448)
      [fop] 	at org.apache.tools.ant.Target.performTasks(Target.java:469)
      [fop] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [fop] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
      [fop] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [fop] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      [fop] 	at org.dita.dost.invoker.Main.runBuild(Main.java:1102)
      [fop] 	at org.dita.dost.invoker.Main.startAnt(Main.java:417)
      [fop] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
      [fop] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
      [fop] Caused by: org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] 	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:296)
      [fop] 	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:116)
      [fop] 	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:648)
      [fop] 	... 45 more
      [fop] Caused by: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] 	at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(ContentHandlerProxy.java:555)
      [fop] 	at net.sf.saxon.event.ContentHandlerProxy.startContent(ContentHandlerProxy.java:398)
      [fop] 	at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:213)
      [fop] 	at net.sf.saxon.event.ComplexContentOutputter.startContent(ComplexContentOutputter.java:721)
      [fop] 	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:375)
      [fop] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
      [fop] 	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(RelaxNGDefaultsComponent.java:210)
      [fop] 	at org.apache.xerces.xinclude.XIncludeHandler.startElement(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
      [fop] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop] 	at org.ditang.relaxng.defaults.RelaxDefaultsParserConfiguration.parse(RelaxDefaultsParserConfiguration.java:111)
      [fop] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
      [fop] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
      [fop] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
      [fop] 	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
      [fop] 	at net.sf.saxon.event.Sender.send(Sender.java:138)
      [fop] 	at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:383)
      [fop] 	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:293)
      [fop] 	... 47 more
      [fop] Caused by: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 17:86)
      [fop] 	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
      [fop] 	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
      [fop] 	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
      [fop] 	at com.sun.proxy.$Proxy3.invalidChild(Unknown Source)
      [fop] 	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:561)
      [fop] 	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:537)
      [fop] 	at org.apache.fop.fo.flow.Block.validateChildNode(Block.java:294)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:276)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
      [fop] 	at net.sf.saxon.event.ContentHandlerProxy.startContent(ContentHandlerProxy.java:388)
      [fop] 	... 66 more
      [fop] 
      [fop] C:\AppData\Local\Temp\temp20190411162757165\topic.fo -> F:\DITA\build\casebook.pdf

**Comment by raducoravu** [comment]
@coderliz this probably depends on the particular DITA content you are publishing. Maybe you can try to open the "C:\AppData\Local\Temp\temp20190411162757165\topic.fo" separately at line 17, maybe you can determine from what DITA content that invalid fo:list-item was generated, then somehow come up with a small sample DITA project reproducing the problem and attach it to the issue.

**Comment by robander** [comment]
Another thing to check - do you get this with out-of-the-box DITA-OT, or do you have plug-ins installed that modify PDF styles? I've seen this error occasionally with custom PDF processing that adds `fo:block` to add styles for any element with a specific attribute, but that results in the errors above when you have that attribute on a list item.

**Comment by coderliz** [comment]
@raducoravu @robander, thanks for the help of you two.
**This issue is caused by my own negligence.** My case.xsd is specilized from the task.xsd
My specilization is as below:
```xml
<xs:element name="constraints">
    <xs:annotation>
        <xs:documentation>Replace Prerequisite section in Task.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:complexContent>
            <xs:extension base="constraints.class">
                <xs:attribute ref="class" default="- topic/ul task/prereq case/constraints "/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:element>
```
But in the task topic, the element "prereq" is spcilized for the "topic/section":
```xml
<xs:element name="prereq">
    <xs:annotation>
        <xs:documentation>
            The pre-requisite (&lt;prereq&gt;) section of a task should document things the user needs to know or do before starting the current task. Prerequisite links will be placed in a list after the related-links section; on output the &lt;prereq&gt; links from the related-links section are added to the &lt;prereq&gt; section.
    Category: Task elements
        </xs:documentation>
    </xs:annotation>
   <xs:complexType>
        <xs:complexContent>
          <xs:extension base="prereq.class">
              <xs:attribute ref="class" default="- topic/section task/prereq "/>
          </xs:extension>
       </xs:complexContent>
    </xs:complexType>
</xs:element>
```
This make the topic.fo produced the error like bellow: "fo:list-item" is not a valid child of "fo:block"! 
```xml
<fo:block space-before="0.6em">
    <fo:block>
        <fo:list-item relative-align="baseline" space-after="1.5pt" space-before="1.5pt">
            <fo:list-item-label end-indent="label-end()" keep-together.within-line="always">
                <fo:block text-align="start">•</fo:block>
            </fo:list-item-label>
            <fo:list-item-body start-indent="body-start()">
                <fo:block>
                    <fo:block space-after="0.6em" space-before="0.6em" text-indent="0em">test constraint</fo:block>
                </fo:block>
            </fo:list-item-body>
        </fo:list-item>
    </fo:block>
</fo:block>
```
