### ISSUE TITLE
Decrease logging level for all apache projects

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3307]
I'm using the Apache HTTP Client libraries with the DITA OT and lately starting with DITA OT 3.3.1 my console started getting flooded with debug messages coming from the library:

       [gen-list] [DEBUG] http-outgoing-0 >> GET http://devel-new.sync.ro/webdav-qa/DITA/flowers/topics/introduction.xml HTTP/1.1
       [gen-list] [DEBUG] http-outgoing-0 >> Accept: application/xml,*/*
       [gen-list] [DEBUG] http-outgoing-0 >> Accept-Encoding: gzip

These too verbose messages seem to be stopped if for example in the "config\logback.xml" we set to INFO all org.apache packages:

      <logger name="org.apache" level="INFO"/>

or at least add a specific rule for the http client:

     <logger name="org.apache.http" level="INFO"/>

**Comment by jelovirt** [comment]
Could you send a PR for the latter?
