### ISSUE TITLE
dita executable does not parse multiple DITAVALS on Windows 10 CLI

### ISSUE THREAD

**Issue by StanDoherty** [dita-ot/dita-ot#3312]
On Linux and MacOS, I can specify multiple DITAVAL files separated by a ":" (colon) to be processed. The following works fine with the sample files I have attached.  

`/Users/stanleydoherty/Desktop/dita-ot/bin/dita 
  --input=./test_006_cli-ditavals.ditamap 
  --format=html5 --output=output/html5 
  --filter=test_006_cli-ditavals_exclude-platform-red.ditaval:test_006_cli-ditavals_exclude-product-green.ditaval:test_006_cli-ditavals_exclude-audience-blue.ditaval`

The dita executable does not parse the equivalent argument separation character for Windows, ";" (semicolon). Colon and comma do not work either. 

Here's the Windows 10 command line. 

`C:\git\dita-ot-feature-tests>c:\dita-ot\bin\dita 
  --input=./test_006_cli-ditavals.ditamap 
  --format=pdf 
  --output=output\pdf --filter=test_006_cli-ditavals_exclude-platform-red.ditaval;test_006_cli-ditavals_exclude-product-green.ditaval;test_006_cli-ditavals_exclude-audience-blue.ditaval`

The dita executable reports:

`Error: Target "test_006_cli-ditavals_exclude-product-green.ditaval" does not exist in the project "DOST".`

Here are my text files. 
[multiple-ditavals-cli_windows.zip](https://github.com/dita-ot/dita-ot/files/3233400/multiple-ditavals-cli_windows.zip)

Stan Doherty
stan@modularwriting.com

**Comment by robander** [comment]
I've found that I have to put the values in quotes when calling from the DOS command line (on both Windows 7 and Windows 10) -- so try the command like this:
`--filter="test_006_cli-ditavals_exclude-platform-red.ditaval;test_006_cli-ditavals_exclude-product-green.ditaval;test_006_cli-ditavals_exclude-audience-blue.ditaval"`

I had the same error you did at some point, tried the quotes, and didn't think more about it -- but seeing the question here I wonder if our docs need updating for this.

**Comment by robander** [comment]
Stan confirmed that adding quotes resolved the issue.

I'm not sure if this has always been a requirement but I know I've been using it for quite a while.

@infotexture -- not sure how best to handle in the docs, would it be appropriate to add the quote requirement into the existing note after `args.filter` here? https://www.dita-ot.org/dev/parameters/parameters-base.html#base__args.filter

**Comment by infotexture** [comment]
Assuming the quoted value will do no harm on macOS and Linux, I added the info to the [args.filter](https://www.dita-ot.org/dev/parameters/parameters-base.html#base__args.filter) parameter description and to the corresponding [--filter](https://www.dita-ot.org/dev/topics/build-using-dita-command.html#using-command-line-tool__d12e307) entry in [Building output using the `dita` command](https://www.dita-ot.org/dev/topics/build-using-dita-command.html) with dita-ot/docs@5e8d883.
