### ISSUE TITLE
PDF index <index-see-also> and <index-see> issues

### ISSUE THREAD

**Issue by lief-erickson** [dita-ot/dita-ot#3314]
PDF FOP index produces the following issues related to `<index-see-also>`:
1. If there are multiple `<index-see-also>` elements as children of `<indexterm>` only the first one (alphabetically, after sorting occurs between *_MERGED.xml and stage1.xml) appears in the index. In the example below, only "See also DTD" is emitted. Both "RELAX NG" and "schema" are suppressed.
```xml
<indexterm>grammar files<index-see-also>schema</index-see-also>
                        <index-see-also>DTD</index-see-also>
                        <index-see-also>RELAX NG</index-see-also>
</indexterm>
```
Note: Changing the markup to put each `<index-see-also>` as a lone child of `<indexterm>` had no effect on the final "see also" entries; it does however create extra page number entries for "grammar files" in the index, which is likely related to the next issue.
```xml
<indexterm>grammar files<index-see-also>schema</index-see-also></indexterm>
<indexterm>grammar files<index-see-also>RELAX NG</index-see-also></indexterm>
<indexterm>grammar files<index-see-also>DTD</index-see-also></indexterm>
```

2. When emitting multiple "see also" entries, they should be separated by a comma. I don't see any processing in index.xsl or index_fop.xsl that would account for that currently.

3. The `<index-see-also>` entries show their page number twice (e.g., "schema 3, 3") -- once for each time the term is used in my test files. Only one entry per page should be emitted. Because the page number is emitted once for each time that a term appears in `<indexterm>` or `<index-see-also>` leads me to believe that each `<index-see-also>` is being processed, but there is no logic to remove duplicated page numbers.

Removing `[1]` from from certain `opentopic-index:index.entry[1]` in plugins\org.dita.pdf2\xsl\fo\index.xsl does emit all of the "see also" entries, albeit the linking is wrong (only to the alphabetically first ID) and there is no comma. 

I'm not sure if anything in plugins\org.dita.pdf2.fop\xsl\fo\index_fop.xsl is implicated.

Tested using
* The attached files
* DITA-OT 3.3.1 with no custom plugins
* Generated from oXygen.

The attached .zip file contains a DITA map and one topic file to demonstrate the issues.

Edit: I also confirmed that `<index-see>` is also affected. 

[see-also.zip](https://github.com/dita-ot/dita-ot/files/3238413/see-also.zip)

**Comment by robander** [comment]
For the separate items described in this issue:

1. Added a fix to #3373 to fix the first item. Additional see or see-also entries are no longer dropped.
2. This is also fixed (the entries that were dropped now appear, separated by commas).
3. The duplicate page numbering is caused by FOP, which does not automatically handle removing the extra number for entries on the same page. When I test this with FOP I will get two links like `3, 3` while the same test with AH filters out the duplicate and just gives me one link to page 3.
