### ISSUE TITLE
Index entries missing if child entries exist

### ISSUE THREAD

**Issue by lief-erickson** [dita-ot/dita-ot#3320]
# Description
The DITA specification is clear that an `<indexterm>` with children should not create locators (i.e., links or page numbers). 

> In the case of nested <indexterm> elements, each <indexterm> with no <indexterm> children (the "leaves") contributes a page number to the generated index; the ancestral <indexterm> elements for each leaf <indexterm> provide the higher levels for the multilevel entry.

But the specification appears to make an assumption that the index entries are all in the same file. That distinction is not clear when multiple files are involved. 

garagetaskoverview.xml & wwfluid.xml
`<indexterm>garage</indexterm>`

shelving.xml
`<indexterm>garage<indexterm>shelving</indexterm></indexterm>`

# Actual result
garage
&nbsp;&nbsp;&nbsp;shelving 5

# Expected result
garage 3, 7
&nbsp;&nbsp;&nbsp;shelving 5

Bonus: OT Info message suggestion. "This `<indexterm>` has the same text as at least one other `<indexterm>` that has children entries."

# Environment
OT used: DITA OT 3.3.1
Target: pdf
PDF Formatter: FOP
OT run from: Command line and oXygen

# Errors
None in log.

## Files to reproduce

[omitted-entries.zip](https://github.com/dita-ot/dita-ot/files/3278587/omitted-entries.zip)

**Comment by drmacro** [comment]
I think the intent of the spec is that non-leaf index entries should not produce page numbers. That's a pretty universal editorial style. So it's not a function of local markup but of the effective index structure after evaluation of all index entries.

I would consider your expected result to be wrong and would flag it as a bug if it occurred in my content.

Unless I had an editorial group that insisted that that was their practice for indexing, in which case I would expect it to occur in *all* cases.

I can't think of a justification for the behavior to be selected on specific index entries and would definitely not want it to be dependent on the vagaries of source markup, much less, the organization of the source into (or not into) specific storage objects.

**Comment by lief-erickson** [comment]
The spec doesn't say that explicitly, but I can see how that might be the intent. Others may see it differently. If so, maybe they'll chime in.

My biggest issue is that DITA-OT silently drops any non-leaf index entries without warning. There is no possibility for authors to correct the markup or to even know that their entries have been omitted.

Even if we disagree about the expected output, I think we can agree that an author who creates an index entry should expect that it appears in the index, and if it cannot appear there, because some author created an index entry of the same name with a child, that there's some warning mechanism that the index entry has been dropped with the reason it was dropped. This would allow the author to amend the markup to include a child entry.

That's the reason behind the "Bonus" message.

**Comment by drmacro** [comment]
I think the problem with my initial suggestion (all or none) is that there will be cases where, as a matter of editorial policy, you never want a specific term to have page numbers and other terms should always have page numbers, even if they end up with subordinate terms.

One way to do this is to define all the "index heads" in the root map (i.e., conreffed into the root map's prolog--presumably such a structure would be separately managed and shared across publications) which has the effect of not associating page numbers to those entries that do not also occur in topics.

Then if you also allow non-leaf index entries that occur within topics to have page numbers, only those that do will get page numbers, effectively giving you a way to distinguish pure index heads from non-leaf but page-generating index entries.

**Comment by robander** [comment]
> My biggest issue is that DITA-OT silently drops any non-leaf index entries without warning.

Definitely agree that's a problem.

Otherwise -- if I've got 20 different primary entries `<indexterm>example</indexterm>`, and someone contributes one topic that happens to add `<indexterm>example<indexterm>error condition</indexterm></indexterm>`, I've silently lost 20 entries from my index.

I'm familiar with the best practice of "Don't use an index entry when it has leaf entries" but really unfamiliar with how universal that practice is. I think given that markup, I'd rather have those 20 entries appear (it's what the markup says, and easy to see when reviewing the index) than to have them silently dropped (impossible to detect when reviewing). Failing that, it should definitely be an error condition, because one way or another we've dropped content that an author expected to appear.

**Comment by drmacro** [comment]
I tried to so a little research last night and discovered an ISO standard for indexing (ISO 999:1996) but of course the only thing I can see for free is the ToC, which doesn't help much.

Only leaf entries get numbers was what I learned and what I think I remember from various books but it's definitely an editorial choice and thus we need to support whatever choice is made.

Maybe this is something to explore in the context of Kris' stage 1 indexing proposal, where we could add an "index-head" element distinct from "index-entry"?

**Comment by jelovirt** [comment]
A late comment, but note that the indexing code in PDF2 differs between formatters.

**Comment by robander** [comment]
Looking at this one again - verified the results are the same with FOP and AH output, so I think this one is probably from the common code that collects and sorts the index terms. Also checked to make sure the results are the same with both a simple input map and a bookmap with `<indexlist>`.
[3320.zip](https://github.com/dita-ot/dita-ot/files/3518054/3320.zip)

**Comment by robander** [comment]
Correction - definitely not from the sorting code, the `index.xsl` code in the pdf2 directory is explicitly set up to follow a different processing path for terms that have sub-terms (ignoring any page links).
