### ISSUE TITLE
Footnote with id set on it does not produce proper markers

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3327]
Let's say I define a footnote and I set an ID on it (because I later want to refer to it from somewhere else):

    <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
    <topic id="care">
        <title>Care and Preparation</title>
        <body>
            <p>When caring for your flower garden you want <fn id="fnid">to</fn></p>
        </body>
    </topic>

There should be a (1) marker in the paragraph content and a (1) marker at the end of the topic. There should be a link between the (1) marker at the end of the topic and the (1) marker inside the paragraph content. 
But somehow after setting the id on the fn element there is no longer a (1) marker inside the paragraph.

**Comment by raducoravu** [comment]
👍 Another of our end users tries to create footnotes in Markdown content, something like:

            # Topic Title (Heading 1)
            
            ## Section Title {.section}
            
            Here is a paragraph.[^] Here is more of the paragraph.
            
            [^1]: This is a test footnote.

which gets dynamically converted to DITA as:

     <fn callout="1" id="fn_1">This is a test footnote.</fn>

Because the @id attribute is on the fn element, the callout is no longer rendered.

**Comment by raducoravu** [comment]
In the XSLT "plugins/org.dita.pdf2/xsl/fo/topic.xsl" there is an XSLT template:

     <xsl:template match="*[contains(@class,' topic/fn ')]">

which does something like:

              <xsl:when test="not(@id)">
                <fo:inline xsl:use-attribute-sets="fn__callout">
                  <fo:basic-link internal-destination="{$id}">
                    <xsl:copy-of select="$callout"/>
                  </fo:basic-link>
                </fo:inline>
              </xsl:when>
              <xsl:otherwise>
                
                <fo:inline/>
              </xsl:otherwise>

and I'm not sure why it avoid generating anything when the footnote has an @id attribute.

**Comment by raducoravu** [comment]
👍 Reported also on DITA Users List:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dita-ot-users/ribjDwS0Kg4/t0WrrRJFAgAJ

**Comment by raducoravu** [comment]
Similar problems for the HTML5 output.

**Comment by robander** [comment]
I missed this issue when originally reported.

This is the design of the `<fn>` element, and it has caused confusion repeatedly over the years. 

The idea (and how I've sometimes seen it used) is that when you want use-by-reference footnotes, you can define them in a group at one spot in the topic. You can refer to them as needed (some can be referred to many times). When published, numbers are only generated for the footnotes that are referenced, and only where referenced (not where defined). 

The processing for this is described in the specification here: 
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/langRef/base/fn.html#fn

**Comment by raducoravu** [comment]
Thanks @robander, I'm slowly starting to understand how this work. So if someone defines an ID on a footnote and they still want the original footnote displayed at the same location they probably need to do something like this:

      <xref href="#introduction/fnid" type="fn"/><fn id="fnid">sometext</fn>

The link to the footnote definition in the topic footer seems to work. But then the generated footnote marker will no longer contain a link back to the original place which seems to obey the specification.

I'm still having problems understanding the use case of linking to a footnote element.

**Comment by robander** [comment]
I think the main use case is for repeated notes (not one-time notes) -- something that can come up two or more times in the same topic. I've seen this a few times, and will construct a kind of silly example here:
```
<p>Footnotes are fun and easy to use.<xref href="#./results" type="fn"/>
They are never confusing<xref href="#./results" type="fn"/>, and nobody ever
has trouble understanding how to use them.<xref href="#./results" type="fn"/></p>
<fn id="results">Your results may vary</fn>
```

In that case, each clause would get the superscript `1` that links down to the footnote; the footnote does not link back because there are multiple potential targets.

I do not think there is a use case for doing this when the footnote is only used once, unless it's just "we like to have a central spot in our topics to define all of our footnotes".

**Comment by robander** [comment]
FYI @raducoravu I found an actual example of this I'd forgotten about -- in the long topic about what elements are / should be translated, the same footnote is reused many times across the tables. Footnotes 1 through 6 at the bottom of the page are defined at the top of the source, and referenced when needed. The first one is used 12 times, and the second one is used 40 times. Only the last two footnotes are used ones / defined where used, and those are the ones where both the footnote and the number link to each other:
http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part2-tech-content/non-normative/elementsMerged.html

**Comment by raducoravu** [comment]
@robander thanks, seeing an example makes all the difference, now I understand the use case.

**Comment by robander** [comment]
@raducoravu the current processing in DITA-OT is working as designed, so I think this can be closed. 

The samples above show markdown - is the `lwdita` plugin converting these foonotes with an ID, which results in the issue? If so then we should probably move this to report against the `lwdita` parser.
