### ISSUE TITLE
Term with keyref linked in HTML but not PDF

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#3328]
A client reported today that `<term keyref="glossary-term"/>` is rendered as a link in HTML output, with the definition text appearing as expected on mouseover. In PDF output however, the term is rendered in _italics_, but not linked to the definition.

I see several open issues related to terms and glossentry references (for example #2173, #3174), but each case is slightly different and I'm not sure whether the lack of linking in PDF output is a bug in the code, an oversight, or a conscious design decision.

Any thoughts?

**Comment by raducoravu** [comment]
If the client is using a "glossref" in the DITA Map to refer to the glossentry, then they would need to explicitly set 'print='yes'' on it.

**Comment by drmacro** [comment]
My rule is do not use <glossref>.
