### ISSUE TITLE
Right align counters in steps when producing PDF output

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3335]
If a DITA "steps" element has more than 9 steps, the counters presented for the first nine steps are left-aligned, like in the image here:

https://www.oxygenxml.com/forum/viewtopic.php?f=26&t=20253

I suggest adding to the attribute set "steps.step" this extra attribute:

       <xsl:attribute name="end-indent">label-end()</xsl:attribute>

**Comment by infotexture** [comment]
In initial testing, the proposed change is apparently not sufficient to right-align ordered list numbers with the current `develop` code.

The `end-indent` is already set in the `ol.li__label` attribute set on [Line 88 of lists-attr.xsl](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/attrs/lists-attr.xsl#L88).

The number labels can be right-aligned by changing the `text-align` attribute in the `ol.li__label__content` attribute set on [Line 92](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/attrs/lists-attr.xsl#L92) from `start` to `end`:

```diff
     <xsl:attribute-set name="ol.li__label__content">
-        <xsl:attribute name="text-align">start</xsl:attribute>
+        <xsl:attribute name="text-align">end</xsl:attribute>
         <xsl:attribute name="font-weight">bold</xsl:attribute>
     </xsl:attribute-set>
```

But this change affects all numbered lists _(even those with only single-digit step numbers)_, and would produce a ragged left margin, so I'm not sure we should change the defaults, as longer lists are probably the exception, not the rule.

**Comment by raducoravu** [comment]
In my initial post the correct attribute set name should have been "steps.step__label".
You are right in your investigation, the "ol.li__label" already has that attribute I suggested set on it. I probably did not accurately test this on my side.

**Comment by sdevarb** [comment]
> In initial testing, the proposed change is apparently not sufficient to right-align ordered list numbers with the current `develop` code.
> 
> The `end-indent` is already set in the `ol.li__label` attribute set on [Line 88 of lists-attr.xsl](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/attrs/lists-attr.xsl#L88).
> 
> The number labels can be right-aligned by changing the `text-align` attribute in the `ol.li__label__content` attribute set on [Line 92](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/attrs/lists-attr.xsl#L92) from `start` to `end`:
> 
> ```diff
>      <xsl:attribute-set name="ol.li__label__content">
> -        <xsl:attribute name="text-align">start</xsl:attribute>
> +        <xsl:attribute name="text-align">end</xsl:attribute>
>          <xsl:attribute name="font-weight">bold</xsl:attribute>
>      </xsl:attribute-set>
> ```
> 
> But this change affects all numbered lists _(even those with only single-digit step numbers)_, and would produce a ragged left margin, so I'm not sure we should change the defaults, as longer lists are probably the exception, not the rule.

Followed the steps. It works! Thank you.
