### ISSUE TITLE
Image Alt Text not added to PDF in DITA-OT 3.3.3 with Apache FOP formatter

### ISSUE THREAD

**Issue by catrachos** [dita-ot/dita-ot#3343]
## Expected Behavior
Expect `<image><alt>string</alt></image>` to display alt text in PDF output using Apache FOP formatter. In Acrobat reader I would expect popup showing `string` and the audio screen reader to read the alternate text just as if I were to edit it in manually on an image using Microsoft Word or another PDF editor.

## Actual Behavior
Used Apache FOP formatter with following command line: `dita -i filename.ditamap -f pdf2`

I checked code in topic_fop.xsl

```
<xsl:template match="*|@alt" mode="graphicAlternateText">
       <xsl:attribute name="fox:alt-text">
            <xsl:apply-templates select="." mode="text-only"/>
       </xsl:attribute>
 </xsl:template>
```

I checked the XSLT. It is running through the code and resolving the select statement as expected. But doesn't exhibit as alt text in the PDF output.

## Actual Solution
Sorry, retract this. Not a bug. To answer my own question, the `<accessibility>` setting has to be added or configured as `true` in the `fop.xconf` file:

```
<fop version="1.0">
  <accessibility>true</accessibility>
  ...****
```
As described at the following link: [Apache™ FOP: Accessibility](https://xmlgraphics.apache.org/fop/2.2/accessibility.html)

This solved the problem.

## Steps to Reproduce

1. Using following command line:
dita -i:filename.ditamap -f pdf2

where dita files contained <image href="imagefile.png"><alt>text string</alt></image>

## Copy of the error message, log file or stack trace
No error messages, completed normally producing PDF file as expected.

## Environment

* DITA-OT version: DITA-OT 3.3.3
* Operating system and version: Window 10
  _(Linux, macOS, Windows)_
* How did you run DITA-OT? startcmd, dita command, and in oXygen 21.1

* Transformation type:
  PDF2, in oxygen PDF FO and PDF CSS

**Comment by raducoravu** [comment]
Maybe you need to run the Apache FOP with the "-a" flag:

https://xmlgraphics.apache.org/fop/2.2/accessibility.html

or add:

     <accessibility>true</accessibility>

in the fop.xconf

**Comment by robander** [comment]
Marking closed - based on the updated text in the description, this was resolved by updating the FOP configuration as Radu suggested.

**Comment by raducoravu** [comment]
If a question arises as to why the DITA OT does not enable accessibility by default in the PDFs, I think there are two problems:
1) PDF increases in size.
2) The Apache FOP processor has had in the past and may still have various bugs related to enabling this flag: https://github.com/dita-ot/docs/issues/64
