### ISSUE TITLE
NullPointerException in FileUtils.getRelativePath

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3366]
The stack trace:

https://www.oxygenxml.com/forum/viewtopic.php?f=20&t=20682

     D:\Oxygen XML Author 21\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:87: java.lang.NullPointerException
	at org.dita.dost.util.FileUtils.getRelativePath(FileUtils.java:169)
	at org.dita.dost.module.DebugAndFilterModule.getRelativePathFromOut(DebugAndFilterModule.java:532)
	at org.dita.dost.module.DebugAndFilterModule.getPathtoProject(DebugAndFilterModule.java:514)
	at org.dita.dost.writer.DitaWriterFilter.startDocument(DitaWriterFilter.java:95)
	at org.xml.sax.helpers.XMLFilterImpl.startDocument(Unknown Source)
	at org.dita.dost.writer.TopicFragmentFilter.startDocument(TopicFragmentFil

It looks like a side effect of a condition added by @robander in: https://github.com/dita-ot/dita-ot/pull/2797

**Comment by raducoravu** [comment]
Looking at the console output provided by the end user, at some point I think he has some absolute paths pointing outside of the folder where the DITA Map is located, probably a conref which points to some network drive located on an Y drive.

**Comment by chrispitude** [comment]
We have run into this too. It occurs when our working directory is a directory on C:\ in Windows (for example, C:\my_dita_project). If we add one directory level, the problem disappears.

Sample invocation command:

```
c:\ubuntu-1804\rootfs\home\chrispy\dita-ot-3.4.1\bin\dita.bat ^
 -i C:\top_level_error\A1\A2\A3\A4\OPENME2.ditamap ^
 -Dbasedir=C:\top_level_error\A1\A2\A3\A4 ^
 -f html5 ^
 -t C:\top_level_error\temp\pdf-OPENME2 ^
 -o C:\top_level_error\out\pdf-OPENME2 ^
 --filter C:\top_level_error\prj\ditaval\flag_final.ditaval
```

I've attached a tiny testcase. To run, extract in the C:\ drive in Windows, then run `runme.bat`.

[top_level_error.zip](https://github.com/dita-ot/dita-ot/files/5150396/top_level_error.zip)
