### ISSUE TITLE
Builds fail with Saxon 9.9

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#3369]
After the upgrade to Saxon 9.9 in #3330, test builds fail with 

```bash
Error: java.lang.NoSuchMethodError: 
    net.sf.saxon.jaxp.TransformerImpl.getUnderlyingController()
    Lnet/sf/saxon/trans/XsltController;
```

## Steps to Reproduce

1. Check out latest `develop` branch @ 30bf363.
2. `./gradlew`
3. `cd src/main/docsrc/samples/`
4. `dita -input sequence.ditamap -format html5`

## Related issue

See https://github.com/dita-ot/dita-ot/issues/3279#issuecomment-481507796 by @robander and  [setMessageEmitter call](https://github.com/dita-ot/dita-ot/blame/30bf3634f2abe6a8ad653891a6eae98b23dd817a/src/main/java/org/dita/dost/util/XMLUtils.java#L79).

**Comment by raducoravu** [comment]
I had the same problem but I was running the DITA OT with a slightly older Saxon 9.8 version, maybe you should look in the "DITA-OT\lib" folder to see if you have duplicate Saxon JARs.
That's because the "gradlew" at least on my side does not properly remove old JAR libraries resulting in accumulation of older JAR libraries in the target folder.

**Comment by infotexture** [comment]
@raducoravu Thanks for your quick diagnosis, that was indeed the problem. 👍 

Deleting `src/main/lib` and re-running the Gradle wrapper with `./gradlew` rebuilt the library folder to contain only the currently referenced libraries. Builds work fine now. ✅ 

_(Turns out I had 20 older libraries in there, including 2 older versions of Saxon.)_ 🙈

**Comment by raducoravu** [comment]
@infotexture right, I had similar problems on my side, I wish the gradlew would remove all previous JAR libraries before starting. Because in addition to the DITA-OT\lib folder there are also JAR libraries in the FOP plugin "lib" folder which also get duplicated.

**Comment by infotexture** [comment]
Gradle will do whatever we tell it to. 

We _could_ add a task to the build to delete these library folders to prevent this sort of error, but I doubt we'd want that to run by default, as it would probably increase build time and add a new  delay to the CI process.

Might be worth considering as an optional task that could be run on demand.
