### ISSUE TITLE
Are incremental builds a possibility?

### ISSUE THREAD

**Issue by ChrisTrenkamp** [dita-ot/dita-ot#3380]
I'm investigating the Dita OT and would like to know if it's possible to have incremental builds.  What I mean is after building a deliverable, subsequent builds will only process files that have changed (changes including things like content changes to the topic itself, conref changes, changes in links, etc.).  

The goal is to speed up builds and provide feedback on content that has changed.

My group is considering transitioning our content to Dita and need some speed metrics on Dita OT.  Processing the Dita 1.3 standard as HTML5 took about 5 minutes on my machine, and that's a very small deliverable compared to the documentation we need to process.  It's one thing if an initial build takes a while, but we can't have builds that take the same amount of time when one topic changes.

Is it possible to implement this kind of functionality to Dita OT?

**Comment by infotexture** [comment]
@ChrisTrenkamp Not out of the box, but with the [DITA Open Toolkit Gradle Plugin](https://eerohele.github.io/dita-ot-gradle/) by @eerohele.
