### ISSUE TITLE
Scoped <xref @keyref> produces errors, does not affect output

### ISSUE THREAD

**Issue by chrispitude** [dita-ot/dita-ot#3385]
## Expected Behavior
I'm using the example from the "Cross-deliverable linking" section from the ["Understanding Scoped Keys in DITA 1.3" OASIS paper](https://www.oasis-open.org/committees/download.php/56472/Understanding%20Scoped%20Keys%20In%20DITA%201.3.pdf).

When I publish this map to XHTML, I expect to get some kind of information in the output that I can post-process into a cross-deliverable link.

## Actual Behavior
I get the following:

```
$ dita -i widget.ditamap -f xhtml
   [mapref] I/O error reported by XML parser processing file:/tmp/temp20191015204303672/gadget.ditamap: /tmp/temp20191015204303672/gadget.ditamap (No such file or directory)
   [mapref] I/O error reported by XML parser processing file:/tmp/temp20191015204303672/gadget.ditamap: /tmp/temp20191015204303672/gadget.ditamap (No such file or directory)
[move-meta] file:/mnt/c/Users/chrispy/scope/widget.ditamap:5:66: [DOTX020E][ERROR]: Missing navtitle attribute or element for peer topic "gadget.ditamap". References must provide a local navigation title when the target
 is not a local DITA resource.
[move-meta] file:/mnt/c/Users/chrispy/scope/widget.ditamap:5:66: [DOTX024E][ERROR]: Missing linktext and navtitle for peer topic "gadget.ditamap". References must provide a local navigation title when the target is not
a local DITA resource.
 [pipeline] file:/mnt/c/Users/chrispy/scope/widget.ditamap:5:66: [DOTX009W][WARN]: Could not retrieve a title from 'gadget.ditamap'. Using 'gadget.ditamap' instead.
```

The message refers to adding a @navtitle to a map, which doesn't make sense to me. But if I add it anyway:

`   <mapref href="gadget.ditamap" scope="peer" keyscope="gadget" navtitle="FOOBAR"/>`

the DOTX messages go away, but I still get the [mapref] error messages:

```
$ dita -i widget.ditamap -f xhtml
   [mapref] I/O error reported by XML parser processing file:/tmp/temp20191015205354072/gadget.ditamap: /tmp/temp20191015205354072/gadget.ditamap (No such file or directory)
   [mapref] I/O error reported by XML parser processing file:/tmp/temp20191015205354072/gadget.ditamap: /tmp/temp20191015205354072/gadget.ditamap (No such file or directory)
```

In addition, I expected the output to have some kind of handle or hook for me to post-process:

```
$ fgrep 'integrate the Gadget module' *.html
get-started-widget.html:      <p class="p">If you choose to <span class="xref">integrate the Gadget module</span>, many more options will be available to you.</p>
```

but perhaps the information is only available within the publishing pipeline, not after.

## Steps to Reproduce
1. Download and extract the testcase: [scope.zip](https://github.com/dita-ot/dita-ot/files/3731546/scope.zip)
2. Run the following command: `dita -i widget.ditamap -f xhtml`

## Environment
Running in Ubuntu 18.04 via WSL in Windows 10

* DITA-OT version: 3.3.4
* Operating system and version: linux (Ubuntu 18.04)
* How did you run DITA-OT? dita command
* Transformation type: XHTML

**Comment by keberlein** [comment]
Hi, Chris. DITA 1.3 introduced scoped keys and a _potential_ mechanism for cross-deliverable links. However, DITA-OT does not support cross-deliverable linking. There are too many factors in the mix (how DITA content is stored, conventions used by implementation, business requirements, etc.) for DITA-OT to implement a feature that will work reliably for subtantial percentage of implementations. If your implementation needs cross-deliverable links, you will need to roll your own solution.

**Comment by chrispitude** [comment]
Thanks for the reply! Yes, I am trying to roll my own solution for cross-deliverable links. I've never written XSLT or a DITA processing plugin, so I'm at the point where I'm trying to figure out where to start.  :)

I was hoping the output <xref> would have some nonfunctional-but-vestigial information I could use for post-processing the output, but alas not. Does that mean I need to write XSLT to plug somewhere into the processing pipeline? If you can suggest which extension point and what to look for, it would save me days of flailing about.

I'm assuming I'd at least need the [mapref] I/O errors to be fixed in order to roll my own solution.

**Comment by drmacro** [comment]
I think you're the first person to (publicly) try to use cross-deliverable links directly with the OT.
With 3.x it should be possible to hook into the map preprocessing to do something useful but I haven't looked into it myself.

But I think your idea of just putting something in the HTML that can be post processed is a reasonable approach to a local solution. 

But it might be possible to do something more complete in map preprocessing if you can reasonably predict what the ultimate target will be based on the source information (for example, you can know what the mapping from source details to eventual HTML location will be or you have some feature in your Web server that you can take advantage of, such as query-based URLs that will always work in that context or something.

Contact me offline and I'll see if I can at least point you in the right direction with regard to hacking preprocessing.

**Comment by raducoravu** [comment]
About this remark:

          In addition, I expected the output to have some kind of handle or hook for me to post-process:

I looked in the transformation temporary folder and the keyrefs are still there on the DITA elements.
In the XSLT stylesheet "DITA-OT\plugins\org.dita.html5\xsl\topic.xsl" there is an XSLT template called:

      <xsl:template name="commonattributes">

and in it you add at the end this extra content:

    <xsl:if test="contains(@class, ' topic/xref ')">
      <xsl:if test="@keyref">
        <xsl:attribute name="data-keyref" select="@keyref"/>
      </xsl:if>
    </xsl:if>

the original keyref attribute should be ported to a data-keyref attribute in the HTML content, something like:

     <span class="xref" data-keyref="bookB.keyB_topics_sub4">Booky book book</span>

The link is no longer an HTML "a" link element because the DITA OT does not know how to solve the original link target but maybe the keyref set on the span might be enough for you to have data for post processing.

**Comment by chrispitude** [comment]
Eliot sent me an offline email with lots of useful suggestions on what to look at next - thanks Eliot! (Are you agreeable to me posting it here, or do you want to post it?)

Regarding the DITA-OT requiring a @navtitle for a peer <mapref>, Eliot noted the following to me:

> In maprefImpl.xsl you'll see there's a template:
> 
> `<xsl:template match="*[contains(@class, ' map/topicref ')][(@format, @dita-ot:orig-format) = 'ditamap']" priority="10">`
> 
> This is the template that handles mapref topicrefs.
> 
> This template clearly assumes that all maprefs are simply submaps but that is not the case for DITA 1.3.

This also explains why the peer <mapref> is showing up in the output TOC as a navigable submap. Adding `processing-role="resource-only"` to the <mapref> removed the peer map from the output, but I still needed @navtitle to avoid errors. (The /tmp directory errors were still emitted.)

Eliot also provided some thoughts on how peer maps could be intercepted and processed. In summary, we could store all these peer-map scoped key values, resolve them during topic processing, and predictively build the output (by assuming the output directories are peer directories). This is a reasonable baseline behavior and gets us the closest to out-of-the-box support for cross-deliverable links.

Unfortunately, this is well beyond my current skill set.  :(

Radu, I tried your suggestion. I found the following files in the Oxygen DITA-OT directory:

```
/mnt/c/Program Files/Oxygen XML Editor 22/frameworks/dita$ find . -name topic.xsl
./DITA-OT3.x/plugins/org.dita.html5/xsl/topic.xsl
./DITA-OT3.x/plugins/org.dita.pdf2/xsl/fo/topic.xsl
```

and I modified the html5 version. When I ran Oxygen's WebHelp transformation, the keyref is preserved via @data-keyref:

`<p class="- topic/p p">If you choose to <span class="- topic/xref xref" data-keyref="gadget.integ-gadget">integrate the Gadget module</span>, many more options will be available to you.</p>`

This puts the burden of resolving the keyref on me instead of the DITA-OT, but this is within my skill set. For now, I'll pursue this angle and share my findings!

**Comment by raducoravu** [comment]
@chrispitude about that @navtitle being required on topicrefs to maps, I also get frustrated by it from time to time, I wanted to add an issue for it but then I considered that it's not bad to have that navtitle there at least to describe what the referenced resource is, even if that description will not appear anywhere in the published output. Anyway, it's a bug, you can add it separately if you want.

**Comment by chrispitude** [comment]
I've written a script that post-processes the HTML5 files produced by the DITA-OT, Oxygen WebHelp, or other formats that use the topic.xsl file with Radu's additional code. See:

https://github.com/chrispy-snps/DITA-fix-xbook-html-links

There is an example DITA-OT testcase that demonstrates the resulting working cross-book links.

The fix_html_xbook_links.pl script requires a couple perl modules; see the header comments for installation information.

**Comment by raducoravu** [comment]
@chrispitude thanks for sharing this, HTML is the easier part, probably PDF would be harder to do.
