### ISSUE TITLE
Question: Shoehorning LOT and LOF into custom DITA PDF plugin

### ISSUE THREAD

**Issue by kirkilj** [dita-ot/dita-ot#3387]
We have our own custom PDF plugin and would like to add List of Tables and List of Figures capability to a standard unspecialized DITA Map - not a Bookmap. If someone was industrious enough, could he/she take the code the implements the LOT and LOF functionality for a Bookmap and invoke it during our the DITA Map processing of our plugin? We'd probably use additional custom build properties, such as lot.enable and lof.enable to determine if an LOT or LOF was desired for a particular deliverable. I hear that our users would also like a List of Tasks, if possible. 

Would we be looking at an Ant, XSL, or Java modification to pull this off? All of the above? Would there be a particular extension point that would be ideal? Unfortunately, we cannot employ a specialization at this point in our migration cycle, such as the DITA for Publishers pubmap created by Eliot Kimber.

**Comment by drmacro** [comment]
It will definitely be an XSLT extension, as you'll need to generate the LoT and LoF in the generated FO instance.

But it should be easy to integrate the existing processing just by providing your own way to call it at the appropriate point in the top-level map processing.

**Comment by robander** [comment]
It's a bit odd, but you may be able to get a really quick solution for LOT and LOF by overriding the `topicmerge` XSL step (you can hook into that with a plugin). In there, insert the `<ot-placeholder:tablelist>` and `<ot-placeholder:figurelist>` elements that result in the formatted lists for bookmap. Try formatting a bookmap, save the temp dir and see where they are in the merged file, and then put them out in the right location for your map. I'm pretty sure those kick off the automated lists.

There is no list of tasks today, so you'd be doing that one from scratch, but as Eliot said it would all be XSLT.

**Comment by robander** [comment]
Closing this issue (question was answered above).
