### ISSUE TITLE
Topicmerge pipeline is not handling child maps correctly

### ISSUE THREAD

**Issue by mariodigiacomo** [dita-ot/dita-ot#3405]
## Expected Behavior
[pipeline] Processing d:\temp\buildPDF-prc\SIMACAEDoc\SIMACAEPRCRefMap.doc\src\..\..\..\SIMASharedDoc\SIMAPRCRefResources.doc\src\simaprc-m-Loads-sb.xml

## Actual Behavior
[pipeline] [DOTX008E][ERROR] File 'file:/d:/temp/buildPDF-prc/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simaprc-m-Loads-sb.xml' does not exist or cannot be loaded. 
## Possible Solution
 Look for child maps in correct directory

## Environment

* DITA-OT version: 2.3.1
* Operating system and version: Windows
* How did you run DITA-OT? Via Ant
* Transformation type: PDF3

**Comment by mariodigiacomo** [comment]
This is probably relevant, as the move-meta step is also complaining:
```

[move-meta] Processing file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap
[move-meta] Processing file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap
[move-meta] Reading file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap
[move-meta] Writing file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap
[move-meta] Processing file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap
[move-meta] Processing file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap to file:/d:/temp/buildPDF-simacaeprc-ref-m/SIMACAEDoc/SIMACAEPRCRefMap.doc/src/simacaeprc-ref-m.ditamap.tmp1572982649365
[move-meta] Loading stylesheet C:\PROGRA~1\DITA-OT\dita-ot-2.3.1\xsl\preprocess\mappull.xsl
[move-meta] Set parameter basedir to 'C:\PROGRA~1\DITA-OT\dita-ot-2.3.1'
[move-meta] Set parameter style to 'C:\PROGRA~1\DITA-OT\dita-ot-2.3.1\xsl\preprocess\mappull.xsl'
[move-meta] Set parameter conserve-memory to 'false'
[move-meta] Set parameter message to 'Move metadata entries.'
[move-meta] Set parameter inputmap to 'SIMACAEDoc\SIMACAEPRCRefMap.doc\src\simacaeprc-ref-m.ditamap'
[move-meta] Set parameter TRANSTYPE to 'pdf3'
[move-meta] Recoverable error on line 58 of mappullImpl.xsl:
[move-meta]   FODC0002: java.io.FileNotFoundException:
[move-meta]   d:\temp\buildPDF-simacaeprc-ref-m\SIMACAEDoc\SIMACAEPRCRefMap.doc\src\simaprc-m-Loads-sb.xml (The system cannot find the file specified)
[move-meta] file:/d:/ws/RELEASE_DOC/R422/BSFDOCEN/SIMASharedDoc/SIMAPRCRefResources.doc/src/simaprc-m-Loads.ditamap:8:84: [DOTX023W][WARN]: Unable to retrieve navtitle from target: 'simaprc-m-Loads-sb.xml'. 
[move-meta] file:/d:/ws/RELEASE_DOC/R422/BSFDOCEN/SIMASharedDoc/SIMAPRCRefResources.doc/src/simaprc-m-Loads.ditamap:8:84: [DOTX027W][WARN]: Unable to retrieve linktext from target: 'simaprc-m-Loads-sb.xml'. 
```
Note that the missing file (simaprc-m-Loads-sb.xml) is in the same directory as simaprc-m-Loads.ditamap

**Comment by raducoravu** [comment]
@mariodigiacomo Can you try to maybe post a sample DITA project to reproduce the problem? Also can you try to publish with the regular PDF2 transtype? Also try to see if publishing with latest DITA OT 3.x downloaded from DITA OT website and with the regular PDF transtype encounters the same problem.

**Comment by mariodigiacomo** [comment]
I have been able to track the issue to the mapref step, where the hrefs for submaps are not converted to relative paths.  While I continue testing, can anyone tell me what the "keep-submap-href" parameter does?

**Comment by raducoravu** [comment]
As far as I know there is no such dita ot parameter. Maybe it’s part of your custom pdf3 plugin which is also not part of the dita ot standard install.

**Comment by mariodigiacomo** [comment]
OK.  Next idea.

Is there an existing way to force the generated map file in the temp directory to use absolute paths?

**Comment by mariodigiacomo** [comment]
Can someone at least tell me which process modifies/populates the HREF attributes in the generated ditamap?  I thought it was mapref, but my debug tests indicate the hrefs are already modified when href is set in maprefImpl.xsl

**Comment by shudson310** [comment]
I'm seeing a similar problem: net.sf.saxon.trans.UncheckedXPathException: I/O error reported by XML parser processing file

This is odd, because a completeness check passes and the file is at the path specified. For some reason, when the reference is resolved, the OT is looking in the wrong path.

**Comment by raducoravu** [comment]
@shudson310 I do not think your problem is similar with this one. It's similar with this one:
https://github.com/dita-ot/dita-ot/issues/3395
and usually occurs when there is some XSLT validation problem. Unfortunately right now the error does not contain all the information required to easily identify the problem.

**Comment by mariodigiacomo** [comment]
Problem not evident after updating to 3.4
