### ISSUE TITLE
Upgrade FOP to 2.4 to pick up change-bar support

### ISSUE THREAD

**Issue by kirkilj** [dita-ot/dita-ot#3406]
### Will 3.4 include FOP 2.4, which has finally been released w/ change-bar support? 

I looked at the Gradle files and couldn't find a version number in the fop-related configuration. I can see specific versions for other libraries. For future reference, let me know where I can find this.

**Comment by infotexture** [comment]
@kirkilj Not yet, but would probably make sense to upgrade this dependency while we're at it. 👍 

With the way we bundle FOP, there's no single line in the Gradle files that defines the version, but rather a list of libraries in various places (see 39f1ac4 for the previous changes for FOP 2.3)

**Comment by infotexture** [comment]
For context: FOP 2.4 was released yesterday (November 5, 2019). 

See https://xmlgraphics.apache.org/fop/2.4/releaseNotes_2.4.html for changes:

> - Require Java 7 or later
> - Drop dependency on Avalon-Framework
> - Add change bar generation
> - Add support for Khmer complex script

**Comment by infotexture** [comment]
Implemented for 3.4 in https://github.com/dita-ot/dita-ot/pull/3407.

**Comment by raducoravu** [comment]
Running some tests with the new Apache FOP and MathML equations, encountering this problem:

      [fop] Caused by: java.lang.NullPointerException
      [fop] 	at net.sourceforge.jeuclid.context.LayoutContextImpl.setParameter(LayoutContextImpl.java:192)
      [fop] 	at net.sourceforge.jeuclid.fop.JEuclidElement.createPropertyList(JEuclidElement.java:148)
      [fop] 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:291)

I will patch the JEuclid project on my side to avoid the problem. JEuclid is not that maintained unfortunately. Anyway, just wanted to add this here, it seems that the new FOP sets some parameters to various plugins and one of the parameters has a null value.

**Comment by ImtiazHiader** [comment]
@raducoravu is JEuclid patch for FOP 2.4 available?

**Comment by raducoravu** [comment]
If you download the Oxygen Publishing Engine (which is a DITA OT with custom plugins installed):
https://www.oxygenxml.com/publishing_engine/download.html
extract the ZIP and inside this folder:

   oxygen-publishing-engine-3.x/plugins/com.oxygenxml.pdf.css/lib/oxygen-pdf-chemistry/lib

you will find a JAR library called something like:

    oxygen-patched-jeuclid-core-22.0-20200212.185228-90.jar

which should be used instead of the original JEuclid core JAR library.
