### ISSUE TITLE
dita-ot-3.4 is missing /resources/project.rnc

### ISSUE THREAD

**Issue by qvrijt** [dita-ot/dita-ot#3409]
dita-ot-3.4:
According to the documentation, a dita-ot projectfile refers to an rnc file supplied with the toolkit to validate project files.

The xml-model expects it in `@href=../../../resources/project.rnc`, which resolves into `resources/project.rnc`.

And that file isn't in the released toolkit.

**Comment by infotexture** [comment]
@qvrijt Good catch Quick, thanks for spotting this. 

Looks like an oversight we can easily correct. I'll send a pull request to resolve this soon.

**Comment by infotexture** [comment]
To enable validation in the meantime, you can copy the [src/main/resources/project.rnc](https://github.com/dita-ot/dita-ot/blob/develop/src/main/resources/project.rnc) file from the source code repository to the `resources/` folder .

**Comment by qvrijt** [comment]
@infotexture I am so happy to see toolkit support for projects, Roger.
I have evolved from organizing documentation packages using listfiles, to ini.files and now to xml based projects. Super! Is the extension .ditaprj considered in the team?
