### ISSUE TITLE
Add some spans around trademark symbols in generated HTML5 and XHTML outputs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3416]
If you use something like this:

     <tm tmtype="reg"/>

you may want to match in the CSS the symbol and customize it a little bit.
We had this need for our PDF using CSS from HTML output and recently somebody else wanted this for the CHM output.

**Comment by robander** [comment]
Is this a request for support for that exact markup, `<tm tmtype="reg"/>`, with no content? 

That seems odd to me -- the element is meant to surround a trademark, such as 
`<tm tmtype="reg">MyCompany</tm>`

Using this element without any content seems like a way to use the `<tm>` element almost as a character entity -- like the desire is really to add `&reg;` but DITA does not define that entity.

I can understand surrounding the generated TM content with a span, like `<span class="tm">MyCompany®</span>`, but I'm not sure if that's the goal here.

**Comment by raducoravu** [comment]
Our particular end user wanted to control the vertical align of the symbol. Ideally for maximum flexibility we would have two spans, one around the tm text and one explicitly around the symbol:

           <span class="tm">MyCompany<span class="tm_symbol">®</span></span>
