### ISSUE TITLE
Plugin URI not working in mapref

### ISSUE THREAD

**Issue by mariodigiacomo** [dita-ot/dita-ot#3417]
How do I implement the plugin URI in mapref?  There's no xslt tag for the xmlcatalog element.

## Expected Behavior
<xsl:import href="plugin:org.dita.base:xsl/preprocess/maprefImpl.xsl"/> finds maprefimpl.xsl

## Actual Behavior
  [mapref] Error on line 8 column 80 of mapref.xsl:
   [mapref]   Malformed URL plugin:org.dita.base:xsl/preprocess/maprefImpl.xsl(base
   [mapref]   file:/C:/PROGRA~1/DITA-OT/dita-ot-3.4/plugins/org.dita.base/xsl/preprocess/mapref.xsl):
   [mapref]   unknown protocol: plugin

## Environment
* DITA-OT version: 3.4
* Operating system and version: Windows
* How did you run DITA-OT? Ant command

* Transformation type: Custom PDF

**Comment by robander** [comment]
Have you tried using the `dita` command to start your build? That is the preferred way to run DITA-OT builds, and may be doing more to set up your environment so that common JAR files and catalogs are located properly.

**Comment by mariodigiacomo** [comment]
The Ant command is inside of a script.  While it is possible to convert over, I would prefer not to to maintain backwards compatibility.  Is there documentation on what the command sets up?  There's nothing in the plugin uri docs that says it is a requirement.

**Comment by mariodigiacomo** [comment]
I tried it with dita.bat, but saw the same behavior:

"c:\Program Files\DITA-OT\dita-ot-3.4\bin\dita.bat" -i j:\3dxpreintdocr422/SIMACAEDoc/SIMACAECAERefResources.doc/src/simacae-m-ImpConcepts.ditamap -f pdf3 -o d:\temp\ditatest -Dcustomization.dir=C:/PROGRA~1/DITA-OT/dita-ot-3.4/plugins/com.3ds.xmfo/SMACustomization -Dargs.xmfo.formtter=distiller -t d:/temp/buildPDF-simacae-m-ImpConcepts -Ddita.dir=C:/PROGRA~1/DITA-OT/dita-ot-3.4 -Dgenerate.copy.outer=3 -Dargs.logdir=d:\temp\pdfout -Ddita.extname=xml -Dargs.indexshow=no -Dargs.artlbl=no -Dargs.draft=no -Dargs.fo.output.rel.links=yes -Dargs.fo.include.rellinks=nofamily -Dclean.temp=yes -v -d |tee
 ditabuild.log 2>&1

[ditabuild.log](https://github.com/dita-ot/dita-ot/files/3881204/ditabuild.log)

**Comment by raducoravu** [comment]
The problem is probably in your "pdf3" plugin, do you have an ANT target there with an "xslt" task which runs the mapref XSLT? If you do does that "xslt" task has a reference to the main DITA OT XML catalog? If it does is that "xslt" task wrapped inside a "pipeline" element? Maybe you can post some fragments from your custom build file.

Also this is not really a DITA OT bug. If you cannot reproduce a problem with DITA OT's base plugins, then it's probably a problem in your specific plugin. There is a DITA OT google group on which you can post such problems: https://groups.google.com/d/forum/dita-ot-users

**Comment by mariodigiacomo** [comment]
I don't _think_ it's a problem with my plugin, as this step is performed before any of my code.  But I've added the core xml files as attachments.
[org.dita.base.zip](https://github.com/dita-ot/dita-ot/files/3891947/org.dita.base.zip)

**Comment by raducoravu** [comment]
Can you give a precise sequence of steps that somebody who does not have your DITA DTD specialization and your PDF customization plugin can use to reproduce the issue on their computer?
For example:
1) Download a zip containing a small DITA project.
2) Download a fresh DITA OT 3.4 from the DITA OT web site.
3) Open the command line, run the command ...., the problem ca be reproduced.

**Comment by mariodigiacomo** [comment]
Can someone point me at an appropriate project?

**Comment by raducoravu** [comment]
@mariodigiacomo I do not understand what you mean. By project I mean a zip file containing a map plus one or two topics and maybe a PDF customization plugin. So that when the plugin is installed in the DITA Open Toolkit and the DITA Map is published the problem you reported can be reproduced.

**Comment by mariodigiacomo** [comment]
Ah, I misunderstood your request.

The problem doesn't seem to be related to my plugin, but in essence, I duplicated it by running ANT (although, as above, I've seen it with dita.bat as well) on a single xml file.  When it reaches the mappull step (which should be empty) it chokes on the XSL file because it does not recognize the plugin: namespace.

I'm trying to understand where the code would normally load the dita.catalog, since the pipeline does not have an xslt element.

**Comment by raducoravu** [comment]
Somewhere in the DITA OT build files you have something like this:

      <module class="org.dita.dost.module.MaprefModule">
        <param name="style" location="${dita.plugin.org.dita.base.dir}/xsl/preprocess/mapref.xsl"/>
        <ditafileset format="ditamap" input="true"/>
      </module>

This is probably the stage which breaks on your side. Looking at the Java code for the "org.dita.dost.module.MaprefModule" class:
https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/module/MaprefModule.java
it does this:

        transformerFactory.setURIResolver(CatalogUtils.getCatalogResolver());

The code for the CatalogUtils is this one:

https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/util/CatalogUtils.java

Now if I were to be able to reproduce the problem on my side I could try to add some logging in various places in the Java code and see what's going on.

You mentioned:

     The problem doesn't seem to be related to my plugin

Then try to remove the plugin, run the DITA OT integrator, then try to reproduce again the problem. If you can then give us a complete sequence of steps to reproduce the problem on our side.

**Comment by mariodigiacomo** [comment]
After further review, I think it **is** my plugin, but not the parts that we actually customized.  The order of operations is quite different in my "pdf3" transtype.  I've attached the build files and a test xml I was able to duplicate the error in.

[com.3ds.xmfo.zip](https://github.com/dita-ot/dit
[foo-c-c-example.zip](https://github.com/dita-ot/dita-ot/files/3932841/foo-c-c-example.zip)
a-ot/files/3932825/com.3ds.xmfo.zip)

I suspect that one of the newer intermediate steps between initialization and the java call is the solution.  Is there documentation on how things have changed?

**Comment by mariodigiacomo** [comment]
[com.3ds.xmfo.zip](https://github.com/dita-ot/dita-ot/files/3932849/com.3ds.xmfo.zip)

**Comment by raducoravu** [comment]
In your build file "plugins\com.3ds.xmfo\integrator.xml" there is at some point a reference to an XSLT stylesheet:

  <param name="style" value="${dita.dir}/plugins/com.3ds.xmfo/xsl/preprocess/topicmerge.xsl"/>

but the stylesheet is not present in your sample zip plugin.
