### ISSUE TITLE
Text overflowing table cells and the like is not clipped. Long text flows into adjacent cells/block, obscuring stuff there.

### ISSUE THREAD

**Issue by guanganyuan** [dita-ot/dita-ot#3424]
## Expected Behavior

Text overflowing table cells and the like is clipped when convering to PDF format.

## Actual Behavior

Text overflowing table cells and the like is not clipped when convering to PDF format.

## Steps to Reproduce

1. Create a .dita file and insert into tables;
2. Convert to PDF format;

https://github.com/guanganyuan/pptest1/blob/master/overflow%20table%20cell.png
## Environment

* DITA-OT version:3.4
* Operating system and version:
  _(macOS, Windows)_
* How did you run DITA-OT?
  _(`dita` command, CMS )_
* Transformation type:
  _(PDF2)_

**Comment by drmacro** [comment]
This is a limitation in FOP. If you used Antenna House Formatter you would see the text wrapped more or less as you expected.
The workaround is to inject zero-width space characters at suitable breakpoints in the text within table cells.

**Comment by kbrown01** [comment]
One persons "limitation" is another persons "feature". The proper implementation is to provide break points as zero-width space characters where the data owner can enforce the rules and not the breaking rules of the formatting engine. This is especially important in many medical/pharm documents like drug information, dosages and in drug names.

**Comment by guanganyuan** [comment]
> This is a limitation in FOP. If you used Antenna House Formatter you would see the text wrapped more or less as you expected.
> The workaround is to inject zero-width space characters at suitable breakpoints in the text within table cells.

thx, something is wrong when i injecting zero-width space characters. [the](https://github.com/guanganyuan/pptest1/blob/master/replace.png) stylesheet is lost.[https://github.com/guanganyuan/pptest1/blob/master/stylesheet%20is%20lost.png](url)
it should look like this.[https://github.com/guanganyuan/pptest1/blob/master/without%20injecting%20%20ZWSP.png](url)

**Comment by guanganyuan** [comment]
> One persons "limitation" is another persons "feature". The proper implementation is to provide break points as zero-width space characters where the data owner can enforce the rules and not the breaking rules of the formatting engine. This is especially important in many medical/pharm documents like drug information, dosages and in drug names.

thx a lot. It confused me. As a new man to dita-ot and xsl, I just do not know how to insert  ZWSP characters.  I have uploaded my files upstairs , can you help me to find the mistake?
