### ISSUE TITLE
Missing Nested topics in HTML5 ToC

### ISSUE THREAD

**Issue by cinthyargc** [dita-ot/dita-ot#3428]
### Description
I am experiencing an issue with HTML 5 and nested topics,  if they are part of a *.dita file, they are not being included in the Table of Content. Is this something that DITA-OT should handle as it's a valid DITA behavior? 

I am using this link as a reference: https://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/base/topicstructure.html

I have a map with a lot of topicrefs, let’s take as an example below

```xml
...
    <topicref href="../content/dita_with_inner_topics_here.dita"/>
....
```
Above topicref is pointing to a dita file containing nested topics:

```xml
<topic xml:lang="en-us" id="topic_parent_id ">
  <title>Parent topic</title>
     ...
     <topic xml:lang="en-us" id="topic_child_id_1">
       <title>Child topic title 1</title>
       ...
     </topic>
     <topic xml:lang="en-us" id="topic_child_id_2">
       <title>Child topic title 2</title>
       ...
     </topic>
</topic>
```

However, this inner topics are not being included in the table of contents, but they are in the content:

Table of Content, missing subtopics:
Section 10.2 - Verify hardware
**Section 10.3 - Parent topic**
Section 10.5 - Disable feature

Actual content including nested topics:
Section 10.3 - Parent topic
(topic_parent_id )
Note:
…
**Section 10.3.1 - Child topic title 1**

This is happening with HTML 5, and only affecting the Table of Content.

**Environment:**
MacOs
DITA-OT 3.4

Thank you!

**Comment by pflotscher** [comment]
I am facing the same issue right now. 
I know that it is not included because the ToC is created out of the `topicref`s in a `map`.
Since the org.dita.pdf2 creates ToC entries in a scenario like that I would expect the same from org.dita.html5.
Is there something I'm missing here?
