### ISSUE TITLE
Cannot properly expand abbreviated-form

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3431]
Based on this message:

https://groups.io/g/dita-users/message/44956

I'm attaching this sample project, when converted to PDF the warning appears and the abbreviated form reference is not properly expanded:

           [DOTX060W][WARN]: Key 'key_g_dccs' was used in an abbreviated-form element, but the key is not associated with a glossary entry. Abbreviated-form should ONLY be used to reference to a glossary entry.

[abbrevform-not-resolving.zip](https://github.com/dita-ot/dita-ot/files/3954354/abbrevform-not-resolving.zip)

I looked inside this XSLT stylesheet:

     plugins\org.dita.pdf2\xsl\fo\abbrev-domain.xsl

in this template:

    <xsl:template match="*[contains(@class,' abbrev-d/abbreviated-form ')]" name="topic.abbreviated-form">

this variable:

     <xsl:variable name="target" select="key('id', substring(@href, 2))[1]" as="element()?"/>

seems to match the topicref to the glossentry instead of the glossentry. Looking at the _MERGED.xml file, both the topicref to the glossentry and the glossentry element have the same @id attribute value which is wrong in my opinion. Also even if I manually set an @id attribute value on the glossref in the DITA Map:

           <glossref keys="key_g_dccs" href="glossary/g_dccs.dita#g_dccs" print="yes" id="test"/>

the @id attribute will not be preserved in the _MERGED.xml document.

A possible easy fix for this would be to rewrite the "target" variable as:

     <xsl:variable name="target" select="key('id', substring(@href, 2))[self::*[contains(@class,' glossentry/glossentry ')]]" as="element()?"/>

but the problem with the @id attribute set on two different elements with the same value in the _MERGED.xml document would remain.

**Comment by shaneataylor** [comment]
I think this is a duplicate of #2773 .

**Comment by raducoravu** [comment]
Duplicate of #2773
