### ISSUE TITLE
Better control of output folder location with DITA OT project file

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3432]
I have a DITA OT project file which defines an output folder:

    <deliverable name="Oxygen XML Blog to WebHelp Responsive">
      <context idref="blog"/>
      <output href="site"/>
      <publication transtype="webhelp-responsive"/>
    </deliverable>

Two problems:

1) The output folder is not interpreted relative to the project file, it's somehow relative to the DITA OT folder making it harder to control its final location.
2) The output path will actually contain an extra "out/" folder although I have not specified anywhere that I want that extra "out/" folder present, I just want my HTML files to be placed in the "site" folder.

So these two problems combine require an extra script to run after the publishing and actually move the content where it should have been located.

**Comment by PieterjanVandenweghe** [comment]
I have the same problem. We have our own output folder structure and scripts based on that structure.

```
<deliverable name="Knowledge Base Flow" id="kb_flow">
<context idref="kb_flow"/>
<output href="_output/webhelp_responsive/flow/__flow_knowledgebase.bookmap/"/>
<publication transtype="webhelp-responsive"/>
</deliverable>
```
Using the DITA-OT project file, files are currently saved to **out**/_output/webhelp_responsive/flow/__flow_knowledgebase.bookmap/

I would like the files to be saved in the defined relative path in the DITA-OT project file, without the extra 'out/' folder that is added by default at the moment.

**Comment by infotexture** [comment]
Per https://www.dita-ot.org/dev/topics/using-project-files.html, the `output` location specified in the project file is relative to the CLI `--output` directory.

The `out` directory is simply the default value that is used if no custom output folder is defined via the `--output` option when invoking the `dita` command.

So if you'd like to generate output in `/path/to/some/folder/`, pass that to the `dita` command:

    dita --project=project-file.xml --output=/path/to/some/folder/

Each deliverable in the project file will be generated there in subfolders corresponding to their output locations from the project file, for example:

```
/path/to/some/folder/
├── deliverable-A-output-folder
└── deliverable-B-output-folder
```

**Comment by raducoravu** [comment]
So this seems to work as designed.
