### ISSUE TITLE
No warning for broken in-topic link / unresolved link text.

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#3433]
## Expected Behavior

The attached topic has three invalid `@href` attributes that refer to content within the same file. When building HTML5 output, the result is a broken link and link text like `#jira680__twwo` and `#badtopic__twwo`

The build should warn about these unresolved links during `topicpull`.

## Actual Behavior

No message, clean build, bad output.

## Steps to Reproduce

Build the following topic to HTML5:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN"  "topic.dtd">
<topic id="jira680" xml:lang="en-us">
<title>Jira680</title>
<shortdesc>Why does this link not report an error</shortdesc>
<body>
<ol>
<li>First item! look at the second! <xref href="#./tvo"/> and <xref href="#jira680/twwo"/> and <xref
href="#badtopic/twwo"/></li>
<li id="two">whoops I broke my ID when I linked here</li>
</ol>
</body>
</topic>
```

## Environment

* DITA-OT version: 3.3.4
* Operating system and version: Windows
* How did you run DITA-OT? `dita` command 
* Transformation type: HTML5

**Comment by kirkilj** [comment]
@robander, you raised this a couple years ago. It looks like it was fixed in a forked OT repo, but not in the main repo. Do you know if this is still an issue in 3.7.1 or dev branch?
