### ISSUE TITLE
DITA 2.0: allow for new "specializations" attribute

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#3440]
## Description

With DITA 2.0, the `@domains` attribute is going away, along with most tokens that go in it -- https://github.com/oasis-tcs/dita/issues/217

The `@specializations` attribute is added to replace it, and only used for specialized attributes.

For DITA 2.0, we need to:

- Stop issuing this message when `@domains` is missing: `[DOTJ029I][INFO] No 'domains' attribute was found for element '<map>'. This generally indicates that your DTD or Schema was not developed properly according to the DITA specification.`
- Allow the new syntax for specialized attribute tokens when determining which attributes can be used for filtering

## Possible Solution

I'm not sure that the `DOTJ029I` is even needed.

If we want to keep supporting 1.3 while looking ahead to 2.0, we could possibly:

- Drop that message (not really needed)
- If a topic or map has `@specializations`, create `@domains` along side it with the right syntax
- If a topic or map has `@domains`, create `@specializations` with tokens for specialized attributes
- Steps that follow (core steps or extensions) will then work with either variant, and can be switched over in the future to be based on DITA 2.0 syntax

**Comment by jelovirt** [comment]
Sounds like a good plan. In the future, we will need to change all processing steps that use `@domains` to use `@specializations` instead, but that should be a separate story.

**Comment by raducoravu** [comment]
Yesterday I started coding similar things in Oxygen XML Editor, being able to handle both @domains and @specializations when determining specialization profiling attributes plus not issuing a warning that @domains no longer exists for DITA 2.0 and newer versions.

**Comment by raducoravu** [comment]
Question on this issue closed 2 years ago, if I search in all the XSLT stylesheets from the DITA OT I get 5-6 places where the @domains attribute is used, should we take into account at least in some of those places the new @specializations attibute?
