### ISSUE TITLE
pdf2: filtering of nested topicrefs runs into 'SXXP0003: Premature end of file' error

### ISSUE THREAD

**Issue by skulle** [dita-ot/dita-ot#3443]
## Expected Behavior
A nested topic in a submap (refer to topic3.xml in the attached sample) is filtered out by a ditavalref and the audience attribute

## Actual Behavior
The build aborts with an error:
```
[topic-fragment] Processing file:/C:/git/dita-sample-data/dita-ot-bug/temp/e91279b807935ed88f940757f71ca197b1a82a26.xml
[topic-fragment] Error 
[topic-fragment]   SXXP0003: Error reported by XML parser: Premature end of file.
[topic-fragment] Error 
[topic-fragment]   Error reported by XML parser processing
[topic-fragment]   file:/C:/git/dita-sample-data/dita-ot-bug/temp/e91279b807935ed88f940757f71ca197b1a82a26.xml: Premature end of file.
```

## Possible Solution
It seems that the problem is related to a `keys` attribute and the position of the `audience` attribute. 

The attached sample runs through if you remove the unused key k1 (document.ditamap) or if you move the audience attribute from the concept element (topic3.xml) to the topicref element (map.ditamap).

Currently I don't know how to fix the issue but I am looking into it. If anyone has some ideas I am glad to hear them.

## Steps to Reproduce
Please build `document.ditamap` with transtype `pdf2`
[sample.zip](https://github.com/dita-ot/dita-ot/files/4096293/sample.zip)

## Copy of the error message, log file or stack trace
[console.log](https://github.com/dita-ot/dita-ot/files/4096269/console.log)

## Environment

* DITA-OT version: 3.3.3
* Operating system and version: Windows 10 1909
* How did you run DITA-OT?  Ant, via ant-launcher.jar
* Transformation type: pdf2

**Comment by raducoravu** [comment]
The DITA OT never worked too well when you have profiling attributes set on the root element:
https://github.com/dita-ot/dita-ot/issues/3352

Maybe you can remove that 'audience="Internal"' attribute from the root element of the Topic3 and add it on the topicref instead:

            <topicref href="topic3.xml" audience="Internal" />

**Comment by skulle** [comment]
Thx for the quick reply Radu.
Yes I think we are going to move the audience attribute to the topicref. As far as I know it should not have been put there in the first place since our company guidlines prefer to have it on the topicref. Hopefully we can do this for all affected documents, including published documents, lets hope...

**Comment by raducoravu** [comment]
Well, if you don't to it for the published documents they won't get published :)
