### ISSUE TITLE
PDF - Stage "preprocess2" does not report not resolved conrefs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3446]
I'm attaching a sample project, the main DITA Map is `m_Key-Resolution-TEST.ditamap`.
There is a topic named `c_Keyref-source-TEST.xml` which is not referenced in the DITA Map as resource-only so because of that the conrefs to that topic are no longer resolved with the "preprocess2" PDF stage.

The problem can be fixed by referring to the `c_Keyref-source-TEST.xml` in the DITA Map as resource-only but such cases when conrefs cannot be resolved should be reported as error messages by the publishing engine, right now no message is issued and people have the impression that the conref has been resolved until they look inside the PDF.

[conref-keyref-test.zip](https://github.com/dita-ot/dita-ot/files/4138282/conref-keyref-test.zip)

**Comment by ZoeLawson** [comment]
I just ran into this myself. (And I've run into it in the past as well)
It's an easy fix, but unless you look at the output and notice that words are missing, there's nothing to help you out.

**Comment by android606** [comment]
Just wanted to add my vote that this is causing significant issues for me as well. I'm having to switch back to old 'preprocess' to keep folks happy.

**Comment by ckab74** [comment]
Adding my vote. I've run into this issue because keyrefs in conrefed files were no longer resolved, when we moved to 3.5.4, outputs seemed to run properly, but then we saw that the keyrefs were missing in our outputs. Adding the conrefed files to our main ditamaps solved the issue, but an error message to give you a hint would be a plus.

**Comment by raducoravu** [comment]
Thanks @jelovirt
