### ISSUE TITLE
Remove URI format check from external links

### ISSUE THREAD

**Issue by thendarion** [dita-ot/dita-ot#3456]
## Description
all hrefs are ckecked for URI format, so copy-pasted external links often throw errors even though they work just fine when clicked

## Possible Solution
skip external href format checks

**Comment by jelovirt** [comment]
@thendarion Could you add examples of invalid URIs that cause problems?

**Comment by thendarion** [comment]
sure, here's an example
`<xref href="https://cwmp-data-models.broadband-forum.org/tr-098-1-8-0.html#D.InternetGatewayDevice:1.InternetGatewayDevice.Layer2Bridging.Marking.{i}." format="html" scope="external" >InternetGatewayDevice.Layer2Bridging.Marking.{i}.</xref>`
I suspect that the culprit is the pair of curly braces in there

**Comment by jelovirt** [comment]
Yes, the problem are the curly braces. The URI should be escaped as `https://cwmp-data-models.broadband-forum.org/tr-098-1-8-0.html#D.InternetGatewayDevice:1.InternetGatewayDevice.Layer2Bridging.Marking.%7Bi%7D.`.

**Comment by thendarion** [comment]
IMHO, it's not lifelike for the writer to URI encode every external link they copy-paste, so dita-ot needs to handle them properly
