### ISSUE TITLE
Chunking with keyrefs in child map results in random HTML filenames

### ISSUE THREAD

**Issue by amantalwar04** [dita-ot/dita-ot#3457]
## Expected Behavior
I have a ditamap which uses chunking on a topicref keyref on a child map. For example:

> PARENT Map - test.ditamap

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/map.dtd">
<map title="Growing Flowers">

  <keydef href="carenew.dita" keys="T2" type="topic">
    </keydef>
  <keydef href="careanother.dita" keys="T3" type="topic">
    </keydef>
  <keydef href="care.dita" keys="T1" navtitle="care" type="topic" format="dita" id="careid"
     ></keydef>
  <keydef href="careful.dita" keys="T4" navtitle="Careful" type="topic">
  </keydef>
  <keydef href="careless.dita" keys="T5" navtitle="Careless" type="topic">
  </keydef>
  <keydef href="test_more.ditamap" format="ditamap" keys="M1" />
  
  <topichead navtitle="Growing Trees">
    <mapref keyref="M1" format="ditamap"/>
  </topichead>

  <topicref keyref="T2"/>
  <topicref keyref="T3"/>
</map>
```

> CHILD Map - test_more.ditamap

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "http://docs.oasis-open.org/dita/v1.1/OS/dtd/map.dtd">
<map id="treemore" title="Growing Trees">
  
  <topicref keyref="T2" locktitle="yes"/>
  <topicref keyref="T1" chunk="to-content" format="dita">
    <topicref keyref="T4" locktitle="yes" navtitle="test1"/>
    <topicref keyref="T5" locktitle="yes" navtitle="test2"/>
    </topicref>
</map>

```
I expect the XHTML output to NOT to generate something like "chuck123456789.html" for the topics chunked in the CHILD map. 

## Actual Behavior
The XHTML output has random HTML file names, something like "chunk123456789.html" for all the chunked topics.

## Steps to Reproduce
1. Use the attached [test.zip](https://github.com/dita-ot/dita-ot/files/4212013/test.zip) archive and generate XHTML output preferably using the WebHelp Responsive transformation scenario.

2. Launch the Webhelp. Observe that all the chunked topics are renamed to chunk_<random_number>_.html. 

## Environment

* DITA-OT version: 3.x
* Operating system and version:
  _(Windows)_
* How did you run DITA-OT?
  _( oXygen)_
* Transformation type:
  _(HTML5, PDF, custom, etc.)_

**Comment by amantalwar04** [comment]
We have a customer release coming up and would like to have a fix/patch at the earliest. Thank you for your help and support.

**Comment by raducoravu** [comment]
@amantalwar04 thanks for the bug report and the samples. This is an open source project, it's maintained by volunteers and we cannot commit to a deadline for a fix. The code which deals with chinking has always had various problems. 
Maybe in the meantime you can try to find a workaround in order not to block your release, maybe create a DITA topic which has conrefs to those three topics and refer to that newly created DITA topic in your DITA Map.

**Comment by amantalwar04** [comment]
@raducoravu thanks for the help and support. I was wondering if there could an XSLT that can read all the child maps and replace the maprefs with topicrefs from the child maps?
For example, the current implementation which is achieved using `<mapref>` is:
```
map a
|_____map a1
|_____map a2
      |_______map a21
      |_______map a22
              |_______map a221
```
What I think we need is an XSLT that reads all the ditamap files and creates one single map (Map_unified.ditamap) with all the topic refs in map a1, map a2, map a21, map a22, and map a221.

I am sure with this processing, we should be able to fix the chunk<random_number>.html issue. What do you think?

**Comment by raducoravu** [comment]
The DITA OT code is quite complex, you can read more about its architecture here:

https://www.dita-ot.org/dev/reference/architecture.html

It has Java stages and XSLT stages. 
That particular output file with a funny name is generated probably in one of the Java processing stages. 
Even if you would just be able to rename that HTML file to some other name, that might not be enough, you would need to also make changes to all links which refer to elements inside that chunked HTML file.
You might also try some post processing, somehow make changes to the generated HTML documents.

**Comment by amantalwar04** [comment]
Thanks, Radu.

| AMAN TALWAR
   Technical Documentation and Localization-XHD
   867.4339

**Comment by drmacro** [comment]
The DITA Community "DITA Utilities" project includes a relatively-simple XSLT transform to resolve map references: https://github.com/dita-community/dita-utilities/tree/master/src/xslt/map-to-map-transform

That might do what you need.
