### ISSUE TITLE
DITA to XEP fails with certain index term combinations

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3460]
Add in a DITA topic this prolog:

      <prolog><metadata> <keywords><indexterm>Web Server<indexterm>maintain</indexterm></indexterm><indexterm>maintain2</indexterm> </keywords></metadata></prolog>

and publish to PDF using XEP, publishing fails with errors like:

       [xep] [XEPJ002E][ERROR] no entries for index key 'indexid-1836659637'

This particular problem was added as a side effect in #3320

As a possible workaround although I'm not sure if it's the right one, in the index_xep.xsl at the line:

    <fo:inline id="{@indexid}"/>

add an extra indexkey attribute with the same value:

    <fo:inline id="{@indexid}" index-key="{@indexid}"/>

**Comment by infotexture** [comment]
Is this the same issue reported in #3447 and fixed in the 3.4.1 hotfix queue with #3450 & #3455?

**Comment by raducoravu** [comment]
Nope, #3447 allowed the XEP PDF generation with index terms to work again (fixing a side effect from #2110) but in doing so it uncovered this second problem which is a side effect of another fix by @robander in #3320.

**Comment by infotexture** [comment]
Ah, OK, good to know.

@robander If we're planning to ship other fixes for XEP indexing issues with 3.4.1, would it make sense to also include the changes proposed above in 3.4.1?

**Comment by robander** [comment]
It's been a while since I did that fix but @raducoravu that does sound like the right update. And yes, I think aim it at 3.4.1.
