### ISSUE TITLE
In project files, allow DITAVAL to be specified in both <context> and <deliverable>

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3474]
## Description
The new "project file" feature in DITA-OT 3.4 is great! Organizing multiple deliverables has been a pain point of ours.

We have separate DITAVAL files for **filtering** content based on @product and **highlighting** content based on @rev. Thus, we would need DITAVAL support in the `<deliverable>` elements as well.

## Possible Solution
A proposed example is as follows (note the **REQUESTED FEATURE** comments):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://www.dita-ot.org/project">

  <!-- source material contexts -->

  <context name="Product A User Guide" id="A_Context">
    <input href="A.ditamap"/>
    <profile>
      <ditaval href="ditaval/onlyA.ditaval"/>
    </profile>
  </context>
  <context name="Product B User Guide" id="B_Context">
    <input href="B.ditamap"/>
    <profile>
      <ditaval href="ditaval/onlyA.ditaval"/>
    </profile>
  </context>

  <!-- output scenarios -->

  <deliverable name="Product A Review PDF" id="A_PDF_review">
    <context idref="A_Context"/>
    <output href="./A-PDF-review"/>
    <publication transtype="pdf"/>
    <ditaval href="ditaval/flag_rev.ditaval"/>   <!-- ***REQUESTED FEATURE*** -->
  </deliverable>
  <deliverable name="Product A Final PDF" id="A_PDF_final">
    <context idref="A_Context"/>
    <output href="./A-PDF-final"/>
    <publication transtype="pdf"/>
    <!-- note no DITAVAL file here -->
  </deliverable>

  <deliverable name="Product B Review PDF" id="B_PDF_review">
    <context idref="B_Context"/>
    <output href="./B-PDF-review"/>
    <publication transtype="pdf"/>
    <ditaval href="ditaval/flag_rev.ditaval"/>   <!-- ***REQUESTED FEATURE*** -->
  </deliverable>
  <deliverable name="Product B Final PDF" id="B_PDF_final">
    <context idref="B_Context"/>
    <output href="./B-PDF-final"/>
    <publication transtype="pdf"/>
    <!-- note no DITAVAL file here -->
  </deliverable>

</project>
```

**Comment by jelovirt** [comment]
@georgebina @raducoravu What's your take on this? IMO we should not implement this by just adding the support `ditaval` in `deliverable`. I deliberately left out extending from the 1.0 release.

IMO instead of

```xml
<deliverable name="Product B Review PDF" id="B_PDF_review">
    <context idref="B_Context"/>
    <output href="./B-PDF-review"/>
    <publication transtype="pdf"/>
    <ditaval href="ditaval/flag_rev.ditaval"/>   <!-- ***REQUESTED FEATURE*** -->
  </deliverable>
```
we should support
```xml
<deliverable name="Product B Review PDF" id="B_PDF_review">
    <context idref="B_Context">
        <ditaval href="ditaval/flag_rev.ditaval"/>   <!-- ***REQUESTED FEATURE*** -->
    </context>
    <output href="./B-PDF-review"/>
    <publication transtype="pdf"/>
  </deliverable>
```

But the question is, how does it extend the `context`. Does it replace existing `ditaval` or add to the existing profiling. How about if you extend with `input`? We don't support multiple `input` at this time and I don't want extending be addition or replace based on what you extend.

**Comment by georgebina** [comment]
I understand the requirement - it comes from the fact that DITAVAL contains publishing (flagging) information, together with the filtering (include/exclude) information. 
From this point of view, I think adding a flagging filter in the deliverable makes more sense than allowing additional filters dynamically in context, but if we do that, we need to make it clear that it is a flagging only filter. This means, we should filter out other information from that filter, if it contains include/exclude instructions. So maybe something like below will capture this idea better:

```xml
<deliverable name="Product B Review PDF" id="B_PDF_review">
    <context idref="B_Context"/>
    <output href="./B-PDF-review"/>
    <publication transtype="pdf"/>
    <flag href="ditaval/flag_rev.ditaval"/>   <!-- ***REQUESTED FEATURE*** -->
  </deliverable>
```

Alternatively, maybe the flagging belongs better to the publication element:

```xml
<deliverable name="Product B Review PDF" id="B_PDF_review">
    <context idref="B_Context"/>
    <output href="./B-PDF-review"/>
    <publication transtype="pdf">
      <flag href="ditaval/flag_rev.ditaval"/>   <!-- ***REQUESTED FEATURE*** -->
    </publication>
  </deliverable>
```

If we want to define overwrites on referred context and publication element, we should discuss that as a separate issue, I think, with its own motivation.

Regards,
George

**Comment by chrispy-snps** [comment]
Some background information:

- We have nearly 200 books.
- They are grouped in various ways (product families, functional areas), with 1-3 filtering conditions per group.
  - Some books have both PDF and OLH deliverables, and some are PDF-only.
  - All books have both PDF-final and PDF-review deliverables.
  - We use a collaborative PDF-based review flow for documentation updates.

We fully agree on the desire for separation between filtering settings (input side) and flagging settings (output side); they are orthogonal.

**Comment by chrispy-snps** [comment]
I proceeded forward by specifying the flagging DITAVALs in the contexts. In Oxygen, this has the consequence of doubling up the context options presented to the user (attached).

![image](https://user-images.githubusercontent.com/50950969/76529527-c98b6480-6448-11ea-88aa-448e2f1e09bb.png)

**Comment by chrispy-snps** [comment]
What can we do to increase the priority for this?

**Comment by chrispy-snps** [comment]
I tried to resolve this by using `<param>` to set the `args.filter` parameter inside an id-reused `<publication>` definition:

```
  <publication transtype="pdf2" id="pub-pdf-review">
    <param name="args.draft" value="yes"/>
    <param name="args.filter" value="ditaval/flag_review.ditaval"/>
    <param name="output.dir" value="out-review/pdf"/>
  </publication>
```

but unfortunately this didn't work - `args.draft` was used, but `args.filter` and `output.dir` **were not used**.

Testcase attached:

[dita_project_file.zip](https://github.com/dita-ot/dita-ot/files/5919497/dita_project_file.zip)

To reproduce, run:

`dita --project=books.xml --deliverable="del-pdf-review-prodA_ug" --verbose`

then note in the log output that the two parameters are not used.

This seems like a bug that should be fixed -- and **once fixed, would meet the original need**. Should I repurpose this issue to having the `<publication>`-level `<param>` elements honored?

**Comment by chrispy-snps** [comment]
The `args.filter` behavior seems to be its own bug when filtering DITAVAL is specified in `<context>` and flagging DITAVAL is defined in `<publication>`, so I filed a separate issue for it:

[In DITA-OT project files, support incremental "args.filter" in <publication> elements #3690](https://github.com/dita-ot/dita-ot/issues/3690)

This leaves the `output.dir` argument being ignored, which I now believe is not a bug because we don't directly accept `-Doutput.dir` on the command line either:

`Error: Property output.dir cannot be set with -D, use -o instead`

Given these findings, I am closing this issue and allowing #3690 to carry the torch forward.
