### ISSUE TITLE
args.input has incorrect prefix 'file:' when read from a project file

### ISSUE THREAD

**Issue by thendarion** [dita-ot/dita-ot#3486]
## Expected Behavior
args.input=/my/path

## Actual Behavior
args.input=file:/my/path

## Steps to Reproduce
1. create a project file (tried XML)
2. run a transformation

## Environment

* DITA-OT version: 3.4.1
* Operating system and version: Linux
* How did you run DITA-OT? dita
* Transformation type: PDF

**Comment by jelovirt** [comment]
The `args.input` is a system path or URI, thus `file:/my/path` should work correctly. What is the actual failure you get?

**Comment by thendarion** [comment]
OK, it might be my plugin then

I use the depend.preprocess.pre extension point, and at that point there's not much I can access, because most internal variables are not available yet
I try to process args.input but 'file:' is blocking my efforts in certain cases
as a workaround, now I remove 'file:' from args.input
but it would be better if args.input didn't have 'file:' in some cases only -- it should be either never or always, so people knew what to expect and could develop their extensions accordingly

**Comment by jelovirt** [comment]
We can't change `args.input` at this point because of backwards compatibility. It's either a system path or a URI. Plugin developers need to accept both types of values.

**Comment by thendarion** [comment]
I see. somehow I thought that it is a system path to the outside world and only DITA-OT handles it as a URI

I guess that concludes this ticket then

thanks :)
