### ISSUE TITLE
Improve CLI help for subcommands

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#3492]
## Description

In previous releases, the CLI help included basic descriptions for the following arguments:

```
  --install [<file>]          install plug-in from a local ZIP file
  --install [<url>]           install plug-in from a URL
  --install [<id>]            install plug-in from plugin registry
  --install                   reload plug-ins
  --uninstall <id>            uninstall plug-in with the ID
  --plugins                   print list of installed plug-ins
  --transtypes                print list of installed transtypes
  --deliverables              print list of deliverables in project
  -h, --help                  print this message
  --version                   print version information and exit
```

## Current Behavior

Now that subcommand help has moved to dedicated `dita subcommand --help` with #3437, the top-level entries for the subcommands are empty, and nothing indicates that more info is available via `dita subcommand --help`:

```
$ dita --help
Usage:
  dita -i <file> -f <name> [options]
  dita --project=<file> [options]
Subcommands:
  deliverables
  install
  plugins
  transtypes
  uninstall
  version
```

## Expected Behavior

To help users understand the purpose of each subcommand, it would be good if a basic description could be presented alongside each subcommand in the `dita --help` output, and find a place to indicate that details are available for each via `dita <subcommand> --help`:

```
$ dita --help
Usage:
  dita -i <file> -f <name> [options]
  dita --project=<file> [options]
Subcommands:
  deliverables      Print list of deliverables in project file
  install           Install or reload plug-ins
  plugins           Print list of installed plug-ins
  transtypes        Print list of installed transformation types (output formats)
  uninstall         Remove and delete plug-in
  version           Print version information and exit

  See 'dita <subcommand> --help' for details about a specific subcommand.
```

For subcommands with multiple arguments, it looks like the arguments are missing next to their descriptions:

```
dita install --help
Usage:
  dita install [<file> | <url> | <id>]
Arguments:
                 install plug-in from a local ZIP file
                 install plug-in from plugin registry
                 install plug-in from a URL
```

Expected to see something like this instead:

```
dita install --help
Usage:
  dita install [<file> | <url> | <id>]
Arguments:
  <file>       Install plug-in from a local ZIP file
  <url>        Install plug-in from a URL
  <id>         Install specified plug-in ID from registry
```

**Comment by infotexture** [comment]
@jelovirt I just noticed that `dita help` is not currently listed among the subcommands, although it _does_ work without the double hyphens.

Would you prefer to view that as an option (rather than a subcommand) for consistency with the `dita subcommand --help` syntax, or what's the rationale there?

**Comment by jelovirt** [comment]
`dita help` is there as a fallback. The preferred form is `dita --help` and `dita subcommand --help`.
