### ISSUE TITLE
RNG default attributes expansion causes the mathml namespaces to be removed

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3499]
I have  a RNG topic containing an embedded MathML equation:
[oxygen_eqn.zip](https://github.com/dita-ot/dita-ot/files/4448722/oxygen_eqn.zip)

If it gets published to PDF and the temporary files folder is kept from being deleted we can notice in the temporary files folder that the processed topic no longer has the mathml namespace set on the "math" element, thus the MathML processor will no longer be able to process the equation in the PDF.

**Comment by raducoravu** [comment]
The problem seems to be in the "org.ditang.relaxng.defaults.RelaxNGDefaultsComponent", I will compare it with the one we have in the Oxygen main library, see if it needs to be updated in some way.

**Comment by raducoravu** [comment]
I would like to add a fix for this, should I create a pull request on the "develop" branch? Are there any automatic tests with RNG topic processing?

**Comment by jelovirt** [comment]
@raducoravu I don't think we have any tests for RNG processing. Please make the PR against `release/3.5` branch. So first check out `release/3.5` and then create your feature branch from there.
