### ISSUE TITLE
Customizing the PDF extension doesn't work

### ISSUE THREAD

**Issue by afriron** [dita-ot/dita-ot#3517]
## Expected Behavior
In the plug-in that extends the capabilities of PDF have to work set through customization.dir.

## Actual Behavior
The standard "org.dita.pdf2" plugin ignores the "customization.dir" setting.

## Steps to Reproduce

1. Copy folder "com.example.print-pdf" from dita-ot-3.5\docsrc\samples\plugins\ to DITA OT\plugins
2. Change string 
` <xsl:variable name="page-height">297mm</xsl:variable>` in file plugins\com.example.print-pdf\cfg\fo\attrs\custom.xsl to `<xsl:variable name="page-height">100mm</xsl:variable>`.
3. Run dita-ot-dir/bin/dita --install
4. Run bin\dita --input=my.ditamap --format=print-pdf

Document is builded, but the page size remains standard.
My own plugin that extends PDF in a similar way (using "customization.dir") worked in version 3.3.4, but doesn't work in 3.5.

* DITA-OT version: 3.5
* Operating system and version: Windows
* I run DITA OT: bin\dita --input=my.ditamap --format=print-pdf
* Transformation type: custom ("com.example.print-pdf")

**Comment by infotexture** [comment]
Verified on macOS with the latest code on the `hotfix/3.5.1` branch (9823515).

Followed the steps above, resulting PDF is indeed generated with the default Letter page size 
— custom page height is not applied.

**Comment by jelovirt** [comment]
This is a regression bug in the move to S9API, affecting all code that uses the `<pipeline>` `<xslt`> where the XSLT compiling requires XML resolver.
