### ISSUE TITLE
Regression when using key scopes

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3524]
Our automated tests run on a DITA OT 3.5.1 build have discovered a regression to issue #2538
I'm attaching a sample project:
[Archive.zip](https://github.com/dita-ot/dita-ot/files/4720897/Archive.zip)

If you publish the UserGuide.ditamap to HTML5 and open the index.html, the first "Configuration" link should refer to a "Configuration.html" file and the second link should refer to a "Configuration-1.html" file. 
With DITA OT 3.5.1 both these links refer to the same target file (Configuration.html).
With DITA OT 3.4.2 the links refer to different HTML files (which is correct).

**Comment by raducoravu** [comment]
This might be related to the commit in which the "merge" method was added to the KeyScope class but I'm not sure about that.

**Comment by raducoravu** [comment]
Found out why this does not work, the method:
org.dita.dost.module.KeyrefModule.walkMap(Element, KeyScope, List<ResolveTask>)
at some point modifies the href value directly on DOM elements like:

     hrefNode.setValue(value.toString());

In DITA OT 3.4.1 for example after "collectProcessingTopics" was called the DOM map element was saved on disk like this:

            final List<ResolveTask> jobs = collectProcessingTopics(fis, rootScope, doc);
            writeMap(in, doc);

but that "writeMap(in, doc)" line is missing in the 3.5.1 code so the DITA Map modified by side effect by the method "walkMap" is no longer serialized on disk.

**Comment by raducoravu** [comment]
@jelovirt any feedback on this?

**Comment by jelovirt** [comment]
@raducoravu confirmed this and the regression was that the map was saved too early, before modifying the map.
