### ISSUE TITLE
toc-attr_fop.xsl not found (PDF plugin)

### ISSUE THREAD

**Issue by tec-lab** [dita-ot/dita-ot#3543]
The attached plugin was generated using the PDF plugin generator (http://dita-generator.elovirta.com/).

## Expected Behavior
Create a PDF

## Actual Behavior
An error occurs that toc-attr_fop.xsl is not found. Which actually is not part of the dita-ot distribution.

## Steps to Reproduce
Install the atos.zip plugin.
Run the dita generator with the "space" transformation:
`dita --input=test.ditamap --format=space`

## Copy of the error message, log file or stack trace
```
[pipeline] Error on line 80 column 79 of topic2fo_shell_fop.xsl:
 [pipeline]   XTSE0165: I/O error reported by XML parser processing
 [pipeline]   file:D:/Programs/dita/plugins/org.dita.pdf2.fop/cfg/fo/attrs/toc-attr_fop.xsl:
 [pipeline]   D:\Programs\dita\plugins\org.dita.pdf2.fop\cfg\fo\attrs\toc-attr_fop.xsl (The system
 [pipeline]   cannot find the file specified)
Error: The following error occurred while executing this line:
D:\Programs\dita\plugins\org.dita.pdf2\build.xml:278: java.lang.RuntimeException: Failed to compile stylesheet 'D:\Programs\dita\plugins\atos\xsl\fo\topic2fo_shell_fop.xsl': I/O error reported by XML parser processing file:D:/Programs/dita/plugins/org.dita.pdf2.fop/cfg/fo/attrs/toc-attr_fop.xsl: D:\Programs\dita\plugins\org.dita.pdf2.fop\cfg\fo\attrs\toc-attr_fop.xsl (The system cannot find the file specified)
```

## Environment
Windows 10
dita 3.5.2

**Comment by tec-lab** [comment]
[atos.zip](https://github.com/dita-ot/dita-ot/files/4880374/atos.zip)

**Comment by jelovirt** [comment]
This is a [known limitation](https://github.com/jelovirt/pdf-generator/issues/18) in the generator, not in DITA-OT. The PDF plugin generator does _not_ support DITA-OT 3.5.
