### ISSUE TITLE
DITA 2.0 topic is reported as invalid

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3586]
I validate this topic in Oxygen XML Editor using the DITA 2.0 RNGs included in DITA OT 3.5.1:

    <?xml-model href="urn:oasis:names:tc:dita:rng:topic.rng:2.x" schematypens="http://relaxng.org/ns/structure/1.0"?>
    <?xml-model href="urn:oasis:names:tc:dita:rng:topic.rng:2.x" schematypens="http://purl.oclc.org/dsdl/schematron"?>
    <topic id="abcdef">
    <title>ABCDEF</title>
    <body><p></p></body>
    </topic>

I obtain the error:

    System ID: /Users/raducoravu/eclipse-workspace/eXml/frameworks/dita/DITA-OT3.x/plugins/org.oasis-open.dita.v2_0/rng/base/commonElementsMod.rng
      Engine name: Jing
     Severity: error   
     Description: group of "string" or "data" element
      Start location: 2673:77

**Comment by raducoravu** [comment]
In "plugins/org.oasis-open.dita.v2_0/rng/base/commonElementsMod.rng" there is a define for stentry attributes:

             <define name="stentry.attributes">

for all attribute definitions there the "data" elements should be placed inside them instead of siblings, same for the "choice" element which should be inside the attribute definition.

**Comment by robander** [comment]
Looks like this should be reported to the OASIS TC to fix, but keep this open to track updating to a new version of the beta grammar files.

**Comment by raducoravu** [comment]
@robander should I report it or will you?
