### ISSUE TITLE
Latest dev code fails unless temp directory is specified

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#3589]
## Expected Behavior

Build runs without need to specify `-temp` parameter.

## Actual Behavior

Fails with a null pointer exception unless `-temp` is specified with the CLI.

## Steps to Reproduce
With latest `develop` branch, run
`dita -i src/main/docsrc/samples/hierarchy.ditamap -f html5 -o out`

Build fails immediately with 
`Error: java.lang.NullPointerException`

Works as expected if I add `-temp ./temp` to the command line

## Environment

* DITA-OT version: latest `develop`
* Operating system and version: macOS
* How did you run DITA-OT? `dita` command
* Transformation type: (any)

**Comment by infotexture** [comment]
Fixed with #3593.
