### ISSUE TITLE
Links with trailing #IDs break in PDF output

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#3592]
## Expected Behavior

Valid HTML links should be preserved as authored in all output formats.

## Actual Behavior

Links that end with a fragment identifier `#ID` pointing to a subordinate resource  _(like deep links to the DITA spec)_ work fine in HTML output, but break in PDF output. 

### Given a source URL with a trailing `#ID`

- http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/ditaval/ditaval-revprop.html#ditaval-revprop

### Link URL is output with `%23`

- http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/ditaval/ditaval-revprop.html%23ditaval-revprop

## Possible Cause

Looks like `preprocess2` may be overzealously normalizing something along the way and URL-encoding the hash mark `#` that precedes the ID at the end of the URL, resulting in broken links.

## Environment

* DITA-OT version: latest `develop` branch @ b4996131e07bb1960794c5507760ec1eee48e112
* Operating system and version:  _macOS_
* How did you run DITA-OT? _`dita` command_
* Transformation type:  _PDF_

**Comment by jelovirt** [comment]
I can't reproduce this right now. @infotexture are you still able to reproduce this and attach a test case?

**Comment by infotexture** [comment]
☑️ Closing as no longer reproducible with DITA-OT 4.1.2.

The DITA-OT docs topic [Generating revision bars](https://www.dita-ot.org/dev/topics/pdf2-creating-change-bars) links to the DITA [specification](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/ditaval/ditaval-revprop.html#ditaval-revprop) for the `@changebar` attribute of the `<revprop>` element, and this link is correctly created with the `#ditaval-revprop` fragment identifier in the 4.1.2 distribution docs PDF.
