### ISSUE TITLE
Non existing xml catalog mappings for DTDs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3601]
I updated to DITA OT 3.5.4, we have an automated test pointing out not existing file references in the XML catalogs, it found these problems. Each error message first shows the missing file path and the path to the XML catalog where it's referenced.

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\bookmap\dtd\bookmap.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/bookmap/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\concept.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\glossentry.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\glossgroup.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\reference.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\task.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\troubleshooting.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.v2_0\dtd\subjectScheme\subjectScheme.ent` does not exist from file
`…/org.oasis-open.dita.v2_0/dtd/subjectScheme/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\bookmap\dtd\bookmap.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/bookmap/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\concept.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\glossentry.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\glossgroup.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\reference.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\task.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.techcomm.v2_0\dtd\technicalContent\dtd\troubleshooting.ent` does not exist from file
`…/org.oasis-open.dita.techcomm.v2_0/dtd/technicalContent/catalog.xml`

The file
`…\org.oasis-open.dita.v2_0\dtd\subjectScheme\subjectScheme.ent` does not exist from file
`…/org.oasis-open.dita.v2_0/dtd/subjectScheme/catalog.xml`

**Comment by infotexture** [comment]
@raducoravu I edited above to replace the redundant local paths with `…` but I wonder if the path separators are significant. 🤔 

The first entry on each line uses Windows backslashes, whereas the catalog references each use UNIX slashes.

**Comment by raducoravu** [comment]
@infotexture thanks for the help. The auto tests are running on Windows, hence the path separators in the reported problems. But the problems exist. For example you can open "DITA-OT/plugins/org.oasis-open.dita.techcomm.v2_0/dtd/bookmap/catalog.xml", it has two references to ""dtd/bookmap.ent"" but the ent file is not located in the "dtd" subfolder.

**Comment by infotexture** [comment]
OK, got it. Just wanted to make sure that wasn't the problem.

Sounds like something that will need to be fixed in the upstream grammar files. 

cc/ @robander

**Comment by robander** [comment]
This has been fixed at OASIS, so I think we just need to update the versions shipped in DITA-OT to the latest beta grammar files. 

Base catalog update: https://github.com/oasis-tcs/dita/commit/114f8a1ed0195adba111caa83ba761d1c94a2f8d

Tech comm update: https://github.com/oasis-tcs/dita-techcomm/commit/6c6b5856f2b3b15480efece062ba69b4e9224c3e#diff-4e8930cb06a54258af0b118762a261da

**Comment by robander** [comment]
Fixed for next release with #3617
