### ISSUE TITLE
Cannot conref push table after paragraph

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3605]
According to the DITA specification I should be able to push a table after an existing paragraph as long as they have equivalent parent elements:
https://www.oxygenxml.com/dita/1.3/specs/langRef/attributes/theconactionattribute.html?hl=conref%2Cpush%2Cafter#theconactionattribute__pushing-content

> Either the container elements of the source and target match, or the container of the source element is be a specialization of the target's container.

But this does not seem to work for me, the DITA OT issues this warning:

    
```
[DOTJ043W] The conref push function is trying to replace an element that does not exist (element "#t2/p1" in file "...\temp\html5\target2.dita").
```

I'm attaching a sample DITA project:
[conref-push-table-para.zip](https://github.com/dita-ot/dita-ot/files/5331470/conref-push-table-para.zip)

**Comment by raducoravu** [comment]
@robander can you maybe give me feedback about whether this should work or not? So about pushing an element with a name after an element with another name, as long as they have the same parent element type.

**Comment by raducoravu** [comment]
oops, I think this is a duplicate of #3555

**Comment by jelovirt** [comment]
Closing as duplicate
