### ISSUE TITLE
Add licensing conditions for the OASIS 2.0 DITA schemas

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3608]
There are two DITA OT plugins "org.oasis-open.dita.techcomm.v2_0" and "org.oasis-open.dita.v2_0". They come from the OASIS GitHub project which has other licensing terms.

Stefan our CEO looked over this aspect and would feel more comfortable with us distributing the DITA OT if you specified that those plugins have different licensing terms.
I quote from what he said:

> In the NOTICES.txt maybe an entry can be added after line 41 which would mention the DITA 2.0 DTD, XSD and RNG schemas, mention their licensing terms, adding the licensing terms to a file named "oasis-dita20.txt" like they did for DITA 1.2 and 1.3. In that "oasis-dita20.txt" file maybe they can add the content of page 3 from this PDF: https://www.oasis-open.org/committees/download.php/65576/dita-2.0-specification.pdf

**Comment by raducoravu** [comment]
@robander does it make sense to add different licensing terms for the two plugins?

**Comment by raducoravu** [comment]
Here's what I did for the DITA OT bundled with Oxygen 23:
Added here:
plugins/org.oasis-open.dita.v2_0
this license file:
[license.txt](https://github.com/dita-ot/dita-ot/files/5642204/license.txt)

and added information about DITA 2.0 schemas in the NOTICES.txt:


[NOTICES.txt](https://github.com/dita-ot/dita-ot/files/5642211/NOTICES.txt)

**Comment by robander** [comment]
Adding notices section from the PDF as suggested, and as confirmed with Kris. I haven't put a separate license file into the plugin itself; adding the full notices matches what we currently deliver for DITA 1.3.
