### ISSUE TITLE
HTML5 fails with schema-based map having chunk=to-content

### ISSUE THREAD

**Issue by takesson** [dita-ot/dita-ot#3620]
## Expected Behavior
Transformation into HTML5 should work and produce a single chunk.

## Actual Behavior
Fails with error. The temporary ditabase does not have the xsi namespace declaration.

## Possible Solution
I suspect the declaration of xsi is not propagating to the pseudo-topic created when chunk=to-content is set on the map root element (assuming those declarations are propagating to the ditabase...).
```xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"```

## Steps to Reproduce

1. Create Sample.ditamap using xsi:noNamespaceSchemaLocation
2. ```bin/dita -f html5 -Droot-chunk-override=to-content -i Sample.ditamap```

## Copy of the error message, log file or stack trace
    [chunk] Failed to transform file:/var/folders/_d/qw_ml1h95vd2d6kmf1krj3600000gp/T/temp20201030002053316/Sample.dita: The prefix "xsi" for attribute "xsi:noNamespaceSchemaLocation" associated with an element type "topic" is not bound.
[move-meta] Error on line 1 column 1397 of Sample.dita:
[move-meta]   SXXP0003: Error reported by XML parser: The prefix "xsi" for attribute
[move-meta]   "xsi:noNamespaceSchemaLocation" associated with an element type "topic" is not bound.
Error: Failed to run pipeline: Failed to transform document: org.xml.sax.SAXParseException; systemId: file:/var/folders/_d/qw_ml1h95vd2d6kmf1krj3600000gp/T/temp20201030002053316/Sample.dita; lineNumber: 1; columnNumber: 1397; The prefix "xsi" for attribute "xsi:noNamespaceSchemaLocation" associated with an element type "topic" is not bound.

## Environment

* DITA-OT version: 3.5.4
* Operating system and version: macOS
* How did you run DITA-OT? bash, see above
* Transformation type: HTML5

**Comment by takesson** [comment]
Actually, it seems to fail when chunk=to-content is set on topicref elements within the ditamap as well. The issue is not specific to setting chunk on the map root element.

**Comment by takesson** [comment]
The following patch avoids the failure.
```
diff --git a/src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java b/src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java
index bb4d209d5..36b5c9599 100644
--- a/src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java
+++ b/src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java
@@ -313,6 +313,8 @@ public abstract class AbstractChunkTopicParser extends AbstractXMLWriter {
         if (TOPIC_TOPIC.matches(cls) && resAtts.getValue(XMLNS_ATTRIBUTE + ":" + DITA_OT_NS_PREFIX) == null) {
             addOrSetAttribute(resAtts, XMLNS_ATTRIBUTE + ":" + DITA_OT_NS_PREFIX, DITA_OT_NS);
         }
+        // Declare the xsi namespace for schema based topics.
+        addOrSetAttribute(resAtts, "xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
         return resAtts;
     }
 

```

**Comment by easirois** [comment]
I have a client that is hitting the same issue with 3.5.2 with XHTML output type when they have mathml content in the source.   SXXP0003: Error reported by XML parser: The prefix "m" for element "m:math" is not bound.

**Comment by easirois** [comment]
I have implemented a pull request for this issue. https://github.com/dita-ot/dita-ot/pull/3684

1) Check to see if the attribute xsi:noNamespaceSchemaLocation exists, if so add xmlns:xsi namespace declaration
2) If content within a topic contains namespaced content, like MathML, then add the appropriate namespace declaration on the element.
