### ISSUE TITLE
map2hhcImpl.xsl contains incomplete code

### ISSUE THREAD

**Issue by Demosteneus** [dita-ot/dita-ot#3627]
Hi, 

There is an issue with the file **map2hhcImpl.xsl** from **dita-ot-develop\dita-ot-3.6.0-SNAPSHOT@23ce7fd\plugins\org.dita.htmlhelp\xsl\map2htmlhelp**

**sgprefix">DOTX</xsl:variable>**  should probably be:  **<xsl:variable name="msgprefix">DOTX</xsl:variable>**

![image](https://user-images.githubusercontent.com/68335318/98347097-3f1af500-2017-11eb-9a0b-64f46a9f9a77.png)

**Comment by raducoravu** [comment]
@robander seems to have broken it in this commit: https://github.com/dita-ot/dita-ot/commit/f88cc9be1b41450daf4b2c0cb648fbc10bdea000

**Comment by jelovirt** [comment]
@Demosteneus Removing line 33 should fix it. PRs are welcome if you're interested.
