### ISSUE TITLE
NullPointerException in JobMapper when referencing image on another disk drive.

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3635]
On Windows I have a DITA topic on the D:\ drive like:
D:\projects\samples\dita\flowers\topics\introduction.dita
and it references using an absolute href an image on the c:\ drive:
file:/C:/Users/my_user/Desktop/Snowdrop.jpg
Using the latest DITA OT sources I publish to HTML5:

      dita -i D:\projects\samples\dita\flowers\flowers.ditamap -f html5 -v

and get a NullPointerException reported:

      DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:364: java.lang.NullPointerException
	at org.dita.dost.ant.types.JobMapper.mapFileName(JobMapper.java:79)
	at org.apache.tools.ant.util.CompositeMapper.lambda$mapFileName$0(CompositeMapper.java:32)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)

**Comment by raducoravu** [comment]
The exception is very similar to the one here #2844 but as it stems from a different problem, I'm logging this issue separately.

**Comment by raducoravu** [comment]
I can no longer reproduce this problem with DITA OT 3.6.

**Comment by raducoravu** [comment]
It seems I can still reproduce the problem, the image which is referenced with an absolute reference needs to be placed on another drive than the original DITA Map.

**Comment by raducoravu** [comment]
Adding a sample which can be used to reproduce the NPE (at least on Windows):
[jobMapperNPE.zip](https://github.com/dita-ot/dita-ot/files/6115503/jobMapperNPE.zip)

**Comment by raducoravu** [comment]
Had two more people report this for distinct projects, the NullPointerException does not help them understand what the problem is.

**Comment by jlacour31** [comment]
I created a pull request that resolve this issue, if the paths have nothing in common, the method returns the left URI. Which for example in the case of CleanPreprocessModule.getBaseDir() is the original calculated baseDir.
