### ISSUE TITLE
Penetration Test Vulnerability found in the output generated from DITA OT, authored in Oxygen XML Editor

### ISSUE THREAD

**Issue by Roopgovind** [dita-ot/dita-ot#3637]
Hi,
We  generated output from DITA OT (1.0), authored in Oxygen XML Editor. When the testers did a Penetration test, they passed a script "<script>alert("HI")</script> " which should not be executed ideally, but the search is executing the same. We have and urgent fix for this. Please let me know the possible solution.

**Comment by raducoravu** [comment]
What specific output type do you obtain from DITA ? Is it plain HTML? Or is it Oxygen WebHelp Responsive output?
Plain HTML output obtained from DITA does not have any Javascript code included and it also does not have a search functionality.
If it's Oxygen WebHelp Responsive output you obtain maybe you can get in touch with "support@oxygenxml.com" and provide more details (Oxygen version for example).

**Comment by raducoravu** [comment]
@Roopgovind I'm closing this one, if you provide extra details it can be opened later on
