### ISSUE TITLE
New transformation fails with external plugin

### ISSUE THREAD

**Issue by jdwinfodesign** [dita-ot/dita-ot#3639]
## Expected Behavior
HTML5 transformation with font color red (simple test for new HTML5 transtype plugin).

## Actual Behavior
The proper path appears in config/plugins.xml, but the transformation fails with the following:
Transformation failed. C:\Users\jdwin\Documents\DITA-OT\dita-ot-3.5.4\plugins\org.dita.base\build_init.xml:22: 
taskdef class org.dita.dost.ant.InitializeProjectTask cannot be found

## Steps to Reproduce
1. Following the directions in in "The configuration.properties file" in the DITA-OT documentation (version 3.5.4), set up new plugin outside the DITA-OT
For example: plugindirs = plugins;demo;C:\\Users\\jdwin\\Documents\\jdwinfodesign\\jdw-demo-content\\plugins
2. Run integrator and new transformation (as a new DITA-OT transformation) in Oxygen (version 21 used).

[com.jdwinfodesign.html5.zip](https://github.com/dita-ot/dita-ot/files/5598583/com.jdwinfodesign.html5.zip)

## Copy of the error message, log file or stack trace
C:\Users\jdwin\Documents\jdwinfodesign\DITA-OT-instances\dita-ot-3.5.4\build.xml:19: The following error occurred while executing this line:
C:\Users\jdwin\Documents\jdwinfodesign\DITA-OT-instances\dita-ot-3.5.4\plugins\org.dita.base\build.xml:36: The following error occurred while executing this line:
C:\Users\jdwin\Documents\jdwinfodesign\DITA-OT-instances\dita-ot-3.5.4\plugins\org.dita.base\build_init.xml:22: taskdef class org.dita.dost.ant.InitializeProjectTask cannot be found
 using the classloader AntClassLoader[]

## Environment
* DITA-OT version: external DITA-OT 3.5.4
* Operating system and version: Windows 10
* Running in Oxygen 21 transformation scenario, i.e., "New OT transform"
* New transtype based on HTML5.

**Comment by raducoravu** [comment]
Can you integrate and run the transformation exclusively from the command line using the "dita" script?
If you can then maybe the problem is in Oxygen XML Editor. I remember I made a fix in Oxygen version 23 because previous versions did not properly look for the "configuration.properties" in the right folder.

**Comment by jdwinfodesign** [comment]
I ran it from the command line using the dita script and was successful.
