### ISSUE TITLE
Images not resolving properly in PDFs

### ISSUE THREAD

**Issue by shudson310** [dita-ot/dita-ot#3654]
## Expected Behavior
Images should appear in the PDF

## Actual Behavior
Images do not appear. The log has many entries like:

```
 [fop] [ERROR] Image not found. URI: file:/private/var/folders/cx/_fvptjtx2l3d9_hvsbwqr6mh0000gp/T/OxygenXMLTemp/ditaTemporaryOutputDir-1608586795964/t1/t2/t3/t4/t5/99e4452f31d74a93d59f9107490c7728e2310be8.png. (See position 95181:1162)
      [fop] [ERROR] Image not found. URI: file:/private/var/folders/cx/_fvptjtx2l3d9_hvsbwqr6mh0000gp/T/OxygenXMLTemp/ditaTemporaryOutputDir-1608586795964/t1/t2/t3/t4/t5/cb73cab4d61a29a9c631b48afda8652cfa4a479b.png. (See position 95192:1162)
      [fop] [ERROR] Image not found. URI: file:/private/var/folders/cx/_fvptjtx2l3d9_hvsbwqr6mh0000gp/T/OxygenXMLTemp/ditaTemporaryOutputDir-1608586795964/t1/t2/t3/t4/t5/e4416ea3622f39033e036be22058fcc84087d83a.png. (See position 95204:1162)
      [fop] [ERROR] Image not found. URI: file:/private/var/folders/cx/_fvptjtx2l3d9_hvsbwqr6mh0000gp/T/OxygenXMLTemp/ditaTemporaryOutputDir-1608586795964/t1/t2/t3/t4/t5/f90890eb1f627eaa3ed6b6a29e536698a6b3b98f.png. (No context info available)
[fop] [ERROR] Image not found. URI: file:/doc/source/d5e8e5eacc51c9a5deadc32cf9120abbe13c4316.png. (No context info available)
      [fop] [INFO] Rendered page #3.
```

## Possible Solution
 
It appears that the renderer is expecting the temp file name, but is looking in the source dir rather than the temp dir?

## Steps to Reproduce

1. Create a ditamap with topics that contain multiple images
    For example: 
    ```xml
    <image href="../image/newlanding-spotlight-icon.png" id="image_snk_cd5_1kb" placement="inline">
      <alt>Spotlight icon</alt>
    </image>
    ```
2. Run a PDF transform
3. Open the PDF in a PDF viewer

## Environment

* DITA-OT version: 3.6
* Operating system and version:
  macOS Catalina 10.15.7
* How did you run DITA-OT?
  tried Jenkins, oXygen, command line. None of the PDFs contained images.
* Transformation type:
  custom

**Comment by infotexture** [comment]
> * Transformation type:
>   custom

@shudson310 The default PDF transformation should resolve images as expected.

Can you confirm that this also works in your environment with the same source code? 

— If so, the issue is likely related to your custom transformation type.

**Comment by shudson310** [comment]
Basic PDF transform resolves images, so must be something in custom. TBH the custom plugin was written for 2.4.4, so will have to figure out what needs to change.

**Comment by shudson310** [comment]
Found the offending code in our custom plugin. Images are working as expected now.
