### ISSUE TITLE
DITA OT 3.6 - NullPointerException in custom ANT target using xslt pipeline

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3656]
We have a custom ANT build file with this target:

  <target name="whr-collect-indexterms.3x" description="Build list of index terms" if="dot3x">
    <property name="args.extract.indexterms.xsl" value="${webhelp.responsive.dir}/xsl/indexterms/extractIndexterms.xsl"/>
    <makeurl property="dita.temp.dir.url" file="${dita.temp.dir}"/>
  	<pipeline>
    <xslt basedir="${dita.temp.dir}" destdir="${dita.temp.dir}" style="${args.extract.indexterms.xsl}" reloadstylesheet="${webhelp.reload.stylesheet}">
      <ditafileset format="dita" processingRole="normal"/>
      <param name="TEMPFOLDER" expression="${dita.temp.dir.url}"/>
      <param name="OUT_EXT" expression="${out.ext}"/>
      <mapper type="regexp" from="^(.*?)$$" to="\1.indexterms"/>
      
      <xmlcatalog>
        <catalogpath path="${xsl.extensions.xml.catalog.file.path}"/>
        <catalogpath path="${dita.plugin.org.dita.base.dir}/catalog-dita.xml"/>
      </xmlcatalog>	
    </xslt>
  	</pipeline>   
    
  	<pipeline>
    <xslt in="${dita.temp.dir}/${user.input.file}" out="${output.dir}/index.xml" style="${webhelp.responsive.dir}/xsl/indexterms/collectIndexterms.xsl" classpathref="dost.class.path" reloadstylesheet="${webhelp.reload.stylesheet}">
      <param name="TEMPFOLDER" expression="${dita.temp.dir}"/>
      <param name="JOB_FILE" expression="${dita.temp.dir}/.job.xml"/>
      <param name="INDEXTERMS_PROPERTIES_URL" expression="${indexterms.properties.url}"/>
      <param name="WEBHELP_PARAMETERS_URL" expression="${webhelp.responsive.parameters.file.url}"/>
      
      
      <xmlcatalog>
        <catalogpath path="${xsl.extensions.xml.catalog.file.path}"/>
        <catalogpath path="${dita.plugin.org.dita.base.dir}/catalog-dita.xml"/>
      </xmlcatalog>	
    </xslt>
  	</pipeline>
    
  </target>

when the target is run I get this NullPointerException:

     Caused by: java.lang.NullPointerException
	at org.dita.dost.ant.ExtensibleAntInvoker.getJob(ExtensibleAntInvoker.java:328)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:173)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	... 22 more

Looking at that particular line of code:

            store = new StreamStore(job.tempDir, xmlUtils);

the "job" can only be null there. Probably you need to replace job.tempDir=>tempDir

**Comment by jelovirt** [comment]
You should have Job at this point in project reference. Do you have `<antcall>` that doesn't set `inheritRefs="true"`?

**Comment by raducoravu** [comment]
@jelovirt there is indeed an antcall to that specific target:

     <antcall target="whr-collect-indexterms.3x"/>

and indeed if I set inheritRefs to that ant call and to all others it seems to work, thanks for this.

**Comment by jelovirt** [comment]
AFAICT tne NPE will be fixed by #3657, but that will just fix the NPE. The correct fix is to change the plug-in code to inherit references on `antcall`.
