### ISSUE TITLE
Add schema caching when parsing RNG-based maps and topics

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3661]
If I have a DITA Map with 5 RNG-based topics referenced in it, the method `org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.loadDefaults()` is called by the pre-processing stage 5 times and the RNG schemas are loaded 5 times. To avoid this we need to cache the loaded RNG defaults obtained for the `topic.rng`and re-use them.
I propose passing the XML grammar pool on the `RelaxNGDefaultsComponent` constructor and having a grammar pool implementation which can cache also RNG defaults.
We already have something like this in Oxygen and use it when running "Validate and check for completeness" on RNG-based map and topics.

**Comment by raducoravu** [comment]
Adding a small project with RNG based map and a couple of RNG based topics.

[abc_0.zip](https://github.com/dita-ot/dita-ot/files/5757457/abc_0.zip)

**Comment by chrispitude** [comment]
We use RelaxNG grammars for our books. I tested a modified Oxygen-specific DITA-OT with this caching, and the runtime was **over twice as fast** to publish 90 books to PDF (from over two hours to under an hour).

**Comment by raducoravu** [comment]
This issue was fixed back in 2022 by the pull request linked above.
