### ISSUE TITLE
Changes to .job.xml file are sometimes not detected and handled

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3663]
## Expected Behavior
I have a DITA-OT plugin that excludes `<draftintro>` topics (unless `args.draft==true`). This exclusion is performed before `mapref` processing by doing the following three things:

1. Delete `<draftintro>` elements from the map
2. Delete `*_draftintro*.dita` files from `$tempdir`
3. Delete `*_draftintro*.dita` file entries from `$tempdir/.job.xml`

The expectation is that this effectively removes the `<draftintro>` topics from the transformation.

## Actual Behavior
In versions prior to 3.5, this works perfectly 100% of the time.

Starting with the 3.5 release and continuing through 3.6, this fails roughly 20% of the time as follows:

```
[topic-fragment] Failed to process XML filter: Failed to transform file:/tmp/temp20201231154916747/src/_draftintro_chrispy.dita: /tmp/temp20201231154916747/src/_draftintro_chrispy.dita (No such file or directory)
[topicpull] Recoverable error
[topicpull]   I/O error reported by XML parser processing
[topicpull]   file:/tmp/temp20201231154916747/src/_draftintro_chrispy.dita:
[topicpull]   /tmp/temp20201231154916747/src/_draftintro_chrispy.dita (No such file or directory)
[topicpull] Failed to transform document: I/O error reported by XML parser processing file:/tmp/temp20201231154916747/src/_draftintro_chrispy.dita: /tmp/temp20201231154916747/src/_draftintro_chrispy.dita (No such file or directory)
```

There seems to be some kind of race condition where the updated `.job.xml` file list is not considered (I think).

## Steps to Reproduce

1. Unarchive the attached testcase.
2. Edit `do.sh` and set `VER` to the DITA-OT version to use.
2. Run the `do.sh` script (bash script for linux).
3. Check for errors by running `grep Failed out*.out`.

[BUG.zip](https://github.com/dita-ot/dita-ot/files/5758355/BUG.zip)

## Environment
* DITA-OT version 3.5 and higher
* Operating system and version: Windows 10, running Ubuntu 18.04 via WSL
* Ran DITA-OT via: `dita` command
* Transformation type: `dita`

**Comment by chrispy-snps** [comment]
More detail on the plugin can be found here:

https://groups.google.com/g/dita-ot-users/c/u6sGODXRCrw/m/41E-i3l4AgAJ

**Comment by raducoravu** [comment]
Making changes directly to the .job.xml seems kind of fragile to me. Also it will not work with the new store-type=memory parameter because the .job.xml is no longer in the temporary files folder.
Maybe it would be better to have a custom Java ANT task which changes directly the internal org.dita.dost.util.Job object.
@jelovirt do you have other advice for this?

**Comment by chrispy-snps** [comment]
@raducoravu, it is terribly fragile and I dislike the approach immensely. But I could not find any other way to remove a topic from processing from a DITA-OT plugin.

@jelovirt  - from a high level, how can I write a plugin that suppresses bookmap `<draftintro>` topics, except when `args.draft` is set to `yes`? From a low level, details on my struggles can be found [here](https://groups.google.com/g/dita-ot-users/c/u6sGODXRCrw/m/41E-i3l4AgAJ).

**Comment by chrispy-snps** [comment]
I'm closing this issue because we've worked around the problem by using profiling conditions to hide `<draftintro>` elements. It's hacky, but it works reliably.
