### ISSUE TITLE
Small change in message

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3669]
Sometimes the DITA OT issues this message:

     DOTX037W][WARN]: No title found for this document; using "***" in XHTML title bar. 

maybe we should replace XHTML=>HTML as the message is reported also for the HTML5 output.

**Comment by infotexture** [comment]
@raducoravu Good catch, I'll send a pull request to fix this.

While we're at it, I'll also clarify the "title bar" reference, as the HTML document itself doesn't have a "bar", only the browser that displays it does. 

This is explained in the [corresponding entry of the messages topic](https://www.dita-ot.org/dev/topics/error-messages.html#msgs__DOTX037W) in the docs, but that info is not available in logs, so makes sense to fix it in the CLI message.
