### ISSUE TITLE
Dublin core headers are still issued for XHTML type outputs

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3675]
As a continuation to this pull request #3595 if I search for "DC.Rights.Owner" in all plugins bundled with DITA OT, I can still find it in the XHTML and the light weight DITA plugins.

**Comment by jelovirt** [comment]
#3595 only changed HTML5 plugin. If DC is removed from XHTML or MHTML plugins, those will be handled as separate issues and should be raised as enhancement requests for those plugins.

**Comment by raducoravu** [comment]
That extra plugin which adds DC headers for the HTML5 plugin is not included by default with the DITA-OT, meaning that out of the box there is a small inconsistency in how the headers get generated with HTML5 versus XHTML outputs. But I do not care much about those headers anyway.
