### ISSUE TITLE
Transformation fails with "URI has a fragment component" when calling a <mapref> with a <ditavalref>

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3680]
## Expected Behavior
I am trying to use "wrapper maps" to instantiate two different flavors of a shared map:

```
<!-- bookA.ditamap: -->
<map>
  <ditavalref href="shared/A.ditaval"/>
  <mapref href="shared/shared.ditamap"/>
</map>

<!-- bookB.ditamap: -->
<map>
  <ditavalref href="shared/B.ditaval"/>
  <mapref href="shared/shared.ditamap"/>
</map>
```

When I transform the bookA and bookB maps, I expect to get the content of `shared.ditamap`, with the A and B DITAVAL conditions applied respectively.

## Actual Behavior
Transformation fails with:

```
$ dita --input bookA.ditamap --format dita --output A
Reload stale job configuration reference
Error: java.lang.IllegalArgumentException: URI has a fragment component
```

However, if I filter `shared.ditamap` using a command line option instead of a wrapper map, then it works:

```
$ dita --input shared/shared.ditamap --format dita --filter shared/A.ditaval --output A
[normalize] file:/mnt/c/Users/chrispy/Documents/DITA/bugs/shared_maps/A/keys.ditamap
[normalize] file:/mnt/c/Users/chrispy/Documents/DITA/bugs/shared_maps/A/common/common_chapter.dita
[normalize] file:/mnt/c/Users/chrispy/Documents/DITA/bugs/shared_maps/A/shared.ditamap
[normalize] file:/mnt/c/Users/chrispy/Documents/DITA/bugs/shared_maps/A/A/chapter_for_book_a.dita
$
```

## Steps to Reproduce

1. Unarchive the attached testcase.
2. Run the two commands shown above.

[shared_maps.zip](https://github.com/dita-ot/dita-ot/files/5816858/shared_maps.zip)

## Environment

* DITA-OT version: 3.6.0
* Operating system and version: Ubuntu 18.04 LTS
* Ran DITA-OT via: `dita` command
* Transformation type: `dita`

**Comment by DaveGibbons** [comment]
I'm getting this same error when I have a topicref in a map and the href attribute includes a ? argument, like 

1.html?query=2 

I've tried it without the = sign, and that doesn't make a difference.

**Comment by raducoravu** [comment]
This issue seems to stem from two problems:

1) The method org.dita.dost.module.BranchFilterModule.filterTopics(Element, List<FilterUtils>) calls "job.getStore().transform" with an URI which has an anchor component like:

    file:/Users/raducoravu/Downloads/shared_maps/temp/html5/oxygen_dita_temp/shared/common/common_chapter.dita#topic_rrt_vkb_34b

2) The method org.dita.dost.store.AbstractStore.transform(URI, List<XMLFilter>) does not expect that the URI passed as a parameter has an anchor component, it appends a ".temp" to it resulting in:

         file:/Users/raducoravu/Downloads/shared_maps/temp/html5/oxygen_dita_temp/shared/common/common_chapter.dita#topic_rrt_vkb_34b.temp

and then attempts to create a file for it.

**Comment by raducoravu** [comment]
A quick fix could be to suppress the anchor part in "org.dita.dost.module.BranchFilterModule.filterTopics(Element, List<FilterUtils>)":

             String href = topicref.getAttribute(ATTRIBUTE_NAME_HREF);
        if(href != null && href.contains("#")) {
        	href = href.substring(0, href.indexOf("#"));
        }

But (2) in my opinion should also remove anchor and query parts from the URI before adding that ".temp" suffix to it.

**Comment by chrispy-snps** [comment]
@raducoravu, thanks for looking into this!

Originally I thought this was related specifically to the wrapper map structure. But given your findings, I have confirmed that _any_ use of branch filtering applied to a within-file nested subtopic results in this error.

This means that the problem is more serious than I originally thought.

Our writers use within-file subtopics (instead of the `@chunk` attribute) to control how content is chunked and presented in online help. We had planned to start using branch filtering in the next few weeks. Unfortunately this bug prevents us from doing so.

**Comment by raducoravu** [comment]
@chrispy-snps what I can try to do is to patch things on our side in the DITA OT distribution we ship and I will send you an email once the fix is in place in our nightly builds and you can test it on your side.

**Comment by chrispy-snps** [comment]
@raducoravu - absolutely, I am happy to test!

**Comment by chrispy-snps** [comment]
Thanks @jelovirt !

**Comment by chrispy-snps** [comment]
Thanks @raducoravu , @jelovirt !
