### ISSUE TITLE
Allow a PDF deliverable to specify its output file name

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3682]
## Description
When a shared map is published to PDF in multiple profiling conditions, then each output PDF file must have a different name according to its condition.

`<deliverable>` elements allow the output _directory_ to be specified (great for HTML5!), but not the output _basename_ (needed for PDF).

As a result, the output PDF files derive their basename from the input map, resulting in duplicate PDF file names:

![3682_1](https://user-images.githubusercontent.com/50950969/152381770-f437b3ca-a35e-45d0-ab87-7a29cdd2ac50.svg)

## Possible Solution
One approach would be to support `<param>` directly inside `<deliverable>`:

![3682_2](https://user-images.githubusercontent.com/50950969/152381808-1cf78e2a-5e49-4e6b-8079-9aa8f0d35def.svg)

If this is too philosophically different from what `<deliverable>` was intended to contain, another approach is to allow `<param>` inside an `idref`'ed `<publication>` inside the `<deliverable>`

![3682_3](https://user-images.githubusercontent.com/50950969/152381817-818c49d1-b4fa-4a94-af33-0cb35c42d029.svg)

This second approach is very RelaxNG-like in its method of applying overrides to a refererence, which is quite nice!

Some workarounds (and their deficiencies) are:

* Uniquify the PDF `<publication>` definition.
  * In our case, we would need to uniquify our `<publication>` definitions by the hundreds, which is not ideal because then we must update _all_ of them whenever our PDF transformation changes.
* Rename the PDF files using a post-processing script.
  * Isn't the goal of DITA-OT project files to be able to replicate -- in a structured way -- what is normally performed on the `dita` command line (where the basename is normally specified), without the need for post-processing scripts?
  * If all PDFs go in the same directory, then they collide with themselves during full publication before such a script could run.
* Place the PDF files in different output directories.
  * This avoids file collisions, but it does not solve the duplicate file name issue (which would confuse our customers).

## Potential Alternatives
A new basename-specific element (`basename`?) could be added to `<deliverable>`, but a `<param>`-based approach would be more generally useful for deliverable-specific tweaks to publishing.

## Additional Context
To reproduce, you can try using the following project file (copied to `<DITA-OT>/docsrc/samples/project-files/pdf-test.xml`, perhaps):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://www.dita-ot.org/rng/project.rnc" type="application/relax-ng-compact-syntax"?>
<project xmlns="https://www.dita-ot.org/project">

  <!-- single map to be published in two flavors -->
  <context id="context-ug1" name="User Guide 1">
    <input href="../../userguide-book.ditamap"/>
    <!-- pretend we have DITAVAL 1 applied here -->
  </context>

  <context id="context-ug2" name="User Guide 2">
    <input href="../../userguide-book.ditamap"/>
    <!-- pretend we have DITAVAL 2 applied here -->
  </context>


  <!-- single shared publication definition -->
  <publication id="pub-pdf2" transtype="pdf2">
    <param name="args.chapter.layout" value="BASIC"/>
    <param name="args.gen.task.lbl" value="YES"/>
    <param name="include.rellinks" value="friend"/>
    <param name="processing-mode" value="strict"/>
  </publication>


  <!-- publish book flavors with two different output base names -->
  <deliverable id="del-pdf-ug1">
    <context idref="context-ug1"/>
    <output href="."/>
    <publication idref="pub-pdf2">
      <param name="outputFile.base" value="userguide1"/>
    </publication>
  </deliverable>

  <deliverable id="del-pdf-ug2">
    <context idref="context-ug2"/>
    <output href="."/>
    <publication idref="pub-pdf2">
      <param name="outputFile.base" value="userguide2"/>
    </publication>
  </deliverable>

</project>
```

**Comment by raducoravu** [comment]
As a possible workaround how about if you have a seed DITA OT project file from which you generate the final DITA OT project file used for publishing using XSLT? Your XSLT could for example expand in place the publication idrefs adding to them both parameters defined in the referenced publication and the the extra parameters.

**Comment by chrispy-snps** [comment]
@raducoravu - this is an interesting idea, thank you!

If I can figure out how to incorporate such a translation XSLT into Oxygen XML Author (such that the original project file would be in the Master files list, but the translation would be performed after the writer chooses a deliverable to transform), then I will do it.

**Comment by georgebina** [comment]
Hi Chris,

I do not think it is a good idea to push multiple DITA-OT outputs to the same folder, the transformations may generate the same files but with different content and thus you may not get what you expect. Also, the DITA-OT project files cannot make assumptions about the output of a specific transformation, it may be one file, it may be a set of file, maybe in the output folder or maybe in some subfolders. 

Instead of something like:

```
  <!-- publish book flavors with two different output base names -->
  <deliverable id="del-pdf-ug1">
    <context idref="context-ug1"/>
    <output href="."/>
    <publication idref="pub-pdf2">
      <param name="outputFile.base" value="userguide1"/>
    </publication>
  </deliverable>

  <deliverable id="del-pdf-ug2">
    <context idref="context-ug2"/>
    <output href="."/>
    <publication idref="pub-pdf2">
      <param name="outputFile.base" value="userguide2"/>
    </publication>
  </deliverable>
```
you have now the possibility of using:
```
  <!-- publish book flavors with two different output base names -->
  <deliverable id="del-pdf-ug1">
    <context idref="context-ug1"/>
    <output href="userguide1"/>
    <publication idref="pub-pdf2"/>
  </deliverable>

  <deliverable id="del-pdf-ug2">
    <context idref="context-ug2"/>
    <output href="userguide2"/>
    <publication idref="pub-pdf2"/>
  </deliverable>
```

And then, you will most probably get for this particular transformation:
`userguide1/userguide-book.pdf`
`userguide2/userguide-book.pdf`
A further script can just put all these PDFs in a folder and rename them based on the parent of some other convention that you want.

**Comment by georgebina** [comment]
Now, the possibility to add `param` entries inside `<publication idref="..">` to overwrite or add to existing parameters looks like a nice to have feature for the DITA-OT project files. 
It is similar to how one can overwrite or extend patterns in Relax NG schemas. When you include a schema, inside the `include` element you may place additional pattern definitions that will overwrite or extend (if the `combine` attribute  is used) the ones from the included schema (see [Replacing definitions](https://relaxng.org/tutorial-20011203.html#IDAVEZR)).

**Comment by chrispy-snps** [comment]
@georgebina - I'm glad you like the idea of per-deliverable parameters. Indeed, it's similar to extending RelaxNG, XSLT, etc. - very DITA-OT-like in concept!

I appreciate your concern about not wanting to overwrite deliverables. But while HTML5 deliverables must be unique by **directory** name, PDF files need only be unique by **file name**. Our output structure is as follows:

```
pdf/book1.pdf
pdf/book2.pdf
book1/...HTML5 help...
book2/...HTML5 help...
```

so we will have no collisions.

**Comment by chrispy-snps** [comment]
@georgebina - I started some additional discussion here:

[DITA-OT Users: Using DITA-OT project files for conditional books](https://groups.google.com/g/dita-ot-users/c/b0QM2rK2kVk)

although given our current discussion, the `<param>` overlay is probably the highest value-to-effort option.

**Comment by chrispitude** [comment]
@georgebina - Given that you like the idea of including publication-specific `<param>` entries inside `<publication idref="..">` elements, how can we make that happen? :)
