### ISSUE TITLE
PDF2 custom font mappings are not respected anymore

### ISSUE THREAD

**Issue by skulle** [dita-ot/dita-ot#3688]
## Expected Behavior
After upgrading from dita-ot 3.3.3 to 3.6 the `font-mappings.xml` from a custom pdf plugin is not used anymore. All generated pdfs use Tahoma now instead of Source Sans Pro. 

## Possible Solution
Setting the XsltTransformers' URIResolver in the PDF2 `com.idiominc.ws.opentopic.fo.i18n.PreprocessorTask.java` file like below solved the problem for me.

```
             if (style != null) {
                 log("Loading stylesheet " + style, Project.MSG_INFO);
                 final XsltExecutable compile = xmlUtils.getProcessor().newXsltCompiler().compile(job.getStore().getSource(style));
                 final XsltTransformer t = compile.load();
                 t.setURIResolver(xmlcatalog);
                 t.setSource(new DOMSource(document));
                 t.setDestination(job.getStore().getDestination(output));
                 t.transform();
```
## Environment
store-type=file
parallel=true

* DITA-OT version: 3.6
* Operating system and version:  Windows 10 1909
* How did you run DITA-OT? ant-launcher
* Transformation type: custom pdf extending the pdf2 plugin

**Comment by raducoravu** [comment]
Looks like a regression from when the store-type memory feature was added:
https://github.com/dita-ot/dita-ot/commit/b402e2f96c9ede0d13493e6914b75bdc2b0e76ab

probably a better fix would be to set to the transformer a combination between its base URI resolver and the extra URI resolver necessary at this stage in order for the customization font mappings file to be overridden.

**Comment by skulle** [comment]
Already a bit late, but thanks for fixing this so quickly
