### ISSUE TITLE
In DITA-OT project files, apply both <context> and <publication> DITAVAL filtering

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3690]
## Expected Behavior

(This is a more educated follow-up to #3474.)

For DITA-OT project files, if a `<context>` applies a DITAVAL and a `<publication>` applies a DITAVAL, then a `<deliverable>` using both of them should apply both DITAVAL files:

![3690_1](https://user-images.githubusercontent.com/50950969/152367300-f7a0d755-6414-437b-833f-1df573cd0998.svg)

## Actual Behavior
The `<context>` DITAVAL is applied but the `<deliverable>` DITAVAL is discarded.

If the `<context>` DITAVAL is removed, then the `<deliverable>` DITAVAL is applied as expected.

## Possible Solution
Both `<context>` and `<publication>` DITAVAL files should be applied. The need for this is demonstrated by replacing the `<context>` and `<publication>` definitions above with their respective DITAVAL files:

![3690_2](https://user-images.githubusercontent.com/50950969/152367787-dcdedff1-f64d-4ea1-81c7-b71360b959c9.svg)

In this example, the `<context>` DITAVAL is filtering on `@product`, while the `<publication>` DITAVAL is filtering on `@audience` (and applying `@rev` highlighting). These filtering aspects are orthogonal.

## Steps to Reproduce
In the attached testcase:

[dita_project_file.zip](https://github.com/dita-ot/dita-ot/files/5920276/dita_project_file.zip)

run the following command:

`dita --project=books.xml --deliverable="del-pdf-review-prodA_ug" --verbose`

then note in the output log that the publication `flag_review.ditaval` DITAVAL is not applied.

## Environment

* DITA-OT version: 3.5.4
* Operating system and version: Ubuntu Linux 18.04 LTS
* Ran via `dita` command
* Transformation type: PDF

**Comment by raducoravu** [comment]
As a possible workaround how about if you have a seed DITA OT project file from which you generate the final DITA OT project file used for publishing using XSLT? Your XSLT could for example expand in the deliverable the publication idrefs and the context idrefs, adding to the context element extra ditaval filter elements for each args.filter parameter found in the publication element.

**Comment by chrispy-snps** [comment]
@raducoravu - this is an interesting idea, thank you!

If I can figure out how to incorporate such a translation XSLT into Oxygen XML Author (such that the original project file would be in the Master files list, but the translation would be performed after the writer chooses a deliverable to transform), then I will do it.

**Comment by raducoravu** [comment]
@chrispy-snps I replied on the DITA Users list, the Oxygen "Publish DITA-OT Project" transformation scenarios are based on an ANT build file which runs the DITA OT "dita" executable, a custom ANT build file could apply the XSLT on the original DITA OT project file and then run the DITA OT command line on the newly created DITA OT project (you could create it in the same folder with the original project file so that all relative paths still resolve), then maybe at the end remove the temporary DITA OT project file.
