### ISSUE TITLE
Two-level keyrefs (keyref -> keyref -> keydef) no longer resolve properly.

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3694]
## Expected Behavior
If I define a key in a shared keys file:

```
    <topicgroup keyscope="B">
        <keydef keys="Product">
            <topicmeta>
                <keywords>
                    <keyword>Product B</keyword>
                </keywords>
            </topicmeta>
        </keydef>
    </topicgroup>
```

then choose one of those values in my bookmap:

`<keydef keys="Product" keyref="B.Product"/>`

then the value should be resolved properly, [as described here](https://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/example-keydef-with-keyref.html).

## Actual Behavior
This worked in DITA-OT 3.5.4, but it stopped working in DITA-OT 3.6; transformation now fails with the message shown below.

## Steps to Reproduce
Extract the following testcase:

[oxygen_two_level_keyref.zip](https://github.com/dita-ot/dita-ot/files/5946890/oxygen_two_level_keyref.zip)

then run the following command:

`dita -i OPENME2_bookB.ditamap -f html5 --verbose`

## Copy of the error message, log file or stack trace
```
$ ~/dita-ot-3.6/bin/dita -i OPENME2_bookB.ditamap -f html5 --verbose
...
keyref:
   [keyref] Reading file:/tmp/temp20210208161507271/OPENME2_bookB.ditamap
Error: java.lang.NullPointerException
$
```

## Environment
* DITA-OT version: 3.6
* Operating system and version: Ubuntu 18.04 LTS running via WSL within Windows 10
* How did you run DITA-OT? `dita` command
* Transformation type: HTML5

**Comment by raducoravu** [comment]
Attaching the NullPointerException stack trace:

    /Users/.../dita-ot-3.6/plugins/org.dita.base/build_preprocess.xml:229: java.lang.NullPointerException: Cannot invoke "net.sf.saxon.s9api.XdmNode.select(net.sf.saxon.s9api.streams.Step)" because "resMeta" is null
	at org.dita.dost.reader.KeyrefReader.mergeMetadata(KeyrefReader.java:429)
	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:340)
	at org.dita.dost.reader.KeyrefReader.resolveIntermediate(KeyrefReader.java:311)
	at org.dita.dost.reader.KeyrefReader.read(KeyrefReader.java:133)
	at org.dita.dost.module.KeyrefModule.execute(KeyrefModule.java:116)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:189)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)

**Comment by chrispy-snps** [comment]
Thanks @raducoravu , @jelovirt !
