### ISSUE TITLE
Make it possible to add Saxon features in pipeline + XSLT task

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#3713]
## Description
Recent DITA-OT customization after `preprocess` forces developers to use XSLT + pipeline elements because many of the files that DITA-OT generated in temporary folder or properties are now obsolete. 

[https://www.dita-ot.org/dev/topics/plugin-coding-conventions.html](https://www.dita-ot.org/dev/topics/plugin-coding-conventions.html)

> Use custom <pipeline> elements
> In Ant scripts, use the XSLT module from DITA-OT instead of Ant’s built-in <xslt> or <style> tasks.
> 
> The XSLT module allows access to DITA-OT features like using the job configuration to select files in the temporary folder based on file metadata and custom XSLT extension functions.
> 

    <pipeline>
      <xslt style="${dita.plugin.example.dir}/custom.xsl"
            destdir="${dita.output.dir}">
        <ditafileset format="dita" />
      </xslt>
    </pipeline>

However this element combination does not allow to add Saxon feature settings via `factory` element inside `xslt` element.

        <factory name="net.sf.saxon.TransformerFactoryImpl">
            <attribute name="http://saxon.sf.net/feature/timing" value="true"/>
            <attribute name="http://saxon.sf.net/feature/suppressXsltNamespaceCheck" value="true"/>
            <attribute name="http://saxon.sf.net/feature/enableAssertions" value="true"/>
            <attribute name="http://saxon.sf.net/feature/traceListenerClass" value="net.sf.saxon.trace.XSLTTraceListener"/>
        </factory>

Using Saxon feature setting is very important to debug XSLT stylesheets for stylesheet developers. 
As a result I want to submit a request to allow `factory` element in `xslt` element.

## Possible Solution

None! As described above, using raw `xslt` task is not possible due to DITA-OT generated files in temporary folder or properties that exist in older version are now removed.

[https://www.dita-ot.org/3.5/topics/migrating-to-3.5.html](https://www.dita-ot.org/3.5/topics/migrating-to-3.5.html)

> 9.2.	Legacy constructs removed
> DITA-OT 3.5 no longer includes the following legacy properties, list files, and targets, which were deprecated in previous releases. These constructs were no longer used in recent releases, and have now been removed entirely.
> 

## Potential Alternatives
None.

## Additional Context
None.

**Comment by ToshihikoMakita** [comment]
One more request: Enable  `force='yes'` parameter that exists in original ANT XSLT task.

> Engine name: DITA-OT
> Severity: fatal
> Description: Transformation failed. D:\DITA-OT\plugins\com.antennahouse.wh.index\add-build.xml:19: xslt doesn't support the "force" attribute
>

**Comment by jelovirt** [comment]
Based on my initial investigation, this may be something we cannot support. For reference see [Configuration using s9api](https://www.saxonica.com/html/documentation10/configuration/config-interfaces/s9api-config.html).

The `Processor` object in DITA-OT is shared between modules and we use the same instance for all transformations in a transtype. This means a single XSLT pipeline module would modify the shared configuration and might end up breaking other modules. We cannot simply create a new `Processor` for each XSLT pipeline module, because it would break in-memory store that relies on using the same `Processor` instance.

**Comment by ToshihikoMakita** [comment]
Thank you for your investigation.
I understood the reasons.
