### ISSUE TITLE
PDF2 build breakes due to an invalid xref's URI

### ISSUE THREAD

**Issue by skulle** [dita-ot/dita-ot#3718]
Not sure if this is to be treated as a bug, an improvment or not at all, but in dita-3.3.3 one could generate a pdf2 document which contained an xref with an invalid URI, e.g.

`<xref format="pdf" href="file://ccm/temp/diff.pdf" scope="external">file</xref>`

The URI misses a 3 slash so that the authority component would be empty, instead it is //ccm/ which was not intended. It should have beed file:///ccm/temp/diff.pdf.

However, dita-3.6.1. aborts the build with an exception:
```
BUILD FAILED
C:\bin\dita-ot-3.6.1\plugins\org.dita.base\build.xml:29: The following error occurred while executing this line:
C:\bin\dita-ot-3.6.1\plugins\org.dita.base\build_preprocess2.xml:171: java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(File.java:423)
	at org.dita.dost.writer.ValidationFilter.validateReference(ValidationFilter.java:201)
	at org.dita.dost.writer.ValidationFilter.startElement(ValidationFilter.java:96)
	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:121)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)

```
## Expected Behavior
Depending on the processing-mode, e.g. lax, a PDF2 document is generated

## Actual Behavior
Build aborts with an exception

## Steps to Reproduce
Build the attached document

## Copy of the error message, log file or stack trace
```
BUILD FAILED
C:\bin\dita-ot-3.6.1\plugins\org.dita.base\build.xml:29: The following error occurred while executing this line:
C:\bin\dita-ot-3.6.1\plugins\org.dita.base\build_preprocess2.xml:171: java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(File.java:423)
	at org.dita.dost.writer.ValidationFilter.validateReference(ValidationFilter.java:201)
	at org.dita.dost.writer.ValidationFilter.startElement(ValidationFilter.java:96)
	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:121)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
```

## Environment

* DITA-OT version: 3.6.1
* Operating system and version: Windows
* How did you run DITA-OT? ant-launcher
* Transformation type: PDF
[authoring.zip](https://github.com/dita-ot/dita-ot/files/6181752/authoring.zip)

**Comment by jelovirt** [comment]
Since file URI is allowed to contain an authority, we should not try to fix `file:///ccm/temp/diff.pdf` into `file://ccm/temp/diff.pdf`. Instead, the external scope should not try to validate the URI using `java.io.File`.

**Comment by skulle** [comment]
Not sure if I understand you correctly. You still would want run a verification for an external file URI but not just with `java.io.File`, or do you would skip the verification step at all?

**Comment by jelovirt** [comment]
Can be cherry picked to 4.1.2
