### ISSUE TITLE
ValidationFilter stage breaks with unexpected error for invalid URL

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3730]
I have this link in a DITA topic:

    <xref href="http://www,oxygenxml.com" format="html" scope="external"/>

notice there is a comma in the href attribute value instead of a dot.
I publish to HTML5, the publishing breaks with:

       D:\projects\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:96: java.lang.RuntimeException: Expected scheme-specific part at index 5: http:
	at org.dita.dost.util.URLUtils.setFragment(URLUtils.java:559)
	at org.dita.dost.util.URLUtils.stripFragment(URLUtils.java:541)
	at org.dita.dost.writer.ValidationFilter.validateReference(ValidationFilter.java:199)
	at org.dita.dost.writer.ValidationFilter.startElement(ValidationFilter.java:96)
	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:121)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(Unknown Source)
	at org.dita.dost.writer.DebugFilter.startElement(DebugFilter.java:78)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)

The URL is not really invalid according to the URI standard, so you can create an URI over it:

     new URI("http://www,oxygenxml.com")

**Comment by raducoravu** [comment]
So there are two problems, that there is a runtime exception thrown and that the exception details do not indicate in which file the problem occurred.

**Comment by chrispitude** [comment]
We are hitting this issue as well. It makes debugging difficult.

**Comment by raducoravu** [comment]
+1 another one of our users encountered the same problem.
For Oxygen 24 we decided to patch the DITA OT code and skip validation of all links which have scope=external.

**Comment by raducoravu** [comment]
👍 one more problem which may appear quite often, the same error is triggered for **mailto:** links like this:

      <xref href="mailto:abc@sync.ro" format="html" scope="external">

@jelovirt maybe either the validation could be skipped altogether for scope=external links or have some special cases for URL protocols which are not implemented in Java but exist in the wild, schemes like:

    "aaa://",
    "aaas://",
    "acap://",
    "cap://",
    "cid:",
    "crid://",
    "data:",
    "dav:",
    "dict://",
    "dns://",
    "fax:",
    "ftp://",
    "go://",
    "gopher://",
    "h323:",
    "icap://",
    "im:",
    "imap://",
    "info:",
    "ipp://",
    "iris:",
    "iris.beep:",
    "iris.xpc:",
    "iris.xpcs:",
    "iris.lwz:",
    "javascript:",
    "ldap://",
    "mailto:",
    "mid:",
    "modem:",
    "msrp://",
    "msrps://",
    "mtqp://"

**Comment by xephon2** [comment]
@raducoravu, how about `tel:`?

**Comment by raducoravu** [comment]
@xephon2 interesting, I never knew about this one.
