### ISSUE TITLE
Introduce new <ditafileset> member

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#3748]
## Description
Current DITA-OT documentation refers about <ditafileset> features and it is described in the following URL:
https://www.dita-ot.org/dev/topics/plugin-coding-conventions.html#ariaid-title1
There are three `<ditafileset>` examples listed. The first and third are useful for DITA plug-in development. However `<ditafileset format="ditamap"/>` selects all DITA maps in the temporary directory. This is useless because most of plug-in developers need **only main ditamap** to get information after preprocess.

## Possible Solution
Add `<ditafileset format="ditamap-main"/>` to select the main ditamap file.

## Potential Alternatives
Probably following may work.
```xml
<fileset dir="${dita.temp.dir}">
  <includes name="${dita.input.filename}.ditamap"/>
</fileset>
```

## Additional Context
This is only my idea. This should be discussed in DITA-OT developers.

**Comment by jelovirt** [comment]
You can already do this with

’’’
<ditafileset format="ditamap" input="true"/>
’’’

**Comment by jelovirt** [comment]
@infotexture Could we add information about the undocuments attributes to https://www.dita-ot.org/dev/topics/plugin-coding-conventions.html?

* `@input = true | false` — `true` for start document, `false` for others; defaults to `false`
* `@inputResource = true | false` — `true` for resources files (`--resource` in CLI), `false` for others; defaults to `false`
* `@conref = true | false` —  `true` for documents that use conref, `false` for others; defaults to `false`
* `@processingRole = resource-only | normal` — `resource-only` for documents references as resource only, `normal` for normal references; defaults to any.
