### ISSUE TITLE
Reconsider how force-unique works with references to separate topics inside the same file

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3750]
I'm attaching a DITA Map which references a glossary.ditamap with the following content:

    <map>
        <glossref href="concepts/glossary.dita#flowers.genus" print="yes" keys="genus"/>
        <glossref href="concepts/glossary.dita#flowers.pollination" print="yes" keys="pollination"/>
      ....
    </map>

so we have multiple references to multiple glossentry elements located in the same file.
If I publish to PDF setting the "force-unique=true" parameter the PDF output will contain the glossary entries multiplied a number if times because the ForceUniqueFilter adds copy-to attributes to each reference.

I think the ForceUniqueFilter should not consider that references like "glossary.dita#flowers.genus" or "glossary.dita#flowers.pollination" are identical and thus avoid setting extra copy-to attributes on them.

[force-unique-flowers.zip](https://github.com/dita-ot/dita-ot/files/6458775/force-unique-flowers.zip)

**Comment by chrispy-snps** [comment]
This issue also affects us.

**Comment by chrispy-snps** [comment]
This issue also affects us. We use nested topics, and subtopic references are required to define `@keys` values for the subtopics:

```
    <topicref href="topic.dita" keys="topic">
      <topicref href="topic.dita#subtopic1" keys="subtopic1"/>
      <topicref href="topic.dita#subtopic2" keys="subtopic2"/>
    </topicref>
```

However, when setting `force-unique=true`, we get duplicate topic files in our HTML5 output:

```
$ ls -1 out/topic*
out/topic.html
out/topic_2.html
out/topic_3.html
```

This issue occurs with both glossterms in a glossgroup file (as in @raducoravu 's example) and with nested topics in a topic file. Here is a testcase for nested topics:

[force-unique-topic.zip](https://github.com/dita-ot/dita-ot/files/7016919/force-unique-topic.zip)

**Comment by kirkilj** [comment]
This may or may not be related, but we've been seeing similar behavior when generating PDF via XSL-FO and FOP using only fragment links to rows within a sibling nested topic. Linking to the enclosing topic or table, instead of the row, works fine.

Running the same content using fragment links to individual rows through PDF via Oxygen's XHTML and CSS generates working links just fine.

**Comment by chrispy-snps** [comment]
This issue occurs during the `copy-to` preprocessing step, inside `CopyToModule`:

```
    <pipeline message="Resolve copy-to." taskname="copy-to">
      <module class="org.dita.dost.module.CopyToModule">
        <param name="force-unique" value="${force-unique}" if:set="force-unique"/>
      </module>
    </pipeline>
```

When `force-unique == false`, the output of this step is as follows:

```
<map>
  <title>My Map</title>
  <topicref href="topic.dita">
    <topicref href="topic.dita#concepts"/>
    <topicref href="topic.dita#configuration">
      <topicref href="topic.dita#option1"/>
      <topicref href="topic.dita#option2"/>
    </topicref>
    <topicref href="topic.dita#limitations"/>
  </topicref>
</map>
```

When `force-unique == true`, the output of this step is as follows:

```
<map>
  <title>My Map</title>
  <topicref href="topic.dita">
    <topicref href="topic.dita#concepts" copy-to="topic_2.dita#concepts"/>
    <topicref href="topic.dita#configuration" copy-to="topic_3.dita#configuration">
      <topicref href="topic.dita#option1" copy-to="topic_4.dita#option1"/>
      <topicref href="topic.dita#option2" copy-to="topic_5.dita#option2"/>
    </topicref>
    <topicref href="topic.dita#limitations" copy-to="topic_6.dita#limitations"/>
  </topicref>
</map>
```

Here's the testcase I used for this (similar to @raducoravu 's testcase, but with a topic file instead of a glossary file):

[force_unique_duplicated_topics.zip](https://github.com/dita-ot/dita-ot/files/7981748/force_unique_duplicated_topics.zip)

**Comment by raducoravu** [comment]
We'll have a patch for this in the org.dita.dost.writer.ForceUniqueFilter with the DITA OT 3.7 bundled with Oxygen 24.1 which we'll release this March.
Not sure how perfect the patch is but I'm attaching also the patched Java source in case somebody finds it useful for anything.
[ForceUniqueFilter.java.zip](https://github.com/dita-ot/dita-ot/files/7984063/ForceUniqueFilter.java.zip)

**Comment by chrispy-snps** [comment]
@raducoravu - this patch is good progress!

In the force_unique_duplicated_topics.zip testcase above, here is the output from the `copy-to` preprocessing step:

```
<map>
  <title>My Map</title>
  <topicref href="topic.dita">
    <topicref href="topic.dita#concepts" copy-to="topic.dita#concepts"/>
    <topicref href="topic.dita#configuration" copy-to="topic.dita#configuration">
      <topicref href="topic.dita#option1" copy-to="topic_4.dita#option1"/>  <!-- duplicated -->
      <topicref href="topic.dita#option2" copy-to="topic_5.dita#option2"/>  <!-- duplicated -->
    </topicref>
    <topicref href="topic.dita#limitations" copy-to="topic.dita#limitations"/>
  </topicref>
</map>
```

The fix resolves the duplicates for the direct child nested topics, but doesn't quite reach into their descendants too.

I learned how to integrate your patch into a DITA-OT development tree and build/test with it today, so I am happy to test additional patch updates if you like.

**Comment by raducoravu** [comment]
@chrispy-snps Thanks I forwarded your remarks to the team who created the patch.

**Comment by raducoravu** [comment]
@chrispy-snps my colleague worked more on the patch, now it looks like this:
[ForceUniqueFilter.java.zip](https://github.com/dita-ot/dita-ot/files/8033186/ForceUniqueFilter.java.zip)

He says it should cover the problem you found.

**Comment by chrispy-snps** [comment]
@raducoravu - I can confirm that the lower-level descendants are now considered, and that the indexing now reflects the actual file duplication count - thank you!

If I comment out the nested subtopics in submap?.ditamap, the output of `copy-to` is:

```
   <submap keyscope="submap1">
      ...
      <topicref href="topic.dita"/>
   </submap>
   <submap keyscope="submap2">
      ...
      <topicref href="topic.dita" copy-to="topic_2.dita"/>
   </submap>
```

Note that the first topic has no `@copy-to` attribute.

But if I uncomment them, the output of `copy-to` is:

```
   <submap keyscope="submap1">
      ...
      <topicref href="topic.dita">
         <topicref href="topic.dita#concepts" copy-to="topic.dita#concepts"/>
         <topicref href="topic.dita#configuration" copy-to="topic.dita#configuration">
            <topicref href="topic.dita#option1" copy-to="topic.dita#option1"/>
            <topicref href="topic.dita#option2" copy-to="topic.dita#option2"/>
         </topicref>
         <topicref href="topic.dita#limitations" copy-to="topic.dita#limitations"/>
      </topicref>
   </submap>
   <submap keyscope="submap2">
      ...
      <topicref href="topic.dita" copy-to="topic_2.dita">
         <topicref href="topic.dita#concepts" copy-to="topic_2.dita#concepts"/>
         <topicref href="topic.dita#configuration" copy-to="topic_2.dita#configuration">
            <topicref href="topic.dita#option1" copy-to="topic_2.dita#option1"/>
            <topicref href="topic.dita#option2" copy-to="topic_2.dita#option2"/>
         </topicref>
         <topicref href="topic.dita#limitations" copy-to="topic_2.dita#limitations"/>
      </topicref>
   </submap>
```

Note that the descendants of the first topic have a `@copy-to` trying to copy the file to itself. As a result, the DITA-OT issues this warning:

```
  [copy-to] [DOTX064W][WARN] The copy-to attribute [copy-to="topic.dita"] uses the name of a file that already exists, so this attribute is ignored.
```

So I think somehow the first topic instance should remain unmodified, like this:

```
   <submap keyscope="submap1">
      ...
      <topicref href="topic.dita">
         <topicref href="topic.dita#concepts"/>
         <topicref href="topic.dita#configuration">
            <topicref href="topic.dita#option1"/>
            <topicref href="topic.dita#option2"/>
         </topicref>
         <topicref href="topic.dita#limitations"/>
      </topicref>
   </submap>
   <submap keyscope="submap2">
      ...
      <topicref href="topic.dita" copy-to="topic_2.dita">
         <topicref href="topic.dita#concepts" copy-to="topic_2.dita#concepts"/>
         <topicref href="topic.dita#configuration" copy-to="topic_2.dita#configuration">
            <topicref href="topic.dita#option1" copy-to="topic_2.dita#option1"/>
            <topicref href="topic.dita#option2" copy-to="topic_2.dita#option2"/>
         </topicref>
         <topicref href="topic.dita#limitations" copy-to="topic_2.dita#limitations"/>
      </topicref>
   </submap>
```

If your colleague would find it useful, feel free to mention [`ditaot_save_preprocessing.pl`.](https://github.com/chrispy-snps/DITA-ditaot-utilities#ditaot_save_preprocessingpl) It works on a DITA-OT development tree too; the examples above are copied/pasted directly from what it saves.
