### ISSUE TITLE
Possible typo for service mark

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#3753]
## Expected Behavior

The service mark code should be written correctly.
https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/i18n/en.xml line 44
```xml
<!-- Service mark -->
<character>&#x2120;</character>
```
## Actual Behavior

Wrongly coded as:
```xml
<!-- Service mark -->
<character>&#2120;</character>
```
This will be appeared as U+0848 MANDAIC LETTER ATT instead of U+2120 SERVICE MARK.

## Possible Solution

Correct the typo.

## Steps to Reproduce
No procedure.

## Copy of the error message, log file or stack trace
No error messages.

## Environment
* DITA-OT version: 3.6.1

**Comment by jelovirt** [comment]
This issue occurs in every language file that has service mark configuration. Search and replace over files.

**Comment by easirois** [comment]
Added pull request https://github.com/dita-ot/dita-ot/pull/3754
