### ISSUE TITLE
Cannot run integrator on Windows and then use the DITA-OT on Linux

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3755]
Let's say I have a DITA-OT folder on Windows and run the DITA-OT integrator in it, it re-generates various resources among which the `config/org.dita.dost.platform/plugin.properties`. All references in the re-generated resources contain Windows-style `\` separators.
Then I take the entire DITA-OT, copy it on a Linux or Mac machine and try to use it to publish a small DITA Map, it will not work, I get an error that the public ID of the DITA Map cannot be mapped through the XML catalogs.
I need to run the DITA-OT integrator again on Linux to make the DITA-OT work again.

In my opinion all resources generated by the DITA-OT integrator process should use `/` style path separators which work both on Windows and on Linux/Mac.

**Comment by chrispy-snps** [comment]
@raducoravu, thank you for filing this! I use Ubuntu 20.04 in Windows 10 via WSL, so I jump back and forth between the two worlds on-the-fly. This has been a thorn in my side for awhile, but I never managed to track down the root cause.

**Comment by easirois** [comment]
We run into the same issue as well with DITA OT 3.x and install.

I will do more testing, but adding the replace() in this line in Integrator.java does dump "/" in the properties file while generated from a windows machine.  

configuration.put(name, FileUtils.getRelativePath(new File(ditaDir, "dummy"), f.getPluginDir()).getPath().replace("\\", "/"));

**Comment by easirois** [comment]
hmm..just that fix doesn't do it.  Looks like the config\plugin.xml file might have a role as well to play.

**Comment by easirois** [comment]
That seems to work on my end.  I'll provide a pull request for it.
