### ISSUE TITLE
Separate temporary files folders for each deliverable

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3757]
I can set the "clean.temp=no" parameter to specify that the transformation temporary files folder should not be deleted, but right now all deliverables are published using the same temporary files folder, making it hard to debug for each deliverable and see what temporary files have been created for them. 
So I think that for each deliverable we should have a separate subfolder in the transformation temporary files folder, to keep the temporary files separately. This would help also if at some point we want to make the processing parallel for all deliverables.

**Comment by kirkilj** [comment]
If the memory store is enabled, would it not also need to be partitioned by deliverable where applicable?
