### ISSUE TITLE
Empty param in project.xml causes Error: null

### ISSUE THREAD

**Issue by vicmortelmans** [dita-ot/dita-ot#3761]
## Expected Behavior
Running

`dita.bat --project=project.xml --verbose --debug`

When a param in the project.xml is empty and this is not allowed (is it?), the error message should describe what the problem is

## Actual Behavior

Running the above command returns:

```
Searching for integrator.xml ...
Error: null
```

## Steps to Reproduce

In the project.xml, in `<deliverable> -> <publication>`, provide an empty param:

`         <param name="the_name_of_the_param" value=""/>`

## Environment

* DITA-OT version: 3.6.1
* Operating system and version: Windows
* How did you run DITA-OT? dita.bat
* Transformation type: custom

**Comment by thendarion** [comment]
I just ran into this as well on Linux, so it's platform-independent
