### ISSUE TITLE
Adopt appropriate Japanese font setting in PDF2

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#3768]
## Description
Avoid garbled glyph in Japanese DITA topic formatting in PDF2 output.

## Possible Solution
Change obsolete Japanese font-family assignment in the following file:
[https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/font-mappings.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/fo/font-mappings.xml)

## Potential Alternatives
None.

## Additional Context
The sample DITA instance is here:
[https://github.com/AntennaHouse/pdf5-ml/tree/master/samples/sample_ja](https://github.com/AntennaHouse/pdf5-ml/tree/master/samples/sample_ja)

Also the expected result is here:
[https://github.com/AntennaHouse/pdf5-ml/blob/master/samples/sample_ja/out/sample_ja.pdf](https://github.com/AntennaHouse/pdf5-ml/blob/master/samples/sample_ja/out/sample_ja.pdf)

I attached the PDF2 FOP output that use above `font-mappings.xml`.

[sample_ja-before.pdf](https://github.com/dita-ot/dita-ot/files/6694659/sample_ja-before.pdf)

I attached the same output that uses appropriate Japanese font:

[sample_ja-after.pdf](https://github.com/dita-ot/dita-ot/files/6694665/sample_ja-after.pdf)

I will make the pull-request to enable this request.

**Comment by jelovirt** [comment]
Fixed by #3769
