### ISSUE TITLE
Null pointer exception in pdf generation when using dost Imgutils getheight/width()

### ISSUE THREAD

**Issue by Koushik9020** [dita-ot/dita-ot#3789]
Hello All,
I’m using dita-ot-1.8.5 and trying to create a pdf by inserting few EPS images to source xml files and trying to scale those images using the scale-to-fit attribute in the source.

So In order to use the scale-to-fit attribute I need to get the actual height and actual width of the EPS  image so that I can use them as conditions for setting the image attributes related to scale-to-fit from XSL:FO (like for example content-width and content-height etc.., ) inside the <xsl:external-graphic/> tags

so for getting the actual height/width of the EPS images I’m using this functions like:- getheight() and getwidth() from the Imgutils dita source dost.jar project inside my xslt stylesheet of the dita-ot pdf plugin but I’m getting Nullpointer Exection in the transformation log with -1 as it’s values.

But when I tried the same thing with .png images it works as expected. 

Any idea like if we support the EPS images with Imgutils dost.jar inside the dita-ot For getting the EPS image height/width 

Please suggest the possible ways for fixing this.

**Comment by robander** [comment]
There is really no support available for DITA-OT 1.8.5, and the referenced code does not exist in recent releases, so this is not something that is fixable at this point.

As @drmacro noted in the [DITA-OT Slack channel](https://dita-ot.slack.com/archives/C02DW51E3/p1628601081027400), working with EPS will likely require custom code. My only experience with it involved using Ghostscript to render the EPS (actually a Postscript file), and then embedding the image. There is nothing natively in DITA-OT to support that workflow though.

**Comment by jelovirt** [comment]
Closing as obsolete.
