### ISSUE TITLE
output PDF failure by "fo:flow" is missing child elements

### ISSUE THREAD

**Issue by qiangpx** [dita-ot/dita-ot#3828]
I'm a newer for dita-ot ,and exactly, i think it is not a bug, it's just a wrong use to generate pdf format output by using Java API. so I need you support to guide me how to generate pdf file, thank you a lot. I refer to the link below
https://www.dita-ot.org/dev/reference/java-api.html 
## Expected Behavior
want to test ProcessorTest.testRun() successfully.
## Actual Behavior
"fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10729)
## Possible [Solution](url)
looking forward to your suggestion 
## Steps to Reproduce
1. downlaod the dita-ot project from https://github.com/dita-ot/dita-ot and build in local
2. only change transfertype from html5 to pdf coz i want to get pdf file  (ps: other parameters are defalut)
3. Run test with Junit : ProcessorTest.testRun

## Copy of the error message, log file or stack trace
]([url]([url](url)))
--------------------
16:56:36.227 [main] DEBUG org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager - page finished: 1, current num: 1
16:56:36.228 [main] DEBUG org.apache.fop.area.AreaTreeHandler - Last page-sequence produced 1 pages.
16:56:36.228 [main] DEBUG org.apache.fop.layoutmgr.PageSequenceLayoutManager - Ending layout
16:56:36.248 [main] ERROR org.apache.fop.cli.InputHandler - net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10729)
**### [ERROR] Anttask - Error rendering fo file: /tmp/junit3428944608494935814/tmp/1636966515861/topic.fo <org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10729)**
net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10729)>org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10729)
net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:flow" is missing child elements. Required content model: marker* (%block;)+ (See position 1:10729)
	at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)
	at org.apache.fop.tools.anttasks.FOPTaskStarter.render(Fop.java:671)
	at org.apache.fop.tools.anttasks.FOPTaskStarter.run(Fop.java:532)
	at org.apache.fop.tools.anttasks.Fop.execute(Fop.java:369)
---------------------
## Environment

* DITA-OT version: master branch, maybe 3.6.1
* Operating system and version:
Linux version 4.19.112-2.el8.x86_64 (root@3e6e2f794d6849b0823b9cb19064f400) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)) #1 SMP Wed Jun 10 09:04:49 EDT 2020
* How did you run DITA-OT?
  do UnitTest with IDEA
* Transformation type:
  PDF

**Comment by jelovirt** [comment]
Taking a unit test, changing the arguments, and expecting everything to keep on working is not really how unit tests are intended to be used.

Please see [Using the Java API](https://www.dita-ot.org/dev/reference/java-api.html) for documentation on how to use DITA-OT via the Java API.
