### ISSUE TITLE
Need better design for "skip" properties

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#3845]
## Description

Many of our Ant targets in the preprocess code have "skip" properties that allow you to skip running part of our build pipeline. These are considered internal properties and subject to change, but available to advanced users who understand the code. There are several problems:

* They are not documented, even for advanced users (this has come up in Slack a few times).
* The naming is inconsistent, with most based on Ant target names rather than on function. You can disable the code that cascades map metadata, but you have to know the Ant target is `move-meta-entries` making the property name `preprocess.move-meta-entries.skip`. Some do not use the Ant target name, such as `preprocess.clean-map-check.skip`. Where preprocess and preprocess2 have overlapping targets, preprocess2 uses the name from preprocess; where they do not, it creates a property with the Ant target name. An odd one is `clean-temp.skip` which is outside of preprocess.
* Property names based on Ant target name makes it hard to split or combine steps
* You have to set the property to disable something, which is not intuitive; setting `preprocess.keyref.skip=true` disables keyref resolution.
* Because of how Ant works, setting the variable to *anything* disables the target, it just checks if the property is set. So, setting `preprocess.keyref.skip=false` also disables keyref. This is likely familiar to people with a lot of Ant experience, but many of those trying to tweak DITA-OT builds do not have that background.

List of current skip properties in base plugin:

- `clean-temp.skip`
- `preprocess.branch-filter.skip`
- `preprocess.chunk.skip`
- `preprocess.clean-map-check.skip`
- `preprocess.clean-preprocess.skip`
- `preprocess.coderef.skip`
- `preprocess.conref.skip`
- `preprocess.conrefpush.skip`
- `preprocess.copy-files.skip`
- `preprocess.copy-flag.skip`
- `preprocess.copy-html.skip`
- `preprocess.copy-image.skip`
- `preprocess.debug-filter.skip`
- `preprocess.gen-list.skip`
- `preprocess.keyref.skip`
- `preprocess.map-profile.skip`
- `preprocess.maplink.skip`
- `preprocess.mapref.skip`
- `preprocess.move-meta-entries.skip`
- `preprocess.normalize-codeblock.skip`
- `preprocess.profile.skip`
- `preprocess.topic-profile.skip`
- `preprocess.topicpull.skip`

Note that not all are used in `target/@unless`. Some are used e.g.

```xml
<filter class="org.dita.dost.writer.NormalizeCodeblock"
        unless:set="preprocess.normalize-codeblock.skip"/>
```

## Possible Solution

Ideally, in a 4.0 major release we could:
* Create a consistent pattern for all of the current "skip" properties.
* The property names should be based entirely on function, not connected to the Ant target, so that even if we split a single `chunk` target into 5 targets, the "process chunking" property does not change and works to disable all 5.
* The property be set to "false" to disable a step. Ant has `istrue` condition that maps case-insensitive "true", "yes", and "on" to `true`; otherwise `false`.
* The actual Ant property used to skip a target is internal-only, and our build should fail if someone tries to set it; going forward this ensures we do not break anyone if those properties have to change
* All of this makes it possible to document the properties in a straightforward manner - "Set X to false to disable conref resolution" - without going into detail about why it's "enable this property to disable this feature", or why "disable this property" also disables it, etc.

I'm not sure of the best pattern for these or I'd have started with a PR that updated one step. Adding some ideas, using conref as an example; I like having `run` or `buildstep` or `build-step` in there, but am not attached to anything. I do like having the feature name last so all of these have the same prefix:
* `run.conref.step=true`
* `run.step.conref=true`
* `run.buildstep.conref=true`
* `build-step.conref=true`

## Potential Alternatives

We could simply document the properties that exist today, but we've intentionally avoided this:
* It locks in the properties like an external API, making them hard to change
* The issues above all make it hard to document, requiring an explanation of Ant and of the "enable to disable" naming

## Additional Context

This has come up twice in Slack over the last few months, both times about the `preprocess.clean-map-check.skip` property as a way to skip that step and retain information added by preprocessing.

**Comment by robander** [comment]
One open question after thinking on this more - would this design apply to *all* parameters that let you skip a processing target? Most of them apply to a DITA feature (conref, keyref, resolve links, etc), but some do not (clean temp directory). 

I think we could go either way on this (all documented, vs some still internal-only as today), but if some "skip this Ant target" properties stay internal-only our docs should probably note that fact.

**Comment by jelovirt** [comment]
> would this design apply to all parameters

This is a good point. Right now you use `clean.temp=no` in to retain temporary files. The falsy value of `clean.temp` is mapped to internal property `clean-temp.skip`. So in effect this is already what we're targeting, except for the consistent naming scheme.

**Comment by jelovirt** [comment]
For example chunk processing has

```xml
<target name="chunk-check">
  <condition property="preprocess.chunk.skip">
    <isset property="noMap"/>
  </condition>
</target>
```

That is, the processing only runs chunking if the start document is a map. We need to retain this possibility, that processing will not neccessarily know in the beginning whether a given step should be ran. So we can't have an init phase set all internal skip properties in the beginning.

**Comment by jelovirt** [comment]
@robander If we use for example `run.chunk.step=true` and it maps to internal skip property, do we

1. use a new skip property `_chunk.disable` and completely remove the old property.
2. keep using the old property `preprocess.chunk.skip`.
3. use the new property but initialize the value based on the old property.

I'm leaning towards option 3 with a deprecation warning for the old property and removing the support in e.g. 4.1.

**Comment by jelovirt** [comment]
Reopen because we need additional code changes.

**Comment by infotexture** [comment]
@jelovirt Is there something left to do here?
