### ISSUE TITLE
HTML5 Output fails when having links between inner topics and chunk="to-content select-topic"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3846]
## Expected Behavior
Uploaded a sample project, in the "untitled5.dita" topic there are two inner topics and one refers to the other:

    <topic id="topic2">
        <title>Topic 2</title>
        <body>
            <p>link to topic3: <xref href="#topic3"/></p>
        </body>
    </topic>
    <topic id="topic3">
        <title>Topic 3</title>
        <body>
            <p>Para 3</p>
        </body>
    </topic>

The DITA Map splits the main topic in multiple topics:

    <topicref href="untitled5.dita#topic2" chunk="to-content select-topic"/>
    <topicref href="untitled5.dita#topic3" chunk="to-content select-topic"/>

The HTML5 output should produce HTML files "topic2.html" and "topic3.html", the "topic2.html" should have a link to "topic3.html"

## Actual Behavior
The HTML5 output fails with a fatal error in the chunking stage:

    [Error: java.lang.IllegalArgumentException: Illegal character in fragment at index 21: untitled5.dita#topic2#topic3

## Possible Solution
In the "org.dita.dost.writer.AbstractChunkTopicParser.processAttributes(Attributes)" method in the if clause:

              if (href.startsWith(SHARP)) {

if the "relative" variable has an anchor inside it, avoid merging it with the href "relative + href". Something like:

            if (href.startsWith(SHARP)) {
                // if @href refers to a location inside current parsing file
                // update @href to point back to current file
                // if the location is moved to chunk, @href will
                // be update again to the new location.
            	if(relative.toString().contains("#")) {
            		XMLUtils.addOrSetAttribute(resAtts, ATTRIBUTE_NAME_HREF, relative.resolve(href).toString());
            	} else {
            		XMLUtils.addOrSetAttribute(resAtts, ATTRIBUTE_NAME_HREF, relative + href);
            	}
            }

## Steps to Reproduce
[sampleChunkSelfLinks.zip](https://github.com/dita-ot/dita-ot/files/7844006/sampleChunkSelfLinks.zip)

Publish the attached project to HTML5.

## Copy of the error message, log file or stack trace
     [Error: java.lang.IllegalArgumentException: Illegal character in fragment at index 21: untitled5.dita#topic2#topic3

## Environment

* DITA-OT version: 3.6.1
* Operating system and version: any
* How did you run DITA-OT? dita command
* Transformation type:HTML5

**Comment by raducoravu** [comment]
@jelovirt if someone would add a pull request to the AbstractChunkTopicParser class would this interfere with the larger chunking stage refactoring that you were doing to support the DITA 2.0 features? I remember this was something you were working on at some point.

**Comment by jelovirt** [comment]
@raducoravu The DITA 2.0 chunking will be its own module and will not share code with DITA 1.x chunking module. So it would be safe to add this.
