### ISSUE TITLE
Update Apache FOP to version 2.8

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3863]
Update to Apache FOP 2.7:
https://xmlgraphics.apache.org/fop/2.7/releaseNotes_2.7.html
and for the satellite libraries:
Apache XML Graphics Commons 2.7
Apache FOP-PDF-Images 2.7

**Comment by raducoravu** [comment]
List of fixes:
https://issues.apache.org/jira/browse/FOP-2781?jql=project%20%3D%20FOP%20AND%20resolution%20%3D%20Fixed%20AND%20fixVersion%20%3D%202.3%20ORDER%20BY%20updated%20DESC%2C%20created%20DESC%2C%20priority%20DESC

We have not yet updated the FOP libs in our Oxygen Chemistry PDF-CSS processor so we have no first find knowledge about how 2.7 works.

**Comment by jlacour31** [comment]
We successfully integrate all FOP, FOP-Images and XML Graphics Commons libraries into Oxygen. At this time both pdf2 and pdf-css plugins are working fine and no failures appeared in unit testing.

**Comment by raducoravu** [comment]
There are now new releases of FOP 2.8 and the associated libraries. We have not tested with it on our side but maybe the DITA OT 4.0 could come bundled with these latest libraries.

**Comment by jlacour31** [comment]
From what I can see, DITA-OT 4.1.1 already includes FOP-2.8, we can close this.
