### ISSUE TITLE
Extra fop.jar present in DITA-OT-3.7

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#3864]
## Expected Behavior
There should not be any fop.jar present in the root folder of DITA-OT.

## Actual Behavior
There's a 'fop.jar' in DITA-OT root folder, containing only a MANIFEST file.

## Steps to Reproduce

1. Download DITA-OT 3.7 from https://www.dita-ot.org/download
2. Unzip it and check the dita-ot-3.7 folder content
3. The same jar is present in dita-ot-3.7\plugins\org.dita.pdf2.fop\lib\

## Environment

* DITA-OT version: 3.7
* Operating system and version: Windowns
* How did you run DITA-OT? N/A
* Transformation type: N/A

**Comment by jelovirt** [comment]
This is likely due to manual fixes I had to do for the distribution package.

**Comment by infotexture** [comment]
@jelovirt @raducoravu I tested this again by running the distribution build task locally from a [fresh Git worktree](https://github.com/dita-ot/dita-ot/wiki/Fresh-dist-worktree).

The empty `fop.jar` is still created.

The CI fixes in [f30f8ba](https://github.com/dita-ot/dita-ot/commit/f30f8baca7934bf5faacd8c2a3aabacf76c54c3c) do not apply when running locally of course, but the extra JAR file does not appear to be created by the CI process, as it appears during the distribution build task even when CI is not involved.

**Comment by jelovirt** [comment]
Should be fixed now. @infotexture can you close this if you can confirm?

**Comment by infotexture** [comment]
Re-ran the distribution build locally from a [fresh Git worktree](https://github.com/dita-ot/dita-ot/wiki/Fresh-dist-worktree) based on d55b27164eb773ab28a738636fbd2ffc28401a1c.

The empty `fop.jar` is no longer created. ✅

_Re-closing._
