### ISSUE TITLE
Updated Saxon processor to version 11.1

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3868]
## Description
Update used Saxon processor to version 11.1: https://www.saxonica.com/products/latest.xml

Changes between 10 and 11.1 https://www.saxonica.com/documentation11/index.html#!changes/all/10-11.1

**Comment by jelovirt** [comment]
Saxon 11 has moved away from old SAX and JAXP resolvers to org.xmlcatalog resolver support. This is problematic because Ant has a hard dependency to old XML resolver implementation. So we would need to finish #3516 before this.

**Comment by jelovirt** [comment]
https://github.com/xmlresolver/xmlresolver/issues/86 has been fixed

**Comment by raducoravu** [comment]
@jelovirt recently I started working to integrate Saxon 11 in Oxygen (for the Oxygen v 25 release), I listed some problems I have with the XML catalog resolver here: https://saxonica.plan.io/issues/5582#note-8

In my opinion you could bypass the entire new XML catalog implementation by:

- Use net.sf.saxon.lib.ParseOptions.setXMLReaderMaker(Maker) to create your own XML readers with your own entity resolver set to it. The entity resolver needs to be an instance of EntityResolver2
- Use the "configuration.setResourceResolver(resolver);" to set your own ResourceResolverWrappingURIResolver over your custom URIResolver.

**Comment by raducoravu** [comment]
About https://github.com/xmlresolver/xmlresolver/issues/86 I discussed with Norman Walsh on this issue:
https://saxonica.plan.io/issues/5635
and the latest 4.5.0 version of the xmlresolver project no longer has the disk cache enabled by default.

**Comment by robander** [comment]
Merged version 12.2 with https://github.com/dita-ot/dita-ot/pull/4130
