### ISSUE TITLE
The space gets removed in PDF, in the case of <unknown> element.

### ISSUE THREAD

**Issue by ndeswal** [dita-ot/dita-ot#3872]
## Expected Behavior
When generating PDF from the given XML
```
<topic><title>DEMO TOPIC</title>
<body><p>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;This
is a paragraph with starting space</p>
<p>This is a paragraph to show<unknown>Newly added content </unknown>unknown tag space issue</p></body></topic>
```
The output in PDF should be inline with xhtml output. See screenshots attached
"This is a paragraph to show unknown tag space issue"
HTML output
![image](https://user-images.githubusercontent.com/43330862/152516774-b817a7a5-26c1-4366-8e77-f4fdb8e2a88b.png)

## Actual Behavior
The space between text 'show & text 'unknown' is not present.
See attached screenshot of PDF output
![image](https://user-images.githubusercontent.com/43330862/152516965-f9cf41ca-d413-4448-82ee-c0c0d91d6f41.png)

## Steps to Reproduce
1. generated the HTML & PDF output of the xml snippet above.
`dita --input=<input file> --format=pdf --output=<output folder>`

## Environment

* DITA-OT version: 3.3.3
* Operating system and version:
  Windows
* How did you run DITA-OT?
`dita` command
* Transformation type:
  PDF

**Comment by chrispy-snps** [comment]
@ndeswal - I cannot reproduce this with DITA-OT 3.7.0. I tried three transformation types -- `xhtml`, `html5`, and `pdf2` -- and all three omitted the space, which is the correct behavior.

**Comment by ndeswal** [comment]
I mentioned the wrong DITA-OT version. The DITA-OT version is 3.3.3. Sorry for the inconvenience.

**Comment by chrispy-snps** [comment]
@ndeswal - in that case, this appears to be fixed (no space inserted when `<unknown>` is suppressed) in the latest DITA-OT release.
