### ISSUE TITLE
args.filter does not support multiple relative paths in DITA-OT project file

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3873]
## Expected Behavior
Per [the documentation](https://www.dita-ot.org/3.7/topics/using-project-files.html), DITA-OT project files promise to convert relative paths to absolute paths when `path="..."` is used:

> Use `path` for parameters that require an absolute value, like `args.cssroot`. Paths may be defined relative to the project file, but are always expanded to an absolute system path.

If I specify multiple relative paths for `args.filter` in a DITA-OT project file:

```
<publication transtype="html5">
  <!-- this does not work -->
  <param name="args.filter" path="flag_final.ditaval:filter_B.ditaval"/>
</publication>
```

then all paths in the list should be resolved to absolute paths.

## Actual Behavior
Only the first path is resolved to a full path, leaving the second path to fail as follows:

```
$ dita --project project.xml
[ditaval-merge] [DOTJ071E][ERROR] Cannot find the specified DITAVAL 'file:/home/chrispy/dita-ot/filter_B.ditaval'.
```

Multiple full paths do work as expected:

```
<publication transtype="html5">
  <!-- this works, but it is not portable across compute environments -->
  <!-- (as evidenced by the fact that you'll have to modify this to run it yourself -->
  <param name="args.filter" path="/mnt/c/nobackup/project_file_experiments/ditaval/flag_final.ditaval:/mnt/c/nobackup/project_file_experiments/ditaval/filter_B.ditaval"/>
</publication>
```

but this is not portable across compute environments.

## Steps to Reproduce
1. Extract the following testcase:
   [project_file_multiple_ditaval.zip](https://github.com/dita-ot/dita-ot/files/8008890/project_file_multiple_ditaval.zip)
2. Run the following command:
   `dita --project project.xml`

## Environment
* DITA-OT version: 3.7
* Operating system and version:
  Linux
* How did you run DITA-OT?
  `dita` command
* Transformation type:
  HTML5

**Comment by raducoravu** [comment]
It would probably be useful for things to work as @chrispy-snps suggests.
Probably this could be fixed in the 'org/dita/dost/project/Project.java' "resolvePath" method but somehow the parameter "args.filter" is the only one which uses ":" to separate distinct path values so a fix would probably need to split the initial value based on ":" only if the parameter name is "args.filter" to avoid improbable cases when another's parameter value contains a ":" inside it.

**Comment by chrispy-snps** [comment]
I also noticed that in Windows, `args.filter` file lists with absolute paths *must* use the `file:/` prefix:

```
<param name="args.filter"
                value="file:/C:/path/to/flag_final.ditaval;file:/C:/path/to/filter_B.ditaval"/>
```

But, in Linux, file lists *cannot* use the `file:/` prefix (probably because the splitting on ':' gets confused)

```
<param name="args.filter"
                value="/path/to/flag_final.ditaval:/path/to/filter_B.ditaval"/>
```

If `file:/` is not used in Windows, then the following error occurs:

```
C:\args-filter>dita.bat --project project.xml
Error: Failed to run pipeline: URI scheme is not "file"
```

This might (or might not) be relevant to the solution.

**Comment by raducoravu** [comment]
Maybe another implementation approach would be to allow specifying the same parameter name multiple times in the DITA OT project file like:

    <publication transtype="html5"> 
        <param name="args.filter" value=...
        <param name="args.filter" value=...

and take into account all such values when processing the DITA OT project file.

**Comment by jelovirt** [comment]
`args.filter` should not be used with project files. You should be using `project` element

```xml

<publication transtype="html5">
  <profile>
    <ditaval href="flag_final.ditaval"/>
    <ditaval href="filter_B.ditaval"/>
  </profile>
</publication>
```
