### ISSUE TITLE
Branch filtering does not handle nested subtopics properly

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3875]
## Expected Behavior
If I have nested subtopics, and the same topic is used in two different DITAVAL contexts:

```
  <topicgroup keyscope="A">
    <ditavalref href="filter_A.ditaval"/>
    <topicref href="topic.dita">  <!-- reused topic -->
      <topicref href="topic.dita#subtopic1_id"/>
      <topicref href="topic.dita#subtopic2_id"/>
      <topicref href="topic.dita#subtopic3_id"/>
    </topicref>
  </topicgroup>

  <topicgroup keyscope="B">
    <ditavalref href="filter_B.ditaval"/>
    <topicref href="topic.dita">  <!-- reused topic -->
      <topicref href="topic.dita#subtopic1_id"/>
      <topicref href="topic.dita#subtopic2_id"/>
      <topicref href="topic.dita#subtopic3_id"/>
    </topicref>
  </topicgroup>
```

then branch filtering should uniquify the topic and its nested subtopics properly.

## Actual Behavior
After the `branch-filter` preprocessing stage, the map looks like this:

```
   <topicgroup keyscope="A">
      <topicref href="topic.dita">
         <topicref href="topic.dita#subtopic1_id"/>
         <topicref href="topic.dita#subtopic2_id"/>
         <topicref href="topic.dita#subtopic3_id"/>
      </topicref>
      <ditavalref href="filter_A.ditaval"/>
   </topicgroup>

   <topicgroup keyscope="B">
      <topicref href="topic-1.dita">
         <topicref href="topic.dita#subtopic1_id" filter-copy-to="topic-1.dita#subtopic1_id"/>
         <topicref href="topic.dita#subtopic2_id" filter-copy-to="topic-1.dita#subtopic2_id"/>
         <topicref href="topic.dita#subtopic3_id" filter-copy-to="topic-1.dita#subtopic3_id"/>
      </topicref>
      <ditavalref href="filter_B.ditaval"/>
   </topicgroup>
```

(I used the `ditaot_save_preprocessing.pl` script from [here](https://github.com/chrispy-snps/DITA-ditaot-utilities) to easily obtain the preprocessing results.)

In the "B" branch, note that the top-level topic is correctly uniquified to `@href="topic-1.dita"`, but the nested subtopics are left in an unfinished state with the original `@href` and lingering `@filter-copy-to` attributes that were never used.

Because of this, the child navigation links in the final HTML output are incorrect:

* Topic in A
  * Subtopic 1 in A
  * Subtopic 2 in A
  * Subtopic 3 in A
* Topic in B         <-- correct
  * Subtopic 1 in A  <-- incorrect, should be B
  * Subtopic 2 in A  <-- incorrect, should be B
  * Subtopic 3 in A  <-- incorrect, should be B

## Possible Solution
The `@filter-copy-to` on the nested subtopics should also be applied.

I think this might be follow-up work to #3680 (Transformation fails with "URI has a fragment component" when calling a `<mapref>` with a `<ditavalref>`).

I am happy to test any patches or suggested changes.

## Steps to Reproduce
1. Download the following testcase:
   [branch_filtering_nested_subtopics.zip](https://github.com/dita-ot/dita-ot/files/8020075/branch_filtering_nested_subtopics.zip)
2. Run the following command:
   `dita -i map.ditamap -f html5 -o out`

## Environment
* DITA-OT version: 3.7
* Operating system and version:
  Linux
* How did you run DITA-OT?
  `dita` command
* Transformation type:
  HTML5

**Comment by raducoravu** [comment]
@chrispy-snps as a possible fix in the org.dita.dost.module.BranchFilterModule.generateCopies(Element, List<FilterUtils>) method here:

     final FileInfo srcFileInfo = job.getFileInfo(srcUri);

the anchor should be removed before searching for the source file:

    final FileInfo srcFileInfo = job.getFileInfo(URLUtils.removeFragment(srcUri));

and here:

     job.getStore().transform(srcAbsUri, dstAbsUri, pipe);

again remove the anchors before transforming the source to the destination:

     job.getStore().transform(URLUtils.removeFragment(srcAbsUri), URLUtils.removeFragment(dstAbsUri), pipe);

The fix seems to work for me on your small example. I think the fix ends up in certain cases (also in yours) copying the same source file multiple times to the destination file, possibly as a speed improvement if the destination exists we should skip calling job.getStore().transform multiple times with the same source and destination URIs. But I'm not sure precisely how this could be done.

**Comment by raducoravu** [comment]
@chrispy-snps I will try to submit the pull request as I also need to come up with an automated test for this.
