### ISSUE TITLE
Incorrect numbering of footnotes without callout

### ISSUE THREAD

**Issue by DeekshaBhagat** [dita-ot/dita-ot#3878]
## Expected Behavior
The default numbering should start with 1 for footnotes when callout is defined by user.

## Actual Behavior
The numbering starts with 2 for footnote when callout is not defined by user.
Special case - This happens only when, we add a footnote to title of topic.

## Possible Solution
TOC also shows title. So, tried removing Table of Content page. But, stiill getting incorrect numbering.

## Steps to Reproduce
1. Create a DitaMap. Create a Topic. Add the topic to DitaMap.
2. Add a footnote to title of Topic. Don't assign it a callout.
3. Render PDF. Default numebring starts with 2.

* Topic Content and Map Content [SampleMapTopic.zip](https://github.com/dita-ot/dita-ot/files/8024640/SampleMapTopic.zip)
* Rendered PDF [Map117e99f80-3035-4f83-90fb-d2a413ea3ff5.pdf.pdf](https://github.com/dita-ot/dita-ot/files/8024615/Map117e99f80-3035-4f83-90fb-d2a413ea3ff5.pdf.pdf)

## Copy of the error message, log file or stack trace
No error message shown

## Environment

* DITA-OT version: 3.5
* Operating system and version: Linux
* How did you run DITA-OT? Dita Java API
* Transformation type: PDF

**Comment by DeekshaBhagat** [comment]
Rendered PDF - [](url
[Map117e99f80-3035-4f83-90fb-d2a413ea3ff5.pdf.pdf](https://github.com/dita-ot/dita-ot/files/8024615/Map117e99f80-3035-4f83-90fb-d2a413ea3ff5.pdf.pdf)
)

**Comment by DeekshaBhagat** [comment]
Hi @jelovirt ,
Is there any way to debug this issue. I am afraid that, footnotes are counted twice , when we add them in topic title.

**Comment by chrispy-snps** [comment]
@DeekshaBhagat - according to the [content models for <title> ](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/contentmodels/cmltt.html#cmltt__title), `<fn>` is not one of the allowed child elements of `<title>`. When I transform the testcase you attached, I get the following error:

```
 [gen-list] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:/home/chrispy/3878/SampleMapTopic/3032ECA72E2F000062027DF400110602'.: file:/home/chrispy/3878/SampleMapTopic/3032ECA72E2F000062027DF400110602 Line 1:The content of element type "title" must match "(boolean|keyword|markupname|apiname|option|parmname|cmdname|msgnum|varname|wintitle|numcharref|parameterentity|textentity|xmlatt|xmlelement|xmlnsname|xmlpi|ph|b|i|line-through|overline|sup|sub|tt|u|codeph|synph|filepath|msgph|systemoutput|userinput|menucascade|uicontrol|equation-inline|q|term|abbreviated-form|text|tm|state|cite|data|sort-as|data-about|draft-comment|foreign|svg-container|mathml|unknown|required-cleanup|image)".
```

**Comment by chrispy-snps** [comment]
@DeekshaBhagat - I am unfamiliar with the `pdf2` processing pipeline, but maybe you could look inside the temporary files it creates and see where the title is getting duplicated for the TOC, then somehow add an XSLT template (via a plugin) to delete `title//fn` elements for the TOC case only?

**Comment by DeekshaBhagat** [comment]
@chrispy-snps Thank you for looking into the issue.
Which version of dita-ot did you use.
I am tried using  3.5.2 and 3.7, but it gives following error.

[fop] [ERROR] Anttask - Error rendering fo file: C:\Users\dbt7\AppData\Local\Temp\temp20220216105413232\topic.fo <org.apache.fop.apps.FOPException
      [fop] java.lang.NullPointerException>org.apache.fop.apps.FOPException
      [fop] java.lang.NullPointerException
      [fop]     at org.apache.fop.tools.anttasks.FOPTaskStarter.renderInputHandler(Fop.java:652)

**Comment by chrispy-snps** [comment]
@DeekshaBhagat - I used DITA-OT 3.7. I'm not sure what else to suggest, since the DITA source is invalid (`<fn>` is not allowed in `<title>` per the content model).

**Comment by DeekshaBhagat** [comment]
Thank you @chrispy-snps. We are closing this issue as a known constraint.
