### ISSUE TITLE
New translations for german and french

### ISSUE THREAD

**Issue by Mircea-Andrei16** [dita-ot/dita-ot#3882]
## Description
User came to Oxygen support asking for "Notice" translation in <hazardstatement> and proposes "Hinweis".

## Possible Solution
We have changed certain vars for german and french (variable id = value):
- Notices title = "Hinweises"
- Notice = "Hinweis"
- Caution = "VORSICHT"
- Remember = "Erinnern"
- Notices title = "Notices"
- Notice = "Notice"

## Additional Context
![hazard_notice](https://user-images.githubusercontent.com/72509527/154667095-04b481e7-1ff2-4f6f-8988-4f456d6e8393.png)

**Comment by raducoravu** [comment]
@xephon2 any comments about making these changes?

**Comment by infotexture** [comment]
@raducoravu Looks like there are a few duplicate entries in the list above.

The correct German plural for _Notices_ is _Hinweise_ — no trailing “s”.

**Comment by jlacour31** [comment]
@infotexture the duplicates are the french versions, I already reviewed them.

**Comment by xephon2** [comment]
@raducoravu, @infotexture 

Signal words are defined in the technical standards ANSI Z535.6 and IEC 82079. They are also named on the German Wikipedia site [Sicherheitshinweis](https://de.wikipedia.org/wiki/Sicherheitshinweis). The correct values are:

| **English** | **German** | Meaning                                                                                            |
| ----------- | ---------- | -------------------------------------------------------------------------------------------------- |
| Danger      | Gefahr     | Indicates a hazardous situation that, if not avoided, **WILL** result in death or serious injury.  |
| Warning     | Warnung    | Indicates a hazardous situation that, if not avoided, **COULD** result in death or serious injury. |
| Caution     | Vorsicht   | Indicates a hazardous situation that, if not avoided, could result in minor or moderate injury.    |
| Notice      | Hinweis    | Indicates a situation that, if not avoided, can result in property damage.                         |



> **Note**: The correct German ANSI term for `Notice` is `Hinweis`, but this is no good translation. A safety note of level `Notice` is used to refer to a material damage. `Hinweis` is a term which is usually used for useful information. But if want to explain to your user how he can avoid damage of his 1,000,000 USD machine, this is more than just a useful information. Therefore it is common practice to use the term `Achtung` instead of `Hinweis` for `Notice`. But the correct term is `Hinweis`. The DITA-OT should stick to the standard (even if the standard is not good).

You can find an overview of all ANSI Z535 signal words (in several languages) here (slide 21): [Neue ANSI Z535 - Vom vernünftigen Umgang mit Sicherheitshinweisen](https://docplayer.org/24219221-Neue-ansi-z535-vom-vernuenftigen-umgang-mit-sicherheitshinweisen.html).


**[org.dita.base/xsl/common/strings-de-de.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/xsl/common/strings-de-de.xml)**

| ID         | Current Value | Should be changed to | Explanation                                                                          |
| ---------- | ------------- | -------------------- | ------------------------------------------------------------------------------------ |
| `Danger`   | GEFAHR        | _no change needed_   | The term is usually capitalized.                                                     |
| `Warning`  | Warnung       | WARNUNG              | The term is usually capitalized.                                                     |
| `Caution`  | ACHTUNG       | VORSICHT             | Please use the correct ANSI Z535.6/IEC 82079 term.                                   |
| `Note`     | Anmerkung     | _no change needed_   |                                                                                      |
| `Notes`    | Anmerkungen   | _no change needed_   |                                                                                      |
| `Remember` | Hinweis       | Merke                | This is the imperative of `merken` which is the direct translation of `to remember`. |

**[org.dita.pdf2/cfg/common/vars/de.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.pdf2/cfg/common/vars/de.xml)*

| ID              | Current Value               | Should be changed to | Explanation                                                                                               |
| --------------- | --------------------------- | -------------------- | --------------------------------------------------------------------------------------------------------- |
| `Notice`        | `<!--TODO:Notice-->`        | HINWEIS              | **This string should be stored in `org.dita.base`. All safety levels should be kept in the base plugin!** |
| `Notices title` | `<!--TODO:Notices title-->` | Hinweise             |                                                                                                           |

**Comment by infotexture** [comment]
@xephon2 Thanks for the review & references. I've updated the German translations in #3883 accordingly.

> All safety levels should be kept in the base plugin!

That does look like something that should be aligned, but it's probably best treated as a separate issue. 
I'll discuss with the team and submit a separate PR.

> You can find an overview of all ANSI Z535 signal words (in several languages) here (slide 21): [Neue ANSI Z535 - Vom vernünftigen Umgang mit Sicherheitshinweisen](https://docplayer.org/24219221-Neue-ansi-z535-vom-vernuenftigen-umgang-mit-sicherheitshinweisen.html).

@jlacour31 According to this reference, ANSI Z535 suggests the French “Notice” translation should be “AVIS”.

Shall we make that change here too?

**Comment by jlacour31** [comment]
@infotexture, @xephon2 we changed the french translation for notice accordingly.

**Comment by Schelmenzunft** [comment]
The imperative form "Merke" reads rather unusual, old-fashioned, some may even think it's a typo, Merke(l). Perhaps something like "Nicht vergessen" would be more applicable in technical documentation.

**Comment by infotexture** [comment]
Germans may have different opinions on the most appropriate translation of the `Remember` string, but the changes in #3883 address the original issue, so this should have been closed when #3883 was merged for 3.7.1. (I'll do that now.)

[Overriding strings](https://www.dita-ot.org/dev/topics/overriding-strings.html) is a common plug-in use case that provides a solution for situations like this where users would prefer a different translation than that which DITA-OT provides by default.

@Schelmenzunft If you feel strongly that the default translation of the `Remember` string should be changed, I suggest filing a separate issue, which we can use to discuss pros and cons of each alternative, and decide what's best if consensus emerges there.
