### ISSUE TITLE
Publishing to html5 fails when an image path has query

### ISSUE THREAD

**Issue by DunaMariusCosmin** [dita-ot/dita-ot#3886]
I have a map with a topic that contains a image element like this: 
`<image href="image.png?width=250" id="image_k31_t2r_qsb"/>`

When I tried to publish the map to html5 using version 3.7.0 and I received the following error: 
`Error: Failed to run pipeline: URI has a query component`

It seems to be related to this issue; #3717

This is a sample DITA map: [sampleDitaOT.zip](https://github.com/dita-ot/dita-ot/files/8108367/sampleDitaOT.zip)

**Comment by raducoravu** [comment]
The error occurs here:

    Caused by: java.lang.IllegalArgumentException: URI has a query component
	at java.base/java.io.File.<init>(File.java:429)
	at org.dita.dost.util.URLUtils.exists(URLUtils.java:703)
	at org.dita.dost.module.GenMapAndTopicListModule.categorizeReferenceFile(GenMapAndTopicListModule.java:632)

There are also places in the Store interface like org.dita.dost.store.Store.transform(..) which fail similarly when the URIs have a query and an attempt to create a new file over it throws the error. And I think we should always be flexible in this regard, remove the query, anchor and then attempt to create a file over the URI.
