### ISSUE TITLE
Add the support for id and outputclass in Markdown

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#3900]
## Description
Currently id and outputclass are only available in headings, this could be extended to elements like list-items or images.
We should be able to keep the same format, something like `![Carrot](../../images/Carrot.jpg){#carrot .juice}`

## Workaround
At the moment the only solution is to embed HTML inside the md file: `<img src="../../images/Carrot.jpg" id="carrot" outputclass="juice">`

**Comment by jelovirt** [comment]
@jlacour31 Please file this issue at https://github.com/jelovirt/org.lwdita/issues

**Comment by jlacour31** [comment]
@jelovirt I created https://github.com/jelovirt/org.lwdita/issues/91.
