### ISSUE TITLE
Latest DTD changes in DITA 1.3 specs no longer allow outputclass attribute on change-historylist element

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3905]
This change:https://github.com/dita-ot/dita-ot/commit/43ac6e75e8deb4680dd4c2a675a38f997b549939

made it invalid to use the outputclass attribute on change-historylist using the DTDs bundled with DITA OT 3.7.

        <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
        <topic id="introduction">
            <title>Introduction</title>
            <prolog>
                <change-historylist outputclass="abc"/>
            </prolog>
        </topic>

@robander  can you look a bit into this? The "change-historylist.attributes" in the DTD now no longer allow outputclass.

**Comment by jelovirt** [comment]
Related PR https://github.com/oasis-tcs/dita/pull/334 from DITA TC.

**Comment by robander** [comment]
Fixed in the OASIS repository (commit linked above), and PR open to fix this for dita-ot in 3.7.2.

**Comment by robander** [comment]
Fixed with #3911
