### ISSUE TITLE
HTML5 customisation with chunk attribute

### ISSUE THREAD

**Issue by DivyaRao23** [dita-ot/dita-ot#3908]
We have the following customisation in-place for HTML5 transformations in the rewrite-rules.xsl file:
```xslt
<xsl:template match="file[@format = 'dita']/@result">
     <xsl:variable name="outDir">topics/</xsl:variable>
     <xsl:variable name="fileOnly" select="(tokenize(., '/')[last()])" />
     <xsl:variable name="parentDir" select="tokenize(., '/')[last()-1]" />
     <xsl:choose>
            <xsl:when test="starts-with($parentDir, 'temp|topic')">
                <xsl:attribute name="{local-name()}" select="concat($outDir, $fileOnly)" />
            </xsl:when>
     </xsl:choose>
</xsl:template>
```
 
This customisation creates issues when I include a markdown topic with `chunk="by-topic"` in my ditamap.
 ```xml
<bookmap xml:lang="en-US">
   <chapter href="tn-2119.md" format="markdown" chunk="by-topic" />
</bookmap>
 ```
Only the first chunk that is converted to html is moved to ‘topics’ folder.
Rest of the generated chunks are moved to a different folder
![image](https://user-images.githubusercontent.com/82793275/160628598-4a9ee4fb-7666-4a9b-9487-7e2f934ed37c.png)

I added an `xsl:message` inside the `xsl:template` to see if it gets called for the files which were generated by the chunking, it doesn't call the template for chunked files.

Can this template be called for the chunked files?

* DITA-OT version: 3.6.1
* Operating system and version: macOS

* How did you run DITA-OT? dita` command
 
* Transformation type: HTML5

**Comment by raducoravu** [comment]
So you are using this DITA OT extension point: https://www.dita-ot.org/dev/topics/plugin-rewrite-rules.html
Can you also add to the issue a zip containing a very small sample DITA project to test the problem with and a DITA OT plugin which uses the extension point ?
