### ISSUE TITLE
Remove support for delayed conref domain

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#3918]
## Description
Remove support for [delayed conref domain](https://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/containers/delayconref-d.html). It's only used by Eclipse Help plug-in and has very little use. Removing support for the domain will simplify code and reduced code maintenance burden.

**Comment by robander** [comment]
I think this is a good change for DITA-OT 4.0. The markup itself is being removed from the upcoming DITA 2.0 standard; the TC solicited input to see if anyone was using the domain and was not able to find any use. In my own searching, the only instances I could find were in test buckets just exercising the markup, but no use in actual content.

Leaving it in the code is messy, as it hard-codes references to an external plugin that is not getting as much use. I like the idea of cleaning up the code and removing this (just as I supported removing the markup from DITA 2.0).
