### ISSUE TITLE
Publishing speed slower with Java 17 than with Java 1.8 [Windows]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3932]
## Expected Behavior
I publish on Windows a large (about 2000 topics) DITA Map to HTML5 with default settings:
https://github.com/oxygenxml/userguide/blob/master/DITA/UserManual.ditamap
With both Java 17 and 1.8 they should get published in about the same time.

This continues on this comment I added here some time ago: https://github.com/dita-ot/dita-ot/issues/3621#issuecomment-720276269

## Actual Behavior
With Java 1.8 it gets published in about 253 seconds, with Java 17 it gets published in about 400 seconds.

## Possible Solution
- Set the **-Dsun.io.useCanonCaches=true** system property in the dita script file which starts the Java process. There was a [change in Java 12](https://bugs.openjdk.java.net/browse/JDK-8207005 ) which changed default for the cache to `false`. As the DITA OT works intensively with files, enabling this property seems to make a big difference and remove this large publishing time difference between Java 1.8 and 17..
- Setting `store-type=memory` as a parameter also helps as a workaround to reduce the publishing time with Java 17.

## Steps to Reproduce

1. Download https://github.com/oxygenxml/userguide
2. Publish "DITA/UserManual.ditamap" to HTML5 using default params and Java 17
3. Publish "DITA/UserManual.ditamap" to HTML5 using default params and Java 8
4. Compare publishing times

## Environment
 Windows, Java 17 Eclipse Adoptium

* DITA-OT version: 3.7
* Operating system and version:
  Windows
* How did you run DITA-OT?
  _(`dita` command)_
* Transformation type:
  _(HTML5.)_

**Comment by jelovirt** [comment]
@raducoravu Could you open a PR that adds `-Dsun.io.useCanonCaches=true` to [`dita.bat`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/bin/dita.bat#L60)?

**Comment by raducoravu** [comment]
@jelovirt Yes, I can open a pull request after [#3926](https://github.com/dita-ot/dita-ot/pull/3926) gets accepted as I forgot to create a separate branch for the grammar cache pull request so I right now have modifications directly in my cloned DITA-OT project's "develop" branch.

**Comment by chrispy-snps** [comment]
I was curious about this `-Dsun.io.useCanonCaches=true` option, so I tried some experiments using this PowerShell script:

[run.ps1.zip](https://github.com/dita-ot/dita-ot/files/8801429/run.ps1.zip)

Should this option have an effect when specified on the `dita` command line? It didn't seem to make a difference for me (although the Java version certainly did):

![runtimes_file](https://user-images.githubusercontent.com/50950969/171077670-6dbb29fa-2ad3-4f68-abe2-eb710304e45c.svg)

Here is the `gnuplot` plot command that I used:

[plot.cmds.zip](https://github.com/dita-ot/dita-ot/files/8801446/plot.cmds.zip)

**Comment by raducoravu** [comment]
@chrispy-snps  the "-Dsun.io.useCanonCaches" is a Java VM parameter, it cannot be passed as a dita.bat command line parameter, you need to actually modify the dita.bat and add this **-Dsun.io.useCanonCaches=true** in the command line something like:

      "%_JAVACMD%" %ANT_OPTS% -Djava.awt.headless=true -Dsun.io.useCanonCaches=true  ...........

**Comment by chrispy-snps** [comment]
@raducoravu - thanks, this looks much better!

![runtimes_file](https://user-images.githubusercontent.com/50950969/171407461-2f24eff0-0904-4c20-85fd-b94fed0bcdbc.svg)

I use these CDF plots for visualizing noisy data because the Y=50% value provides a median to draw conclusions from, and the slope gives a good idea of variance and outliers.

**Comment by chrispy-snps** [comment]
@raducoravu, @jelovirt - here are the results on a 24-core linux box:

![runtimes_file_linux](https://user-images.githubusercontent.com/50950969/171898084-9d971e7e-afad-442e-b27e-a1151d5d20b4.svg)

There is still a benefit to the option, but not as significant as in Windows. Should we also set the parameter in the linux `dita` batch script?

**Comment by raducoravu** [comment]
@chrispy-snps @jelovirt for consistency sake maybe we could add the flag in both dita scripts. Even if it just shaves off a few seconds on Linux it still makes the processing more efficient and consumes less CPU resources.
