### ISSUE TITLE
DITA-OT 3.6 or above can't handle Input file of non-ASCII path.

### ISSUE THREAD

**Issue by yin-yang-alchemist** [dita-ot/dita-ot#3934]
## Expected Behavior

Input file of non-ASCII path should be processed properly.

## Actual Behavior

When the full path of input file contains non-ASCII characters, a fatal error occurs.
This behavior depends on DITA-OT version.

- 3.7.2 -> Failed
- 3.6.1 -> Failed
- 3.5.4 -> Success

## Possible Solution

Probably the direct cause of this error is the encoding of .job.xml file created in Temp directory.
The encoding of .job.xml file is Shift-JIS which is the default encoding of Japanese environment.

## Steps to Reproduce

1. Unzip the following sample to some directory.
2. run dita command `dita.bat -i .\サンプル\hierarchy.ditamap -f pdf`

[DITA-OT_non-ASCII_path_sample.zip](https://github.com/dita-ot/dita-ot/files/8849315/DITA-OT_non-ASCII_path_sample.zip)

## Copy of the error message, log file or stack trace

```
C:\Temp\DITA-OT_issue> C:\apl\dita-ot-3.7.2\bin\dita.bat -i .\サンプル\hierarchy.ditamap -f pdf
 [pipeline]  Error reported by XML parser: Invalid byte 1 of 1-byte UTF-8 sequence.
 [pipeline] Failed to transform document: Failed to transform document: org.xml.sax.SAXParseException; systemId: file:/C:/Users/lis74h/AppData/Local/Temp/temp20220607095738941/.job.xml; lineNumber: 1; columnNumber: 90; Invalid byte 1 of 1-byte UTF-8 sequence.
[i18n-preprocess] [Fatal Error] stage2.fo:86:159: XML document structures must start and end within the same entity.
Error: The following error occurred while executing this line:
C:\apl\dita-ot-3.7.2\plugins\org.dita.pdf2\build.xml:337: java.io.IOException: Failed to read document: XML document structures must start and end within the same entity.
```

.job.xml file in Temp directory: [job_xml.zip](https://github.com/dita-ot/dita-ot/files/8849398/job_xml.zip)

## Environment

* DITA-OT version: 3.7.2
* Operating system and version: Windows 10 21H2
* How did you run DITA-OT? dita command
* Transformation type: PDF

**Comment by raducoravu** [comment]
So this probably occurs only on Windows because on Mac and Linux the default platform encoding is UTF-8. This is kind of tricky to test, for example when I expand the zip you provided, the folder name is already broken. Also my Windows OS does not have Japanese locale.
@jelovirt looking in the DITA OT code, in the "Job" class this code should have forced UTF-8 encoding on the OutputStreamWriter constructor:

      try (Writer outStream = new BufferedWriter(new OutputStreamWriter(getStore().getOutputStream(jobFile.toURI())))) {

**Comment by raducoravu** [comment]
Oh, I think a workaround for this would be to open the "DITA-OT\bin\dita.bat" file, search in it for "-Djava.awt.headless=true " and add after it an extra parameter:

      -Dfile.encoding=UTF-8

**Comment by chrispy-snps** [comment]
Possibly related to #3870?

**Comment by raducoravu** [comment]
@chrispy-snps this is probably not related to #3870 which is about how coderef referenced content is read by the DITA OT.
