### ISSUE TITLE
Converting Markdown files containing Abbreviations fails

### ISSUE THREAD

**Issue by michael-nok** [dita-ot/dita-ot#3938]
## Expected Behavior
DITA-OT transformation of a DITAMAP file to Markdown should have succeeded.

Contents of `test.ditamap`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map id="ID0" title="None" rev="1-0">
    <topicref href="docs/index.md" format="markdown"/>
</map>
```

```
dita -i test.ditamap -o tmp -f markdown -v
```

## Actual Behavior

The transformation fails with the following error message:

`Error: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.abbreviation.Abbreviation`

## Steps to Reproduce

If the Markdown file contains an [Abbreviation](https://python-markdown.github.io/extensions/abbreviations/), something like the following, the transformation fails.

```
*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium
```

## Copy of the error message, log file or stack trace

```
[gen-list] Processing file:/tmp/docs/index.md
Error: Failed to run pipeline: No renderer configured for com.vladsch.flexmark.ext.abbreviation.Abbreviation
```

## Environment

* DITA-OT version: 3.7.2
* Operating system and version: Linux (EC2 instance)
* How did you run DITA-OT? `dita -i test.ditamap -o tmp -f markdown -v`
* Transformation type: Markdown

**Comment by raducoravu** [comment]
@michael-nok this issue should probably be added to the specific issues list for the Markdown DITA plugin: https://github.com/jelovirt/org.lwdita/issues

**Comment by michael-nok** [comment]
Move to https://github.com/jelovirt/org.lwdita/issues/100
