### ISSUE TITLE
`processing-role="resource-only"` does not cascade downward in map

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#3940]
## Expected Behavior
In a map, I have two versions of the same topic file (topic2.dita):

* The unpublished version is resource-only without a key definition.
* The published version is local with a key definition.

![wrong_ref](https://user-images.githubusercontent.com/50950969/173200395-46a20a9e-2ec3-4885-8f4a-16e6bcf6df97.svg)

When I have an `<xref>` to that key, the reference should resolve to the published version.

## Actual Behavior
The transformation creates a duplicate HTML5 file for the unpublished version, and the key-derived reference incorrectly points to that instead:

![wrong_ref_html](https://user-images.githubusercontent.com/50950969/173200403-7038557d-1897-429c-8ac2-0c80d33d1516.svg)

## Possible Solution
A workaround (but not a fix) is to add `@processing-role="resource-only"` to the unpublished `<topicref>` directly:

![wa](https://user-images.githubusercontent.com/50950969/173200411-9930cd98-2505-43dd-af44-ac21056de927.svg)

In this case, the HTML5 output is as expected:

![wa_html](https://user-images.githubusercontent.com/50950969/173200422-7a7fb828-a3fe-4253-aa9e-6198204bd332.svg)

## Steps to Reproduce
Testcase: [ditaot_wrong_ref.zip](https://github.com/dita-ot/dita-ot/files/8884518/ditaot_wrong_ref.zip)

To run: `dita -i map -f html5 -Dforce-unique=true`

## Environment

* DITA-OT version: 3.7.2
* Operating system and version: Linux
* How did you run DITA-OT? `dita` command
* Transformation type: `html5`

**Comment by chrispy-snps** [comment]
Using [`ditaot_save_preprocessing.pl`](https://github.com/chrispy-snps/DITA-ditaot-utilities), I found that the `topic2` keyref in topic1.dita is resolved to "topic2.dita" in `keyref`:

```
$ diff -r temp-05-branch-filter/topic1.dita temp-06-keyref/topic1.dita
7c7
<       <p>See also: <xref keyref="topic2"/>
---
>       <p>See also: <xref keyref="topic2" href="topic2.dita"/>
```

which is before the topic is uniquifed by `force-unique` in `copy-to`:

```
diff -r temp-06-keyref/map.ditamap temp-07-copy-to/map.ditamap
10c10
<    <topicref href="topic2.dita" keys="topic2"/>
---
>    <topicref href="topic2.dita" keys="topic2" copy-to="topic2_2.dita"/>
Only in temp-07-copy-to/: topic2_2.dita
```

I tried using `preprocess2`, but somehow three copies of the topic were created:

```
$ ls out
commonltr.css  commonrtl.css  index.html  topic1.html  topic2.html  topic2_2.html  topic2_3.html
```

**Comment by chrispy-snps** [comment]
When I explicitly add `@processing-role="resource-only"` to topic2:

```
    <topicgroup processing-role="resource-only">
        <topicref href="topic2.dita" processing-role="resource-only"/>
                                <!-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -->
    </topicgroup>
```

then `copy-to` does not duplicate the topic:

```
$ diff temp2-06-keyref/ temp2-07-copy-to/
$
```

Should `copy-to` be looking for `@processing-role="resource-only"` in ancestors of topic references too? Or does `@processing-role="resource-only"` not cascade downward in this way?

**Comment by raducoravu** [comment]
The processing-role seems to be a cascading attribute:
https://www.oxygenxml.com/dita/1.3/specs/archSpec/base/cascading-in-a-ditamap.html
so it should probably cascade down from the topicgroup to the topicrefs inside it.

**Comment by chrispy-snps** [comment]
This bug also causes duplicate search results in Oxygen WebHelp:

![image](https://user-images.githubusercontent.com/50950969/178108613-f21523bb-9c22-4f53-a63f-21835a7a81ae.png)

The duplicate copy of the topic opens with no WebHelp navigation (because it is not in the TOC). Here's a WebHelp testcase:

[3940_webhelp.zip](https://github.com/dita-ot/dita-ot/files/9077255/3940_webhelp.zip)

**Comment by raducoravu** [comment]
Looking in the class 
https://github.com/dita-ot/dita-ot/blame/develop/src/main/java/org/dita/dost/writer/ForceUniqueFilter.java

there is a TODO there " // FIXME: handle cascading" so indeed the processing-role cascading does not seem to be taken into account.

**Comment by antonyterrence** [comment]
[test_resource_only_attribute.zip](https://github.com/dita-ot/dita-ot/files/9104689/test_resource_only_attribute.zip)
Like Chris mentioned, processing-role="resource-only" set to a map reference does not cascade downwards. As a result, the processor crawls xrefs found in the resource-only files and generates html pages for them. In the attached sample, the test_resource_only_attribute.ditamap has a mapref to glossary.ditamap. The glossary.ditamap refers the rest_api.dita topic, which contains an xref to chapter_2.dita. chapter_2.dita is not referenced from the main map (test_resource_only_attribute.ditamap). When it is published to html, an html file for chatper_2.dita is created as well although the mapref has `@processing-role` set to `resource-only`.

**Comment by raducoravu** [comment]
@antonyterrence this issue initially described here occurs specifically when the "force-unique=true" parameter is used when publishing. Are you also using it?

**Comment by antonyterrence** [comment]
@raducoravu , no I am not using it. There seem to be many similar issues reported:
https://github.com/dita-ot/dita-ot/issues/2077
https://github.com/dita-ot/dita-ot/pull/2694
If the processing-rol=resource-only is used, it should cascade down and apply to all child references. dita-ot should not treat such references as normal and generate html files for them. Nor should crawl cross-references if the attribute is used. I am not an expert and am reporting this as a user.

**Comment by chrispy-snps** [comment]
The following XSLT template applied in `mapref` seems to work around the issue (for our source content, at least):

```
  <!-- work around DITA-OT #3940 (processing-role="resource-only" does not cascade downward in map) -->
  <xsl:template match="*[@processing-role = 'resource-only']//*[contains-token(@class, 'map/topicref')]">
    <xsl:copy>
      <xsl:attribute name="processing-role" select="'resource-only'"/>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
```

@antonyterrence - does the following DITA-OT plugin work around the issue for you?

[com.workaround.3940.zip](https://github.com/dita-ot/dita-ot/files/9174040/com.workaround.3940.zip)

**Comment by raducoravu** [comment]
@chrispy-snps I attempted to make some changes to the "ForceUniqueFilter" Java class to propagate the processing role and this seems to fix the problem in your original attached sample project. When the 3.7.4 hotfix branch is created maybe I can try to add a pull request for this.

**Comment by raducoravu** [comment]
@antonyterrence the fix I will propose here will be for @chrispy-snps 's initial project and it does not help with your case in which two topics refer to each other and they are both in resource-only context. That problem is more related to https://github.com/dita-ot/dita-ot/pull/2694 and seems to be removed if you set the "onlytopic.in.map=true" parameter in the transformation scenario.

**Comment by chrispy-snps** [comment]
Thanks @raducoravu! I will test the pull request on our production content when it's ready.

**Comment by raducoravu** [comment]
@chrispy-snps I opened the pull request with the proposed changes.

**Comment by chrispy-snps** [comment]
I think this issue can be closed as fixed.
