### ISSUE TITLE
Markdown keys and preprocess2

### ISSUE THREAD

**Issue by njmuck** [dita-ot/dita-ot#3946]
Markdown keys do not work in preprocess2 because we are ignoring the file set when processing topic keys.

Please add markdown to the topic-keyref target.
```xml
<target name="topic-keyref"
    unless="preprocess.keyref.skip"
    description="Resolve keyref">
    <pipeline message="Resolve keyref." taskname="keyref">
      <module class="org.dita.dost.module.KeyrefModule" parallel="${parallel}">
      <ditafileset format="dita"/>
      <ditafileset format="markdown"/>
      <param name="transtype" value="${transtype}"/>
      </module>
    </pipeline>
  </target>
```

**Comment by db4rr** [comment]
Hi! Bumping this issue as it is complicating our work with hybrid DITA/Markdown authoring.
Not having  <ditafileset format="markdown"/> select the markdown files is making it difficult for us to process source markdown files.
