### ISSUE TITLE
Conref to topic element is not resolved when publishing to HTML

### ISSUE THREAD

**Issue by DunaMariusCosmin** [dita-ot/dita-ot#3976]
## Steps to Reproduce
I publish the DITA map from this zip file [sample.zip](https://github.com/dita-ot/dita-ot/files/9198045/sample.zip) to HTML and the conref to topic element is not resolved into the output.

In the console I have the following messages: 
`   [conref] Loading stylesheet file:/D:/kitSite/Oxygen%20XML%20Editor%2024.1/frameworks/dita/DITA-OT3.x/plugins/org.dita.base/xsl/preprocess/conref.xsl
   [conref] Processing file:/C:/Users/cosmin_duna/Desktop/toDelete/sample/temp/html5/topic.dita
   [conref] An empty sequence is not allowed as the value of variable $first
   [conref] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the value of variable $first`

## Possible Solution
I checked into the "plugin:org.dita.base:xsl/preprocess/conrefImpl.xsl" file and the problem seems to be into the template that matches '*[@conref:orig-id]'.  In my case the "orig-id" variable is the id of a topic and the content ('content' variable) where this id is searched contains a list  of elements that skips the topic elements.
So, it seems to work if I change the "first" variable with this:
`<xsl:variable name="first" select="($topic//@conref:orig-id[. = $orig-id])[1]" as="attribute()"/>`

**Comment by raducoravu** [comment]
Looks like a side effect added by @jelovirt in #3736
