### ISSUE TITLE
 Transformation crashes if map element doesn't have class attribute

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3980]
With a topicref like this:

     <topicref href="topic.dita" rev="1.0"/>

publishing to Oxygen WebHelp responsive using force.unique throws a NPE:
   

     /.../plugins/org.dita.base/build_preprocess.xml:250: java.lang.NullPointerException
	at java.base/java.util.ArrayDeque.addFirst(ArrayDeque.java:286)
	at org.dita.dost.writer.ForceUniqueFilter.startElement(ForceUniqueFilter.java:60)

This appears to be a side effect from fixing this issue where the Stack was replaced with ArrayDeque which does not allow null values: [3750](https://github.com/dita-ot/dita-ot/issues/3750)

**Comment by jelovirt** [comment]
Javadoc for `Deque`:

> While Deque implementations are not strictly required to prohibit the insertion of null elements, they are strongly encouraged to do so. Users of any Deque implementations that do allow null elements are strongly encouraged not to take advantage of the ability to insert nulls.

So we should wrap the value in `Optional` instead of changing the  implementation to `LinkedList` that supports `null`.
