### ISSUE TITLE
The attribute "border-radius" is not suported in PDF2 plugin

### ISSUE THREAD

**Issue by Billy-102** [dita-ot/dita-ot#3984]
## Expected Behavior
I'm using customized pdf2 plugin and hope to apply the attribute "border-radius" into the styling of <codeblock> in final PDF output.

## Actual Behavior
I added the line:

```<xsl:attribute name="border-radius">5pt</xsl:attribute>```

in `custom.xsl` file.

## Copy of the error message, log file or stack trace

However, I got nothing changed in the PDF: 

![image](https://user-images.githubusercontent.com/94583069/183290632-3193b7b8-6d62-4806-9020-97dcf83b34b2.png)

## Possible Solution
I am wondering if the **FOP** formatter supports for such attribute ("border-radius"), or if there is **other approaches** to take the same effects in PDF. 

## Environment

* DITA-OT version: 
dita-ot-**3.7.0**
* Operating system and version: 
**Windows**
* How did you run DITA-OT?
 **`dita` command**
* Transformation type:
**PDF2**

**Comment by jelovirt** [comment]
[XSL FO 1.1](https://www.w3.org/TR/xsl11/) does not have property `border-radius`, thus you can't use it with PDF2.

**Comment by Billyshane** [comment]
BTW, which version has the property `border-radius` ?

**Comment by kirkilj** [comment]
The FOP docs describe that a FOP extension supports some form of border radius. You need to prefix its use with the fox: names pace. I haven't tested it,but I actually have a possible use case. See docs at https://xmlgraphics.apache.org/fop/2.7/extensions.html#rounded-corner. You'd probablywant to add the template/attribute-set changes to one of the FOP specific stylesheets.

**Comment by kirkilj** [comment]
The 2.7 FOP docs describe that a FOP extension supports some form of border radius. You need to prefix its use with the fox: namespace. I haven't tested it, but I actually have a possible use case - separating <troubleSolution> elements. See docs at https://xmlgraphics.apache.org/fop/2.7/extensions.html#rounded-corner. You'd probablywant to add the template/attribute-set changes to one of the FOP specific stylesheets. 

```
<fo:block-container margin="10 20pt 20pt 20pt">
          <fo:block border-style="solid" border-width="10" border-color="#00f" 
                           fox:border-radius="20pt" padding="20pt" text-align="center" margin-bottom="10pt"> 
               Circular corners are specified when 'border-radius' is set to a single value.  
               This value is the radius of the outer quadrant of the corner.
          </fo:block>
          <fo:block border-style="solid" border-width="10" border-color="#00f" 
                           fox:border-radius="20pt 40pt" padding="20pt" text-align="center" margin-bottom="10pt">
                 Quarter-ellipse corners can be generated by setting two values for the property.  
                 The first value is the radius in the Inline Progression Direction.  
                 The second value is the radius in the Block Progression Direction.
          </fo:block>
</fo:block-container> 
```

**Comment by Billyshane** [comment]
@kirkilj 
Thank you for your help. I have applied the property successfully!

**Comment by kirkilj** [comment]
I'm glad it helped. I tested it as well. I'm proposing using them to group cause/remedy pairs in DITA Troubleshooting topics.

**Comment by kirkilj** [comment]
@jelovirt , can you redisposition this issue so it's no longer tagged as Invalid?
