### ISSUE TITLE
Failed to import another Language_Code.xml for language-specified variables

### ISSUE THREAD

**Issue by Billyshane** [dita-ot/dita-ot#3987]
## Expected Behavior
Import another language-specified variables xml

## Actual Behavior
I typed:

```<import href="Language_Code.xml"/>```

but it did not work.

## Copy of the error message, log file or stack trace

I also tried:

```<include href="Language_Code.xml"/>```
or 
```<import src="Language_Code.xml"/>```
or
```<include src="Language_Code.xml"/>```

however, none of them works. So I am wondering how can I import an existed **Language_Code.xml** to use the language-specified variables?

## Environment

* DITA-OT version:
dita-ot-3.7.0
* Operating system and version:
Windows
* How did you run DITA-OT?
dita command
* Transformation type:
PDF2

**Comment by chrispy-snps** [comment]
@Billyshane - I'm not sure I understand what your situation is. Do you have a tiny testcase that illustrates the issue?

**Comment by jelovirt** [comment]
@Billyshane Where did you try to use `<import href="Language_Code.xml"/>`? In which file?

**Comment by Billyshane** [comment]
> @Billyshane - I'm not sure I understand what your situation is. Do you have a tiny testcase that illustrates the issue?

For example, the variables declared in **zh_CN.xml** can also be used in **zh.xml**, so I just want to import zh_CN.xml in zh.xml to publish the map with @xml:lang="zh" in order to use the same variables.

**Comment by Billyshane** [comment]
> @Billyshane Where did you try to use `<import href="Language_Code.xml"/>`? In which file?


As I described in the last reply, I tried to use `<import href="zh_CN.xml"/>` in zh.xml, is it illegal?

![image](https://user-images.githubusercontent.com/94583069/184117779-0f05ea11-0a35-4951-a1b3-22a6e66373cf.png)

**Comment by xephon2** [comment]
Have you read the docs? [Adding new strings](https://www.dita-ot.org/dev/topics/adding-new-strings.html)

**Comment by Billyshane** [comment]
> Have you read the docs? [Adding new strings](https://www.dita-ot.org/dev/topics/adding-new-strings.html)

Thank you for your guidance, I have made it included.
