### ISSUE TITLE
Relax possibility for named template to return an empty sequence

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3991]
I have quite a large project containing a large chunk of topicrefs.
At some point during processing the large chunked topic in the "html5.topics.common.inner" stage I get in the console the error:

     [xslt] An empty sequence is not allowed as the result of template related-links:result.reference
     [xslt] Failed to transform document: Failed to transform document: An empty sequence is not allowed as the result of template related-links:result.reference
     [xslt] Processing

and afterwards the HTML topic corresponding to the chunked file is incomplete, it's not even valid, it's missing most of its contents.

In this file `DITA-OT/plugins/org.dita.html5/xsl/reference.xsl` there is a template:

```xml
<xsl:template match="*[contains(@class, ' topic/link ')][@type='reference']" mode="related-links:result-group"
              name="related-links:result.reference" as="element()">
```

If I relax the `as="element()?"` to specify an optional element, the processing works and produces a large HTML document from the chunked topic, as it should.
Looking in all other XSLTs, all other templates named `related-links:result.reference` have `as="element()?"`

I might not be able to provide a sample project for this one.

**Comment by jelovirt** [comment]
Looks like a good backwards compatible fix for 3.7.3. @raducoravu Could you open a PR?
