### ISSUE TITLE
Customization i18n file cannot be imported in pdf2 plugin

### ISSUE THREAD

**Issue by Billy-102** [dita-ot/dita-ot#3998]
## Expected Behavior
I am using the pdf2 plugin customization folder to override the variables and attributes. I uncomment the lines under this line
```
<!-- I18N configuration override entries.-->
```
in the catalog.xml in customization folder and created the xml file accordingly. However, the xml file in customization/cfg/fo/i18n cannot override the original one in the plugin.

## Environment

* DITA-OT version: 3.x
* Operating system and version:
_Windows_
* How did you run DITA-OT?
_oXygen_
* Transformation type:
  _PDF_

**Comment by raducoravu** [comment]
Can you give more details about your purpose? What do you mean by "override the variables and attributes"? In what original file are those variables and attributes defined?
Maybe it would be useful if you attached a zip containing a small and minimal PDF customization plugin folder which can be used to reproduced the problem.
XML configuration files from the "plugins/org.dita.pdf2/cfg/fo/i18n" folder are used in this XSLT stylesheet "plugins/org.dita.pdf2/xsl/fo/i18n-postprocessImpl.xsl" for post processing the XSL-FO file.

There is also documentation about overriding variables from a PDF customization plugin:
https://www.dita-ot.org/3.7/topics/pdf-plugin-structure_common-vars.html

**Comment by Billy-102** [comment]
I have solved it. I have believed that we should uncomment the lines in catalog.xml in Customization folder at first. Finally I found that the overriding path has been defined in the build file, so I created the folder common/vars in Customization folder accordingly. And then, without uncommenting the uri lines in catalog.xml, I can copy the original i18n file to the newly created folder and modify it so that the override can be realized.











At 2022-09-05 12:26:12, "Radu Coravu" ***@***.***> wrote:

Can you give more details about your purpose? What do you mean by "override the variables and attributes"? In what original file are those variables and attributes defined?
Maybe it would be useful if you attached a zip containing a small and minimal PDF customization plugin folder which can be used to reproduced the problem.
XML configuration files from the "plugins/org.dita.pdf2/cfg/fo/i18n" folder are used in this XSLT stylesheet "plugins/org.dita.pdf2/xsl/fo/i18n-postprocessImpl.xsl" for post processing the XSL-FO file.

There is also documentation about overriding variables from a PDF customization plugin:
https://www.dita-ot.org/3.7/topics/pdf-plugin-structure_common-vars.html
