### ISSUE TITLE
Property 'args.html5.toc.class' does not work in HTML5 transformation

### ISSUE THREAD

**Issue by DTC-tobin** [dita-ot/dita-ot#4015]
Adding the property `args.html5.toc.class` to the properties file that I use when generating HTML5 output produces no corresponding @class attribute on the TOC <body> element.

I have the following line in my properties file:
`args.html5.toc.class = top_toc`

In the output log, the property is recognized and associated with the OUTPUTCLASS parameter:
```
html5.map.toc:
     ...
     [xslt] Set parameter OUTPUTCLASS to 'top_toc'
```

The XSL transforms appear to be looking for @outputclass on the <map> element, but the intermediate <map> element in the temp directory contains no such attribute:
```
<map xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot"
    xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" 
    cascade="merge" 
    class="- map/map " 
    ditaarch:DITAArchVersion="1.3" 
    domains="(map mapgroup-d) (topic abbrev-d) (topic delay-d) a(props deliveryTarget) (map ditavalref-d) (map glossref-d) (topic hazard-d) (topic hi-d) (topic indexing-d) (topic markup-d) (topic pr-d) (topic relmgmt-d) (topic sw-d) (topic ui-d) (topic ut-d) (topic markup-d xml-d)" 
    specializations="@props/deliveryTarget" 
    xml:lang="ja" 
    xtrc="map:1;5:20" 
    xtrf="file:/***.ditamap">
```

In the meantime, we can just manually add a @class attribute since it's just one file, but I hope this can be addressed in a future update.

Thanks
Michael T.

**Comment by chrispy-snps** [comment]
I think the `args.html5.toc.class` and `args.xhtml.toc.class` parameters might be an orphaned feature.

They are converted to Ant `OUTPUTCLASS` parameters in these files:

```
plugins/org.dita.html5/build_dita2html5.xml
199:        <param name="OUTPUTCLASS" expression="${args.html5.toc.class}" if:set="args.html5.toc.class"/>

plugins/org.dita.xhtml/build_dita2xhtml.xml
45:        <param name="OUTPUTCLASS" expression="${args.xhtml.toc.class}" if:set="args.xhtml.toc.class"/>
```

These `OUTPUTCLASS` parameters are passed from the Ant targets into these top-level stylesheets:

```
plugins/org.dita.xhtml/xsl/map2xhtml-cover.xsl
plugins/org.dita.html5/xsl/map2html5-cover.xsl
```

which through some imports call these leaf-level "cover"-named stylesheets:

```
plugins/org.dita.xhtml/xsl/map2htmtoc/map2htmlcoverImpl.xsl
plugins/org.dita.html5/xsl/cover.xsl
```

These "cover"-named stylesheets generate the TOC output files. But, the `@class` attribute in the `<body>` element creation makes no reference to the `OUTPUTCLASS` parameter.

The only stylesheet reference to an `OUTPUTCLASS` is in this single leaf-level stylesheet:

```
plugins/org.dita.xhtml/xsl/map2htmtoc/map2htmtocImpl.xsl
19:<xsl:param name="OUTPUTCLASS"/>   <!-- class to put on body element. -->
59:     <xsl:if test="string-length($OUTPUTCLASS) &gt; 0">
61:         <xsl:value-of select="$OUTPUTCLASS"/>
```

which is ultimately included by this top-level stylesheet:

```
plugins/org.dita.xhtml/xsl/map2htmltoc.xsl
10:<xsl:import href="plugin:org.dita.xhtml:xsl/map2htmtoc/map2htmtocImpl.xsl"/>
```

which is not called anywhere. It appears to be an orphaned stylesheet that is no longer used.

So I think the fix here would be in two parts:

1. Identify and remove orphaned stylesheet files.
2. Update the following files to apply the `OUTPUTCLASS` parameter:
   plugins/org.dita.xhtml/xsl/map2htmtoc/map2htmlcoverImpl.xsl
   plugins/org.dita.html5/xsl/cover.xsl

**Comment by DTC-tobin** [comment]
As a follow up, I discovered a super-simple workaround: set @outputclass on the <map> element. (I don't know why this didn't occur to me before...)

Though I think the issue should still be resolved, since the property _is_ documented. Either the functionality should be removed or handled along the lines that @chrispy-snps suggests.
