### ISSUE TITLE
PDF2 renders index entries in link text

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#4017]
When a link target includes index entries, PDF2 adds the text of the index entries to `<xref>` link text, whereas HTML5 output does not.

In the DITA-OT docs, there's a cross-reference that links to the transtype parameter:

```xml
<xref keyref="parameters-base/transtype"/>
```

The link target is stored in the generated topic `parameters-base.dita` and includes index entries:

```xml
<plentry id="transtype" importance="required">
  <pt><parmname>transtype</parmname><ph>
      <indexterm><parmname>transtype</parmname></indexterm>
      <indexterm>parameters
        <indexterm><parmname>transtype</parmname></indexterm></indexterm></ph></pt>
  <pd id="transtype.desc">Specifies the output format (transformation type).</pd>
</plentry>
```

When HTML5 output is generated, the link text is correct:

> This argument corresponds to the common parameter [transtype](https://www.dita-ot.org/dev/parameters/parameters-base.html#base__transtype).

But PDF output concatenates the index entries to the link text:

>  This argument corresponds to the common parameter [transtypetranstypeparameterstranstype](#) on page 93. 

## Environment

* DITA-OT version: 3.7.3
* Operating system and version: (most likely all)
* How did you run DITA-OT? `dita` command
* Transformation type: PDF

**Comment by chrispy-snps** [comment]
The output of `preprocess2` has the desired target text:

```
<?xml version="1.0" encoding="UTF-8"?>
<topic id="topic">
   <title>My Topic</title>
   <body>
      <p>See <xref href="#topic/dlentry-id" type="dlentry">Term</xref>.</p>
      <dl>
         <dlentry id="dlentry-id">
            <dt>Term<ph><indexterm>FINDME</indexterm></ph>
            </dt>
            <dd>Definition</dd>
         </dlentry>
      </dl>
   </body>
</topic>
```

so I guess `pdf2` is recomputing the target text somewhere downstream.

**Comment by infotexture** [comment]
@chrispy-snps Thanks, that detail is helpful.

**Comment by chrispy-snps** [comment]
@infotexture - the problem exists for other cross-reference targets too. I am hoping to have a fix soon.
