### ISSUE TITLE
Generating single html - root-chunk-override is not equivalent to setting chunk attribute on map root element

### ISSUE THREAD

**Issue by Billy-102** [dita-ot/dita-ot#4019]
## Expected Behavior
I set the "root-chunk-override" property as "to-content", in the **html5.init** target, to make the output one html containing all topics in the dita source.

## Actual Behavior
However, it still generates separated topic html files at the same time while it will only generate one single html when I set the **chunk** attribute to "to-content" in the ditamap source.

## Possible Solution
No possible solution currently.

## Steps to Reproduce
1. Go to org.dita.html5 plugin folder
2. Find build_dita2html5.xml file
3. Locate the html5.init target
4. Add the line: `<property name="root-chunk-override" value="to-content"/>`
5. Publish with html5 transtype

## Environment
* DITA-OT version: 3.7.0
* Operating system and version: Windows
* How did you run DITA-OT?
 `dita` command
* Transformation type:
 HTML5

**Comment by raducoravu** [comment]
I can reproduce the problem, possibly if someone were to investigate this further, in the "ChunkModule" Java class there is a "removeChunkSources(..)" method which should probably remove the source files which are chunked together. And this does not happen although the init(...) method in the same class seems to propagate the chunk override value to the map root.

**Comment by raducoravu** [comment]
Attaching a zip containing a small map and two topics for tests:
[flowers.zip](https://github.com/dita-ot/dita-ot/files/9751297/flowers.zip)

Coming back to this, there are now two ChunkModule classes, the new one for DITA 2.0 is located in "org.dita.dost.chunk.ChunkModule" and the older one in "org.dita.dost.module.ChunkModule".

The problem can be reproduced with a DITA 1.3 map, so the old "org.dita.dost.module.ChunkModule" implementation is used. And the problem is in the method "org.dita.dost.reader.ChunkMapReader.process(Document)" which should set the root chunk override on the root element before calling "readLinks(doc);".

if I were out of curiosity to change the DOCTYPE declaration of the DITA Map to make it 2.0:

     <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 2.x Map//EN" "map.dtd">

and then publish to HTML5 using the "root-chunk-override" param set to "combine", I get a NullPointerException instead:

     java.lang.NullPointerException: Cannot invoke "java.net.URI.resolve(java.net.URI)" because "chunk.src" is null
	at org.dita.dost.chunk.ChunkModule.rewriteLinks(ChunkModule.java:230)
	at org.dita.dost.chunk.ChunkModule.lambda$9(ChunkModule.java:193)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.dita.dost.chunk.ChunkModule.generateChunks(ChunkModule.java:188)
	at org.dita.dost.chunk.ChunkModule.processCombine(ChunkModule.java:85)
	at org.dita.dost.chunk.ChunkModule.execute(ChunkModule.java:52)

So there seem to be bugs in both implementations.

@jelovirt what's your opinion on this?

**Comment by Billy-102** [comment]
> Attaching a zip containing a small map and two topics for tests: [flowers.zip](https://github.com/dita-ot/dita-ot/files/9751297/flowers.zip)
> 
> Coming back to this, there are now two ChunkModule classes, the new one for DITA 2.0 is located in "org.dita.dost.chunk.ChunkModule" and the older one in "org.dita.dost.module.ChunkModule".
> 
> The problem can be reproduced with a DITA 1.3 map, so the old "org.dita.dost.module.ChunkModule" implementation is used. And the problem is in the method "org.dita.dost.reader.ChunkMapReader.process(Document)" which should set the root chunk override on the root element before calling "readLinks(doc);".
> 
> if I were out of curiosity to change the DOCTYPE declaration of the DITA Map to make it 2.0:
> 
> ```
>  <!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 2.x Map//EN" "map.dtd">
> ```
> 
> and then publish to HTML5 using the "root-chunk-override" param set to "combine", I get a NullPointerException instead:
> 
> ```
>  java.lang.NullPointerException: Cannot invoke "java.net.URI.resolve(java.net.URI)" because "chunk.src" is null
> at org.dita.dost.chunk.ChunkModule.rewriteLinks(ChunkModule.java:230)
> at org.dita.dost.chunk.ChunkModule.lambda$9(ChunkModule.java:193)
> at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
> at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
> at org.dita.dost.chunk.ChunkModule.generateChunks(ChunkModule.java:188)
> at org.dita.dost.chunk.ChunkModule.processCombine(ChunkModule.java:85)
> at org.dita.dost.chunk.ChunkModule.execute(ChunkModule.java:52)
> ```
> 
> This NPE comes probably from "org.dita.dost.chunk.ChunkModule.collectChunkOperations(URI, Element, List)" which has a commented out ** //.src(href)** when chunk is combine.
> 
> So there seem to be bugs in both implementations.
> 
> @jelovirt what's your opinion on this?

So, do you mean that we need to rewrite the java module?

**Comment by raducoravu** [comment]
I added the issue #4036 to look into the NPE obtained when using DITA 2.0 maps with "root-chunk-override" set to "combine".

**Comment by Billy-102** [comment]
Sorry, I have no knowledge about Java.



---- Replied Message ----
| From | Radu ***@***.***> |
| Date | 11/03/2022 22:34 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [dita-ot/dita-ot] Generating single html - root-chunk-override is not equivalent to setting chunk attribute on map root element (Issue #4019) |

@Billy-102 yes, the fix needs to be done in the Java org.dita.dost.reader.ChunkMapReader class this code:

    final Element root = doc.getDocumentElement();
    if (rootChunkOverride != null) {
        final String c = join(rootChunkOverride, " ");
        logger.debug("Use override root chunk \"" + c + "\"");
        root.setAttribute(ATTRIBUTE_NAME_CHUNK, c);
    }


should be moved 3 lines up before the call to "readLinks(doc);".
Do you have Java knowledge to check out the project, make the changes on your side and then re-build it?

I will try to find some time to create a pull request and a testcase for it but I'm not sure in what DITA OT version the fix will be included.

**Comment by Billy-102** [comment]
Thank you. Waiting for your pull request. And then I might test it in the version 3.7.x



---- Replied Message ----
| From | Radu ***@***.***> |
| Date | 11/03/2022 22:34 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [dita-ot/dita-ot] Generating single html - root-chunk-override is not equivalent to setting chunk attribute on map root element (Issue #4019) |

@Billy-102 yes, the fix needs to be done in the Java org.dita.dost.reader.ChunkMapReader class this code:

    final Element root = doc.getDocumentElement();
    if (rootChunkOverride != null) {
        final String c = join(rootChunkOverride, " ");
        logger.debug("Use override root chunk \"" + c + "\"");
        root.setAttribute(ATTRIBUTE_NAME_CHUNK, c);
    }


should be moved 3 lines up before the call to "readLinks(doc);".
Do you have Java knowledge to check out the project, make the changes on your side and then re-build it?

I will try to find some time to create a pull request and a testcase for it but I'm not sure in what DITA OT version the fix will be included.

**Comment by Billy-102** [comment]
@raducoravu  Thank you. I can see the commits in this site, but how can I apply this modification to my installed DITA-OT? I have never practiced such approach before.

**Comment by raducoravu** [comment]
@Billy-102 I suspect my changes will be part of DITA OT 4.0 which should be released sometime next week.

**Comment by Billy-102** [comment]
Ok, thank you.









在 2022-11-07 16:17:07，"Radu Coravu" ***@***.***> 写道：

@Billy-102 I suspect my changes will be part of DITA OT 4.0 which should be released sometime next week.
