### ISSUE TITLE
Improve the way emails are presented

### ISSUE THREAD

**Issue by DunaMariusCosmin** [dita-ot/dita-ot#4020]
I have the following DITA topic: 
![image](https://user-images.githubusercontent.com/23210284/195332713-fe678763-6da8-453b-87ff-0f7225c3215b.png)

I publish it to HTML5 and I obtain this: 
![image](https://user-images.githubusercontent.com/23210284/195337545-ae0049fc-0ba6-4fb8-ba90-eec4ae5a7483.png)

I expected that the "mailto:" prefix not be presented.  (the "mailto:" should be removed from the text inside the "a" element).

**Comment by robander** [comment]
I think this sounds like a reasonable enhancement request

**Comment by chrispy-snps** [comment]
I think the following changes would be good:

* In PDF and HTML deliverables, remove the `mailto:` prefix from the default target text.
* In HTML deliverables, suppress `target="_blank"` to avoid a blank browser tab from briefly appearing before the mail client opens.

I will look into a PR for these changes.
