### ISSUE TITLE
Syntax Diagram ID attribute doesn't propagate into HTML output

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#4021]
## Expected Behavior
If I have a DITA Topic with the following content: &lt;syntaxdiagram id="simple-syntaxdiagram">, the ID should be copied in the the final output.

## Actual Behavior
Currently no ID is present in the output file.

## Possible Solution
We could add a &lt;xsl:call-template name="setidaname"/> in org.dita.html5/xsl/syntax-braces.xsl (or at list setid).

## Steps to Reproduce

1. Create a syntaxdiagram in a topic
2. Run the dita -f html5 transformation on the topic
3. Inspect the output in the browser

## Environment

* DITA-OT version: 3.7.3
* Operating system and version: Windows
* How did you run DITA-OT? oXygen and dita command
* Transformation type: HTML5

**Comment by robander** [comment]
Is your test using the syntax diagram plugin to render the diagram with arrows and/or SVG diagrams?

I'm using out of the box 4.0, and cannot reproduce this on the HTML5 output. Input topic:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA 2.x Topic//EN" "topic.dtd">
<topic id="topicid">
    <title>test syntax 4021</title>
    <body>
        <p id="para">testing</p>
        <syntaxdiagram id="simple-syntaxdiagram">
            <groupchoice>
                <kwd>1</kwd>
                <kwd>2</kwd>
                <kwd>3</kwd>
            </groupchoice>
        </syntaxdiagram>
    </body>
</topic>
```

Output contains the diagram ID:
```
<div class="body">
  <p class="p" id="topicid__para">testing</p>
  <figure class="fig syntaxdiagram fignone" id="topicid__simple-syntaxdiagram">
...
```

**Comment by jlacour31** [comment]
Hi @robander ,

I tested with the following topic, it is the sample from DITA specs with an ID:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="topic_cdd_fm2_4vb">
    <title>Topic</title>
    <body>
        <syntaxdiagram id="simple-syntaxdiagram">
            <title>CopyFile</title>
            <groupseq><kwd>COPYF</kwd></groupseq>
            <groupcomp><var>input-filename</var><kwd>*INFILE</kwd></groupcomp>
            <groupseq><var>output-filename</var><kwd>*OUTFILE</kwd></groupseq>
            <groupchoice> <var>input-filename</var> <kwd>*INFILE</kwd></groupchoice>
            <groupchoice> <var>output-filename</var> <kwd>*OUTFILE</kwd></groupchoice>
        </syntaxdiagram>
    </body>
</topic>
```
I then tried to run the follwoing command: `dita -v -f html5 -i D:\syntax-diagram\map.ditamap -o D:\syntax-diagram\out\html5`
In the generated HTML topic, there's no ID:
```
<!DOCTYPE html
  SYSTEM "about:legacy-compat">
<html lang="en"><head><meta charset="UTF-8"><meta name="copyright" content="(C) Copyright 2022"><meta name="generator" content="DITA-OT"><title>Topic</title><link rel="stylesheet" type="text/css" href="commonltr.css"></head><body id="topic_cdd_fm2_4vb"><main role="main"><article role="article" aria-labelledby="ariaid-title1">
    <h1 class="title topictitle1" id="ariaid-title1">Topic</h1>
    <div class="body">
        <div class="fig syntaxdiagram">
            <h3>CopyFile</h3>
             <kbd><b>COPYF</b></kbd> 
             <var>input-filename</var><kbd><b>*INFILE</b></kbd> 
             <var>output-filename</var><kbd><b>*OUTFILE</b></kbd> 
             {  <var>input-filename</var> <kbd><b> | *INFILE</b></kbd> } 
             {  <var>output-filename</var> <kbd><b> | *OUTFILE</b></kbd> } 
        </div>
    </div>
</article></main></body></html>
```
I tried to run the command on both DITA-OT 3.7.4 and 4.0 without any differences.

**Comment by jlacour31** [comment]
But you're right, with your example the ID did copy in the HTML output.
It seems the `<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA 2.x Topic//EN" "topic.dtd">` change the behavior.

**Comment by robander** [comment]
Very odd / unexpected - but you're right, when I publish with that sample using the DITA 1.3 topic, I do not get the ID in HTML5 output.

**Comment by robander** [comment]
🤦 The `@class` values changed in DITA 2.0 for syntax elements. So, none of the syntax code is running on the DITA 2.0 topic - it's falling back to figures and divs, which do generate the IDs.

**Comment by robander** [comment]
opened PR to fix the issue; will need to handle the DITA 2.0 markup separately, it should use the same processing as 1.3 but that will not be for a patch
