### ISSUE TITLE
In `preprocess2`, `<glossref>` elements are ignored

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#4026]
## Expected Behavior
When a `<glossref>` element is used:

![4026](https://user-images.githubusercontent.com/50950969/197647643-8d13b945-787d-438c-aebe-a4eee1c29105.svg)

it should be processed as a convenience specialization of `<topicref>`.

## Actual Behavior
When `preprocess2` is used, the `map-reader` stage discards `<glossref>` elements. As a result, `mapref` and other downstream stages never process the referenced content.

## Possible Solution
Update the `map-reader` stage to preserve `<glossref>` elements.

(Are there other specializations of `<topicref>` to be handled? What about user specializations of `<topicref>`?)

## Steps to Reproduce
1. Download the following testcase:
   [preprocess2-glossref.zip](https://github.com/dita-ot/dita-ot/files/9855907/preprocess2-glossref.zip)
2. Run the following command:
   `dita -i map.ditamap -f pdf2 -verbose`

## Copy of the error message, log file or stack trace
The reference to the term defined in the `<glossref>` topic is unresolved:

```
   [keyref] file:/mnt/c/nobackup/2773/topic.dita:7:42: [DOTJ047I][INFO] Unable to find key definition for key reference "term2-key" in root scope. The href attribute may be used as fallback if it exists
```

## Environment
* DITA-OT version: 3.7.3
* Operating system and version: Linux, Ubuntu 20.04 LTS
* How did you run DITA-OT? `dita` command
* Transformation type: `pdf2`

**Comment by ruthrapr** [comment]
Hi @chrispy-snps ,

With print="yes" it's working, related issue: #3328 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
  <title>test</title>
  <topicref href="topic.dita"/>
  <topicref keys="term1-key" href="term1.dita"/>
  <glossref keys="term2-key" href="term2.dita" print="yes"/>
</map>
```

**Comment by chrispy-snps** [comment]
@ruthrapr - thank you for linking that issue!

Indeed, in the Attributes section of [3.14.2.2 <glossref>](https://docs.oasis-open.org/dita/dita/v1.3/os/part2-tech-content/langRef/technicalContent/glossref.html), it says:

>@print
>    Specifies whether the topic should be included in a print-specific rendition, such as PDF. **On this element the value defaults to "no".**

which explains this behavior perfectly. I am closing this issue as not-a-bug.
