### ISSUE TITLE
Keyref on longdescref element inside image is not resolved to an href

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4071]
Started from:
https://www.oxygenxml.com/forum/viewtopic.php?p=68639#p68639

Let's say I have an image element with a longdescref inside it having a keyref:

    <image href="image.jpg">
      <longdescref keyref="targetKey"/>
    </image>

I publish the DITA Map to HTML5, look in the temporary files folder at the temp DITA topic and it does not contain an @href on the &lt;longdescref> element.

As a possible suggested fix in this field org.dita.dost.writer.KeyrefPaser.keyrefInfos probably an extra definition needs to be added:

    ki.add(new KeyrefInfo(TOPIC_LONGDESCREF, ATTRIBUTE_NAME_HREF, false, false));

**Comment by Koushik9020** [comment]
If possible can you also provide the same fix for this dita-ot-1.8.5 version also , as this fix is very crucial for our business needs. As we have a roadmap of using the latest version of dita-ot sometime later after this year.

**Comment by chrispy-snps** [comment]
I made a testcase to test all the standard DITA elements that support `@keyref`:

[4071.zip](https://github.com/dita-ot/dita-ot/files/10172225/4071.zip)

Using [`ditaot_save_preprocessing.pl`](https://github.com/chrispy-snps/DITA-ditaot-utilities#using-ditaot_save_preprocessingpl), I confirmed that `<longdescref>` is the only element that is missing support.

**Comment by infotexture** [comment]
Fixed by https://github.com/dita-ot/dita-ot/pull/4080.
