### ISSUE TITLE
[MDITA] # Title {.concept} is rendered literally as Title {.concept} in PDF

### ISSUE THREAD

**Issue by mkarg** [dita-ot/dita-ot#4129]
## Expected Behavior
`# Title {.concept}` should be rendered as `Title` in PDF.

## Actual Behavior
`# Title {.concept}` is rendered literally as `Title {.concept}` in PDF.

## Possible Solution
A workaround is to not use `{.concept}`.

## Steps to Reproduce
Render PDF from a ditamap which references one Markdown file starting with `# Title {.concept}`.

## Environment
DITA-OT 3.7.4, Windows, PDF

**Comment by jelovirt** [comment]
Which `@format` are you using? `mdita` doesn't support attribute lists; only `markdown` supports attribute lists.

**Comment by mkarg** [comment]
Thank you, Jarno, for this clarification. Indeed I am using `mdita` and was unaware that `{.concept}` is only supported for `markdown` but not for `mdita`. Closing this as invalid. Sorry for the confusion.
