### ISSUE TITLE
Logging the deliverable ID

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#4143]
## Description
It would be very useful to log the deliverable ID to identify the current deliverable. This is necessary when publishing multiple deliverables in a row, so when using a multi-deliverable DITA-OT project file.

## Possible Solution
The most simple solution is probably to log it in `log-arg`.

## Potential Alternatives
Even better it would be to prefix all error messages with the deliverable ID, this would help if the publishing does not run in verbose or debug mode.

## Additional Context
–

**Comment by raducoravu** [comment]
My colleague @DunaMariusCosmin has a pull request for this: https://github.com/dita-ot/dita-ot/pull/4100
The DITA OT bundled with Oxygen 25.1 will contain this improvement so that every error reported in the Problems list when running a DITA OT project will contain as a prefix the deliverable ID.

**Comment by xephon2** [comment]
@raducoravu, could you please merge #4100, so that the codes is shipped with the next point release? It would be very useful for us to have this functionality in the "normal" DITA-OT as well (not "only" in the Oxygen Publishing engine).

**Comment by raducoravu** [comment]
@xephon2 maybe you can comment on the pull request, I am not the one to decide if a PR should be merged or not.

**Comment by chrispy-snps** [comment]
I would also like to see #4100 merged.

**Comment by chrispy-snps** [comment]
Here is a testcase: [4100.zip](https://github.com/dita-ot/dita-ot/files/14972588/4100.zip)

It has all four combinations of deliverable names and/or IDs:

```
$ grep '<del' project.xml
  <deliverable>
  <deliverable name="Deliverable description goes here">
  <deliverable id="del-id-1">
  <deliverable name="Deliverable description goes here" id="del-id-2">
```
