### ISSUE TITLE
Techcomm includes still reference the non-pubid URNs

### ISSUE THREAD

**Issue by takesson** [dita-ot/dita-ot#4144]
## Expected Behavior
Includes in techcomm.v2_0 rng files should resolve to org.oasis-open.dita.v2_0 rng files via catalog.xml

## Actual Behavior
The resolver will fail to resolve includes like:
```
<include href="urn:oasis:names:tc:dita:rng:topicMod.rng:2.0">
```

## Possible Solution
Update techcomm.v2_0 equivalent to #4040 

## Steps to Reproduce
Just an example with trang and the resolver. I am not yet sure if this impacts DITA-OT use of jing.

1. cp lib/xml-resolver-1.2.jar . resolver.jar
2. java -jar trang.jar -C plugins/org.oasis-open.dita.techcomm.v2_0/catalog.xml  plugins/org.oasis-open.dita.techcomm.v2_0/rng/technicalContent/ditabase.rng trang-out/ditabase.rnc

## Copy of the error message, log file or stack trace
fatal: exception "java.net.MalformedURLException" thrown: unknown protocol: urn

## Environment

* DITA-OT version: 4.0.2
* Operating system and version: macOS
* How did you run DITA-OT? Tested with external tool.
* Transformation type: N/A

**Comment by takesson** [comment]
@robander The includes in https://github.com/oasis-tcs/dita-techcomm where never updated with the 'pubid' addition. I am not sure what the plan is?

**Comment by robander** [comment]
Starting the update: https://github.com/oasis-tcs/dita-techcomm/pull/228
