### ISSUE TITLE
dita2htmlhelp.init: Triggers DOTA015F by setting preprocess.copy-image.skip=true

### ISSUE THREAD

**Issue by bird2tori** [dita-ot/dita-ot#4181]
## Expected Behavior
No fatal error DOTA015F

## Actual Behavior
Triggers DOTA015F.

## Possible Solution
As DOTA015F says, change  `<property name="preprocess.copy-image.skip" value="true"/>` to `<property name="build-step.copy-image" value="false"/>`.

## Steps to Reproduce
We get this with 4.0.2 when using --format=htmlhelp.

## Copy of the error message, log file or stack trace
preprocess2.init:
[pathconvert] Set property dita.map.filename.root = UserManual
     [echo] *****************************************************************
     [echo] * input = E:\vbox\3vn\trunk\out\win.amd64\debug\obj\manual\en_US\dita\UserManual.ditamap
Property "args.resources" has not been set
     [echo] * resources = ${args.resources}
     [echo] *****************************************************************
Property "build-step.branch-filter" has not been set
Property "build-step.chunk" has not been set
Property "build-step.clean-preprocess" has not been set
Property "build-step.clean-preprocess" has not been set
Property "build-step.coderef" has not been set
Property "build-step.conref" has not been set
Property "build-step.copy-flag" has not been set
Property "build-step.copy-html" has not been set
  [antcall] Exiting E:\vbox\3vn\trunk\tools\common\dita-ot\v4.0.2-r1\build.xml.
Error: The following error occurred while executing this line:
E:\vbox\3vn\trunk\tools\common\dita-ot\v4.0.2-r1\plugins\org.dita.base\build_init.xml:52: [DOTA015F][FATAL] Internal property preprocess.copy-image.skip may not be set directly. Use property build-step.copy-image instead.

## Environment

* DITA-OT version: 4.0.2
* Operating system and version: Windows 11
* How did you run DITA-OT? Directly via java.exe, but same a dita.bat.
* Transformation type: htmlhelp

**Comment by raducoravu** [comment]
Similar with: https://github.com/jelovirt/com.elovirta.ooxml/issues/101
