### ISSUE TITLE
Circular `<xref>` references inside `<shortdesc>` causes infinite XSLT recursion during `topicpull` target text computation 

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#4184]
## Expected Behavior
According to the DITA content models, an `<xref>` inside a `<shortdesc>` is allowed and thus should not interfere with publishing:

```
<!-- topic1.dita -->
<topic>
  <title>Feature 1</title>
  <shortdesc>This is feature 1, which works together with <xref keyref="feature2"/>.</shortdesc>
  ...
</topic>

<!-- topic2.dita -->
<topic>
  <title>Feature 2</title>
  <shortdesc>This is feature 2, which works together with <xref keyref="feature1"/>.</shortdesc>
  ...
</topic>
```

## Actual Behavior
If there is a circular reference loop across topic `<shortdesc>` elements (such as in the example above), infinite XSLT recursion occurs when `topicpull` attempts to resolve the `<xref>` target text:

```
[topicpull] Too many nested template or function calls. The stylesheet may be looping.
[topicpull] Failed to transform document: Failed to transform document: Too many nested template or function calls. The stylesheet may be looping.

[topicpull] Too many nested function calls. May be due to infinite recursion.
[topicpull] Failed to transform document: Failed to transform document: [topicpull] Too many nested function calls. May be due to infinite recursion.
```

We found this issue when converting our specialized topic-summary element into `<shortdesc>` elements. Some of our summaries mentioned related features using `<xref>` elements.

Even when the references aren't circular, unnecessarily nested `<desc>` elements can result. Given the following linear sequence of `<shortdesc>` references:

```
<!-- topicW.dita -->
<shortdesc>This is feature W, which works together with <xref keyref="featureX"/>.</shortdesc>

<!-- topicX.dita -->
<shortdesc>This is feature W, which works together with <xref keyref="featureY"/>.</shortdesc>

<!-- topicY.dita -->
<shortdesc>This is feature W, which works together with <xref keyref="featureZ"/>.</shortdesc>

<!-- topicZ.dita -->
<shortdesc>This is feature Z.</shortdesc>
```

the `topicpull` processing for topicW.dita is:

```
<shortdesc>This is feature W, which works together with
  <xref keyref="featureX" href="topicX.dita" type="topic">Feature X
    <desc>This is feature X, which works together with
      <xref keyref="featureY" href="topicY.dita" type="topic">Feature Y
        <desc>This is feature Y, which works together with
          <xref keyref="featureZ" href="topicZ.dita" type="topic">Feature Z
            <desc>This is feature Z.</desc>
          </xref>.
        </desc>
      </xref>.
    </desc>
  </xref>.
</shortdesc>
```

## Possible Solution
Not sure yet.

## Steps to Reproduce
1. Download and extract the following testcase: [4184.zip](https://github.com/dita-ot/dita-ot/files/11401087/4184.zip)
2. Run a transformation on map.ditamap (any type).

## Environment
* DITA-OT version: 4.0.2
* Operating system and version: Linux
* How did you run DITA-OT? `dita` command
* Transformation type: any type that runs `preprocess` or `preprocess2`

**Comment by infotexture** [comment]
@chrispy-snps I wonder if there's something specific to your case that causes this to happen. 🤔 

We have [keyreffed cross-references in short descriptions in the DITA-OT docs](https://github.com/dita-ot/docs/blob/develop/topics/markdown-input.dita#L6-L8), and haven't had problems with them yet.

**Comment by infotexture** [comment]
That ↑ said, I was able to reproduce the error with the attached files.

**Comment by chrispy-snps** [comment]
@infotexture - thanks, this was an important clue! It looks like the issue only occurs when there is a loop of topics that reference each other. In this case, feature 1's `<shortdesc>` references feature 2, and feature 2's `<shortdesc>` references feature 1. When I break the reference loop, the issue no longer occurs.
