### ISSUE TITLE
Branch filtering override does not work

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#4191]
## Expected Behavior

Usually, if you have a normal DITAVAL filtering, you can specify a default rule and override it, for example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<val>
  <prop action="exclude" att="audience"/>
  <prop action="include" att="audience" val="expert/>
</val>
```

Unfortunately this does not work, when you use branch filtering. I tried to have the default rule in my `main.ditaval` and override the default rule in my `expert.ditaval` (branch filtering):

**main.ditaval**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<val>
    <prop action="exclude" att="audience"/>
</val>
```

**expert.ditaval**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<val>
    <prop action="include" att="audience" val="expert"/>
</val>
```

**branch-filtering-override2.ditamap**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="urn:oasis:names:tc:dita:rng:map.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<map>
    <title>Branch Filtering Override</title>
    <topicref href="topic1.dita"/>
    <topicref href="topic2.dita" audience="expert"/>
    <topicref href="topic3.dita" audience="expert">
        <ditavalref href="expert.ditaval"/>
    </topicref>
</map>
```

## Actual Behavior
The filtered topics are not rendered, so the default rule is applied. 

## Possible Solution

No idea.

## Steps to Reproduce

Download the test files [branch-filtering-override2.zip](https://github.com/dita-ot/dita-ot/files/11441272/branch-filtering-override2.zip) and publish the deliverable from the DITA-OT project file.
## Environment

* DITA-OT version: 3.6.0, 3.7.4
* Operating system and version: Windows 10
* How did you run DITA-OT? oXygen
* Transformation type: pdf2

**Comment by chrispy-snps** [comment]
@xephon2 - in [2.4.4.1 Overview of branch filtering](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/base/branch-filtering-overview.html#branch-filter-overview), it says:

> Using `<ditavalref>` elements, it is possible to specify one set of conditions for a branch and another set of conditions for a subset of the branch. As with global conditions, properties set to "exclude" for a map branch override any other settings for the same property specified for a subset of the branch.

I believe the intent is that if some content contains branch-filtered excluded content in it, you cannot accidentally re-include that content from a higher level, where that higher level could be either branch filtering or global filtering.

See #4094 for some related reading.

**Comment by xephon2** [comment]
Thanks, @chrispy-snps , I missed this statement. This means, the case is specified, the OT works according to the spec and this issue can be closed.
