### ISSUE TITLE
gradlew fails with Java versions newer than 17

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#4196]
## Expected Behavior
According to the [DITA-OT prerequisites](https://github.com/dita-ot/dita-ot/#prerequisites-java-17), Java versions newer than version 17 should be usable to build the DITA-OT:

> To build and run DITA-OT, you’ll need Java Development Kit (JDK), version 17 or newer.

## Actual Behavior
When OpenJDK 18 is used, the initial `gradlew` command fails with the following error:

```
* What went wrong:
Could not compile settings file '/home/chrispy/git/dita-ot/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 62
```

When OpenJDK 19 is used, a similar error occurs:

```
* What went wrong:
Could not compile settings file '/home/chrispy/git/dita-ot/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63
```

## Possible Solution
If this is a known limitation, the prerequisites statement should be updated.

## Steps to Reproduce
1. Install OpenJDK 19:
   `sudo apt install openjdk-19-jdk`
2. Select version 19:
   `sudo update-alternatives --config java`
3. In a clone of the DITA-OT development repository, build the DITA-OT:
   `rm -rf ~/.gradle && git clean -fdx && ./gradlew`

## Copy of the error message, log file or stack trace
```
$ ./gradlew
Downloading https://services.gradle.org/distributions/gradle-7.2-bin.zip
..........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.2!

Here are the highlights of this release:
 - Toolchain support for Scala
 - More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior

For more details see https://docs.gradle.org/7.2/release-notes.html

Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/chrispy/git/dita-ot/settings.gradle'

* What went wrong:
Could not compile settings file '/home/chrispy/git/dita-ot/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63

  java.lang.IllegalArgumentException: Unsupported class file major version 63
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
...omitted...
```

## Environment
* DITA-OT version: `develop` branch
* Operating system and version: Ubuntu 22.04 LTS

**Comment by kirkilj** [comment]
what happens when you try a more recent version of Gradle, such as 8.x?

**Comment by chrispy-snps** [comment]
@kirkilj - I'm not sure how I would use a different version than what's included with the DITA-OT repository. I usually just clone it and run the `./gradlew` wrapper script in the root directory.

**Comment by jelovirt** [comment]
Can't reproduce this on a Mac.

**Comment by jelovirt** [comment]
Reproduced with Docker image `docker:22.04`.

**Comment by jelovirt** [comment]
@infotexture are you able to test if docs build will work with Gradle 7.6.1. We could update Gradle in both core and docs repos for 4.1 release.

**Comment by infotexture** [comment]
✅ @jelovirt Yes, bumped both wrappers locally and tested docs distribution build.

Still works fine with OpenJDK 17, so no regressions. Didn't test with Java 18 or 19, but since Gradle 7.6 adds support for Java 19, we should be fine.

I'll submit PRs with the wrapper changes for both repos.
