### ISSUE TITLE
Branch filtering does not work on ,`<mapref>`s, must use `<topicref>`s instead

### ISSUE THREAD

**Issue by darrenn-jackson** [dita-ot/dita-ot#4208]
## Expected Behavior
According to the [spec](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/base/mapref.html#mapref), a `<mapref>` is identical to a `<topicref>` element with the `@format` attribute set to `"ditamap"`

As a result I'd expect the following ditamap to correctly omit in the output the submap content that has profiling attributes applied and that are excluded via the referenced ditaval file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map id="combined">
    <title>Title</title>
    <topicref href="index.md" format="markdown"/>
    <topichead>
       <topicmeta>
          <navtitle>Install the Software</navtitle>
       </topicmeta>
       <mapref href="install_guide.ditamap">
          <ditavalref href="combo.ditaval"/>
       </mapref>
    </topichead>   
    <mapref href="admin_guide.ditamap"/>
</map>
```

## Actual Behavior
DITA-OT returns the following error: 

```
Error: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'file:MY_DOCS_PATH/combined.ditamap'.: file:MY_DOCS_PATH/combined.ditamap Line 12:The content of element type "mapref" must match "(topicmeta?,(data|sort-as|data-about)*)".
```

This forces me to change that first `<mapref>` to a `<topicref>` in order to transform without errors:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map id="combined">
    <title>Title</title>
    <topicref href="index.md" format="markdown"/>
    <topichead>
       <topicmeta>
          <navtitle>Install the Software</navtitle>
       </topicmeta>
       <topicref href="install_guide.ditamap" format="ditamap">
          <ditavalref href="combo.ditaval"/>
       </topicrefref>
    </topichead>   
    <mapref href="admin_guide.ditamap"/>
</map>
```

This workaround not only completes successfully, but also correctly applies the branch filtering on the submap.

**There is a chance that this is cause by some company-specific DITA-OT plugins I have installed**

## Possible Solution

Maybe process `<mapref>` elements exactly the same way as `<topicref>` elements whose `@format` is set to `"ditamap"`?

## Steps to Reproduce

I ran into this while working on a public repo, so you can use that to reproduce:

1. Clone `git@github.com:Cray-HPE/docs-uan.git` 
2. Verify that DITA-OT 4.0.2 and the LwDITA plugin are installed.
3.  Within the `docs-uan/docs/portal/developer-portal` subdir, run `dita -i uan_combined.ditamap -o build/ -f html5`
4. Note successful transform
5. Change the `<topicref>` in that ditamap to a `<mapref>`
6. Repeat Step 2
7. Note error message

## Copy of the error message, log file or stack trace

Error message is pasted above.

## Environment

* DITA-OT version: _4.0.2_
* Operating system and version:
  _Linux_
* How did you run DITA-OT?
  _`dita` command_
* Transformation type:
  _HTML5 and ReadTheDocs tested_

**Comment by darrenn-jackson** [comment]
Thanks @robander and @chrispy-snps  for providing the explanation. This does make sense to me. I should have checked the actual content model instead of relying solely on the verbal description in the spec. 

Any chance that the verbal description of `<mapref>` in the spec can be corrected in 1.3 and/or improved in 2.0?

**Comment by chrispy-snps** [comment]
@darrenn-jackson - you could send a request to the OASIS DITA technical committee ([dita-comment@lists.oasis-open.org](mailto:dita-comment@lists.oasis-open.org)). Note that this email address is for formal requests; all communication is recorded, posted, and archived.

**Comment by chrispy-snps** [comment]
@darrenn-jackson - are you able to close this issue as expected behavior? (I would also like to see `<ditavalref>` be valid in `<mapref>` in a future OASIS DITA standard, if possible.)

**Comment by darrenn-jackson** [comment]
I'll close this because the it's not a DITA-OT bug, nor is it a problem with the DITA schema. It's just that I went with the verbal description instead of the content model for this element defined in the spec.
