### ISSUE TITLE
Missing XML catalog entry for lwdita schemas

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4233]
This XMl catalog `org.oasis-open.xdita.v0_3_0\catalog-dita.xml` refers to this non existing module:
```xml
<public publicId="-//OASIS//ELEMENTS XDITA Highlight Domain//EN" uri="dtd/highlightDomain.mod"/>
```

**Comment by robander** [comment]
Fixed the catalog in the lwdita repo: https://github.com/oasis-tcs/dita-lwdita/pull/114

This should get picked up for our next update to the lwdita grammar
