### ISSUE TITLE
coredump with openjdk-17, but not with openjdk-17-zero, on Linux ARM64 (not amd64!)

### ISSUE THREAD

**Issue by weiwu-zhang** [dita-ot/dita-ot#4249]
## Reproduce Steps
1. Clone out the repository I'm working on: `git clone https://github.com/TokenScript/documents.git`
2. Checkout the version that has the problem: `git checkout 27e5205f349e6ef9b4de8e3b787cedf270819c23`
3. Run command `$ dita --project config/smartlayer-docsite.yaml` (you need html5-bootstrap)

Expected Behaviour

output from that command means success

## Actual Behavior
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff82ee26d4, pid=4392, tid=4410
#
# JRE version: OpenJDK Runtime Environment (17.0.7+7) (build 17.0.7+7-Ubuntu-0ubuntu123.04)
# Java VM: OpenJDK 64-Bit Server VM (17.0.7+7-Ubuntu-0ubuntu123.04, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# V  [libjvm.so+0xa426d4]  PhaseIdealLoop::build_loop_late_post_work(Node*, bool)+0xf4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/weiwu/Projects/documents/core.4392)
#
# An error report file with more information is saved as:
# /home/weiwu/Projects/documents/[hs_err_pid4392.log](https://github.com/dita-ot/dita-ot/files/12081829/hs_err_pid4392.log)
#
# Compiler replay data is saved as:
# /home/weiwu/Projects/documents/replay_pid4392.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
#
Aborted (core dumped)
```

## Possible Solution
This works:
```
$ apt-get purge openjdk-17-jrk
$ apt-get install openjdk-17-jre-zero
```

## Environment

* DITA-OT version: 4.1
* Operating system and version:
  _Ubuntu 23.04 ARM64_
* How did you run DITA-OT?
  _commandline, demonstrated in the steps_
* Transformation type:
  _HTML5_

[hs_err_pid4392.log](https://github.com/dita-ot/dita-ot/files/12081844/hs_err_pid4392.log)
[replay_pid4392.log](https://github.com/dita-ot/dita-ot/files/12081845/replay_pid4392.log)

**Comment by rrcomtech** [comment]
I'm also getting this issue.

#### Environment

- DITA-OT version: `4.0.2`
- Operating system and version: Docker Image `ubuntu:jammy` and `debian:bookworm`
- How did I run DITA-OT? 
_Docker setup, running in Jenkins Pipeline_
- Transformation Type: _XML_

**Comment by raducoravu** [comment]
Usually when the Java VM breaks with such core dumps, it's either a bug in the Java VM or some bad native function call from the Java code which is run inside the Java VM. 
I googled for "build_loop_late_post_work(Node*, bool)", there are various mentions of a crash like there:
https://github.com/adoptium/adoptium-support/issues/530
I do not see how the DITA Open Toolkit's Java code could be changed to prevent this, I consider this a bug in the Java VM.

**Comment by weiwu-zhang** [comment]
@rrcomtech I am guessing that @jelovirt meant you can help with the reproduction steps, because my original steps are already in the issue, and it's hard to reproduce due to arm64.

**Comment by weiwu-zhang** [comment]
@raducoravu I moved it to flexmark library. Thanks. https://github.com/vsch/flexmark-java/issues/585
