### ISSUE TITLE
HTML5: Teletype output contains inline style attributes

### ISSUE THREAD

**Issue by Jon-Hill-i2** [dita-ot/dita-ot#4254]
## Expected Behavior

When MDITA source contains text wrapped in backticks, the generated HTML output should contain either `<span>` elements with appropriate class attributes, or `<tt>` elements as described in the release notes.

## Actual Behavior

In the situation described above, the generated HTML contains inline style attributes, so that (for example)

```
`backticks`
```

in the MDITA source becomes

```
<span class="ph tt" style="font-family: monospace">backticks</span>
```

in the HTML output. This appears to contradict the explanation in the release notes, which goes like this:

> Standard Markdown syntax can now be used to indicate a span of code by wrapping it with backtick quotes (`). In Markdown DITA input, these constructs are converted to DITA \<codeph\> elements on import, and rendered as \<code\> elements in HTML output. In MDITA input, this syntax is converted to teletype \<tt\> elements to align with LwDITA, which supports teletype highlighting in XDITA.

## Possible Solution

Unknown

## Steps to Reproduce

The attached [`demo.zip`](https://github.com/dita-ot/dita-ot/files/12215053/demo.zip) file contains source and output that demonstrates the problem.

## Copy of the error message, log file or stack trace

N/A

## Environment

* DITA-OT version: 4.1.1
* Operating system and version: Windows 10 version 22H2
* How did you run DITA-OT? `dita` command
* Transformation type: HTML5

**Comment by jelovirt** [comment]
> In MDITA input, this syntax is converted to teletype <tt> elements to align with LwDITA

This means when MDITA is parsed, backtick code spans are parsed as `<tt>` elements. This means the transtype specific code will get a `<tt>` for transformation. In the case of HTML5 transtype, `<tt>` is converted into a HTML5 `<span>` element with classes. So there's no bug here, it's how HTML5 plug-in works. This is not related to MDITA, the same will happen with DITA input documents.

**Comment by jelovirt** [comment]
HTML5 plug-in doesn't generate HTML5 `<tt>` element for DITA `<tt>` element because the [HTML5 `<tt>` element is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt).

**Comment by Jon-Hill-i2** [comment]
> > In MDITA input, this syntax is converted to teletype `<tt>` elements to align with LwDITA
> 
> This means when MDITA is parsed, backtick code spans are _parsed_ as `<tt>` elements. This means the transtype specific code will get a `<tt>` for transformation. In the case of HTML5 transtype, `<tt>` is converted into a HTML5 `<span>` element with classes. So there's no bug here, it's how HTML5 plug-in works. This is not related to MDITA, the same will happen with DITA input documents.

Fair enough. Linking the problem with MDITA was my mistake. But I still think there's a problem here. The `<tt>` element _isn't_ just being converted to a `<span>` element with classes. It's being converted to a `<span>` element with classes _and_ a `style` attribute.

I don't think I've seen inline styles being used anywhere else in DITA-OT output. They're not CSS friendly. I think that generating them here is a bug.

**Comment by infotexture** [comment]
> The `<tt>` element _isn't_ just being converted to a `<span>` element with classes. 
> It's being converted to a `<span>` element with classes _and_ a `style` attribute.

@jelovirt This looks like a bug to me too, as we've previously removed other remnants of hard-coded styles per https://github.com/dita-ot/dita-ot/pull/3632#discussion_r525075485. 

I'll reopen (and rename) this, and prepare a PR to move the inline styling to the Sass partial for the highlighting domain like in #3632.
