### ISSUE TITLE
Different topicmeta/navtitle should keep their value even if the target file is the same

### ISSUE THREAD

**Issue by ruthrapr** [dita-ot/dita-ot#4275]
Hi, maybe this goes against the spec but I didn't find anything about it.

## Expected Behavior

In a ditamap, different `topicmeta/navtitle` should keep their value even if the target file (`@href`) is the same.

![expected-behavior](https://github.com/dita-ot/dita-ot/assets/28505803/7d5ffb28-5c0f-437a-a510-47f8d216c16b)

## Actual Behavior

Transformation (here HTML5, but I think it's related to preprocess) keeps the string of the first `navtitle` with the same `@href`

![actual-behavior](https://github.com/dita-ot/dita-ot/assets/28505803/8871606d-56bb-46aa-bd99-0cc4de4f6e71)

## Steps to Reproduce

Create a ditamap with several `topicmeta/navtitle` referencing the same file. Then, run a transformation (HTML5, PDF).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA Map//EN" "map.dtd">
<map>
    <title>Test map</title>
    <topicref href="test_navtitle.dita" locktitle="yes">
        <topicmeta>
            <navtitle>Navtitle 1</navtitle>
        </topicmeta>
    </topicref>
    <topicref href="test_navtitle.dita" locktitle="yes">
        <topicmeta>
            <navtitle>Navtitle 2 (using same href as previous)</navtitle>
        </topicmeta>
    </topicref>
    <topicref href="test_navtitle2.dita" locktitle="yes">
        <topicmeta>
            <navtitle>Navtitle 3 (using a different href)</navtitle>
        </topicmeta>
    </topicref>
</map>
```

## Environment

* DITA-OT version: 4.0.2
* Operating system and version: MacOS 13.2.1
* How did you run DITA-OT? oXygen 25.1
* Transformation type: HTML5, PDF

**Comment by raducoravu** [comment]
I think I agree with your expected result.
I see that if I set the "force-unique" publishing parameter to "true", as it will generate an unique HTML file for each topic instance, it also seems to fix this problem as well:
https://www.dita-ot.org/dev/parameters/parameters-base#base__force-unique

**Comment by ruthrapr** [comment]
Thanks @raducoravu, "force-unique" fixed my problem. However, I'm still not sure if the current behavior is "right"

**Comment by raducoravu** [comment]
@ruthrapr the DITA 1.3 specification does not cover this exact case in which you refer the same topic multiple times with different navtitle, so there is no right/wrong way of treating this case from the specification's point of view:
https://www.oxygenxml.com/dita/1.3/specs/langRef/base/navtitle.html

**Comment by ruthrapr** [comment]
Yes of course, maybe "expected behavior" is more appropriate

**Comment by chrispy-snps** [comment]
I agree that while the DITA 1.3 specification is silent here, the user expectation is that the specified title should be preserved in each _map_ instance, regardless of whether the topics themselves are duplicated or not.

Using [`ditaot_save_preprocessing.pl`](https://github.com/chrispy-snps/DITA-ditaot-utilities#using-ditaot_save_preprocessingpl), I see that the map is as follows before `move-meta-entries`:

```
<map cascade="merge">
   <title>Test map</title>
   <topicref locktitle="yes" href="test_navtitle.dita" type="topic">
      <topicmeta>
         <navtitle dita-ot:locktitle="yes">Navtitle 1</navtitle>
         <linktext>My Topic</linktext>
      </topicmeta>
   </topicref>
   <topicref locktitle="yes" href="test_navtitle.dita" type="topic">
      <topicmeta>
         <navtitle dita-ot:locktitle="yes">Navtitle 1</navtitle>
         <linktext>My Topic</linktext>
      </topicmeta>
   </topicref>
   <topicref locktitle="yes" href="test_navtitle2.dita" type="topic">
      <topicmeta>
         <navtitle dita-ot:locktitle="yes">Navtitle 3 (using a different href)</navtitle>
         <linktext>My Topic 2</linktext>
      </topicmeta>
   </topicref>
</map>
```

and as follows after `move-meta-entries`:

```
<map cascade="merge">
   <title>Test map</title>
   <topicref locktitle="yes" href="test_navtitle.dita" type="topic">
      <topicmeta>
         <navtitle dita-ot:locktitle="yes">Navtitle 1</navtitle>
         <linktext>My Topic</linktext>
      </topicmeta>
   </topicref>
   <topicref locktitle="yes" href="test_navtitle.dita" type="topic">
      <topicmeta>
         <navtitle dita-ot:locktitle="yes">Navtitle 1</navtitle>
         <linktext>My Topic</linktext>
      </topicmeta>
   </topicref>
   <topicref locktitle="yes" href="test_navtitle2.dita" type="topic">
      <topicmeta>
         <navtitle dita-ot:locktitle="yes">Navtitle 3 (using a different href)</navtitle>
         <linktext>My Topic 2</linktext>
      </topicmeta>
   </topicref>
</map>
```

Is it a bug that the map navigation title is overwritten when `@locktitle`=`yes`? (I have never used `@locktitle` before.)
