### ISSUE TITLE
java.lang.BootstrapMethodError: java.lang.SecurityException: class "net.sf.saxon.s9api.XmlProcessingError"

### ISSUE THREAD

**Issue by stefan-jung** [dita-ot/dita-ot#4294]
## Expected Behavior
A life without errors and exceptions. 🌞🍸 

## Actual Behavior
When using a DITA-OT based Oxygen XML Publishing Engine 3.7.4 on GitHub Action, the build fails in the `mapref` stage. I am not sure, where exactly the SecurityException is thrown, so I am not sure if this exception is related to the core DITA-OT or to the Oxygen XML Publishing Engine.

## Possible Solution
I have no idea.

## Steps to Reproduce
Not sure how to reproduce that in a public environment.

## Copy of the error message, log file or stack trace
```
2023-10-05T10:16:45.6059232Z mapref:
2023-10-05T10:16:45.7411899Z [31mError: java.lang.BootstrapMethodError: java.lang.SecurityException: class "net.sf.saxon.s9api.XmlProcessingError"'s signer information does not match signer information of other classes in the same package[0m
2023-10-05T10:16:45.7614153Z ##[error]Process completed with exit code 1.
2023-10-05T10:16:45.7689578Z Post job cleanup.
```

## Environment

* DITA-OT version: Oxygen XML Publishing Engine 3.7.4
* Operating system and version: GitHub Action (Linux)
* How did you run DITA-OT? GitHub Action calls the `dita` command
* Transformation type: PDF (XSL:FO FOP)

**Comment by raducoravu** [comment]
@stefan-jung can you search in the Oxygen XML Publishing Engine 3.7.4 folder and subfolders for all "*saxon*" library file names and list here where you found them?

**Comment by stefan-jung** [comment]
@raducoravu, sure. It's `SAXON-HE-10.6.jar`. The other two libraries are not on the classpath and do not matter here. This is what is distributed with [oxygen.zip](https://www.oxygenxml.com/InstData/Editor/Windows/VM/oxygen.zip), path is `oxygen\frameworks\dita\DITA-OT3.x\lib\saxon\Saxon-HE-10.6.jar`.

* `dita-ot\lib\saxon\Saxon-HE-10.6.jar` ⬅️ **ONLY THIS ONE IS USED**
* `dita-ot\plugins\com.dometic.oxygen-framework\lib\saxon9.jar`
* `dita-ot\plugins\com.dometic.oxygen-framework\lib\Saxon-HE-10.6.jar`

**Comment by raducoravu** [comment]
@stefan-jung  how about if you just remove those two extra libraries just in case?

**Comment by stefan-jung** [comment]
@raducoravu, I have tested this and it does not make any difference.

**Comment by jelovirt** [comment]
This sounds more like a configuration or installation issue in Oxygen XML Publishing Engine, not in DITA-OT. If so, this should be closed and the issue reported to SyncRO Soft.

**Comment by raducoravu** [comment]
@stefan-jung how about if you run about the same command locally on your local disk using the same Oxygen publishing engine (based on DITA OT 3.7) folder?
