### ISSUE TITLE
HTML output uses removed HTML5 attribute: @compact

### ISSUE THREAD

**Issue by markgif** [dita-ot/dita-ot#4298]
## Expected Behavior
HTML output should use standard HTML markup supported by major browsers. @compact is no longer supported by Chrome, Firefox, Safari, Edge, Opera.

## Actual Behavior
HTML output for html5 and xhtml uses @compact attribute, which was removed from HTML5. It was deprecated in HTML 4 about 20 years ago.

HTML5 spec, section 16.2 Non-conforming features:
https://html.spec.whatwg.org/#non-conforming-features
Paraphrase of the spec:
>The following attributes are obsolete (though the elements are still part of the language), and must not be used by authors:
>compact on dl elements
>compact on menu elements
>compact on ol elements
>compact on ul elements

## Possible Solution
Add a compact value in `@class`, and make the CSS match that?

## Steps to Reproduce
1. In DITA 1.3 XML topic, add @compact to the root element of a list like `<ul>`:
    ```xml
    <ul compact="yes">
        <li>text</li>
    ```
2. Run the html5 or xhtml transtype on it.
3. The HTML output uses @compact.
    html5:
    ```xml
    <ul class="ul" compact>
    ````
    xhtml:
    ```xml
    <ul class="ul" compact="compact">
    ```
    CSS:
    ```css
   *[compact=yes] > li {
    margin-top: 0; }
   *[compact=no] > li {
    margin-top: 0.53em; }
   ```

The Oxygen XML editor gives an error if you open the HTML file:

> The “compact” attribute on the “ul” element is obsolete. Use CSS instead.

## Environment

* DITA-OT version: 4.1.1
* Operating system and version:
Windows 10
* How did you run DITA-OT?
Oxygen GUI
* Transformation type:
html5, xhtml

**Comment by jelovirt** [comment]
The `@compact` is one of those features of DITA that I think is very rarely used. We should replace this with outputting `class="compact"` in HTML5 and XHTML.

**Comment by markgif** [comment]
@compact in DITA XML is still used quite a bit, according to the OASIS DITA TC. @fwegmann asked them. The TC plans to keep @compact in DITA 2.0. But it's long gone in HTML. We've been discussing compact lists in the Lightweight DITA Subcommittee and I discovered this.

**Comment by chrispy-snps** [comment]
Testcase that applies `@compact="yes"` to `<ul>`, `<ol>`, `<sl>`, and `<dl>`: [4298.zip](https://github.com/dita-ot/dita-ot/files/12907024/4298.zip)

**Comment by markgif** [comment]
I have a request on this. Recently in the Lightweight DITA Subcommittee we decided to add the attribute @data-compact to the HTML5 flavor of Lightweight DITA (aka HDITA), instead of adding a fixed `@class` value of `"compact"`. Can we get you to use `@data-compact="yes"` or `@data-compact="no"` instead of the `@class` syntax above?

Example:

HTML5 and HTML5 XML syntax ("XHTML")
`<ul class="ul" data-compact="yes">`

CSS
```
*[data-compact=yes] > li {
margin-top: 0; }
*[data-compact=no] > li {
margin-top: 0.53em; }
```

**Comment by chrispy-snps** [comment]
@jelovirt, @robander - this represents a departure from precedent for capturing element characteristics in the HTML. I think we should discuss it in the next monthly call.

**Comment by markgif** [comment]
I would not mind attending this meeting, can I?
