### ISSUE TITLE
External link with relative path is processing wrongly in xhtml and pdf output

### ISSUE THREAD

**Issue by Roopesh-Navath** [dita-ot/dita-ot#4314]
## Expected Behavior
External link with relative path should treat as an external link

## Actual Behavior
External link with relative path is not processing as an external link but processing as internal link and adding current file path
input: `<xref format="html" href="/documentation/product/us/en/" scope="external"/>`
output:  `<a class="xref" href="file:/C:/workarea/input/sample-book/installing.dita" target="_blank">file:/C:/workarea/input/sample-book/installing.dita</a>`

## Steps to Reproduce

1.create an xref link with relative path and add scope as external <xref format="html" href="/documentation/product/" scope="external"/>
2. add it in a ditamap and publish
3.observe the html output

https://gist.github.com/Roopesh-Navath/7af1b539ac08cdcf8dce96a2d5e9be33
## Copy of the error message, log file or stack trace

```
debug-filter:
   [filter] Using Xerces grammar pool for DTD and schema caching.
   [filter] Processing file:/C:/workarea/input/external-link/installing.dita to file:/C:/workarea/out/darwin/xhtml/temp/installing.dita
   [filter] file:/C:/workarea/input/external-link/installing.dita:12:104: [DOTJ083E][ERROR] The resource referenced as file:/documentation/product/us/en/ is capitalized differently on disk, using file:/C:/documentation/product/us/en.
   [filter] Processing file:/C:/workarea/input/external-link/taskbook.ditamap to file:/C:/workarea/out/darwin/xhtml/temp/taskbook.ditamap
```

## Environment

* DITA-OT version: 4.1.2
* Operating system and version:
  _(Linux, macOS, Windows)_Windows
* How did you run DITA-OT? dita
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type: xhtml, pdf
  _(HTML5, PDF, custom, etc.)_

**Comment by raducoravu** [comment]
Publishing your sample DITA Map to XHTML or HTML5 outputs using DITA OT 4.1.2 without **any** extra installed plugins, the HTML output for that link looks like:
<img width="932" alt="Screenshot 2023-10-26 at 11 42 39" src="https://github.com/dita-ot/dita-ot/assets/1005979/152cb4dd-5b20-4a35-bc90-66f1a23425de">

So I cannot reproduce the problem.
Do you have custom plugins installed in the DITA OT?

**Comment by raducoravu** [comment]
@Roopesh-Navath thanks I will.
