### ISSUE TITLE
dita2markdown Tables are malformatted when cells contain multiple paragraphs or lists

### ISSUE THREAD

**Issue by ol-roboro** [dita-ot/dita-ot#4339]
## Expected Behavior

Tables rendered in a dita2markdown conversion should be well formatted regardless of whether cells contain paragraphs or lists.

## Actual Behavior

Tables with even relatively simple content are rendered in markdown output poorly and often don't conform to general markdown requirements.

For example, the generated markdown output for a table that contains a list, might appear as follows:

```
|Title|Description|
|-------------------------|-----------|
|tools
|Provides a set of useful tools. Useful files under the directory include:

 -   **`wibble`**
...
```

This example illustrates one of many issues with the table formatting that results in a dita2markdown conversion.

## Possible Solution

Perhaps the easiest solution to this problem is to provide an option to render tables in HTML format, which most markdown renderers and parsers respect.

Table formats are notoriously problematic in Markdown, particularly for more complex tables, so providing an option to output tables in HTML format could help work around these problems.

## Environment

* DITA-OT version: 3.6.1 and 4.1.2
* Operating system and version:
  _Linux_
* How did you run DITA-OT?
  _`dita` command_
* Transformation type:
  _markdown_github_ _markdown_gitbook_ _markdown_

**Comment by jelovirt** [comment]
This is a known issue and will likely be implemented in the next LwDITA plug-in version. See https://github.com/jelovirt/org.lwdita/pull/200
