### ISSUE TITLE
markdown2dita: notes in lists

### ISSUE THREAD

**Issue by amyhiggins** [dita-ot/dita-ot#4344]
If I try to add a note to a list item (ordered or unordered list), I receive the following error when building with any output format I try:
> Error: Failed to run pipeline: class com.vladsch.flexmark.ext.admonition.AdmonitionBlock cannot be cast to class com.vladsch.flexmark.ast.ListItem (com.vladsch.flexmark.ext.admonition.AdmonitionBlock and com.vladsch.flexmark.ast.ListItem are in unnamed module of loader java.net.URLClassLoader @eed1f14)

This is the code I've tried:
```
1. First item
2. Second item

    !!! note
        Note about the second item.

3. Third item
```

I can add the note to the bottom of the list for now, but it would be nice if the note could directly follow the list item it's referring to.

**Comment by raducoravu** [comment]
Could you move this issue on the DITA OT plugin project which does the Markdown to DITA conversion:
https://github.com/jelovirt/org.lwdita/issues
?

**Comment by amyhiggins** [comment]
Moved to https://github.com/jelovirt/org.lwdita/issues/204
