### ISSUE TITLE
markdown2dita: superscript link for footnotes doesn't appear

### ISSUE THREAD

**Issue by amyhiggins** [dita-ot/dita-ot#4345]
When I add a footnote in markdown, I can see the generated footnote in the output, but no superscript number or link to the footnote. For example, this markdown:

```
Here's a simple footnote[^1].

[^1]: This is the first footnote.
```

results in (no superscript number or link in main text):

Here's a simple footnote.

----
1\. This is the first footnote.

**Comment by raducoravu** [comment]
Could you move this issue on the DITA OT plugin project which does the Markdown to DITA conversion:
https://github.com/jelovirt/org.lwdita/issues
?

**Comment by amyhiggins** [comment]
Moved to https://github.com/jelovirt/org.lwdita/issues/205
