### ISSUE TITLE
Weird chars should be removed before and after the [move-meta] Fatal Error for messy entities

### ISSUE THREAD

**Issue by stefan-jung** [dita-ot/dita-ot#4363]
## Expected Behavior
Weird chars should be removed before and after the `[move-meta]` Fatal Error for messy entities. Right now, it looks like this on GitHub Actions: `[31m` and `[0m`

024-01-26T07:33:01.4887470Z [move-meta] Processing file:/tmp/abc.dita
2024-01-26T07:33:01.4898097Z [move-meta] Processing file:/tmp/abc.dita
2024-01-26T07:33:01.4905368Z [move-meta] [Fatal Error] abc.dita:180:200: XML document structures must start and end within the same entity.
2024-01-26T07:33:01.4908852Z [31m[move-meta] Failed to read file:/tmp/abc.dita: Failed to parse /tmp/abc.dita:Failed to read document: XML document structures must start and end within the same entity.[0m
2024-01-26T07:33:01.4911474Z [move-meta] Processing file:/tmp/abc.dita
2024-01-26T07:33:01.4916241Z [move-meta] Processing file:/tmp/abc.dita
## Environment

* **DITA-OT version**: 4.1.1
* **Operating system and version**: GitHub Actions/Ubuntu
* **How did you run DITA-OT?** dita command

**Comment by raducoravu** [comment]
You need to run the command line using the " -no-color" flag.

**Comment by raducoravu** [comment]
@infotexture btw I do not see in the docs the "-no-color" cmd line param mentioned anywhere.

**Comment by stefan-jung** [comment]
Thank you @raducoravu.

@infotexture, if you'd like the explain the parameter, it's correct that it has just one prefixed hyphen.

```YAML
run: dita-ot/bin/dita --project=my-docs.xml --verbose -no-color
```

**Comment by stefan-jung** [comment]
https://github.com/dita-ot/docs/pull/525 sent

**Comment by infotexture** [comment]
> I do not see in the docs the "-no-color" cmd line param mentioned anywhere.

Thanks, good catch Radu. 🙏 

We mentioned it in the 3.7 _Release Notes_, but apparently forgot to add it to the main parameter listings:

https://www.dita-ot.org/3.7/release-notes/#v3.7__3741

**Comment by infotexture** [comment]
> if you'd like the explain the parameter, it's correct that it has just one prefixed hyphen

@stefan-jung Actually, both should work. See https://www.dita-ot.org/dev/parameters/dita-command-arguments:

> Note: Most `dita` command options support several syntax alternatives. All options can be specified with a GNU-style option keyword preceded by two hyphens. In many cases, Unix-style single-letter options (preceded by a single hyphen) are also available for brevity and backwards compatibility.

Thanks for the docs PR. Will follow up there with feedback in context.

**Comment by raducoravu** [comment]
Also the choice to use color in the console by default or not is more complex, for Windows for example no color is used.

org.dita.dost.invoker.Arguments.getUseColor()

**Comment by jelovirt** [comment]
Or set `NO_COLOR` system variable.
