### ISSUE TITLE
In `preprocess2`, nested subtopics of a branch-filtered submap are duplicated/unresolved

### ISSUE THREAD

**Issue by chrispy-snps** [dita-ot/dita-ot#4380]
## Expected Behavior
I have a submap that is included under two branch-filtered conditions:

![4380](https://github.com/dita-ot/dita-ot/assets/50950969/ca2ce15c-95ac-4380-a75c-ed8677661f51)

If the submap contains a topic that has nested subtopics, I expect only two HTML topic files in the output directory (the topic filtered for each condition):

```
$ ls -1 out/topic*.html
out/topic-1.html
out/topic.html
```

## Actual Behavior
In the DITA-OT 4.2-prerelease with `preprocess2`, some extra HTML topic files are created:

```
$ ls -1 out/topic*.html
out/topic-1.html
out/topic_2.html
out/topic_3.html
out/topic_4.html
out/topic.html
```

and the index.html file has unresolved references to intermediate hashed file names:

```
<li class="topicref"><a href="topic.html">Product A</a><ul>
   <li class="topicref"><a href="topic.html#subtopic1">Subtopic 1</a></li>
   <li class="topicref"><a href="topic.html#subtopic2">Subtopic 2</a><ul>
      <li class="topicref"><a href="topic.html#subsubtopic">Subtopic 2 Subsubtopic</a></li>
     </ul>
   </li>
   <li class="topicref"><a href="topic.html#subtopic3">Subtopic 3</a></li>
  </ul>
</li>
<li class="topicref"><a href="topic-1.html">Product B</a><ul>
   <li class="topicref"><a href="55c3682f2ff133845b875a9388c32f75b7f6cc30.html#subtopic1">Subtopic 1</a></li>
   <li class="topicref"><a href="d036779dc064ca9c0ce4724f24595e8db49f56c2.html#subtopic2">Subtopic 2</a><ul>
      <li class="topicref"><a href="d036779dc064ca9c0ce4724f24595e8db49f56c2.html#subsubtopic">Subtopic 2 Subsubtopic</a></li>
     </ul>
   </li>
   <li class="topicref"><a href="bdeab86701dd30ef2d48b7db2cf6097220a24287.html#subtopic3">Subtopic 3</a></li>
  </ul>
</li>
```

## Possible Solution
Not sure.

## Steps to Reproduce
1. Download and extract the following testcase:
   [4380.zip](https://github.com/dita-ot/dita-ot/files/14133058/4380.zip)
1. Run the following command:
   `dita -i map.ditamap -f html5 -Dforce-unique=true`

## Environment
* DITA-OT version: 4.2-prerelease
* Operating system and version: Linux
* How did you run DITA-OT? `dita` command
* Transformation type: HTML5

**Comment by jelovirt** [comment]
The key here is `force-unique` use with branch filtering.

**Comment by chrispy-snps** [comment]
Can the priority for this be raised? It is a blocking issue for our content.

**Comment by chrispy-snps** [comment]
I confirmed the fix for this on our production content - thank you!

During testing, I found another issue and filed #4429.
