### ISSUE TITLE
Better mark validation error in topic

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4406]
If I have an invalid ID in a topic:

```xml
<topic id="%50">
```

I will get in the console output something like this:

```
file:../flowers/topics/introduction.dita:3:17: Attribute value "%50" of type ID must be an NCName when namespaces are enabled.
```
so the error line is not marked with an `[ERROR]` tag.

**Comment by jelovirt** [comment]
Which DITA-OT version and how was it run. If I mock a test case like that and run it with 4.2 on the command line, I get

```
Error: file:/Volumes/tmp/src/topic.dita:3:17: Attribute value "%50" of type ID must be an NCName when namespaces are enabled.
```

**Comment by jelovirt** [comment]
The message content comes from SAXException thrown by the XML parser. In order to get some message ID to the message, we could add a generic parsing message that doens't have a `<reason>` other than the message text from the XML parser.

**Comment by raducoravu** [comment]
So if I run DITA OT 4.2 on Windows on a DITA Map which contains a topic like this:

```
<?xml version='1.0' encoding='UTF-8'?>
 <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd"> 
<topic id="%50">     
<title>Introduction</title> 
</topic> 
```

the command line I run and the error look like this (notice no [Error:] marker before the reported error):
```
"C:\Users\radu_coravu\Downloads\dita-ot-4.2/bin/dita.bat" -f html5 -o D:\samples\dita\flowers/out/html5 -t D:\samples\dita\flowers/temp/html5 -i D:\samples\dita\flowers\flowers.ditamap
file:/D:/samples/dita/flowers/topics/introduction.dita:3:17: Attribute value "%50" of type ID must be an NCName when namespaces are enabled.
```

**Comment by raducoravu** [comment]
On Mac OS indeed there is an "Error:" marker with a red foreground.

**Comment by jelovirt** [comment]
Ok, so this is a case where on Windows the CLI doesn't use colours in the log and the prefix is missing. I'll open a PR to make sure the prefixes are output on Windows too.

**Comment by raducoravu** [comment]
@jelovirt yes, also when the -no-colors flag is used the prefix should be output as well.
