### ISSUE TITLE
Echo current deliverable in non-verbose mode

### ISSUE THREAD

**Issue by stefan-jung** [dita-ot/dita-ot#4451]
## Description
I'm building hundreds of deliverables in a batch on GitHub Actions. So far I am publishing with `--verbose`, which leads to huge log files. My log files have exceeded now a size of 50 MB (for a plaintext file!). Now I am getting difficulties to parse it. The idea was to turn-off the `--verbose` mode.

The problem now is, that the context is now missint in the log. I do not know what deliverable has thrown what error. What I am missing are these lines:

```
Publishing deliverable 67 of 159: NAME OF DELIVERABLE [id-of-deliverable]
```

## Possible Solution
Add these lines to non-verbose logging.

## Potential Alternatives
None

**Comment by chrispy-snps** [comment]
Currently, #4100 (not yet merged) only issues deliverable messages in verbose mode. Like you, I would also like to see deliverable messages in non-verbose mode too. This is for two reasons:

* Publishing multiple deliverables tends to have a longer runtime and thus is more deserving of a status indicator.
* The deliverable messages provide context for errors that occur.

**Comment by stefan-jung** [comment]
Closing this as a duplicate of https://github.com/dita-ot/dita-ot/issues/3948.
