### ISSUE TITLE
xref link to a list is not working when the topic is used as conref in another topic and published with transtype xhtml

### ISSUE THREAD

**Issue by Roopesh-Navath** [dita-ot/dita-ot#4472]
## Expected Behavior
xref link should work as a normal link

## Actual Behavior
link is broken due to the wrong xref id generated 

## Possible Solution
xref id should be generated using the target element id

## Steps to Reproduce

1.create a bookmap, keymap and 2 topics and use one topic inside bookmap and use other one as conref inside another topic
2. add ul list with specific id and link this list using xref in the same topic
3. use this topic as conref in another topic
4. publish xhtml and observe the link
5. link is broken 

ouptut html
  ```
<p class="p">link to topic 1 list <a class="xref" href="#id_mjp_kh5_hbc__d36e25">#id_mjp_kh5_hbc__d36e25</a>
                    </p>
                    <ul class="ul" id="id_mjp_kh5_hbc__ul-list">
                        <li class="li">
                            <p class="p">topic 1 list item</p>
                        </li>
                        <li class="li">
                            <p class="p">topic 1 list item 2</p>
                        </li>
                    </ul>
```

[sample-code](https://gist.github.com/Roopesh-Navath/749721a05e224725413509f11c0e4553)

## Copy of the error message, log file or stack trace
[log](https://gist.github.com/Roopesh-Navath/26b53a3dba7fb8fd5590876246ff3341)

## Environment

* DITA-OT version: 4.2.2
* Operating system and version:Windows
  _(Linux, macOS, Windows)_
* How did you run DITA-OT? : dita 
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type:
  _(HTML5, PDF, custom, etc.)_xhtml

**Comment by raducoravu** [comment]
In such cases the link href should be "#./ul-list"

https://www.oxygenxml.com/dita/1.3/specs/archSpec/base/uri-based-addressing.html#uri-based-addressing__topics-with-uri
