### ISSUE TITLE
[Feature Request] Exit Codes on Erroring Execution

### ISSUE THREAD

**Issue by rrcomtech** [dita-ot/dita-ot#4495]
## Description
I am running DITA OT as part of my CI. It builds my documents to test if a PR is liable to be merged. Sadly, when a link breaks, DITA OT notifies me in the logs, but it does not return a non-zero exit code. That causes my CI to pass, even if DITA OT actually has errors. 

## Possible Solution
Return a non-zero exit code, if there are errors in the logs.

## Potential Alternatives
Provide a flag that allows me to tell DITA to return a non-zero exit code if errors occurr in the logs.

**Comment by jelovirt** [comment]
Have you tried using [`processing-mode`](https://www.dita-ot.org/dev/parameters/parameters-base#base__processing-mode) with value `strict` to make the processing fail on errors?

**Comment by rrcomtech** [comment]
Yes, that fixed it! Thank you very much :)
