### ISSUE TITLE
Cannot use copy-to topics in reltable

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#4534]
## Expected Behavior
The copied-to topic should be present in the output directory and should have a link to the task.

## Actual Behavior
The copied-to topic doesn't exist and some errors appear in console.

## Steps to Reproduce
Run the following command with the attached files: `dita -v -f html5 -i /path/to/map.ditamap -o /path/to/out`
[reltable.zip](https://github.com/user-attachments/files/17658901/reltable.zip)

```xml
<topicref href="topic.dita" copy-to="topic2.dita"/>
<reltable>
    <relrow>
        <relcell>
            <topicref href="topic2.dita"/>
        </relcell>
    </relrow>
</reltable>
```
## Copy of the error message, log file or stack trace
```
Error: [DOTX008E] The resource 'file:/D:/support/_forum/Stacey/topic2.dita' cannot be loaded. Make sure 'file:/D:/support/_forum/Stacey/topic2.dita' exists and that you have permission to access it.
```

## Environment
* DITA-OT version: 4.2.3
* Operating system and version: Windows
* How did you run DITA-OT? `dita` command, oXygen
* Transformation type: HTML5

**Comment by jelovirt** [comment]
I'm not sure this is a bug. I think the source should be

```xml
<topicref href="topic.dita" copy-to="topic2.dita"/>
<reltable>
    <relrow>
        <relcell>
            <topicref href="topic.dita" copy-to="topic2.dita"/>
        </relcell>
    </relrow>
</reltable>
```

Because the map should reference files that exist in the source, not ones that will exist in the output.

The implementation does seem to have some bugs related to `index.html` generation, but IMO this exact case is not a bug.

**Comment by jlacour31** [comment]
You're right! If I add the copy-to attribute into the reltable I get the links correctly:
```
<map>
    <title>Map</title>
    <topicref href="topic.dita"/>
    <topicref href="task.dita"/>
    <topicref href="topic.dita" copy-to="topic2.dita"/>
    <reltable>
        <relheader>
            <relcolspec type="topic"/>
            <relcolspec type="task"/>
        </relheader>
        <relrow>
            <relcell>
                <topicref href="topic.dita"/>
                <topicref href="topic.dita" copy-to="topic2.dita"/>
            </relcell>
            <relcell>
                <topicref href="task.dita"/>
            </relcell>
        </relrow>
    </reltable>
</map>
```
Thanks, I didn't knew about the possibility to use copy-to into reltables.
